add zabbix template.get function
saltstack/salt pull request #36291
Opened 2016-09-14 12:17 UTC by mchugh19

### What does this PR do?
Adds support for querying Zabbix templates through the template.get API

### What issues does this PR fix or reference?
None

### New Behavior
Allows querying Zabbix templates:
```
salt '*' zabbix.template_get name='Template OS Linux'
salt '*' zabbix.template_get host='Template OS Linux'
salt '*' zabbix.template_get templateids="['10050', '10001']"
salt '*' zabbix.template_get              #returns all templates
```

### Tests written?
No

2016-09-17 10:40 UTC, cachedout commented on salt/modules/zabbix.py
> +            if 'name':
`if name:`

Please remove the quotes. Otherwise it always returns True because it just checks the existence of the defined string.

2016-09-17 10:41 UTC, cachedout commented on salt/modules/zabbix.py
> +            if 'host':
`if host:`

2016-09-17 10:41 UTC, cachedout commented on salt/modules/zabbix.py
> +            if 'templateids':
`if templateids:`

2016-09-17 10:41 UTC, cachedout requested changes

2016-09-17 14:59 UTC, mchugh19 commented
Right you are, corrected. Thanks!

2016-09-18 01:31 UTC, cachedout approved these changes
Much better. This looks ready to go!

2016-09-18 01:31 UTC, merged

2016-09-18 01:32 UTC, cachedout commented
Many thanks for this, @mchugh19. We really appreciate it!