Automate module downloading from salt-master
saltstack/salt pull request #36625
Opened 2016-09-28 03:50 UTC by bllackeye

### What does this PR do?

Automate module downloading into salt-minion. 

### What issues does this PR fix or reference?

### Previous Behavior
In order to distribute  custom modules to minions, users have to run saltutils.sync_modules to inform concerned minions to pull modules from salt-master.  

If the custom module to run is not synchronised to the minion and loaded into memory,  salt-minion throws exception. 

### New Behavior
Upon receiving a message, the targeted salt minion will check the readiness of the module to run. If the concerned module is not ready, the targeted salt minion automatically tries to sync modules into the minion and loads them before trying to run the modules. 

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

1) before invoke a function, the minion check the readyness of the
function.
2) the minion will try to download modules and load the modules if the
required module is not ready.

2016-09-28 05:32 UTC, cachedout commented
Hi @bllackeye 

Thanks for taking the time to write this and contribute it. There are a number of issues, unfortunately.

First, it's syntactically incorrect. The indentation under the `_check_moduleReadyness` is not correct and the minion doesn't even start with the code you've provided. Secondly, the entire function is created as an inner function to `_handle_decoded_payload` instead of being a method of the `Minion` class. There are a number of smaller implementation issues as well.

More importantly, I really don't think this behavior is something we want to put into Salt by default. It creates unnecessary overhead in a performance-sensitive part of the design just to handle rare cases where an automatic module sync is desirable. The choice to make module synchronization operations explicit one was very intentional. Also, this _only_handles cases where the module that's called is not present and not cases where the module is cross-called so, in effect, it only handles the case where somebody could have just as easily done a sync before this. Moreover, in cases where the module doesn't exist on the master either, this just creates unnecessary work for both the master and the minion since the module will never be found and synced.

Regarding your case that master publications are unreliable, I'd have to understand why you believe the request step, which is many-to-one from minions to master would be more reliable than the one-to-many publication step. This could be true in cases where a minion for some reason didn't receive the sync command and it's the only one asking for an update but I think that most of the time this code gets his will be when _all_ minions are syncing.

We're certainly willing to discuss this one more and I welcome your feedback but as it sits, this isn't something we can merge right now.

2016-09-28 05:35 UTC, damon-atkins commented
_check_moduleReadyness   I would have thought this should be  _check_module_readyness

2016-09-28 05:52 UTC, damon-atkins commented
Could changing the output from saltutil.sync_* resolve this.
Or  saltutil.sync_*  creates a flag file and salt cmd prints a warning the last sync for ? failed, until saltutil.sync_* is successfull and clears the flag.

2016-09-28 05:56 UTC, cachedout commented
@damon-atkins We could explore those options but I am extremely hesitant to go down this path. I don't personally believe that Salt should automate module sync in any fashion. I'm always up for a discussion though. :]

2016-09-28 06:17 UTC, bllackeye commented
Hi, @cachedout 

Thanks for your comments, it is my bad not to do the syntax check, because the function was copy from other working code( it is 2015.5 too, but looks quite different). 

Intuitively, checking the function_name from minion_instance.functions is the only workload introduced every time, for which I think it is trivial. But I have to admit that I am not 100% sure, as I am an newbie  to python.

The reason I'd like to introduce this capability is that I regularly run into this issue in one of my projects, Sometime, the massage simple got lost, or the minion received the message but will wait for a while before it really run saltutils.sync_modules, yes, saltutils.sync_module is invoked from minion instead of salt-master 'push the modules' to minions.  Because we are using a lot custom modules, so I have to figure out one way to reliably deliver the modules to minions. One of way I tried was sync the module then query the status, which I think even more expensive because it introduces more work to salt-master which is the real bottleneck. 

As far as performance is concerned, I strongly believe that salt-master is the potential bottleneck, and the solution I proposed here at least avoid one round of  traffic though it does introduce a little bit workload on the minion. 

Finally, I'd like to thank your guys for your comments and responsiveness. I think this is why open source becomes so perspective.  

Bllackeye

2016-09-28 07:02 UTC, damon-atkins commented
> Sometime, the massage simple got lost, or the minion received the message but will wait for a while before it really run saltutils.sync_modules, yes, saltutils.sync_module is invoked from minion instead of salt-master 'push the modules' to minions.
Sounds like you should log an issue for this, or upgrade to 2016.3.x to see if its better

2016-09-28 07:23 UTC, bllackeye commented
Hi, @damon-atkins 

Well, I thought losing message occasionally  is the cost we have to pay for high scalability.

2016-09-28 07:25 UTC, cachedout commented
@bllackeye Could you give us an idea of the approximate number of minions attached to your master? It's not normal for publications to just go missing unless a minion truly isn't connected.

2016-09-28 08:27 UTC, bllackeye commented
Hi, 
My application scenario is like this, 1) spawn a virtual machine in a private cloud, and install a salt-minion. 2) try to run a custom module from the minion. I don't have too many salt-minions in my dev environment, just a dozen of them.   The issues described in the last post were observed with salt-debug. 

I spent sometime to google the solutions to those problems. I could find someone complained about module sync issues.

2016-09-28 08:36 UTC, damon-atkins commented
Replace 2 with using reactor to kick off the salt sync and high state. This way you know the connection has been made before the salt commands are run.  You could be hitting a timing issue.

2016-09-28 08:50 UTC, s0undt3ch requested changes

2016-09-28 08:50 UTC, s0undt3ch commented on salt/minion.py
> +     def _check_moduleReadyness(self,function_name, minion_instance):
Please, no camel case, underscores to split words is preferable.

2016-09-28 08:50 UTC, s0undt3ch commented on salt/minion.py
> +                       break;
And this semicolon doesn't belong in python ;)

2016-09-28 08:50 UTC, s0undt3ch commented on salt/minion.py
> +        minion_instance._check_moduleReadyness(function_name,minion_instance)
One space after comma please.

2016-09-28 08:50 UTC, s0undt3ch commented on salt/minion.py
> +            minion_instance._check_moduleReadyness(data['fun'][ind],minion_instance)
One space after comma please.

2016-09-28 10:40 UTC, bllackeye commented on salt/minion.py
> +            minion_instance._check_moduleReadyness(data['fun'][ind],minion_instance)
@s0undt3ch  thank you for pointing out the problems.

2016-09-29 15:07 UTC, thatch45 commented
I am having a hard time with this one. I think it is a good idea  to auto sync, but this does mean that a typo will auto sync a ton of minions. For instance if you ran salt \* test.pong you would have a sync stampeed.

Also, we just can't bring a change like this into a point release branch, this would have to go on develop

Next, since this is in the main minion loop it would block the minion, so no other commands would get to the minion and get executed while the sync was happening. The right approach here would to call an execution function that would run in another process and subsequently call the freshly synced module/function once the sync is complete.

This should also be config gated and defaulted to being turned off.

2016-09-30 01:03 UTC, bllackeye commented
Hi @thatch45 

Point taken, I will stop here. Should I do anything to rollback?

2016-09-30 06:01 UTC, damon-atkins commented
I think the flag file on the master is a better way to go?  It would be informative but would not create any load...

2016-09-30 07:07 UTC, bllackeye commented
I kind of agree that the proposed approach favourites the use cases where there  are a lot of custom modules to run. 

For example, I would like to run mymodule.myfunction, and I know it is not a standard module, but I am not sure whether this module has been downloaded into the target minions. (This is a very typical scenario in a dynamic environment, new machine spawned now and then) 

So I would like to do salt 'expr' saltutils.sync_modules first, then run salt 'expr' mymodule.myfunction, this will make all minions referred by expr to do the sync and introduce all the trouble mentioned by @thatch45. 

It will be even better if a -F switch can be introduced, something like salt -F 'expr'  mymodule.myfunction to tell minions to automatically download mymodule if it is not there,

2016-09-30 07:41 UTC, bllackeye commented
Hi @cachedout 

Got it, thank you for clearing things up.

2016-10-18 03:11 UTC, cachedout commented
@bllackeye Since it looks like we're not going to go in this direction, I'm going to go ahead and close this. Thanks again for the effort here and the good discussion. We really appreciate it. :]

2016-10-18 03:11 UTC, closed without merging