Adding a get_fqdn method to the network module
saltstack/salt pull request #36732
Opened 2016-10-01 04:44 UTC by cmclaughlin

### What does this PR do?

Adds a `get_fqdn` to the network module - allowing quick and easy lookup of a host's fully qualified domain name.

### What issues does this PR fix or reference?
Did a quick search, didn't find any.

### Tests written?

No (it's super simple code though)

2016-10-01 09:39 UTC, cachedout requested changes

2016-10-01 09:39 UTC, cachedout commented on salt/modules/network.py
> +    from socket import getfqdn
We already have `socket` imported so there is no need for this line. You can remove it and change the line below to `return socket.getfqdn()`.

2016-10-01 22:21 UTC, cmclaughlin commented on salt/modules/network.py
> +    from socket import getfqdn
Done... this was copy-pasta from get_hostname()... so I applied your suggestion there too.

2016-10-03 11:41 UTC, cachedout commented on salt/modules/network.py
> +    from socket import getfqdn
Great! Thank you!

2016-10-03 11:42 UTC, merged