Update topics/grains doco, about considerations before adding a Grain
saltstack/salt pull request #37028
Opened 2016-10-15 14:20 UTC by damon-atkins

### What does this PR do?
topics/grains regarding consideration to take into effect before adding a grain.

### What issues does this PR fix or reference?
Helps people understand when a grain should be created and what to place in it.

### Previous Behavior
Not Clear

### New Behavior
A bit clearer

2016-10-16 16:04 UTC, terminalmage requested changes

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +Consider adding Gains when the information is needed for targeting,
Misspelling and unnecessary capitalization. Also this sentence needs to be improved, or split into two sentences. As one sentence, it doesn't make much sense.

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +or applications. Most of the time execution module called from a JINJA template
"jinja" should not be all capitals.

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +structure can be named and design to support many platforms, operating systems
Did you mean "named and designed"?

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +or applications. Most of the time execution module called from a JINJA template
"Most of the time execution module" ?

Maybe "Most of the time, an execution module" would be better.

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +idea for a Grain would should be developed as a execution module rather than a
Unnecessary capitalization.

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +Gain or a combination of both keeping minimum grain data.
Misspelling and unnecessary capitalization.

2016-10-16 16:04 UTC, terminalmage commented on doc/topics/grains/index.rst
> +will provide the necessary detail information for a Salt State. Consider if your
We try to avoid 2nd-person pronouns in our documentation where possible.

2016-10-17 09:54 UTC, merged

2016-10-17 09:54 UTC, cachedout commented
Thank you, @damon-atkins