Implement `status.uptime` on macOS
saltstack/salt pull request #37157
Opened 2016-10-21 21:42 UTC by jfindlay

### What does this PR do?
Implement `status.uptime` on macOS

### What issues does this PR fix or reference?

### Tests written?

Yes

2016-10-24 03:15 UTC, cachedout commented
Go Go Jenkins!

2016-10-24 09:56 UTC, isbm requested changes
@jfindlay please look at these.

2016-10-24 09:56 UTC, isbm commented on salt/modules/status.py
> +        seconds = float(__salt__['cmd.shell'](cmd, output_loglevel='trace').strip() or 0)
On Solaris, with `kstat` you will always get an integer, no need to `float` here.

2016-10-24 09:56 UTC, isbm commented on salt/modules/status.py
> +        usec = usec_data.split('usec = ')[1]
I would not do that and suggest something more reliable, although probably less readable:
```python
data = bt_data.split("{")[-1].split("}")[0].strip().replace(' ', '')
uptime = dict([(k_sec, int(v_sec,))
                for k_sec, v_sec in [pair.strip().split("=")
                                     for pair in data.split(",")]])
```
What you do here is to turn mac returned data into a dictionary, and refer to it something like:
```python
uptime['usec']
uptime['sec']
```

You can turn the above to a lambda and also query sleep time etc.

2016-10-24 09:56 UTC, isbm commented on salt/modules/status.py
> +        seconds = curr_seconds - float(sec + '.' + '{0:0>6}'.format(usec))
BTW, Mac is also only an integer, no floats there. :smiley:

2016-10-24 09:58 UTC, isbm commented
@cachedout please hold a moment. :smile:

2016-10-24 09:59 UTC, cachedout commented
@isbm Will do. :]

2016-10-24 20:56 UTC, isbm commented
@jfindlay two more to go. :-)

2016-10-26 01:54 UTC, cachedout commented
@jfindlay Could you please let me know where you are with this one?

2016-10-27 06:32 UTC, cachedout commented
Because there has been no response, I am closing this. @jfindlay when you are ready to go here please re-open it.

2016-10-27 17:03 UTC, isbm requested changes
@jfindlay Thanks for the update! Could you please still look at this one?

2016-10-27 17:03 UTC, isbm commented on salt/modules/status.py
> +        seconds = int(curr_seconds - int(sec_data.split('sec = ')[1]))
@jfindlay If you could use my previous suggestion, we by now would also have sleep time of Mac!

2016-10-27 17:04 UTC, isbm commented on salt/modules/status.py
> +        seconds = int(curr_seconds - int(sec_data.split('sec = ')[1]))
Specifically:
```python
data = bt_data.split("{")[-1].split("}")[0].strip().replace(' ', '')
uptime = dict([(k_sec, int(v_sec,))
                for k_sec, v_sec in [pair.strip().split("=")
                                     for pair in data.split(",")]])
```
What you do here is to turn mac returned data into a dictionary, and refer to it something like:
```python
uptime['usec']
uptime['sec']
```

You can turn the above to a lambda and also query sleep time etc.

2016-10-27 17:38 UTC, isbm commented on salt/modules/status.py
> +        seconds = int(curr_seconds - int(sec_data.split('sec = ')[1]))
Point is, you could reuse it and get also other values from the `sysctl`, such as "sleeptime" or "waketime". That said, you could turn the code above to a `def _internal_function(data)` and reuse it.

2016-10-27 17:44 UTC, jfindlay commented on salt/modules/status.py
> +        seconds = int(curr_seconds - int(sec_data.split('sec = ')[1]))
@isbm, you're welcome to open a pull request on my branch, `https://github.com/jfindlay/salt/compare/mac_time...isbm:mac_time`.

2016-10-27 17:50 UTC, isbm commented on salt/modules/status.py
> +        seconds = int(curr_seconds - int(sec_data.split('sec = ')[1]))
Ah, but that's easy:
```python
def _parse_sysctl(data):
    data = data.split("{")[-1].split("}")[0].strip().replace(' ', '')
    return dict([(k_sec, int(v_sec,))
                    for k_sec, v_sec in [pair.strip().split("=")
                                         for pair in data.split(",")]])

...
seconds = int(curr_seconds - _parse_sysctl(bt_data)['sec'])
```

At the moment I don't have Salt installed on OSX.

2016-10-29 18:55 UTC, isbm commented
@jfindlay @cachedout I find https://github.com/saltstack/salt/pull/37321 superseding this one. Maybe it would be possible to collaborate with @sjorge ? He did really awesome job.

2016-10-29 21:33 UTC, sjorge commented
@isbm ooh I did not know there was a sysctl module, merging stuff now, OSX == FreeBSD it seems.

So we have 4 big buckets: Linux, SunOS, FreeBSD+OSX, OpenBSD+NetBSD... let me try and fold @jfindlay stuff inside mine

2016-10-31 07:11 UTC, cachedout commented
I'm fine with using the PR from @sjorge if that's what's agreed on. Any objection, @jfindlay ?

2016-10-31 16:31 UTC, jfindlay commented
@cachedout, none from me. Excellent job everyone.

2016-10-31 16:31 UTC, closed without merging