don't pull image in dockerng.running if test=true
saltstack/salt pull request #37198
Opened 2016-10-24 20:39 UTC by t2b

### What does this PR do?
prevent state dockerng.unning from actually pulling docker image if run with test=true

### What issues does this PR fix or reference?
fixes #36587 

### Previous Behavior
dockerng.running pulls the image if it is not present

### New Behavior
don't pull the image if test=true and return an appropriate comment

### Tests written?
No

2016-10-25 04:33 UTC, cachedout commented
@ticosax Any thoughts?

2016-10-25 08:03 UTC, ticosax requested changes
It is going in the right direction, but it needs more work for completeness.

2016-10-25 08:03 UTC, ticosax commented on salt/states/dockerng.py
> +            return ret
I believe you shouldn't return so early, as other actions are expected from `dockerng.running` state once the image is pulled.

2016-10-25 12:28 UTC, t2b commented
i can return later, but some later actions require a present image or exception will appear. i can try to catch these exceptions and return appropriate comments.

2016-10-25 13:30 UTC, ticosax commented
Just do what you think will be useful and not too disruptive for normal operations. I will not be picky with this pull request.

2016-10-25 19:59 UTC, t2b commented
i have update my branch. i don't return early now, and the comment is more specific.

if you are running a container 'redis' based on the image 'redis:3.0' and change the state to use the image 'redis:3.2' the comment will be:
`Image 'redis:3.2' will be pulled. Container 'redis' will be replaced`

the new commit includes my changes from pull request #37199

2016-10-25 20:32 UTC, ticosax commented on salt/states/dockerng.py
> +        image_id = None
here I suggest something like
```python
if not __opts__['test']:
    raise
```
To not break existing behavior

2016-10-25 22:00 UTC, ticosax approved these changes
well done

2016-10-27 06:30 UTC, cachedout commented
Thank you @t2b and thanks as always to @ticosax as well.

2016-10-27 06:30 UTC, merged