Get cluster gh
saltstack/salt pull request #37310
Opened 2016-10-28 16:16 UTC by alexbleotu

### What does this PR do?

Added utils.vmware.get_cluster
- retrieves a cluster in a datacenter based on its name

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2016-10-31 07:07 UTC, cachedout requested changes

2016-10-31 07:07 UTC, cachedout commented on tests/unit/utils/vmware_test/cluster_test.py
> +                    res = vmware.get_cluster(self.mock_dc, 'fake_cluster2')
This indentation looks like it might be wrong.

2016-10-31 08:11 UTC, alexbleotu commented
Yep saw that. Will fix when I get in the office.

On 31 Oct 2016 07:07, "Mike Place" <notifications@github.com> wrote:

> *@cachedout* requested changes on this pull request.
> ------------------------------
>
> In tests/unit/utils/vmware_test/cluster_test.py
> <https://github.com/saltstack/salt/pull/37310#pullrequestreview-6393006>:
>
> > +        with patch('salt.utils.vmware.get_managed_object_name',
> +                   MagicMock(return_value='fake_dc')):
> +            with patch('salt.utils.vmware.get_mors_with_properties',
> +                       MagicMock(return_value=self.mock_entries)):
> +                with self.assertRaises(VMwareObjectRetrievalError) as excinfo:
> +                    vmware.get_cluster(self.mock_dc, 'fake_cluster')
> +        self.assertEqual(excinfo.exception.strerror,
> +                         'Cluster \'fake_cluster\' was not found in '
> +                         'datacenter \'fake_dc\'')
> +
> +    def test_cluster_found(self):
> +        with patch('salt.utils.vmware.get_managed_object_name',
> +                   MagicMock(return_value='fake_dc')):
> +            with patch('salt.utils.vmware.get_mors_with_properties',
> +                       MagicMock(return_value=self.mock_entries)):
> +                    res = vmware.get_cluster(self.mock_dc, 'fake_cluster2')
>
> This indentation looks like it might be wrong.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/37310#pullrequestreview-6393006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQOKgcUIkrByABg7Hi6JzSxjiUs6FUTaks5q5ZPDgaJpZM4Kjm__>
> .
>

2016-10-31 16:39 UTC, alexbleotu commented
All fixed

2016-10-31 22:46 UTC, alexbleotu commented
@cachedout You were right, the timeout increase did not fix the zeromq test... It needs more investigation

2016-11-01 13:32 UTC, alexbleotu commented
any further issues?

2016-11-02 12:01 UTC, alexbleotu commented
@rallytime Tests failing nothing to do with my code. Can you please merge it in so I can rebase the other pull request

2016-11-02 14:28 UTC, merged