Add grains for the cloud metadata server
saltstack/salt pull request #37649
Opened 2016-11-11 19:31 UTC by gtmanfred

### What does this PR do?

My understanding is that this should always appear at 169.254.169.254.

This is specifically used with ec2 and openstack, and possible some
other cloud providers, but this format should work for the two I know
of.

### What issues does this PR fix or reference?

Closes #37436

2016-11-11 19:32 UTC, gtmanfred commented
@techhat can you take a look at this? I attempted to use `http.query` for this but it kept giving me an error that the Name was not able to be found.  I think this is because it has to use an ip address.

Thanks!
Daniel

2016-11-12 21:13 UTC, cachedout requested changes

2016-11-12 21:13 UTC, cachedout commented on salt/grains/metadata.py
> +"""
Our style guide specifies single-quotes, please

2016-11-14 03:28 UTC, cachedout commented
Go Go Jenkins!

2016-11-14 03:35 UTC, gtmanfred commented
I will get to the single quotes in the morning.
On Sun, Nov 13, 2016 at 9:28 PM Mike Place <notifications@github.com> wrote:

> Go Go Jenkins!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/37649#issuecomment-260240817>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoQp2h5kbexGZDGV0xCwVYv6Y1AWMks5q99VJgaJpZM4KwEGR>
> .
>

2016-11-15 07:02 UTC, merged