ldap external_auth groups fix for auth.ldap.groupclass option
saltstack/salt pull request #38293
Opened 2016-12-15 22:30 UTC by stephentrooly

### What does this PR do?
allows for `auth.ldap.groupclass: posixGroup` or `auth.ldap.groupclass: person` style of group class for ldap servers that do not have 'memberOf' overlay enabled

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/38259

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2016-12-19 14:37 UTC, cachedout commented
@cro Could you please look at this?

2016-12-22 20:05 UTC, cro commented
Go Go Jenkins!

2016-12-22 20:10 UTC, cro requested changes
This should work fine.

@stephentrooly would you mind documenting what's going on here in `salt/doc/topics/eauth.rst`?

2016-12-28 19:40 UTC, cachedout commented
@cro Is this all ready to go from your end?

2017-01-04 20:23 UTC, merged

2017-01-04 20:23 UTC, cachedout commented
Spoke with @cro who will do a docs PR as a follow-up.