Fix issue #38517, added time.sleep(1) at line 227 in slack.py
saltstack/salt pull request #38520
Opened 2017-01-02 16:17 UTC by basdusee

There is a bug in the Slack engine which creates a high CPU load.
There needs to be a time.sleep(1) statement in the while True loop.

### What does this PR do?
It adds one line of code, "time.sleep(1)", to prevent high CPU usage.

### What issues does this PR fix or reference?
Issue #38517 

### Previous Behavior
100% CPU load (or core load in a multicore system) when using Slack.py Engine.

### New Behavior
CPU load is normal, small delay in functionality when using "!" commands in Slack.

### Tests written?
No

2017-01-04 17:42 UTC, cachedout commented
Go Go Jenkins!

2017-01-04 18:46 UTC, cachedout requested changes

2017-01-04 18:46 UTC, cachedout commented on salt/engines/slack.py
> +            time.sleep(1)
This indentation level doesn't line up. Could you adjust it to align with the instructions in the block that you want to be executed? Thanks.

2017-01-05 10:26 UTC, basdusee commented on salt/engines/slack.py
> +            time.sleep(1)
That's weird, should be ok. "while True:" is at position 9, so "time.sleep(1)" should be at position 13, same level as the for-loop.
Maybe it's not all spaces as lineout characters. I re-indented the time.sleep(1) and checked it again for weird whitespaces. Should be fine now.

2017-01-05 15:23 UTC, basdusee commented on salt/engines/slack.py
> +            time.sleep(1)
Checked it again, it was some weird Unicode foobar. Copy-paste related problems. It's fixed in e3a883c... commit.

2017-01-05 20:35 UTC, merged