Add mysql file handling to mysql module and state
saltstack/salt pull request #38561
Opened 2017-01-04 18:05 UTC by mchugh19

This is an attempt to work around the issues described in https://groups.google.com/forum/#!topic/salt-users/Zc4D7NN5RKQ

In short, many salt states rely on the mysql.create_db state, but then install the mysql client in order to populate the database. This overcomplicates the state handling as the mysql client package name must now be tracked for every state doing this behavior and is unusable in an environment not directly connected to the internet. 

### What does this PR do?
This pull request attempts to solve this issue by extending the mysql module with a file_query function where it attempts to read a sql file and run a query for each statement up until the trailing ; and ignores -- comments. In order to detect errors from the mysql module, it also modifies the standard query behavior to return False on error instead of an empty dict. This will cause all mysql processing to stop on any error, which I would think is the expected behavior. 

It also adds a run_file state allowing for use such as:
```
import_schema:
  mysql_query.run_file:
    - database: some_db
    - query_file: /tmp/schema.sql
```

With resulting output:
```
local:
----------
          ID: import_schema
    Function: mysql_query.run_file
      Result: True
     Comment: {'rows affected': 1L, 'query time': {'raw': 21.2241, 'human': '21.22s'}}
     Started: 17:36:00.136384
    Duration: 23852.153 ms
     Changes:
              ----------
              query:
                  Executed
```

### Tests written?
No

2017-01-04 19:04 UTC, cachedout commented
@mchugh19 Very nice. There are a few lint errors here that we need to have cleaned up before we can get this in. I would also like @gtmanfred to have a look at this.

2017-01-04 19:22 UTC, gtmanfred requested changes
Other than the one change.  The rest of this looks solid.

Thanks!

2017-01-04 19:22 UTC, gtmanfred commented on salt/modules/mysql.py
> +def file_query(database, file_name, **connection_args):
Need a doc string here to show how to use the module on the commandline

2017-01-04 22:48 UTC, mchugh19 commented on salt/modules/mysql.py
> +def file_query(database, file_name, **connection_args):
Done

2017-01-04 22:49 UTC, gtmanfred approved these changes

2017-01-04 22:52 UTC, mchugh19 commented
Added docstring, versionadded string, and fixed lint errors.
I think the almost complete duplication of the existing mysql run function is a bit awkward, so if there are any suggestions on re-use, I'm game. But otherwise, I think this likely works.

2017-01-05 23:28 UTC, cachedout requested changes
Two small changes are needed and then this should be all ready to go. Thanks!

2017-01-05 23:28 UTC, cachedout commented on salt/modules/mysql.py
> +            if query_result == False:
This should be `if query_result is False:`

2017-01-05 23:28 UTC, cachedout commented on salt/states/mysql_query.py
> +    if query_result == False:
Also here: `if query_result is False:`

2017-01-06 07:46 UTC, mchugh19 commented on salt/modules/mysql.py
> +            if query_result == False:
done

2017-01-06 07:46 UTC, mchugh19 commented on salt/states/mysql_query.py
> +    if query_result == False:
done

2017-01-06 17:15 UTC, cachedout approved these changes

2017-01-06 17:16 UTC, merged

2017-04-07 12:41 UTC, bensbox commented
Is it possible only to import the sql files, if the database is empty?

2017-04-07 13:43 UTC, mchugh19 commented
It really just runs all of the sql statements in the file and is as good as your sql. If they require an empty db, then they can fail on a non-empty db. If the sql statements update existing data, then they can do so. 

Basically since it kicks off a bunch of sql, it is not idempotent and is as useful as your sql.