New execution module: statuspage
saltstack/salt pull request #38588
Opened 2017-01-05 16:58 UTC by mirceaulinic

### What does this PR do?

To handle easier requests to the StatusPage API: http://doers.statuspage.io/api/v1/

In the salt-ish style, the API and the page ID is taken from the config file if not sent on the CLI.

2017-01-05 18:49 UTC, cachedout commented
Go Go Jenkins!

2017-01-05 20:43 UTC, cachedout requested changes
Pylint has some issues here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5252/violations/file/salt/modules/statuspage.py/

2017-01-05 21:00 UTC, mirceaulinic commented
Damn! Sorry about that @cachedout! I have pushed the fix.

2017-01-05 23:19 UTC, cachedout commented on salt/modules/statuspage.py
> +import requests
I think we should move this to a try/except inside the `__virtual__` function.

2017-01-05 23:44 UTC, mirceaulinic commented on salt/modules/statuspage.py
> +import requests
Isn't `requests` one of the requirements? https://github.com/saltstack/salt/blob/develop/requirements/base.txt#L5

2017-01-06 17:29 UTC, cachedout approved these changes

2017-01-06 17:29 UTC, merged