Add support for wildcard versions in pkg.installed states
saltstack/salt pull request #38621
Opened 2017-01-06 16:57 UTC by terminalmage

This pull request adds support for aptpkg, yumpkg, and pacman to specify a
wildcard in a version number. While apt supports resolving wildcards
intrinsically, this functionality has been added via the use of the
pkg.list_repo_pkgs function for yumpkg and pacman. Code has also been added to
the pkg.installed state to resolve wildcard versions, to preserve idempotence.

An integration test is included, and documentation has been added to the
state's docstring as well as the Nitrogen release notes.

Resolves #34438
Refs: #34442

2017-01-06 17:35 UTC, cachedout requested changes
I think there's possibly a small typo here. Also, we need some lint cleaned up.

2017-01-06 17:35 UTC, cachedout commented on salt/modules/yumpkg.py
> +            yum_prefix.append('-C')
`cmd_prefix`?

2017-01-08 20:50 UTC, terminalmage commented on salt/modules/yumpkg.py
> +            yum_prefix.append('-C')
Yeah, typo. Fixed it, as well as lint, and rebased the changes into their respective commits.

2017-01-09 17:19 UTC, cachedout approved these changes

2017-01-09 17:19 UTC, cachedout commented
Go Go Jenkins

2017-01-09 17:20 UTC, cachedout commented
Go Go Jenkins!

2017-01-17 18:39 UTC, cachedout commented
Go Go Jenkins!

2017-01-30 16:56 UTC, rallytime commented
Go Go Jenkins!

2017-02-06 23:36 UTC, terminalmage commented
Go Go Jenkins!

2017-02-07 21:41 UTC, merged