Add network module for NILinuxRT: nilrt_ip.py
saltstack/salt pull request #38781
Opened 2017-01-17 16:25 UTC by raazvvann

### What does this PR do?
Add network module for NILinuxRT

Connman is the network manager used as backend.
Functionalities:
  - ip.get_interface_details()
  - ip.up(interface)
  - ip.down(interface)
  - ip.set_dhcp_linklocal_all(interface)
  - ip.set_static_all(interface, address, netmask, gateway, domains)
  - ip.build_interface(interface, interface_type, enable, **settings)
  - ip.build_network_settings(**settings)
  - ip.get_network_settings()
  - ip.apply_network_settings(**settings)

Integration test for:
  - ip.enable
  - ip.disable
  - ip.set_dhcp_linklocal_all
  - ip.set_static_all

Signed-off-by: Heghedus Razvan <razvan.heghedus@ni.com>

### Tests written?

Yes

2017-01-17 17:46 UTC, cachedout commented
Hi @raazvvann 

Thanks for this. There are a few issues that the linter picked up. Could you please take a look and make the requested changes? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7855/violations/

2017-01-23 17:38 UTC, cachedout requested changes

2017-01-23 17:38 UTC, cachedout commented on salt/modules/nilrt_ip.py
> +except ImportError:
What we probably want to do here is to move this into `__virtual__` and have that function return `False` if the `ImportError` is caught. That will ensure that Salt's loader system correctly displays the right error to the user and won't load the module when requested. There are many examples of this in various Salt execution modules.

2017-01-26 15:43 UTC, raazvvann commented
I need to do some more work on this module, beside what you requested. I will let you know when is ready.

2017-02-01 11:37 UTC, raazvvann commented
@cachedout I have done some rework on this module, please take a look and let me know if something isn't right

2017-02-02 19:09 UTC, cachedout commented on salt/modules/nilrt_ip.py
> +        if _get_state() == 'offline':
Because `_get_state()` can raise an exception, we need to catch that here and then handle it appropriately instead of letting it bubble up.

2017-02-02 19:09 UTC, cachedout commented on salt/modules/nilrt_ip.py
> +    return False
We could shorten this to `return state == 'online' or state == 'ready'` which will have the same result and be a little easier to read.

2017-02-06 12:51 UTC, raazvvann commented on salt/modules/nilrt_ip.py
> +        if _get_state() == 'offline':
Done

2017-02-06 12:51 UTC, raazvvann commented on salt/modules/nilrt_ip.py
> +    return False
Done

2017-02-06 19:30 UTC, merged