On version numbering, from discussion in PR #34535
saltstack/salt pull request #38849
Opened 2017-01-20 22:17 UTC by markuskramerIgitt

### What does this PR do?
Documenting the relationship between version numbering and Git 

Trom discussion in PR #34535

2017-01-23 16:51 UTC, cachedout requested changes

2017-01-23 16:51 UTC, cachedout commented on doc/topics/releases/version_numbers.rst
> +Version numberss, Git and salt --version
`Version numbers`

2017-01-23 16:51 UTC, cachedout commented on doc/topics/releases/version_numbers.rst
> +The salt version, for prorgammers, is based on `git describe` and presented to end users with `salt --version`.
`programmers`

2017-01-23 16:51 UTC, cachedout commented on doc/topics/releases/version_numbers.rst
> +The salt version, for prorgammers, is based on `git describe` and presented to end users with `salt --version`.
`end-users`

2017-01-24 09:27 UTC, markuskramerIgitt commented
Hello @cachedout, thank you for your corrections.

I fxied my spelling errors and checked in 33c1978, which appears above.
Does this mean I don't need another Pull Request?

2017-01-25 18:08 UTC, rallytime requested changes
I had one small technicality about the version_numbers doc changes. Once that is fixed, I think the doc changes look good. Thanks for putting this together @markuskramerIgitt!

However, I did not review the other files included here, as the windows build files are not my area. Were those files meant to be included here?

2017-01-25 18:08 UTC, rallytime commented on doc/topics/releases/version_numbers.rst
> +  | v2016.11.1 | Tag of the moment that the 2016.11.1 branch was created                    |
Change the word `branch` to `release` here. The `v2016.11.1` syntax is not a branch. It is a tag signaling the commit that a release is based on.

2017-01-26 08:47 UTC, markuskramerIgitt commented on doc/topics/releases/version_numbers.rst
> +  | v2016.11.1 | Tag of the moment that the 2016.11.1 branch was created                    |
@rallytime, thank you, I changed the wording (on my local file).

In fact there are many unrelated files in this pull request. This was not my intention.
I will now make a local backup of my pending changes, cancel all my pull requests, delete ally my branches and start over from scratch.

2017-01-26 09:51 UTC, closed without merging