Fix smtp ret require gnupg
saltstack/salt pull request #38937
Opened 2017-01-25 14:03 UTC by arthru

### What does this PR do?
This PR makes smtp returner be independant from gnupg installation

### What issues does this PR fix or reference?
Can't find an issue for that. I encountered the problem myself.

### Previous Behavior
Smtp returner could not be used if gnupg python module is not installed

### New Behavior
Smtp returner could be used without gnupg. If gpgowner is set and gnupg is not installed, an error is shown.

### Tests written?
No

2017-01-25 16:31 UTC, arthru commented
It looks like CI is broken (at least, fails are not due to my code)

2017-01-25 17:49 UTC, cachedout requested changes
Thanks for sending this @arthru 

I agree with you that `gnupg` shouldn't be required simply to use the `smtp` returner but I'm not sure this is the best way to go about this.

The basic problem is that all bare exceptions are silently caught by the functions which call the returner and so if we raise one in this way, we're effectively just breaking gnupg for people who want to use it but don't have the right deps installed. We need to at least give them a warning. :]

So, we have a couple of options. We can change things so that the exceptions that are raised by returners are caught, logged and displayed to the user. Or, we can log an error where you're now logging the exception and use that to inform the user, or we could even do both.

Either way, I'll accept this PR as soon as it properly informs the user that the required deps are not available if they try to use gnupg. Thanks!

2017-01-26 09:58 UTC, arthru commented
I just updated the merge request in order to log an error instead of raising an exception.

2017-01-26 19:12 UTC, cachedout approved these changes

2017-01-26 20:08 UTC, merged