add ability to override pillar data during state.sls_id run.
saltstack/salt pull request #39092
Opened 2017-01-31 22:10 UTC by jacobweinstock

### What does this PR do?
add ability to override pillar data during state.sls_id run.
### What issues does this PR fix or reference?
n/a
### Previous Behavior

pillar data override would have no effect in the following: 
```salt '*' state.sls_id apache http pillar="{'test': 'override'}"```
### New Behavior

pillar data override would take effect in the following: 
```salt '*' state.sls_id apache http pillar="{'test': 'override'}"```
### Tests written?

No

2017-02-01 19:12 UTC, cachedout requested changes

2017-02-01 19:12 UTC, cachedout commented on salt/modules/state.py
> +        st_ = salt.state.HighState(opts, pillar, pillar_enc=pillar_enc, proxy=__proxy__)
Let's use the kwarg explicitely here, so `pillar=pillar`.

2017-02-01 19:44 UTC, jacobweinstock commented on salt/modules/state.py
> +        st_ = salt.state.HighState(opts, pillar, pillar_enc=pillar_enc, proxy=__proxy__)
ah yes, copy that. thanks. pushing the change up now.

2017-02-02 17:55 UTC, cachedout approved these changes

2017-02-02 17:55 UTC, cachedout commented
This looks better now but I would also like @thatch45 and @terminalmage to look at it.

2017-02-02 18:01 UTC, thatch45 approved these changes
I am going to give this a thumbs up as it reflects how the other state function handle cli pillar propperly

2017-02-02 19:33 UTC, merged

2017-02-02 23:12 UTC, terminalmage commented
After the fact I know, but this gets a :+1: from me as well. Nice work!