Zabbix agent registration from itself, added template checking and ad…
saltstack/salt pull request #39154
Opened 2017-02-03 08:19 UTC by mmoono

### What does this PR do?
It adds the possibility of running Zabbix API calls from either Zabbix Server or Zabbix Agent. It gives us the possibility of using grains['localhost'] as hostname/interface, when ran from agent. It also adds the possibility of assign newly added/existing host to a predefined template. 

### What issues does this PR fix or reference?
Currently you can only run Zabbix agent registration from the Zabbix master server. Also, when adding a new host to monitor, there is no way to assign it to existing template.

### Previous Behavior
zabbix_host.present state could be ran only from the zabbix server. New hosts were not assigned to a template. 

### New Behavior
zabbix_host.present can be ran from either zabbix_server or zabbix_agent. 
When specifying templateids in sls file, host is assigned to those templates. When template not specified, host will be added unassigned to any template.

### Tests written?

No

2017-02-05 22:32 UTC, mchugh19 commented
Just a head's up, there is template functionality in the state in the develop branch. See https://github.com/saltstack/salt/blob/develop/salt/states/zabbix_host.py

It handles adding a template via templateId or template Name. So you may wish to look into leveraging that as well.

2017-02-06 06:28 UTC, mmoono commented
Oh, thanks for the info Christian. Of course we will use it once it's available in a release.
What about launching zabbix commands from zabbix agent hosts?

2017-02-07 17:08 UTC, cachedout commented
@mchugh19 Did you see the comment above from @mmoono ?

2017-02-07 18:57 UTC, mchugh19 commented on salt/modules/zabbix.py
> +    if salt.utils.which('zabbix_server') or salt.utils.which('zabbix_agent'):
If this is to be opened up to machines other than the zabbix server, you don't need this at all. The rest of the module seems to use salt's http interfaces, so it should run without needing zabbix utilities installed.

2017-02-07 19:01 UTC, mchugh19 commented on salt/modules/zabbix.py
> +def template_get(templateids=None, groupids=None, hostids=None, **connection_args):
You want to submit this against the develop branch. This function already exists there, so this will need a conflict merge.

2017-02-07 19:04 UTC, mchugh19 commented on salt/states/zabbix_host.py
> +        hosttemplates = __salt__['zabbix.template_get'](hostids=hostid, **kwargs)
The develop branch version of this fine includes another function, assign_templates. You may want to base this off of that functionality as it allows for specifying a template via a templateID or name.

2017-02-07 19:05 UTC, mchugh19 requested changes
Will need a rebase against develop

2017-02-07 19:12 UTC, mchugh19 commented
@mmoono Yep, it sounds like a fine idea to me! In our environment we didn't want to push out zabbix admin credentials out to all minions. If you're okay with that, all should be fine. You'll want to rebase this work against the develop branch, as some of this functionality already exists there.

2017-02-07 20:28 UTC, mmoono commented
@mchugh19, thanks! We didn't check the develop branch earlier to see what's there. As you said, the template handling is already there, so my changes are not needed. We will rebase the modules with develop branch tomorrow morning. But, again as you said ;), passing the connection arguments to the zabbix agents (in zabbix_host state) could come in handy.
Thanks!

2017-02-12 23:57 UTC, mchugh19 commented
Hey @mmoono! Hopefully you can get the rebase done, and evaluate the template handling. In looking things over, it turns out the kwargs/connection_args are often not passed to the module calls, making the comments about optional _connection_user/pass/url a complete lie :/

We've just started investigating using vault to access passwords. As part of that, we're looking at migrating password data from pillars to a query in the top of some states, which means using the _connection_whatever functionality. 

Cheers!

2017-02-13 09:54 UTC, mmoono commented
Hi @mchugh19, 
Indeed, I didn't pass the **kwargs to all __salt__ calls in the zabbix_host.py. Now, this is corrected. 
All in all, the methods which we were testing in our env, did pass the kwargs correctly. API calls were made from the minion to zabbix server without any problems. 
We will now wait for newer version of Salt, to take it into use.
Thanks!

Take care.

2017-02-13 10:10 UTC, mchugh19 commented
Super! Can you push the updates? One or two of the calls had overloaded the name kwarg, where passing in all **kwargs might make things funky. So we'll just want to review.

2017-02-13 11:51 UTC, mmoono commented
It should be there already: https://github.com/mmoono/salt/commit/8c2cdf77c9287682bc0d7a9ad3508321c8b24f93

2017-02-13 14:04 UTC, mchugh19 commented
Gocha. Didn't see that as it wasn't pushed to this PR.

2017-02-13 21:46 UTC, cachedout commented
Go Go Jenkins!

2017-02-13 21:52 UTC, mmoono commented
@mchugh19, damn! Sorry for that. Ehh, it looks like I have a lot to learn when it comes to git..

2017-02-15 20:24 UTC, cachedout commented
@mmoono Did you want to try to get that commit into this PR? Let me know if I can help. Thanks!

2017-02-15 20:25 UTC, cachedout commented
We also need the following two errors fixed before we can merge this, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/8539/violations/

2017-02-16 06:42 UTC, mmoono commented
@cachedout, I've fixed the pylint violations: https://github.com/mmoono/salt/commit/05385aba54b623ba38dfe90dda7dc286987e30f1. 
But now comes the tricky part(?). How can I add different branch (in this case develop) to this PR, while it is based on the 2016.11 branch?

2017-02-18 00:04 UTC, cachedout commented
@mmoono In order for those pylint (and other) fixes to show up in this PR, they made to be made and pushed to the same branch that this PR is made from. In this case, that's `mmoono:2016.11`

2017-03-22 19:14 UTC, cachedout commented
@mmoono We still don't have the right commits in this PR. I'm going to go ahead and close this and ask you to please open a brand-new PR with the changes that you want made. Thanks.

2017-03-22 19:14 UTC, closed without merging