fix: no more test against SYSTEM user
saltstack/salt pull request #39279
Opened 2017-02-09 16:06 UTC by martintamare

### What does this PR do?
Remove hard test against the user for windows, so as to be correct with all windows language

### What issues does this PR fix or reference?
Related to #38246

The code is not factorized yet, I would like advice on the best practise to factorize the function get_sid_from_name.
How can we call other utils functions from the code.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-02-09 16:59 UTC, cachedout requested changes
I don't see an import for `win32security` or `pywintypes` anywhere. Those need to be added before this can work.

2017-02-09 18:07 UTC, martintamare commented
Yep, agreed.
Any advice on how to factorize the get_sid_from_name ?
Can i cross call utils modules ? (don't know if that phrasing is correct in english ;)

2017-02-09 22:03 UTC, cachedout commented on salt/utils/win_runas.py
> +def get_sid_from_name(name):
To refactor this, just import `salt.utils` at the top of this file and then call `salt.utils.get_sid_from_name` where neccesary.

2017-02-10 12:48 UTC, martintamare commented
Should be better now.
Only one thing I don't know : the get_user function in __init__.py
Should I remove the last else ?

2017-02-13 21:30 UTC, cachedout commented on salt/utils/__init__.py
> +        return  # What should I do ?
Here I would recommend that you `raise salt.exceptions.CommandExecutionError('Required external libraries not found. Need 'pwd' or 'win32api')`

2017-02-14 09:46 UTC, martintamare commented
Code changed, and all commit merged into one.
We should be go to go.

2017-02-21 10:37 UTC, martintamare commented
Hello there,
Any update on this ?

2017-03-03 16:22 UTC, cachedout commented
@twangboy Can you please look at this?

2017-03-03 16:22 UTC, cachedout commented
Go Go Jenkins!

2017-03-03 17:17 UTC, twangboy requested changes
I think this is a good fix to account for the different names of the `SYSTEM` account in different languages. Recommend for merge after requested changes are completed.

2017-03-03 17:17 UTC, twangboy commented on salt/utils/__init__.py
> +    HAS_WIN32 = True
Here I would recommend `HAS_WIN32 = salt.utils.win_functions.HAS_WIN32` to make sure `win_functions` actually loads the win32 libraries.

2017-03-07 07:14 UTC, martintamare commented
Change applied !
Cheers,

2017-03-07 16:49 UTC, twangboy approved these changes

2017-03-22 19:07 UTC, cachedout commented
Linted by hand and it passed. Since @twangboy signed off on this I am going to go ahead and merge it.

2017-03-22 19:07 UTC, merged