add extmod_blacklist to make it easier to remove modules
saltstack/salt pull request #39367
Opened 2017-02-13 18:21 UTC by gtmanfred

### What does this PR do?
Similar to extmod_whitelist, but blacklist instead

### What issues does this PR fix or reference?
https://github.com/saltstack/zh/issues/1059

### Tests written?

Yes

2017-02-13 20:06 UTC, cachedout requested changes

2017-02-13 20:06 UTC, cachedout commented on salt/runners/saltutil.py
> +    return salt.utils.extmods.sync(__opts__, 'modules', saltenv=saltenv, extmod_whitelist=extmod_whitelist
This has a syntax error. Please add a trailing comma.

2017-02-13 21:57 UTC, cachedout commented
The test written for this appears to have failed: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/8458/testReport/junit/integration.modules.saltutil/SaltUtilSyncModuleTest/test_sync_all_blacklist/

2017-02-14 15:58 UTC, rallytime commented
@gtmanfred Looks like the following related tests are failing here. Can you take another look?

- `integration.modules.saltutil.SaltUtilSyncModuleTest.test_sync_all_blacklist_and_whitelist `
- `integration.modules.saltutil.SaltUtilSyncModuleTest.test_sync_all_blacklist`

2017-02-14 16:15 UTC, gtmanfred commented
Whoops! Forgot to add the blacklist to the sync_all function, thanks tests!
On Tue, Feb 14, 2017 at 9:58 AM Nicole Thomas <notifications@github.com>
wrote:

> @gtmanfred <https://github.com/gtmanfred> Looks like the following
> related tests are failing here. Can you take another look?
>
>    -
>    integration.modules.saltutil.SaltUtilSyncModuleTest.test_sync_all_blacklist_and_whitelist
>    -
>    integration.modules.saltutil.SaltUtilSyncModuleTest.test_sync_all_blacklist
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/39367#issuecomment-279748697>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoQ9UHIqk0PEICWx8t4jYg2xxz4ipks5rcc9AgaJpZM4L_jFc>
> .
>

2017-02-14 17:37 UTC, gtmanfred commented
hrm, now they are all failing

2017-02-14 17:53 UTC, gtmanfred commented
Ok, they should all pass on this run.

Thanks!

2017-02-15 19:52 UTC, cachedout commented
Afraid not. :] Please have another look at the tests. Thanks, @gtmanfred

2017-02-15 20:45 UTC, gtmanfred commented
I rebased my changes on develop, to see if that fixes those extra errors.  I am seeing everything passing when I run the full test suite.  We will see what jenkins says.

2017-02-17 23:57 UTC, merged