Parallel states
saltstack/salt pull request #39406
Opened 2017-02-14 21:02 UTC by thatch45

YES! You heard that right PARALLEL STATES!!!!!!

This PR allows you to set `parallel: True` on a state and it runs in a separate process!

Salt States just went from fast to ludicrous speed!

I am having a hard time figuring out a good way to test these to make sure states are running in parallel in an automated way, so I am open to suggestions.

2017-02-14 21:05 UTC, gtmanfred commented
That was fast.

2017-02-14 21:21 UTC, KaiSforza commented on salt/state.py
> +        return False if False in retset else True
Why not use `return False not in retset`? Just think it makes it a bit more readable.

2017-02-14 22:27 UTC, s0undt3ch commented on salt/state.py
> +        proc = multiprocessing.Process(
Use salt.utils.process.MultiprocessingProcess to get logging from the spawned process. Or the SignalHandlingMultiprocessingProcess. Whichever fits your needs.

2017-02-14 22:36 UTC, ninja- commented
great work @thatch45 !! I am going to test this and get some feedback as soon as possible.

Consider my example:
My total states run time is 10s.
Of that, 3s is the cloudflare task which updates DNS details, and 7s are the 'normal' tasks.

If I set cloudflare task to run in parallel on start, this should clearly give me free 3 seconds and reduce run time to 7s.

I'll check if that's how it's going to work on my setup 😄

2017-02-14 22:40 UTC, ninja- requested changes
This should work pretty well, but I am concerned about the 200ms magic value being too high.

2017-02-14 22:40 UTC, ninja- commented on salt/state.py
> +            time.sleep(0.2)
woah. 200ms seems like way too much...

2017-02-14 22:40 UTC, ninja- commented on salt/state.py
> +                    time.sleep(0.2)
Again, this magic value seems like a bit too high, especially if this parallel task is going to block other dependent tasks.

2017-02-14 22:43 UTC, ninja- commented on salt/state.py
> +            time.sleep(0.2)
If we are waiting forever anyway why not use waitpid() ?

2017-02-14 22:45 UTC, thatch45 commented on salt/state.py
> +            time.sleep(0.2)
good call, I changed them to 0.01

2017-02-14 22:45 UTC, ninja- commented on salt/state.py
> +            time.sleep(0.2)
wouldn't waitpid() be better?

2017-02-15 00:49 UTC, mirceaulinic commented
Fantastic addition @thatch45! Thanks you very much!

Would someone mind explaining the following to me:

```python
time.sleep(0.01)
```

Why is this needed and why the value of 0.01?

Thanks,
Mircea

2017-02-15 00:53 UTC, ninja- commented
@mirceaulinic basically, the tasks are started as seperate processess, and the code checks every 10ms if any of background tasks has finished to unblock executions on tasks dependent of them

2017-02-15 13:02 UTC, ninja- commented
@thatch45 I am wondering if we should close parent ZeroMQ connections in the forked process so tasks like file.managed etc. won't break with parallel: true? Is this handled at some point in salt's code?

2017-02-15 15:59 UTC, thatch45 commented
@ninja- this is a good point, I need to test some of this...

2017-02-15 16:00 UTC, thatch45 commented
As for using waitpid, I do think that this would be a better solution, but at the same time I think this approach makes the code more flexible for now. So I will say that we can move to it later but we should get this functional first

2017-02-16 12:20 UTC, damon-atkins commented
Need to be careful with waitpid and windows. Might be a case to use windows specific python functions.

2017-02-17 22:03 UTC, cachedout commented on doc/ref/states/parallel.rst
> +before the nginx this this:
`this this`?

2017-02-17 22:03 UTC, cachedout commented on salt/state.py
> +        with open(tfile, 'wb+') as fp_:
`salt.utils.fopen`?

2017-02-17 22:08 UTC, cachedout commented on salt/state.py
> +                    except OSError, IOError:
`except (OSError, IOError):` for Python 3 compat, please.

2017-02-17 23:10 UTC, thatch45 commented
ok, I pushed some fixes

2017-02-17 23:16 UTC, cachedout commented
Thanks. I played around a bit with the timing on this to make sure it wasn't going to use too much CPU sorting through the process table in a loop like that. Seems totally fine, so this default is a good one. This should be ready after this test run.

2017-02-17 23:16 UTC, cachedout approved these changes

2017-02-19 17:58 UTC, merged

2017-02-24 14:45 UTC, ninja- commented
@thatch45 I checked the matter of zeromq connections(whether it has a chance to break if the parallel task is file.managed etc. or the process forks).
<s>So the proper way to avoid the problem is to set FD_CLOEXEC on the file descriptor, just like in salt.utils.fopen(would be nice to have a Windows fallback but ehh...)
Unless I missed something, this flag is not set on ZeroMQ socket.
It can be done like on the snippet here: http://stackoverflow.com/a/27910874</s>

EDIT: FD_CLOEXEC probably wouldn't trigger because Salt is using fork(..) without exec(...). Hm.
If I am right here, then the part in salt.utils.fopen is also a dead code.

After implementing that I'd feel more safe about going with parallel states or working on SaltCacheLoader knowing that it won't break on threads or fork.

Would you maybe have an idea on how to close the ZeroMQ sockets in child process with minimal patch length?