fixing issue 39191
saltstack/salt pull request #39427
Opened 2017-02-15 18:12 UTC by narendraingale2

### What does this PR do?

This PR is fixing issue 39191. 

### What issues does this PR fix or reference?
issue 39191

### Previous Behavior
refer this issue  https://github.com/saltstack/salt/issues/39191

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-02-15 23:39 UTC, cachedout commented
@ticosax Could you please take a look here?

2017-02-16 11:18 UTC, ticosax reviewed
looks good.
But I'd like to be sure why `PATH` and `no_proxy` are not compared.

2017-02-16 11:18 UTC, ticosax commented on salt/states/dockerng.py
> +                if key not in ['PATH', 'no_proxy']:
please explain this exclusion of `PATH` and `no_proxy`.

2017-02-16 11:18 UTC, ticosax commented on salt/states/dockerng.py
> +                        env_ptr.setdefault('new', {})[key] = None
I'd rather skip it the `new` entry since the variable is not defined. Having the previous entry just in `old` should be fine.
your call though.

2017-02-16 11:19 UTC, ticosax commented
I forgot, a test covering this fix would be awesome.

2017-02-16 14:45 UTC, narendraingale2 commented on salt/states/dockerng.py
> +                if key not in ['PATH', 'no_proxy']:
These 2 variables are set by docker engine by default. 'docker inspect' shows these variables in ENV section as below. So these variables are included in list of actual_env variables and if we don't skip them container will get restarted every time even if there is no change in user defined environment variables.

"Env": [
                "VAR3=value33",
                "no_proxy=*.local, 169.254/16",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],

2017-02-16 14:46 UTC, narendraingale2 commented on salt/states/dockerng.py
> +                        env_ptr.setdefault('new', {})[key] = None
Agree I will remove new entry.

2017-02-16 14:53 UTC, ticosax commented on salt/states/dockerng.py
> +                if key not in ['PATH', 'no_proxy']:
Please add in the comment that those environment variables are controlled by docker then.

2017-02-16 15:26 UTC, narendraingale2 commented
@ticosax , @cachedout  This is my first contribution and sorry to say but I don't know how to write test cases. Though I would like to write. If you could direct me to some tutorial/video would be great. Thanks in advance.

2017-02-16 15:29 UTC, ticosax commented on salt/states/dockerng.py
> +                actual_val = actual_env.get(key)
you can do
```python
for key, actual_val in actual_env.items():
```
instead

2017-02-16 15:32 UTC, ticosax commented
@narendraingale2 everything is explained here.
https://docs.saltstack.com/en/latest/topics/development/tests/index.html

You will see dockerng coverage is pretty decent. You will be able to start easily from an existing test.

2017-02-16 15:41 UTC, narendraingale2 commented on salt/states/dockerng.py
> +                actual_val = actual_env.get(key)
done.

2017-02-20 05:08 UTC, narendraingale2 commented
Can somebody help me to run test case . When I try to run I am getting below error. I am trying to run integration tests. 

```
sudo ../salt/tests/runtests.py --name=integration.modules.pillar
 -> integration.modules.pillar.PillarModuleTest.test_pillar_items  .............................................................................................................
       Traceback (most recent call last):
         File "/Users/ningale/salt/tests/integration/modules/pillar.py", line 121, in test_pillar_items
           get_items = self.run_function('pillar.items')
         File "/Users/ningale/salt/tests/integration/__init__.py", line 1745, in run_function
           minion_tgt, function, arg, timeout=timeout, kwarg=kwargs
         File "/Users/ningale/salt/salt/client/__init__.py", line 701, in cmd
           **kwargs)
         File "/Users/ningale/salt/salt/client/__init__.py", line 340, in run_job
           'The salt master could not be contacted. Is master running?'
       SaltClientError: The salt master could not be contacted. Is master running?
```

2017-02-28 00:24 UTC, cachedout commented
@narendraingale2 Are you going to be able to come back and add the test requested by @ticosax ?

2017-03-01 05:29 UTC, narendraingale2 commented
Sure @cachedout  I was on vacation. Will submit soon.

Regards,
Narendra

2017-03-02 17:50 UTC, cachedout requested changes
In order for our new test runner to pick up these new tests, we need test/integration/states/docker.py renamed to test_docker.py, please.

2017-03-03 16:16 UTC, cachedout commented
@narendraingale2 We need a few more changes. First, there are a number of lint errors which need to be resolved:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9206/violations/file/tests/integration/states/test_docker.py/

Second, a test failed: integration.states.test_docker.TestModuleDockereng.test_docker_env

At a glance, this may be because some platforms do not have the proper prequsities installed. The test should be gated so that tests are skipped if the prereqs aren't found.

2017-03-05 07:00 UTC, narendraingale2 commented
@cachedout I am unable to run integration test cases.
`Traceback (most recent call last):
  File "../salt/tests/runtests.py", line 59, in <module>
    from tests.integration import TestDaemon  # pylint: disable=W0403
  File "/Users/ningale/salt/tests/integration/__init__.py", line 49, in <module>
    from tests.support.processes import *  # pylint: disable=wildcard-import
  File "/Users/ningale/salt/tests/support/processes.py", line 18, in <module>
    from pytestsalt.utils import SaltRunEventListener as PytestSaltRunEventListener
ImportError: No module named pytestsalt.utils
(salt-dev) ningale-L111:salt ningale$ `

Could you please help me to resolve this issue ?

2017-03-05 09:45 UTC, closed without merging

2017-03-05 09:52 UTC, narendraingale2 commented
Sorry but I dont know how files to be changed are 41. So I closed this PR and opened new. 

https://github.com/saltstack/salt/pull/39838

sorry for inconvenience caused.