Slack Engine Access Groups
saltstack/salt pull request #39499
Opened 2017-02-19 05:30 UTC by garethgreenaway

Finally getting around to adding a PR for something I started working on at the last Salt conference.  

### What does this PR do?
Adding in the ability to include access groups for the Slack engine, then specify what commands those groups have access to run.

### What issues does this PR fix or reference?
#35267

### Previous Behavior
All Slack users had access to all defined Salt commands.

### New Behavior
Command access can be broken up into groups.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-02-19 05:36 UTC, garethgreenaway commented
@mchugh19 Appreciate a quick glance at this PR since you've made some additions to the Slack engine recently.

2017-02-19 07:26 UTC, mchugh19 commented
Haven't run it, but at a glance it looks solid. Should we move the config parsing to a _utils function to keep things in sync between this, the hipchat engine, and any future chatops engines?

2017-02-22 18:47 UTC, cachedout commented
@garethgreenaway Did you see the comment above? I want to make sure you get a chance to make any needed changes before we merge this. Thanks! :]

2017-02-22 19:23 UTC, garethgreenaway commented
@cachedout Yup!  It's a good idea but can probably be made in a future PR.

2017-02-22 22:48 UTC, cachedout commented
@garethgreenaway Thanks for the response. I'll take one last look at this then and hopefully get it in. :]

2017-02-23 19:22 UTC, cachedout requested changes

2017-02-23 19:22 UTC, cachedout commented on salt/engines/slack.py
> +          valid_users=[],
We don't allow mutable values as kwarg defaults. Here's a good explanation as to why: http://reinout.vanrees.org/weblog/2012/04/18/default-parameters.html

Instead, our typical approach is to set `None` as the default and then switch it over inside the function implementation to a list. Let me know if you have questions.

2017-02-23 19:22 UTC, cachedout commented on salt/engines/slack.py
> +          valid_commands=[],
Same issue here with the default list.

2017-02-24 23:38 UTC, merged