Allow states to declare _connection_ keys as documented
saltstack/salt pull request #39494
Opened 2017-02-18 08:36 UTC by mchugh19

### What does this PR do?
The state documentation refers to allowing _connection_user, password, and url keys but does not actually use them. This commit corrects that. 

### Previous Behavior
Connection information was only passed via salt pillar. 

### New Behavior
Connection information is now defined by the state if available. Otherwise, it falls back on the standard pillar.

### Tests written?
No

@jirikotlin
@mmoono - This may possibly conflict with some of your recent updates as well. If you'd like to re-push your changes we can see how to resolve.

2017-02-19 17:50 UTC, cachedout commented
@mchugh19 Could you please look at these lint errors: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/8753/violations/file/salt/states/zabbix_host.py/

2017-02-19 20:10 UTC, mchugh19 commented
Will do. Currently traveling so it'll be next week.

2017-03-02 17:36 UTC, cachedout requested changes

2017-03-02 17:36 UTC, cachedout commented on salt/states/zabbix_host.py
> +    connection_args = {}
This function doesn't accept `**kwargs`. Perhaps you just forgot to add it?

2017-03-02 20:17 UTC, mchugh19 commented on salt/states/zabbix_host.py
> +    connection_args = {}
Right you are. Corrected! Thanks!

2017-03-03 16:07 UTC, merged