More redis functions to manipulate sets
saltstack/salt pull request #39601
Opened 2017-02-23 15:25 UTC by mirceaulinic

### What does this PR do?

Add few more functions to the redis execution module, this time they are useful to manipulate sets.
There are many other important features that can be added later.

2017-02-23 15:33 UTC, gtmanfred requested changes
Everything else looks good, i would just say we take this opportunity to add config.get to possibly pull the connection information from pillars.

2017-02-23 15:33 UTC, gtmanfred commented on salt/modules/redismod.py
> +def _get_kwargs_opts(**options):
can we use this opportunity to add `salt['config.get']()`to the options here so that the redis connection can be set in the pillar data?

2017-02-23 16:58 UTC, mirceaulinic commented on salt/modules/redismod.py
> +def _get_kwargs_opts(**options):
Yes, I agree, we should do that!

2017-02-24 18:48 UTC, cachedout commented on salt/modules/redismod.py
> +def _get_kwargs_opts(**options):
@mirceaulinic I'm sure you're busy this week but when you get a moment if you could let me know if you want to come back and make this change, please let me know. Thanks much.

2017-02-26 03:42 UTC, mirceaulinic commented on salt/modules/redismod.py
> +def _get_kwargs_opts(**options):
Sure @cachedout, I will let you know when this is ready to be reviewed! I am again in transit and I will not have the time required over the next several days. Thanks for patience!

2017-02-27 20:22 UTC, cachedout commented on salt/modules/redismod.py
> +def _get_kwargs_opts(**options):
No worries. Thanks @mirceaulinic !

2017-03-22 18:56 UTC, cachedout commented
@mirceaulinic Just checking in with you on this one. :]

2017-03-22 18:56 UTC, cachedout commented
Go Go Jenkins!

2017-03-23 14:01 UTC, mirceaulinic commented
Hi @cachedout - I did not forget, it's just with lower prio and I'll continue working on it later. I will ping you when ready. Thanks!

2017-03-23 21:40 UTC, cachedout commented
@mirceaulinic I really appreciate you keeping me updated. It helps me a lot. Thanks!

2017-04-13 15:59 UTC, cachedout commented
Hi @mirceaulinic. No hurry but just checking in with you here. Let me know how it's going on this one. Thanks!

2017-04-14 13:55 UTC, mirceaulinic commented
Hi @cachedout - apologies for delaying this. I have scheduled this for next Friday. Thanks a lot for patience!

2017-04-14 14:56 UTC, cachedout commented
@mirceaulinic Wonderful! Thanks so much.

2017-05-22 17:44 UTC, cachedout commented
Hi @mirceaulinic. Checking back with you here. :]

2017-05-23 17:16 UTC, mirceaulinic commented
Hi @cachedout - I am very sorry for delaying this. I have too many now in the queue (few pull requests to follow as fixes in nitrogen). But don't worry, I didn't forget about it, just that it may take a little longer to clear my backlog. Thanks!

2017-05-24 16:22 UTC, cachedout commented
@mirceaulinic No worries. Thank you for the update!

2017-07-31 23:23 UTC, cachedout commented
Hi @mirceaulinic. Just checking in with you again on this. :]

2017-09-11 22:00 UTC, cachedout commented
@mirceaulinic I'm going to close this for now, since we're doing some housekeeping on old PRs. When you are ready to come back to this, please leave a comment here and we will happily re-open this so we can get this in. Thanks very much.

2017-09-11 22:00 UTC, closed without merging