Fix ext_grains and ext_modules tests for Windows
saltstack/salt pull request #39648
Opened 2017-02-24 18:50 UTC by twangboy

### What does this PR do?
Fixes the `test_grains_overwrite` test in `integration.loader.test_ext_grains` tests
Fixes the `test_overridden_internal` test in `integration.loader.test_ext_modules` tests
Adds the tests to the Windows Whitelist
Modifies the names of all the renamed tests in the Windows whitelist
Fixes unreachable `log.debug in in the `grains` function in `loader.py`

### Tests written?
Yes

2017-02-26 03:18 UTC, cachedout requested changes

2017-02-26 03:18 UTC, cachedout commented on tests/integration/loader/test_ext_grains.py
> +        # To avoid a race condition on Windows, we need to make sure the
This needs more investigation IMHO. What's supposed to be putting this file in the cache? Why is it taking so long? I very much dislike just putting in timeouts when it's not clear what the problem is.

2017-02-27 16:48 UTC, twangboy commented on tests/integration/loader/test_ext_grains.py
> +        # To avoid a race condition on Windows, we need to make sure the
I don't know...

2017-02-27 16:52 UTC, cachedout commented on tests/integration/loader/test_ext_grains.py
> +        # To avoid a race condition on Windows, we need to make sure the
That's a much larger problem then. Let's try to figure out why that might be happening. Let me know if you would like a second pair of eyes to help diagnose the issue there.

2017-02-27 21:01 UTC, twangboy commented on tests/integration/loader/test_ext_grains.py
> +        # To avoid a race condition on Windows, we need to make sure the
I don't even know where to start

2017-02-28 00:19 UTC, cachedout commented on tests/integration/loader/test_ext_grains.py
> +        # To avoid a race condition on Windows, we need to make sure the
OK. Grab me tomorrow afternoon and we'll have a look. :]

2017-03-01 22:00 UTC, twangboy commented
@cachedout I clarified the comments on this one

2017-03-01 22:12 UTC, cachedout approved these changes

2017-03-01 22:12 UTC, merged