Vault: Add support for expanding lists in policies
saltstack/salt pull request #39672
Opened 2017-02-26 20:18 UTC by carlpett

### What does this PR do?
The `policies` configuration templates can now refer to grains which are lists and have them automatically expanded into multiple policies.

### New Behavior
If a template contains a grain which evaluates to a list, it will be expanded into multiple policies. For example, given the template `saltstack/by-role/{grains[roles]}`, and a minion having these grains:

            grains:
                roles:
                    - web
                    - database

The minion will have the policies `saltstack/by-role/web` and `saltstack/by-role/database`.

Previously, the policy `saltstack/by-role/[web, database]` would have been generated.

### Tests written?

Yes. Would appreciate an extra eye on those, as they are the first ones I've written for salt. Is my way of running through a list of cases possible to do some other way?

2017-02-27 16:54 UTC, cachedout requested changes
Some very minor issues to fix up but overall this looks really good!

2017-02-27 16:54 UTC, cachedout commented on salt/runners/vault.py
> +
We need one more newline here to match with the other separations between functions in this module.

2017-02-27 16:54 UTC, cachedout commented on salt/runners/vault.py
> +    '''
We need to add a `# pylint: disable=W0105` to the end of this so that the lint check does not complain.

2017-02-27 18:58 UTC, carlpett commented
@cachedout Thanks, fixed comments. Any feedback on the tests, is it a "typical" implementation of data-driven tests in `salttesting`?

2017-02-28 00:32 UTC, cachedout commented
@carlpett Thanks for the quick update. Test looks great, actually. Well-done!

2017-02-28 00:33 UTC, merged