A random startup delay option for minions
saltstack/salt pull request #39802
Opened 2017-03-02 23:43 UTC by cachedout

This allows minions to spread out the load to the master if a large number
of them start up at once.

2017-03-06 21:38 UTC, rallytime requested changes
I just had some simple doc requests to go with this. It also looks like some tests are unhappy with this change.

2017-03-06 21:38 UTC, rallytime commented on conf/minion
> +# To avoid overloading a master when many minions startup at once, a randomized
Could you also add this documentation to the [minion.rst](https://github.com/saltstack/salt/blob/develop/doc/ref/configuration/minion.rst) page?

It's probably a good idea to add this to the Nitrogen release notes as well.

2017-04-06 18:52 UTC, cachedout commented on conf/minion
> +# To avoid overloading a master when many minions startup at once, a randomized
Done.

2017-04-10 22:41 UTC, cachedout commented
Go Go Jenkins!

2017-04-13 15:53 UTC, merged