Fix endpoint handling per region
saltstack/salt pull request #39850
Opened 2017-03-06 15:44 UTC by epcim

### What does this PR do?

Fixes behavior, if keystone is hared for multiple regions. (multiregion setup) at such case endpoint_get can't just get endpoint by "service name". As, multiple entries may exist.

### What issues does this PR fix or reference?

N/A

### Previous Behavior
Remove this section if not relevant

one iteration did deleted old endpoints, second created endpoints from other region, see for reference:
https://github.com/saltstack/salt/blob/develop/salt/states/keystone.py#L734

### New Behavior
works only with specific region.
side effect: possibly salt can't modify region of existing endpoint.

### Tests written?

No, No idea how to integrate with existing setup. Tested on dev. environment.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-03-06 17:27 UTC, cachedout commented
Hi @epcim! Thanks for this.

All we need to do here is to modify the existing tests to pass in a region since it is now required. Could you please make the modifications outlined here?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9265/violations/

2017-03-06 20:18 UTC, gtmanfred requested changes
I am ok with this mostly, but I think that if the `region` is not specified it should default to the keystone region that is used to authenticate.

2017-03-07 15:48 UTC, epcim commented
@gtmanfred note, IMHO there is no default region in keystone client session. I just checked it. You may get regions, but you won't get the default. Correct me if you have more experience.

Also, the create, etc.. calls has already default region=RegionOne so some other calls called under these will get this attribute.

2017-03-07 15:51 UTC, gtmanfred commented
there is no default region in keystone.  But when you setup an identity endpoint, you also setup a region that that endpoint is in.

I would like, if the region is not defined/passed, to use the region that the identity endpoint is in to be used.

2017-03-07 15:52 UTC, gtmanfred commented
Also, there are unit tests for keystone that are failing.

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9424/testReport/junit/unit.states.test_keystone/KeystoneTestCase/test_endpoint_absent/

2017-03-07 16:39 UTC, epcim commented
will push soon. if there is no default region i do have to fix doc strings as wellOn 7 Mar 2017 4:52 p.m., Daniel Wallace <notifications@github.com> wrote:Also, there are unit tests for keystone that are failing.
https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9424/testReport/junit/unit.states.test_keystone/KeystoneTestCase/test_endpoint_absent/

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-07 17:00 UTC, epcim commented
[**@gtmanfred**](https://github.com/gtmanfred) commented on [Mar 7, 2017, 4:51 PM GMT+1](https://github.com/saltstack/salt/pull/39850#issuecomment-284761519 "2017-03-07T15:51:32Z - Replied by Github Reply Comments"):
> there is no default region in keystone.  But when you setup an identity endpoint, you also setup a region that that endpoint is in.
> 
> I would like, if the region is not defined/passed, to use the region that the identity endpoint is in to be used.

do you mean from session to get id of the current keystone, and do sub-query to find it's region? (if such uuid is provided).

Note for endpoint create we ship default value RegionOne which either is not the one of current endp.

2017-03-07 17:12 UTC, gtmanfred commented
Yes, I would like to do that, and also if you could change the default create to that.  IMO it is what that always should have been.

2017-03-07 19:47 UTC, epcim commented
[**@gtmanfred**](https://github.com/gtmanfred) commented on [Mar 7, 2017, 4:51 PM GMT+1](https://github.com/saltstack/salt/pull/39850#issuecomment-284761519 "2017-03-07T15:51:32Z - Replied by Github Reply Comments"):
> there is no default region in keystone.  But when you setup an identity endpoint, you also setup a region that that endpoint is in.
> 
> I would like, if the region is not defined/passed, to use the region that the identity endpoint is in to be used.

do you mean from session to get id of the current keystone, and do sub-query to find it's region? (if such uuid is provided).

Note for endpoint create we ship default value RegionOne which either is not the one of current endp.
[**@gtmanfred**](https://github.com/gtmanfred) commented on [Mar 7, 2017, 6:12 PM GMT+1](https://github.com/saltstack/salt/pull/39850#issuecomment-284790596 "2017-03-07T17:12:38Z - Replied by Github Reply Comments"):
> Yes, I would like to do that, and also if you could change the default create to that.  IMO it is what that always should have been.

Seems to me there is no way to get it
Check : 
https://github.com/openstack/keystone/blob/25a871d1446d3769ca58463350a65ed3a4d9d7d4/keystone/catalog/controllers.py#L180
if it's not defined region or region_id then None is set.

I checked v2 and v3 (shortly) when you connect you don't have any info what keystone you talk to. Surprisingly.

It seems RegionOne si common default, and None is acceptable as well if 1 region is used. So I might update the states/module with default region=None; And our tests to use RegionOne as that's what we have in test. env. But having region=None I find not good anyway.

Replace RegionOne with None on endpoint_create is not backward compatible.
Use RegionOne everywhere as default region value is viable.
Keep it as it is, require end users to design their pillar properly, not ignoring region entry.

Btw, we don't implement create_region.

Anyone has a solution to get region of the current identity from it's session response?

2017-03-08 15:04 UTC, gtmanfred approved these changes

2017-03-08 15:05 UTC, gtmanfred commented
`None` as a default works for me then.

Also, you still have pylint failing on some keystone stuff. https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9305/console

And There are still some unittests failing. https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9448/

2017-03-09 16:20 UTC, epcim commented
Folks any ideas what to do with: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/9298/ 
??

2017-03-21 17:29 UTC, cachedout commented
Go Go Jenkins!

2017-03-22 14:49 UTC, epcim commented
[**@cachedout**](https://github.com/cachedout) commented on [Mar 21, 2017, 6:29 PM GMT+1](https://github.com/saltstack/salt/pull/39850#issuecomment-288155894 "2017-03-21T17:29:14Z - Replied by Github Reply Comments"):
> Go Go Jenkins!

Working on it.
Will add better debuging, and one for test=true as curently we are blind.

2017-03-22 18:30 UTC, cachedout commented
As soon as we can get those tests to pass we should be ready to go here.

2017-03-28 00:46 UTC, cachedout commented
Go Go Jenkins!

2017-03-28 00:46 UTC, cachedout commented
@epcim Once these tests run, could you please have a look at any failures? We'd like to get this in but we need any test failures resolved first. Thanks!

2017-04-03 20:59 UTC, cachedout requested changes
Could you please fix the lint errors found here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10061/violations/file/salt/modules/keystone.py/

2017-04-04 10:58 UTC, epcim commented
Go Go Jenkins!

```
HTTP ERROR 404

Problem accessing /job/PR/job/salt-pr-docs-n/5525/. Reason:

    Not Found

```

2017-04-04 14:41 UTC, cachedout commented
Looks like the lint errors are still there. Let us know if you'd like a hand in fixing those up. Thanks!

2017-04-04 16:38 UTC, cachedout commented
I just went ahead and fixed that lint error so need to fix it. Thanks.

2017-04-05 05:36 UTC, epcim commented
[**@cachedout**](https://github.com/cachedout) commented on [Apr 4, 2017, 6:38 PM GMT+2](https://github.com/saltstack/salt/pull/39850#issuecomment-291558474 "2017-04-04T16:38:09Z - Replied by Github Reply Comments"):
> I just went ahead and fixed that lint error so need to fix it. Thanks.

thanks, I am still debuging a one situation that fails. Once fix I still do have to update unit tests as I recently added more verbosed output from runs, but now return string's do not match what we have in unit tests.

2017-04-05 08:10 UTC, epcim commented on salt/states/keystone.py
> +            _addEndpoint()
Can someone closely review this line?
- Behavior before was "delted endpoint" after first run, and "created" on second run.
- Not sure whether I added the test for this kind of recreate

2017-04-05 09:03 UTC, epcim commented on salt/states/keystone.py
> +            _addEndpoint()
If I am in the picture, we also do not test creation of the endpoints over api v3 in the unit tests.

2017-04-05 16:50 UTC, cachedout commented on salt/states/keystone.py
> +            _addEndpoint()
@gtmanfred Can you look here please?

2017-04-07 18:55 UTC, cachedout commented
@epcim OK. Please let me know when you think this one is ready for a final review.

2017-04-10 14:34 UTC, gtmanfred commented on salt/states/keystone.py
> +            _addEndpoint()
I will take a look once 2016.11.4 is out the door :+1:

2017-04-13 13:53 UTC, epcim commented
[**@cachedout**](https://github.com/cachedout) commented on [Apr 7, 2017, 8:55 PM GMT+2](https://github.com/saltstack/salt/pull/39850#issuecomment-292622584 "2017-04-07T18:55:02Z - Replied by Github Reply Comments"):
> [@epcim](https://github.com/epcim) OK. Please let me know when you think this one is ready for a final review.

Seems as implemented, but will test it manually once more in my env. within one week. Our integration tests are not the level I would like to see - but hard to upgrade.

2017-04-13 15:15 UTC, cachedout commented
@epcim Sounds good. Keep me posted. Thank you.

2017-04-17 19:19 UTC, gtmanfred commented
Go Go Jenkins!

2017-04-20 17:39 UTC, cachedout commented
Hi @epcim. It's been a week. :]

Were you able to test this?

2017-04-20 22:00 UTC, epcim commented
tomorrow will finish!On 20 Apr 2017 19:39, Mike Place <notifications@github.com> wrote:Hi @epcim. It's been a week. :]
Were you able to test this?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2017-04-21 14:16 UTC, epcim commented
[**@cachedout**](https://github.com/cachedout) commented on [Apr 20, 2017, 7:39 PM GMT+2](https://github.com/saltstack/salt/pull/39850#issuecomment-295828249 "2017-04-20T17:39:28Z - Replied by Github Reply Comments"):
> Hi [@epcim](https://github.com/epcim). It's been a week. :]
> 
> Were you able to test this?

Well I tested create/update endpoints in multiregion setup and it works as expected.  I am OK with the current version. If you don't have any objections I am done with it.

BTW the unit/integration test's are not the kind I like (not readable, not extensive) but honestly I was not able to make them better.

Test True
```
----------
          ID: keystone_identity_service_glance_endpoint_RegionOne
    Function: keystone.endpoint_present
        Name: glance
      Result: None
     Comment: Public URL changes from "https://172.16.10.254:3333" to "https://172.16.10.254:5555"
              Admin URL changes from "http://172.16.10.254:9292" to "http://172.16.10.254:4444"
              Endpoint for service "glance" will be updated
     Started: 14:08:01.489746
    Duration: 274.09 ms
     Changes:   
              ----------
              Endpoint:
                  Will be updated
  Name: cinderv2 - Function: keystone.service_present - Result: Clean Started: - 14:08:01.764079 Duration: 85.661 ms
```
Run
```
----------
          ID: keystone_identity_service_glance_endpoint_RegionOne
    Function: keystone.endpoint_present
        Name: glance
      Result: True
     Comment: Public URL changes from "https://172.16.10.254:3333" to "https://172.16.10.254:5555"
              Admin URL changes from "http://172.16.10.254:9292" to "http://172.16.10.254:4444"
              Endpoint for service "glance" has been updated
     Started: 14:09:05.204970
    Duration: 2823.952 ms
     Changes:   
              ----------
              HUMAN_ID:
                  False
              NAME_ATTR:
                  name
              adminurl:
                  http://172.16.10.254:4444
              enabled:
                  True
              id:
                  f16f440820a3430bbebcb9d3d64575a6
              internalurl:
                  http://172.16.10.254:9292
              publicurl:
                  https://172.16.10.254:5555
              region:
                  RegionOne
              service_id:
                  6ae63a3aba534a96ae885941e13ad37d
```
Surely add/modify another region glance endpoint works./

2017-04-23 09:59 UTC, cachedout approved these changes

2017-04-23 10:00 UTC, merged

2017-05-25 20:07 UTC, seanjnkns commented
Could we get this backported to 2016.3 and 2016.11?

2017-05-26 17:16 UTC, rallytime commented
I have back-ported this to 2016.11. We won't back-port it to 2016.3, however, as @gtmanfred stated in #41435.