unit tests for junos specific code
saltstack/salt pull request #39884
Opened 2017-03-08 12:02 UTC by vnitinv

### What does this PR do?
Few JUNOS specific bug fixes and unit test added

### What issues does this PR fix or reference?
Changes for using latest PyEZ

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-03-10 01:16 UTC, mirceaulinic commented
Oh my... I personally find this hard to review: hundreds of changes in all the existing modules + tests in a single PR... I think you should split this into a PR with the corrections & a separate one just containing the tests.

2017-03-10 01:17 UTC, mirceaulinic commented
Also: some rebase and squash would not hurt, it's very noisy and commits like https://github.com/saltstack/salt/pull/39884/commits/c67f68e0064151f9796ef07894bfb6235af00f79 don't tell me much.

2017-03-10 18:27 UTC, vnitinv commented
@mirceaulinic We are consolidating all the changes (pull request from org members) into our org level branch and sending a unified pull request in a certain time (say each month once). This is as per discussion with SaltStack. In such scenario splitting feature specific pull request will be tough.

But at the same time, I take your second comment where a single blank line was added. Will pass on this feedback to the commiter. Thanks for pointing.

2017-03-10 21:27 UTC, cachedout commented
@mirceaulinic FWIW, GitHub does give maintainers the option to squash PRs into a single commit when they are merged. So, I don't mind a lot of commits in PRs. Splitting features up though, as you mention, is very helpful to us. :]

2017-03-10 21:32 UTC, cachedout commented
@vnitinv There are a few lint issues here. Could you please have a look?

2017-03-14 05:54 UTC, rajvidhimar commented
@cachedout  I am unable to open https://jenkins.saltstack.com/ to check the error report. Is it down?

2017-03-14 15:22 UTC, rallytime commented
Go Go Jenkins!

2017-03-14 15:22 UTC, rallytime commented
@rajvidhimar Yes, jenkins was having a rough day yesterday. It is back up now and I have restarted the test run. :)

2017-03-14 19:12 UTC, cachedout requested changes
Some lint changes are still needed here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9470/violations/file/tests/unit/modules/test_junos.py/

2017-03-15 10:12 UTC, vnitinv commented
@cachedout with latest code we dont see any violation in this list
https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9510/violations/

Is that something we are missing?

2017-03-15 12:18 UTC, rajvidhimar commented
@cachedout https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9658/testReport/junit/unittest.loader.ModuleImportFailure.unit/modules/test_junos/
We have external dependencies such as nose, junos-eznc (PyEZ) to run the junos unit tests. Is there a way we can add these dependencies, so that the builds don't error out?

2017-03-17 05:10 UTC, vnitinv commented
@cachedout Can you please review this and let us know if we need to do changes.

2017-03-21 17:20 UTC, cachedout commented
Go Go Jenkins!

2017-03-21 17:45 UTC, s0undt3ch requested changes

2017-03-21 17:45 UTC, s0undt3ch commented on tests/unit/modules/test_junos.py
> +from nose.plugins.attrib import attr
We don't use nose and we're actually working towards using pytest.
`attr` seems just like a test selection decorator and, if that's the only benefit, could it be removed?

You can select this test case on the develop branch by passing the module filesystem path to runtests.py

2017-03-23 21:16 UTC, cachedout commented
@vnitinv We need this rebased because there is a merge conflict. This was reviewed by @s0undt3ch and he requested changes which are listed above. Thanks.

2017-03-24 06:54 UTC, vnitinv commented
@cachedout I have done merge in place of rebase as rebase was giving me few errors. Hope merge should be fine. If you want we I send a new pull request with the cleaner version.

2017-03-27 11:47 UTC, vnitinv commented
@cachedout @s0undt3ch Can you please review the changes and merge the pull request. 
All the jenkins jobs are passing.

2017-03-28 00:35 UTC, cachedout approved these changes

2017-03-28 00:35 UTC, merged