Move stuff to make it available for salt-ssh
saltstack/salt pull request #39907
Opened 2017-03-08 22:09 UTC by gtmanfred

### What does this PR do?
Move some stuff from call_high to call_chunks so that it is available to salt-ssh.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/39239

### Tests written?

No

2017-03-08 23:05 UTC, s0undt3ch requested changes

2017-03-08 23:05 UTC, s0undt3ch commented on salt/state.py
> +	ret = self.call_chunks(chunks)
Missing a space? Tabs?

2017-03-08 23:06 UTC, gtmanfred commented on salt/state.py
> +	ret = self.call_chunks(chunks)
I swear, I am just going to delete my .vimrc tonight.

2017-03-08 23:07 UTC, s0undt3ch commented on salt/state.py
> +	ret = self.call_chunks(chunks)
:)

2017-03-09 09:33 UTC, s0undt3ch approved these changes
Test failure is not related.

2017-03-09 09:33 UTC, merged