salt.modules.state: use correct _errors when _check_pillar failed
saltstack/salt pull request #39946
Opened 2017-03-10 12:15 UTC by dqminh

When _check_pillar failed, `_errors` are stored in `st_.opts['pillar']`, not
`__pillar__`, use the correct variable to prevent exception such as the
following being raise:

```
The minion function caused an exception: Traceback (most recent call
last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1435,
in _thread_return
        return_data = executor.execute()
      File
"/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line
28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py",
line 553, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py",
line 1046, in sls
        err += __pillar__['_errors']
      File "/usr/lib/python2.7/site-packages/salt/utils/context.py",
line 211, in __getitem__
        return self._dict()[key]
    KeyError: '_errors'
```

Signed-off-by: Daniel Dao <dqminh89@gmail.com>

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-03-11 03:39 UTC, cachedout requested changes
I'm afraid this caused some tests to fail: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/9329/

2017-03-14 19:13 UTC, cachedout commented
@dqminh Did you see the above comment about failing tests?

2017-03-21 16:45 UTC, cachedout commented
@dqminh Bump. Did you see the above comment on the failing tests here?

2017-03-22 18:13 UTC, cachedout commented
Closed for lack of response. @dqminh when you can come back to this, we'll happily re-open it. Thanks.

2017-03-22 18:13 UTC, closed without merging

2017-03-22 18:44 UTC, dqminh commented
It was only a few days :p 
I will take a look as soon as i have some time.