Fix problems with the test suite on Py3
saltstack/salt pull request #40094
Opened 2017-03-16 21:17 UTC by twangboy

### What does this PR do?
Fixes some problems discovered during the initialization of the test suite on Py3.
- `.encode('string-escape`)` is not a thing in Python 3
- `file.directory` would try to make None the owner in Windows... If None is passed as the User it will now use the Current User.
- There was a logic error in `win_dacl.py` where if the current ace permission is unknown it would fail... it was checking for an item inside a list instead of checking for an empty list.
- There was an issue with username and sid lookup functions where they didn't handle `None` as an input. Now they return the value for `NULL SID`

### What issues does this PR fix or reference?
https://github.com/saltstack/zh/issues/1176

### Previous Behavior
Tests failed to start due to these issues. Additional problems with salt-jenkins will be coming in another PR.

### New Behavior
Tests now start...

### Tests written?
No

2017-03-17 09:39 UTC, s0undt3ch commented on salt/modules/pip.py
> -        if salt.utils.is_windows():
Are you sure this is not required for python 2?

2017-03-17 09:39 UTC, s0undt3ch commented on salt/modules/pip.py
> +                bin_env, 'Scripts', 'pip.exe')
Same as above.

2017-03-17 17:01 UTC, cachedout commented
@twangboy Can you please respond to the above comments from @s0undt3ch ?

2017-03-17 22:37 UTC, twangboy commented
@s0undt3ch Applied fixes you requested

2017-03-17 23:38 UTC, s0undt3ch requested changes

2017-03-17 23:38 UTC, s0undt3ch commented on salt/modules/pip.py
> +        if salt.utils.is_windows() and six.py2:
`six.PY2`, uppercase.

2017-03-17 23:38 UTC, s0undt3ch commented on salt/modules/pip.py
> +            if six.py2:
Same as above

2017-03-20 21:56 UTC, cachedout commented
@s0undt3ch Can you re-review with the latest changes please?

2017-03-20 22:14 UTC, s0undt3ch approved these changes

2017-03-20 22:14 UTC, s0undt3ch commented
:+1:

2017-03-20 22:14 UTC, merged