salt.returners.local_cache:prep_jid useless recursive function ?
saltstack/salt pull request #40156
Opened 2017-03-20 16:53 UTC by arount

## Issue

While trying to understand how works custom returners I finally thought it was easier to look at code than doc or example. Anyway I walked on `local_cache` returner and seen recursive `prep_jid` function.

Recursion was done by waiting 0.1s, not sure but I think this is done _only_ to avoid stack-overflow. It's always a good thing to avoid recursive functions when possible and I'm always triggered when I see a `time.sleep` in code, especially close to recursive method.

## What I understood of the current code

If I'm right, `prep_jid` is recursive because `salt.utils.jid.gen_jid()` use reformatted `datetime.datetime.now()` string as id, so it is possible two or more jid are same. To avoid conflicts this method simply try 5 times before raising error.

Because jid contains micro-second, I don't think `time.sleep` is used to be sure to generate another id, but only to avoid stack-overflow.

## What I done

### 1. Recursion

I removed recursion from `prep_jid` by creating function `_make_jid_directory` trying to make it and returns False if failed to.
I just call this function five time in `prep_jid` which make exactly same thing but without recursive function.

I removed deprecated `recurse_count` arg too.

### 3. Time.sleep

So I remove `time.sleep` before recursion. Seems useless to me.

### os.path.isdir VS try / except

```
    if not os.path.isdir(jid_dir):
        try:
            os.makedirs(jid_dir)
        except OSError:
```

This part is doing two times the same things, one time in pythonish way, one time not. I updated it to only use `try / except` which gives you same result than `if not os.path.isdir`.

I tried this on self-contained install & real server, don't get errors which seems to confirm `time.sleep` is useless.

2017-03-20 21:36 UTC, cachedout commented
@arount Thanks for this. Is this purpose here merely to clean up dead code and to improve readability or is there an open GitHub issue associated with this?

2017-03-21 08:53 UTC, arount commented
@cachedout It's about clean and make it easier to read. There is no issue related.

I will surely continue to work on this, make checks pass & update doc. I can't work all time on this, so can I ping you in comments when I'm done with this ?

In this time, can you please explain in some lines why it is done like that ? I'm afraid to miss something and create regression or something. If there are no _real_ reason why, so just tell me, I just want to be sure I really understand what I'm doing.

2017-03-21 09:14 UTC, arount commented
Got this with pylint: `E:  1, 0: Module file has the wrong file permissions(expected 0644): 0664 (file-perms)`. All returners are 0664, should I skip this error ?

2017-03-22 18:06 UTC, cachedout requested changes
This needs a `from salt.ext.six.moves import range` at the top to pass the lint check, please.

2017-03-22 23:29 UTC, cachedout approved these changes

2017-03-23 01:49 UTC, arount commented
Well, I finally understood how returners works. I hope I'm not wrong. What I saw is `prep_jid` and `save_load` struggled to access jid directory.

In fact each one was trying to create jid directory but when `OSError` was raised instead of checking if directory exists, make recursions.

jids are datetime, so by waiting 0.1s for each recursion they finally got a new clean jid without existing directory.

I tested this version, hope it's ok.
btw I forced a single new commit.

2017-03-23 09:20 UTC, arount commented
@cachedout sorry but can you help with tests. Pylint still failling in jenkins but seems to work on my host. No sure if warning is the issue: `salt/returners/local_cache.py:28: [W0611(unused-import), ] Unused range imported from salt.ext.six.moves`.

I do not understand what going on with linode-ubuntu too.

Thank you

2017-03-23 12:46 UTC, s0undt3ch commented
The lint issue is valid, you do not seem to be using `range`, so, remove that import.

2017-03-23 12:47 UTC, s0undt3ch commented
As for the Ubuntu failures, they are unrelated to your PR, don't worry about those.

2017-03-23 12:57 UTC, arount commented
@s0undt3ch thank you. Done.

2017-03-23 20:55 UTC, cachedout commented
I know that @thatch45 has experience with some race-conditions that can be present in this area of the code so I want to run this past him before we merge it. Thanks for being patient, @arount

2017-03-23 21:08 UTC, thatch45 requested changes
From the look of things I think this has the potential to create massive problems. It the event where we have jid directory collisions this would just raise the collisions instead of retry, and those collisions are much more possible in the event of a syndic.
Basically, I am very hesitant to merge this one. if we don't fall back to create a new jid then we will have issues.
I do however like the refactor and I am very open to changing the sleep to 0.01 seconds to improve performance

2017-03-23 21:23 UTC, arount commented
@thatch45 Thanks for feedback, this is interesting. I will look at syndic and its behavior and came back to you.

I will surely add conflict security but I do not know how. I feel like jid collision should be managed  by  `salt.utils.jid.gen_jid`. Is there something you are open to ? (not saying this is what I will do, but that can be a solution).

2017-03-28 00:25 UTC, cachedout commented
@thatch45 Can you follow up on the above question please? Thanks.

2017-03-29 08:08 UTC, arount commented
More i'm reading this more I'm thinking replacing `salt.utils.jid.gen_jid` code by `uuid.uuid4()` will fix issue without any hack or control needed.

What do you think ?

2017-03-29 08:31 UTC, thatch45 commented
The jid value is also a timestamp and is used elsewhere in Salt as a timestamp, I think that the best way to alleviate this issue from the perceptive of making the jid a uuid would be to add a few chars at the end of the jid that are random

2017-04-13 15:51 UTC, cachedout commented
@arount Are you going to come back to this one? If so, we'll need a rebase to address a merge conflict. If I don't hear from you, I'll go ahead and close it for the time being. Thanks.

2017-04-14 10:02 UTC, arount commented
@cachedout sorry for this delay. Yes, I want to finish it. I do all I can to push something today. Keep you in touch

2017-04-14 10:09 UTC, cachedout commented
@arount Thank you very much!

2017-05-02 17:27 UTC, cachedout commented
Hi @arount. Just checking in with you here. :]

2017-05-03 15:30 UTC, arount commented
Haa, i'm such a bad person ! Well I updated my branch to use `uuid` as jid (that can be transformed in timestamp) but it breaks units tests (but, it's expected), I just need to check theses tests.

So, promise, if friday I did not make it works, I will just close the PR.

I really want to finish this PR, but maybe I'm going too far.

See you soon

2017-05-03 17:07 UTC, cachedout commented
@arount You're great! Thanks so much!

2017-05-04 13:08 UTC, arount commented
Ok. Here is the thing

## salt.utils.jid

The major change here is the `jid` generation and format. `salt.utils.jid.gen_jid` now returns `uuid4` strings (example `590ae156-3f01-4aa2-b603-27257ff6e627`). These uuid strings store current time and so can be parsed in timestamp or formatted string date.

### gen_jid

Because using formated `datetime.datetime.now()` allow lot of conflicts, I chose to use something more robust, uuid is done for that, so I thought the best thing to do is to use uuid and find a way to store timestamp within.

So in `salt.utils.jid.gen_jid` I now create a classic `uuid4` instance and replace the first field of this uuid by the current timestamp. Like it, even if two jid are created in the exact same time chance of conflict is really low, not impossible, but way less likely.

### jid_to_time

Jid are not returned as `uuid.UUID` instance but as string, so, to extract time from given jid `jid_to_time` will instantiate an `uuid.UUID` from given jid string and will extract its first field where timestamp is stored.

Btw I cleaned the method to compute date string by using `strftime`.

### is_jid

Just check if given string is a well formatted uuid string and check than first field is not empty or 0.

## salt.returners.local_cache

I finally add a single chance to handle conflict. I added an more explicit log that make possible to follow jid over conflicts by reading logs.

## Tests

Hm, "integration" tests file `tests/integration/returners/test_local_cache.py` was removed since I started this PR. I was struggling on this one, so I will test it anyway on my host.

I'm not sure failed tests on my host are really failing or not (maybe tests needs to be on a vm or stuff like that). I currently continue to test all that and dig in tests log to be sure, so maybe some news commits will append.

## Guys, I need you

Well, maybe I change to much thing in one single PR, don't know. But I know this can be a critic update, you know salt way better than me, I count on you to check this, if tests are ok, it should be ok, but a human point of view will make me more confident.

_wow, what a long post_

2017-05-04 13:09 UTC, arount commented
Hu, last thing, guys, tell me if the idea of using uuid is a good one for you, I like this solution, but maybe I'm the only one :)

2017-05-04 13:36 UTC, arount commented
erf, got conflict :/ Let me check that

2017-05-22 17:26 UTC, thatch45 commented
@arount I am sorry that you have put so much effort into this, but changing the jid format in this way will break many external salt applications, as well as many returners inside of Salt and can break many jid checks and validations. I also don't see the benefit of this PR, while the recursive approach does pin a few extra cycles it is far from being a bottle neck on the master and is only hit in the case of a collision.
Sorry, but I am going to close this out.

2017-05-22 17:26 UTC, closed without merging

2017-05-24 12:04 UTC, arount commented
@thatch45 No worries, I understand and anyway don't have enough time to finish it like I would like.
See you on smaller PRs so :)

2017-05-24 15:45 UTC, thatch45 commented
Thanks for being understanding, I hate to let people down!