Support for default item in match.filter_by #23050
saltstack/salt pull request #40168
Opened 2017-03-20 20:39 UTC by fungus

### What does this PR do?
Adds a default parameter to the match.filter_by function.  This allows custom return for no matches found.
### What issues does this PR fix or reference?
#23050
### Previous Behavior
Returns None on no matches.

### Tests written?
No

2017-03-20 20:52 UTC, whiteinge requested changes
Sorely needed addition. Thanks for diving in and getting it added! Just a few notes.

2017-03-20 20:52 UTC, whiteinge commented on salt/modules/match.py
> +        }, default=['other']) %}
`default='web*'` perhaps?

2017-03-20 20:52 UTC, whiteinge commented on salt/modules/match.py
> +    return default
Should be `lookup.get(default, None)`

2017-03-20 20:52 UTC, whiteinge commented on salt/modules/match.py
> +              default=None):
I'd suggest using `default='default'` to match the grains function.

2017-03-20 21:11 UTC, fungus commented
Got it.  I thought it made more sense to specify a default value, instead of a default key in the lookup table.  However, matching the behavior of grains.filter_by is more important.  Commit added.

2017-03-20 21:46 UTC, whiteinge approved these changes

2017-03-20 21:46 UTC, whiteinge commented
Thank you!

2017-03-21 15:25 UTC, cachedout approved these changes

2017-03-21 15:25 UTC, merged

2017-03-21 15:26 UTC, cachedout commented
Thank you very much, @fungus