Fix: Configs are read multiple times
saltstack/salt pull request #40181
Opened 2017-03-21 13:54 UTC by isbm

## What does this PR do?

### Reduces number of config is read.
Salt unnecessarily reads same configs multiple times. E.g. five workers reading eight little configs more than 240 times!

The idea is to cache the `__opts__` in the reference and return it from there, instead of read and parse the whole YAML file all over again.

### Fixes crash
 If one of configs is not readable (permission denied), Salt Master goes rock-n-roll. This happens when Salt Master, running as `salt:salt` meets config that is `root:root`.

### Tests written?

No

2017-03-21 15:22 UTC, gtmanfred approved these changes

2017-03-21 15:49 UTC, cachedout commented
@isbm Could you rebase this against the head of 2016.11 please? I want to get a clean test run before this gets merged. Thanks.

2017-03-21 20:29 UTC, isbm commented
@cachedout here you go!

2017-03-22 14:17 UTC, vutny approved these changes
:+1:

2017-03-22 14:17 UTC, vutny commented on salt/config/__init__.py
> +    if (not salt.utils.validate.path.exists(path, quiet=os.path.basename(path) == '.saltrc')
What is `.saltrc` by the way?

2017-03-22 14:40 UTC, isbm commented on salt/config/__init__.py
> +    if (not salt.utils.validate.path.exists(path, quiet=os.path.basename(path) == '.saltrc')
@vutny it is an _optional_ config file that can sit in home of user that executes e.g. minion and if something `echo "master: google.com"` to it, you will have rock-n-roll understanding why the heck your minion connects to google. :laughing:

2017-03-22 14:42 UTC, isbm commented on salt/config/__init__.py
> +    if (not salt.utils.validate.path.exists(path, quiet=os.path.basename(path) == '.saltrc')
Because it is optional and forgotten entity (and normally never used), this is why I muted it to the logs.

2017-03-22 16:55 UTC, cachedout approved these changes

2017-03-22 17:16 UTC, thatch45 approved these changes

2017-03-22 17:43 UTC, damon-atkins commented
It's good to see salt exits if it can not read a configuration file if it exists.  Wasted many of hour with another  product because config files had issues but no error/warnings were  sent to the log files. In fact the product said it read the file successfully when it did not.

2017-03-22 18:19 UTC, s0undt3ch requested changes

2017-03-22 18:19 UTC, s0undt3ch commented on salt/utils/validate/path.py
> +        log.error('Failed to read configuration from {0} - file does not exists'.format(path))
_File does not exist_, singular.

2017-03-22 18:20 UTC, s0undt3ch commented on salt/utils/validate/path.py
> +        log.error('Failed to read configuration from {0} - file does not exists'.format(path))
But I'm Portuguese so I could be wrong :)

2017-03-22 18:20 UTC, cachedout commented on salt/utils/validate/path.py
> +        log.error('Failed to read configuration from {0} - file does not exists'.format(path))
Good catch.

2017-03-22 21:48 UTC, isbm commented on salt/utils/validate/path.py
> +        log.error('Failed to read configuration from {0} - file does not exists'.format(path))
@s0undt3ch fixd.

2017-03-22 21:49 UTC, isbm commented
@damon-atkins I didn't finished with configs. :-) Many things are still coming. But not in _this_ PR, sorry.

2017-03-22 22:27 UTC, cachedout commented
Should be ready to go after the tests run.

2017-03-23 09:01 UTC, isbm commented
@cachedout @s0undt3ch the unit test was crashing for cloud config, because it was assuming that re-read from the disk will update data. That was exactly what this PR is fixing: if someone/something changes config right during Salt starts, then you end up with a spaghetti of different configs within the same worker.

2017-03-23 12:11 UTC, s0undt3ch commented on salt/utils/validate/path.py
> +        log.error('Failed to read configuration from {0} - file does not exists'.format(path))
Bragger! ;)

2017-03-23 12:20 UTC, s0undt3ch approved these changes

2017-03-23 15:04 UTC, cachedout commented
These integration test failures are still surprising, though. I'll see if I can replicate these when running them locally.

2017-03-23 15:19 UTC, isbm commented
@cachedout Unit tests are passing, actually.

2017-03-23 16:57 UTC, s0undt3ch commented
@cachedout not if the latest docker changes made by @terminalmage are not yet part of this PR.

@isbm a pull and rebase against the latest develop branch would clear things up.

2017-03-23 16:58 UTC, s0undt3ch commented
Oh wait! There's more failures now....

2017-03-23 16:58 UTC, cachedout commented
@s0undt3ch I'm not sure why the Docker changes would affect a failing integration test for batching? Though a rebase wouldn't hurt I'm sure. :]

2017-03-23 17:16 UTC, s0undt3ch commented
@cachedout they wouldn't, I looked at the test results this morning and only the docker tests were failing, however, now, there's more, so, ignore my comment.

2017-03-23 17:20 UTC, cachedout commented
@s0undt3ch OK, we're on the same page now then. :]

@isbm Yes, the unit tests are passing but integration tests still seem to be failing as a result of this change.

2017-03-24 13:12 UTC, isbm commented
@cachedout @s0undt3ch OK, we have here the same problem as with the Unit tests: integration assumes that configs gets re-read just like that. But this is exactly now (partly) fixed design problem: config *should* be read only _once_. And an operation for reading config should be different from the operation of getting it. This part still comes though. At the moment I went to the compromise whether config is read once (well, almost, since different workers are still re-reading them all over again) and then its cache returned when requested once again (within one worker). I don't know (yet) what would be the best way of sharing data across workers (pyro? shared memory? anything else?). Also at the moment there is no way to reload config. But my next move would be implementing hot configuration (i.e. configure Salt on hot running without rebooting it). I was thinking about how to do it efficiently, and I think I have an idea.

But the integration tests built otherwise and does hard with configs ([example](https://github.com/saltstack/salt/blob/develop/tests/integration/__init__.py#L1299-L1337) — wow, BTW). So we need to update also integration test suite.

@thatch45 — **Q:** what was the reason to always read configs on each instance instead of sharing one, parsed?

@s0undt3ch maybe we can look at [this](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9923/testReport/junit/integration.runners.jobs/ManageTest/test_active/) [this](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9923/testReport/junit/integration.runners.manage/ManageTest/test_up/) and [this](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9923/testReport/junit/integration.runners.state/StateRunnerTest/test_orchestrate_output/) together in the meanwhile? They're actually seems having the same source of issue, probably will go away of one fix.

P.S. Unit tests are passing...

2017-03-24 18:58 UTC, thatch45 commented
In many cases the re-read is due to sectioning off parts of the code for reuse early on and then integrating them more tightly as the organic growth of a feature pull it back in.
Basically there are a lot of times when good intentions don't pan out over time and it concludes in sub-optimal results.

2017-03-24 19:44 UTC, isbm commented
@thatch45 thanks for clarifying that! I had the same impression that it is just grew up overtime and not always where intended to. So seems we are on the right path.

2017-03-24 20:17 UTC, thatch45 commented
I agree that we are. There are a lot of places where things like config loading and disk hits can be improved. I don't doubt the overall design, but things creep in over time when the intent and needs of interfaces shift with macro changes in the codebase.

2017-03-25 10:59 UTC, isbm commented
@thatch45 Well, then let's continue hammering it for better.
@cachedout I will look at these integration failures from Monday on.

2017-03-27 21:22 UTC, cachedout commented
Go Go Jenkins!

2017-03-28 17:17 UTC, cachedout commented
@isbm Any updates here on the integration test failures?

2017-04-06 18:30 UTC, cachedout commented
Bump @isbm

2017-04-13 15:50 UTC, cachedout commented
@isbm Since we didn't get a response from you, I am closing this until you're ready to come back to it. When you are, just drop me a line and we'll re-open it. Thanks very much.

2017-04-13 19:55 UTC, isbm commented
@cachedout please reopen it back. I am working on it and have it as a pending-to-finish task. We just have lots of other rain of way more important issues, so I cannot be always on upstream, sorry.

2017-04-13 20:01 UTC, isbm commented
@cachedout and sorry not pinging back. It was just... Hell unleashed lately bugwise. :laughing:

2017-04-13 20:02 UTC, cachedout commented
@isbm No worries at all. Sorry to hear you're so busy. Hope things improve. :]

2017-04-13 20:07 UTC, isbm commented
@cachedout they do. Easter now, holidays... :laughing:

2017-04-19 14:00 UTC, isbm commented
@cachedout [OK, I am back](https://www.youtube.com/watch?v=6vImyP5EYc8) wow, and it even doesn't need to be rebased. Yet. :laughing:

2017-04-22 08:50 UTC, isbm commented
@cachedout * soon *. I want to get rid of this as well. :laughing:

2017-05-02 17:27 UTC, cachedout commented
Hi @isbm. Just checking in with you again. :]

2017-05-04 12:30 UTC, isbm commented
@cachedout yep, looking now.

2017-05-22 17:16 UTC, cachedout commented
Go Go Jenkins!

2017-05-24 15:02 UTC, isbm commented
Seems like `LocalClient` doesn't like this change (yet).

2018-04-10 20:31 UTC, cachedout commented
@isbm I would like to see if we can get this in. Do you want to resolve the merge conflict and then let's see if we can get the failing tests to pass?

2018-04-10 20:31 UTC, cachedout commented
Also, let's get this moved over to the develop branch.

2018-05-15 15:52 UTC, rallytime commented
Hey @isbm - Since 2016.11 is closed to any fixes now and this needs a rebase anyway, I'm going to close this. Can you resubmit against `develop` as @cachedout mentioned above? Of course, reach out if you have any questions/concerns. Thank you!

2018-05-15 15:52 UTC, closed without merging