More PY3 fixes in test suite
saltstack/salt pull request #40234
Opened 2017-03-22 21:15 UTC by terminalmage

This fixes a couple netapi tests, and also adds the needed bits in runtests.py to make --grains tests actually run when that argument is passed.

@whiteinge can you have a look at the netapi test fixes? One involved a response coming back from cherrypy as a bytestring (which ``json.dumps()`` did not like), and another involved the event from tornado containing bytestrings. I assumed these were expected changes to the return in both cases, so I updated the tests to deal with the fact that the reponses come back containing bytestrings. I just want to make sure that is the correct fix.

2017-03-22 21:44 UTC, s0undt3ch requested changes

2017-03-22 21:44 UTC, s0undt3ch commented on tests/integration/netapi/rest_cherrypy/test_app.py
> +        resp = json.loads(salt.utils.to_str(response.body[0]))
Get the encoding from the headers and use that. to_str will use the filesystem encoding which is not what we need here.

2017-03-22 21:44 UTC, s0undt3ch commented on tests/integration/netapi/rest_tornado/test_app.py
> +                {'foo': salt.utils.to_bytes('bar')}
This is probably safe here since its the event system, in our control.

2017-03-23 00:34 UTC, terminalmage commented on tests/integration/netapi/rest_cherrypy/test_app.py
> +        resp = json.loads(salt.utils.to_str(response.body[0]))
The encoding is not in the headers, here's a dump of the headers:

```python
{'Access-Control-Allow-Credentials': 'true',
 'Access-Control-Allow-Origin': '*',
 'Access-Control-Expose-Headers': 'GET, POST',
 'Allow': 'GET, HEAD, POST',
 'Cache-Control': 'private',
 'Content-Length': 65,
 'Content-Type': 'application/json',
 'Date': 'Thu, 23 Mar 2017 00:29:20 GMT',
 'Server': 'CherryPy/10.2.1',
 'Vary': 'Accept-Encoding'}
```

2017-03-23 00:36 UTC, whiteinge approved these changes
@s0undt3ch's suggestion is a good one but I'm not sure the faux test server will have that encoding header present. (My dev env isn't working ATM to verify.)

I'm still pretty unknowledgeable about the move to bytestrings in Py3 but I pulled down the latest develop (f1686009b3ff) to test those changes on Py2 and everything looks to be working as normal. So if this change fixes the test then it's ok by me. ¯\_(ツ)_/¯

2017-03-23 09:08 UTC, s0undt3ch commented on tests/integration/netapi/rest_cherrypy/test_app.py
> +        resp = json.loads(salt.utils.to_str(response.body[0]))
Wait! Wait!
Sorry @terminalmage, I was being dumb.
The content type is  'application/json', so it must be UTF-8, and in this case, pass it explicitly.

2017-03-23 09:14 UTC, s0undt3ch commented
The failures are unrelated, and my suggestion to pass utf-8 explicitly is not a blocker. Merging.

2017-03-23 09:15 UTC, s0undt3ch approved these changes

2017-03-23 09:15 UTC, merged