Add boto_elbv2 states and modules for de/registering targets and chec…
saltstack/salt pull request #40263
Opened 2017-03-23 16:29 UTC by deuscapturus

Add boto_elbv2 states and modules for de/registering targets and checking health of AWS Application Load Balancer target groups.

### What does this PR do?

Add module and state for boto elbv2

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-03-23 20:35 UTC, cachedout requested changes
Hi @deuscapturus 

We need some minor lint fixes, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9807/violations/

2017-03-26 15:12 UTC, deuscapturus commented
@cachedout I'm finally past the lint checker.

2017-03-28 00:01 UTC, cachedout commented on salt/modules/boto_elbv2.py
> +            msg = 'The load balancer does not exist in region {0}'.format(region)
This doesn't appear to be used?

2017-03-28 00:01 UTC, cachedout commented on salt/states/boto_elbv2.py
> +        changes = False
This could just be `failure = changes = False` if you like.

2017-03-28 02:04 UTC, deuscapturus commented on salt/states/boto_elbv2.py
> +        changes = False
That's not my style.  It's your choice though.

2017-03-28 02:07 UTC, deuscapturus commented on salt/modules/boto_elbv2.py
> +            msg = 'The load balancer does not exist in region {0}'.format(region)
What do you mean?

2017-03-28 04:40 UTC, cachedout commented on salt/states/boto_elbv2.py
> +        changes = False
Not a requirement at all. Just a suggestion. We're totally fine either way. :]

2017-03-28 04:42 UTC, cachedout commented on salt/modules/boto_elbv2.py
> +            msg = 'The load balancer does not exist in region {0}'.format(region)
Unless I'm just totally misreading this (which is possible!) the `msg` variable is set and then we immediately `return False`, without doing anything with the message at all. Did you intend to log that message?

2017-03-28 05:18 UTC, deuscapturus commented on salt/modules/boto_elbv2.py
> +            msg = 'The load balancer does not exist in region {0}'.format(region)
oh yeah.. that was supposed to go to `log`.  latest commit fixes that.

2017-03-28 17:15 UTC, cachedout approved these changes

2017-03-28 17:15 UTC, merged