Add NAPALM section in Nitrogen release notes
saltstack/salt pull request #40302
Opened 2017-03-24 13:23 UTC by mirceaulinic

### What does this PR do?

2017-03-24 16:48 UTC, rallytime approved these changes

2017-03-24 17:00 UTC, cachedout requested changes

2017-03-24 17:00 UTC, cachedout commented on doc/topics/releases/nitrogen.rst
> +Introduced in 2016.11, the modules for cross vendor network automation
`cross-vendor`

2017-03-27 23:25 UTC, cachedout approved these changes

2017-03-28 02:45 UTC, merged