Add ip protocol to logstash engine
saltstack/salt pull request #40304
Opened 2017-03-24 15:42 UTC by vquiering

### What does this PR do?
This adds the ability to choose the protocol when using the logstash engine.

### What issues does this PR fix or reference?
#40257 

### Previous Behavior
Engine was using udp no matter what. Was not documented though.

### New Behavior
Add proto option to engine config and choose whether to use udp or tcp in your logstash input config.

2017-03-24 22:42 UTC, rallytime requested changes

2017-03-24 22:42 UTC, rallytime commented on salt/engines/logstash.py
> +def start(host, port=5959, proto='tcp', tag='salt/engine/logstash'):
Can you move the new `proto` kwarg to the end of the list so we don't have an API change here? Otherwise I think this looks good.

2017-03-25 11:12 UTC, vquiering commented
@rallytime I just changed the list order as requested.

2017-03-27 14:49 UTC, rallytime approved these changes

2017-03-27 14:51 UTC, merged

2017-03-27 15:20 UTC, gtmanfred commented
Didn't we find out that the default that the logstash engine was using was udp in the issue?

Shouldn't we set the default to udp instead of tcp so that people don't need to change their configurations since we are not adding a warning message?

At the least we should make a note in the release notes for nitrogen.

Thanks,
Daniel

2017-03-27 15:29 UTC, rallytime commented
@gtmanfred Oh! Good catch. I agree that we should stick with the original default. Sorry about that.

@vquiering Would you mind making a new PR with the changes requested above?

2017-03-27 18:14 UTC, vquiering commented
@rallytime 
Done. Defaults to udp now.

2017-03-27 20:03 UTC, rallytime commented
Wonderful! Thank you!