Move unit tests which were in integration tests
saltstack/salt pull request #40339
Opened 2017-03-27 16:55 UTC by s0undt3ch

This needs to be merged after https://github.com/saltstack/salt/pull/40138 is merged

2017-03-28 15:15 UTC, cachedout requested changes
Just one lint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9957/violations/file/tests/unit/utils/test_docker.py/

2017-03-30 18:52 UTC, s0undt3ch commented
Go Go Jenkins!

2017-03-30 19:34 UTC, s0undt3ch commented
Go Go Jenkins!

2017-03-30 22:45 UTC, cachedout approved these changes

2017-03-31 19:44 UTC, s0undt3ch commented
@cachedout this should be ready for you to take another look

2017-03-31 20:02 UTC, s0undt3ch commented on tests/unit/modules/test_file.py
> +            print(8888, ret)
Bah!

2017-03-31 20:02 UTC, s0undt3ch commented on tests/unit/netapi/rest_tornado/test_handlers.py
> +# Import Salt libse
Fix comment

2017-03-31 21:21 UTC, s0undt3ch commented
Fixed my own review comments.

2017-04-01 23:33 UTC, s0undt3ch commented
Go Go Jenkins!

2017-04-02 00:41 UTC, s0undt3ch commented
Go Go Jenkins!

2017-04-02 09:20 UTC, s0undt3ch commented
Cachim!

2017-04-02 16:55 UTC, s0undt3ch commented
@cachedout this is ready for a final review. No more commits will be added to this PR.

2017-04-04 16:21 UTC, cachedout approved these changes

2017-04-04 16:21 UTC, merged

2017-04-04 16:23 UTC, s0undt3ch commented
Woohoo!!!! Gimme a few mins for another one like this :)