New engine: Napalm syslog
saltstack/salt pull request #40458
Opened 2017-03-31 16:13 UTC by mirceaulinic

### What does this PR do?

Defines a new engine taking events from a third party library called napalm-logs and publishes them on the Salt bus. The events format respects the OpenConfig and IETF standards.

2017-03-31 20:18 UTC, cachedout requested changes
I really like this!

Just one small change requested though. See the in-line comment. This should be really nice to get in. Strong work!

2017-03-31 20:18 UTC, cachedout commented on salt/engines/napalm_syslog.py
> +import zmq
Not everybody uses Salt with ZeroMQ. This should be gated.

2017-03-31 23:22 UTC, mirceaulinic commented on salt/engines/napalm_syslog.py
> +import zmq
No problem - added in https://github.com/saltstack/salt/pull/40458/commits/75c64bfe453d86f2f19a41fac5d2ccc49a40739b.

2017-04-03 19:18 UTC, mirceaulinic commented
Hi @cachedout - I have solved the changes requested.

2017-04-03 22:27 UTC, cachedout approved these changes

2017-04-03 22:27 UTC, merged