Enhance/module/hadoop
saltstack/salt pull request #40472
Opened 2017-03-31 22:50 UTC by daxroc

### What does this PR do?
Backward compatible Enhancement for hadoop module to use hdfs tool over deprecated hadoop

### New Behavior
Uses hdfs tool to perform the same commands enabled with optional arguments as described in the documentation

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-04-01 17:29 UTC, s0undt3ch reviewed
Is hdfs the new CLI binary? An alternative binary? We could probably search `$PATH` for the hdfs binary and then the dfs binary in this order since the new one is backwards compatible with the old one?
This would remove the need to explicitly pass `use_hdfs`?

These are basically questions to see if we can support both more transparently....

2017-04-01 17:29 UTC, s0undt3ch commented on salt/modules/hadoop.py
> +    if module in __authorized_modules__:
Are these tabs? Indentation should be a multiple of 4 spaces and no tabs.

2017-04-01 19:22 UTC, daxroc commented
@s0undt3ch made the adjustments to transparently use hdfs if available and fallback on hadoop if not. Refactored the version to use the same command wrapper. And some minor changes on lint recommendations.

Thanks for the feedback - appreciated!

2017-04-01 20:26 UTC, s0undt3ch commented on salt/modules/hadoop.py
>      return (False, 'The hadoop execution module cannot be loaded: hadoop binary not in path.')
_hadoop or hdfs not found_

2017-04-01 20:26 UTC, s0undt3ch commented on salt/modules/hadoop.py
> +    trailing argument of use_hdfs will use hdfs command for execution
The docstring here is still valid?

2017-04-04 20:10 UTC, cachedout requested changes
A test has failed. Could you please take a look?

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10295/testReport/junit/unit.modules.test_hadoop/HadoopTestCase/test_version/

2017-04-04 21:43 UTC, daxroc commented
Reverted version method back - worked as it should have. My bad ...

2017-04-05 17:29 UTC, cachedout approved these changes

2017-04-05 17:30 UTC, merged