Fix for https://github.com/saltstack/salt/issues/38472
saltstack/salt pull request #40546
Opened 2017-04-05 19:20 UTC by jinm

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-04-05 21:13 UTC, rallytime commented
Refs #38472

2017-04-06 02:41 UTC, terminalmage requested changes
See my comments for required changes.

2017-04-06 02:41 UTC, terminalmage commented on salt/modules/file.py
> +            elif cached_sum != source_sum.get('hsum', __opts__.get('hash_type', 'md5')):
We should not be using ``__opts__.get()`` here, nor falling back to md5, for reasons I explain further in [this pull request](https://github.com/saltstack/salt/pull/40552), which I have just opened to fix similar references in the 2016.3 branch.

Please change this to ``__opts__['hash_type']``

2017-04-06 02:42 UTC, terminalmage commented
@rallytime once the requested changes have been made and this has been merged, it will need a backport to 2016.11.

2017-04-06 04:14 UTC, jinm commented
@rallytime @terminalmage the change is in.

2017-04-06 14:07 UTC, terminalmage commented
There was no need to make the other changes in develop, because https://github.com/saltstack/salt/pull/40552 would have taken care of this when merged forward.

There are a lot of failing tests, but it looks like these might have been broken in develop when you branched. Can you please fetch from our develop branch and rebase?

```
git remote add upstream https://github.com/salstack/salt
git fetch upstream
git rebase upstream/develop
git push origin develop --force
```

2017-04-06 17:04 UTC, terminalmage commented
https://github.com/saltstack/salt/pull/40559 seems to have been opened instead of just rebasing this one. Closing in favor of https://github.com/saltstack/salt/pull/40559.

2017-04-06 17:04 UTC, closed without merging