wake on lan match with grains cache
saltstack/salt pull request #40664
Opened 2017-04-12 18:33 UTC by gtmanfred

### What does this PR do?
Allow using the grains cache to `wake on lan` minions

### Tests written?

No

2017-04-12 21:10 UTC, cachedout requested changes

2017-04-12 21:10 UTC, cachedout commented on salt/runners/network.py
> +        salt-run network.wol minion_id
These docstrings are incorrect.

2017-04-12 23:00 UTC, s0undt3ch requested changes

2017-04-12 23:00 UTC, s0undt3ch commented on salt/runners/network.py
> +import logging
Group python imports on top

Yeah, being picky, sorry... :)

2017-04-13 19:18 UTC, gtmanfred commented on salt/runners/network.py
> +import logging
no worries!
fixed!

2017-04-13 19:33 UTC, cachedout approved these changes

2017-04-13 19:59 UTC, merged