Fix errno code for filecache test for other operating systems.
saltstack/salt pull request #40685
Opened 2017-04-13 19:08 UTC by Ch3LL

### What does this PR do?
Not all operating systems include the `EREMOTEIO` errno code so had to replace with `EIO` for operating systems. This test was failing on MacOSX with the folloinwg error:

```
*** unit.fileclient_test.FileclientTestCase.test_cache_raises_exception_on_non_eexist_ioerror Tests  ***********************************************************************
 --------  Tests with Errors  ----------------------------------------------------------------------------------------------------------------------------------------------
   -> unit.fileclient_test.FileclientTestCase.test_cache_raises_exception_on_non_eexist_ioerror  ...........................................................................
       Traceback (most recent call last):
         File "/testing/tests/unit/fileclient_test.py", line 51, in test_cache_raises_exception_on_non_eexist_ioerror
           with patch('os.makedirs', self._fake_makedir(num=errno.EREMOTEIO)):
       AttributeError: 'module' object has no attribute 'EREMOTEIO'
   .........................................................................................................................................................................
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
============================================================================================================================================================================
FAILED (total=1, skipped=0, passed=0, failures=0, errors=1) 
==========================================================================  Overall Tests Report  ==========================================================================

```

### Tests written?

Yes

2017-04-13 19:58 UTC, isbm commented
OMG, why this is different on OSX... :cry: @Ch3LL please dump that try/except thing. I picked up this error number to be just a different than IO Error. Feel free to pick up anything that is common on OSX and Linux. :-)

2017-04-13 19:59 UTC, isbm requested changes
Sorry it is different on OSX... :-( Please remove all that and simply pick up another error code. It can be anything, e.g. `EROFS` or `EUCLEAN` etc.

2017-04-13 21:10 UTC, Ch3LL commented
Thanks for the input. I was not sure if you were using `EREMOTEIO` for a specific reason. I changed it to `EIO` since that seems to be on all operating systems. :)

2017-04-13 22:11 UTC, Ch3LL commented
Pushed another change. I re-read your comment and realized you didn't want IO. Makes sense. Hows it look now?

2017-04-14 13:08 UTC, isbm commented
@Ch3LL you can just use any error number, other than OS Error. The UT should quack about anything, and stay silent if `errno.EEXIST` appears. :smile:

2017-04-14 13:44 UTC, Ch3LL commented
K perfect thanks

2017-04-14 16:54 UTC, merged