Update win_pki.py
saltstack/salt pull request #40879
Opened 2017-04-25 12:57 UTC by peter-funktionIT

### What does this PR do?
Adds password support to win_pki.get_cert_file

### What issues does this PR fix or reference?
Current implementation does not support pfx with password.

get_cert_file will not work with a password-protected pfx, therefore neither will import_cert (since it calls get_cert_file to get certificate properties).

### Tests written?

Yes/No

2017-04-25 16:03 UTC, twangboy approved these changes

2017-04-26 15:07 UTC, rallytime commented
Hi @peter-funktionIT - It looks like this is failing some pylint errors. Can you clean those up please? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10676/violations/file/salt/modules/win_pki.py/

2017-04-26 18:23 UTC, cachedout requested changes

2017-04-26 18:23 UTC, cachedout commented on salt/modules/win_pki.py
> +        format.
I believe you forgot to add this to the function's list of arguments. :]

2017-04-26 20:01 UTC, peter-funktionIT commented on salt/modules/win_pki.py
> +        format.
Quite right, thank you!
Fixed now.

2017-04-27 01:59 UTC, damon-atkins commented
Wont every minion see this password when applied only to one system?  As command is broadcast to every salt-minion to accept/reject.   How are passwords normal passed?

2017-05-01 16:49 UTC, cachedout commented
@damon-atkins If used directly, then yes. Though, it's certainly possible to call this execution module from a state, for example, and then substitute in the password with one taken from pillar, which could then be locked down do only authorized minions. That said, perhaps a warning on the function here would be good?

2017-05-01 17:00 UTC, damon-atkins commented
Warning in the doco sounds good. I assume password would be in some logs as well depending on how its called/run.

2017-05-02 16:42 UTC, cachedout commented on salt/modules/win_pki.py
> +        format.
Could we add a warning in the documentation stating that this password will be seen by all minions? See the discussion below on this.

2017-05-04 16:11 UTC, cachedout approved these changes

2017-05-04 16:12 UTC, merged