Remove warnings about md5 hash-type for Nitrogen
saltstack/salt pull request #40899
Opened 2017-04-26 16:31 UTC by rallytime

Refs #40543

2017-04-26 19:56 UTC, cachedout approved these changes

2017-04-27 11:22 UTC, cachedout approved these changes

2017-04-27 11:29 UTC, cachedout requested changes

2017-04-27 11:29 UTC, cachedout commented on salt/modules/ssh.py
> +        hash_type = 'sha256'
Looks like this is breaking the tests.

2017-05-01 18:52 UTC, rallytime commented
Go Go Jenkins!

2017-05-02 22:22 UTC, rallytime commented
@cachedout These failing tests should be fixed now. :)

2017-05-03 16:55 UTC, cachedout approved these changes

2017-05-03 16:55 UTC, merged

2017-05-03 22:49 UTC, rallytime commented
This is causing the tests to hang on the nitrogen branch right here:
```
17:12:57 Starting External Pillar Tests
17:12:57 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:12:57 
17:12:57 Running tests...
17:12:57 ----------------------------------------------------------------------
17:12:57   test_includes_disabled (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:100.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_includes_enabled (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_dev_master_merge_lists (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_dev_master_no_merge_lists (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_master_dev_merge_lists (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_master_dev_no_merge_lists (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_with_pillarenv (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_single_source (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_includes_disabled (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:100.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_includes_enabled (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_dev_master_merge_lists (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_dev_master_no_merge_lists (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_master_dev_merge_lists (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_master_dev_no_merge_lists (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_multiple_sources_with_pillarenv (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:100.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_single_source (integration.pillar.test_git_pillar.TestGitPythonHTTP)
17:12:57 [CPU:0.0%|MEM:73.7%]  ... SKIP (0.001s)
17:12:57   test_includes_disabled (integration.pillar.test_git_pillar.TestGitPythonSSH)
17:12:59 [CPU:100.0%|MEM:73.7%]  ... ERROR (2.482s)
17:12:59   test_includes_enabled (integration.pillar.test_git_pillar.TestGitPythonSSH)
17:13:04 The authenticity of host '[127.0.0.1]:39093 ([127.0.0.1]:39093)' can't be established.
17:13:04 RSA key fingerprint is SHA256:vZmsqXbFBKUmMD6eCLItW5rl5xGGWI/eB/EkXpkAmJc.
```
So I am reverting this for now. I'll have to resubmit once those tests are fixed.