[Feature] Turns a gitfs remote into a true "formula" merges into all saltenvs
saltstack/salt pull request #40985
Opened 2017-05-01 13:31 UTC by ekristen

Thank you to @terminalmage for taking the time to give me basically everything I needed to implement this in a comment on the original issue. Very much appreciated.

### What does this PR do?
It enables a gitfs remote to be a true formula, or a global one, when set, all states from the referenced branch are merged into whichever saltenv is actually being referenced.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/40527

### How to use and test this feature.
Add the following to your salt-minion (for a masterless test) config.

```yaml
environment: testing
fileserver_backend:
  - git
gitfs_remotes:
  - https://github.com/ekristen/salt-states-testing.git
  - https://github.com/ekristen/salt-formula-testing.git
```

If you inspect `https://github.com/ekristen/salt-states-testing.git` you'll find a testing branch and if you inspect `https://github.com/ekristen/salt-formula-testing.git` you will NOT find a testing branch. Given this setup, if you run the following command `salt-call --local state.sls testing` it will succeed (as it is from the first repo), however if you run `salt-call --local state.sls formula` it will fail as there is no `testing` branch on the second repository.

Modify the config so it looks like this.

```yaml
environment: testing
fileserver_backend:
  - git
gitfs_remotes:
  - https://github.com/ekristen/salt-states-testing.git
  - https://github.com/ekristen/salt-formula-testing.git:
    - formula: master
```

Then rerun the commands, first `salt-call --local state.sls testing` it will still resolve and run, and now `salt-call --local state.sls formula` this time it will resolve and run appropriately. 

### Tests written?
No - I looked at the gitfs tests and there did not seem to be an appropriate way or place to test this new feature within the current test suite for gitfs.

2017-05-01 14:01 UTC, terminalmage requested changes

2017-05-01 14:01 UTC, terminalmage commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
I thought we discussed naming this as ``global``, not ``formula``. This feature is useful for more than just formulas, so giving it such a specific name seems wrong.

2017-05-01 14:03 UTC, ekristen commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
@terminalmage my bad! I forgot to mention when I typed up the original PR, I tried global, but it kept throwing a syntax error, seems to be a reserved keyword.

2017-05-01 14:07 UTC, ekristen commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
Perhaps a synonym? `world`, `wordwide`, or `universal` (I think I like universal the best?)

2017-05-01 14:14 UTC, terminalmage commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
Oh, interesting. I've never tried using ``global`` as a class attribute, so I've never run into this syntax error before. I'll try to brainstorm some ideas as well.

2017-05-01 14:17 UTC, terminalmage commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
What about ``all_saltenvs``?

2017-05-01 14:21 UTC, ekristen commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
That works for me, the value would still be the branch name I assume?

2017-05-01 14:23 UTC, terminalmage commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
Yeah. If you're comfortable writing RST, this should be documented in the gitfs documentation page at doc/topics/tutorials/gitfs.rst. If not, I can take care of documentation.

2017-05-01 14:27 UTC, terminalmage commented
Don't worry about tests, we have limited test coverage for gitfs but I've been working on a framework which will make it easier to do integration tests on git_pillar and gitfs (https://github.com/saltstack/salt/pull/40777). Writing new integration tests for gitfs is something I have plans for soon anyway, and I can make sure something like this is covered.

2017-05-01 14:40 UTC, ekristen commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
I'm fine with writing RST. I can take a stab at adding some initial docs in.

2017-05-01 14:49 UTC, terminalmage commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
Cool. I can help polish them if they need to be tweaked in any way.

Thanks for taking this on, I'm really excited about this feature!

2017-05-01 14:58 UTC, ekristen commented on salt/fileserver/gitfs.py
> +PER_REMOTE_ONLY = ('formula', 'name', 'saltenv')
Glad to help, this will be very useful for me.

2017-05-01 15:01 UTC, ekristen commented
@terminalmage I did notice the original issue was slated for `Oxygen` but I assume that was based on if you had to do all the work, with an open PR now, might it be possible to get it merged for an upcoming release?

For now I left all documentation notes to reference Oxygen.

2017-05-01 15:43 UTC, terminalmage commented
We've passed the feature freeze for Nitrogen, so develop is the correct branch and Oxygen is the correct release.

2017-05-01 15:45 UTC, ekristen commented
Is there a timeline? https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html has TBD for both Nitrogen and Oxygen. Thanks!

2017-05-01 15:59 UTC, terminalmage commented
Nitrogen is expected late this month, with Oxygen in the fall (tentatively).

2017-05-01 19:48 UTC, cachedout commented
@terminalmage Can you re-review this and approve if you think it's ready?

2017-05-02 21:44 UTC, terminalmage commented
@ekristen I opened https://github.com/ekristen/salt/pull/1 against your fork which tweaks and builds upon the docs you added, and also modifies the gitfs code to add debug logging when a per-saltenv configuration is being overridden by ``all_saltenvs``. This is something I had not considered initially until I started testing the functionality of your PR.

Can you please merge that PR and then test and confirm that it still works to your liking? If so, and assuming tests pass, I think this is good to merge.

Thanks once again for your contribution.

2017-05-02 21:58 UTC, ekristen commented
@terminalmage I have merged your PR, I will test shortly and confirm all is working appropriately still.

2017-05-02 22:14 UTC, ekristen commented
@terminalmage everything works, the only comment I have is that the debug messages off a bit?

They seem to repeat multiple times, and always state `None` was mapped to `saltenv`. As you are way more familiar with the system I'll defer to you as to whether or not this is correct, just wanted to mention it.

```
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'base' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'base' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'base' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'base' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'base' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'testing' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
[DEBUG   ] The per-saltenv configuration has mapped the 'None' branch/tag to saltenv 'testing' for gitfs remote 'https://github.com/ekristen/salt-formula-testing.git', but this remote has all_saltenvs set to 'master'. The per-saltenv mapping will be ignored in favor of 'master'.
```

2017-05-03 14:03 UTC, terminalmage commented
That definitely is not correct. Change this line:

```python
if all_saltenvs_ref != per_saltenv_ref:
```

to

```python
if per_saltenv_ref and all_saltenvs_ref != per_saltenv_ref:
```

I didn't test it without a per-saltenv config, duh.  Thanks for catching this.

2017-05-03 17:06 UTC, cachedout commented
@terminalmage Looks like the requested change has been made. Requesting re-review.

2017-05-03 17:17 UTC, terminalmage approved these changes
LGTM. Thanks, @ekristen!

2017-05-03 17:17 UTC, merged

2017-05-03 19:31 UTC, ekristen commented
Thanks @terminalmage