Ensure strings in decorator
saltstack/salt pull request #41014
Opened 2017-05-02 19:20 UTC by cachedout

Fixes #40937

2017-05-05 18:28 UTC, terminalmage requested changes

2017-05-05 18:28 UTC, terminalmage commented on salt/utils/decorators/__init__.py
> +        args_ = ','.join([str(arg) for arg in args] + ['{0}={1}'.format(str(k), str(kwargs[k])) for k in sorted(kwargs)])
The problem with just using `str()` in PY2 is that it causes a ``UnicodeDecodeError`` when you do it on a unicode string:

```python
>>> x = [1, 2, 3, u'✓']
>>> x
[1, 2, 3, u'\u2713']
>>> y = [str(z) for z in x]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' in position 0: ordinal not in range(128)
```

So, while your code is more concise, an approach like [this](https://github.com/saltstack/salt/blob/c7c5266/salt/utils/timed_subprocess.py#L43-L49) would be better here.

2017-05-08 09:36 UTC, mamalos commented
@terminalmage 's comment is right. Thanks for the suggested solution.

2017-06-14 15:52 UTC, rallytime commented
I have switched the base branch on this pull request from `nitrogen` to `2017.7` in preparation for moving from a code-named release to a version number.

2017-06-20 17:31 UTC, cachedout commented on salt/utils/decorators/__init__.py
> +        args_ = ','.join([str(arg) for arg in args] + ['{0}={1}'.format(str(k), str(kwargs[k])) for k in sorted(kwargs)])
@terminalmage Updates made.

2017-06-20 18:13 UTC, terminalmage approved these changes
:+1:

2017-06-20 20:36 UTC, merged

2017-08-22 13:19 UTC, mamalos commented
Hi everybody!

Unfortunately this fix is buggy...first of all it broke some code I wrote (which means that I did not do my work well when you asked about my opinion before changing it :) ). But thanks to this bug I realised that I shouldn't have used the **memoize** decorator in the first place, so it turned out to be OK! :)

The first bug is in https://github.com/saltstack/salt/blob/2017.7.1/salt/utils/decorators/__init__.py#L254 (which for some reason is not present in **2017.7**), where we see that **args** is replaced with **str_args**, for some reason, which means that the actual arguments' list is changed (every argument is changed with its "string version") when this decorator is called. This, I suppose, shouldn't have been done (arguments should remain untouched). **2017.7** was correct wrt this problem.

The second bug that I see (and that it is based on the above discussion) is that the current code can hash wrong stuff. So, for example, a string argument (or keyword argument) with the value "False" will be cached over a boolean argument with the value False. So in order to be precise, the type of each argument should be added in the caching key as well. Hence, something like the following could be used instead:

```python
def _memoize(*args, **kwargs):
    args_ = ','.join(['{0}({1})'.format(x, type(x)) for x in args] + ['{0}={1}({2})'.format(k, kwargs[k], type(kwargs[k])) for k in sorted(kwargs)])
    if args_ not in cache:
        cache[args_] = func(*args, **kwargs)
    return cache[args_]
``` 
the **type** function could be any suggested type function (from module six or whatever), and I've removed the **isinstance** string conditionals since I'm not sure how they could help with the suggested string syntax. Of course, the above code is just my 2c, but I think you get the message.

2017-08-23 13:32 UTC, mamalos commented
Yep, confirmed, @cro had already corrected this arguments' change in commit a260e91 for version **2017.7**. This should be merged in **2017.7.1** as well.