Start working on network automation docs
saltstack/salt pull request #41028
Opened 2017-05-03 15:16 UTC by mirceaulinic

### What does this PR do?

Feedback much appreciated

Ping @whiteinge

2017-05-03 17:22 UTC, cachedout requested changes
Really great! Just one small typo to fix.

2017-05-03 17:22 UTC, cachedout commented on doc/topics/network_automation/index.rst
> +Install NAPALAM - follow the notes_ and check the platform-specific dependencies_.
`NAPALM`

2017-05-03 17:37 UTC, mirceaulinic commented on doc/topics/network_automation/index.rst
> +Install NAPALAM - follow the notes_ and check the platform-specific dependencies_.
Nice catch!

2017-05-04 00:41 UTC, whiteinge commented
This builds good locally. IMO this should be added to the top-level TOC:

```diff
diff --git a/doc/contents.rst b/doc/contents.rst
index cb1e3e52a2..3dea7e04c4 100644
--- a/doc/contents.rst
+++ b/doc/contents.rst
@@ -17,6 +17,7 @@ Salt Table of Contents
     topics/orchestrate/index
     topics/ssh/index
     topics/cloud/index
+    topics/network_automation/index
     topics/proxyminion/index
     topics/virt/index
     ref/cli/index
```

2017-05-04 15:05 UTC, rallytime approved these changes

2017-05-04 15:05 UTC, rallytime commented
Thank you @mirceaulinic!

2017-05-04 15:05 UTC, merged

2017-05-10 17:30 UTC, mirceaulinic commented
@gtmanfred @vnitinv @tonybaloney would you be able to continue adding bits under this topic?

2017-05-11 09:38 UTC, vnitinv commented
@mirceaulinic Will add for junos. Thanks

2017-05-22 07:00 UTC, vnitinv commented
@rajvidhimar Can you please take care of this.

2017-05-22 07:01 UTC, tonybaloney commented
@vnitinv it's merged