Update http_json.py
saltstack/salt pull request #41121
Opened 2017-05-08 09:35 UTC by sumeetisp

Updated to join url and minion_id

### What does this PR do?
This change will join the url and minion_id to retrieve pillars of the specified minion_id. Earlier the url had to be hard coded.
### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-08 15:34 UTC, gtmanfred requested changes
We need to make this a configuration setting to do this, because we do not want to break people who are currently using this module as is.

2017-05-11 15:16 UTC, AsocPro commented
Something that would be really good with this setting is if it were much more generalized such as a string that the minion can interpolate so that it is more than just adding the minion on the end of the URL. Basically if possible I think it should be avoided adding a bunch of one off settings that do very specific things since that could get out of hand quickly.

2017-05-22 17:03 UTC, cachedout commented
@sumeetisp Did you see the above feedback on this PR?

2017-05-24 18:03 UTC, cachedout commented
@sumeetisp Since we have not heard back from you on the requested follow-up items, I'm afraid I have to close this. If you're able to come back to it, please let me know and we will gladly re-open it.

2017-05-24 18:03 UTC, closed without merging