Implement etcd based minion data cache
saltstack/salt pull request #41141
Opened 2017-05-09 12:26 UTC by FedericoCeratto

### What does this PR do?
Implement a minion data cache plugin for etcd.

### Tests written?
No. Tested manually with a local DB instance. I'm open to suggestions to create integration tests.

2017-05-12 17:49 UTC, cachedout requested changes

2017-05-12 17:49 UTC, cachedout commented on salt/cache/etcd_cache.py
> +    client = etcd.Client(**etcd_kwargs)
Same issue here as in the other PR. We should not be doing this sort of initialization in `__virtual__` IMHO.

2017-05-22 12:13 UTC, FedericoCeratto commented on salt/cache/etcd_cache.py
> +    client = etcd.Client(**etcd_kwargs)
Updated.

2017-05-22 17:02 UTC, cachedout commented
Go Go Jenkins!

2017-05-29 09:50 UTC, FedericoCeratto commented on salt/cache/etcd_cache.py
> +    client = etcd.Client(**etcd_kwargs)
Done

2017-05-30 14:38 UTC, FedericoCeratto commented on salt/cache/etcd_cache.py
> +    client = etcd.Client(**etcd_kwargs)
Done

2017-05-30 15:01 UTC, cachedout approved these changes

2017-05-30 15:01 UTC, merged