Fix: zypper handling of multiple version packages
saltstack/salt pull request #41208
Opened 2017-05-12 08:46 UTC by pkazmierczak

### What does this PR do?

For kernel packages, zypper reports multiple versions as "new" during
upgrade. Thus, a salt state requesting pkg.latest of any kernel package
would fail, even though zypper runs successfully. This commit provides
a simple fix.

### Previous Behavior
pkg.latest on SLE minions installed latest kernel version, but the state failed. 

### New Behavior
pkg.latest on SLE minions installs latest kernel version, and the state succeeds. 

### Tests written?

No

2017-05-12 09:24 UTC, isbm requested changes
This looks very good. However, we really would need a unit test here.

@cachedout please hold on with the merging. :wink:

2017-05-12 15:55 UTC, cachedout commented
@pkazmierczak Did you want to write a unit test for this or, @isbm is this something you're volunteering to do? :]

2017-05-12 16:00 UTC, pkazmierczak commented
@cachedout I'll write a test. @isbm is basically volunteering me:)

2017-05-12 16:01 UTC, cachedout commented
@pkazmierczak Sounds great. Thanks!

2017-05-16 18:52 UTC, pkazmierczak commented
@isbm Tests are in, would you please have another look?

2017-05-16 19:58 UTC, isbm requested changes

2017-05-16 19:58 UTC, isbm commented on tests/unit/modules/zypper_test.py
> +                with patch('salt.modules.zypper.list_pkgs', MagicMock(side_effect=[{"kernel-default": "3.12.49-11.1"}, {"kernel-default": "3.12.49-11.1,3.12.51-60.20.2"}])):
All that can be actually be either a multiple statement (Python 2.7+ supports it) or a `@patch` decorator.

2017-05-16 19:58 UTC, isbm commented on tests/unit/modules/zypper_test.py
> +                with patch('salt.modules.zypper.list_pkgs', MagicMock(side_effect=[{"kernel-default": "3.12.49-11.1"}, {"kernel-default": "3.12.49-11.1,3.12.51-60.20.2"}])):
And while we do not have that stupid 80 chars punch-card limit on width as we no longer on CRT IBM terminals, still we shouldn't abuse the freedom. :wink: So I'd keep it 120 for the sanity reasons.

2017-05-16 20:48 UTC, pkazmierczak commented on tests/unit/modules/zypper_test.py
> +                with patch('salt.modules.zypper.list_pkgs', MagicMock(side_effect=[{"kernel-default": "3.12.49-11.1"}, {"kernel-default": "3.12.49-11.1,3.12.51-60.20.2"}])):
Done & done.

2017-05-16 21:45 UTC, pkazmierczak commented
Ah, jenkins linter is complaining that the code isn't python 2.6 compatible. I suppose I'd rather revert to the cascade of `with` statements than decorators, following a convention that's pretty much consistent throughout other unit tests. What do you think, @isbm?

2017-05-18 15:44 UTC, merged