Increase timeout for Windows
saltstack/salt pull request #41204
Opened 2017-05-11 22:40 UTC by twangboy

### What does this PR do?
Fixes `integration.modules.test_publish` tests for Windows. The timeout was set too low.

### What issues does this PR fix or reference?
https://github.com/saltstack/zh/issues/1273

### Tests written?
NA

2017-05-12 16:05 UTC, cachedout requested changes
This is not how we should be doing this. We cannot just blindly change the value of a timeout that a user specifies. If this is to be changed, it should be a value that is passed _in_ from a test.

2017-05-12 17:33 UTC, twangboy commented
@cachedout Moved the timeout to the test itself.

2017-05-12 18:09 UTC, cachedout approved these changes

2017-05-15 19:58 UTC, twangboy commented
@cachedout Can we get this in?

2017-05-15 20:04 UTC, merged