rest_cherrypy: remove sleep call
saltstack/salt pull request #41235
Opened 2017-05-15 05:56 UTC by moio

### What does this PR do?

It removes a delay when processing events from the `rest_cherrypy` netapi that limited the throughput to 10 events per second maximum.

### What issues does this PR fix or reference?

None known.

### Previous Behavior

If more than 10 events per second were published on the Event bus, `netapi` clients would only get up to 10 per second, and the rest would be queued.

This can be easily reproduced with the [evil-minions Salt load generator](https://github.com/moio/evil-minions).

### New Behavior

Events are processed as fast as possible.

### Tests written?

No.

This PR is more of a question rather than a code contribution (to @pass-by-value, @whiteinge or anyone with in-depth knowledge of this matter). I am not experienced enough to see why this might be needed or what would an alternative solution look like at the moment.

I did not observe negative side effects with this patch.

Thanks in advance!

2017-05-15 06:03 UTC, moio commented
PS. to dear colleagues @meaksh, @dincamihai, @pkazmierczak and @isbm - if you see any evident reason I can't see why this is a super bad idea your input is more than welcome!

2017-05-15 07:37 UTC, isbm requested changes

2017-05-15 07:37 UTC, isbm commented on salt/netapi/rest_cherrypy/app.py
> -                time.sleep(0.1)
This is likely to suppress high CPU load on idle. I'd leave `sleep` here, but set to `0.01` instead.

2017-05-15 07:48 UTC, moio commented on salt/netapi/rest_cherrypy/app.py
> -                time.sleep(0.1)
CPU is flat at 0 when idle, so this does not seem to be the problem.

2017-05-15 07:56 UTC, isbm commented on salt/netapi/rest_cherrypy/app.py
> -                time.sleep(0.1)
@pass-by-value we are wondering why you would add that `sleep` here. :wink: Any insights?

2017-05-15 08:08 UTC, isbm commented on salt/netapi/rest_cherrypy/app.py
> -                time.sleep(0.1)
To my first comment, I think it was needed pre-Tornado, which now does now [the same thing here](https://github.com/tornadoweb/tornado/blob/master/tornado/gen.py#L936). OK, _I think_ that it is safe to remove after all.

2017-05-15 08:08 UTC, isbm approved these changes

2017-05-15 13:03 UTC, isbm commented
@moio please remove `import time` to fix lint.

2017-05-15 15:31 UTC, moio commented
Argh! Right @isbm, thanks for pointing that out. Fixed.

2017-05-15 18:16 UTC, rallytime commented
Go Go Jenkins!

2017-05-17 18:57 UTC, cachedout commented
I'd like to have @whiteinge come by here to have a look at this before we get this in.

2017-05-17 21:56 UTC, whiteinge approved these changes
I don't know the history here but if I were to guess, I'd concur with @isbm 's assessment that this was for a non-Tornado concurrency lib.

2017-05-17 21:59 UTC, whiteinge commented
I seem to recall there were a couple teams members looking into Gevent back when this was added which monkey-patches `time.sleep` and requires that is added to avoid blocking.

👍  from me.  (Thanks for the ping @cachedout.)

2017-05-18 16:02 UTC, merged

2017-05-19 05:07 UTC, moio commented
@cachedout thanks for merging! Should I open PRs to backport this to other versions, or will someone from the team simply cherry-pick the commit?

Is there any need for unit tests?

2017-05-19 19:03 UTC, cachedout commented
@moio I have marked this for backporting. As always, we would gladly accept unit tests for this. :]

2017-05-20 21:42 UTC, moio commented
@cachedout: I am willing to invest some time in a unit testing that "covers" this patch, I can't help wondering if it is worth it.

The only implementation idea that came to me is to mock several objects, call `event_stream` and ensure `time.sleep` is never called.

If this is the "correct way", does such a test bring any value? IOW: do you believe it is worth it to have such mock-heavy tests, that know so much about implementation details, and rely so much about them?

Or, do you see any other way a test could be implemented to capture better the nature of this patch?

From my perspective an integration test would make more sense here, and specifically a performance regression test. Side note: we have a plan to introduce general ones for critical Salt areas based on [evil-minions](https://github.com/moio/evil-minions), but that will take some time before it becomes reality.

Thanks!

2017-05-22 17:59 UTC, cachedout commented
@moio Yes, I think that's right. In truth, a regression here would likely be detected by the existing integration tests so I'm really not even sure what additional integration tests might be added that would make sense on this one.