combine mongodb_user/mongodb_database and add role grant/set methods
saltstack/salt pull request #41278
Opened 2017-05-16 15:47 UTC by jettero

### What does this PR do?

Combine mongodb_user and mongodb_database into one state module. (Why were these ever separate??) and add user_grant_roles and user_set_roles functions.

The modern mongodb security docs recommend role based authentication and the mongodb_user state module didn't have any role methods (though the mongodb execution module does have them).

I made no attempt to deprecate or remove the mongodb_user and mongodb_database state modules in this PR... Even if removed (and assuming this combination module is approved); they should probably stick around for a while for backwards compatibility.

### Tests written?

No. Perhaps I should write up something though.

I'm not even aware of where Salt tests live (or how to run them). Checking.

2017-05-16 22:32 UTC, cachedout commented
@jettero Thanks for this!

There are a number of lint errors. Could you please update this PR with fixes? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/11234/violations/file/salt/states/mongodb.py/

2017-05-18 14:50 UTC, jettero commented
That linter takes quite a while to go through.

2017-05-18 17:03 UTC, jettero commented
OK. 

I dislike the whitespace rules (not that it matters), but made the lint changes. There's still some lint problems in core, but I don't think I'm meant to fix that.

2017-05-19 18:41 UTC, cachedout commented on salt/states/mongodb.py
> +    for i in ('mongodb.user_exists', 'mongodb.db_exists',):
Either the mongodb module should be loaded and all its funcs will be available or it won't be. There shouldn't be a need to do two full loops here. One should suffice.

2017-05-22 16:00 UTC, jettero commented on salt/states/mongodb.py
> +    for i in ('mongodb.user_exists', 'mongodb.db_exists',):
agreed

2017-05-31 20:08 UTC, cachedout requested changes
These have been separate since their creation in mid-2012. I believe that we should do this in a couple of stages to give people some time to migrate.

My suggestion is that we begin to add deprecation notices in Oxygen for the mongodb states and then target at least one release down the road. We can add those notices and raise them in logs and then add them to the docs as well. Then, when the targeted release comes we can do this split.

Let me know your thoughts.

2017-06-01 14:02 UTC, jettero commented
That makes perfect sense to me. I feel like it should definitely be combined, but I can see leaving it alone for tradition's sake too. I can split it back out, but I've no idea how to proceed with the deprecation and (in particular) the notices about it. Presumably that's work for the actual devs rather than hobbyists.

2017-06-01 16:37 UTC, jettero commented
I wonder if it makes sense to make the states/mongodb_database.py and states/mongodb_user.py simply import the functions from the combined states/mongodb.py ; rather like the mongo_future_return.py (analogously, not identically).

2017-06-01 16:54 UTC, jettero commented
I rebased to develop and it moved all the commits below our conversation.

The new one is "like this?"

I'm wondering if that could be used to keep the separate versions and the new combined version and make sure they're always in sync (so to speak).

2017-06-07 17:33 UTC, cachedout commented
Hi @jettero 

Deprecating isn't hard. We just need a docs notice:

https://github.com/saltstack/salt/blob/develop/salt/modules/trafficserver.py#L209

And then to raise a warning:

https://github.com/saltstack/salt/blob/develop/salt/modules/trafficserver.py#L216

2017-06-12 13:10 UTC, jettero commented
I think the jenkins problems are slightly spurious...

2017-06-14 17:31 UTC, merged

2018-03-16 19:45 UTC, terminalmage commented
This shouldn't have been done. There's a very good reason for them to have been separate in the first place: because it makes requisites look cleaner. Also, this is a standard way of doing things that we've established in Salt, when multiple different kinds of things are being managed by Salt.

I also don't like that we now have to divergent sets of states, which I now have to resolve into a single module.

2018-03-16 20:16 UTC, terminalmage commented
Also, roles were already supported in `mongodb_user.present` at the time this PR was written. I'm going with the existing code and scrapping the role management states in mongodb.py since the role management makes more sense in mongodb_user.py as it is integrated into the `mongodb_user.present` state and doesn't require additional states/requisites to work properly.

2018-03-17 21:09 UTC, terminalmage commented
Reverted in https://github.com/saltstack/salt/pull/46597