napalm_syslog engine: Add check for IPv6 address for zmq socket
saltstack/salt pull request #41300
Opened 2017-05-17 13:09 UTC by loverend

### What does this PR do?
Adds a check for an IPv6 address when creating a ZMQ socket. If the address is IPv6 then we enable IPv6 on the socket.

### Previous Behavior
ZMQ would open a IPv4 socket

### New Behavior
ZMQ will enable IPv6 on the socket 

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-17 15:07 UTC, mirceaulinic approved these changes

2017-05-17 16:34 UTC, cachedout requested changes
I would prefer that we use `salt.utils.network.is_ipv6()` for this.

2017-05-18 09:48 UTC, loverend commented
Changed to use `salt.utils.network.is_ipv6()` as recommended by @cachedout

2017-05-18 16:10 UTC, cachedout approved these changes

2017-05-18 16:10 UTC, merged

2017-05-18 16:10 UTC, cachedout commented
Many thanks, @loverend