Add TLS connection options for pgjsonb returner
saltstack/salt pull request #41339
Opened 2017-05-19 09:11 UTC by aneeshusa

Previously, any TLS options in the configuration were silently ignored,
and would not have worked regardless
because they were copied from the MySQL returner.

### What does this PR do?

Allow using TLS connections in the pgjsonb returner.

### What issues does this PR fix or reference?

#23508 (original implementation by @cro)

### Previous Behavior

TLS options for the pgjsonb returner were silently ignored.

### New Behavior

The pgjsonb returner can make TLS connections to Postgres.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-21 03:36 UTC, terminalmage requested changes

2017-05-21 03:36 UTC, terminalmage commented on salt/returners/pgjsonb.py
> +            k: v for k, v in _options.items()
We should be using ``six.iteritems()`` here to ensure that Python 2 uses a generator. To do this, just add a ``from salt.ext import six`` to the imports, and change this line to the following:

```python
k: v for k, v in six.iteritems(_options)
```

2017-05-21 04:09 UTC, aneeshusa commented on salt/returners/pgjsonb.py
> +            k: v for k, v in _options.items()
Thanks for the pointer, fixed.

2017-05-22 16:23 UTC, cachedout commented
@terminalmage Re-review, please.

2017-05-24 14:11 UTC, terminalmage approved these changes
Looks good.

2017-05-24 16:37 UTC, merged