minion_id_lowercase
saltstack/salt pull request #41354
Opened 2017-05-20 13:12 UTC by tsaridas

### What does this PR do?
Adds option to minion config to always lowercase minion id when generated by salt.

### What issues does this PR fix or reference?
Some windows hosts have minion id in capital letters.

### Previous Behavior
minion id would be in capital.

### New Behavior
User will have the option to always have minion id in lowercase.

### Tests written?
No

2017-05-22 16:01 UTC, cachedout commented on salt/config/__init__.py
> +    if opts.get('minion_id_lowercase', True):
I'm not sure we should be defaulting this to `True`. Even though it's in the config, I would feel more comfortable here if we either raised a `KeyError` if it wasn't set or just let it default back to `None`.

2017-05-22 18:34 UTC, tsaridas commented
I though opts.get was comparing values. Removed True. 
That should do it right ?
thanks for your comment

2017-05-24 14:10 UTC, terminalmage requested changes

2017-05-24 14:10 UTC, terminalmage commented on doc/ref/configuration/minion.rst
> +-----------------
The dashed line underneath should be the same length as the line above, to prevent Sphinx build warnings.

2017-05-24 16:18 UTC, tsaridas commented on doc/ref/configuration/minion.rst
> +-----------------
Thanks for the comment @terminalmage . Fixed

2017-05-24 17:08 UTC, cachedout commented
@terminalmage Re-review requested.

2017-05-24 17:08 UTC, cachedout commented
Go Go Jenkins!

2017-05-25 14:46 UTC, terminalmage approved these changes

2017-05-25 18:45 UTC, merged