WIP Updating Neutron module to suport KeystoneAuth
saltstack/salt pull request #41397
Opened 2017-05-23 21:42 UTC by Enquier

### What does this PR do?
Modifies the existing Neutron Client to support Keystone Auth

### What issues does this PR fix or reference?
This is the Neutron version of issue #37824 which relates to the Nova Salt-Cloud driver
This issue liberates code from the nova implementation merged here:
@gtmanfred  #38647
and my own addition of SSL verification merged here:
@Enquier #40752

### Previous Behavior
Neutron client unable to use v2 Openstack identity api.

### New Behavior
Neutron client now able to use KeystoneAuth similar to Recent additions in Nova Cloud Module

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-23 21:43 UTC, Enquier commented
The current branch works. I just haven't had time to extensively test, clean up any remaining references to NovaClient and add new documentation

2017-05-23 22:06 UTC, gtmanfred commented
@Enquier are you trying to get this fixed in 2016.11?  If yes, can you change the branch to merge against to 2016.11 so that it can be merged forward?

Otherwise, this looks good.

Thanks,
Daniel

2017-05-23 22:19 UTC, Enquier commented
Good point I will change the base branch.

2017-05-24 15:57 UTC, cachedout commented
@gtmanfred Could you please give this a thorough review? Thanks.

2017-05-24 16:08 UTC, gtmanfred requested changes

2017-05-24 16:08 UTC, gtmanfred commented on salt/modules/neutron.py
> +            'verify': verify,
verify might not be set if profile is not being used.

2017-05-24 16:08 UTC, gtmanfred commented on salt/modules/neutron.py
> +
need to check for use_keystone_auth here too

2017-05-24 16:08 UTC, gtmanfred commented on salt/utils/openstack/neutron.py
> +        self.kwargs['service_type'] = 'network'
can't this be another name?  I would say we should default to 'network'  But i believe it is possible for it to be networkv2 on openstack instances, i think rackspace has networkv2.

2017-05-24 17:20 UTC, Enquier commented on salt/utils/openstack/neutron.py
> +        self.kwargs['service_type'] = 'network'
Okay ill add it back in. Service_type was hard coded into the Nova implementation so I took lead from that

2017-05-24 17:21 UTC, Enquier commented on salt/modules/neutron.py
> +            'verify': verify,
See this morning's commits I added that in.

2017-05-24 17:21 UTC, Enquier commented
I went ahead and added the two or three lines that will enable the nova module to take advantage of the previous changes to the Nova cloud module

2017-05-24 17:32 UTC, Enquier commented on salt/modules/neutron.py
> +
done

2017-05-24 17:39 UTC, gtmanfred approved these changes

2017-05-24 17:40 UTC, Enquier commented
@gtmanfred I have completed the requested changes. I do have one concern. Specifying the "service_type" might prevent a single profile from being used for both Nova and Neutron Client. I am wondering if we should change it to neutron_service_type and nova_service_type?

2017-05-24 18:07 UTC, gtmanfred commented
Yeah, but we should do that in develop.

2017-05-24 18:18 UTC, Enquier commented
Okay sounds good. I added documentation so I consider this done.

2017-05-25 18:47 UTC, rallytime commented
Go Go Jenkins!

2017-05-25 21:16 UTC, merged