Fixing module function to use correct rabbitmq command
saltstack/salt pull request #41460
Opened 2017-05-26 14:07 UTC by teoyaomiqui

#41458

### What does this PR do?
Fixes rabbitmq module function to form correct command

### What issues does this PR fix or reference?
41458
Related to issue https://github.com/saltstack/salt/issues/41458

### Previous Behavior
rabbitmq_user.present fails with rabbitmq-servers versions below 3.5.6

### New Behavior
rabbitmq_user.present succeeds with rabbitmq-servers versions below 3.5.6

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-26 14:08 UTC, denyskulykov approved these changes

2017-05-26 14:09 UTC, izadorozhna approved these changes

2017-05-26 14:11 UTC, akissa commented
This change breaks backwards compartibility

2017-05-26 14:21 UTC, teoyaomiqui commented
I don't have much experience with this module, so could you please point out how exactly and in what conditions backwards compatibility would be broken?

Thanks in advance!

2017-05-26 18:54 UTC, epcim requested changes

2017-05-26 18:54 UTC, epcim commented on salt/modules/rabbitmq.py
> +    cmd = ('rabbit_auth_backend_internal:user_login_authentication'
do the same thing what puppet folks: https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/322/files#diff-c62722635df69c579feeb9bf9534b82dR48

"version" is available in the code, so it's not a problem to keep backward compatibility.

2017-05-26 19:52 UTC, teoyaomiqui commented
There another function in rabbitmq, as far as i've checked,  it is available in all versions. I've changed the commit, please take a look at it.

2017-05-27 05:33 UTC, epcim commented
best if you could tes the change on lab/staging.On 26 May 2017 21:52, Kostiantyn Kalynovskyi <notifications@github.com> wrote:There another function in rabbitmq, as far as i've checked,  it is available in all versions. I've changed the commit, please take a look at it.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

2017-05-27 06:10 UTC, teoyaomiqui commented
I did check it on two envs.

2017-06-07 17:39 UTC, cachedout commented
@epcim and @akissa How does this look to you now? Are there additional changes you would like to see?

2017-06-14 17:27 UTC, cachedout commented
@epcim and @akissa. Last call for feedback. :]

2017-06-15 06:50 UTC, akissa commented
If i can remember correctly the version of rabbitmq shipped in centos 6 does not have the function. I am so busy with other stuff i do not have time confirm that, @teoyaomiqui if you can please confirm that.

2017-06-20 20:06 UTC, cachedout commented
Thanks, @akissa 

@teoyaomiqui Did you see the above comment?

2017-06-20 20:19 UTC, teoyaomiqui commented
@cachedout i'll check it out next week, I've been quite busy during two past weeks, my apologies.

2017-06-21 15:42 UTC, cachedout commented
@teoyaomiqui Sounds good. Many thanks.

2017-07-31 23:21 UTC, cachedout commented
@teoyaomiqui Were you able to look at the above comment?

2017-09-11 22:11 UTC, cachedout commented
@teoyaomiqui Because we haven't heard back from you, I need to close this PR for the time being. When you are ready to come back to it, please let me know and we'll happily re-open this. Thanks.

2017-09-11 22:11 UTC, closed without merging