Add keystone V3 API support for keystone.endpoint_present|absent
saltstack/salt pull request #41509
Opened 2017-05-30 21:23 UTC by seanjnkns

### What does this PR do?
Add keystone V3 API support for keystone.endpoint_present|get, endpoint_absent|delete.
    
Passing interface to endpoint_present, or absent, will ensure only the given interface
for specified the specified region, is acted upon.
    
### What issues does this PR fix or reference?
Fixes #41435

### Previous Behavior
keystone.endpoint_present, or absent, would return an array of dictionaries containing 3 elements, unlike one with V2, when getting the endpoint list.  As a result, when creating the admin, internal, and public interfaces, each subsequent endpoint_present call for the same service and region would overwrite the previous interface, leaving you with just a single interface.

Also, endpoint absent would either delete just a single endpoint for a service using V3 API, or delete none, and still state that changes were made.

### New Behavior
endpoint_present and absent now pass the interface to endpoint_get to return information about just the chosen region, service name, and interface, and then acts upon that, much like would be the case with V2.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-31 17:50 UTC, gtmanfred requested changes
This looks great! we just need to make sure that the tests get updated.

Thanks @seanjnkns

2017-05-31 17:53 UTC, seanjnkns commented
I'm looking at the tests right now trying to determine why they're throwing assertion errors and debugging them.  I "may" need some assistance/pointers as all these endpoint_absent/present tests are written based on the V2 assumption, which from best guess, is why they fail when functioning with properly integrated V3 API calls utilizing interface.

2017-06-01 00:22 UTC, seanjnkns commented
I actually want to write 2 more integration unit tests before this is accepted.  I fixed the V2 versions, but I'd like to add 2 V3 ones first.  We already have other unit tests, non-integration, covering these, and the V3 ones are largely clones of the V2 ones, just with interface passed in and the comment(s) will differ.  I expect to have this done sometime tomorrow and will push that when ready.

2017-06-02 17:25 UTC, cachedout commented
@gtmanfred Re-review request.

2017-06-02 19:13 UTC, gtmanfred approved these changes

2017-06-02 19:13 UTC, gtmanfred commented
Looks good to me!

Thanks,
Daniel

2017-06-03 03:01 UTC, merged