Use psutil where possible in win_status.py
saltstack/salt pull request #41512
Opened 2017-05-30 21:56 UTC by twangboy

### What does this PR do?
Uses PSUTIL where possible to simplify and fix broken code
- `status.cpuload` failed if more than 1 cpu was present

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/41428

### Tests written?
No

2017-05-31 16:26 UTC, cachedout requested changes

2017-05-31 16:26 UTC, cachedout commented on salt/modules/win_status.py
> +import psutil
This will stacktrace. We only have `psutil` as a dep for Nitrogen.

2017-05-31 17:04 UTC, twangboy commented on salt/modules/win_status.py
> +import psutil
Gated the import

2017-05-31 17:59 UTC, cachedout approved these changes

2017-05-31 19:56 UTC, merged

2017-06-02 03:34 UTC, terminalmage commented
Wouldn't this add a runtime dep on psutil? If so, this is probably not a huge deal as we have a lot better control over the modules we distribute on Windows.

2017-06-02 13:25 UTC, twangboy commented
We're already packaging psutil with Windows.

On Jun 1, 2017 9:35 PM, "Erik Johnson" <notifications@github.com> wrote:

> Wouldn't this add a runtime dep on psutil? If so, this is probably not a
> huge deal as we have a lot better control over the modules we distribute on
> Windows.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/41512#issuecomment-305680549>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AI8v_9oeCvz40Tx8QvrOAk40z8pwBRg8ks5r_4LlgaJpZM4Nq5p1>
> .
>

2017-06-02 14:57 UTC, terminalmage commented
Yes, I kinda figured we were (or could do so easily).