default skip_verify to False
saltstack/salt pull request #41528
Opened 2017-05-31 16:27 UTC by wasabi222

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-05-31 16:29 UTC, mirceaulinic approved these changes

2017-05-31 19:33 UTC, cachedout requested changes
Please add a note about this change to the nitrogen release notes before we merge this. Thanks.

2017-05-31 22:46 UTC, mirceaulinic commented
@cachedout this is a new state module in Nitrogen, is this note required in that case?
However, @wasabi222 you may need to add a note in the release notes for the other PR: https://github.com/saltstack/salt/pull/41532. Thanks!

2017-06-01 14:57 UTC, cachedout commented
@mirceaulinic Ah, I didn't catch that. You are correct. This is fine as-is.

2017-06-01 14:57 UTC, cachedout approved these changes

2017-06-01 14:57 UTC, merged