Additional fixes to states/saltmod.py
saltstack/salt pull request #41611
Opened 2017-06-06 18:18 UTC by garethgreenaway

### What does this PR do?
Following the documentation, when passed the test=True argument the runner and wheel functions should return a result value of False.

### What issues does this PR fix or reference?
38894

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-06-06 19:56 UTC, whiteinge requested changes
Thanks for sending this follow-up. Sorry that I missed it the first time!

In test mode the `result` field should be `None` and `changes` should be an empty dict.

2017-06-06 20:02 UTC, garethgreenaway commented
@whiteinge Ack.  MIssed that.  Updated the PR.  Thanks!

2017-06-06 21:13 UTC, whiteinge approved these changes

2017-06-07 14:03 UTC, terminalmage approved these changes

2017-06-07 15:31 UTC, garethgreenaway commented
Go Go Jenkins!

2017-06-07 16:37 UTC, cachedout approved these changes

2017-06-07 22:58 UTC, rallytime approved these changes

2017-06-07 22:58 UTC, merged