Adding ability to specify an encryption key for KMS
saltstack/salt pull request #41622
Opened 2017-06-07 01:59 UTC by TheRhino04

### What does this PR do?
Adds the ability to specify an encryption key for KMS encryption an ebs drive in Salt Cloud for the EC2 Provider

### What issues does this PR fix or reference?
Can't find a related one

### New Behavior
Pass in the parameter kmskeyid to any cloud profile and the correct encryption key is used in amazon for the EBS volume encryption

### Tests written?
No, but can be upon request

2017-06-07 16:35 UTC, cachedout requested changes

2017-06-07 16:35 UTC, cachedout commented on salt/cloud/clouds/ec2.py
> +        if ''kmskeyid' in kwargs:
It looks like there is an extra quotation mark here.

2017-06-07 17:05 UTC, TheRhino04 commented on salt/cloud/clouds/ec2.py
> +        if ''kmskeyid' in kwargs:
Derp, pushed too early. And I see one test is failing due to a documentation mismatch, do you want that in this PR as well?

2017-06-08 17:58 UTC, cachedout commented on salt/cloud/clouds/ec2.py
> +        if ''kmskeyid' in kwargs:
That test failure is elsewhere in the code. This looks fine now.

2017-06-08 17:58 UTC, merged