Allow Nova cloud module to set a specific floating ip address
saltstack/salt pull request #41655
Opened 2017-06-08 16:04 UTC by Enquier

### What does this PR do?
Add ability of users to specify an floating ip address in the floatingip block in lieu of specifying a pool name

### What issues does this PR fix or reference?
This fixes two things:
1. Allows users to specify a floating ip address in their config files (desirable for machines whose ip might be registered in DNS).
2. Adds a max nova version, recent updates to nova have removed functionality that nova cloud requires. At this time I have tested up to version 6.0.1 for functionality in python-novaclient and added an error for versions greater than that. #41654

### Previous Behavior
1. You could not specify an ip address when assigning a floating ip automatically in the nova cloud module
2. Installing a version of nova newer than 6.0.1 would cause unspecific nova cloud errors

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-06-08 16:48 UTC, gtmanfred approved these changes
I approve this, we need to move away from the nova module.  And locking it in to versions that work for now is ok by me.

2017-06-08 17:01 UTC, cachedout requested changes

2017-06-08 17:01 UTC, cachedout commented on salt/cloud/clouds/nova.py
> +                    log.debug
This line should either be fixed or removed.

2017-06-09 04:54 UTC, Enquier commented on salt/cloud/clouds/nova.py
> +                    log.debug
Line removed in latest commit

2017-06-14 16:43 UTC, cachedout approved these changes

2017-06-14 16:44 UTC, merged

2017-06-14 16:44 UTC, cachedout commented
Merged. Thanks very much, @Enquier !