[RFC] Fix cp tests for mac
saltstack/salt pull request #41664
Opened 2017-06-08 22:29 UTC by gtmanfred

### What does this PR do?
Mac does not have a locale set.  It uses C.  This allows the tests to run on
systems without a locale and python3

Is there a better way to fix these?

### What issues does this PR fix or reference?
Fixes saltstack/salt-jenkins#404
Fixes saltstack/salt-jenkins#405
Fixes saltstack/salt-jenkins#406
Fixes saltstack/salt-jenkins#407

2017-06-08 23:19 UTC, rallytime approved these changes

2017-06-09 07:38 UTC, vutny reviewed
But the tests are failing on both Ubuntu and CentOS...

2017-06-09 14:52 UTC, rallytime commented
Oh @gtmanfred - python2 needs `__salt_system_encoding__` passed in for the `decode` calls.

2017-06-09 15:07 UTC, gtmanfred commented
grrr, well that is a problem, because this fails because macs encoding is us-ascii, which fails here.

Should we just skip these tests and say that this functionality is not supported if a locale is not setup?

2017-06-09 16:19 UTC, s0undt3ch requested changes
We should never use bare `.decode()` calls, we should always provide the system encoding, specially if we're reading from the filesystem.

2017-06-09 16:19 UTC, s0undt3ch commented on salt/fileclient.py
> +                        data = data.decode()
You should specify the encoding, `__salt_system_encoding__`, or it will :boom: on non ASCII.

2017-06-09 16:19 UTC, s0undt3ch commented on salt/modules/cp.py
> +                data = data.decode()
Specify the system encoding

2017-06-09 16:19 UTC, s0undt3ch commented on tests/integration/modules/test_cp.py
> +                data = data.decode()
Specify the encoding.

2017-06-09 16:19 UTC, s0undt3ch commented on tests/integration/modules/test_cp.py
> +                data = data.decode()
You get the drill from the above comments ;)

2017-06-09 16:19 UTC, s0undt3ch commented on tests/integration/modules/test_cp.py
> +    @skipIf(__salt_system_encoding__ == 'US-ASCII', 'Requires a unicode locale, i.e. en_US.UTF-8')
We can skip, but we shouldn't. We should be able to handle gzipped files whether we're on a system with a unicode locale set or not.

2017-06-09 16:22 UTC, gtmanfred commented on salt/fileclient.py
> +                        data = data.decode()
The problem is it is currently exploding when I set this to __salt_system_encoding__, because that is 'us-ascii' in this case.

2017-06-09 16:24 UTC, gtmanfred commented on tests/integration/modules/test_cp.py
> +    @skipIf(__salt_system_encoding__ == 'US-ASCII', 'Requires a unicode locale, i.e. en_US.UTF-8')
What would be the best way to do this?

I pass this to salt.utils.to_bytes and it explodes because it can't encode it as 'latin-1'

2017-06-09 19:55 UTC, gtmanfred commented
Ok, from talking with @s0undt3ch we have a problem.

When files are sent from the master to the minion with the fileserver, we transfer bytes in the msgpack, but then the file is written as text on the minion, and we lose the encoding from the master in the process.

This only seems to be a problem when the locale on the system is C/POSIX which is US-ASCII in python

The correct solution is to use `use_bin_type=True` when msgpack is dumping the data.  But that requires the encoding to be set here https://github.com/saltstack/salt/blob/nitrogen/salt/payload.py#L113-L129 which breaks backwards compatibility with py2 and older minions.

So, as i see it right now, we have two ways forward.  One is just a stop gap until we get to a correct fix

1) We could sit down and figure out a way to get this to work, and be backwards compatible with python2 and older minions.  After talking with s0undtech, I think we have an idea.  We can add an setting to the blob in msgpack that keeps the encoding, and if binary is set to True, we then reload the msgpack.  This will cause double the load here, but will maintain backwards compatibility, then once these old minions are phased out in a 2 years, we can remove this stuff.  I think this might work, we will have to do some testing.

2) We can add a requirement for salt and python3 that says you have to set a unicode locale on your system if you want to use python3.  And then work on making the above mentioned change for Oxygen.

Thanks,
Daniel

2017-06-09 20:14 UTC, gtmanfred commented
This will show how many tests will be fixed on mac with locale set to en_US.UTF-8 http://mac-jenkins.lehi.saltstack.net:8080/job/2017.5/job/macOS-py3-10.12/24/console

2017-06-13 20:32 UTC, closed without merging