Fixes to states/virt.py
saltstack/salt pull request #41722
Opened 2017-06-13 19:25 UTC by garethgreenaway

### What does this PR do?
Adding the ability to configure some options when generating libvirt keys, particularly the number of days that the certificates will be valid for.

### What issues does this PR fix or reference?
#41667 

### Previous Behavior
Previously options were unavailable when generating certificates for use with libvirt.

### New Behavior
This change allows options including the number of days that the certificate will be valid for to be specified.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-06-13 22:32 UTC, isbm requested changes
Could you please look at these changes?

2017-06-13 22:32 UTC, isbm commented on salt/pillar/libvirt.py
> +                               __grains__['fqdn'], expiration_days)
This line can be on the previous though. But maybe multi-line template would work better here?

2017-06-13 22:32 UTC, isbm commented on salt/states/virt.py
> +    # libvirt.cacert.pem
Needed?

2017-06-13 22:32 UTC, isbm commented on salt/states/virt.py
> +    for (key, value) in kwargs.iteritems():
Parenthesis is unnecessary here.

2017-06-13 22:34 UTC, isbm commented
> ## Tests written?
> No

Why?

2017-06-13 22:53 UTC, garethgreenaway commented on salt/pillar/libvirt.py
> +                               __grains__['fqdn'], expiration_days)
Fair.  Seemed more readable at the time to have it on it's own line but moving it up one is fine as well.

2017-06-13 22:54 UTC, garethgreenaway commented on salt/states/virt.py
> +    # libvirt.cacert.pem
Not needed, but much like the line too long warnings are caught via the lint plugin I'm using so they show up as errors/warnings.  We're not failing on them but it makes for more readable code so I tend to fix them when I find them.

2017-06-13 22:54 UTC, garethgreenaway commented on salt/states/virt.py
> +    for (key, value) in kwargs.iteritems():
Good catch, thanks.  This was left over from something else.

2017-06-14 13:39 UTC, isbm requested changes
Maybe still consider to remove these comments about keys. They are anyways in the code.

Very much appreciated the unit test! Your karma is up. :wink:

2017-06-14 13:39 UTC, isbm commented on salt/states/virt.py
> +    # libvirt.cacert.pem
I mean, maybe just yank this comment at all? Why garbage in the code...

2017-06-14 15:59 UTC, cachedout commented on salt/states/virt.py
> +    # libvirt.cacert.pem
I agree with @isbm here. Seems like these should just be removed.

2017-06-14 19:01 UTC, cachedout commented
@isbm How is this looking to you now?

2017-06-14 21:51 UTC, garethgreenaway commented
Go Go Jenkins!

2017-06-14 22:36 UTC, isbm commented
@cachedout Yep, now I can stop bothering your new employee. :laughing:
@garethgreenaway thanks!

2017-06-14 22:37 UTC, isbm approved these changes

2017-06-14 23:21 UTC, garethgreenaway commented
@isbm No worries!  Thanks for your feedback.

2017-06-15 15:40 UTC, cachedout commented
@isbm We're always glad for your help and feedback. Thanks. :]

2017-06-15 16:58 UTC, garethgreenaway commented
Go Go Jenkins!

2017-06-16 16:30 UTC, garethgreenaway commented
Go Go Jenkins!

2017-06-16 21:24 UTC, rallytime approved these changes
Very nice.

2017-06-16 21:24 UTC, merged