Win install docs
saltstack/salt pull request #41728
Opened 2017-06-13 21:11 UTC by twangboy

### What does this PR do?
Removes references to salt-master in the installation and build docs
Adds documentation for building Python 3 installs

### What issues does this PR fix or reference?
https://github.com/saltstack/zh/issues/1187

### Tests written?
NA

2017-06-14 15:44 UTC, rallytime commented
I have switched the base branch on this pull request from `nitrogen` to `2017.7` in preparation for moving from a code-named release to a version number.

2017-06-14 21:48 UTC, rallytime requested changes
I had a couple of small changes that need to be fixed. Then we can get this merged in.

2017-06-14 21:48 UTC, rallytime commented on doc/topics/installation/windows.rst
> +    Salt-Minion-2017.5.1-Py2-AMD64-Setup.exe /S /master=yoursaltmaster /minion-name=yourminionname
This version with `2017.5` won't exist. Can you change that to `2017.7`?

2017-06-14 21:48 UTC, rallytime commented on doc/topics/installation/windows.rst
> +    Salt-Minion-2017.5.1-Py3-AMD64-Setup.exe /S /master=yoursaltmaster /minion-name=yourminionname /start-minion=0
Same comment here about the version.

2017-06-14 21:48 UTC, rallytime commented on doc/topics/installation/windows.rst
> +    git checkout 2017.5.2
Same comment here.

2017-06-14 21:48 UTC, rallytime commented on doc/topics/installation/windows.rst
> +    if ``pip`` is still not recognized make sure that the Python Scripts folder
`if` should be `If` :)

2017-06-14 21:48 UTC, rallytime commented on doc/topics/installation/windows.rst
> +with the build version (2017.5.2) and the Python version as parameters.
Oh, version here, too. There are a few more references with the `.5` version below. You get the idea. :)

2017-06-15 15:59 UTC, rallytime approved these changes

2017-06-15 18:09 UTC, damon-atkins commented
Might be worth adding how to run the windows tests, given this document covers building a developed environment.

2017-06-16 21:41 UTC, merged