open and write in byte mode using fileserver
saltstack/salt pull request #41730
Opened 2017-06-13 22:04 UTC by gtmanfred

### What does this PR do?
This switches to byte mode explicitely in the last few places I could find that
are using the fileserver payload to store files.

We should only ever be reading in the file, and then passing it to the minion,
the unicode locale on the master should not matter.  Then we want to make sure
to write the information in bytes to the filesystem.

2017-06-14 03:18 UTC, s0undt3ch requested changes

2017-06-14 03:18 UTC, s0undt3ch commented on salt/fileserver/hgfs.py
>                  fp_.write('# hgfs_remote map as of {0}\n'.format(timestamp))
Since you now opened in binary mode, you can only write bytes to the file. Since this is ASCII, it's safe to do `b'ascii string'`. On py3 of course.

2017-06-14 14:53 UTC, gtmanfred commented on salt/fileserver/hgfs.py
>                  fp_.write('# hgfs_remote map as of {0}\n'.format(timestamp))
Sorry, i missed reverting this one.

The only ones that needed to be changed was the env_cache which used the Serial output.

Thanks,
Daniel

2017-06-14 15:43 UTC, rallytime commented
I have switched the base branch on this pull request from `nitrogen` to `2017.7` in preparation for moving from a code-named release to a version number.

2017-06-14 15:44 UTC, rallytime commented
Go Go Jenkins!

2017-06-14 16:25 UTC, rallytime commented
Go Go Jenkins!

2017-06-14 19:12 UTC, terminalmage submitted a review, later dismissed

2017-06-14 19:13 UTC, terminalmage commented on salt/fileserver/hgfs.py
>                  fp_.write('# hgfs_remote map as of {0}\n'.format(timestamp))
`salt.utils.to_bytes()` is a shorthand for this.

2017-06-14 19:13 UTC, terminalmage commented on salt/fileserver/hgfs.py
>                  fp_.write('# hgfs_remote map as of {0}\n'.format(timestamp))
Oh you're going to revert it

2017-06-14 19:52 UTC, rallytime commented
Go Go Jenkins!

2017-06-14 21:51 UTC, rallytime commented
Go Go Jenkins!

2017-06-15 15:20 UTC, cachedout commented
@s0undt3ch and @terminalmage Re-review requested.

2017-06-15 20:29 UTC, terminalmage approved these changes

2017-06-15 21:06 UTC, cachedout commented
Just waiting on @s0undt3ch for one more review and then we should be set.

2017-06-17 06:34 UTC, s0undt3ch approved these changes

2017-06-17 15:44 UTC, rallytime commented
Go Go Jenkins!

2017-06-19 16:28 UTC, merged