Fix typo in cmd.wait documentation
saltstack/salt pull request #41793
Opened 2017-06-16 09:33 UTC by abednarik

### What does this PR do?

Fix typo in cmd.wait documentation

### What issues does this PR fix or reference?

#41732

2017-06-16 15:11 UTC, terminalmage requested changes

2017-06-16 15:11 UTC, terminalmage commented on salt/states/cmd.py
> +        Use ``cmd.run`` together with :mod:`onchanges </ref/states/requisites#onchanges>`
Why did you remove the RST hyperlink for ``cmd.run`` here? Please put it back.

2017-06-16 17:22 UTC, abednarik commented
Sorry. The same line is present in this file, my idea was to keep consistency. Will change both lines when I get 5.

2017-06-19 11:41 UTC, abednarik commented
Hi

 I just did the small update to keep RST hyperlink in both lines.

Thanks.

2017-06-19 16:30 UTC, cachedout commented
@terminalmage Re-review requested.

2017-06-19 19:57 UTC, terminalmage requested changes
Just a couple more changes, if you please. Neither of these are anything _you_ did wrong, but they are additional changes that I noticed should be made.

2017-06-19 19:57 UTC, terminalmage commented on salt/states/cmd.py
> +    Use :mod:`cmd.run <salt.states.cmd.run>` together with :mod:`onchanges </ref/states/requisites#onchanges>`
I know that you didn't write the original code here for the ``onchanges`` link, but this is an invalid link, and ``:mod:`` isn't used for user-generated anchors anyway, so I don't think this link _ever_ worked.

To get this link fixed, please change this to:
```
:ref:`onchanges <requisites-onchanges>`
```

That will link it to the user-defined anchor for the ``onchanges`` requisite in **doc/ref/states/requisites.rst**.

2017-06-19 19:57 UTC, terminalmage commented on salt/states/cmd.py
> +        Use :mod:`cmd.run <salt.states.cmd.run>` together with :mod:`onchanges </ref/states/requisites#onchanges>`
The same change as above should be made to the ``onchanges`` link here.

2017-06-19 19:57 UTC, terminalmage commented on salt/states/cmd.py
>      instead of ``cmd.wait``.
Can we also make this into a link to match the link for cmd.run? This can be changed to:

```
:mod:`cmd.wait <salt.states.cmd.wait>`
```

2017-06-19 19:57 UTC, terminalmage commented on salt/states/cmd.py
> +        instead of ``cmd.wait``.
Same request as above to change this into a link.

2017-06-19 20:33 UTC, abednarik commented
Hi @terminalmage 

 No problem, doing this small contributions is the way to me to say thanks for tools that I use everyday.
 I did those changes and a rebase.

Thanks.

2017-06-20 19:53 UTC, merged