Better support for numeric saltenvs
saltstack/salt pull request #41906
Opened 2017-06-22 16:19 UTC by terminalmage

When passing the saltenv on the CLI when running states, it is passed through PyYAML. This means that a numeric saltenv (e.g. ``2017.7``) would be loaded as a float, causing an error when the fileclient runs ``salt.utils.path_join()`` and passes the numeric saltenv as one of the path components.

This commit forces CLI saltenvs to be strings. It also makes a small performance improvement when a localconfig is passed by not performing a deepcopy on the ``__opts__`` (which ends up never getting used anyway).

2017-06-22 16:53 UTC, cachedout requested changes

2017-06-22 16:53 UTC, cachedout commented on salt/modules/state.py
>          opts = salt.config.minion_config(kwargs['localconfig'], defaults=opts)
in `defaults=opts` `opts` will be undef.

2017-06-26 14:00 UTC, terminalmage commented on salt/modules/state.py
>          opts = salt.config.minion_config(kwargs['localconfig'], defaults=opts)
Oh, good call. Thanks, I've corrected this.

2017-06-26 14:01 UTC, terminalmage commented on salt/modules/state.py
>          opts = salt.config.minion_config(kwargs['localconfig'], defaults=opts)
I squashed my correction into the prior commit, as I don't like leaving broken code in intermediate commits during a PR. It can mess with bisects.

2017-06-29 17:19 UTC, cachedout approved these changes

2017-06-29 17:19 UTC, merged