udpated docker_container doc for selinux
saltstack/salt pull request #41929
Opened 2017-06-24 05:08 UTC by BenjaminSchubert

The selinux flags for volumes where missing in the docker_container state.

### What does this PR do?

This PR fixes a missing documentation on the docker_container state.

### What issues does this PR fix or reference?

It also fix #38368 which is not relevant anymore with the new docker module.

### Tests written?
No

2017-06-26 13:52 UTC, terminalmage requested changes
Looking at the [Docker Engine API docs](https://docs.docker.com/engine/api/v1.26/#operation/ContainerCreate) (scroll down and expand **HostConfig**, then scroll down to find the **Binds** documentation) I see no mention of including the selinux context along with the mode. It's possible that the API docs are just incomplete, and I've not used selinux in Docker before so I'm not all that familiar with it.

Can you provide an example SLS using the selinux context, so that we can confirm that this actually works once we translate the SLS file input to what the API wants?

2017-06-26 13:52 UTC, terminalmage commented on salt/states/docker_container.py
> +        on a selinux-enabled host can be ``z`` if the volumne is shared between multiple containers
This is a run-on sentence.

2017-06-26 13:52 UTC, terminalmage commented on salt/states/docker_container.py
> +        .. code-block:: yaml
Adding this here makes the above documentation confusing, as it tells the user that the below two examples are equivalent, and then has three consecutive examples.

Please add a line above this example saying something like "Below is an example of setting the selinux context:"

2017-06-27 12:47 UTC, BenjaminSchubert commented
Ok, I updated the documentation to reflect your comments, would this be better for you ?

Concerning the documentation it is indeed incomplete. For the documentation on available options you can look at [the docker documentation](https://docs.docker.com/engine/tutorials/dockervolumes/). 

Here is a reproduction of the bug : 

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"
  
  config.vm.provider "libvirt" do |lb|
    lb.memory = 2048
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    # update and install dependencies
    dnf update -yq
    dnf install -yq docker python-docker-py
    systemctl start docker
   
    # install salt and configure it
    curl -s -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
    sh bootstrap-salt.sh -MP git develop

    sed -i 's/#master: salt/master: localhost/g' /etc/salt/minion

    systemctl restart salt-master
    systemctl restart salt-minion

    sleep 10
    salt-key -Ay

    # add salt state
    mkdir -p /srv/salt
    cat <<- EOF > /srv/salt/testing.sls
test_docker_selinux:    
  docker_container.running:
    - name: test
    - image: alpine:latest
    - cmd: tail -f /test.sls
    - binds:
      - /srv/salt/testing.sls:/test.sls:ro

test_docker_no_z_selinux:
  docker_container.running:
    - name: test-selinux
    - image: alpine:latest
    - cmd: tail -f /test.sls
    - binds:
      - /srv/salt/testing.sls:/test.sls:ro,Z
EOF

    # run the test
    salt "*" state.apply testing

	docker ps -a
  SHELL
end
```

This will setup a selinux-enabled fedora virtual machine, install and configure salt, then run two containers with a file, both with and without the correct selinux labeling.

The one with the Z will be alive afterwards while the one without will get killed because tail failed to access the file. You can get more information with dmesg or docker logs.

If you need anything else, I will be happy to give you more information.

2017-06-28 01:29 UTC, BenjaminSchubert commented
Aslo, would tests be required to make sure Salt always accepts these arguments ? I mean, the previous version of the container did sanitization checks wrong, preventing this use case.

2017-06-28 02:29 UTC, BenjaminSchubert commented
For reference I opened an issue on the docker bug tracker concerning the documentation at https://github.com/moby/moby/issues/33855

2017-06-28 16:18 UTC, cachedout commented
@terminalmage Re-review requested.

2017-06-29 03:41 UTC, terminalmage commented
>Concerning the documentation it is indeed incomplete. For the documentation on available options you can look at [the docker documentation](https://docs.docker.com/engine/tutorials/dockervolumes/). 

The problem with referring to the docker documentation is that the CLI usage differs in some cases from what the API expects. So I want to make absolutely sure that it works when you include the `,Z` at the end. Does adding this to the SLS work as expected when you run the state?

>Aslo, would tests be required to make sure Salt always accepts these arguments ? I mean, the previous version of the container did sanitization checks wrong, preventing this use case.

I'm sorry, I'm having trouble understanding this. The previous version of which container?

2017-06-29 03:46 UTC, terminalmage commented
Also, it looks like you updated your example to use `:Z` instead of `,Z`, what was the reason for this?

2017-06-29 03:50 UTC, BenjaminSchubert commented
> >Concerning the documentation it is indeed incomplete. For the documentation on available options you can look at the docker documentation.

>The problem with referring to the docker documentation is that the CLI usage differs in some cases from what the API expects. So I want to make absolutely sure that it works when you include the ,Z at the end. Does adding this to the SLS work as expected when you run the state?

@terminalmage Yes it does, please look at the Vagrantfile I made in previous comment showing how you can make sure it works. I also opened an issue in their documentation, still waiting for a comment though (see https://github.com/moby/moby/issues/33855 for reference).


> >Aslo, would tests be required to make sure Salt always accepts these arguments ? I mean, the previous version of the container did sanitization checks wrong, preventing this use case.

>I'm sorry, I'm having trouble understanding this. The previous version of which container?

Sorry I wasn't clear. What I meant is that the old docker-ng module made sanitization checks that where wrong (it checked for `rw` or `ro`, not allowing anything else). Thus I wanted to know if tests should be made to prevent such a regression, as :Z and :z is correct (see the previously mentionned Vagrantfile).

Is this more clear ?

2017-06-29 04:06 UTC, BenjaminSchubert commented
> Also, it looks like you updated your example to use :Z instead of ,Z, what was the reason for this?

Oups that's a typo sorry. Fixed !

2017-06-29 13:20 UTC, terminalmage commented
Which is a typo? [here](https://github.com/saltstack/salt/pull/41929/files#diff-3de3ca67cca4d4c99133a50b8dd4453dR286) and [here](https://github.com/saltstack/salt/pull/41929/files#diff-3de3ca67cca4d4c99133a50b8dd4453dR317) I see a comma, while [here](https://github.com/saltstack/salt/pull/41929/files#diff-3de3ca67cca4d4c99133a50b8dd4453dR343) I see a colon.

2017-06-29 13:31 UTC, terminalmage commented
It looks like the links I used were from an older diff. Still, [this line](https://github.com/saltstack/salt/pull/41929/files#diff-3de3ca67cca4d4c99133a50b8dd4453dR342) uses a colon. Is the comma correct, or is the colon?

2017-06-29 13:32 UTC, terminalmage commented
The documentation issue you opened upstream suggests that the colon is correct.

2017-06-29 13:36 UTC, BenjaminSchubert commented
It must be a comma if we specify `ro` or `rw` before, otherwise it is `:`. 

So that would be : 
`/tmp:/tmp:ro,Z`
`/tmp:/tmp:z`
`/tmp:/tmp:rw,y`
etc

Is this more clear ?

2017-06-29 15:09 UTC, terminalmage commented
It does now, though this wasn't made clear in the docs you added. There are some additional concerns for CLI usage of the `create` function in the execution module, which require their own documentation and which aren't covered here. Also, these documentation fixes should go into the `2017.7` branch where they can be merged forward into develop. I've taken your work in this PR and cherry-picked it on top of the `2017.7` branch, added some clarification (in addition to some unrelated docs tweaks I noticed needed to be made), and opened https://github.com/saltstack/salt/pull/42016. I'm going to close this PR in favor of the new one, since it contains all the commits from this PR already. Please let me know if anything looks out of place in https://github.com/saltstack/salt/pull/42016 and I'll make sure to get it fixed. Thanks again for your time and for helping to make Salt's documentation more accurate!

With regard to 2016.11, technically it's the same module, it's just undergone some restructuring/renaming for the 2017.7.0 release (see [here](https://github.com/saltstack/salt/blame/c2b5e50d5043c6b865596ae496e7e38801ba9f07/doc/topics/releases/2017.7.0.rst#L463)). Updating the code we use to verify the binds configuration in the 2016.11 release branch would be a lot of work, given that this code was written before some improvements to docker-py which make comparison much easier (hence the overhaul in the 2017.7 branch). Given that we're only likely to release one or two more 2016.11 bugfix releases, and this is fixed in 2017.7 and later, I'm hesitant to go back and fix it in the 2016.11 branch. The newer code both A) works, and B) has full unit test coverage for the argument handing.

2017-06-29 15:09 UTC, closed without merging

2017-06-29 23:19 UTC, BenjaminSchubert commented
@terminalmage This is indeed much better ! Thank you !

No problem concerning 2016.11, it seems indeed better not to backport it.

2017-07-03 15:55 UTC, terminalmage commented
@BenjaminSchubert Thanks for helping bring this to my attention, I really appreciate it! I am by no means familiar with all of Docker's many configurable parameters, so it's very helpful when the community helps us catch things like this. Bonus points for also helping to improve the Docker Engine API docs, as well. :+1: