Fix unit tests for Windows
saltstack/salt pull request #41943
Opened 2017-06-26 18:37 UTC by twangboy

### What does this PR do?
Fixes failing unit tests:
```
unit.returners.test_local_cache.LocalCacheCleanOldJobsTestCase.test_clean_old_jobs_empty_jid_dir_remains
unit.returners.test_local_cache.LocalCacheCleanOldJobsTestCase.test_clean_old_jobs_empty_jid_dir_removed
```

Fixes Windows paths and a race condition

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

2017-06-27 18:01 UTC, cachedout requested changes

2017-06-27 18:01 UTC, cachedout commented on tests/unit/returners/test_local_cache.py
> +        # dir before trying to clean the job cache to avoid a race condition
If any call in that function isn't properly cleaning up a filehandle, that's a serious bug. We need to investigate why and solve that issue.

2017-06-27 21:32 UTC, twangboy commented
This PR can't be merged until we can show that `local_cache.clean_old_jobs` doesn't support clean times < 1s accuracy on certain platforms (Windows) and is documented.

2017-07-05 18:24 UTC, twangboy commented
@cachedout What do you think of this fix?

2017-07-05 18:34 UTC, cachedout commented
I think this makes sense. We can probably just move the `time.time()` call into the line where the subtraction is actually done though. No need to make an assignment on a line before, that I can see.

2017-07-05 18:55 UTC, twangboy commented
@cachedout Done

2017-08-30 16:10 UTC, rallytime approved these changes

2017-09-11 21:33 UTC, cachedout approved these changes

2017-09-11 21:34 UTC, merged