Fixes to modules/git.py
saltstack/salt pull request #41945
Opened 2017-06-26 19:37 UTC by garethgreenaway

### What does this PR do?
Updating the git module to allow an identity file to be used when passing the user parameter

### What issues does this PR fix or reference?
#41936 

### Previous Behavior
Previously if the identity parameter was used along with the user parameter, the identity file would be copied to the Salt cache directory and would be inaccessible to the user.

### New Behavior
This swaps out cp.cache_file for cp.get_file, storing the file in a temporary location where it's accessible to the user that the salt commands are running as.  The temporary file is then cleaned up.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-06-26 20:15 UTC, terminalmage requested changes
Rather than caching the file first and then chmod'ing it, we should be temporarily changing the umask. This would be done using `umask = os.umask(0o077)` and then making absolutely sure that we undo that by putting _everything_ after we change the umask into a try/finally. The `finally` clause should then run `os.umask(umask)`, and we should at that time also remove the identity file.

2017-06-26 20:19 UTC, garethgreenaway commented
@terminalmage You're taking about the set_mode at line 186?

2017-06-26 20:20 UTC, terminalmage commented
Yes. And we should only be setting the umask on non-windows of course.

2017-06-27 04:08 UTC, terminalmage commented
@garethgreenaway I'll try to review your updates on Tuesday.

2017-06-29 13:49 UTC, terminalmage commented
@garethgreenaway I just added a context manager last night for another issue, that I think will come in handy here. It's in the head of 2016.11 now so you'd have to fetch and rebase, but this should make the code a bit cleaner since you won't have to worry about restoring the umask manually. You can then revert back the code that conditionally removes the GIT_SSH wrapper to the way it was before (see [here](https://github.com/saltstack/salt/pull/41945/files#diff-59a19c9338fb59c2d90efccd4a0d618fL247)).

You'd just need to make sure that everything from before the temp file is created until after it is deleted is within the `with salt.utils.files.set_umask(0o177):` block.

```
Python 2.7.13 (default, May 10 2017, 20:04:36)
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.utils.files
>>> import salt.utils
>>> with salt.utils.files.set_umask(0o177):
...     print(salt.utils.mkstemp())
...
/tmp/tmpYsNw8N
>>>
[root@3f8b9b4ae508 ~]# ls -l /tmp/tmpYsNw8N
-rw------- 1 root root 0 Jun 29 13:37 /tmp/tmpYsNw8N
```

2017-06-29 18:45 UTC, terminalmage approved these changes

2017-07-13 23:01 UTC, rallytime commented
Go Go Jenkins!

2017-07-14 17:46 UTC, merged