Update win_service.py
saltstack/salt pull request #42053
Opened 2017-06-30 16:28 UTC by jlayze

### What does this PR do?
Added support for StartType and Start_Delayed as kwargs in win_service.enable.  This allows for setting Manual and Auto (Delayed) start types from states.service.running and states.service.dead.

Example state.sls:
```
"Patch Agent":
  service.running:
    - enable: True
    - StartType: Manual
```
Or
```
"Patch Agent":
  service.dead:
    - enable: True
    - StartType: Delayed
```
### What issues does this PR fix or reference?
Set StartType for Windows Service from states.service module #42052

### Tests written?
Yes, and I found if the service is running, then changing from Auto to Auto(Delayed) or vice versa doesn't work due to the before_toggle_enable_status check in states.service.running:
```
before_toggle_status = __salt__['service.status'](name, sig)
    if 'service.enabled' in __salt__:
        before_toggle_enable_status = __salt__['service.enabled'](name)
    else:
        before_toggle_enable_status = True

    # See if the service is already running
    if before_toggle_status:
        ret['comment'] = 'The service {0} is already running'.format(name)
        if enable is True and not before_toggle_enable_status:
            ret.update(_enable(name, None, **kwargs))
        elif enable is False and before_toggle_enable_status:
            ret.update(_disable(name, None, **kwargs))
        return ret
```
Also found the same to be true with states.service.dead if the service is already stopped.

2017-06-30 16:59 UTC, twangboy requested changes

2017-06-30 16:59 UTC, twangboy commented on salt/modules/win_service.py
> +        **kwargs supports StartType
This should probably add two named arguments here. `start_type` with a default of `auto` and `start_delayed` with a default of `False`. To conform with other parameter names in salt please avoid CamelCase.

There needs to be additional documentation here as well for both parameters... similar to that for `modify`.

2017-06-30 16:59 UTC, twangboy commented on salt/modules/win_service.py
> +        return info(name)['StartType'] == 'Auto'
If you add the two parameters above, you don't need the whole `if kwargs is not None:` block. Something like this should work.

```
modify(name, start_type=start_type, start_delayed=start_delayed)
status = info(name)
return statys['StartType'].lower() == start_type.lower() and status['StartTypeDelayed'] == start_delayed
```

2017-06-30 20:00 UTC, jlayze commented
@twangboy Thanks, this looks much cleaner now.

I still needed to keep an IF block for the return, as the 'Delayed' flag isn't cleared when changing from Auto(Delayed) to Manual or Disabled, so service.enable was reporting a failure to enable start at boot when changing between Manual and Disabled after previously being set to Auto(Delayed).

2017-07-03 04:04 UTC, twangboy approved these changes

2017-07-03 04:04 UTC, twangboy commented
@jlayze Looks like we got some failing tests...

2017-07-03 17:12 UTC, jlayze commented
@twangboy aren't the Ubuntu and CentOS failures expected for a Windows module?  win_service.py should never be used on anything but Windows, and it's working as expected in all the tests I've run.

2017-07-03 17:37 UTC, twangboy commented
@jlayze Yeah, even though it's a Windows only function, some unit tests still run on Linux. Return values are Mocked so they still run. It looks like the `return_value` for the `MagicMock` needs to have an item added to the dictionary for `StartTypeDelayed`.

So, it's in the file `tests/unit/modules/test_win_service.py` on line `216` or so (in the `test_enable` function).
It needs to be something like this:
```
        mock_info = MagicMock(return_value={'StartType': 'Auto',
                                            'StartTypeDelayed': False})
```

2017-07-03 17:52 UTC, jlayze commented
@twangboy created PR #42091 to update test_win_service.py

2017-07-03 21:51 UTC, twangboy commented
@jlayze You need to modify `test_win_service.py` in this PR so that the test runs against the new changes in `win_service.py`.

2017-07-05 18:11 UTC, jlayze commented
@twangboy So I've made the required change to `test_win_service.py` and now `test_enable` is passing, but there are 31 other failures that are new.  I'm not sure where the 2 new checks and these errors came from.  I tried updating this PR's branch with the current `development` branch, but that hasn't helped.

2017-07-05 20:53 UTC, twangboy commented
@jlayze These test failures are unlrelated to this PR. Great job and thanks for your submission.

2017-07-07 16:32 UTC, rallytime approved these changes

2017-07-07 16:32 UTC, merged