ssh config roster for salt-ssh
saltstack/salt pull request #42103
Opened 2017-07-03 23:17 UTC by davidjoliver86

Addresses #35727

### What does this PR do?
Adds a roster module that leverages an SSH config file, using its `Host xxx` directives as roster targets, and allowing salt-ssh to leverage the connection parameters.

Use case is primarily targeted toward running shell commands on hosts that match the pattern.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/35727

### New Behavior
Adds ``sshconfig`` roster.

### Tests written?
Yes

2017-07-04 00:56 UTC, gtmanfred commented
This looks awesome!

Would you mind taking a look at the 2 pylint errors?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/12528/violations/file/tests/unit/test_ssh_config_roster.py/

Thanks,
Daniel

2017-07-05 18:12 UTC, davidjoliver86 commented
@gtmanfred Should be good now.

2017-07-13 08:31 UTC, vutny commented
This is so cool feature, @davidjoliver86

2017-07-25 20:43 UTC, cachedout commented on salt/syspaths.py
> +HOME_DIR = __generated_syspaths.SPM_REACTOR_PATH
I'm unclear on why `SPM_REACTOR_PATH` was chosen here. Could you please clarify?

2017-08-11 16:03 UTC, rallytime commented
@davidjoliver86 Did you get a chance to look at the comments above?

2017-08-12 21:17 UTC, davidjoliver86 commented
@rallytime Gonna look over it now - been a little busy lately, my apologies.

2017-08-12 21:47 UTC, davidjoliver86 commented on salt/syspaths.py
> +HOME_DIR = __generated_syspaths.SPM_REACTOR_PATH
Just a typo. :hushed:

2017-09-11 19:54 UTC, cachedout requested changes
The only addition I'd like to request here is to add a description of this new feature to the release notes. They are here: https://github.com/saltstack/salt/blob/develop/doc/topics/releases/oxygen.rst

After that, I'm good with merging this. Thanks!

2017-09-12 16:38 UTC, cachedout approved these changes

2017-09-12 16:38 UTC, cachedout commented
I'll just go ahead and modify the release notes in a follow-up PR. Thanks, @davidjoliver86 !

2017-09-12 16:38 UTC, merged