Allow to wipe the "salt-thin" on the client when calling "salt-ssh" wrapped functions
saltstack/salt pull request #42231
Opened 2017-07-10 13:14 UTC by meaksh

### What does this PR do?
This PR fixes an issue on `salt-ssh` when using `-w` or `--wipe` argument to wipe the `salt-thin` on the ssh minion and calling any of the wrapped functions (wfuncs) defined for `salt-ssh`.

Currently, the cleanup of the deployed `salt-thin` is made by the SHIM code, but when calling `salt-ssh` wrapped functions (wfuncs), like `state.apply`, `state.show_highstate`, `pillar.get`, `grains.get`, etc, the cleanup is not performed even if `-w` or `--wipe` are passed as parameter to the `salt-ssh` call.

This is happening because few reasons:
- Not all wrapped functions are actually running SHIM on its execution. i.a. `grains.get`
- In such wrapped functions which execute SHIM, they don't pass the `wipe` option to the `Single` object so the cleanup is also not performed even if SHIM code is executed.

This PR proposes to trigger a `test.ping` job to the ssh minion just after calling a `wfunc` in cases where `-w` is set for `salt-ssh`. This `test.ping` job will execute SHIM code on the minion including the cleanup, so the deployed `salt-thin` from SHIM execution on previous stages will be wiped from the ssh minion.

### Previous Behavior
```
clisles11sp4:~ # ls -l /var/tmp/
total 0

---

suma3pg-new:~ # salt-ssh clisles11sp4 -i --roster-file=/tmp/tmp_roster grains.get uuid -w -W
clisles11sp4:
    cb2956de-5a8c-e44d-85a8-fc8d1b170412

---

clisles11sp4:~ # ls -l /var/tmp/
total 8
drwx------ 4 root root 4096 jul 10 14:46 .208736
```

### New Behavior
```
clisles11sp4:~ # ls -l /var/tmp/
total 0

---

suma3pg-new:~ # salt-ssh clisles11sp4 -i --roster-file=/tmp/tmp_roster grains.get uuid -w -W
clisles11sp4:
    cb2956de-5a8c-e44d-85a8-fc8d1b170412

---

clisles11sp4:~ # ls -l /var/tmp/
total 0
```

### Tests written?

No

/cc @isbm

2017-07-10 14:04 UTC, isbm requested changes

2017-07-10 14:04 UTC, isbm commented on salt/client/ssh/__init__.py
> +                            "test.ping",
I personally not the fan of this approach. Either create a single point of "wipe out" and react as wipe out, or fix _every function_. What you do here is a workaround where "some functions do call it, so let call those functions" thing.

Instead I would do something like:
```python
if 'ssh_wipe' in self.opts:  # "ssh_wipe" should be a constant!
    try:
        wipe_here_the_thing_now()
    except WhateverValidExceptionClassOfTheDay as ex:
        log.error(............)
```

2017-07-10 14:05 UTC, isbm commented
> ## Tests written?
>
> No

/cc @meaksh :wink:

2017-07-10 14:12 UTC, meaksh commented
Marking as [WIP], let's think a bit on this. 😄 

Thanks for your feedback @isbm !

2017-07-10 14:21 UTC, meaksh commented
BTW tests would go to `salt-toaster`: https://github.com/openSUSE/salt-toaster/blob/master/tests/ssh/test_ssh.py

2017-07-31 23:04 UTC, cachedout commented
Hi @meaksh. Do you want this to stay open or do you want to close it and come back to it another day?

2017-08-06 18:09 UTC, cachedout commented
No response from @meaksh so we're closing this for now. I'm happy to re-open it when you're ready to come back to it though. Thanks!

2017-08-06 18:09 UTC, closed without merging

2017-08-07 14:38 UTC, meaksh commented
@cachedout - Sorry for the late response, I was on vacations for a few days. I'll ping you as soon as I'm back with this, thanks!