Added mssql_user state
saltstack/salt pull request #42316
Opened 2017-07-14 19:48 UTC by pakdel

### What does this PR do?
Add `mssql_user.present` and `mssql_user.absent`
It also adds minor features to `mssql` execution module

### What issues does this PR fix or reference?

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-07-14 19:50 UTC, pakdel commented on salt/modules/mssql.py
> -    # 'database' argument is mandatory
'database' has a default value and is not mandatory

2017-07-17 14:04 UTC, cachedout requested changes

2017-07-17 14:04 UTC, cachedout commented on salt/modules/mssql.py
> +def login_create(login, new_login_password=None, new_login_domain=None, new_login_options=[], **kwargs):
We cannot have mutable values like lists as default keyword arguments. Please change this to something like `None` and then transform it to a list inside the function if necessary.

2017-07-17 14:04 UTC, cachedout commented on salt/modules/mssql.py
> +def user_create(username, login=None, domain=None, database=None, roles=[], options=[], **kwargs):
Same here. Please don't use lists as defaults.

2017-07-17 14:04 UTC, cachedout commented on salt/states/mssql_user.py
> +def present(name, password=None, domain=None, database=None, roles=[], login_options=[], user_options=[], **kwargs):
Same here. Please no default lists.

2017-07-20 15:08 UTC, pakdel commented
@cachedout I believe I fixed those issues

2017-07-21 16:01 UTC, pakdel commented
Deprecated by https://github.com/saltstack/salt/pull/42460

2017-07-21 16:01 UTC, closed without merging