Document use of python methods in jinja
saltstack/salt pull request #42346
Opened 2017-07-17 19:27 UTC by edgan

### What does this PR do?
It adds to the Salt jinja documentation mention of a the use of python methods on variables. This is lacking in the official Jinja documentation, and is an open issue, https://github.com/pallets/jinja/issues/273 . Even the salt documentation hints at it, but doesn't call it out.

2017-07-18 17:21 UTC, cachedout requested changes
Just some minor style fixups are needed here and then we can get this merged. Thanks, @edgan !

2017-07-18 17:21 UTC, cachedout commented on doc/topics/jinja/index.rst
> +Python methods
`Python Methods`

2017-07-18 17:21 UTC, cachedout commented on doc/topics/jinja/index.rst
> +A power feature of jinja that is only hinted at in the official jinja
`powerful`

2017-07-18 17:34 UTC, edgan commented on doc/topics/jinja/index.rst
> +Python methods
I had considered this, but found that not all titles were completely capitalized.

2017-07-18 17:35 UTC, edgan commented on doc/topics/jinja/index.rst
> +A power feature of jinja that is only hinted at in the official jinja
This I have to disagree with you. I think powerful sounds better, and if you don't like the style the whole word could just be dropped. I think "A feature" sounds better than "A power feature".

2017-07-18 17:39 UTC, edgan reviewed
Ok, I have made those changes. I was mixed up in what you were suggesting at first. I thought what I had submitted was a little different.

2017-07-18 17:46 UTC, cachedout commented
@edgan Looks much better. Thanks!

2017-07-18 17:46 UTC, cachedout approved these changes

2017-07-19 15:53 UTC, rallytime approved these changes

2017-07-19 15:53 UTC, merged