VMware utils functions: additional logs & raise NoPermission exceptions
saltstack/salt pull request #42354
Opened 2017-07-18 09:23 UTC by alexbleotu

### What does this PR do?

Logs VMWare exceptions and raises correct messages when vim.fault.NoPermission errors are caught

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-07-18 17:26 UTC, cachedout requested changes
There are a number of cases here where we could use `log.exception` instead of `log.error`. I've highlighted two but there are more.

2017-07-18 17:26 UTC, cachedout commented on salt/utils/vmware.py
> +                log.error(exc)
This should probably be `log.exception`

2017-07-18 17:26 UTC, cachedout commented on salt/utils/vmware.py
> +                    log.error(exc)
same here wrt log.exception

2017-07-19 13:51 UTC, alexbleotu commented on salt/utils/vmware.py
> +                log.error(exc)
Didn't know about this - thanks Mike!

2017-07-19 13:52 UTC, alexbleotu commented on salt/utils/vmware.py
> +                    log.error(exc)
Done

2017-07-20 21:42 UTC, alexbleotu commented
@cachedout I've done the changes. Can you please have a look?

2017-07-31 20:03 UTC, cachedout approved these changes

2017-07-31 20:03 UTC, merged