win_pki: Don't fail on certs without DnsNames
saltstack/salt pull request #42457
Opened 2017-07-21 15:02 UTC by carlpett

### What does this PR do?
`item['DnsNameList']` is None for some certificates (among others a handful included in the default Windows root CA store). This PR makes this case not crash.

### What issues does this PR fix or reference?
#42455

### Previous Behavior
Crash

### New Behavior
Normal operation

### Tests written?
No

2017-07-21 18:13 UTC, twangboy requested changes

2017-07-21 18:13 UTC, twangboy commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
How about a get statement here instead...
```
cert_info['dnsnames'] = [name['Unicode'] for name in item.get('DnsNameList', [])]
```

2017-07-21 21:55 UTC, cachedout commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
If you fall back to a list there, i think the lookup on the left side of the comprehension will fail.

2017-07-21 23:03 UTC, twangboy commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
@cachedout 
```
cert_info['dnsnames'] = [name.get('Unicode') for name in item.get('DnsNameList', [])]
```
?

2017-07-22 06:58 UTC, carlpett commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
@twangboy `name['Unicode']` expects `name` to be a dict, while it falls back to a list in your suggestion. If my original patch is lacking in readability, I could just change it to a regular if/else block?

2017-07-24 17:03 UTC, twangboy commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
Maybe this then?
```
cert_info['dnsnames'] = [name.get('Unicode') for name in item.get('DnsNameList', {})]
```

2017-07-24 18:46 UTC, carlpett commented on salt/modules/win_pki.py
> +        cert_info['dnsnames'] = [name['Unicode'] for name in item['DnsNameList'] or []]
Yep, that should work. Updated the PR.

2017-07-24 21:16 UTC, twangboy approved these changes

2017-07-25 18:45 UTC, merged