Add runas_passwd as a global for states
saltstack/salt pull request #42603
Opened 2017-07-27 21:53 UTC by twangboy

### What does this PR do?
The following PR added `runas` as a global state variable. 

https://github.com/saltstack/salt/pull/39248

This breaks runas functionality in Windows as Windows also requires a password. This adds another global state variable named `runas_passwd`.

### What issues does this PR fix or reference?
Found while helping Charles

### Previous Behavior
Runas would fail on Windows when run from a state.

### New Behavior
Runas now works from a state

### Tests written?
No

2017-07-27 23:11 UTC, gtmanfred requested changes
You will also need to add runas_password to the state level reserved words.

https://github.com/saltstack/salt/blob/2017.7/salt/state.py#L99

There should also probably be a log in the cmd state warning that runas_password should be used.

2017-07-27 23:11 UTC, gtmanfred commented on salt/modules/cmdmod.py
> +        password = __context__.get('runas_passwd')
I think runas_password is better so that it isn't confusing where one is shortened and one isn't.

2017-07-27 23:11 UTC, gtmanfred commented on doc/ref/states/requisites.rst
> +        - password: supersecret
this should be runas_password

2017-07-27 23:33 UTC, gtmanfred commented
This is what I would add to the cmd states.

```
if 'password' in kwargs:
    log.debug('password is deprecated, please use runas_password')
kwargs['password'] = kwargs.pop('runas_password', None)
```

This will make it so that when people use the state from a state file or from `__states__` it will accept the same variables.

2017-07-28 00:03 UTC, twangboy commented on doc/ref/states/requisites.rst
> +        - password: supersecret
This is in the state file. I think it stays password. That's what's documented. If we rename it, then we'll have to do a bunch of deprecation stuff.

2017-07-28 00:06 UTC, gtmanfred commented on doc/ref/states/requisites.rst
> +        - password: supersecret
Right, in the state file is where it matters.  It is a global state variable, the salt.state intercepts it and puts it in the __context__.

2017-07-28 17:41 UTC, gtmanfred approved these changes

2017-07-31 19:49 UTC, thatch45 approved these changes
Yes, this is being inserted correctly.

2017-07-31 19:49 UTC, merged