python2- prefix for fedora 26 packages
saltstack/salt pull request #42651
Opened 2017-07-31 19:26 UTC by gtmanfred

### What does this PR do?
The package name was changed in Fedora 26

### Tests written?

Yes

2017-07-31 19:28 UTC, Ch3LL approved these changes

2017-08-01 17:38 UTC, cachedout commented
Go Go Jenkins!

2017-08-04 14:45 UTC, terminalmage approved these changes

2017-08-06 17:54 UTC, cachedout commented
Go Go Jenkins!

2017-08-06 17:55 UTC, cachedout requested changes

2017-08-06 17:55 UTC, cachedout commented on salt/client/__init__.py
> +            for failed in list(set(pub_data['minions']) - set(ret)):
Eh? What is this doing in a PR about package naming? :]

2017-08-06 19:16 UTC, gtmanfred commented on salt/client/__init__.py
> +            for failed in list(set(pub_data['minions']) - set(ret)):
yup, not sure how that ended up on the top of this.

fixed.

2017-08-07 14:34 UTC, rallytime approved these changes

2017-08-07 14:35 UTC, merged