Add token_expire_user_override link to auth runner docstring
saltstack/salt pull request #42709
Opened 2017-08-02 20:21 UTC by whiteinge

### What does this PR do?

Cross-link some docs.

2017-08-03 20:28 UTC, cachedout commented on salt/runners/auth.py
> +    Non-root users may specify an expiration data if allowed via the
`expiration data`? `date`? If so, how is that specified?

2017-08-04 16:43 UTC, garethgreenaway commented
Go Go Jenkins!

2017-08-04 21:10 UTC, whiteinge commented on salt/runners/auth.py
> +    Non-root users may specify an expiration data if allowed via the
Good catch.

2017-08-06 17:40 UTC, cachedout requested changes

2017-08-06 17:40 UTC, cachedout commented on salt/runners/auth.py
> +    ``token_expire`` param.
It's not clear from reading this what the parameter should *be* though. Below I see an example of it being `94670856` but I have no idea what this means. Could we clarify this a bit, perhaps with an example and explanation?

2017-08-07 21:38 UTC, whiteinge commented on salt/runners/auth.py
> +    ``token_expire`` param.
Good point, thanks.

2017-08-14 19:02 UTC, rallytime approved these changes

2017-08-14 19:03 UTC, merged