Set force=true when removing a windows directory
saltstack/salt pull request #42732
Opened 2017-08-03 20:28 UTC by michelsm

### What does this PR do?

Provides an additional check when file.absent is being applied to a directory. This allows windows directories to be forcefully removed by setting the force field equal to true.

This PR fixes an inconsistency that currently exsists when using file.absent to remove a single file on windows vs removing a windows directory.

Currently removing windows...
- file uses file.remove with force=true
- directory uses file.remove with force=false

As a result, this PR will ensure that the removal of windows directories is executed with the same logic.

### What issues does this PR fix or reference?

Inability for users to forcefully remove windows directories (becomes an issue with permissions).
Inconsistencies between the removal of windows files and windows directories with file.absent.

### Previous Behavior

Prior to this PR, the functionality of forceful removal was not implemented for directories.
This poses an issue for windows users due to permission constraints.

### New Behavior

Windows users have the ability to forcefully remove directories without the interference of permissions. The changes implemented for directories now follow the same logic that was previously set for files.

### Tests written?

No

2017-08-03 22:25 UTC, twangboy approved these changes

2017-08-09 13:39 UTC, michelsm commented
Since this PR has received approval, when can I expect these changes to be merged?

2017-08-09 16:34 UTC, twangboy requested changes

2017-08-09 16:34 UTC, twangboy commented on salt/states/file.py
> +        	if salt.utils.is_windows():
Needs another space in the indentation here... It's failing lint.

2017-08-09 17:30 UTC, michelsm commented
Spacing has been fixed.

2017-08-09 21:03 UTC, twangboy approved these changes

2017-08-10 12:34 UTC, michelsm commented
Hi, I'm new to this and can see that this PR has been approved. Is there anything else I need to do to get my PR merged?

2017-08-10 13:50 UTC, rallytime commented
Hi @michelsm and welcome!

I have assigned @terminalmage to take a look at this. Once he has a chance to review it, we can go from there. Thank you for your contribution!

2017-08-10 13:53 UTC, terminalmage approved these changes

2017-08-10 13:54 UTC, merged

2017-08-10 13:55 UTC, terminalmage commented
@michelsm Thanks! And congrats on your first Salt PR!