Resolve SDB in flat roster
saltstack/salt pull request #42746
Opened 2017-08-04 16:06 UTC by amendlik

### What does this PR do?
Add SDB support to the flat roster

### What issues does this PR fix or reference?
None

### Previous Behavior
Flat roster did not resolve sdb:// URLs

### New Behavior
Flat roster resolves sdb:// URLs

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-08-04 19:34 UTC, gtmanfred requested changes

2017-08-04 19:34 UTC, gtmanfred commented on salt/roster/flat.py
> +        conditioned_raw[str(minion)] = _resolve_sdb(raw[minion])
Is there a reason to not use `salt.config.apply_sdb`?

2017-08-04 22:25 UTC, amendlik commented on salt/roster/flat.py
> +        conditioned_raw[str(minion)] = _resolve_sdb(raw[minion])
I did not know that function existed. It does the exact same thing as `_resolve_sdb`, so I'll use `salt.config.apply_sdb`. Thanks!

2017-08-06 17:38 UTC, cachedout commented
@gtmanfred Re-review requested.

2017-08-06 19:19 UTC, gtmanfred approved these changes

2017-08-06 19:19 UTC, gtmanfred commented
Looks good to me!

2017-08-08 17:19 UTC, merged