[develop] Adding fingerprint_hash_type to known host example.
saltstack/salt pull request #42756
Opened 2017-08-04 22:20 UTC by nixjdm

Since 2017.7.0 [the existing example](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ssh_known_hosts.html) would not have worked without this change.

### What does this PR do?
Updates documentation to conform to existing behavior, changed in 2017.7.0

### What issues does this PR fix or reference?
None. It's a simple docs update and I couldn't find a related ticket.

### Tests written?

N/A

2017-08-06 17:36 UTC, cachedout requested changes

2017-08-06 17:36 UTC, cachedout commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
This should be `sha256` though.

2017-08-06 19:29 UTC, nixjdm commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
The current line 14 here is [the hexed md5 format of GitHub's fingerprint](https://help.github.com/articles/github-s-ssh-key-fingerprints/).

They could be two different examples. There currently isn't a sha256 example in the docs anywhere that I've seen.

2017-08-07 20:55 UTC, cachedout commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
Then we need to change the fingerprint example as well. :]

2017-08-15 04:35 UTC, cachedout commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
@nixjdm Did you want to change the examples to SHA-256 and away from MD5? If not, we can have somebody else do it and then come back to this PR after that is done.

2017-08-16 21:18 UTC, nixjdm commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
I'm fine having only a sha256 example. I'll give it a shot. I'll try to get my own code using the sha256 hast type and update this if I get that working. Give me a couple days, please.

2017-08-18 22:37 UTC, nixjdm commented on salt/states/ssh_known_hosts.py
> +        - fingerprint_hash_type: md5
@cachedout I haven't gotten sha256 to work for me, so I'll not add that example and leave this md5 one.

I tried with the github hash of `SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8`, and without the prefix as `nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8`, with and without a line reading `- fingerprint_hash_type: sha256`. If I'm simply doing something wrong, I'd appreciate some else fixing this bit of documentation so I can use sha256 myself. In the meantime I'll have to stick with md5.

2017-09-11 19:36 UTC, cachedout commented
Go Go Jenkins!

2017-09-12 16:30 UTC, merged