develop: Allow creation_token to be passed into create_file_system an…
saltstack/salt pull request #42811
Opened 2017-08-08 21:23 UTC by hibbert

…d get_file_system

Change-Id: I49734011406ad847290ab3a42beb23f89d2de269

What does this PR do?

Allows you to pass in creation_token or set it based on name, so you can create a file system idempotently when calling boto_efs.create_file_system and allows you to specify creation_token when searching for file systems in boto_efs.get_file_systems

What issues does this PR fix or reference?

Previous Behavior

You run salt once with a name for the EFS, it will create the EFS with a random creation_token, if you run it again you will get another file system with a different creation_token.

You cannot search for a file system using a creation_token.

New Behavior

By default the creation_token when creating the filesystem will be set based on the name you also have the option of passing it in. Either way this will stop another filesystem being created on a second salt run.

When searching for a filesystem you have the option of passing in creation_token, which is now unique, this is easier to search on than filesystemid which will always be unique.

Tests written?

No

Please review Salt's Contributing Guide for best practices.

2017-08-10 18:58 UTC, rallytime requested changes

2017-08-10 18:58 UTC, rallytime commented on salt/modules/boto_efs.py
> +                       creation_token=None,
Can you move this new kwarg to the end of the list? We don't want to cause an API change and break functions that may be using position options.

2017-08-10 18:58 UTC, rallytime commented on salt/modules/boto_efs.py
> +                     creation_token=None,
Same comment as above on this addition as well.

2017-08-10 18:59 UTC, rallytime commented
Hi @hibbert and welcome!

I have two comments that need to be addressed above before we can get this change in. I would also like @ryan-lane to look at this as well.

Thank you for your contribution!

2017-08-21 20:36 UTC, cachedout commented
@hibbert Did you see the above requests?

2017-08-23 18:09 UTC, cachedout commented
@ryan-lane Did you have any interest in looking at this?

2017-08-25 19:36 UTC, ryan-lane commented
+1 looks good

2017-08-30 16:05 UTC, rallytime approved these changes

2017-08-30 19:13 UTC, rallytime commented
re-run lint

2017-08-30 20:02 UTC, merged