Yield timed out minions from LocalClient.cmd_iter
saltstack/salt pull request #42820
Opened 2017-08-09 13:43 UTC by cenkalti

### What does this PR do?

Makes `LocalClient.cmd_iter` return value consistent with `LocalClient.cmd`

### What issues does this PR fix or reference?

Fixes #42711

### Previous Behavior

Timed out minions are not yielded from the iterator.

### New Behavior

Timed out minions are yielded from the iterator.

### Tests written?

No

2017-08-14 17:39 UTC, rallytime requested changes

2017-08-14 17:39 UTC, rallytime commented on salt/client/__init__.py
> +                kwargs.setdefault('expect_minions', True)
I would rather see something like this implemented as a new kwarg defined in the function's argspec. That way, the default behavior here can be set to True, but when other functions call `cmd_iter`, we can account for any potential behavior changes.

Specifically, I am worried about a behavior change in `salt/daemons/masterapi.py` and `salt/cli/batch.py` files and where `expect_minions` is already defaulted to `False` in `get_iter_returns`.

2017-08-30 16:03 UTC, rallytime commented
@cenkalti Did you have a chance to look at my comments here?

2017-09-05 11:07 UTC, cenkalti commented
@rallytime Sorry for the late reply.

I think introducing a new kwarg will complicate the implementation and make it harder to understand the behavior. I suggest improving the documentation of `cmd_iter` method instead of applying this change. Passing `expect_minions=True` solves the issue discussed in #42711.

2017-09-05 14:55 UTC, rallytime commented
Hi @cenkalti - no problem! Thanks for responding.

While I do think that adding some documentation here is a good idea, I don't think a doc change is sufficient. Changing this default without a flag does not address the concern I raised above where places in salt code are already using the `False` default could have unexpected behavior changes resulting in regressions.

While this PR fixes the issue you've mentioned, I want this fix to be safer about behavioral changes and regressions.

I don't think we should merge this without implementing this as a flag, and the aforementioned calls to `cmd_iter` in the salt codebase should be updated accordingly to use this flag. Adding documentation for this change would also be good to have.

2017-09-06 12:23 UTC, cenkalti commented
@rallytime I have added `yield_all_minions` flag that defaults to `True`. If the name of the flag and the implementation is okay to you I will update all invocations of `cmd_iter` and `cmd_iter_no_block` in codebase to add the new flag.

2017-09-06 14:17 UTC, rallytime commented
Hi @cenkalti - That sounds like a great name. I like it. Thank you for adding the flag and I look forward to the seeing the next updates. :)

2017-09-11 20:42 UTC, thatch45 commented
My concern here is if this is going to cause any issues for upstream users of the client, this is just the type of thing that causes unforeseen regressions

2017-09-12 21:20 UTC, cenkalti commented
@thatch45 This change is not backwards compatible. If we want to keep backwards compatibility, this PR shouldn't be merged. In that case the documentation of `cmd_iter` should state that it does not yield results for minions that are not connected. Passing `expect_minions=True` as keyword argument makes `cmd_iter` to include disconnected minions.

2017-09-12 22:08 UTC, thatch45 commented
Thanks @cenkalti for the clarification. I think that it would make more sense to update the docs on this then

2017-09-13 17:18 UTC, cachedout commented
@rallytime and @thatch45 Re-review requested.

2017-09-13 17:49 UTC, rallytime approved these changes

2017-09-29 22:39 UTC, thatch45 approved these changes

2017-10-01 14:08 UTC, merged