API changes for Kubernetes version 2.0.0
saltstack/salt pull request #42845
Opened 2017-08-10 14:53 UTC by brejoc

### What does this PR do?

Switching to the new [Kubernetes client lib](https://pypi.python.org/pypi/kubernetes/2.0.0) API introduced with version 2.0.0.

### What issues does this PR fix or reference?

#42843

### Previous Behavior
You had to use Kubernetes Python client version 1.0.2.

### New Behavior
Now you can use Kubernetes Python client version 2.0.0.

### Tests written?

No

2017-08-10 14:55 UTC, gtmanfred requested changes
Is there a reason we can't gate these changes, and allow both the old and this newer version of kubernetes python client to be installed?

2017-08-11 07:04 UTC, brejoc commented
@gtmanfred You are absolutely right – I think there is no reason not to do that. Thanks! Changed it.

2017-08-11 08:37 UTC, brejoc commented
@meaksh Would you be so kind to also take a look!? Thanks!

2017-08-11 08:57 UTC, meaksh approved these changes
Apart from the previous comment about `:optdepends:` documentation tag, it looks good to me!

Thanks @brejoc for fixing this! 👍 😄

2017-08-11 08:57 UTC, meaksh commented on salt/modules/kubernetes.py
> +:optdepends:    - kubernetes Python client up to version 2.0.0
I would remove this `:optdepends:` change, since the current status of this PR also allows to use lower versions of kubernetes Python client.

2017-08-11 12:50 UTC, flavio commented
LGTM too

2017-08-11 13:57 UTC, gtmanfred approved these changes

2017-08-11 14:04 UTC, rallytime approved these changes

2017-08-11 14:04 UTC, merged