Make chunked mode in salt-cp optional
saltstack/salt pull request #42890
Opened 2017-08-11 19:48 UTC by DmitryKuzmenko

### What does this PR do?
Make chunked mode in salt-cp optional, disabled by default.
It could be enabled with `--chunked` or `-C` cmdline flag.

### What issues does this PR fix or reference?
Fixes #42627 

### Tests written?
No

2017-08-14 14:28 UTC, rallytime requested changes
@DmitryKuzmenko This looks good to me. I just had a couple of small spelling and versioning items to fix here.

@terminalmage Should review this as well.

2017-08-14 14:28 UTC, rallytime commented on doc/ref/cli/salt-cp.rst
> +.. versionchanged:: 2016.11.7,Nitrogen
This versionchanged tag needs to be updated: `Nitrogen` should be `2017.7.2`

2017-08-14 14:28 UTC, rallytime commented on doc/ref/cli/salt-cp.rst
> +    The new chunked mode is available with the new ``-C``, ``--cunked`` argument.
Minor spelling fix: `--cunked` should be `--chunked`

2017-08-14 14:28 UTC, rallytime commented on doc/ref/cli/salt-cp.rst
> +    .. versionadded:: 2016.11.7,Nitrogen
Same version change here: `Nitrogen` -> `2017.7.2`

2017-08-14 14:28 UTC, rallytime commented on doc/ref/cli/salt-cp.rst
> +    Returned tha old mode when salt-cp copies all files in one command back.
Spelling: `tha` should be `the`.

2017-08-14 15:09 UTC, DmitryKuzmenko commented
Fixed. Thank you @rallytime !

2017-08-14 15:31 UTC, rallytime approved these changes

2017-08-15 16:16 UTC, terminalmage approved these changes

2017-08-15 16:17 UTC, terminalmage approved these changes
This looks good. There's only one change I'd make, and it's in the documentaton. We can always get that changed in a separate PR though.

2017-08-15 16:17 UTC, terminalmage commented on doc/ref/cli/salt-cp.rst
> +.. versionchanged:: 2016.11.7,2017.7.2
The wording here could be improved. How about this?

```rst
.. versionchanged:: 2016.11.7,2017.7.2
    Reverted back to the old copy mode to preserve backward compatibility. The
    new functionality added in 2016.6.6 and 2017.7.0 is now available using the
    ``-C`` or ``--chunked`` CLI arguments. Note that compression, recursive
    copying, and support for copying large files is only available in chunked
    mode.
```

2017-08-17 13:48 UTC, DmitryKuzmenko commented on doc/ref/cli/salt-cp.rst
> +.. versionchanged:: 2016.11.7,2017.7.2
Thank you @terminalmage .
I've updated the doc.

2017-08-17 14:41 UTC, rallytime commented
Go Go Jenkins!

2017-08-17 16:05 UTC, garethgreenaway commented
Go Go Jenkins!

2017-08-17 18:37 UTC, merged