fix bug #42936 - win_iis container_setting
saltstack/salt pull request #42970
Opened 2017-08-16 08:55 UTC by Mapel88

Module fix
- Failure / success validation is now working properly
- Server 2008 user can now use either numeric or string id

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-08-16 16:44 UTC, twangboy requested changes

2017-08-16 16:44 UTC, twangboy commented on salt/modules/win_iis.py
> +    def identity_type_map(identity_id,map_type):
Please put spaces between parameters: `identity, map_type`

2017-08-16 16:44 UTC, twangboy commented on salt/modules/win_iis.py
> +        available_ids = ('0','1','2','3','4','LocalSystem','LocalSystem','NetworkService','SpecificUser','ApplicationPoolIdentity')
Please place spaces between items in the list.
Second string item should be `LocalService`
Also, wrap after 80 characters:
```
        available_ids = ('0', '1', '2', '3', '4', 'LocalSystem', 'LocalService',
                         'NetworkService', 'SpecificUser',
                         'ApplicationPoolIdentity')
```

2017-08-16 16:44 UTC, twangboy commented on salt/modules/win_iis.py
> +
Actually, maybe using a dictionary would be a little cleaner and remove the need for the `map_type` paramter:

```
        available_ids = {'0': 'LocalSystem',
                         '1': 'LocalService',
                         '2': 'NetworkService',
                         '3': 'SpecificUser',
                         '4': 'ApplicationPoolIdentity',
                         'localsystem': '0',
                         'localservice': '1',
                         'networkservice': '2',
                         'specificuser': '3',
                         'applicationpoolidentity': '4'}
        if ID.lower() in available_ids:
            return available_ids(ID.lower())
        else:
            raise CommandExecutionError('Identity not found: {0}'.format(identity_id))
```

2017-08-16 16:44 UTC, twangboy commented on salt/modules/win_iis.py
> +
If you go with the dictionary approach above, then you wouldn't need the `'string'` parameter.

2017-08-17 09:39 UTC, Mapel88 commented on salt/modules/win_iis.py
> +
You are correct.
Using dictionary makes much more sense.
Will fix state accordingly

2017-08-20 12:05 UTC, closed without merging