Added unit tests for Kubernetes module
saltstack/salt pull request #42975
Opened 2017-08-16 12:55 UTC by brejoc

Added unit tests for:
    * Node listing,
    * deployment listing,
    * service listing,
    * pod listing,
    * deployment deletion and
    * deployment creation.

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-08-17 18:06 UTC, rallytime requested changes
Thanks for adding tests @brejoc! We always love that. :)

For the 2017.7 branch, we moved some things around in salttesting so we can use pytest. Can you rename this file `test_kubernetes.py` instead of kubernets_test? I also added a couple of comments that need to be fixed for lint.

Once the file is renamed and the other lint issues are fixed, we can see how the test run goes.

2017-08-17 18:06 UTC, rallytime commented on tests/unit/modules/kubernetes_test.py
> +from salttesting import TestCase, skipIf
Can you update this import to `from tests.support.unit import TestCase, skipIf`

2017-08-17 18:06 UTC, rallytime commented on tests/unit/modules/kubernetes_test.py
> +from salttesting.mock import (
This import also needs to be updated to `from tests.support.mock import (`

We moved a bunch of the salttesting libs around for 2017.7 and onward.

2017-08-17 18:06 UTC, rallytime commented on tests/unit/modules/kubernetes_test.py
> +import os
This import isn't used.

2017-08-19 20:37 UTC, brejoc commented
@rallytime The Kubernetes moduels has the [kubernetes](https://pypi.python.org/pypi/kubernetes/) client lib as a dependency. How can we make this happen for the test?

```14:27:16 ImportError: No module named kubernetes.client```

2017-08-21 20:29 UTC, cachedout commented
@brejoc There are some lint errors here. Let us know if you need any help resolving them.

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/13863/violations/file/tests/unit/modules/test_kubernetes.py/

2017-08-23 14:48 UTC, brejoc commented
@cachedout Sorry to bother you, but are the results for the linting job already gone? The link shows a 404.

2017-08-23 14:59 UTC, rallytime commented
Go Go Jenkins!

2017-08-28 19:38 UTC, rallytime commented
Hi @brejoc - I can add the kubernetes lib to our jenkins test prep states. In the mean time, these tests shouldn't be failing during a test-run out of the box. Can you gate these tests to skip if the required libs are not present?

2017-08-30 06:52 UTC, brejoc commented
@rallytime Okay, I think this should be fine now. What do you think?

2017-08-30 18:49 UTC, rallytime commented
@brejoc I think that looks good. Thank you!

I have added a state to install the kubernetes python client to our test VMs and I also updated your branch to the latest HEAD of 2017.7 so we can get a clean run and make sure your tests run accordingly.

2017-08-30 18:49 UTC, rallytime approved these changes
Pending latest test run, this looks good!

2017-08-30 20:30 UTC, merged