Allow cmdmod.exec_code_all to utilize cmdmod.run_all parameters
saltstack/salt pull request #42991
Opened 2017-08-16 19:42 UTC by DarkKnightCZ

### What does this PR do?
Allows cmdmod.exec_code_all to use all arguments from cmdmod.run_all (except python_shell)

### What issues does this PR fix or reference?
Fixes #42990 

### Previous Behavior
User was unable to pass custom script cmd arguments, set specific environment variables and others.

### New Behavior
User is able to pass all arguments from cmdmod.run_all

### Tests written?

Yes

2017-08-17 14:36 UTC, gtmanfred commented on salt/modules/cmdmod.py
> +    if isinstance(args, str):
this should be six.string_types

2017-08-17 14:36 UTC, gtmanfred requested changes
There is just one small change that I have for python3/unicode compatibility.

2017-08-17 16:09 UTC, DarkKnightCZ commented on salt/modules/cmdmod.py
> +    if isinstance(args, str):
@gtmanfred Right, missed that. Fixed in another commit

2017-08-17 16:10 UTC, gtmanfred approved these changes

2017-08-22 16:51 UTC, cachedout commented
Go Go Jenkins!

2017-08-25 21:25 UTC, merged