Super pomme de terre patch #26995
saltstack/salt pull request #43006
Opened 2017-08-17 10:04 UTC by SuperPommeDeTerre

### What does this PR do?
Attempt to fix #26995.
When downloading a SNAPSHOT artefact from Artifactory, the `maven-metadata.xml` file could not be present if the artifact is unique. So, the snapshot_version should be equal to `version`.

### What issues does this PR fix or reference?
#26995

### Previous Behavior
State `artifactory.downloaded` failed when `maven-metadata.xml` couln't be retrived from Artifactory for a SNAPSHOT artifact.

### New Behavior
The artifactory module assume `snapshot_version=version` when the metadata couldn't be retrived.

### Tests written?
No

2017-08-17 10:58 UTC, RostyslavFridman requested changes

2017-08-17 10:58 UTC, RostyslavFridman commented on salt/modules/artifactory.py
> +            log.error('Could not fetch maven-metadat.xml. Assuming snapshot_version=%s.', version)
Please fix the error message. `maven-metadat.xml` ->  `maven-metadata.xml`

2017-08-17 11:29 UTC, SuperPommeDeTerre commented on salt/modules/artifactory.py
> +            log.error('Could not fetch maven-metadat.xml. Assuming snapshot_version=%s.', version)
Fixed in commit 0b666e100bda9b71e39a193e609f302f43918d75.

2017-08-17 12:23 UTC, RostyslavFridman approved these changes

2017-08-21 22:12 UTC, cachedout commented
Go Go Jenkins!

2017-08-23 17:50 UTC, cachedout commented
@SuperPommeDeTerre We can't seem to get a clean test run here. Could I trouble you to please rebase this against the head of the 2017.7 branch?

2017-08-24 07:01 UTC, SuperPommeDeTerre commented
@cachedout Sure, I'll make this !

2017-08-25 08:18 UTC, SuperPommeDeTerre commented
@cachedout Still failing on `integration.modules.test_gem.GemModuleTest.test_update`.
Are there any update to this test ?

2017-08-25 15:24 UTC, SuperPommeDeTerre commented
@cachedout Finally found my mistake. It's much better, now !

2017-08-25 21:16 UTC, merged

2017-08-25 21:16 UTC, cachedout commented
Thanks very much @SuperPommeDeTerre !