Added feature to pass kwargs to the build process for docker_image.pr…
saltstack/salt pull request #43125
Opened 2017-08-23 00:35 UTC by pabloh007

…esent #42606

### What does this PR do?
It adds a feature where you can now pass keyword arguments on the salt state for the build process. It also checks the arguments available for the build function "only" so it other kwargs are passed that are not from the build function, they will be ignored.
### What issues does this PR fix or reference?
Previously you could not pass keyword args to the `docker.build`  
### New Behavior
you can now pass keyword args through docker_image.present state
`
web_service_img:0.0.5:
  docker_image.present:
    - build: /usr/share/dockerfiles/web_service
    - kwargs:
        buildargs:
           APP_VERSION: 0.0.5
`
### Tests written?
No

2017-08-23 18:00 UTC, terminalmage requested changes

2017-08-23 18:00 UTC, terminalmage commented on salt/states/docker_image.py
> +import salt.utils
Please change this to an import of `salt.utils.args`.

2017-08-23 18:21 UTC, pabloh007 commented
Update is done. Thanks!

2017-08-23 21:36 UTC, rallytime requested changes
There are a couple of pylint errors here. I've commented below with the needed changes. :)

2017-08-23 21:36 UTC, rallytime commented on salt/states/docker_image.py
> +import salt.utils.args
Can you add the following import here:
```
from salt.ext.six.moves import zip
```

2017-08-23 21:36 UTC, rallytime commented on salt/states/docker_image.py
> +        build_args = dict(zip(argspec.args, argspec.defaults))
And then change this to:
```
build_args = dict(list(zip(argspec.args, argspec.defaults)))
```

2017-08-23 21:40 UTC, rallytime commented
Hi @pabloh007 and welcome! The pylint failures reported are for Python 3 compatibility issues, and those are a little harder to figure out to spot the error with our lint report. Once you get those fixed up we can review this again. Thanks!

2017-08-23 21:46 UTC, pabloh007 commented
hey @rallytime  Ill work on those changes.

2017-08-30 15:58 UTC, rallytime commented
re-run lint

2017-09-01 15:54 UTC, rallytime approved these changes

2017-09-01 15:54 UTC, rallytime commented
@terminalmage re-review requested

2017-09-05 21:43 UTC, cachedout commented
@pabloh007 I apologize that this has taken a little while for us to get back to. This has some merge conflicts. Could you please resolve them and push up a fix? Thanks.

@terminalmage We need a very quick re-review from you. Should only take a moment since your concerns have been resolved. Thanks.

2017-09-05 21:59 UTC, pabloh007 commented
Have resolved conflicts @cachedout . Thanks!

2017-09-07 17:44 UTC, terminalmage approved these changes

2017-09-07 17:46 UTC, rallytime commented
Thanks @pabloh007!

2017-09-07 17:46 UTC, merged