[WIP] test grains access in module functions
saltstack/salt pull request #43137
Opened 2017-08-23 10:34 UTC by aogier

### What does this PR do?

This is a PoC that should show tests failure when accessing \_\_grains__ entries at least on current Jenkins environment. This behaviour has been observed in #42739 and I'm now trying to recreate it by just pushing a new test against "vanilla" develop branch.

2017-08-23 14:27 UTC, aogier commented
oops unit tests are failing, not integration ones, retry ! :)

2017-08-23 14:46 UTC, aogier commented
culprit is grains patching in unit tests, anyway this PR implements a system group integration test we could use anyway

2017-08-23 16:58 UTC, cachedout commented
@terminalmage Is this the same problem you were chasing down the other day?

2017-08-23 18:59 UTC, aogier commented
FYI I've later found that the culprit where in unit tests, not in integration as title suggest (see [here](https://github.com/saltstack/salt/issues/42739#issuecomment-324354667)). I'm pretty a newbie especially on this dunder magic so it's my fault and not a codebase issue ! :)

2017-09-05 21:50 UTC, terminalmage requested changes
My personal preference would be to move this to its own test, called `test_add_system_group`. You could just add the following before the new code:

```python
     @destructiveTest
     def test_add_system_group(self):
         '''
         Test the add group function with system=True
         '''
```

This will also allow you to remove the `group.delete`, as that will have been handled in the `tearDown`.

2017-09-05 21:50 UTC, terminalmage commented
@cachedout This doesn't sound familiar.

2017-09-07 15:13 UTC, aogier commented
@terminalmage thank you for feedback: I've implemented a couple of system group specific tests that amongst other things work in system gid ranges derived by system configs. I think code is now ready for review.

Thank you, regards

2017-09-08 08:34 UTC, aogier commented
squashed and rebased on last develop

2017-09-11 19:09 UTC, merged