[Feature] Add grains to detect default gateway
saltstack/salt pull request #43182
Opened 2017-08-24 21:43 UTC by basepi

### What does this PR do?

Adds 3 grains, `ip_gw`, `ip4_gw`, and `ip6_gw` to the core grains, based on whether a default gateway shows up in `ip route show`.

### Tests written?

No

2017-08-24 21:53 UTC, terminalmage commented
Why not put the gateway IP in the grain? That could be useful.

2017-08-24 22:07 UTC, basepi commented
Mostly because this was easy, and all I needed for my hosts.

2017-08-24 22:07 UTC, basepi commented
I can probably do some logic massaging and testing tomorrow or Monday if we want the actual gateway IP.

2017-08-25 05:14 UTC, terminalmage commented
I personally think that having the gateway IP would be useful. @cachedout thoughts?

2017-08-25 19:17 UTC, cachedout commented
Yeah, I have to agree with @terminalmage on this one. As a new user, I wouldn't expect this to be a boolean. I'd expect it to contain the gateway itself. We can easily help modify this one to do that though. You know where to find us. :]

2017-08-25 20:35 UTC, basepi commented
Nah, it's easy, it will just take a little more testing which I won't have time to do until next week. I'll get it in.

2017-08-26 00:50 UTC, damon-atkins commented
Note you can have more than one default gateway, not that many people do.

Something that would be use full is the network the default gateway is on, which then can be used to determine all sorts of things, like picking the NTP and DNS server to use.

2017-08-28 16:56 UTC, basepi commented
Right. The problem is that ip routing can be as complex as you want it to be. `default` can redirect to another routing table, there can be multiple `default` entries (though you'll only fall through if you don't get routed on those other entries), etc etc. I did a little bit of dumb parsing, just looking for the `default via` entry which appears to be the standard for simple routing tables. If I can't find it that way, I just set the grain to True instead.

If someone wants to try to make this smarter, more power to them. But beware migraines......

2017-09-05 21:31 UTC, cachedout requested changes
I think that @damon-atkins has a reasonable point here but I can understand that's it's a rare case.

@basepi If you'll update the documentation to indicate that multiple gateways on the same host are not supported by this grain presently, then we can merge it, I think.

2017-09-05 21:35 UTC, basepi commented
@cachedout Done.

2017-09-11 18:59 UTC, cachedout approved these changes

2017-09-11 18:59 UTC, merged