Win fix pkg.install
saltstack/salt pull request #43228
Opened 2017-08-28 18:24 UTC by twangboy

### What does this PR do?
Fixes `pkg.install`
Uses regex to detect salt-minion install in the software def (https://github.com/saltstack/salt/pull/42861#pullrequestreview-56255328)

### What issues does this PR fix or reference?
Found in testing

### Previous Behavior
pkg.install would fail

### New Behavior
pkg.install now works....

### Tests written?
No

2017-08-28 18:54 UTC, damon-atkins commented
Maybe add ._ as well before - for good measure `r'salt[\s._-]*minion'`

2017-08-29 15:14 UTC, twangboy commented
@damon-atkins Done

2017-08-29 17:44 UTC, twangboy commented
Rebased

2017-08-29 18:42 UTC, damon-atkins requested changes

2017-08-29 18:42 UTC, damon-atkins commented on salt/modules/win_pkg.py
> +            if re.search(r'salt[\s-_]*minion', pkg_name, flags=re.IGNORECASE+re.UNICODE) is not None:
`r'salt[\s-_]*minion' `  needs to be `r'salt[\s_-]*minion'` or `r'salt[\s_.-]*minion'` (with . if you want salt.minion)
As like `[a-z]` unless `-` is last it means a range.

2017-08-30 03:19 UTC, damon-atkins approved these changes

2017-08-30 14:26 UTC, rallytime approved these changes

2017-08-30 14:26 UTC, merged