Update __init__.py
saltstack/salt pull request #43236
Opened 2017-08-29 08:08 UTC by akurach

add support for unicode symbols in vm names.
fix for '''UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 5: ordinal not in range(128)'''

### What does this PR do?
add support for unicode symbols in vm names.
fix for '''UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 5: ordinal not in range(128)'''

### Previous Behavior
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 5: ordinal not in range(128)

### New Behavior
works!

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-08-29 13:58 UTC, gtmanfred requested changes

2017-08-29 13:58 UTC, gtmanfred commented on salt/cloud/__init__.py
> +from __future__ import absolute_import, print_function, generators,unicode_literals
you need a space after the comma and then pylint will pass

2017-08-29 14:45 UTC, damon-atkins commented
Keep in mine you can not general mix PY2 Strings and Unicode.   May need to test all external input is Unicode and if it is not convert it to Unicode.
 
In theory develop is moving to Unicode by default ( @terminalmage  )

modules win_pkg.py and reg.py have support Unicode since 2016.11

2017-08-29 14:52 UTC, akurach commented
@damon-atkins hi, i got that error while do salt-cloud -a show_instance vmname. 
seems like one(ore more) of our customers create vm with non-eng symbol. And when salt tries to find $vmname it falls down.

2017-08-31 08:10 UTC, akurach commented
@gtmanfred done)

2017-08-31 15:04 UTC, gtmanfred approved these changes

2017-08-31 15:25 UTC, rallytime approved these changes

2017-08-31 15:25 UTC, merged