mine_interval option is minutes not seconds
saltstack/salt pull request #43325
Opened 2017-09-01 21:02 UTC by doesitblend

### What does this PR do?
Update documentation regarding the configuration of the `mine_interval` option. Documentation at https://docs.saltstack.com/en/latest/ref/configuration/minion.html#mine-interval and https://github.com/saltstack/salt/blob/0931281ebd1ca794b27bf7dc4e918efd3a05c612/conf/minion#L376 currently show that the option is configured in seconds. However, the documentation at https://docs.saltstack.com/en/latest/topics/mine/#mine-interval infers that the option is configured in minutes.

2017-09-01 21:02 UTC, doesitblend commented
ZD 1728

2017-09-01 21:04 UTC, cachedout requested changes

2017-09-01 21:04 UTC, cachedout commented on conf/minion
> +# The number of minutes between when a mine update runs.
This phrasing may be extremely confusing to non-English speakers.

2017-09-05 15:29 UTC, rallytime reviewed
This language is much better, thanks!

I also think that updating the code comment in `salt/config/__init__.py` for the `mine_interval` option would be a good idea to add to this pull request as well to reduce confusion.

Would you mind adding that, too, @doesitblend?

2017-09-05 18:19 UTC, cachedout commented
+1 to adding this to the `config` package

2017-09-07 13:23 UTC, rallytime approved these changes
Thanks @doesitblend! And congratulations on your first pull request. :)

👍

2017-09-07 16:58 UTC, merged