Add a file.link state for hard links
saltstack/salt pull request #43380
Opened 2017-09-06 22:36 UTC by aneeshusa

### What does this PR do?
Adds a file.link state that creates hard links.

TODO:
- Add some tests
- Add the versionadded tag

### What issues does this PR fix or reference?

### Previous Behavior
No file.link state was available, although there was an execution function.

### New Behavior
There is a file.link state.

### Tests written?
Not yet

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-09-07 13:42 UTC, rallytime commented on salt/modules/file.py
> +    except (OSError, IOError) as e:
I know you said you still have some work to do here, but right off the bat, can you change these `e` references to something like `err` or `error`? We like to have 3-letter variables. See [here](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#variables) for more information.

2017-09-07 13:47 UTC, rallytime commented
@aneeshusa There are also some lint errors here, which is causing the tests to fail as well. The name of the broken import is `salt.utils.files`, instead of `file`.

2017-09-15 04:28 UTC, terminalmage requested changes

2017-09-15 04:28 UTC, terminalmage commented on salt/states/file.py
> +    if not os.lexists(target):
This function does not exist, I think you meant `os.path.lexists(target)`

2017-10-25 18:16 UTC, aneeshusa commented
Hi, I'm back at Lyft but we don't have a need for this any more, so going to close this now.

2017-10-25 18:16 UTC, closed without merging