better qemu_static parameter mangle in deboostrap management, tests
saltstack/salt pull request #43390
Opened 2017-09-07 15:07 UTC by aogier

### What does this PR do?
Closes #43387 by managing associated module flag in a more sensible way

### Tests written?

updated existing

2017-09-07 18:02 UTC, rallytime approved these changes

2017-09-07 18:17 UTC, gtmanfred requested changes
You will need to create a new function, but it doesn't matter if the qemu path is readable, only if it is executable.

2017-09-07 18:17 UTC, gtmanfred commented on salt/modules/genesis.py
> +    if static_qemu and not salt.utils.validate.path.is_readable(static_qemu):
shouldn't this be checking if the static_qemu path is executable?

2017-09-07 19:39 UTC, aogier commented
@gtmanfred that's a good point, in fact this entire process will run as root or it will anyway fail creating chroot so yes, let's check only for executable bit thank you

2017-09-08 13:21 UTC, rallytime commented
@aogier It looks like there is a test failing here. Can you take a look?

2017-09-08 14:15 UTC, gtmanfred approved these changes

2017-09-08 19:37 UTC, aogier commented
forgot to mock new method in tests, now it should go fine ! :)

2017-09-08 19:38 UTC, gtmanfred commented
Awesome, thanks!

2017-09-11 13:18 UTC, merged