Add ACL token to Consul module
saltstack/salt pull request #43406
Opened 2017-09-08 02:25 UTC by rtx3

### What does this PR do?
1. Add ACL token to consul module when consul set default ACL rule to…deny.
2. Add node meta to function catalog_register.
3. Fix a bug when function catalog_register return true but actually not registered.

### What issues does this PR fix or reference?
When using consul with ACL requirement

### Tests written?
No
Tested with below conditions: 
consul: 0.9.2
salt: 2017.7.1
function:
catalog_register
catalog_deregister
agent_check_register
agent_check_pass
Not enough time to test all functions, but I believe all functions should work.
Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-09-08 12:15 UTC, vladislavPV commented on salt/modules/consul.py
> -                if item['Value'] != None:
you have to put that back , other way an empty key will cause error

2017-09-11 15:22 UTC, cachedout commented
Hi @rtx3. Thanks for this. There are a number of lint errors, however. Would you mind having a look and fixing them up? Thanks.

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14440/violations/file/salt/modules/consul.py/

2017-09-11 15:39 UTC, garethgreenaway commented
Looks like quite a bit of Lint errors.  Also agree with @vladislavPV 's comments on the empty key changes.  Lastly, adding the new `token` argument to all the functions, usually best practices to add any new arguments to the end to avoid issues with existing calls to those functions.

2017-09-21 10:20 UTC, rtx3 commented
@cachedout Sorry for that, I've fixed my code.
 @garethgreenaway @vladislavPV 
Thanks for the review. I agree with the empty key , my mistake. However, adding a new function with  new arguments may not be the best option. Since all function would call _query to call Consul API, if I added a new _query function in this module would make  a lot of confusion  for others.

2017-09-22 21:50 UTC, garethgreenaway approved these changes

2017-09-25 17:42 UTC, rallytime requested changes
Thanks for this change @rtx3 and welcome!

There are a couple of changes that need to be taken care of before we can get this in, largely around where you're adding the `token` kwarg to various functions. Those references need to be moved to the end of each kwarg list so we can avoid an API change.

Also, with the addition of this option, the documentation also needs to be updated for all of the functions adding the `token` option.

Once those updates are made, we can re-review this. Thank you!

2017-09-25 17:42 UTC, rallytime commented on salt/modules/consul.py
> +def list_(consul_url=None, token=None, key=None, **kwargs):
Can you move the addition of the `token` option after `key`? That way we can avoid an API change for other modules calling out to this function.

2017-09-25 17:42 UTC, rallytime commented on salt/modules/consul.py
> +def get(consul_url=None, key=None, token=None, recurse=False, decode=False, raw=False):
Same comment here. This new kwarg needs to be added to the end of the kwarg list.

2017-09-25 17:42 UTC, rallytime commented on salt/modules/consul.py
> +def put(consul_url=None, token=None, key=None, value=None, **kwargs):
Same comment here.

There are quite a few functions below where the `token` option needs to be moved. Please update this anywhere else in this PR below as well.

2017-09-29 10:41 UTC, cachedout commented
@rtx3 Did you see the above review comments and requests for changes? We would love to get this in if you can come back to it. Thanks.

2017-11-13 19:37 UTC, merged

2018-03-02 12:16 UTC, 1ricardo commented
Hello,

I would like ask @cachedout , what is status of that feature. For me module.consul.put stopped worked, when we implemented the ACL in consul, from security reason.

Best Regards