Bugs/43124 users regex
saltstack/salt pull request #43467
Opened 2017-09-12 20:58 UTC by DmitryKuzmenko

### What does this PR do?
This PR adds missing regex and glob patterns support in `publisher_acl` and `external_auth` for user names.

### What issues does this PR fix or reference?
Fix #43124 

### Previous Behavior
For `publisher_acl` most of the logic was working as expected. The problem was in the master user keys initialization. It was requiring all the items in the `publisher_acl` list to be an existing user despite that it could be a pattern.
For `external_auth` there was no logic testing the user names in this way.

### New Behavior
For `publisher_acl` don't fail if an entry isn't an existing user. Check all the existing users for the patterns in the list.
For `external_auth` match user name to the list items considering the items are patterns, not the exact matches.

### Tests written?
No

2017-09-13 16:36 UTC, cachedout requested changes
@DmitryKuzmenko It appears that a number of tests are failing here. Could you please take a look? Thanks.

2017-09-15 15:01 UTC, DmitryKuzmenko commented
re-run ubuntu

2017-09-17 17:26 UTC, KumarRajnish commented
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

From: Dmitry Kuzmenko [mailto:notifications@github.com]
Sent: Friday, September 15, 2017 8:01 AM
To: saltstack/salt <salt@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [saltstack/salt] Bugs/43124 users regex (#43467)


re-run ubuntu

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/saltstack/salt/pull/43467#issuecomment-329808083>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHusM9SsTnNr7sNrNj-ptkaxa_F20xaGks5sipFFgaJpZM4PVPZV>.

2017-09-22 19:20 UTC, cachedout approved these changes

2017-09-22 19:21 UTC, merged