disable modify yaml constructor
saltstack/salt pull request #43557
Opened 2017-09-16 10:09 UTC by clan

which will modify the default behavior of yaml load.

Foe example, for following example (t.sls), it will cause the difference
between the content of file testa and testb, but it should be identical!

$ cat t
{%- load_yaml as vars %}
toaddr:
  - test@test.com
{%- endload -%}
{{ vars.toaddr }}
$ cat t.sls
/tmp/testa:
  file.managed:
    - source: salt://t
    - user: root
    - group: root
    - mode: "0755"
    - template: jinja

sys-power/acpid:
  pkg.installed:
    - refresh: False

/tmp/testb:
  file.managed:
    - source: salt://t
    - user: root
    - group: root
    - mode: "0755"
    - template: jinja
$ touch /tmp/test{a,b}
$ salt-call state.sls t
local:
----------
          ID: /tmp/testa
    Function: file.managed
      Result: None
     Comment: The file /tmp/testa is set to be changed
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1 @@
                  +['test@test.com']
----------
          ID: /tmp/testb
    Function: file.managed
      Result: None
     Comment: The file /tmp/testb is set to be changed
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1 @@
                  +[u'test@test.com']

2017-09-16 10:12 UTC, clan commented
We don't use heat state/module, so I don't know will this break any function.
Maybe the commiter of heat module can provide better solution. Anyway, it's best to do not change the default behavior of a widely used module (yaml in this case).

2017-09-18 17:15 UTC, cachedout commented
@homolkad Can you comment on this at all?

2017-09-19 07:55 UTC, homolkad commented
Yaml constructor change has been used as "Language-Independen string", but I think it would be better this change are removed.
@clan has right, it's better to do not changed the default behavior of a widely used module. 
We will rewritted our template.yaml for this chtange.

2017-09-19 15:18 UTC, clan commented
@homolkad cool, so what should we do next for this pr?

2017-09-19 15:23 UTC, homolkad commented
@clan for me is this pr correct and acceptable

2017-09-20 14:46 UTC, clan commented
@homolkad maybe you need to approve this pr before it can be merged, thanks.

2017-09-20 16:05 UTC, cachedout requested changes

2017-09-20 16:05 UTC, cachedout commented on salt/modules/heat.py
> +# YamlLoader.add_constructor(u'tag:yaml.org,2002:str',
We don't like to have dead code in our code base. Instead of commenting these out, please just remove these lines.

2017-09-20 16:05 UTC, cachedout commented on salt/states/heat.py
> +# YamlLoader.add_constructor(u'tag:yaml.org,2002:str',
Same here. Please just remove these lines. Thanks.

2017-09-22 18:28 UTC, cachedout approved these changes

2017-09-23 02:29 UTC, clan commented
updated.

In my opinion, my pr only fix the bug shown in the commit msg. Because I don't have test case for this module, so it's better to remove or rewrite all the code which modify the default yaml behavior by @homolkad .

2017-09-25 14:03 UTC, rallytime approved these changes

2017-09-25 14:03 UTC, merged