VMware vCenter proxy + storage policies states & dependencies
saltstack/salt pull request #43674
Opened 2017-09-21 14:53 UTC by alexbleotu

### What does this PR do?

Added a vCenter specific proxy and the functions required to configure storage policies (previously known as storage profiles) on the vCenter. This requires to connect to a different endpoint called =/pbm= which names the state and utils modules. The execution function is =vsphere=

Examples of the input expected to configure a storage policy can be found in the sysdoc of =salt.states.pbm=.

List of functions:
Proxy:
- all required functions to run the `vcenter` proxy
- some existing functions and tests in the `vsphere` module have been adjusted to support the new proxy

Utils functions
- get_new_service_instance_stub that creates a new service instance stub
- salt.utils.pbm.get_profile_manager
- salt.utils.pbm.get_placement_solver
- salt.utils.pbm.get_capability_definitions
- salt.utils.pbm.get_policies_by_id
- salt.utils.pbm.get_storage_policies
- salt.utils.pbm.create_storage_policy
- salt.utils.pbm.create_storage_policy
- salt.utils.pbm.update_storage_policy
- salt.utils.pbm.get_default_storage_policy_of_datastore
- salt.utils.pbm.assign_default_storage_policy_to_datastore

Execution functions:

- salt.modules.vsphere._get_policy_dict that transforms a policy VMware object into a dict representation
- salt.modules.vsphere.list_storage_policies that retrieves dict representations of storage policies, filtered by name
- salt.modules.vsphere.list_default_vsan_policy that retrieves dict representation of the default storage policies
- salt.modules.vsphere._get_capability_definition_dict that transforms a VMware capability definition into a dict representation
- salt.modules.vsphere.list_capability_definitions that returns dict representations of VMware capability definition
- salt.modules.vsphere._apply_policy_config that applies a storage dict representations values to a object
- salt.modules.vsphere.create_storage_policy
- salt.modules.vsphere.update_storage_policy
- salt.modules.vsphere.list_default_storage_policy_of_datastore that lists the dict representation of the policy assigned by default to a datastore
- salt.modules.vsphere.assign_default_storage_policy_to_datastore

States functions:

- salt.states.pbm.default_vsan_policy_configured state that configures the default storage policy
- salt.states.pbm.storage_policies_configured state that creates/configures storage policies
- salt.states.pbm.default_storage_policy_assigned state that manages default storage policies to datastore assigments

### Tests written?

Yes (for utils functions)

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

2017-09-21 14:54 UTC, alexbleotu commented
The state functions use some shared methods in https://github.com/saltstack/salt/pull/43645 so I that needs to be merged in first

2017-09-22 17:47 UTC, cachedout commented
@alexbleotu I got #43645 in but there are some merge conflicts now. Could you please resolve them? Thanks.

2017-09-22 19:19 UTC, alexbleotu commented
@cachedout rebased and added the pyVmomi incompatibility check

2017-09-26 14:01 UTC, rallytime approved these changes
Very well done!

2017-09-27 09:11 UTC, alexbleotu commented
Can we get this merged in? I really need to get both this PR and https://github.com/saltstack/salt/pull/43751 (afterwards please) merged in today or tomorrow. Thanks!

2017-09-27 13:36 UTC, rallytime commented
re-run py3

2017-09-27 14:58 UTC, cachedout requested changes

2017-09-27 14:58 UTC, cachedout commented on salt/utils/vmware.py
> +import sys
Import is in the comment block.

2017-09-27 14:58 UTC, cachedout commented on salt/utils/vmware.py
> +import ssl
Import is in the comment block

2017-09-27 15:29 UTC, alexbleotu commented on salt/utils/vmware.py
> +import ssl
my bad will take them out

2017-09-27 16:56 UTC, alexbleotu commented on salt/utils/vmware.py
> +import sys
Done

2017-09-27 16:56 UTC, alexbleotu commented on salt/utils/vmware.py
> +import ssl
Done

2017-09-27 16:57 UTC, alexbleotu commented
@cachedout  all done. Is the GPG required now?

2017-09-27 18:54 UTC, rallytime commented
@alexbleotu We're going to be encouraging contributors to sign their commits, but you don't need to do so retroactively.

2017-09-27 18:56 UTC, merged