Ensure salt-cloud with libvirt provider does not write low level errors to stderr
saltstack/salt pull request #43700
Opened 2017-09-22 15:12 UTC by rklaren

### What does this PR do?

Back port of the relevant fixes in:  #43684

- Fix libvirt spamming stderr when errors happen (that are not errors at all, like when checking if a VM is absent/present) libvirt errors are now redirected to salt's logging at debug level.
- Mention Fedora 26 support

### What issues does this PR fix or reference?

None.

### Previous Behavior

When instantiating a new domain some messages from the libvirt library were printed to stderr.

### New Behavior

Libvirt messages are now written to salt debug log.

### Tests written?

No

Question: Is this the right branch to backport to ? Should I also cherry-pick the changes to 2017.7.2 ?

2017-09-22 15:52 UTC, rallytime approved these changes

2017-09-22 17:29 UTC, cachedout requested changes
Can you please fix the lint errors shown here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14897/violations/

2017-09-22 19:01 UTC, rklaren commented
@cachedout the lint problems are fixed now, sorry about that.

Does this also need a port forward to 2017.7.2 ? Or is that 'automatic' at some point?

2017-09-22 19:03 UTC, rallytime commented
@rklaren Thanks for fixing those errors. This particular fix won't be available in 2017.7.2, as we've already started the testing for that branch.

2017-09-22 19:08 UTC, rklaren commented
@rallytime ok, thank you!

2017-09-25 01:47 UTC, cachedout approved these changes

2017-09-25 01:47 UTC, merged