Fix `unit.states.test_archive` for Windows
saltstack/salt pull request #43837
Opened 2017-09-29 18:28 UTC by twangboy

### What does this PR do?

#### test_archive.py
Uses os agnostic paths
Mock `salt.utils.which` for Windows

#### archive.py
Handle urlparse inconsistencies on Windows

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

2017-10-19 19:29 UTC, twangboy commented
Rebased...

2017-10-19 22:57 UTC, cachedout commented
Bump @terminalmage

2017-10-23 15:12 UTC, terminalmage requested changes

2017-10-23 15:12 UTC, terminalmage commented on salt/states/archive.py
> +            urlparsed_scheme.lower() in 'abcdefghijklmnopqrstuvwxyz':
Additionally, this block of code could use a comment explaining that this check is to see if the source is a Windows path.

2017-10-23 15:12 UTC, terminalmage commented on tests/unit/states/test_archive.py
> +        source = os.sep + os.path.join('tmp', 'foo.tar.gz')
Again, the `os.path.join()` usage seems unnecessary here. Does the test fail without it?

2017-10-23 15:12 UTC, terminalmage commented on tests/unit/states/test_archive.py
> +        source = os.sep + os.path.join('tmp', 'foo.tar.gz')
Same as the previous test. Does this one fail on Windows without `os.path.join()`?

2017-10-23 17:40 UTC, twangboy commented
Applied @terminalmage 's changes and rebased

2017-11-09 21:33 UTC, twangboy commented
Rebased...
@terminalmage Could you approve?

2017-11-10 18:32 UTC, terminalmage approved these changes

2017-11-13 19:12 UTC, merged