Fix `unit.states.test_mount` for Windows
saltstack/salt pull request #43843
Opened 2017-09-29 20:07 UTC by twangboy

### What does this PR do?
Use `os.path.realpath` to convert paths
Mock `os.path.exists`

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

2017-10-01 09:14 UTC, cachedout requested changes

2017-10-01 09:14 UTC, cachedout commented on tests/unit/states/test_mount.py
> +                    patch('os.path.exists', MagicMock(return_value=True)):
Why is this being patched? It seems like this changes the behavior of this test. Could you please clarify?

2017-10-19 19:30 UTC, twangboy commented
Rebased...

2017-10-19 20:19 UTC, cachedout approved these changes
Approved. Merge at will.

2017-10-20 14:27 UTC, merged