Bugfix: runners/survey.py Python3 support
saltstack/salt pull request #43878
Opened 2017-10-03 10:10 UTC by netzmacher

### What does this PR do?
Fix Survey Runner for Python 3

### What issues does this PR fix or reference?
none

### Previous Behavior
Error when using Python3:
```
File "/usr/local/lib/python3.6/site-packages/salt/runners/survey.py", line 174, in _get_pool_results
digest = hashlib.sha256(str(minions[minion])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

```

### New Behavior
fixed issue

### Tests written?

No

2017-10-03 15:40 UTC, cachedout requested changes

2017-10-03 15:40 UTC, cachedout commented on salt/runners/survey.py
> +        digest = hashlib.sha256(str(minions[minion]).encode('utf-8')).hexdigest()
We should always be using `__salt_system_encoding__` instead of assuming `utf-8`.

2017-10-05 12:48 UTC, rallytime commented
@netzmacher A small lint fix is needed on this one: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/15323/violations/file/salt/runners/survey.py/

2017-10-05 18:34 UTC, rallytime approved these changes

2017-10-05 18:52 UTC, merged

2017-10-05 18:52 UTC, rallytime commented
Thank you @netzmacher and congratulations on your first salt PR! :)