Fix autosign file permission check [develop]
saltstack/salt pull request #44196
Opened 2017-10-20 04:41 UTC by benediktwerner

See #44175

Accounts for the movements of `salt.util` functions.

2017-10-20 13:33 UTC, rallytime requested changes
@benediktwerner I had a couple of minor grammar fixes. Otherwise this looks good to me.

Thank you for adding these tests!

2017-10-20 13:33 UTC, rallytime commented on conf/master
> +# except for the owner. User permissive_pki_access to allow the group write access.
`User` should be `Use`.

2017-10-20 13:33 UTC, rallytime commented on conf/suse/master
> +# except for the owner. User permissive_pki_access to allow the group write access.
`User` should be `Use`.

2017-10-20 13:33 UTC, rallytime commented on doc/ref/configuration/master.rst
> +have write access, but if salt is running as ``root`` it must be a member of that group.
`salt` should be `Salt`.

2017-10-20 22:59 UTC, benediktwerner commented
Fixed.

2017-10-23 13:37 UTC, rallytime approved these changes

2017-10-31 17:46 UTC, cachedout commented
@benediktwerner Can you please resolve the merge conflict here? Thanks.

2017-10-31 22:16 UTC, benediktwerner commented
Done.

2017-11-13 18:30 UTC, thatch45 approved these changes

2017-11-13 18:34 UTC, merged