Fix `unit.modules.test_win_groupadd` for Windows
saltstack/salt pull request #44254
Opened 2017-10-23 21:23 UTC by twangboy

### What does this PR do?
Properly mocks the pywin32 com objects for the test.
Adds additional tests for the group module on Windows

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

### Commits signed with GPG?
Yes

2017-10-24 09:00 UTC, cachedout requested changes
Lint, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/15932/console

2017-10-24 15:28 UTC, twangboy commented
Fixed lint and rebased...

2017-10-25 01:31 UTC, terminalmage approved these changes

2017-10-25 13:33 UTC, cachedout approved these changes

2017-10-25 13:33 UTC, merged