Add multiple spm integration tests
saltstack/salt pull request #44253
Opened 2017-10-23 21:19 UTC by Ch3LL

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43813
https://github.com/saltstack/salt/issues/43802
https://github.com/saltstack/salt/issues/43639
https://github.com/saltstack/salt/issues/43636
https://github.com/saltstack/salt/issues/43635

Will probably need to be rebased after this is merged: https://github.com/saltstack/salt/pull/44248 will check in the morning

2017-10-24 09:03 UTC, cachedout requested changes
I don't see these tests actually being run in Jenkins unless I'm just missing something. We likely need some adjustments here.

2017-10-24 14:34 UTC, Ch3LL commented
Okay I think I've added them correctly. I will wait for the tests results. If this does  work then its A LOT easier to add a directory to the test runner now which is great!

2017-10-24 16:58 UTC, Ch3LL commented
Okay it looks like they are running now ping @cachedout its ready for review

2017-10-25 13:35 UTC, cachedout approved these changes

2017-10-25 13:36 UTC, merged