Fix handling of zfs datasets and mount points with spaces
saltstack/salt pull request #44402
Opened 2017-11-04 10:07 UTC by 3add3287

### What does this PR do?
Properly quote the names of zfs datasets as well as mount points where necessary to handle cases where the path contains spaces

### What issues does this PR fix or reference?
#44401

### Previous Behavior
When paths for zfs filesystems/datasets or mount points had a space in them, the zfs command would be executed with the wrong arguments and throw an error.

### New Behavior
Dataset names or mount points are now properly quoted so spaces work as they should

### Tests written?
No

### Commits signed with GPG?
No

2017-11-06 16:10 UTC, cachedout requested changes
We need to start by fixing up some lint errors which can be seen here:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16132/violations/file/salt/modules/zfs.py/

2017-11-07 23:23 UTC, rallytime commented
Hi @3add3287 - There is a merge conflict here, as well as some test failures. Can you take a look?

2017-11-08 21:09 UTC, cachedout commented
@sjorge Would you like to have a look at this?

2017-11-08 21:18 UTC, sjorge commented on salt/modules/zfs.py
> +    dataset = [_zfs_quote_escape_path(x) for x in dataset]
This looks a bit odd, does this work when multiple datasets are passed?

2017-11-08 21:25 UTC, sjorge commented
@rallytime yeah this will also need a rebase, as the zfs grains change had changed the virtual function.

This will also effect #44371, if this goes in after this one that one will need a rebase too. If it goes in before it won't as I ready re-based.

Both will need to be in before I start work on #44404 as that will probably be a big change.

2017-11-08 21:27 UTC, sjorge approved these changes

2017-11-10 17:36 UTC, cachedout commented
@3add3287 Can you please rebase this? It has merge conflicts.

2017-11-13 17:52 UTC, cachedout commented
Bump @3add3287. We need the merge conflicts fixed before we can merge this, please.

2017-11-13 18:05 UTC, 3add3287 commented
Traveling, should have a chance to look at it tomorrow evening

2017-11-15 18:22 UTC, 3add3287 commented
Conflict seems easy to solve. Not sure I did it right in terms of git and it's workflow (more used to the likes of svn, perforce or, in the dark ages, cvs...)

2017-11-15 18:23 UTC, sjorge approved these changes

2017-11-16 14:33 UTC, rallytime commented
@3add3287 It now appears that this PR is failing some related tests. Can you take a look?

2017-11-18 06:04 UTC, 3add3287 commented
I'm stuck in git hell and can't seem to get my branch properly updated with the diverging branches and pushing the commit. Spending more time reading git docs didn't help, nor did any the approaches I found via search work.
Anyone got a problem if I close this one and create a new PR ?

2017-11-23 09:54 UTC, 3add3287 commented
ping?

2017-12-05 23:09 UTC, rallytime commented
@3add3287 Ah, sorry I didn't see your question until just now. That is totally fine if you want to create a new PR. Just link it here and close this one out.

2017-12-05 23:10 UTC, rallytime commented
For the record, the tests that are failing are the following:

- unit.modules.test_zfs.ZfsTestCase.test_create_error_missing_dataset
- unit.modules.test_zfs.ZfsTestCase.test_create_error_missing_parent
- unit.modules.test_zfs.ZfsTestCase.test_create_error_no_such_pool
- unit.modules.test_zfs.ZfsTestCase.test_create_error_trailing_slash
- unit.modules.test_zfs.ZfsTestCase.test_create_success
- unit.modules.test_zfs.ZfsTestCase.test_create_success_with_create_parent

2017-12-22 19:28 UTC, rallytime commented
@3add3287 Just a bump on this one. :)

2017-12-26 18:12 UTC, 3add3287 commented
Replaced by PR #45172

2017-12-26 18:12 UTC, closed without merging