Adding additional requisites to state compiler
saltstack/salt pull request #44414
Opened 2017-11-06 17:39 UTC by garethgreenaway

### What does this PR do?
Adding four additional requisites, ``require_any`` ``watch_any`` ``onchanges_any`` ``onfail_any``, to the state compiler.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Previously these requisites did not exist.

### New Behavior
Adding four additional requisites, ``require_any`` ``watch_any`` ``onchanges_any`` ``onfail_any``, to the state compiler.

### Tests written?
Yes

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2017-11-06 17:44 UTC, thatch45 requested changes
This looks good, just need to fix those tabs :)

2017-11-06 17:44 UTC, thatch45 commented on doc/ref/states/requisites.rst
> +	A:
are these tabs?!?!?!?!?

2017-11-06 17:44 UTC, thatch45 commented on doc/ref/states/requisites.rst
> +	myservice:
MOAR tabs

2017-11-06 17:48 UTC, garethgreenaway commented on doc/ref/states/requisites.rst
> +	A:
Well this is awkward 😀

2017-11-06 23:58 UTC, garethgreenaway commented
re-run ubuntu

2017-11-07 06:30 UTC, rallytime requested changes
Cool! And yay for tests!

I have some documentation changes that should be fixed up, though. :)

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +The use of ``require_any`` demands that one of the required state executes before the
`state` --> `states`

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +In this example, the service will be reloaded/restarted if the either of the state
I think this statement could be a bit more clear/specific. How about "In this example, the service will be reloaded/restarted if either of the ``file.managed`` states has a result of ``True`` and has changes."?

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +.. _requisites-onfail:
`_requisites-onfail` --> `_requisites-onfail_any`. (The previous wording is already used in this document.)

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +The ``onfail_any`` requisite is applied in the same way as ``require_any`` as ``watch_any``:
The second `as`  should be `and`.

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +        - onfail:
`onfail` --> `onfail_any` :)

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +
Can you add a sentence here about what the expected outcome of the state run will be, as you've done for the other examples so far?

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +        - onchanges:
`onchanges` --> `onchanges_any`

2017-11-07 06:30 UTC, rallytime commented on doc/ref/states/requisites.rst
> +
Same comment here about adding an example of what the expected state run will be.

2017-11-07 06:31 UTC, rallytime commented
Oh! And these new requisites should be added to the `Oxygen` release notes as well.

2017-11-07 06:33 UTC, garethgreenaway commented
👍 will do another push to the PR tomorrow.

2017-11-09 13:49 UTC, rallytime approved these changes

2017-11-13 17:47 UTC, thatch45 approved these changes

2017-11-13 17:48 UTC, cachedout approved these changes

2017-11-13 19:17 UTC, merged