Use with blocks (or try/finally) to ensure filehandles are closed
saltstack/salt pull request #44442
Opened 2017-11-08 18:37 UTC by terminalmage

This fixes a few sources (or potential sources) of filehandle leaks.

2017-11-08 19:28 UTC, rallytime requested changes

2017-11-08 19:28 UTC, rallytime commented on salt/proxy/dummy.py
> +    with open(FILENAME, 'wb') as pck:
These all need to use the `salt.utils.files.fopen` function instead of Python's `open`.

2017-11-08 20:51 UTC, cachedout approved these changes

2017-11-08 21:47 UTC, rallytime requested changes
@terminalmage There are two comments that need to be resolved. Then we can get this in.

2017-11-08 21:47 UTC, rallytime commented on salt/proxy/dummy.py
> +    with salt.utils.fopen(FILENAME, 'wb') as pck:
This line needs to use the new path `salt.utils.files.fopen` instead of `salt.utils.fopen`.

2017-11-08 21:47 UTC, rallytime commented on salt/proxy/dummy.py
> +        with salt.utils.fopen(FILENAME, 'r') as pck:
Same comment here.

2017-11-08 22:48 UTC, rallytime approved these changes

2017-11-09 19:59 UTC, terminalmage commented
I've also fixed the kubernetes tests that were failing on Python 3.

2017-11-09 21:15 UTC, terminalmage commented
Made one more commit fixing a reference to one of the salt.utils funcs which was moved in develop. This should be GTM pending the results of the tests currently running.

2017-11-10 13:45 UTC, rallytime commented
You rock @terminalmage! Thanks for fixing these.

2017-11-10 13:45 UTC, merged