Fix `unit.modules.test_disk` for Windows
saltstack/salt pull request #44466
Opened 2017-11-09 21:47 UTC by twangboy

### What does this PR do?
Skip `test_fstype` on systems missing `lsblk`

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

### Commits signed with GPG?
Yes

2017-11-10 17:17 UTC, cachedout requested changes
Lint fixes please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16245/violations/file/tests/unit/modules/test_disk.py/

2017-11-10 18:58 UTC, twangboy commented
Rebased...

2017-11-13 17:36 UTC, cachedout commented
Go Go Jenkins!

2017-11-13 23:08 UTC, twangboy commented
Rebased...

2017-12-01 17:26 UTC, twangboy commented
Rebased...

2017-12-01 20:13 UTC, rallytime approved these changes

2017-12-01 22:31 UTC, merged