INFRA-5979 - add list_tables() function to boto_dynamodb exec module
saltstack/salt pull request #44525
Opened 2017-11-14 02:41 UTC by tkwilliams

Just that, nothing more :)

2017-11-17 17:41 UTC, rallytime requested changes
@tkwilliams I have a couple of very picky salt-isms. Otherwise I think this looks good from my perspective.

2017-11-17 17:41 UTC, rallytime commented on salt/modules/boto_dynamodb.py
> +
Can you add a `.. versionadded:: Oxygen` tag here?

2017-11-17 17:41 UTC, rallytime commented on salt/modules/boto_dynamodb.py
> +    CLI example::
It's helpful for our doc output to use:
```
CLI Example:

.. code-block:: bash
```
Instead of `CLIE example::`

Would you mind changing that?

2017-11-17 17:41 UTC, rallytime commented on salt/modules/boto_dynamodb.py
> +        r = conn.list_tables(**args)
I know there are other references to single letter variables in the `boto_` files, but our style guide declares that we should be using variables of at least three letters. Would you mind changing those references in this new function? That way we can at least have this addition on the right track. :)

2017-11-17 19:37 UTC, ryan-lane commented
Like the other function, can you add some error checking here?

2017-11-17 20:13 UTC, tkwilliams commented
@rallytime  1) Certainly.  2) Absolutely.  3) Happily. :)  I also normalized the rest of the docstrings since there was a bit of inconsistency between them.

@ryan-lane  I actually started a major re-write of the entire module, since NONE of the functions do ANY error checking (or handling) of any kind.  It was out of scope from my immediate need though, so I backed off and simply wrote my new function in exactly the style of the rest of the module.

I believe the correct action here would be to open an issue requesting a re-write of this module to implement correct error handling, throttle-retry, and a general standardization on using best practices we've developed since this was written.  In the meantime, I think it's better form to keep the new function consistent with the style of the rest of the module.

2017-11-17 20:18 UTC, tkwilliams commented
@ryan-lane Just opened https://github.com/saltstack/salt/issues/44586 to cover your error handling concerns.

2017-11-17 20:23 UTC, rallytime approved these changes

2017-11-17 22:37 UTC, ryan-lane commented
@tkwilliams It doesn't hurt to add error handling to this one function. We want to encourage folks to do things the preferred way for new things, rather than doing large scale rewrites later. It's fine for a module to be temporarily inconsistent, if the inconsistency is moving towards our long-term goal.

2017-12-05 20:36 UTC, rallytime commented
@tkwilliams I agree with @ryan-lane here. I think it would be better to have some error handling here and then do the larger-scale rewrite later. Once that's done, we can get this in.

2017-12-07 18:12 UTC, tkwilliams commented
I don't have the cycles at the moment, so I'll go ahead and close this PR - don't merge it.

When I have a bit of time to work on https://github.com/saltstack/salt/issues/44586, I'll include this new function as part of it.

2017-12-07 18:12 UTC, closed without merging

2017-12-07 18:55 UTC, rallytime commented
Sounds great. Thank you @tkwilliams, as always. :)