Add masterless state.highstate integration test
saltstack/salt pull request #44629
Opened 2017-11-21 17:35 UTC by Ch3LL

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43539

Might need to be rebased if https://github.com/saltstack/salt/pull/44613 is merged first.

2017-11-22 03:13 UTC, rallytime commented
@Ch3LL There is a related test failure on this. Can you swing by and fix it up?

2017-11-27 20:21 UTC, rallytime requested changes

2017-11-27 20:21 UTC, rallytime commented on tests/support/case.py
> +    def run_call(self, arg_str, local=False, with_retcode=False, catch_stderr=False):
The `local` kwarg addition should go at the end of the list so we don't cause an API error. :)

2017-11-27 20:21 UTC, rallytime commented on tests/support/case.py
> +    def run_call(self, arg_str, local=False, with_retcode=False, catch_stderr=False):
Same comment here.

2017-11-29 15:17 UTC, Ch3LL commented
I rebased this branch with 2017.7 which had the correct changes for moving `local` to the end of the kwarg list on the run_call methods. So the files is now removed and shouldn't be an issue. Here's to the hope that the tests pass :)

2017-11-29 19:04 UTC, rallytime approved these changes

2017-11-29 19:05 UTC, merged