Sort the show_top results for test_state_show_top test
saltstack/salt pull request #44697
Opened 2017-11-27 20:27 UTC by Ch3LL

### What does this PR do?
This test was previously failing sometimes because the order would change. Looking at the debug logs during rendering of show_top I see:

```
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('*', ['test', 'core'])]))])
```

Since that list is not ordered the test just needs to be changed to make sure we sort it ourselves and make sure the expected states in the top file show up.

2017-11-27 21:36 UTC, rallytime approved these changes

2017-11-27 21:36 UTC, rallytime commented
Fixes https://github.com/saltstack/salt-jenkins/issues/571

2017-11-27 23:54 UTC, terminalmage requested changes
This is not the correct fix. The ordering of the `show_top` results are very important, as we have to be able to guarantee declarative ordering in the top file. Sorting in the assert defeats the purpose.

There is a config option called `master_tops_first` which decides the ordering when there are both master_tops and top file matches for a given saltenv. The relevant code is [here](https://github.com/saltstack/salt/blob/2c937dc/salt/state.py#L3289-L3298).

Because `master_tops_first` defaults to `False`, and is not being set to `True` by the test suite, the ordering in the test as it was written a couple weeks ago is incorrect, and the value being returned by the test suite is correct.

Therefore, the correct fix would be to reverse the order of the two items in the list so that the master_tops matches come second instead of first:

```python
self.assertEqual(ret, {u'base': [u'core', u'master_tops_test']})
```

2017-11-28 00:07 UTC, terminalmage requested changes
.

2017-11-28 00:08 UTC, terminalmage commented
Oh thank you github, for 500 erroring and making me rewrite my review, only to find out that my original review went through 😠 .

2017-11-28 00:15 UTC, terminalmage commented
Actually, the plot thickens, it seems that `master_tops_first` is new to develop so the ordering was likely correct for 2017.7 and not correct in develop.

2017-11-28 00:18 UTC, rallytime commented
Interesting...It is failing consistently on the `develop` branch, likely because of the info from @terminalmage. I don't remember if I have seen it fail on 2017.7. If I have, it's been inconsistent (and might be one of those errors that shows up in Python 3 specifically.)

2017-11-28 00:25 UTC, terminalmage commented
Yeah, we're doing a set union in 2017.7, and `master_tops_first` is new in develop.

The test in 2017.7 is therefore correct, and we just need to update the test in develop to reverse the order there.

Here's the logic from 2017.7: https://github.com/saltstack/salt/blob/f6313a1/salt/state.py#L3159-L3165

While here's the logic in develop: https://github.com/saltstack/salt/blob/2c937dc/salt/state.py#L3289-L3298

The set union is producing the ordering as seen in this test in 2017.7 (where @rallytime confirms it is not currently failing). 

```python
>>> list(set(['master_tops_test']).union(['core']))
['master_tops_test', 'core']
```

So for 2017.7, this ordering is considered "correct", even though it is not the behavior we want. I added `master_tops_first` in 63823f3 specifically to address the unpredictability of the ordering caused by a set union, but we tend not to make changes to things that effect the state compiler in a point release, hence the fix being made against develop.

2017-11-28 00:33 UTC, terminalmage commented
@rallytime just pointed out that this is failing on PY3, which is likely due to changes in hashing. Therefore, to get this to pass in 2017.7 for both PY2 and PY3, we need to be testing the results of a set union:

```python
self.assertEqual(ret, {u'base': list(set([u'master_tops_test']).union([u'core']))})
```

Sorry for the comment-storm here. We just need to make the above change in 2017.7, and then make a separate fix in develop.

2017-11-28 00:36 UTC, terminalmage commented
Yep, definitely caused by hashing differences affecting set order:

```bash
% python2 -c "print(list(set(['master_tops_test']).union(['core'])))"
['master_tops_test', 'core']
% python3 -c "print(list(set(['master_tops_test']).union(['core'])))"
['core', 'master_tops_test']
```

2017-11-28 00:54 UTC, terminalmage commented
I've opened https://github.com/saltstack/salt/pull/44703 to fix this in develop, @rallytime will just need to make sure that the HEAD side of the merge conflict is kept once the 2017.7 fix is merged forward.

2017-11-28 15:58 UTC, Ch3LL commented
@terminalmage Thanks for the review and the thorough explanation :) 

I went ahead and changed it to assert on a union set. :)

2017-11-28 18:32 UTC, rallytime commented
Go Go Jenkins!

2017-11-28 20:35 UTC, merged