Implements #9183
saltstack/salt pull request #44723
Opened 2017-11-28 22:47 UTC by blhsing

Support glob pattern in file.absent state as requested in issue #9183.

Currently file.absent can only remove one specific file or directory at a time. This PR will enable file.absent to remove all files matching a given glob pattern.

The way I implemented it is with a decorator that wraps any existing function in states/file.py and makes it accept an addition keyword argument of resolve_glob such that when it is set True, the decorator will treat the given file name as a glob pattern and calls the wrapped function for each file that matches the glob pattern, and for the returning dict, the result will only be True if every call to the wrapped function returns result as True, and changes, pchanges and comment will all be made into dicts indexed by matching file names, with values set to those of the corresponding values returned by the individual calls to the wrapped function, so that the changes and comments for each matching file can be individually tracked in case they're different. And if resolve_glob is set False or if no file is found, the decorator will simply call the wrapped function directly for its original behavior.

2017-11-28 23:29 UTC, garethgreenaway commented
@blhsing Thanks for the addition!  Can you please add some tests for this new functionality?  Thanks!

2017-11-29 15:04 UTC, damon-atkins commented
You need to add u infront of every string or add
`from __future__ import unicode_literals` or `from __future__ import absolute_import, unicode_literals`

So that all strings are Unicode.

2017-12-03 23:28 UTC, terminalmage requested changes

2017-12-03 23:28 UTC, terminalmage commented on salt/states/file.py
> +from glob import iglob
Please just import `glob` here and change references to `glob.iglob()`. You don't anything in terms of performance or memory by importing a single function, and it also has the side-effect of getting picked up by Sphinx when we publish the docs.

2017-12-03 23:28 UTC, terminalmage commented
You can disregard the comment from @damon-atkins, we are not yet enforcing this.

2017-12-22 19:21 UTC, rallytime commented
Hi @blhsing - Just checking in here to see if you saw our comments above.

2018-02-08 15:32 UTC, rallytime commented
@blhsing bump

2018-03-13 15:48 UTC, rallytime commented
Since we haven't heard back here, I am going to close this PR. We can of course re-open in when you're ready to make the changes requested above. Or you can file a new PR. Thanks!

2018-03-13 15:48 UTC, closed without merging