Fix auto login support for OSX
saltstack/salt pull request #44748
Opened 2017-11-29 21:08 UTC by twangboy

### What does this PR do?
Fixes an issue with `user.enable_auto_login` and `user.disable_auto_login`. There was a step missing in that we needed create/modify the /etc/kcpassword file when we enable autologin. The file also needs to be removed when autologin is disabled.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44721

### Previous Behavior
The module would make the appropriate plist entry, but autologin did not work.

### New Behavior
`/etc/kcpassword` is now created when autologin is enabled and deleted when autologin is disabled.

### Tests written?
No

### Commits signed with GPG?
Yes

2017-11-30 18:23 UTC, cachedout reviewed
What is the justification for having no tests here? This seems like something that is certain to break as Apple potentially changes the format of this file or new distributions.

2017-11-30 18:23 UTC, gtmanfred approved these changes
tested this on the dev imac and it works

2017-11-30 18:23 UTC, gtmanfred commented on salt/modules/mac_user.py
> +    password = [ord(x) for x in list(password)]
`password = list(map(ord, password))`

2017-12-01 21:43 UTC, twangboy commented
Rebased...

2017-12-04 17:21 UTC, rallytime requested changes
I have a couple of small changes, plus there is some lint. I agree that some autmated tests should be written here.

2017-12-06 20:29 UTC, rallytime approved these changes

2017-12-06 20:30 UTC, rallytime commented
re-run py2

2017-12-07 14:22 UTC, merged