Handle unicode values
saltstack/salt pull request #44754
Opened 2017-11-29 23:05 UTC by twangboy

### What does this PR do?
Fixes issue with unicode values in Py3. There may be a better cross-platform way to do this. This is the only thing I could get to work.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44687

### Previous Behavior
inet_pton function would fail with str has no decode

### New Behavior
inet_pton function works on Py2 and Py3

### Tests written?
N/A

### Commits signed with GPG?
Yes

2017-11-30 17:04 UTC, cachedout requested changes
I don't think this is correct. We don't need to encode it just so we can decode it again. IMHO, we need to detect if this is a `str` to begin with and handle it appropriately.

2017-12-04 21:04 UTC, twangboy commented
Rebased...

2017-12-08 00:55 UTC, twangboy commented
Changes @cachedout suggested have been made

2017-12-11 18:07 UTC, terminalmage approved these changes

2017-12-11 18:15 UTC, cachedout approved these changes

2017-12-12 14:04 UTC, merged