Example yaml of influxdb_user state
saltstack/salt pull request #44788
Opened 2017-12-01 19:37 UTC by kris-anderson

### What does this PR do?
Adds an example yaml code snippet to the documentation for the influxdb_user state

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44773

2017-12-01 20:23 UTC, rallytime approved these changes
Thanks @kris-anderson and welcome! 🎉

2017-12-03 23:14 UTC, terminalmage commented on salt/states/influxdb_user.py
> +            foo_db: read
YAML indentation should be 2 spaces.

2017-12-03 23:15 UTC, terminalmage requested changes

2017-12-03 23:15 UTC, terminalmage commented on salt/states/influxdb_user.py
> +            foo_db: read
YAML indentation should be 2 spaces.

2017-12-04 14:28 UTC, merged