Scheduler tests
saltstack/salt pull request #44823
Opened 2017-12-04 21:08 UTC by garethgreenaway

### What does this PR do?
Adding Scheduler tests some initial integration tests for the new post pone & skip functionality.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Tests did not exist.

### New Behavior
Adding integration tests.

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2017-12-04 22:28 UTC, thatch45 requested changes
That docstring is the only thing I see so far.

2017-12-04 22:29 UTC, garethgreenaway commented on salt/utils/schedule.py
> +        Disable a job in the scheduler. Ignores jobs from pillar
Yes.  Yes we do.

2017-12-04 23:40 UTC, thatch45 approved these changes

2017-12-05 18:28 UTC, garethgreenaway commented
re-run ubuntu

2017-12-05 19:00 UTC, rallytime commented
re-run py2

2017-12-05 23:16 UTC, rallytime commented
re-run centos

2017-12-05 23:31 UTC, rallytime commented
Heh. I was just testing the new command trigger for the centos tests. But it looks like it didn't work. The test failures on centos are not related to this change.

2017-12-06 19:47 UTC, cachedout requested changes
This is not the correct location for new tests. Note that they did not get picked up by the test runner. I suggest they get moved to a new directory inside the integration test suite. Either @rallytime or @Ch3LL can help you with details here.

2017-12-07 15:02 UTC, rallytime commented
Ah, good catch @cachedout. I just checked and the new changes are running the tests. Thanks for updating this @garethgreenaway.

2017-12-07 15:03 UTC, rallytime approved these changes

2017-12-07 16:40 UTC, garethgreenaway commented
re-run centos

2017-12-08 22:15 UTC, rallytime commented
Go Go Jenkins!

2017-12-12 16:57 UTC, cachedout approved these changes

2017-12-12 18:37 UTC, cachedout commented
Go Go Jenkins!

2017-12-12 19:25 UTC, garethgreenaway commented
```
 ✘ gareth@blackoil  ~/code/salt/salt/utils   scheduler_tests  sudo python /home/gareth/code/salt/tests/runtests.py --scheduler 
[sudo] password for gareth: 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.14 (default, Sep 17 2017, 18:50:44) [GCC 7.2.0]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/gareth/code/salt
 * Test suite is running under PID 19817
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Setting up Salt daemons to execute tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Starting salt-master ... STARTED!                                                                                                                                                                                                                                            
 * Starting salt-minion ... STARTED!                                                                                                                                                                                                                                            
 * Starting sub salt-minion ... STARTED!                                                                                                                                                                                                                                        
 * Starting syndic salt-master ... STARTED!                                                                                                                                                                                                                                     
 * Starting salt-syndic ... STARTED!                                                                                                                                                                                                                                            
================================================================================================================================================================================================================================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting Scheduler Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.....
----------------------------------------------------------------------
Ran 5 tests in 2.746s

OK

============================================================================================================================  Overall Tests Report  ============================================================================================================================
***  No Problems Found While Running Tests  ************************************************************************************************************************************************************************************************************************************
================================================================================================================================================================================================================================================================================
OK (total=5, skipped=0, passed=5, failures=0, errors=0) 
============================================================================================================================  Overall Tests Report  ============================================================================================================================
 gareth@blackoil  ~/code/salt/salt/utils   scheduler_tests  
```

2017-12-12 19:31 UTC, garethgreenaway commented
```
 gareth@blackoil  ~/code/salt   scheduler_tests  sudo python3 /home/gareth/code/salt/tests/runtests.py --scheduler
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 3.6.3 (default, Oct 3 2017, 21:16:13) [GCC 7.2.0]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/gareth/code/salt
 * Test suite is running under PID 24195
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Setting up Salt daemons to execute tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Starting salt-master ... STARTED!                                                                                                                                                                                                                                            
 * Starting salt-minion ... STARTED!                                                                                                                                                                                                                                            
 * Starting sub salt-minion ... STARTED!                                                                                                                                                                                                                                        
 * Starting syndic salt-master ... STARTED!                                                                                                                                                                                                                                     
 * Starting salt-syndic ... STARTED!                                                                                                                                                                                                                                            
================================================================================================================================================================================================================================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting Scheduler Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.....
----------------------------------------------------------------------
Ran 5 tests in 2.164s

OK

============================================================================================================================  Overall Tests Report  ============================================================================================================================
***  No Problems Found While Running Tests  ************************************************************************************************************************************************************************************************************************************
================================================================================================================================================================================================================================================================================
OK (total=5, skipped=0, passed=5, failures=0, errors=0) 
============================================================================================================================  Overall Tests Report  ============================================================================================================================
 gareth@blackoil  ~/code/salt   scheduler_tests  
```

2017-12-12 22:05 UTC, merged