status.cpustats: add OpenBSD support
saltstack/salt pull request #44915
Opened 2017-12-11 11:00 UTC by jasperla

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior

```
salt# salt \* status.cpustats
salt.localdomain:
    This method is unsupported on the current operating system!
```

### New Behavior

```
salt# salt \* status.cpustats
salt.localdomain:
    ----------
    0:
        ----------
        Idle:
            98.0%
        Interrupt:
            0.0%
        Nice:
            0.0%
        System:
            2.0%
        User:
            0.0%
```

### Tests written?

No

### Commits signed with GPG?

Yes

Please cherry-pick this to the `2017.7` branch too.

2017-12-11 15:06 UTC, rallytime requested changes

2017-12-11 15:06 UTC, rallytime commented on salt/modules/status.py
> +    .. versionchanged:: 2017.7.3
This should be `Oxygen`.

2017-12-11 15:27 UTC, jasperla commented on salt/modules/status.py
> +    .. versionchanged:: 2017.7.3
Fixed :)

2017-12-12 14:40 UTC, jasperla commented
This should be good to go I think?

2017-12-12 21:46 UTC, garethgreenaway approved these changes

2017-12-12 21:48 UTC, garethgreenaway commented
@jasperla Code looks great.  Could we get some tests added to the PR?

2017-12-13 13:01 UTC, jasperla commented
@garethgreenaway The tests should be good to go; the Jenkins failures appear to be unrelated to my change.

2017-12-13 16:40 UTC, garethgreenaway commented
@jasperla :+1: Awesome.  Thanks!

2017-12-13 17:23 UTC, rallytime commented
re-run py2

2017-12-13 19:22 UTC, jasperla commented
I don't know what happened there, but now the newly added tests actually pass.

2017-12-13 22:17 UTC, rallytime commented
Thanks @jasperla! We've been having some trouble with our tests today. But I have verified that your test is running. Thank you!

2017-12-13 22:17 UTC, rallytime approved these changes

2017-12-13 22:17 UTC, merged

2017-12-14 07:01 UTC, jasperla commented
Thanks @rallytime !