boto_route53 return true after PENDING status #44947
saltstack/salt pull request #44949
Opened 2017-12-12 19:27 UTC by adminericjacobs

### What does this PR do?
have boto_route53.add_record return after successful creating instead of waiting for record to sync across all DNS servers (which takes around 40 seconds).

### What issues does this PR fix or reference?
#44947

### Tests written?

No

### Commits signed with GPG?

No

2017-12-12 19:29 UTC, ryan-lane commented
🔒 

There's an arg you can pass to disable wait for sync, I believe. Some folks want to wait to make sure things are propogated, so it would be good to keep this working.

2017-12-12 20:41 UTC, rallytime requested changes
@adminericjacobs I agree with @ryan-lane that we should allow this functionality to remain.

However, is there a documentation change that might make setting `wait_for_sync=False` easier to find?

2017-12-12 22:33 UTC, ryan-lane commented
I think it's in the state module documentation. Do we document execution module arguments the same way as state module documents? If so, we can just doc the args there.

2017-12-12 22:42 UTC, tkwilliams commented
Agreed, this wait functionality is extremely useful.  The fact that @adminericjacobs couldn't determine from the docs that passing false would do what he needed, without a code change, definitely points to a lack in the docs.  This is one of the oldest boto modules and the docstrings are minimal.  I'll take some of the blame, since I updated the whole `wait_for_sync` logic to accept an int value in addition to simple boolean, and never updated the docs to mention it.  Feel free to open a ticket and assign to me to add the needed docstrings :-/  My bad.

2017-12-12 22:44 UTC, tkwilliams commented
@ryan-lane  I tend to document them, prolly because I USE exec modules more than your team does, so I treat them more as first class citizens alongside the state modules :)

2017-12-15 00:45 UTC, tkwilliams commented
Wow, soooooo, I TOTALLY missed commit c1f5dd7a7b7ddadf91e7742b35b998c687fba55e.  I can't say strongly enough how much I disagree with this changeset.

Specifically, the logic of retrying on API rate limiting is UTTERLY ORTHOGONAL to that of retrying on ALL errors.  The VAST MAJORITY of errors are permanent failure states which NO NUMBER of retries will cause to succeed, while conversely API throttling "errors" are very much temporary failures of the "please retry after a short wait" kind.

Handling these wildly different cases in one except clause, with no variance in that handling - other than a log.debug() statement - is a very very very very very poorly thought out code change.  It will end up causing salt runs to hang for long timeouts before reporting back permanent errors which should not have retried even once, much less `error_retries` times...

Anyone remember the difference between EX_TEMPFAIL (75) and EX_USAGE (64).  No number of retries is gonna convince sendmail you haven't used bad options when you have.  There are a lot more permanent failure states than transient, and treating them the same is bad form, and unfriendly to end-users.

2017-12-22 19:09 UTC, rallytime commented
Since we want to leave this functionality as-is, and this should be a documentation change intstead, I am closing this PR. I have created Issue #45143 to track this effort.

2017-12-22 19:09 UTC, closed without merging