ProfitBricks Cloud API v4 support
saltstack/salt pull request #44987
Opened 2017-12-14 07:26 UTC by edevenport

### What does this PR do?

Updates to support the ProfitBricks Cloud API v4:

* Support for the image aliases.
* Adding new location.

Expanding ProfitBricks cloud provider for a salt-cloud tool to support more commands:

* `list-images`
* `list-locations`
* `create_datacenter`
* Extended configuration with a `delete_volume` option.

Bug fixes:
* Server `vmstate` vs `state` response.

Documentation and test updates.

### Tests written?

Yes

### Commits signed with GPG?

No

2017-12-15 17:38 UTC, rallytime commented
@tonybaloney Can you review this when you get a moment?

2017-12-15 22:16 UTC, gtmanfred commented
What are the reasons we are forcing an upgrade to api v4.  Is it still possible to use api v3, or have they shut it down completely?

Can we not manage both side by side based on which version of the library is installed?

2017-12-16 00:39 UTC, edevenport commented
@gtmanfred - The ProfitBricks Cloud API v4 implements the much needed `image_alias` feature. Prior to v4, the `image` name or UUID was required which both change monthly for many ProfitBricks supplied images. This means the cloud profile can become invalid each month which can cause confusion for users.

Also, while the v3 API is still available, prior versions are not. It's not known when the v3 API will be deprecated. Forcing the currently supported v4 API will prevent this from becoming an issue.

2017-12-18 14:19 UTC, gtmanfred commented
If it is still available i would rather not force it.

This is the same thing we did with rackspace, we supported their v1 api until they totally deprecated it, and ripped it out then.

2017-12-22 02:27 UTC, denza commented
@gtmanfred We added compatibility check for the SDKs where the Profitbricks API 3 is used, like you suggested. This way a user will be informed about possible compatibility problem of a SDK he use. Could you please do a review.

2017-12-22 02:55 UTC, gtmanfred requested changes
I left a few stylistic comments, other than that, it looks good! Thanks for making this compatible with the older version!

2017-12-22 03:26 UTC, denza commented
@gtmanfred  Sorry about that. Now we should be good to go.

2017-12-22 03:28 UTC, gtmanfred approved these changes

2017-12-22 15:01 UTC, rallytime commented
Thank you @edevenport! There are a handful of lint violations here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17626/violations/file/salt/cloud/clouds/profitbricks.py/

Can you fix those? This also has a merge conflict as well. Can you resolve that as well?

2017-12-25 11:28 UTC, denza commented
@rallytime violations are fixed. Conflict is resolved.

2017-12-27 14:26 UTC, rallytime commented on doc/topics/cloud/profitbricks.rst
> +For more information concerning cloud profiles, see :doc:`here
Is there a reason you changed this reference from using `ref` to `doc`? We need to use `ref` here as using `doc` should no longer be done. This is failing the following test: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/18095/testReport/junit/unit.test_doc/DocTestCase/test_check_for_doc_inline_markup/.

2017-12-28 23:01 UTC, denza commented
@rallytime I made a fix you proposed for the test. Could you please review?

2018-01-08 21:39 UTC, rallytime approved these changes

2018-01-09 20:03 UTC, merged