priority for minion_blackout_whitelist by grains
saltstack/salt pull request #45108
Opened 2017-12-20 14:33 UTC by pimiento

### What does this PR do?
For a purpose to make blackout_mode managed by minion not by master, I need that pillar config for `minion_blackout_whitelist` couldn't manage the same option on minion. So I changed `elif` to `if`, so I **also**  check grains.

### Previous Behavior
Master can add option `minion_blackout` for given minion in a **pillar** data, so the minion.py will check `minion_blackout_whitelist` from a **pillar** dict and won't check in **grains**

### New Behavior
Even if it is the `minion_blackout` options in a **pillar**, minion.py will check these options in **grains** then..

### Tests written?

No

### Commits signed with GPG?

No

2017-12-25 08:59 UTC, DmitryKuzmenko requested changes
The change described and implemented here looks reasonable for me. Just disagree with the comment.

2017-12-25 08:59 UTC, DmitryKuzmenko commented on salt/minion.py
> +                # minion_blackout_whitelist by grains has higher priority than by pillar
I disagree with this comment. By the code now there is no any priority, if blackout mode is enabled and function isn't whitelisted it's blocked.

2017-12-25 11:14 UTC, DmitryKuzmenko approved these changes
I'm ok here now. Thank you @pimiento .

2017-12-25 11:18 UTC, pimiento commented
Ok, I've changed comment

2018-01-02 14:13 UTC, terminalmage approved these changes

2018-01-02 14:57 UTC, merged

2019-04-04 15:39 UTC, max-arnold commented
@pimiento Could you please document this feature here: https://docs.saltstack.com/en/latest/topics/blackout/ ?

You can submit the PR against 2019.2 branch.