fix adding parameters to http.query from sdb yaml
saltstack/salt pull request #45116
Opened 2017-12-20 22:52 UTC by arif-ali

### What does this PR do?

Fixes an issue, where, if you specify the sdb rest, it will not pick up parameters such as username, password, etc, from what salt.utils.http.query() can accept 

### What issues does this PR fix or reference?

There is no issue open, as I was working on a live system, and created the PE

### Previous Behavior

While specifying the username and password in the sdb config file, it would not use these values to authenticate against the REST API

### New Behavior

Now that these variables are being picked up, the auth works, and we are able to enumerate all the info from the REST API 

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2017-12-21 14:23 UTC, rallytime commented
re-run lint

2017-12-21 14:59 UTC, gtmanfred approved these changes

2017-12-21 14:59 UTC, gtmanfred commented on salt/sdb/rest.py
> +      if item != 'backend' and item != 'url':
`if item not in ('backend', 'url'):`

2017-12-21 14:59 UTC, gtmanfred commented
I would also like @techhat to take a look

2017-12-21 15:00 UTC, gtmanfred requested changes

2017-12-21 15:00 UTC, gtmanfred commented on salt/sdb/rest.py
> +      if item != 'backend' and item != 'url':
actually, i would like it to be changed to this.

2017-12-21 15:59 UTC, techhat approved these changes

2017-12-21 16:09 UTC, rallytime commented
@arif-ali Can you fix these lint errors? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17584/violations/file/salt/sdb/rest.py/

2017-12-22 17:54 UTC, merged

2018-04-04 11:52 UTC, arif-ali commented
can we backport this to 2017.7 please. I made these changes to my local system running 2017.7, but now we upogradded, the changes were overwritten, and forgot about this patch.

2018-04-04 13:42 UTC, gtmanfred commented
I have marked it to be backported.  In the future, if it is broken in older releases, please open the PR against that release branch so that we can merge forward.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#merge-forward-process

Thanks,
Daniel

2018-04-04 13:45 UTC, arif-ali commented
Thanks, I'll remember that for next time