Stop(deallocate) and Start vm actions
saltstack/salt pull request #45119
Opened 2017-12-21 03:23 UTC by sumeetisp

Adding missing functionality for starting and stopping vm

### What does this PR do?
This PR adds functionality for stopping(deallocate) and starting azure virtual machines.

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2017-12-21 14:16 UTC, rallytime commented
Hi @sumeetisp! Thank you for this addition. Can you fix the lint errors https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17562/violations/file/salt/cloud/clouds/azurearm.py/?

2017-12-22 08:00 UTC, sumeetisp commented
Done

2017-12-22 17:47 UTC, rallytime requested changes
I had a couple of questions and suggestions here. Otherwise this looks good.

2017-12-22 17:47 UTC, rallytime commented on salt/cloud/clouds/azurearm.py
> +
Can you add a `.. versionadded:: Fluorine` here?

2017-12-22 17:47 UTC, rallytime commented on salt/cloud/clouds/azurearm.py
> +
This also need the same version added tag.

2017-12-22 17:47 UTC, rallytime commented on salt/cloud/clouds/azurearm.py
> +                resource_group = group
What is the purpose of setting this resource_group variable? It looks like it's not being used anywhere later.

2017-12-22 17:47 UTC, rallytime commented on salt/cloud/clouds/azurearm.py
> +                resource_group = group
Same question about setting the resource group here as above.

2017-12-23 07:18 UTC, sumeetisp commented
Hi Nicole,

I will be reviewing the code after getting back from vacation on 1st Jan.

Thanks,
Sumeet Salvankar

On 22-Dec-2017 23:17, "Nicole Thomas" <notifications@github.com> wrote:

*@rallytime* requested changes on this pull request.

I had a couple of questions and suggestions here. Otherwise this looks good.
------------------------------

In salt/cloud/clouds/azurearm.py
<https://github.com/saltstack/salt/pull/45119#discussion_r158530961>:

> @@ -1834,3 +1834,63 @@ def delete_blob(call=None, kwargs=None):  # pylint: disable=unused-argument

     storageservice.delete_blob(kwargs['container'], kwargs['blob'])
     return True
+
+
+def stop(name, resource_group=None, call=None):
+    '''
+    Stop a VM
+

Can you add a .. versionadded:: Fluorine here?
------------------------------

In salt/cloud/clouds/azurearm.py
<https://github.com/saltstack/salt/pull/45119#discussion_r158531114>:

> +            try:
+                instance_stop =
compconn.virtual_machines.deallocate(group, name)
+                instance_stop.wait()
+                resource_group = group
+            except CloudError:
+                continue
+    else:
+        instance_stop = compconn.virtual_machines.stop(resource_group, name)
+        instance_stop.wait()
+    return instance_stop
+
+
+def start(name, resource_group=None, call=None):
+    '''
+    Start a VM
+

This also need the same version added tag.
------------------------------

In salt/cloud/clouds/azurearm.py
<https://github.com/saltstack/salt/pull/45119#discussion_r158531258>:

> +    .. code-block:: bash
+
+         salt-cloud -a stop myminion
+    '''
+    if call == 'function':
+        raise SaltCloudSystemExit(
+            'The stop action must be called with -a or --action.'
+        )
+    if not compconn:
+        compconn = get_conn()
+    if resource_group is None:
+        for group in list_resource_groups():
+            try:
+                instance_stop =
compconn.virtual_machines.deallocate(group, name)
+                instance_stop.wait()
+                resource_group = group

What is the purpose of setting this resource_group variable? It looks like
it's not being used anywhere later.
------------------------------

In salt/cloud/clouds/azurearm.py
<https://github.com/saltstack/salt/pull/45119#discussion_r158531323>:

> +    .. code-block:: bash
+
+         salt-cloud -a start myminion
+    '''
+    if call == 'function':
+        raise SaltCloudSystemExit(
+            'The start action must be called with -a or --action.'
+        )
+    if not compconn:
+        compconn = get_conn()
+    if resource_group is None:
+        for group in list_resource_groups():
+            try:
+                instance_start = compconn.virtual_machines.start(group, name)
+                instance_start.wait()
+                resource_group = group

Same question about setting the resource group here as above.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/pull/45119#pullrequestreview-85363528>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHg-ExF8X9n3i0lW4m_MG3iy54x_YxzDks5tC-s4gaJpZM4RJTpt>
.

2018-01-02 04:48 UTC, sumeetisp commented
I have made the suggested changes

2018-01-02 14:08 UTC, rallytime approved these changes

2018-01-02 14:09 UTC, rallytime commented
@sumeetisp This looks good, but there's a lint failure: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17815/violations/file/salt/cloud/clouds/azurearm.py/

Once that is fixed up we can get this in. :)

2018-01-03 13:42 UTC, rallytime commented
Go Go Jenkins!

2018-01-03 20:14 UTC, merged