Azure (ARM): Fix GovCloud Support
saltstack/salt pull request #45187
Opened 2017-12-27 23:14 UTC by nicholasmhughes

### What does this PR do?
This PR fixes the ability of the Azure ARM cloud module to communicate with Azure GovCloud endpoints. Some other issues with the cloud module were also fixed, along with general cleanup from linting, etc.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
- Cloud module was unable to hit endpoints for anything other than the Public Cloud.
- Userdata was not able to be passed during instance creation... it silently failed.
- Some of the functions didn't work from the command line (`salt-cloud -f <function>`)

### New Behavior
- Broke out some functionality into a utils module which can also be used by some execution and state modules which are currently being worked.
- Cloud module can now hit endpoints for any Microsoft hosted endpoint (no custom endpoint support for Azure Stack... yet)
- Custom scripts can now be passed via VM extensions. Added some documentation to the main docstring outlining the uses.
- Fixed functions to work from the command line in order to list various resources accessible to the cloud provider configuration.
- Fixed some logic to ensure the cloud module works as expected.
- Rolled in start/stop actions from PR 45119
- Linted the modules to ensure prettyness...

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2017-12-28 15:13 UTC, gtmanfred approved these changes

2017-12-28 18:25 UTC, gtmanfred requested changes
Can you change the name of the option for the public key to `ssh_key_file` so that it matches what is used in our other cloud providers.

Also if you could add a note about it to the getting started doc for azurearm

https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html

Thanks,
Daniel

2017-12-28 18:40 UTC, gtmanfred commented
Actually, sorry, i am wrong, you were right.  it can be ssh_publickeyfile. ssh_key_file should be the private key that is used to match that public key and log into the server.

2017-12-28 18:47 UTC, nicholasmhughes commented
@gtmanfred I was too quick on the draw... Net effect is updated documentation. Is that correct now?

2017-12-28 18:52 UTC, gtmanfred commented
It looks like you just need to add using the `ssh_key_file` as the identity file for the ssh command.

it should be passed to the `bootstrap()` function as [key_filename](https://github.com/saltstack/salt/blob/2017.7/salt/utils/cloud.py#L323)

Thanks,
Daniel

2017-12-28 19:23 UTC, nicholasmhughes commented
@gtmanfred bootstrapping works as expected using the `ssh_keyfile` parameter, which is pulled in via `saltify.py`. I updated to documentation to reflect this... is that acceptable?

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/saltify.py#L383

2017-12-28 19:43 UTC, gtmanfred approved these changes

2017-12-28 19:43 UTC, gtmanfred commented
Yup, that works for me.

Thanks,
Daniel

2018-01-02 16:40 UTC, rallytime commented
re-run lint

2018-01-08 21:33 UTC, rallytime commented
re-run docs

2018-01-08 21:33 UTC, rallytime commented
@techhat Can you review this?

2018-01-18 18:37 UTC, nicholasmhughes commented
@rallytime @techhat Anything I can do to help with testing/acceptance?

2018-01-19 15:24 UTC, rallytime commented
@nicholasmhughes We're still waiting on a review from @techhat. But in the mean time, this PR has a merge conflict in it. Can you fix that and rebase this?

2018-01-19 16:35 UTC, nicholasmhughes commented
@rallytime I think the conflicts should be resolved. Please let me know if there are any other actions.

2018-01-22 21:34 UTC, drawsmcgraw commented
@rallytime @techhat anything more we can do to assist with the testing/merging?I can buy @techhat a coffee if it helps :)

2018-01-25 16:13 UTC, techhat approved these changes
This is a really great set of changes! Thanks @nicholasmhughes!

2018-01-25 16:13 UTC, techhat commented on doc/topics/cloud/azurearm.rst
> -      ssh_password: verybadpass
`ssh_password` should not be removed from the example, since it is still supported. How about another example block for `ssh_publickeyfile`?

2018-01-25 18:04 UTC, nicholasmhughes commented
@techhat is the documentation change in line with what you were thinking?

2018-01-26 16:20 UTC, techhat commented
@nicholasmhughes perfect, thanks!

2018-01-26 16:35 UTC, merged