Compose services
saltstack/salt pull request #45231
Opened 2018-01-02 09:51 UTC by obeleh

### What does this PR do?

Ads functionality to manage docker-compose service definitions as proposed in #44911 

### What issues does this PR fix or reference?

#44911

### New Behavior

the following salt calls:

- dockercompose.service_create
- dockercompose. service_upsert
- dockercompose.service_remove
- dockercompose.service_set_tag

Different in the behaviour with all other salt calls in this module is that this has to do a yaml.dumps because we're modifying content and not modifying strings. I've explicitly stated in the docstrings that this is the case:

`This wil re-write your yaml file. Comments will be lost. Indentation is set to 2 spaces`

### Tests written?

No

### Commits signed with GPG?

Yes

2018-01-02 14:25 UTC, rallytime commented
re-run lint

2018-01-02 16:47 UTC, rallytime commented
re-run lint

2018-01-04 20:35 UTC, terminalmage requested changes
Now that https://github.com/saltstack/salt/pull/45190 has been merged, we should wait for @rallytime to merge that forward into develop, and then this should be rebased so that we use `salt.utils.yaml.dump()` to do the yaml dumping.

2018-02-08 16:09 UTC, terminalmage approved these changes
I'll work on the yaml dumper, we shouldn't be adding that YAML tag in our custom dumper.

2018-02-08 16:09 UTC, terminalmage commented
Oh sorry, I marked this PR as approved but I had a few changes I wanted to see made before merging.

2018-02-08 16:10 UTC, terminalmage requested changes
Accidentally marked as approved.  See my earlier comments for a few changes that should be made.

2018-02-08 20:26 UTC, terminalmage requested changes
It turns out that using a regular dump here uses PyYAML's default dumper. Using our custom safe dumper, that YAML tag should not be present in the dumped output.

2018-02-08 20:26 UTC, terminalmage commented on salt/modules/dockercompose.py
> +        dumped = yaml.dump(content, indent=2, default_flow_style=False)
Please change this to `safe_dump`.

2018-02-08 20:26 UTC, terminalmage commented on salt/modules/dockercompose.py
> +    services[service_name]['image'] = str('{0}:{1}'.format(image, tag))
If you use `safe_dump` above, you can replace this with `'{0}:{1}'.format(image, tag)`.

2018-02-28 20:29 UTC, rallytime commented
@obeleh Can you come back to this PR and address the comments above?

2018-03-01 06:07 UTC, obeleh commented
Sorry for the delay. At the time you asked for the change I was busy with other things. I've tested the change you suggested and it works. Hope everything is fine now :)

2018-03-01 19:28 UTC, rallytime commented
re-run lint

2018-03-03 08:06 UTC, terminalmage approved these changes

2018-03-05 14:55 UTC, rallytime commented
@obeleh There's a very small lint error here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19740/violations/file/salt/modules/dockercompose.py/

Can you fix that?

2018-03-05 21:53 UTC, merged