[2017.7] config gate auth_events
saltstack/salt pull request #45299
Opened 2018-01-05 17:52 UTC by garethgreenaway

### What does this PR do?
Adding some code to config gate whether `auth_events` are sent to the event bus

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Auth events are always sent.

### New Behavior
Adds a new master configuration option to disable sending the auth events.

### Tests written?
Pending

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-01-05 17:54 UTC, thatch45 approved these changes

2018-01-05 17:59 UTC, austinpapp commented on salt/config/__init__.py
> +    # Wheter to fire auth events
s/Wheter/Whether

2018-01-05 18:42 UTC, austinpapp commented
LGTM

2018-01-05 19:53 UTC, rallytime commented
re-run lint

2018-01-05 20:11 UTC, rallytime commented
@garethgreenaway In addition to the `Pending` status of your tests, can you also add some documentation to the master config docs? https://docs.saltstack.com/en/latest/ref/configuration/master.html

2018-01-05 21:22 UTC, gtmanfred commented
re-run py

2018-01-08 21:30 UTC, rallytime requested changes
Just a couple of small comments. Otherwise 👍

2018-01-08 21:30 UTC, rallytime commented on doc/ref/configuration/master.rst
> +.. conf_master:: master_job_cache
This should be `auth_events`

2018-01-08 21:30 UTC, rallytime commented on doc/ref/configuration/master.rst
> +.. versionadded:: 2017.7.0
Should this be `2017.7.3`?

2018-01-09 14:59 UTC, rallytime approved these changes

2018-01-09 15:00 UTC, merged