[oxygen] Updating various utils and related tests for Unicode goodness.
saltstack/salt pull request #45405
Opened 2018-01-12 00:15 UTC by garethgreenaway

### What does this PR do?
Updating various utils and related tests for Unicode goodness

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-01-12 15:59 UTC, rallytime approved these changes

2018-01-12 23:37 UTC, terminalmage requested changes

2018-01-12 23:37 UTC, terminalmage commented on salt/utils/error.py
> +from __future__ import absolute_import, unicode_literals
We should have `print_function` imported as well in all of these files (see [here](https://gist.github.com/terminalmage/7440c8d6e46ed4ee2f69c834d5363512#print_function-and-unicode_literals)).

2018-01-12 23:37 UTC, terminalmage commented on salt/utils/functools.py
> +                                   salt.utils.stringutils.to_str(name),  # future lint: disable=blacklisted-function
`str()` is actually what we want here, `and in fact salt.utils.stringutils.to_str()` will raise an exception if you feed it value that isn't one of the string types.

2018-01-17 16:16 UTC, terminalmage approved these changes

2018-01-18 15:39 UTC, merged