Add Zabbix inventory support
saltstack/salt pull request #45458
Opened 2018-01-16 07:59 UTC by mchugh19

### What does this PR do?
Add Zabbix inventory handling to zabbix execution module
Support Zabbix inventory handling in zabbix_host state

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-01-22 16:24 UTC, rallytime requested changes
Thanks for this @mchugh19!

I have a couple of small comments.

Can you also write some tests for these new functions?

2018-01-22 16:24 UTC, rallytime commented on salt/modules/zabbix.py
> +    .. versionadded:: Oxygen
This should be updated to `Fluorine` as we've completed the feature freeze for `oxygen` already.

2018-01-22 16:24 UTC, rallytime commented on salt/modules/zabbix.py
> +    .. versionadded:: Oxygen
Same comment here.

2018-01-22 16:24 UTC, rallytime commented on salt/modules/zabbix.py
> +def hostinventory_get(hostids, **connection_args):
I think `host_inventory_get` might be a better name here. I think it's easier to read.

2018-01-22 16:24 UTC, rallytime commented on salt/modules/zabbix.py
> +def hostinventory_set(hostid, **connection_args):
`host_inventory_set` on this function is easier to read, IMHO, as well.

2018-01-23 07:42 UTC, mchugh19 commented
I'm having a bit of trouble coming up with the mocking necessary for the _query method. Could anyone guide me, and I'll write up the test cases?

2018-02-04 22:47 UTC, mchugh19 commented
Took another crack at it and got unit tests going. Added tests for the existing user_* and the newly added host_inventory_* methods.

2018-02-08 15:21 UTC, rallytime commented
@mchugh19 There's a lint error here now: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19090/violations/

Looks like there's also a related test failure: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/2092/

2018-02-08 23:02 UTC, mchugh19 commented
Lint output cleaned up. I had an issue running pylint from python2, but just corrected that.

2018-02-08 23:03 UTC, mchugh19 commented
The referenced test failures seem unrelated as they had to do with other testing scripts like vmware.

2018-02-21 08:06 UTC, mchugh19 commented
I think all requested updates have been made. Is there anything still outstanding?

2018-02-21 14:53 UTC, rallytime approved these changes

2018-02-21 14:56 UTC, rallytime commented
@mchugh19 This looks good to me but the tests timed out before I could double check them. I'll keep an eye on this so we can get it in. Thanks!

2018-02-21 19:17 UTC, merged