emit port cli version, variants as separate args
saltstack/salt pull request #45462
Opened 2018-01-16 14:52 UTC by aphor

### What does this PR do?
Changes macports pkg module behavior to conform to macports documentation for single pkg with optional version and variants arguments.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/45413

### Previous Behavior
The module produces a command with a single port name and version (if given), and variants (if given) concatenated as a single positional arg to the "port install" command.

This is incorrect. The command should give version and variants as separate args eg. 
`port install portname @version +variant`
and the current rev, where version kwarg is omitted and variant is given will try to execute\
`port install portname+variant`
which is incorrect.

### New Behavior
give version and variants as separate args eg. 
`port install portname @version +variant`

### Tests written?

No

### Commits signed with GPG?
Yes

2018-01-19 14:52 UTC, KaiSzuttor commented
@aphor have you checked your PR? I just tried and an exception occurred:
```
An exception occurred in this state: Traceback (most recent call last):
                File "xxx/git/salt/salt/state.py", line 1964, in call
                  **cdata['kwargs'])
                File "xxx/git/salt/salt/loader.py", line 1822, in wrapper
                  return f(*args, **kwargs)
                File "xxx/git/salt/salt/states/pkg.py", line 1663, in installed
                  **kwargs)
                File "xxx/git/salt/salt/modules/mac_ports.py", line 330, in install
                  if 'version' in pparams:
              TypeError: argument of type 'NoneType' is not iterable
```

2018-01-22 14:12 UTC, aphor commented
@KaiSzuttor can you provide an example from which I can add a test?

I checked the code with 4 cases, a single port (from the bug example) with all combinations of version and variant given or not.

If you're getting an exception, I think it would be good to first add a test and then fix it.

2018-01-22 16:29 UTC, gtmanfred requested changes

2018-01-22 16:29 UTC, gtmanfred commented on salt/modules/mac_ports.py
> +        if 'version' in pparams:
you should do a `if pparams and 'version' in pparams:`

because it is possible that pparams is a None value.

2018-01-24 00:08 UTC, aphor commented
I think @gtmanfred is probably right, and I'll fix the PR with his suggestion. I'll have to look into setting up a test for the state module which would cover your case @KaiSzuttor.

2018-01-25 04:51 UTC, aphor commented
@gtmanfred I dropped both formulas_array.append() calls into an if block testing for True-ish-ness of pparams. It wasn't exactly the changes you requested, but I think it covers your request, and probably fixes the error @KaiSzuttor got.

2018-01-25 10:21 UTC, KaiSzuttor commented
Just checked, variant is still ignored for the state file.

2018-02-08 16:21 UTC, gtmanfred commented
@aphor did you see @KaiSzuttor last comment about this causing 'variant' to be ignored when passed from a state?

2018-02-08 20:22 UTC, aphor commented
@gtmanfred Yeah, I saw that. I've been sidetracked, but I'll be able to deal with this over the weekend because we're going to get snowed in here in Chicago.

2018-02-08 20:23 UTC, gtmanfred commented
cool, thanks!

On Thu, Feb 8, 2018 at 1:22 PM, Jeremy McMillan <notifications@github.com>
wrote:

> @gtmanfred <https://github.com/gtmanfred> Yeah, I saw that. I've been
> sidetracked, but I'll be able to deal with this over the weekend because
> we're going to get snowed in here in Chicago.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/45462#issuecomment-364236795>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoe5FeSsOhG4eBl_m9FMeUttjbBUAks5tS1eUgaJpZM4Rf5I->
> .
>

2018-02-11 00:21 UTC, aphor commented
@KaiSzuttor @gtmanfred 

The pkg state module's pkg.installed() doesn't support a variant argument, so it makes calls to the mac_ports execution module to install packages without the (optional) variant kwarg.

I looked at adding support for this into the state module, but I think that should be a separate ticket/PR.

I submitted #45967 "pkg state module does not allow specifying variants for macports packages" to address this.

2018-02-12 15:06 UTC, gtmanfred approved these changes

2018-02-13 16:23 UTC, merged