[PY3] Add unicode_literals to pkg/pkgrepo states/modules
saltstack/salt pull request #45531
Opened 2018-01-18 16:56 UTC by terminalmage

2018-01-18 20:13 UTC, cachedout requested changes

2018-01-19 23:42 UTC, terminalmage commented on salt/modules/dpkg.py
> +        for pkg_info in salt.utlils.stringutils.to_unicode(fp_.read()).split(pkg_mrk):
Fixed, thanks

2018-01-21 01:37 UTC, cachedout approved these changes

2018-01-21 10:57 UTC, damon-atkins commented
`[oxygen] Updating Tier 2 modules, states and related tests for Unicode` #45581 cover the same files

2018-01-21 22:52 UTC, merged