utils/files.py match i/o size with rest of salt i/o code
saltstack/salt pull request #45544
Opened 2018-01-19 08:53 UTC by damon-atkins

### What does this PR do?
utils/files.py match i/o size with rest of salt i/o code
match the i/o size on the minion to the same size on the master.

### What issues does this PR fix or reference?

### Previous Behavior
i/o size was the block size of the file system, which is general small, resulting in poor performance.

### New Behavior
The default i/o size is determined by file_buffer_size
file_buffer_size increase on the minion to same as master. 

### Tests written?

No New Tests

### Commits signed with GPG?

No

2018-01-19 12:06 UTC, damon-atkins commented
Go Go Jenkins!

2018-01-19 15:25 UTC, damon-atkins commented
from the doco check.
```
12:07:35 Exception occurred:
12:07:35   File "/var/jenkins/workspace/PR/salt-pr-docs-n/salt/utils/files.py", line 368, in fopen
12:07:35     kwargs['buffering'] = __opts__['file_buffer_size']
12:07:35 NameError: global name '__opts__' is not defined
```
Not sure how to fix it.

2018-01-19 19:03 UTC, terminalmage reviewed
Changes like this to core I/O behavior need to be reviewed by @thatch45, I'm not sure if there is a reason the minion file_buffer_size is specifically what it is.

I'm also not familiar with the docs check, do you know what is causing that @rallytime ?

2018-01-19 19:05 UTC, thatch45 commented
Making them the same for the sake of them being the same is wrong. But if we can see an improvement in performance then I am all for it.

2018-01-20 02:23 UTC, damon-atkins commented
Go Go Jenkins!

2018-01-20 12:33 UTC, damon-atkins commented
Large I/O size increase bandwidth and reduces cpu usage.  However a large buffer for a small file is pointless.

Given __opts___ is not available and it would need to be loaded. Adding to already large  number of times the minion/master configs just to get file_buffer_size did seem like a good idea.  I have decided to head down path, that a function determines the best I/O size based on the existing file size or a size provided by the user.

Two parts to this  have the call to open() use buffering setting.
Improvements on the default buffer size for files of just 8k.

I was surprised to see the master buffering at 1MB. It would be interesting to see the average file size is.

I thought the Jenkins test might be a good benchmark.

2018-01-22 12:36 UTC, damon-atkins commented
Something going on with os.path.isfile(filepath) and _isfile_side_effect KeyError. Not sure what the issues is?
```
12:16:48 ----------------------------------------------------------------------
12:16:48 Traceback (most recent call last):
12:16:48   File "/testing/tests/unit/states/test_archive.py", line 165, in test_tar_gnutar
12:16:48     keep=True)
12:16:48   File "/testing/salt/states/archive.py", line 977, in extracted
12:16:48     existing_cached_source_sum = _read_cached_checksum(cached)
12:16:48   File "/testing/salt/states/archive.py", line 120, in _read_cached_checksum
12:16:48     with salt.utils.files.fopen(checksum_file, 'r') as fp_:
12:16:48   File "/testing/salt/utils/files.py", line 402, in fopen
12:16:48     kwargs['buffering'] = dynamic_buf_size(filename)
12:16:48   File "/testing/salt/utils/files.py", line 78, in dynamic_buf_size
12:16:48     not os.path.isfile(filepath)):
12:16:48   File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
12:16:48     return _mock_self._mock_call(*args, **kwargs)
12:16:48   File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
12:16:48     ret_val = effect(*args, **kwargs)
12:16:48   File "/testing/tests/unit/states/test_archive.py", line 46, in _isfile_side_effect
12:16:48     }[path]
12:16:48 KeyError: u'/tmp/archive_hash/foo.tar.gz.hash'
```

2018-01-23 15:17 UTC, damon-atkins commented
Go Go Jenkins!

2018-01-23 22:11 UTC, rallytime commented
@damon-atkins This looks like a feature addition to me and something that still might need to be discussed about the problem being solved here. Can you move this to develop?

2018-01-27 11:23 UTC, damon-atkins commented
Hi @rallytime where do I find stats on run times for the tests in Jenkins I was thinking the tests themselves might show improvements.

2018-02-07 15:04 UTC, damon-atkins commented
Go Go Jenkins!

2018-02-07 18:56 UTC, rallytime commented
@damon-atkins This needs to be moved to develop, please.

2018-04-10 20:06 UTC, cachedout commented
Since this has been moved to develop, I have rebased it and restarted the tests.

2018-04-11 09:37 UTC, damon-atkins commented
Thanks.    Seems the errors are not related. What I want to see is the time the tests take with and with out the change.  As a bit of a benchmark.

2018-07-06 18:51 UTC, rallytime requested changes
I would rather see a more refined PoC on this rather than just relying on the test results. I don't think that is a very reliable way to demonstrate that this concept is making a noticeable difference.

In addition, the test results above are not showing any noticeable improvement. The tests on develop typically take about 3 hours each to run, depending on many factors. Each of the test results above took a little over 3 hours to run. This is not the way we should be measuring a change like this.

2018-07-27 20:49 UTC, closed without merging