Add unicode_literals to modules, states, tests (I)
saltstack/salt pull request #45549
Opened 2018-01-19 14:16 UTC by rallytime

2018-01-19 19:19 UTC, terminalmage requested changes
Just a few changes to make. For a couple, you will need to import salt.utils.data, and perhaps remove the stringutils import if it is no longer necessary.

2018-01-19 19:19 UTC, terminalmage commented on salt/modules/incron.py
> +            fp_.writelines(salt.utils.stringutils.to_str(lines))
`to_str()` has to operate on strings, not lists. If you want a one-liner that doesn't use a list comprehension, you can open the file using a mode of `wb` and use:

```python
fp_.writelines(salt.utils.data.encode(lines))
```

Just FYI, the `+` in the mode is entirely unnecessary, it opens the file in read-and-write mode and we're not reading from the filehandle at all. It was likely originally written that way by someone who didn't understand what the `+` was for.

2018-01-19 19:19 UTC, terminalmage commented on salt/modules/incron.py
> +        msg = '%s cannot be written. %s does not exist', filename, folder
```python
msg = '{0} cannot be written. {1} does not exist'.format(filename, folder)
```

2018-01-19 19:19 UTC, terminalmage commented on salt/modules/incron.py
> +            return salt.utils.stringutils.to_unicode(contents.readlines())
`.readlines()` produces a list, not a string. This should be:

```python
return salt.utils.data.decode(contents.readlines())
```

2018-01-19 19:19 UTC, terminalmage commented on salt/modules/ini_manage.py
> +                outfile.writelines(salt.utils.stringutils.to_str(ini_gen))
`ini_gen` is a list here, not a string. Like above, either we need to run `salt.utils.stringutils.to_str()` in a list comprehension, or you can open this file with mode `wb` and use:

```python
outfile.writelines(salt.utils.data.encode(ini_gen))
```

2018-01-20 19:37 UTC, cachedout approved these changes

2018-01-22 18:54 UTC, terminalmage approved these changes

2018-01-22 19:40 UTC, merged