Add unicode_literals to modules, states, and related tests
saltstack/salt pull request #45560
Opened 2018-01-19 21:01 UTC by rallytime

2018-01-22 19:12 UTC, terminalmage requested changes
Just a few minor changes.

2018-01-22 19:12 UTC, terminalmage commented on salt/modules/kapacitor.py
> +log = logging.getLogger(__name__)
Since we don't actually _use_ the log object in this file, we can remove lines 27 and 28.

2018-01-22 19:12 UTC, terminalmage commented on salt/modules/virt.py
> +                    .format(img_dest, six.text_type(disk_size))
`six.text_type` is unnecessary here since we're in a `.format()`.

2018-01-22 19:12 UTC, terminalmage commented on salt/modules/virt.py
> +                    .format(disk_type, img_dest, six.text_type(disk_size))
`six.text_type` is unnecessary here since we're in a `.format()`.

2018-01-22 19:12 UTC, terminalmage commented on salt/modules/virt.py
> +                  ' instead of %s', image, disk_name, diskp[0][disk_name].get('image', None))
`None` is implied if no argument is passed to a `dict.get()`. This doesn't necessarily need to be changed, though.

2018-01-22 19:12 UTC, terminalmage commented on salt/states/kapacitor.py
> +log = logging.getLogger(__name__)
This log object is never used, lines 25 and 26 can be removed.

2018-01-22 19:36 UTC, terminalmage approved these changes

2018-01-23 12:53 UTC, rallytime commented
re-run py

2018-01-24 14:13 UTC, merged