[oxygen] Merge forward from 2017.7 to oxygen
saltstack/salt pull request #45617
Opened 2018-01-22 21:02 UTC by rallytime

Conflicts:
  - salt/modules/pip.py
  - salt/modules/win_pkg.py
  - salt/runners/manage.py
  - salt/states/pkg.py
  - salt/transport/zeromq.py
  - salt/utils/event.py
  - tests/integration/modules/test_pip.py
  - tests/integration/states/test_user.py
  - tests/unit/grains/test_core.py
  - tests/unit/states/test_archive.py
  - tests/unit/utils/test_boto.py

2018-01-22 21:44 UTC, rallytime commented
re-run centos

2018-01-22 21:48 UTC, rallytime commented
re-run centos

2018-01-23 14:39 UTC, terminalmage requested changes

2018-01-23 14:39 UTC, terminalmage commented on salt/modules/win_pkg.py
> +                          '{1}'.format(version_num, pkg_name))
This log message needs to be fixed in Oxygen, `.format()` changed to string replacement.

2018-01-23 18:27 UTC, rallytime commented
I'll need to redo this because it has a merge conflict now.

2018-01-23 18:27 UTC, closed without merging