check the lowstate __id__ before using it
saltstack/salt pull request #45705
Opened 2018-01-26 07:49 UTC by jasperla

it may not always be set, for example when coming in via state.low.

### What does this PR do?

Effectively unbreak `state.low` when `__id__` is not explicitly passed (as suggested by the documentation).

### What issues does this PR fix or reference?

#45682

### Previous Behavior

```
[root@salt salt]# salt salt\* state.low '{"state": "file", "fun": "exists", "name": "/etc/fstab"}'
salt.localdomain:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 312, in low
        ret = st_.call(data)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1901, in call
        ret['__id__'] = low['__id__']
    KeyError: '__id__'
[root@salt salt]#
```

### New Behavior

```
[root@salt salt]# salt salt\* state.low '{"state": "file", "fun": "exists", "name": "/etc/fstab"}'
salt.localdomain:
    ----------
    __run_num__:
        0
    __sls__:
        None
    changes:
        ----------
    comment:
        Path /etc/fstab exists
    duration:
        0.792
    name:
        /etc/fstab
    pchanges:
        ----------
    result:
        True
    start_time:
        07:48:24.983401
[root@salt salt]#
```

### Tests written?

No(t yet)

### Commits signed with GPG?

No

2018-01-26 10:43 UTC, jasperla commented
@gtmanfred I'm not quite sure how to create the test though, as currently the `State.call()` is [mocked](https://github.com/saltstack/salt/blob/develop/tests/unit/modules/test_state.py#L65) in the `state.low` tests. Should it be adjusted too like such:
```
        def call(data):
            '''
                Mock call method
            '''
            ret = {}
            if '__id__' in data:
              ret['__id__'] = data['__id__']
            return ret
```

and adjust the callers accordingly?

2018-01-26 15:09 UTC, gtmanfred commented
so, you can't do a mock like that, because they you aren't actually testing the `call()` function, and if a change is made, it won't be caught.

If you mocked the possible external function calls in the `call()` function, that would be what I would do, and just have one extra state.low test that does this.

2018-02-13 19:46 UTC, garethgreenaway approved these changes

2018-02-22 21:54 UTC, jasperla commented
@gtmanfred I'm sorry but while I understand what you mean, I have no idea how to go about this.
You mean to mock any (missing) external calls from `salt/salt/state.py#State.call()` in `test_state.py` and then one extra `state.low` test that that does what exactly?

2018-02-22 22:55 UTC, gtmanfred commented
since you are testing the code for state.low against salt.state:State.call(), you need to make sure you aren't mocking call(), otherwise what is the point, if someone changes State.call(), the test is not going to fail if they break state.low, because you have mocked the whole function.

2018-03-07 18:01 UTC, rallytime commented
@jasperla Did you see the comment above?

2018-03-12 19:03 UTC, jasperla commented
@rallytime I have, then I got distracted by `smartos_nictagadm`. I'll follow-up shortly!

2018-04-03 13:56 UTC, rallytime commented
Just another bump on this one @jasperla :)

2018-04-04 20:24 UTC, thatch45 commented
Sorry I am so slow on this one. If a low chunk does not have an `__id__` then the `__id__` should be the name. So the right way to fix this would be to still return an `__id__` but copy it in from the `name` key

2018-04-04 20:25 UTC, thatch45 requested changes
We should never return a `ret` from the state system without an `__id__`

2018-04-04 20:27 UTC, thatch45 commented
You may have also noticed that in your example the outputter is the nested outputter and not the highstate outputter. This is because the highstate outputter is crashing when it looks for `__id__` and is falling back onto the nested outputter

2018-05-31 19:18 UTC, rallytime commented
Hi @jasperla - Were you able to come back to this regarding the comments above?

2018-06-15 17:29 UTC, rallytime commented
I am going to close this PR for now since we haven't hear back for a while on this. When you're ready, please let us know and we will happily open this up again. Or feel free to open a new PR. Whichever is easier for you. Thank you!

2018-06-15 17:29 UTC, closed without merging