support amazon linux 2 for service module
saltstack/salt pull request #45764
Opened 2018-01-29 20:15 UTC by mchugh19

### What does this PR do?
Same as #45758, but for the 2017.7 branch. Disables rh_service.py on Amazon Linux 2

### Previous Behavior
service.running states ran via rh_service.py rather than systemd and failed. 

### New Behavior
Systemd is used to manage service calls and runs properly.

### Tests written?
No

### Commits signed with GPG?
No

2018-01-30 13:46 UTC, rallytime requested changes
I have one small request

2018-01-30 13:46 UTC, rallytime commented on salt/modules/rh_service.py
> +                    'Amazon Linux >= version 2 use systemd, will not '
`use` --> `uses` and then maybe let's split the message up into 2 sentences with `systemd. Will not`.

2018-01-30 17:16 UTC, mchugh19 commented
Edited the copy/pasted bits!

2018-01-30 19:11 UTC, rallytime approved these changes

2018-02-02 05:04 UTC, terminalmage approved these changes

2018-02-02 05:05 UTC, terminalmage commented
@rallytime I think this should be added to the RC branch.

2018-02-02 14:12 UTC, merged