[oxygen] Merge forward from 2017.7 to oxygen
saltstack/salt pull request #45760
Opened 2018-01-29 17:52 UTC by rallytime

Conflicts:
  - salt/modules/gnomedesktop.py
  - salt/utils/cloud.py

2018-01-29 23:33 UTC, terminalmage requested changes
Some misspellings.

2018-01-29 23:33 UTC, terminalmage commented on salt/modules/gnomedesktop.py
> +    def gestting_command(self):
I'm guessing this was supposed to be `gsetting_command`, not `gestting_command`.

2018-01-29 23:33 UTC, terminalmage commented on salt/modules/gnomedesktop.py
> +        cmd = self.gestting_command + ['get', str(self.SCHEMA), str(self.KEY)]
Same misspelling here.

2018-01-29 23:33 UTC, terminalmage commented on salt/modules/gnomedesktop.py
> +        cmd = self.gestting_command + ['set', self.SCHEMA, self.KEY, value]
Also here.

2018-01-29 23:34 UTC, terminalmage approved these changes
Actually nevermind, this is a merge, I will fix the things I addressed in my review in the proper branch.

2018-01-29 23:39 UTC, terminalmage commented
Misspellings addressed in https://github.com/saltstack/salt/pull/45773

2018-01-30 13:53 UTC, rallytime commented
@terminalmage Good catch! I merged your 2017.7 changes in and merged those forward to this PR.

2018-01-30 17:47 UTC, merged