Mac add service util
saltstack/salt pull request #45774
Opened 2018-01-30 00:33 UTC by twangboy

### What does this PR do?
Fixes a race condition processing the `__virtual__` for `mac_system`. It was trying to execute a `__salt__['cmd.run']` before it was available in `__salt__`. Moved those functions to `salt.util.mac_utils`.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/45673

### Tests written?
No

### Commits signed with GPG?
Yes

2018-01-30 14:19 UTC, rallytime requested changes
Just one question here from me.

There should also be some unittests written against these new functions.

2018-01-30 14:19 UTC, rallytime commented on salt/modules/mac_service.py
> +    return salt.utils.mac_utils.launchctl(sub_cmd, args, kwargs)
Should this be `**kwargs`?

2018-01-30 18:43 UTC, twangboy commented on salt/modules/mac_service.py
> +    return salt.utils.mac_utils.launchctl(sub_cmd, args, kwargs)
Probably

2018-01-31 21:19 UTC, twangboy commented
@rallytime I've added the unit tests. They pass individually, but not when run together. I need help getting this figured out.

2018-02-28 20:15 UTC, rallytime commented
@twangboy Were you able to come back to this change?

2018-03-01 01:28 UTC, twangboy commented
@rallytime I need help with the tests. I'll fix the merge conflict

2018-03-01 21:32 UTC, twangboy commented
@rallytime OK, I think we got this fixed. @terminalmage figured it out.

2018-03-01 22:19 UTC, rallytime commented
@twangboy Great!

2018-03-03 02:59 UTC, terminalmage approved these changes
One small quibble in the docstring, but this otherwise ready to merge.

2018-03-03 02:59 UTC, terminalmage commented on salt/utils/mac_utils.py
> +    figure out how to properly mock the memoization decorator.
Mocking a decorator will cause you to enter a world of pain. I don't think we should bother attempting, TBH, so we can remove this last sentence from the docstring.

2018-03-05 15:00 UTC, rallytime commented
@twangboy This also has a line failure: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19750/violations/file/salt/utils/mac_utils.py/

2018-03-06 18:22 UTC, twangboy commented
@rallytime Lint fixed... sentence removed...
Rebased

2018-03-06 21:54 UTC, rallytime commented
re-run py3

2018-03-09 17:55 UTC, rallytime commented
re-run py3

2018-03-09 20:50 UTC, rallytime commented
@twangboy It looks like something isn't quite right on these tests for Python 3: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/7733/

Failing tests:
- unit.utils.test_mac_utils.MacUtilsTestCase.test_available_services_non_xml
- unit.utils.test_mac_utils.MacUtilsTestCase.test_available_services_non_xml_malformed_plist

2018-04-05 17:09 UTC, cachedout commented
@twangboy When will you be able to come back to this?

2018-04-10 20:47 UTC, twangboy commented
@rallytime @cachedout Fixed tests for Py3 and rebased

2018-04-10 20:55 UTC, cachedout commented
@rallytime Re-review from you needed then.

2018-04-11 14:25 UTC, rallytime approved these changes

2018-04-11 14:26 UTC, merged