[bugfix] Fix for oversized filenames in fileclient
saltstack/salt pull request #45808
Opened 2018-01-31 18:37 UTC by b1naryth1ef

### What does this PR do?

This PR fixes the bug reported in #40846, wherein salt will attempt (and fail) to write a file with a long filename (e.g. a URL we download that has long query params). This is caused by filesystem naming limitations, which are generally at or above 255 characters.

### What issues does this PR fix or reference?

#40846

### Previous Behavior

Salt would crash when attempting to download and cache a file with a large URL or large set of query paramaters.

### New Behavior

Salt will now use a SHA256 hash of the file name if the file name meets or exceeds 255 characters.

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-01-31 19:11 UTC, b1naryth1ef commented
There is likely a pending discussion here about whether salt should do this implicitly (as implemented in this PR) or whether this should be a flag which changes the cache directory. I avoided the latter since this seemed relatively sane and I didn't wanna mess around with passing parameters all over the place, although I'm open to swapping it over.

2018-02-08 17:32 UTC, terminalmage requested changes
This needs more work, because it would break things like `is_cached` and `_extrn_path` in the fileclient which would expect a full filename.

2018-02-08 22:04 UTC, b1naryth1ef commented
@terminalmage can you expand on what you mean by that a little bit? Based on my naive understanding and reading of the file, it looks like is_cached _uses_ `_extrn_path` (which is where my patch is applied).

2018-05-04 12:31 UTC, terminalmage approved these changes
You are right, I misread the function being modified when I was reviewing. Sorry!

2018-05-04 12:32 UTC, gtmanfred commented
re-run all

2018-05-04 16:41 UTC, b1naryth1ef commented
No problem! Rebased off the latest develop as was requested in slack.

2018-05-16 03:35 UTC, terminalmage approved these changes

2018-05-16 03:35 UTC, merged

2018-05-16 03:41 UTC, terminalmage commented
@rallytime I took care of the backport in https://github.com/saltstack/salt/pull/47673, so you don't need to. The call to `path_join` in the backport will however need to be fixed when merged into 2018.3, but this is something you already check for so we should be good.