Fix ldap eauth
saltstack/salt pull request #45811
Opened 2018-01-31 20:18 UTC by gtmanfred

### What does this PR do?
This pulls in a fix from @amendlik for checking the group authentication, but also cleans up the unicode/str/bytes stuff that was not working in this external authentication

### Tests written?

No (but this has been tested manually against freeipa)

### Commits signed with GPG?

Yes

2018-02-01 07:31 UTC, DmitryKuzmenko requested changes
Commented inline.

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                                                get_user_dn_search, [str('distinguishedName')])
Here is a missing `# future lint: disable=blacklisted-function` lint directive.

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                                               [salt.utils.stringutils.to_str(_config('accountattributename')), str('cn')])
Same here `# future lint: disable=blacklisted-function`

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                                           [salt.utils.stringutils.to_str(_config('accountattributename')), str('cn')])
Same here: `# future lint: disable=blacklisted-function`

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                    if username == salt.utils.data.decode(user).split(',')[0].split('=')[-1]:
If I'm not wrong `salt.utils.stringutils.to_unicode` shall be used here instead of `salt.utils.data.decode`.
Probably @terminalmage will correct me.

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                                            str('cn'),
`# future lint: disable=blacklisted-function`

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                if username == salt.utils.data.decode(user).split(',')[0].split('=')[-1]:
`salt.utils.stringutils.to_unicode`

2018-02-01 07:31 UTC, DmitryKuzmenko commented on salt/auth/ldap.py
> +                                                   [str('cn')])
`# future lint: disable=blacklisted-function`

2018-02-01 17:49 UTC, gtmanfred commented
Issues are fixed, let me just setup freeipa again, and make sure i didn't break anything

2018-02-01 18:13 UTC, gtmanfred commented
:+1: still works with python3 and python2 with the changes

2018-02-02 09:14 UTC, DmitryKuzmenko approved these changes
LGTM

2018-02-02 14:32 UTC, rallytime commented
@amendlik - We're pulling in your changes from #45372 back into the `oxygen.rc1` branch instead of your fix in develop. Can you take a look here?

2018-02-02 14:39 UTC, rallytime approved these changes

2018-02-06 15:53 UTC, cachedout reviewed
I am extremely hesitant to merge this without test coverage.

2018-02-07 22:46 UTC, gtmanfred commented
tests added.

2018-02-08 13:36 UTC, rallytime commented
@gtmanfred Lint here, too: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19099/violations/

2018-02-09 01:03 UTC, gtmanfred commented
Needs https://github.com/saltstack/salt-jenkins/pull/837 for these tests to actually be run

2018-02-09 01:54 UTC, gtmanfred commented
re-run py

2018-02-09 04:20 UTC, gtmanfred commented
https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/19769/testReport/unit.auth.test_ldap/

Tests pass

2018-02-09 12:02 UTC, rallytime commented
re-run lint

2018-02-09 12:23 UTC, rallytime commented
@gtmanfred This has a merge conflict now.

2018-02-09 13:29 UTC, gtmanfred commented
fixed

2018-02-12 16:26 UTC, rallytime commented
re-run lint

2018-02-12 22:44 UTC, gtmanfred commented
Well that didn't fix it, i am unsure of what 

```
22:13:18 Traceback (most recent call last):
22:13:18   File "/var/jenkins/.pyenv/versions/2.7.13/bin/pylint", line 11, in <module>
22:13:18     sys.exit(run_pylint())
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/__init__.py", line 17, in run_pylint
22:13:18     Run(sys.argv[1:])
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 1333, in __init__
22:13:18     linter.check(args)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 755, in check
22:13:18     self._do_check(files_or_modules)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 886, in _do_check
22:13:18     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/lint.py", line 967, in check_astroid_module
22:13:18     walker.walk(ast_node)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 959, in walk
22:13:18     self.walk(child)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 959, in walk
22:13:18     self.walk(child)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 959, in walk
22:13:18     self.walk(child)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pylint/utils.py", line 956, in walk
22:13:18     cb(astroid)
22:13:18   File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/saltpylint/blacklist.py", line 321, in visit_assign
22:13:18     self.imported_salt_modules[node_left.value.expr.name])
22:13:18 AttributeError: 'Attribute' object has no attribute 'name'
22:13:20 + EC2=1
``` is doing

2018-02-15 19:04 UTC, merged