Updating functions win_network.ip_addrs
saltstack/salt pull request #46003
Opened 2018-02-13 14:25 UTC by rrzaripov

Updating functions win_network.ip_addrs for supporting parameters cidr and type, as in network.ip_addrs

### What does this PR do?

Updating functionality of network.ip_addrs and network.ip_addrs6 to getting same result on Windows minions same as on Linux minions.

### What issues does this PR fix or reference?

Not found related issue in bug tracker.

### Previous Behavior

```
sat@salt-master:~# salt win7 network.ipaddrs cidr=192.168.0.0/16
jid: 20180213150316014627
win7:
    ERROR executing 'network.ipaddrs': The following keyword arguments are not valid: cidr=192.168.0.0/16
```

### New Behavior

```
salt@salt-master:~# salt win7 network.ipaddrs cidr=192.168.0.0/16
jid: 20180213152309761890
win7:
    - 192.168.33.214
```

### Tests written?

No (but manual testing passed on Windows 7 and Windows 10)

### Commits signed with GPG?

No

2018-02-13 16:00 UTC, rallytime reviewed
I have some minor doc comments

2018-02-13 16:00 UTC, rallytime commented on salt/modules/win_network.py
> +    Providing a CIDR via 'cidr="10.0.0.0/8"' will return only the addresses
I know you didn't add this function and the associated docs originally, but I'd love it if definitions for each of these kwargs could be added. There should be examples of how to do this in other modules. Then you could add a `.. versionadded:: Fluorine` tag to the new options and make it easy for people to see when these were added.

2018-02-13 16:00 UTC, rallytime commented on salt/modules/win_network.py
> +    Providing a CIDR via 'cidr="2000::/3"' will return only the addresses
I have the same comment here as above.

2018-02-13 16:55 UTC, twangboy approved these changes
Approved, pending changes suggested by @rallytime

2018-02-13 19:18 UTC, rrzaripov commented
@rallytime please, check the documentation update, thank you for review!

2018-02-15 18:55 UTC, rallytime approved these changes

2018-02-15 18:55 UTC, rallytime commented
@rrzaripov The doc changes look good, but looks like there's a related line error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19265/violations/file/salt/modules/win_network.py/

2018-02-17 16:46 UTC, rrzaripov commented
@rallytime thank you for noticing, I fixed the error and update PR.

2018-02-20 19:09 UTC, rallytime requested changes

2018-02-20 19:09 UTC, rallytime commented on salt/modules/win_network.py
> +    .. versionadded:: 2014.7.0
Copy/Paste here? This should be `.. versionadded:: Fluorine` instead of these other versionadded and versionchanged tags. :)

2018-02-20 21:36 UTC, rallytime approved these changes

2018-02-23 19:22 UTC, merged