Backport #45981 to oxygen.rc1
saltstack/salt pull request #46008
Opened 2018-02-13 16:01 UTC by gtmanfred

### What does this PR do?
Backport #45981 to oxygen.rc1

### Tests written?

No

### Commits signed with GPG?

Yes

2018-02-13 19:45 UTC, garethgreenaway approved these changes

2018-02-13 21:43 UTC, rallytime commented
Go Go Jenkins!

2018-02-14 16:49 UTC, rallytime requested changes

2018-02-14 16:49 UTC, rallytime commented on salt/config/__init__.py
> +    'local': True
`'local': True,` --> needs a comma 😉

2018-02-14 16:51 UTC, gtmanfred commented on salt/config/__init__.py
> +    'local': True
whoops, fixed.

2018-02-14 20:28 UTC, rallytime approved these changes

2018-02-14 20:28 UTC, merged