Scalability improvements to the redis cache module
saltstack/salt pull request #46031
Opened 2018-02-14 11:40 UTC by naegelin

Salt cache has a very inefficient means of processing salt mine data which can create heavy reads against the mine cache. For syndics which are in remote locations (different datacenters or high-latency hops) this means reads become slow and blocking in environments where mines are heavily used.  Significant performance improvements can be had by installing a local redis instance on or near the local syndic which is slave to the primary redis cache master (cache.redis.host).  This improvement allows salt to hit the local redis for all significant read activity while maintaining a synchronized cache across syndics.  In other words, using both the remote and local redis configuration options on a syndic ensures that cache writes are centralized and heavy read activity remains localized.

2018-02-14 11:57 UTC, naegelin commented
I will leave this here for whoever wants to run with it as I don't have the bandwidth to meet some of these silly linting rules you guys have in place.

2018-02-14 15:31 UTC, terminalmage requested changes
You actually passed lint. We're still tuning the codeclimate check, so you can disregard it for now. You will however need to fix several issues with needlessly-removed blank lines which will affect Sphinx formatting.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
>  password:
None of the lines above should have been deleted, many are there for Sphinx formatting. Please put them back.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
> -
This blank line needs to be put back.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
> +    Redis connection password of the read-only slave.
Blank lines are needed after each of the above options.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
>      cache.redis.host: localhost
These blank lines need to be added back.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
> -
This blank line needs to be added back.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
>      cache.redis.cluster_mode: true
These blank lines need to be added back.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
> +.. code-block::yaml
A blank line is needed both before and after the `code-block` line.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
>  Cluster Configuration Example:
Blank line needed before this line.

2018-02-14 15:31 UTC, terminalmage commented on salt/cache/redis_cache.py
>      An improvement for this would be loading a custom Lua script in the Redis instance of the user
Add these blank lines back, please.

2018-02-28 20:10 UTC, rallytime commented
@naegelin Were you able to come back to the feedback here?

2018-03-13 15:26 UTC, rallytime commented
I am going to close this since we haven't heard back here. We can always reopen when you're ready to come back to this. Or feel free to open a new PR. Thank you!

2018-03-13 15:26 UTC, closed without merging