implement minimal fix for #45798
saltstack/salt pull request #46044
Opened 2018-02-14 23:13 UTC by arnoschuring

### What does this PR do?
Changes the libcloud version checker to not choke on -rc release versions.

### What issues does this PR fix or reference?
This should fix #45798

### Previous Behavior
```
$ salt-cloud -V                                                         
Traceback (most recent call last):
[..]
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 28, in <module>
    int(part) for part in libcloud.__version__.replace('-', '.').split('.')[:3]
ValueError: invalid literal for int() with base 10: '0rc2'
```

### New Behavior
```
$ salt-cloud -V
Salt Version:
            Salt: 2018.2.0-2306-g2972204
 
Dependency Versions:
 Apache Libcloud: 2.0.0rc2
[..]
```

### Tests written?
No

### Commits signed with GPG?
No

2018-02-14 23:39 UTC, gtmanfred commented
I was pretty certain this was fixed at one point...

2018-02-14 23:42 UTC, gtmanfred commented
Wait it does, Which version are you running into this problem with?
```
.replace('rc', '.')
```

This was added to specifically fix this problem, and it is in all current and latest released version.

2018-02-15 00:59 UTC, gtmanfred requested changes
This shouldn't need to be done, because we are already replacing the rc with a .

2018-02-15 10:27 UTC, arnoschuring commented
ah, never mind, I ran into the issue with 2017.7.2 and forward-ported the check to current develop without verifying if the issue still existed there

2018-02-15 15:25 UTC, gtmanfred commented
This should be in 2017.7.2

https://github.com/saltstack/salt/blob/v2017.7.2/salt/cloud/libcloudfuncs.py#L28

2018-02-15 15:25 UTC, closed without merging