Add docker.prune - pruning for Docker subsystems
saltstack/salt pull request #46176
Opened 2018-02-24 11:20 UTC by The-Loeki

### What does this PR do?
Add `docker.prune`, which is capable of clearing Docker's subsystems of cruft. Which seems necessary, a lot ;)

2018-02-24 12:22 UTC, The-Loeki commented
> Function prune has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

FOR REALZ ROFLMAO I could explain this function to my Cognitively Complexively Challenged neighbours

2018-02-26 15:16 UTC, rallytime commented
@The-Loeki Yeah, we need to tweak the rules for the code-climate build. Can you also add some tests for this new functions?

2018-02-26 15:59 UTC, The-Loeki commented
Hi, I'm afraid I'm going to have to pass on that one due to time constraints... I will however update the function once I get the same function PR'd in docker-py; that should get rid of the hidden function calls.

After that I'm not even sure what there is to test in this case. That is, I'm assuming Docker does it's testing on the API endpoints, `_client_wrapper` is tested as well, I'm not parsing / evalling any output, so what's left is to test is the if constructs?

2018-03-03 03:06 UTC, terminalmage requested changes

2018-03-03 03:06 UTC, terminalmage commented on salt/modules/dockermod.py
> +
Doing a quick sweep of the codebase, these API functions all seem to have been added in docker-py 2.1.0. Can you please add the following here?

```rst
    .. note::
        This requires docker-py version 2.1.0 or later.
```

If pre-2.1.0 docker-py is installed, `_client_wrapper()` function will handle the API error from the unknown function call, so we won't have a traceback. This is just a bit of extra information that should help users who may be on earlier docker-py releases.

2018-03-03 04:10 UTC, terminalmage requested changes
Actually there are a few things about this which don't actually work at all, it looks like it may not even have been tested since the `kwargs` argument doesn't exist for these API funcs and trying to run this function on my laptop immediately resulted in a tracecback.

I'm working on some modifications that I can submit against your fork that should clear this up.

2018-03-03 04:52 UTC, terminalmage commented
Another thing I noticed as I look deeper into the docker-py codebase is that negative filters don't seem to be supported. I've opened https://github.com/docker/docker-py/issues/1940 upstream to get clarification.

2018-03-03 07:50 UTC, terminalmage commented
@The-Loeki Have a look at https://github.com/The-Loeki/salt/pull/1, I made some fixes, changed how `system` works, and added unit tests.

2018-03-03 14:44 UTC, The-Loeki commented
@terminalmage thanks for all the help and advice, regarding the older api's: I can probably easily write up the same kind of workarounds for the other prunes?

2018-03-03 15:41 UTC, terminalmage commented
You mean posting directly to the API endpoint? Yeah, that should be doable, and I can also work to get them supported in docker-py. Which other prunes are yet to be supported?

2018-03-03 17:03 UTC, The-Loeki commented
AFAIK just the one I already opened a PR for, so that would be purely a backwards compat feature

2018-03-03 17:33 UTC, terminalmage commented
Oh, so you were talking about making backwards-compatibility changes for containers, images, etc? If so, I don't think it's necessary in this PR.

2018-03-03 21:21 UTC, merged