Added new functions to CIMC modules
saltstack/salt pull request #46222
Opened 2018-02-27 19:48 UTC by spenceation

### What does this PR do?
Add new CIMC Execution modules:
  - get_hostname
  - get_power_configuration
  - get_syslog_settings
  - set_hostname
  - set_logging_levels
  - set_power_configuration
  - set_user

Add new CIMC State Modules:
  - hostname
  - logging_levels
  - power_configuration
  - user

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-02-28 19:22 UTC, rallytime requested changes
This looks good to me. Very nice. The only thing I would say is that these new functions should have `.. versionadded:: Fluorine` tags.

2018-03-01 13:40 UTC, spenceation commented
@rallytime I've added the requested version tags. Please let me know if there are any issues with them.

2018-03-01 20:02 UTC, rallytime approved these changes

2018-03-01 20:02 UTC, rallytime commented
@spenceation Thanks! There's a tiny lint error here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19716/violations/file/salt/modules/cimc.py/

2018-03-05 19:44 UTC, merged