Add lxd module and states
saltstack/salt pull request #46231
Opened 2018-02-27 21:59 UTC by pcdummy

### What does this PR do?

Adds support for [LXD](https://linuxcontainers.org/lxd/) (Containers, Images and Profiles).

It lived for a long time in [LXD Formula](https://github.com/saltstack-formulas/lxd-formula).

Authors:
Me
[keesbos](https://github.com/saltstack-formulas/lxd-formula/commits?author=keesbos)
[sferket](https://github.com/saltstack-formulas/lxd-formula/commits?author=sferket)

### Tests written?

No

### Commits signed with GPG?

Yes

2018-02-27 22:08 UTC, gtmanfred requested changes

2018-02-27 22:08 UTC, gtmanfred commented on salt/states/lxd.py
> +.. versionadded:: unknown
This will be Fluorine

2018-02-27 22:08 UTC, gtmanfred commented on salt/states/lxd.py
> +__salt__ = {}
These are not needed, we excempt __salt__ and __opts__ in our pylint.

2018-02-27 22:16 UTC, gtmanfred approved these changes

2018-02-27 22:16 UTC, gtmanfred commented
This looks great!  Thanks for submitting these!

2018-02-28 15:33 UTC, rallytime commented
@pcdummy Can you write some tests for these new modules?

2018-03-01 14:59 UTC, pcdummy commented
@rallytime Don't think i get the time for doing so and i even wouldn't know to start with tests.

2018-03-13 15:21 UTC, rallytime commented
@pcdummy There's some documentation [here](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) and we are happy to answer any questions. We won't be able to add new modules and states without some test coverage.

2018-04-03 17:59 UTC, gtmanfred commented
@rallytime I have added an issue for adding tests for this before the fluorine release.

2018-04-03 17:59 UTC, gtmanfred commented
re-run all

2018-04-04 20:50 UTC, merged