Support unittest.mock from Python >= 3.6 again
saltstack/salt pull request #46415
Opened 2018-03-07 12:08 UTC by bdrung

Python 3.6 contains unittest.mock which provide all needed functions (including MagicMock.assert_called). Therefore reverts commit 9d004f6512d0619df895e0aca56143490a34337c partially to only require mock >= 2.0.0 for Python < 3.6.

I have tested this change on Debian unstable.

fixes #46281
Signed-off-by: Benjamin Drung <benjamin.drung@profitbricks.com>

2018-03-07 12:17 UTC, isbm requested changes
The original idea actually was to stop using different libraries (even so they do have intersection of required functions to this time), but have it unified and so have only one point of failure. I also have seen no reasons having two libraries, instead of using upgraded one for all, which is equally covering both major Python versions. Reverting it back will again bring us to infrastructure bugs, and a chaos in a long run.

I'd say, use everything you need in Mock 2. If newer comes out and we really need that, then let's just upgrade to the latest-greatest. But please do not create a grid of `if/else`s that will then shoot your foot, once they diverge again.

@terminalmage what you think?

2018-03-07 15:32 UTC, bdrung commented
@isbm I disagree. mock 2.0.0 says:
```
Rolling backport of unittest.mock for all Pythons
```
So mock and unittest.mock should behave the same. You just have to check that unittest.mock or mock is recent enough (which this pull request does).

2018-03-07 17:08 UTC, isbm commented
We don't run 3.6.

2018-03-08 09:11 UTC, bdrung commented
Debian testing/unstable and Ubuntu >= 17.10 use Python 3.6. `unittest.mock` is part of the *standard library*. The sole purpose of `mock` is to provide `unittest.mock` for older Python releases.  `unittest.mock` and `mock` are not two different libraries, but `mock` is the backport of `unittest.mock`.

2018-03-08 09:13 UTC, isbm commented
And our tests are running 3.4 and so we need it too.

2018-03-08 09:36 UTC, bdrung commented
That's why this patch falls back to use `mock` if Python is not recent enough.

2018-03-08 10:01 UTC, isbm commented
This is why we do not need it at all, since there is already a fallback _anyway_.

2018-03-08 10:15 UTC, bdrung commented
It would be nice to not require installing additional libraries if not needed. `unittest.mock` comes with Python, but `mock` needs to be installed additionally. You do not need it, but it would be nice to have it as Debian package maintainer.

2018-03-08 10:24 UTC, isbm commented
You surely need it, because if you develop unit tests, you _must_ run your unit tests on Python 2.7 as well. And so you _already_ will have Mock 2.0 installed.

2018-03-08 13:10 UTC, bdrung commented
I don't need it when building the Debian package, because that package is build against a specific Python version and the unit tests are run at build time. The build environment is a minimal environment.

2018-03-09 17:09 UTC, terminalmage commented
So, there are two competing sets of needs, here.

1. In SaltStack's jenkins setup, we have a less-limited environment and can easily install mock 2.0.0. This allows us to have a level playing field across all platforms.

2. Debian's platform list is much narrower, and their build/test environment more limited. Having mock 2.0.0 everywhere is not important.

I think the best option here would be to add a CLI option to runtests.py that tells it what to use, but this may prove difficult since we would need to pass/store the result of this CLI option so that it is available when we import from tests.support.mock.

2018-03-09 19:35 UTC, bdrung commented
I don't see a reason why you want to use `mock` instead of `unittest.mock` on Python >= 3.6. New features will be implemented in `unittest.mock` and backported to `mock`.

2018-03-09 20:26 UTC, terminalmage commented
I think @isbm was pretty clear in his initial response. Our reasoning is so that in our test suite, we import the _same exact module_ across all platforms. We install mock via pip when setting up our test VMs, so when mock is updated, test VMs will begin to use the next version, while a distro which uses Python 3.6+ will not update it's minor release of Python. This will cause mock to diverge.

I'm not sure why you'd want to have diverging code when testing multiple different platforms.

2018-04-10 20:40 UTC, cachedout commented
@bdrung Do you have any follow-up comments here?

2018-05-15 15:11 UTC, rallytime commented
Since we haven't heard anything back here for a while, I am going to close this PR. We can of course open this again later if desired and we're happy to continue the discussion as needed. Thank you!

2018-05-15 15:11 UTC, closed without merging