[2018.3.0rc1] fixes to nacl module & runner
saltstack/salt pull request #46426
Opened 2018-03-07 18:08 UTC by garethgreenaway

### What does this PR do?
Fixing a few bugs introduced following the move to unicode all the things.  Adding deprecation notices for the previously used `key` and `key_file` arguments.  Adding deprecation into Release notes.  Adding some tests for Naccl module and runner to test encryption and decryption.

### What issues does this PR fix or reference?
#46334 

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-03-07 19:19 UTC, rallytime approved these changes
Nicely done.

2018-03-07 19:46 UTC, sjorge commented on salt/modules/nacl.py
> +        sk_file = kwargs['sk_file']
should this not be kwargs['keyfile'] ? if assume the idea to to warn and keep the old stuff working until Flourine.

2018-03-07 19:48 UTC, sjorge requested changes
There is a small bug i think, I added a line comment.

2018-03-07 20:02 UTC, garethgreenaway commented
@sjorge Yes!  Thanks!  Thought I caught all of those.

2018-03-07 23:17 UTC, rallytime commented
@garethgreenaway Looks like a couple of test failures here: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/16998/

2018-03-07 23:25 UTC, garethgreenaway commented
@rallytime looks like I need to gate these to ensure libnacl is installed.  Thanks!

2018-03-08 10:54 UTC, sjorge requested changes

2018-03-08 10:54 UTC, sjorge commented on salt/runners/nacl.py
> +        sk_file = kwargs['sk_file']
This one is also still wrong!

2018-03-08 10:56 UTC, sjorge commented
Out of scope for this fix, the code between the module and runner is nearly the same. Maybe we should have a salt.utils.nacl eventually?

2018-03-08 11:03 UTC, sjorge commented on salt/runners/nacl.py
> +    return base64.b64encode(b.encrypt(salt.utils.stringutils.to_bytes(data)))
Sorry to nitpick at this, while applying the changes to locally I noticed this line.
I don't think this one is present in salt.modules.nacl yet the function there is the same as here!

2018-03-08 13:26 UTC, sjorge commented
With the patch applied (with a few more sk_file -> keyfile) I still hit the error. With the following bit in my py-rendered pillar.

```
__salt__['nacl.dec'](data=user['password'], key=nacl['db'])
```

We also need to deprecate the 'key' parameter and have it copied to 'sk' until Flourine.

2018-03-08 16:06 UTC, rallytime commented
@sjorge:

> Out of scope for this fix, the code between the module and runner is nearly the same. Maybe we should have a salt.utils.nacl eventually?

Yeah, I think that is a good idea. Something like that would need to go into develop for a future feature release.

@garethgreenaway Can you follow up on the remaining comments?

2018-03-08 16:46 UTC, garethgreenaway commented
:+1: for salt.utils.nacl.  The code duplication between the two was one of the things I had noticed as well and should be fairly easy to move it into a shared location.

2018-03-08 18:11 UTC, garethgreenaway commented
All the references to `sk` or `sk_file` that should be `key` or `key_file` respectively have been updated.  The unnecessary duplicate `to_bytes` code has been removed.  There was a warning already in place mentioned `key` being deprecated.  And I'm unable to duplicate the issue of calling `nacl.dev` from a py rendered pillar file, are there any errors or additional information in the master logs?

2018-03-08 18:22 UTC, sjorge commented
```#!py
######
## PR 46426
## -----------------------------------
######

import os
import hashlib
import binascii
nacl_key = 'Ii5pTnanQPlo7Asp12NLdCsBd1hgo+PD5tEAPw8TW8Q='
def nthash(password):
  return binascii.hexlify(
    hashlib.new(
      'md4',
      password.encode('utf-16le')
    ).digest()
  ).upper()

def run():
  # salt-run nacl.enc data=password key=nacl_key
  enc_password = 'FZlbJiMU1jwJzQh/yLKPgmEIu56HhPg233PfZuvg6zFk8eFrJbc2kF72BNxJkJy30aGf'
  plain_password = __salt__['nacl.dec'](data=enc_password, key=nacl_key)
  return {
    'test': {
       'crypt': __salt__['shadow.gen_password'](plain_password, 'XeBnQC', 'sha256'),
       'lanman': nthash(plain_password),
    }
  }

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2```

@garethgreenaway above is a stripped down version of my pillar, this should trigger it.

2018-03-08 20:27 UTC, garethgreenaway commented
@sjorge I was able to get your pillar file work by adding an additional argument:
```plain_password = __salt__['nacl.dec'](data=enc_password, key=nacl_key, box_type='secretbox')```

The default is to use the `sealedbox` approach which assumes the data was encrypted using the public key and then will be decrypted using the private key, versus the `secretbox` approach which assumes the data will be encrypted using the same key.

2018-03-08 20:30 UTC, sjorge commented
Perhaps we can set box_type to secretbox if box_type is unset and key is passed?

That way all existing code keep working for this release. (I actually already fixed my code to the new system, but probably best not to break peoples stares/pillars in oxygen just yet.)

2018-03-09 14:58 UTC, rallytime commented
@garethgreenaway Looks like those disable lint errors aren't quite right: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19983/violations/

@sjorge Did you get a chance to follow up on the most recent changes?

2018-03-09 18:09 UTC, sjorge commented
@rallytime I manually applied the changes from 5a2913ff1c9659f2714640961a88937785d12c66 and that made my pillar current pillar work with a few warnings.

So that looks good to me.

2018-03-09 19:17 UTC, merged