[develop] schedule clean up and error tests
saltstack/salt pull request #46651
Opened 2018-03-21 20:08 UTC by garethgreenaway

### What does this PR do?
Removing some duplicate code when handling "when" schedule items. 
Moving tests looking for errors in test_errors.  
Adding new tests to account for other error situations.

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-03-21 20:33 UTC, s0undt3ch requested changes

2018-03-21 20:33 UTC, s0undt3ch commented on salt/utils/schedule.py
> +                        when__ = dateutil_parser.parse(__when)
First check if its already a date time object, if not parse.

2018-03-21 21:43 UTC, garethgreenaway commented
@s0undt3ch :+1: Grabbed the other `isinstance` checks from #46540

2018-03-22 08:09 UTC, s0undt3ch approved these changes
Looks right now :+1:

2018-03-22 08:20 UTC, s0undt3ch commented
We did find another issue though. Happening on 2018.3.
If you what 2 when entries, the second never fires because _next_start_time is set to the first fire time and in the checks, since that date is way in the past, compared to now - interval, it never fires the 2nd entry.

I'll submit a PR against 2018.3

2018-03-22 12:38 UTC, s0undt3ch commented
Never mind my last comment. I was not updating all of the `_` prefixed fields on our end causing the scheduler to misbehave.

2018-03-22 15:44 UTC, merged