Fixing cleanUp method to restore environment
saltstack/salt pull request #46655
Opened 2018-03-22 03:06 UTC by dwoz

### What does this PR do?

The clean-up method was not reliabliy restoring sys.environment on
windows. Using Mock's patch to cleanup more reliably.

### What issues does this PR fix or reference?

#46350

### Previous Behavior

cleanUp method was not restoring sys.environ properly (at least on windows)

### New Behavior

Mock's patch method restores environ properly

### Tests written?

No - This fixes a hand full of existing tests.

### Commits signed with GPG?

Yes

2018-03-22 04:47 UTC, dwoz commented
Looks like this is breaking some other tests in unit.states.test_environ. Making this a WIP until I resolve those.

2018-03-22 06:52 UTC, dwoz commented
Adding `clean=True` to the patch call seems to have done the trick. I think this is good to go.

2018-03-22 17:29 UTC, dwoz commented
I ended up modifying `states.environ.setenv` to handle windows environments a bit more reasonably. The crux of the issue is that environment variables on windows are not case sensitive. Keys are always represented as upper case however.

Without my patch the `tests.unit.states.test_environ.TestEnvironState.test_setenv` test will always fail on the third assertion because `setenv` was in-correctly updating the key `test` which already exists in the environment.

2018-03-22 19:02 UTC, twangboy approved these changes

2018-03-26 15:27 UTC, rallytime commented
@dwoz Looks like there's a related test failure here and some lint. Can you take another look?

2018-03-26 21:16 UTC, rallytime commented
@dwoz This is still failing a related test on linux: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/21135/

2018-03-27 18:40 UTC, dwoz commented
I'm hoping we'll be good after the last commit.

2018-03-27 20:01 UTC, dwoz commented
re-run all

2018-03-27 21:07 UTC, rallytime commented
@dwoz One more lint fix :)

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20489/violations/file/tests/unit/states/test_environ.py/

2018-03-27 21:12 UTC, dwoz commented
@rallytime That linter is doing it's job.

2018-03-28 15:15 UTC, rallytime commented
re-run py

2018-03-28 17:51 UTC, rallytime requested changes
Just some stylist things that need to be changed, otherwise 👍

2018-03-28 17:51 UTC, rallytime commented on tests/unit/states/test_environ.py
> +import salt.utils as utils
I know the `environ` state above was doing it this way, but we are trying to make these imports more uniform. Can you change this to use the full path? That makes it easier to lint/check for these references in newer branches that have diverged from using the funcs in the `salt.utils.__init__.py` file.

2018-03-28 17:51 UTC, rallytime commented on tests/unit/states/test_environ.py
> +        '''test that we can set perminent environment variables (requires pywin32)'''
Can you split up this doc line into 3 lines?

2018-03-29 14:59 UTC, rallytime commented
re-run py2

2018-03-29 14:59 UTC, rallytime approved these changes

2018-03-29 18:31 UTC, merged