Volume password
saltstack/salt pull request #46694
Opened 2018-03-23 21:16 UTC by edevenport

### What does this PR do?

Allows a image root password to be set for server console access. SSH keys are required and now an password is optional.

### Tests written?

No

### Commits signed with GPG?

No

2018-03-26 14:30 UTC, rallytime requested changes
I have one small request, otherwise LGTM.

2018-03-26 14:30 UTC, rallytime commented on doc/topics/cloud/profitbricks.rst
> +
Can you add a `.. versionadded:: Fluorine` tag to this new option?

2018-03-27 14:26 UTC, rallytime approved these changes

2018-03-27 14:27 UTC, rallytime commented
@edevenport Ah, there's a small lint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20450/violations/file/salt/cloud/clouds/profitbricks.py/

2018-03-28 03:27 UTC, denza commented
@rallytime Thanks for heads up. Fixed

2018-03-28 21:11 UTC, rallytime commented
re-run py

2018-03-29 14:10 UTC, merged