Set public and private IP addresses
saltstack/salt pull request #46695
Opened 2018-03-23 21:20 UTC by edevenport

### What does this PR do?

This PR allows a user to set reserved public IP addresses and private IP addresses.

### Previous Behavior

Previously only dynamically assigned IP addresses were allowed.

### New Behavior

Dynamically assigned IP addresses are still the default, but reserved "status" IP addresses can now be assigned.

### Tests written?

No

### Commits signed with GPG?

No

2018-03-26 15:17 UTC, rallytime requested changes
Just one small change requested, otherwise, this looks good.

2018-03-26 15:17 UTC, rallytime commented on doc/topics/cloud/profitbricks.rst
> +
Adding a `.. versionadded:: Fluorine` directive would be good for this new option.

2018-03-26 15:17 UTC, rallytime commented on doc/topics/cloud/profitbricks.rst
> +
Same comment here as above.

2018-03-26 21:12 UTC, denza commented
@rallytime A version tag added.

2018-04-02 21:58 UTC, denza commented
@rallytime Could you please let us know if you require any further changes.

2018-04-03 12:45 UTC, rallytime approved these changes

2018-04-03 12:45 UTC, rallytime commented
@denza Looks good! Thanks!

2018-04-03 12:45 UTC, merged