Purge fix
saltstack/salt pull request #46901
Opened 2018-04-05 15:32 UTC by cbosdo

### What does this PR do?

* Adds a `type` attribute to each disk output by `virt.get_disks`
* Adds a `removables=True` parameter to `virt.purge`

### What issues does this PR fix or reference?

Fixes issue #46747 

### Previous Behavior

`virt.purge` removes all disk images, including ISOs and devices attached to removable devices (cdrom or floppy types)

### New Behavior

Now files attached to removable devices can be kept by calling `virt.purge removables=False`

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-04-05 18:09 UTC, cbosdo commented on salt/modules/virt.py
> +    Pass removables=False to avoid deleting cdrom and floppy images. NOTE THAT
@cachedout as mentioned by @gtmanfred in the issue: to avoid breaking the current behavior too hard.

2018-04-05 18:17 UTC, gtmanfred commented on salt/modules/virt.py
> +    Pass removables=False to avoid deleting cdrom and floppy images. NOTE THAT
If that is what we are doing, then it should be set to None, and then handled below, and also marked as deprecated behavior using warn_until.

https://docs.saltstack.com/en/latest/topics/development/deprecations.html

2018-04-06 06:39 UTC, cbosdo commented on salt/modules/virt.py
> +    Pass removables=False to avoid deleting cdrom and floppy images. NOTE THAT
done

2018-04-06 13:39 UTC, gtmanfred requested changes

2018-04-06 13:39 UTC, gtmanfred commented on salt/modules/virt.py
> +        )
you should also add removeables=True here.  We still want it to maintain the current behavior until that behavior is deprecated in Sodium.  Once we reach the time to work on the Sodium release, we will just remove this whole block, and set the default value in the definition to be `removables=False,`

And the message should be something like `The 'removables argument default value is True, but will be changed to False by default in {version}.  Please set to True to maintain the current behavior in the future.`

2018-04-06 17:41 UTC, gtmanfred approved these changes

2018-04-09 15:21 UTC, rallytime requested changes
I have one small request here, but otherwise, this looks good.

2018-04-09 15:39 UTC, rallytime approved these changes

2018-04-09 16:40 UTC, cachedout approved these changes

2018-04-09 18:47 UTC, rallytime commented
re-run centos

2018-04-09 21:55 UTC, rallytime commented
@cbosdo There are some related unit tests failing due to this change:

- unit.modules.test_virt.VirtTestCase.test_get_disks
- unit.modules.test_virt.VirtTestCase.test_purge_default
- unit.modules.test_virt.VirtTestCase.test_purge_noremovable

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/3907/

Can you take a look?

2018-04-10 06:50 UTC, cbosdo commented
@rallytime those tests are all failing with message `No such file or directory: 'qemu-img'` which means that some package seems to be missing on the setup since my commits didn't change anything related to qemu-img.

2018-04-10 13:50 UTC, rallytime commented
@cbosdo Ah, then something in your changes seems to be triggering those tests when they weren't before, though I don't know what it is off hand. We need to be protecting those tests against running when that library is missing. Would you mind adding that check?

2018-04-10 14:33 UTC, cbosdo commented
@rallytime my bad, I added these tests and get_disks is using qemu-img. I fixed that my mocking up subprocess.Popen and subprocess.Popen.communicate to fake qemu-img's call. Should be back to normal now

2018-04-10 17:06 UTC, rallytime commented
Thanks @cbosdo!

2018-04-10 17:06 UTC, merged