Added clone_images to OpenNebula template_clone kwargs
saltstack/salt pull request #46960
Opened 2018-04-09 14:29 UTC by Sikerdebaard

### What does this PR do?
Added clone_images to OpenNebula template_clone kwargs. If set to True the images attached to the template will be cloned as well.

### What issues does this PR fix or reference?
Unknown

### Previous Behavior
Previously only the template would be cloned and the cloned template would be linked to the original image.

### New Behavior
With this code the option to clone the images along with the template in one RPC call has been added.

### Tests written?

No

### Commits signed with GPG?

No

2018-04-09 14:46 UTC, gtmanfred approved these changes

2018-04-09 14:46 UTC, gtmanfred requested changes
Actually, this should be made against develop, since it would be a new feature, and it needs to be added to the documentation for opennebula.

2018-04-09 14:50 UTC, Sikerdebaard commented
@gtmanfred I've changed the base to develop. I'm not sure how to change the documentation.

2018-04-09 15:17 UTC, gtmanfred commented
Can you rebase your PR to develop, so that it only has your changes in it?

The documentation is just at the top of the opennebula.py file.

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/opennebula.py#L2

and also here

https://github.com/saltstack/salt/blob/develop/doc/topics/cloud/opennebula.rst

If you could just reference the new option somewhere in there, that would do.

2018-04-10 12:33 UTC, gtmanfred approved these changes

2018-04-10 12:33 UTC, merged