Add support for pypsexec and smbprotocol
saltstack/salt pull request #47028
Opened 2018-04-11 19:23 UTC by dwoz

### What does this PR do?

- Removes the need for winexe which is not packaged for all platforms we
  support. The replacement, pypsexec, is pure python so it will work
  everywhere. #46818 

- Add support for smbprotocol to be used instead of impacket.
  smbprotocol supports python 3 and is also used by pypsexec. #46819 

### What issues does this PR fix or reference?

#46818, #46819

### New Behavior

Installing pypsexec and smbprotocol allows us to spin up windows boxes using salt cloud under python 3 without the need for the winexe executable. This also makes using winrm under python 3 work.

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-04-11 19:37 UTC, gtmanfred requested changes
Can you revert the changes to salt.7, and also add a whole section to the doc/topics/releases/fluorine.rst

Otherwise, this looks good to me

2018-04-11 19:37 UTC, gtmanfred commented on doc/man/salt.7
> +\fI\%smbprotocol project home\fP
This file does not need to be edited, it is generated when the package is built.

2018-04-11 21:09 UTC, gtmanfred approved these changes

2018-04-11 22:37 UTC, dmurphy18 commented
@dwoz will this still need impacket to be packaged by Salt Stack, or are the checks for in case it is already installed ?

2018-04-12 03:43 UTC, dwoz commented
@dmurphy18 The checks are to warn users about the depreciation if they already have impacket installed. If smprotocol gets installed, it will be preferred over impacket.

2018-04-12 18:01 UTC, UtahDave commented
I'm getting some errors when using this PR with salt-ssh.
First I tested with the very latest in develop on Python 2.7 and impacket.   salt-ssh worked correctly.

Then I checked out this PR and installed Salt and smbprotocol. I uninstalled impacket.

Here's the output I got:

```
[boucha@elsapo salt (dwoz-pypsexec)]$ sudo salt-ssh test-win-ssh disk.usage
[WARNING ] /usr/local/lib/python2.7/dist-packages/salt/utils/thin.py:549: DeprecationWarning: Use of 'salt.utils.fopen' detected. This function has been moved to 'salt.utils.files.fopen' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 514, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 990, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1288, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1246, in shim_cmd
    self.shell.send(shim_tmp_file.name, target_shim_file, makedirs=True)
  File "saltwinshell/core.pyx", line 127, in saltwinshell.core.Shell.send (saltwinshell/core.c:3567)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 359, in put_file
    password=password
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 331, in _put_file_smbprotocol
    file_open = conn.open_file(tree, path)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 119, in open_file
    CreateOptions.FILE_NON_DIRECTORY_FILE,
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/open.py", line 1012, in create
    return self._create_response(request)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/open.py", line 1018, in _create_response
    response = self.connection.receive(request)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/connection.py", line 1037, in receive
    raise smbprotocol.exceptions.SMBResponseException(response, status)
SMBResponseException: Received unexpected status from the server: (3221225485) STATUS_INVALID_PARAMETER: 0xc000000d
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 514, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 990, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1288, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1246, in shim_cmd
    self.shell.send(shim_tmp_file.name, target_shim_file, makedirs=True)
  File "saltwinshell/core.pyx", line 127, in saltwinshell.core.Shell.send (saltwinshell/core.c:3567)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 359, in put_file
    password=password
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 331, in _put_file_smbprotocol
    file_open = conn.open_file(tree, path)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/smb.py", line 119, in open_file
    CreateOptions.FILE_NON_DIRECTORY_FILE,
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/open.py", line 1012, in create
    return self._create_response(request)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/open.py", line 1018, in _create_response
    response = self.connection.receive(request)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/connection.py", line 1037, in receive
    raise smbprotocol.exceptions.SMBResponseException(response, status)
SMBResponseException: Received unexpected status from the server: (3221225485) STATUS_INVALID_PARAMETER: 0xc000000d
[ERROR   ] Target 'test-win-ssh' did not return any data, probably due to an error.
test-win-ssh:
    Target 'test-win-ssh' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'str' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 791, in run
    data['jid'] = jid  # make the jid in the payload the same as the jid in the tag
TypeError: 'str' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 791, in run
    data['jid'] = jid  # make the jid in the payload the same as the jid in the tag
TypeError: 'str' object does not support item assignment
```

2018-04-13 13:58 UTC, rallytime commented
@dwoz There are some lint failures here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20926/violations/

2018-04-13 19:28 UTC, dwoz commented
@rallytime Thanks, I will look into them.

@UtahDave I will be testing the salt-ssh setup over the weekend.

2018-04-17 00:32 UTC, UtahDave commented
@dwoz Let's test this after updating to the latest develop after this big salt-ssh PR:   https://github.com/saltstack/salt/pull/46684

2018-04-19 18:16 UTC, rallytime commented
@dwoz Can you rebase this with latest develop and see how the tests go?

2018-04-20 15:18 UTC, rallytime requested changes

2018-04-20 15:18 UTC, rallytime commented on salt/utils/cloud.py
> +        """
These need to be single quotes rather than double for salt coding standards :)

2018-04-20 15:18 UTC, rallytime commented on salt/utils/smb.py
> +class MissingSmb(SaltException):
Would it make sense to move this to the `exceptions.py` file instead?

2018-04-29 00:07 UTC, dwoz commented
@UtahDave Can you test this again. I've am able to run salt-ssh against a brand new box with python 2 now.

2018-04-29 07:38 UTC, dwoz commented
Tested this with python 3 but it's dependent on some changes to saltwinshell.

2018-04-30 13:43 UTC, rallytime requested changes

2018-04-30 13:43 UTC, rallytime commented on doc/topics/cloud/windows.rst
> +   Fluorine. These dependencies are replaced by `pypsexec` and `smbprotocol`
The back-ticks around pypsexec and smbprotocol should be double back-ticks for these to format properly in the docs.

2018-04-30 13:43 UTC, rallytime commented on doc/topics/releases/fluorine.rst
> +This changes was made because ``impacket`` is not compatible with python 3.
`python 3` --> `Python 3`

2018-04-30 13:43 UTC, rallytime commented on salt/utils/cloud.py
> +        self._client = PsExecClient(server, usernamem, password, prot, encrypt)
`username` and `port` are misspelled here.

2018-04-30 16:19 UTC, rallytime approved these changes

2018-05-03 05:42 UTC, dwoz commented
@UtahDave @rallytime I have no objects to this going to 2018.3.

2018-05-03 14:33 UTC, rallytime commented
This is a pretty big change so I would usually prefer to put this in develop.

Is the current method for salt cloud not PY3 compatible? Or is there more information/context you can provide about why this would need to go into a bug-fix release?

I'd like @cachedout to weigh in here on this as well.

2018-05-03 14:43 UTC, gtmanfred commented
the current method is not py3 compatible, because it requires impacket, which only works on python2.

And also winexe, which doesn't build anymore for us, so we had to remove it from the repositories.

2018-05-04 16:39 UTC, UtahDave approved these changes

2018-05-04 17:54 UTC, merged