[2018.3] fix to fileclient.py
saltstack/salt pull request #47038
Opened 2018-04-12 18:40 UTC by garethgreenaway

### What does this PR do?
The _ext_nodes master function has been renamed to _master_tops. To ensure compatibility when using older Salt masters we continue to pass the function as _ext_nodes until the Magnesium release.

### What issues does this PR fix or reference?
#46977

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-04-13 13:45 UTC, rallytime commented
I am not familiar with this part of the code, or why that function was renamed, but do we _need_ to rename it? I think that providing a warning is good, but we'll still have this problem with older minions down the road. Is there a way we can alias the function names?

2018-04-13 13:58 UTC, garethgreenaway commented
@rallytime The function is aliased on the master side, so older minions will still be able to function without issue.  The issue popped up when a newer minion connects to an older minion, new minion is expecting that the master side function is named one thing but on the older master it's named something else.  If we pass the older name in the newer minion it will use the alias, until we can deprecate the function name in later versions where we no longer need to support those versions expecting that particular name.

2018-04-13 14:06 UTC, rallytime commented
@garethgreenaway Ah, OK. Thanks for the explanation. That makes more sense.

There's some test failure related to this it looks like. `Magnesium` doesn't exist yet. You'll need to uncomment it [here](https://github.com/saltstack/salt/blob/develop/salt/version.py#L106 ) and move the `pylint: disable` line.

(Looks like that file isn't quite right either. There are 2 Sodiums and there should only be one. Can you remove the commented out Sodium too while you're in there?)

2018-04-13 14:47 UTC, gtmanfred commented
Would it make more sense to just catch an error if the new function doesn't exist, and use the old function?  Then we don't ever have to deprecate it?

@thatch45 is Magnesium a long enough time to document that this will break backwards compatibility? for newer minions with older masters?

2018-04-13 16:07 UTC, terminalmage approved these changes
The change to `master_tops` only affects cases where the minion is a newer release than the master, which is not a supported use of Salt. That said, in the interest of reducing errors, I think this is OK. Magnesium may even be excessive, since we only support going back 2 full release cycles.

2018-04-13 16:08 UTC, gtmanfred approved these changes
ok, cool :+1:

2018-04-13 16:11 UTC, thatch45 commented
The only reason I say Magnesium is because this does not really hurt anything to keep it in there for a little longer, if we can make deprecation windows large enough that they should not bother anyone then we should do it that way.

2018-04-17 20:56 UTC, rallytime commented
@garethgreenaway Can you make the changes above about making the `Magnesium` variable available so we can get this in? Seems like all of the discussion has been resolved. :)

2018-04-20 15:23 UTC, rallytime requested changes
The `Magnesium` variable needs to be exposed in `version.py`.

2018-04-25 14:56 UTC, rallytime approved these changes

2018-04-25 14:57 UTC, merged