Fix issue #47225: avoid zfs.filesystem_present slowdown when dataset has lots of snapshots (2018.3 branch)
saltstack/salt pull request #47228
Opened 2018-04-21 23:22 UTC by pruiz

### Description of Issue/Question

This is the same pull-request as #47226, but against branch 2018.3.

zfs.filesystem_present (when specifying properties) takes forever on a dataset with lots (10k+) of snapshots, this is due to underlying zfs.dataset_present function not limiting properties query to only the filesystem actually being tested for presence, 
but instead allowing query to ask for snapshots and other sub-datasets too.

### Setup

Given a zfs dataset with lots of snapshots, a state like the follwing will take minutes to complete:

```yaml
zfs::dataset::data:
  zfs.filesystem_present:
    - name: TANK/data
    - properties:
        mountpount: /data
```

2018-04-23 14:08 UTC, rallytime commented
Hi @pruiz - There is a merge conflict on this change now. Can you rebase and fix the conflicts? Thanks for your work here. :)

2018-04-23 15:38 UTC, dmurphy18 requested changes
The develop branch changes for zfs were backported to 2018.3 branch, hence would expect that the changes to states/zfs.py should be the same as in #47226

2018-04-23 20:10 UTC, rallytime approved these changes

2018-04-24 08:09 UTC, isbm approved these changes

2018-04-24 13:35 UTC, merged