Fix issue #38366 salt-ssh support private key's passphrase
saltstack/salt pull request #47238
Opened 2018-04-23 08:13 UTC by pengyao

### What does this PR do?

Fix issue #38366

### What issues does this PR fix or reference?

Support private key's passphrase for salt-ssh

### Previous Behavior

Not support

### New Behavior

Private key's passphrase could be configured by:
* `--priv-passwd` for salt-ssh cli
* `salt_priv_passwd` for salt master configure file
* `priv_passwd` for salt roster file

2018-04-23 13:33 UTC, gtmanfred requested changes
Can you add docs about this config option to the salt ssh topics page?

2018-04-23 16:41 UTC, cachedout approved these changes

2018-04-23 16:46 UTC, gtmanfred commented
Also, adding this to the release notes for Fluorine would be greatly appreciated.

2018-04-24 13:31 UTC, gtmanfred requested changes

2018-04-24 13:31 UTC, gtmanfred commented on doc/man/salt-ssh.1
> +Specify the SSH private key file's passphrase.
Can you remove this change?

We compile these when they are packaged, it does not need to be updated.

2018-04-25 02:55 UTC, gtmanfred approved these changes

2018-04-25 17:43 UTC, rallytime commented
This change is causing many of the ssh tests to fail. @pengyao Can you take a look?

2018-04-26 05:43 UTC, pengyao commented
@rallytime It's my fault. I have fixed it.

2018-04-26 17:48 UTC, rallytime commented
@pengyao Looks like one more test here needs to be addressed :)

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/22289/

2018-05-01 16:43 UTC, cachedout commented
@pengyao Are you able to resolve that final failing test? We would really like to get this merged if we can. :)

2018-05-03 12:39 UTC, pengyao commented
@cachedout @rallytime  Jenkins Error is: 
```
No test reports found for the metric 'JUnit' with the resolved pattern 'artifacts/unittests/*.xml'. Configuration error?.
```
I think the error is not created by this commits

2018-05-03 14:27 UTC, rallytime commented
re-run py

2018-05-21 19:03 UTC, rallytime commented
@pengyao The following test is still failing:

- unit.config.schemas.test_ssh.RosterEntryConfigTest.test_config

That will need to be fixed before we can merge this in.

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/23028/

2018-05-22 13:31 UTC, rallytime commented
Thanks for fixing that @pengyao - that looks good.

I think an addition to the release notes (for Fluorine) would be good here as well. Can you add something for that? Then we can get this in :)

2018-05-31 18:59 UTC, rallytime commented
@pengyao We just need this added to the [Fluorine release notes](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/fluorine.rst) and then we can get this in.

2018-06-04 13:28 UTC, rallytime commented
@pengyao Oh! You're right. I thought I double checked but I must have missed it. Thank you!

2018-06-04 13:28 UTC, merged