set conf_file even if it is not readable
saltstack/salt pull request #47273
Opened 2018-04-24 15:17 UTC by gtmanfred

### What does this PR do?
This allows for using grains from the conf_file path, for example, even if the `minion` file does not exist.

### What issues does this PR fix or reference?
Fixes #45315

### Commits signed with GPG?

Yes

2018-04-25 19:13 UTC, gtmanfred commented on salt/config/__init__.py
> +
Because then when we read the file in above, `conf_file` can be overwritten from reading in the conf file.

2018-04-25 19:14 UTC, gtmanfred commented on salt/config/__init__.py
> +
Also, that method was causing all the test suites to have errors, that were resolved by doing it this way.

2018-04-25 19:14 UTC, gtmanfred commented
re-run py

2018-04-26 05:46 UTC, isbm requested changes

2018-04-26 05:46 UTC, isbm commented on salt/config/__init__.py
> +
Still. Why twice setting it? :wink:  How about this:

```python
if salt.utils.validate.path.is_readable(path):
    try:
        opts = _read_conf_file(path)
    except salt.exceptions.SaltConfigurationError as error:
        log.error(error)
        if exit_on_config_errors:
            sys.exit(salt.defaults.exitcodes.EX_GENERIC)
else:
    log.debug('Missing configuration file: {0}'.format(path))
opts['conf_file'] = path
```

2018-04-30 18:20 UTC, rallytime approved these changes

2018-04-30 18:46 UTC, isbm approved these changes

2018-04-30 20:27 UTC, rallytime commented
@gtmanfred This is causing several test failures at the HEAD of the branch, unfortunately: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/22415/#showFailuresLink

Can you take a look?

2018-05-29 15:06 UTC, gtmanfred commented
re-run py

2018-07-03 19:14 UTC, rallytime commented
@gtmanfred Bump - where are we on this one?

2018-07-03 20:56 UTC, gtmanfred commented
I need to do tests still, I will try to do that again on thursday

On Tue, Jul 3, 2018, 2:14 PM Nicole Thomas <notifications@github.com> wrote:

> @gtmanfred <https://github.com/gtmanfred> Bump - where are we on this one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/47273#issuecomment-402264478>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoVMlrmI04fVFqTjeW5uoGkPd6IdLks5uC8KqgaJpZM4Th4ye>
> .
>

2018-07-09 15:07 UTC, gtmanfred commented
I think this is going to require a change in how we load the config file, so I am going to close this, and look at adding something to develop.

Daniel

2018-07-10 17:40 UTC, closed without merging