Add additional service module integration tests and enable for windows
saltstack/salt pull request #47343
Opened 2018-04-26 22:20 UTC by Ch3LL

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/45005

2018-04-30 17:34 UTC, twangboy requested changes

2018-04-30 17:34 UTC, twangboy commented on tests/integration/modules/test_service.py
> +        self.assertTrue(self.run_function('service.enable', [self.service_name]))
Might need to disable the service first before testing the enable function

2018-05-01 16:25 UTC, cachedout commented
@twangboy Re-review requested.

2018-05-01 22:44 UTC, twangboy approved these changes

2018-05-02 13:39 UTC, merged