[develop] Adding clean_old_jobs to pgjsonb returner for Fluorine
saltstack/salt pull request #47366
Opened 2018-04-27 17:22 UTC by garethgreenaway

### What does this PR do?
Adding the clean_old_jobs function the pgjsonb returner for Fluorine

### What issues does this PR fix or reference?
#47316 

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-04-30 19:15 UTC, rallytime requested changes
LGTM, with the exception of a couple of very small comments.

Can you write some tests for this as well?

2018-04-30 19:15 UTC, rallytime commented on salt/returners/pgjsonb.py
> +`keep_jobs` to the number of hours for the jobs to live in the tables.
I know this is very picky, but these instances using single back-ticks throughout these new docs need to be using double back-ticks in order for our docs to display these terms as `code-format`. (Markdown uses single or double, RST uses double-only.)

2018-04-30 19:15 UTC, rallytime commented on salt/returners/pgjsonb.py
> +.. versionadded:: 2015.5.0
`Fluorine`?

2018-05-01 16:34 UTC, cro approved these changes

2018-05-01 22:01 UTC, rallytime approved these changes

2018-05-02 13:38 UTC, rallytime commented
re-run py

2018-05-02 20:46 UTC, merged