Allow for passing in previously compiled grains to custom grain modules
saltstack/salt pull request #47372
Opened 2018-04-27 20:25 UTC by gtmanfred

### What does this PR do?
If a grains module function accepts a variable named `grains` then the grains dict will be passed in.

### What issues does this PR fix or reference?
Closes #47338

### Previous Behavior
No grains are passed to custom grains modules

### New Behavior
Previously compiled grains are passed into grains functions if the function accepts a variable called `grains`

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-04-27 21:01 UTC, DmitryKuzmenko approved these changes

2018-04-28 09:24 UTC, isbm requested changes

2018-04-28 15:10 UTC, gtmanfred commented on doc/topics/grains/index.rst
> +passed in are ``core`` grains. This was added in the Fluorine Release.
that is not correct.

2018-04-28 15:11 UTC, gtmanfred commented on tests/integration/grains/test_custom.py
> +        self.assertEqual(self.run_function('grains.get', ['custom_grain_test']), 'itworked')
We are still using Unittests, so I am going to stick to unittests asserts until that changes.

2018-04-28 15:12 UTC, gtmanfred commented on salt/loader.py
> +                ret = funcs[key](**kwargs)
good point, and it looks like you can pass an empty kwargs to a function that doesn't take any arguments, TIL

2018-04-30 08:56 UTC, isbm commented on tests/integration/grains/test_custom.py
> +        self.assertEqual(self.run_function('grains.get', ['custom_grain_test']), 'itworked')
Actually, PyTest is now the next thing and we already running it all over the place anyway. Why would one invest in soon-to-be-dead old stuff and thus create another technical debt that will cause rewrite in the near distant future? I wouldn't do that.

2018-05-25 19:04 UTC, gtmanfred commented
re-run py

2018-05-25 20:45 UTC, rallytime approved these changes

2018-05-29 15:06 UTC, merged