Fix localized headers of yum in yumpkg.py
saltstack/salt pull request #47406
Opened 2018-04-30 17:16 UTC by shengis

### What does this PR do?

Strip localized headers of yum --quiet --showduplicates repository-packages list
erverything that is not matching package line format is discarded.

### What issues does this PR fix or reference?

Fixes #47404

### Previous Behavior
Discard headers: 'installed packages', 'available packages', 'updated packages', 'upgraded packages'

### New Behavior
Discard all lines that doesn't match the regex

### Tests written?

No

### Commits signed with GPG?

No

2018-04-30 18:56 UTC, isbm requested changes
I don't think this fix is correct. The whole Yum should run on reset locale and thus output everything in English. Matching packages... no, please not. Matching versions is even worse idea. I would rather then look deeper and figure out why French system is not talking on default locale!

I would consider this PR invalid.

2018-04-30 19:13 UTC, terminalmage requested changes
The issue with this approach is that the repo may be on a separate line if the package, version string, or repository runs long. This is because in the absence of a TTY with a known amount of columns, yum/dnf assumes a line width of 80.

Any fix would need to take that into account.

2018-04-30 19:15 UTC, isbm commented
I would certainly avoid parsing names/versions. @dincamihai @meaksh @brejoc thoughts how to help here?

2018-05-01 14:27 UTC, shengis commented
@terminalmage This is taken into account with the re.MULTILINE flag. But I agree, it's not correct to try to match a package line, hard to know what is really matched.

Also, I found the origin of the problem, LANGUAGE must be redefined. So this fix is not required as is.

2018-05-01 15:17 UTC, cachedout commented
@shengis Do you want to keep this PR open then or close it and attempt this another way?

2018-05-01 15:27 UTC, shengis commented
@cachedout I close it, to fix it with the LANGUAGE settings.

2018-05-01 15:27 UTC, closed without merging