Added masterless support to utils/minions.py:_pki_minions function
saltstack/salt pull request #47400
Opened 2018-04-30 14:34 UTC by mcd1992

### What does this PR do?
Adds support to utils/minions.py's _pki_minions function for masterless calls

### What issues does this PR fix or reference?
No known issues/pr open related to this but I ran into this being an issue when using ext_pillar & file_tree on a masterless dev. environment. The file_tree module would use the minions utility library to get all minions / nodegroups from PKI files which don't exist on the masterless minion.

### Previous Behavior
```
$ salt-call --local pillar.get nodegroups 
[ERROR   ] Failed matching available minions with compound pattern: *
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 684, in check_minions
    _res = check_func(expr, delimiter, greedy)
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 476, in _check_compound_minions
    minions = set(self._pki_minions())
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 250, in _pki_minions
    if self.opts['key_cache'] and os.path.exists(pki_cache_fn):
KeyError: u'key_cache'
```

### Tests written?
No

### Commits signed with GPG?
Yes

2018-04-30 14:36 UTC, mcd1992 commented
Made changes into single logic statement as requested in https://github.com/saltstack/salt/pull/47340

Hopefully this 'style' for multi-line is acceptable, didn't see many examples in existing code to base it off of.

2018-04-30 14:58 UTC, mcd1992 commented
Man I suck at git. Forgot to GPG sign and github doesn't like my git amend and force...

2018-05-01 21:39 UTC, mcd1992 commented
Aaand the fast forward is showing up in here.... The git history itself seems clean but the github PR is associating the other commits with this PR? Not sure if  this will cause an issue other than making the PR look bloated, let me know if I should just open another PR. If so I can base it off the 2018.3 branch anyway since this is more of a bugfix than a feature. Didn't realize the difference between develop branch and the others when I first forked this.

2018-05-01 22:03 UTC, rallytime commented
@mcd1992 We have some docs about that here, specifically step #6 about rebasing, if that helps?

https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request

2018-05-02 13:27 UTC, mcd1992 commented
Ah gotcha, thanks rally. Guess I still need to read up on the differences between a rebase and fast-forward.

2018-05-08 16:03 UTC, cachedout approved these changes

2018-05-08 18:58 UTC, rallytime commented
re-run py

2018-05-09 09:36 UTC, isbm requested changes

2018-05-09 09:36 UTC, isbm commented on salt/utils/minions.py
> +         (opts_role == 'minion')):
I think we have an issues with the indent here. Maybe just put it in one line, it anyway reads better then.

2018-05-10 14:32 UTC, rallytime commented
@mcd1992 This has a lint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/21716/violations/file/salt/utils/minions.py/

2018-05-10 17:37 UTC, isbm approved these changes

2018-05-10 17:37 UTC, isbm commented on salt/utils/minions.py
> +        if ((opts_role == 'master' and self.opts.get('__cli') == 'salt-run') or (opts_role == 'minion')):
Better, but too much parenthesis here :wink: Lint already said that too, BTW.

2018-05-10 17:38 UTC, isbm requested changes
Oops, clicked wrong selector. Please remove parenthesis and so fix Lint. :-)

2018-05-11 13:43 UTC, mcd1992 commented
I was unable to get the C0325 pylint error to show up locally but its a simple enough fix anyway.

https://gist.github.com/mcd1992/ba02c7978e9dcd69c2f29885d96ad6cd

2018-05-25 20:43 UTC, merged