make pillar top_matches work with node groups
saltstack/salt pull request #47421
Opened 2018-05-01 21:00 UTC by mattp-

### What does this PR do?
the compound match evaluator to date relied callers to pre-evaluate nodegroups
into their decomposed state. in some places this wasn't happening. Rather than
fix every call site, teach compound_match to evaluate nodegroups in place.

It seems matchers were refactored to salt.utils.minions at some point but the
original minion.py matcher was not ported to use it. Given the hugeness of that
change, i've left as is and ported my fix to salt.utils.minions as well
instead.

### What issues does this PR fix or reference?
this should fix #6602

### Previous Behavior
nodegroup in compound didn't work.

### New Behavior
it works.

### Tests written?
Pending;  pushing this to see what jenkins does

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-05-07 14:15 UTC, cachedout approved these changes

2018-05-07 14:39 UTC, isbm requested changes

2018-05-07 14:39 UTC, isbm commented on salt/minion.py
> +                    words = decomposed + words
You can do it with less coding:
```python
words[0:0] = salt.utils.minions.nodegroup_comp(target_info['pattern'], nodegroups)
```

2018-05-07 20:48 UTC, mattp- commented
@rallytime i believe this should be good to go now

2018-05-09 09:26 UTC, isbm approved these changes

2018-05-09 18:23 UTC, merged

2018-05-09 22:02 UTC, corywright commented
Dreams **can** come true!

Thanks @mattp-!