Fix pillar propagation in salt-ssh when overriding pillar in module.run + state.apply
saltstack/salt pull request #47504
Opened 2018-05-06 19:33 UTC by mateiw

### What does this PR do?

Add option to merge pillar with `opts['pillar']` during pillar compilation. The options is `False` by default and only set by `salt-ssh` in order to allow for the pillar to be propagated when applying a state using `module.run` + `state.apply` and overriding the pillar explicitly. 

This problem doesn't happen with regular, non-ssh minions.

### What issues does this PR fix or reference?

#47501

### Previous Behavior
If `pillar` is specified in `module.run` + `state.apply` it replaces any previous pillar data completely in the state that is applied instead of merging the value with the existing data.
E.g.
```yaml
call_show:
  module.run:
    - name: state.apply
    - mods:
      - showpillar
    - kwargs: 
          pillar:    # <= replaces existing pillar data completely in the showpillar state
              test: "foo bar"
```

### New Behavior
`salt-ssh` sets the option `pillar_compile_merge_global` to `True` in order to for the pillar compilation to merge the new data with the existing one.

### Tests written?

No

### Commits signed with GPG?

No

2018-05-07 13:37 UTC, gtmanfred approved these changes

2018-05-07 14:28 UTC, isbm requested changes

2018-05-07 14:28 UTC, isbm commented on salt/client/ssh/__init__.py
> +                    'pillar_compile_merge_global': True
This gets set to `True` all the time and ignores _any kind_ of settings. I would be OK to set it to `True` by default, but completely ignoring the opposite value of it isn't the great idea. And maybe shorter name? like `merge_pillar`.

2018-05-07 17:33 UTC, mateiw commented
Thanks for the suggestion @isbm. Renamed to `pillar_merge_global` and made it possible to override the default value using `minion_opts` in the roster file or globally using `ssh_minion_opts` in the master config.

2018-05-08 08:56 UTC, isbm requested changes
@mateiw some more updates.

2018-05-08 08:56 UTC, isbm commented on salt/client/ssh/__init__.py
> +                    'pillar_merge_global': True,
I'd remove this and put it do the default `ssh_.....` options that comes from `ssh_minion_opts`. Besides, I would use conventional name `ssh_<do>_<what>`. That would be `ssh_merge_pillar`, and set it to `True` by default. Anyone who wants it void can set it to `False` for Salt SSH.

2018-05-08 13:58 UTC, isbm approved these changes
@mateiw thanks, perfect! Now we're good to go.

2018-05-08 14:13 UTC, terminalmage requested changes
This looks good, but we should document the new config option in doc/ref/configuration/minion.rst (with a `.. versionadded:: 2018.3.2` to note when the option was added).

2018-05-08 14:59 UTC, mateiw commented
@terminalmage I added the documentation for this new option.

2018-05-08 15:31 UTC, terminalmage requested changes
Thanks for adding the docs! Just one minor tweak needed here.

2018-05-08 15:31 UTC, terminalmage commented on doc/ref/configuration/minion.rst
> +----------------------
Can you delete the last two dashes here? Sphinx will warn on the docs build when the dashed line is longer than the line above it.

2018-05-16 02:43 UTC, terminalmage approved these changes

2018-05-16 13:55 UTC, merged