Fix non-root build and signing for rpm packages
saltstack/salt pull request #47545
Opened 2018-05-08 17:41 UTC by dmurphy18

### What does this PR do?
Restores the ability to build and sign packages for rpm builds as a non-root user
This ability was changed in the Nitrogen release.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-pack/issues/545

### Previous Behavior
Could only perform builds and signing for rpm packages as root since 2017.7.0

### New Behavior
Restores ability to perform builds and signing for rpm packages as non-root user, for example: builder, with Salt minions as prior to the 2017.7.0 release.

### Tests written?
No, built and signed Centos 7 packages.

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-05-15 15:18 UTC, rallytime commented
re-run py2

2018-05-16 01:33 UTC, terminalmage requested changes
One small problem here. Also, I thought we standardized on using `user` instead of `runas` everywhere else beside `cmdmod.py`.

2018-05-16 15:44 UTC, dmurphy18 commented on salt/modules/rpmbuild.py
> +        __salt__['file.chown'](path=dest_dir, user=runas, group='mock')
Thanks for the catch, that looks like it should have been makedirs_perms, will fix

2018-05-16 15:58 UTC, dmurphy18 commented
@terminalmage There is a change coming from a contributor see https://github.com/saltstack/salt/pull/47056, so minimizing merge (user vs runas) when that is delivered.  Post merge can update both debbuild.py and rpmbuild.py, as the contributor is also updating debbuild.py.

Also reluctant to change preexisting code for new naming scheme in minor release, fix up in develop after merge.

2018-05-17 19:29 UTC, terminalmage approved these changes
Was not aware that runas was already used elsewhere in the module. That's fine, then. I just didn't want to be introducing new usage of runas if we were moving away from it.

2018-05-17 21:08 UTC, dmurphy18 commented
re-run py2

2018-05-17 21:20 UTC, merged