switch skip-roster to update-roster
saltstack/salt pull request #47541
Opened 2018-05-08 14:44 UTC by gtmanfred

### What does this PR do?
Writing to the /etc/salt/roster file by default was agreed by the SaltStack core engineers to be an undesirable action.  So I have switched the flag to be `--update-roster` and it defaults to False.

### What issues does this PR fix or reference?
Fixes #47532

### Tests written?

No

### Commits signed with GPG?

Yes

2018-05-08 14:50 UTC, cachedout approved these changes

2018-05-08 15:24 UTC, isbm requested changes
I am honestly not in a favour disabling CLI sugar-things that can help attract newcomers. Otherwise this has no much deal here and we shooting ourselves in the foot with this.

The main idea here was that everyone who wants to call salt-ssh can call it directly first time (think "hello world" in PHP or RoR), so then automatically roster gets updated with the credentials and so the next call is smooth. Now you've simply removed this, turning it into again roster-editing configuration curve, which everyone of newcomer hates.

What would be actually improved here is so:

- `ssh_autoupdate_roster: False` into `/etc/salt/master` to disable it explicitly (because the user is already familiar with Salt)
- Add message "host has been added to the roster X" once it is automatically added.

This way we can keep happy newcomers who hates _any sort of configuration_ as well as keep happy advanced users.

2018-05-08 22:41 UTC, edgan commented
@isbm This feature is broken out of the box. It assumes the title in the roster is a DNS resolvable FQDN. Which breaks existing assumptions that go back years, like title can be whatever, and the actual answer is host:. If host: didn't exist it would make sense, but it does. Breaking existing setups for new user sugar is bad.

Example:
```
title:
  host: 1.2.3.4
```

Real world example:
```
foo:
  host: 10.10.1.10
```

2018-05-09 08:41 UTC, isbm commented
@edgan thanks for the update!

Well, actually it is [Salt ID, not a title](https://docs.saltstack.com/en/latest/topics/ssh/roster.html). While this can be indeed anything, why would I put a quote of Oscar Wilde (or anything else) there instead of a short hostname? That said, it supposed to work that if you have something like:

```
my_world_simplest_id_i_could_imagine_to_enter_here:
    foo.somedomain.biz: 123.234.123.234
```

...then nothing bad happens having another record here, once you access `salt-ssh root@foo`:
```
foo:
    foo.somedomain.biz: 123.234.123.234
```

But seems like it should have a better improvement here, especially on poor DNS. So I am all ears how we can do this even less editor dependent. Or, rephrasing, how to automatically add host data to the roster in a better way.

Second, let us stop mixing here two completely different topics: feature itself and its default state. While you think the feature is not working as it should, please use `--skip-roster` option, while we're together making things better.

How do we still keep "autoroster" alongside with the smooth work for advanced users? Having new syntax like `salt-ssh user@host` helps a lot for newcomers and also daily users who dislike to edit roster every time new docker or temporary VM pops up. The initial goal was to make Salt SSH act something like SSH's `known_hosts`, which you do not manually edit at all. And so I see no reason why SaltSSH would not do this automatically, yet keeping the possibility to add hosts data manually or import them from somewhere.

Summarising, I do agree on improvement and listening to the ideas and compromises. But I disagree with the attitude to provide workarounds by moving unresolved questions away by default and avoid solving them and just move on.

2018-05-09 13:45 UTC, rallytime commented
I agree with @gtmanfred and @edgan here. I don't think we should be writing to `/etc/salt/roster` by default, especially since this is a change in default behavior. Passing `--update-roster` to enable the behavior instead of remembering to pass `--skip-roster` for existing installs seems like a good compromise to me.

2018-05-09 14:38 UTC, rallytime commented
@isbm Yes, after looking more closely here, I see there are 2 issues (as you stated in your previous comment - I can understand this a little better now)

1. The `None` syntax bug. This has already has been fixed in #47191. (Original report in #47529)
2. What we do with the default behavior (or another solution?) still needs to be decided. Which is what I think @thatch45 can chime in about.

We can definitely keep this conversation going. I don't think we should rush to get something in for the 2018.3.1 release. We should consider this carefully as we go forward, as you said @isbm. Thanks for chiming in so we can make sure we have a good solution moving forward.

2018-05-09 16:07 UTC, isbm commented
@rallytime absolutely. I am all ears how to improve this as best for everyone, yet keeping it "sweet", i.e. automatic. So, to recap:

- @gtmanfred properly noted that it is not good when things are added somewhere quietly with no message. I completely agree with it. Solution: add a verbosity to what just had happened.

- @edgan dislikes that some garbage is added to the main roster. I actually dislike that too. :wink: Thanks for the bug discovery. @edgan , if you could please write here clear steps to reproduce it, I will fix it and write some tests for this. Thanks!

- Following SSH itself, I'd say adding stuff in background to some cached analogy of like `~/.ssh/known_hosts` would be a correct way. Yes, `known_hosts` serves for a bit different purposes, but still we can leverage this. Probably not to the main `/etc/salt/roster`, but nothing wrong to add that to the _local_ roster, mentioning it in the CLI and have it totally volatile. So next time Salt SSH would look into the main roster _and_ in the local roster. And if nothing found, only then ask for passwords and other options.

Any other suggestions are highly welcome.

2018-05-17 15:24 UTC, thatch45 approved these changes

2018-05-17 15:25 UTC, thatch45 commented
In a nutshell, I find that it is appalling that we added something in the first place that would modify the flat roster, this change is a MUST.

2018-05-17 21:40 UTC, isbm approved these changes
@thatch45 OK, let's indeed leave main flat roster untouched.
@gtmanfred let's this go in first, then I will propose a follow-up PR on top of this that cleans up the cache story part.

2018-05-18 13:29 UTC, merged