Update napalm.py
saltstack/salt pull request #47597
Opened 2018-05-10 17:02 UTC by aesposito91

### What does this PR do?
Address issue - https://github.com/saltstack/salt/issues/47203

This will allow napalm proxy grains to update with a saltutil.refresh_grains

### What issues does this PR fix or reference?
This will allow napalm proxy grains to update with a saltutil.refresh_grains

### Previous Behavior
Grains would not update.

### New Behavior
Grains will update.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-05-10 17:42 UTC, mirceaulinic commented
This bugfix should target the 2017.7 branch and ported into 2018.3 then (or vice-versa).

2018-05-11 15:22 UTC, mirceaulinic requested changes
Please make sure you keep only that return, and change the branch to 2017.7 or 2018.3.

2018-05-11 15:22 UTC, mirceaulinic commented on salt/proxy/napalm.py
> +    return call('get_facts', **{})
This function should only return this (remove the rest of the code).

2018-05-11 19:23 UTC, gtmanfred requested changes
This needs to be rebased to remove the extra commits that are not related to what you are changing.

2018-05-11 19:34 UTC, aesposito91 commented
Will resubmit.

2018-05-11 19:34 UTC, closed without merging