Add file.tidied similar to Puppet's tidy resource.
saltstack/salt pull request #47718
Opened 2018-05-18 13:20 UTC by dhs-rec

### What does this PR do?
Adds file.tidied as inspired by Puppet
### What issues does this PR fix or reference?
Implements #46752
### Tests written?
No
### Commits signed with GPG?
No

2018-05-18 14:39 UTC, cachedout commented
I left some comments in #46752 on this.

2018-05-20 16:51 UTC, gtmanfred requested changes

2018-05-20 16:51 UTC, gtmanfred commented on salt/states/file.py
> +        if fnmatch.fnmatch(name, pattern):
I would use regex instead of fnmatch

2018-05-22 06:49 UTC, dhs-rec commented on salt/states/file.py
> +        if fnmatch.fnmatch(name, pattern):
Done.

2018-05-22 13:14 UTC, gtmanfred approved these changes

2018-05-22 13:45 UTC, rallytime commented
@dhs-rec Can you write some tests for this new function?

2018-05-24 07:28 UTC, dhs-rec commented
Once I manage to wrap my mind around the test stuff...

2018-05-24 16:38 UTC, rallytime commented
@dhs-rec Awesome! Thank you!

There's some docs on testing [here](https://docs.saltstack.com/en/latest/topics/development/tests/index.html), if it helps.

2018-07-03 18:30 UTC, rallytime commented
Hi @dhs-rec - just a bump on this one. Were you able to write some tests for this?

2018-07-09 07:06 UTC, dhs-rec commented
No, sorry. Tried last week but I somehow didn't get it (I'm not that experienced in Python hacking). So I would be glad if someone else could jump in...

2018-07-27 20:50 UTC, rallytime commented
@gtmanfred Do you think you could help out with some tests on this?

2018-07-27 21:04 UTC, gtmanfred commented
Yeah, make an issue and i will work on them :+1:

2018-07-30 16:41 UTC, gtmanfred commented
@dhs-rec i have opened a PR on your branch, once you merge it we should be able to get this PR in.

https://github.com/dhs-rec/salt/pull/1

Thanks,
Daniel

2018-08-05 14:25 UTC, merged

2018-08-10 09:58 UTC, dhs-rec commented
@gtmanfred: Great, thanks a lot!