External WAL directory and datapage checksums for PostgreSQL
saltstack/salt pull request #47780
Opened 2018-05-22 19:42 UTC by moench-tegeder

Since almost forever, PostgreSQL allows storing it's transaction log
(WAL, write ahead log) outside of the data directory (this improves
performance on certain setups, or may just be required by local
policy. The newly added "waldir" option on states.postgres_initdb.present()
and modules.postgresql.initdb() is passed to initdb (the default is
still to keep the transaction log inside the data directory).
As part of the big renaming in PostgreSQL 10 the old "xlog directory"
has been renamed to "wal directory", this patch uses the new name only.

Sind PostgreSQL 9.3 (which is the oldest supported release as of
time of writing), there is support for checksumming the database
on the block level. This can only be enabled when creating the
cluster (this is, at initdb time), so it should be available in
modules and states. This patch adds it in both places.

Documentation for both mini-features has been added to the doc strings.

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-05-22 19:43 UTC, moench-tegeder commented
The versionadded tag has been set to XXX, as it's up to your release planning if and when you merge this.

2018-06-08 20:05 UTC, gtmanfred requested changes

2018-06-08 20:05 UTC, gtmanfred commented on salt/modules/postgres.py
> +        version XXX. The ``checksum`` option requires PostgreSQL 9.3
This will be added in `Fluorine`, you can use the `.. versionadded: Fluorine` macro for rst.

2018-06-10 18:12 UTC, moench-tegeder commented
Ah right. I shouldn't fix documentation while overtired. Gave it a little improvement, too. Thanks for noticing.

2018-06-10 19:55 UTC, gtmanfred requested changes
Just need to fix the spelling and this should be good

2018-06-10 19:55 UTC, gtmanfred commented on salt/modules/postgres.py
> +
Should be Fluorine, like the element in the periodic table

2018-06-10 20:09 UTC, moench-tegeder commented
Drats. One of the few words spelled with "uo".

2018-06-10 23:30 UTC, gtmanfred commented on salt/states/postgres_initdb.py
> +        .. versionadded:: Flourine
One last thing :P these guys need to be fixed too.

2018-06-11 14:25 UTC, gtmanfred approved these changes

2018-06-11 14:35 UTC, rallytime requested changes
A couple of small requests from me.

2018-06-11 14:35 UTC, rallytime commented on salt/modules/postgres.py
> +        waldir=None,
Can you move these new kwargs to the end of the list? We don't want to cause an API change in case users are passing positional args.

2018-06-11 14:35 UTC, rallytime commented on salt/modules/postgres.py
> +        checksums=False,
Same comment here.

2018-06-11 14:57 UTC, moench-tegeder commented
sure, while I'm here.
And while grep failed me yesterday, today it found even more misspellings: https://github.com/saltstack/salt/pull/48052 :)

2018-06-29 19:28 UTC, moench-tegeder commented
Hi again,
is there anything I can do here? Unless I'm missing something, thw kwargs are now in order?

2018-06-29 19:36 UTC, rallytime approved these changes

2018-06-29 19:36 UTC, rallytime commented
Thanks for the bump. It looks great now. Thank you!

2018-06-29 19:36 UTC, merged