Fixes dry run in ini_manage + Fixes related bug - when working with o…
saltstack/salt pull request #47793
Opened 2018-05-23 08:28 UTC by slivik

### What does this PR do?
Fixes bug - Exception raised when working with ini options which are not in a section
Fixes related tests
Fixes pylint warnings

### What issues does this PR fix or reference?
[#47762 - Exceptions in ini_manage state module during dry run](https://github.com/saltstack/salt/issues/47762)

### Previous Behavior
When want to manage ini options which are not in section both dry run and normal run raises an exception.

### New Behavior
Working as expected in both dry and normal run.

### Tests written?

Yes. Updated tests.

### Commits signed with GPG?

Yes

2018-05-29 17:27 UTC, rallytime requested changes
I have one question on this initially, and before I go much further, can you fix the lint errors that were specified in the test run? We use the `.testing.pylintrc` file in the salt repo which has a bunch of salt-specific checks in it as well.

2018-06-05 08:55 UTC, slivik commented on salt/modules/ini_manage.py
> +    if section:
Yes, it is, but for option which is global (not nested under some section), you can provide section as None and get value of such option. So this condition is for this case.

2018-06-06 17:32 UTC, terminalmage approved these changes

2018-06-06 18:02 UTC, rallytime approved these changes

2018-06-06 19:04 UTC, rallytime commented
@slivik Can you fix up the lint errors?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22449/violations/file/salt/states/ini_manage.py/

2018-06-08 13:45 UTC, merged