Bugfixes and unit tests for pkgin module
saltstack/salt pull request #47814
Opened 2018-05-24 06:57 UTC by travispaul

Corrects pkg.latest_version and pkg.file_dict behavior

### What does this PR do?

Fixes 2 bugs in the pkgin module:
- pkg.latest_version doesn't return a version for an uninstalled package.
- pkg.file_dict crashes.

### What issues does this PR fix or reference?

None that I have found.

### Previous Behavior

**pkg.latest_version**

pkgin reports that nginx version 1.14.0 is available but not yet installed:
```
salt# pkgin se nginx
nginx-1.14.0         Lightweight HTTP server and mail proxy server

=: package is installed and up-to-date
<: package is installed but newer version is available
: installed package has a greater version than available package
```

However, pkg.latest_version returns nothing:
```
salt# salt \* pkg.latest_version nginx
salt.n7test.local:

```

**pkg.file_dict**

After installing a package, pkg.file_dict throws an exception:
 
```
# salt \* pkg.install nginx
salt.n7-test.local:
   ----------
   nginx:
       ----------
       new:
           1.14.0
       old:
   pcre:
       ----------
       new:
           8.42
       old:

salt# pkg_info -qL nginx
/opt/pkg/current/man/man8/nginx.8
/opt/pkg/current/sbin/nginx
/opt/pkg/current/share/examples/nginx/conf/fastcgi.conf
/opt/pkg/current/share/examples/nginx/conf/fastcgi_params
/opt/pkg/current/share/examples/nginx/conf/koi-utf
/opt/pkg/current/share/examples/nginx/conf/koi-win
/opt/pkg/current/share/examples/nginx/conf/mime.types
/opt/pkg/current/share/examples/nginx/conf/nginx.conf
/opt/pkg/current/share/examples/nginx/conf/win-utf
/opt/pkg/current/share/examples/nginx/html/50x.html
/opt/pkg/current/share/examples/nginx/html/inde

salt# salt \* pkg.file_dict nginx

salt.n7-test.local:
   The minion function caused an exception: Traceback (most recent call last):
     File "/opt/pkg/current/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
       return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
     File "/opt/pkg/current/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
       return func(*args, **kwargs)
     File "/opt/pkg/current/lib/python2.7/site-packages/salt/modules/pkgin.py", line 684, in file_dict
       for field in ret:
   RuntimeError: dictionary changed size during iteration
```

### New Behavior

**pkg.latest_version**

```
salt# salt \* pkg.latest_version nginx
salt.n7-test.local:
   1.14.0
```

**pkg.file_dict**

```
salt# salt \* pkg.file_dict nginx
salt.n7-test.local:
   ----------
   files:
       ----------
       nginx:
           - /opt/pkg/current/man/man8/nginx.8
           - /opt/pkg/current/sbin/nginx
           - /opt/pkg/current/share/examples/nginx/conf/fastcgi.conf
           - /opt/pkg/current/share/examples/nginx/conf/fastcgi_params
           - /opt/pkg/current/share/examples/nginx/conf/koi-utf
           - /opt/pkg/current/share/examples/nginx/conf/koi-win
           - /opt/pkg/current/share/examples/nginx/conf/mime.types
           - /opt/pkg/current/share/examples/nginx/conf/nginx.conf
           - /opt/pkg/current/share/examples/nginx/conf/win-utf
           - /opt/pkg/current/share/examples/nginx/html/50x.html
           - /opt/pkg/current/share/examples/nginx/html/index.html
           - /opt/pkg/current/share/examples/rc.d/nginx
```

### Tests written?

Yes

### Commits signed with GPG?

Yes

----

I'd just like to say that Salt has the **best** documentation I've ever seen for writing tests. As someone who has not written much Python, I especially found the page on using iPython invaluable. 
I ran my unit test on a machine without pkgin installed but may have missed something as writing Python unit tests is very new to me. Please let me know if they can be approved.

2018-05-24 07:10 UTC, travispaul reviewed
Added comments describing changes.

2018-05-24 07:10 UTC, travispaul commented on salt/modules/pkgin.py
> +            p = line.split(';' if _supports_parsing() else None)
This appears to have been inadvertently changed from ';' to ',' in 9df3dab883d21d1dcf40142d233fd005fc24c9c8

2018-05-24 07:10 UTC, travispaul commented on salt/modules/pkgin.py
> +                        if len(p) > 1 and p[1] == '<' or p[1] == '':
``p[1]`` will be an empty string here if the package has not yet been installed.

2018-05-24 07:10 UTC, travispaul commented on salt/modules/pkgin.py
> +    for field in list(ret):
Using ``list()`` here resolves the ``RuntimeError: dictionary changed size during iteration
`` exception.

2018-05-24 07:10 UTC, travispaul commented on salt/modules/pkgin.py
> +            if line.startswith('No results found for'):
Handles the case where the package wasn't found.

2018-05-24 07:30 UTC, travispaul commented on salt/modules/pkgin.py
> +                        if len(p) > 1 and p[1] in ('<', '', '='):
``p[1]`` is an empty string if the package is not installed and '=' if it is already installed and the latest version.

2018-05-24 09:55 UTC, isbm approved these changes

2018-05-24 12:07 UTC, sjorge commented
LGTM, will test this on SmartOS when I get home in about 1 hours.

2018-05-24 12:48 UTC, sjorge approved these changes
LGTM, works fine on SmartOS too.

```
[cronos :: sjorge][/salt/states/.extmods/_modules][master ✔]
[!]$ salt ares pkg.latest_version salt
ares:
    2018.3.0
[cronos :: sjorge][/salt/states/.extmods/_modules][master ✔]
[.]$ salt ares pkg.file_dict salt
ares:
    ----------
    files:
        ----------
        salt:
            - /opt/local/bin/salt
            - /opt/local/bin/salt-api
            - /opt/local/bin/salt-call
            - /opt/local/bin/salt-cloud
            - ...
```

2018-05-24 16:30 UTC, cachedout requested changes

2018-05-24 16:30 UTC, cachedout commented on tests/unit/modules/test_pkgin.py
> +        Test getting the latest version of an ininstalled package
`installed` or `uninstalled`? ;)

2018-05-24 16:32 UTC, rallytime commented
@travispaul There are some lint errors on the test file: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22137/violations/file/tests/unit/modules/test_pkgin.py/

Can you take a look?

2018-05-24 16:33 UTC, rallytime commented
@travispaul There are some lint errors on the test file: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22137/violations/file/tests/unit/modules/test_pkgin.py/

Can you take a look?

2018-05-24 17:03 UTC, travispaul commented
Thanks for the feedback. Hopefully I got those lint issues fixed. pylint wasn't as forgiving as jenkins and had some additional output (I did not run it until now).

2018-05-25 03:14 UTC, travispaul commented
Looks like those lint issues are now fixed: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22156/
Please let me know if any other changes are needed. Thanks.

2018-05-25 13:30 UTC, rallytime approved these changes

2018-05-25 13:30 UTC, merged