Fix issue when archive is on mapped drive
saltstack/salt pull request #47827
Opened 2018-05-24 23:39 UTC by twangboy

### What does this PR do?
Fixes an issue when the archive is on a drive letter that is not the same working directory as python. `os.path.relpath` throws the following error:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\dev\salt\salt\state.py", line 1889, in call
    **cdata['kwargs'])
  File "c:\dev\salt\salt\loader.py", line 1826, in wrapper
    return f(*args, **kwargs)
  File "c:\dev\salt\salt\states\archive.py", line 1006, in extracted
    existing_cached_source_sum = _read_cached_checksum(cached)
  File "c:\dev\salt\salt\states\archive.py", line 130, in _read_cached_checksum
    checksum_file = _checksum_file_path(path)
  File "c:\dev\salt\salt\states\archive.py", line 69, in _checksum_file_path
    log.debug('.'.join((os.path.relpath(path, __opts__['cachedir']), 'hash')))
  File "c:\python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive z:, start on drive c:
```

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/47791

### Previous Behavior
If the archive was on any other drive it would throw the above error.

### New Behavior
Now it doesn't. 
For the file `C:\temp\test.zip` on the same drive as the cwd, it creates the hash dir in the following location, dropping the drive letter (normal, previous behavior):
` c:\salt\var\cache\salt\minion\archive_hash\local\Temp\test.zip`
If the file was on a different drive (`Z:\temp\test.zip`) it will create the hash dir like this, instead of throwing an error (adding the drive letter):
`c:\salt\var\cache\salt\minion\archive_hash\local\z\temp\test.zip`

### Tests written?
No

### Commits signed with GPG?
Yes

2018-05-25 03:48 UTC, sbrakl commented on salt/states/archive.py
> +        if 'path is on drive' in exc.message:
Checking on the error message 'path is on drive' isn't way to do.  In my case, error message is 'ValueError: path is on mount 'd:', start on mount 'c:''. 
https://github.com/saltstack/salt/issues/47791

2018-05-26 12:06 UTC, sbrakl commented on salt/states/archive.py
> +        if 'path is on drive' in exc.message:
Cool, thanks

2018-05-30 22:19 UTC, twangboy commented
@sbrakl @terminalmage Could you review this again?

2018-05-31 04:06 UTC, sbrakl approved these changes
Look good to me

2018-06-01 19:13 UTC, terminalmage requested changes

2018-06-01 19:13 UTC, terminalmage commented on salt/states/archive.py
> +    log.debug('Found path: %s', relpath)
This is a rather generic message. Not only that, but `relpath` is just the path relative to the root of where where we are storing the checksum file. Maybe get rid of the line above, and replace the below with something like this:

```python
ret = salt.utils.path_join(__opts__['cachedir'], 'archive_hash', relpath)
log.debug('Using checksum file %s for cached archive file %s', ret, path)
return ret
```

2018-06-04 21:42 UTC, twangboy commented
Rebased
@terminalmage Updated the debug message

2018-06-06 16:41 UTC, terminalmage approved these changes

2018-06-06 17:18 UTC, merged