Prevent crash if files in file.recurse
saltstack/salt pull request #47923
Opened 2018-06-01 14:48 UTC by isbm

### What does this PR do?

Bugfix.

### What issues does this PR fix or reference?

```yaml
foo:
  file.recurse:
    - name: /tmp/blah
    - source: salt://foo
```

If we have `$SALT/foo/здоров-був.txt` file, crash happens. This PR fixes it.

2018-06-01 15:20 UTC, terminalmage requested changes
One minor change, and then this also needs a backport to 2018.3 (CC @rallytime)

2018-06-01 15:20 UTC, terminalmage commented on salt/modules/state.py
> +from salt.utils import to_unicode
`salt.utils` is deprecated, this would need to be imported from `salt.utils.stringutils`.

2018-06-02 18:40 UTC, isbm commented
![bart](https://i.imgflip.com/2bhqzp.jpg)

2018-06-03 03:39 UTC, terminalmage approved these changes

2018-06-04 13:56 UTC, merged