Add Azure DNS modules
saltstack/salt pull request #47945
Opened 2018-06-03 20:38 UTC by nicholasmhughes

### What does this PR do?
Add Azure DNS modules for crud operations on DNS zones and record sets.

### What issues does this PR fix or reference?
N/A

### Tests written?
No

### Commits signed with GPG?
Yes

2018-06-04 15:03 UTC, gtmanfred approved these changes
This looks good, can we get some unittests for these modules?

Thanks,
Daniel

2018-06-08 03:48 UTC, nicholasmhughes commented
The only unit tests I've done were heavily copy/pasted for (I believe) some `file` module functionality. I don't really know where to start for building Azure module unit tests from scratch. If someone can hold my hand on this, I might try... but I'm not certain if I have the bandwidth to complete them in a timely manner.

2018-06-08 13:57 UTC, gtmanfred commented
Look at the Boto modules unit tests.

And I am available (not today,at a conference today) but to help in the
#develop channel on the community slack.  Or in just pms there.

Thanks!
Daniel

On Thu, Jun 7, 2018 at 10:48 PM, Nicholas Hughes <notifications@github.com>
wrote:

> The only unit tests I've done were heavily copy/pasted for (I believe)
> some file module functionality. I don't really know where to start for
> building Azure module unit tests from scratch. If someone can hold my hand
> on this, I might try... but I'm not certain if I have the bandwidth to
> complete them in a timely manner.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/47945#issuecomment-395637913>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssoSXH4IO-FBjILUeQ133D8EhcyXyXks5t6fQBgaJpZM4UYOt->
> .
>

2018-08-05 19:32 UTC, rallytime commented
@nicholasmhughes Just a bump here. Were you able to get some tests going for this?

2018-08-05 21:06 UTC, nicholasmhughes commented
@rallytime , nope... I tried to mess around and duplicate the tests from the Azure SDK, but failed. I don't really have time in the near future to make it happen. As far as this PR, it's been field tested and there are already a lot of Azure modules merged that don't have tests. We can either merge this or close it. I'd prefer the latter obviously. :wink:

2018-08-15 08:40 UTC, cachedout requested changes

2018-08-15 08:40 UTC, cachedout commented on salt/states/azurearm_dns.py
> +import json
Unused import?

2018-08-15 08:40 UTC, cachedout commented on salt/states/azurearm_dns.py
> +import salt.utils
Unused import?

2018-08-15 15:32 UTC, cachedout approved these changes

2018-08-15 15:32 UTC, merged

2018-08-15 15:33 UTC, cachedout commented
Merged! Thanks, @nicholasmhughes. This is great.