[2018.3] Fix to cmd_batch
saltstack/salt pull request #48236
Opened 2018-06-21 04:41 UTC by garethgreenaway

### What does this PR do?
Fixing cmd_batch to work correctly when called via salt-api.

### What issues does this PR fix or reference?
#48141 

### Previous Behavior
When running from the salt-api this would result in an exception, presumably because salt.utils.versions was unavailable.

### New Behavior
import salt.utils.versions inside cmd_batch.

### Tests written?
Not yet.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-06-21 08:50 UTC, isbm commented
@garethgreenaway how come? This module is imported already and is used all over the place.

2018-06-21 08:51 UTC, isbm requested changes
This is really weird. The module is imported and is used all over the place. And only that one function fails?? How come?

2018-06-21 13:07 UTC, gtmanfred approved these changes

2018-06-21 13:08 UTC, gtmanfred commented
Probably because of multiprocessing

2018-06-21 14:20 UTC, rallytime commented on salt/client/__init__.py
> +            import salt.utils.versions
Can you add a comment here about why this later import is needed so we don't accidentally remove it in the future?

2018-06-22 15:40 UTC, rallytime approved these changes
And a test to boot! Well done.

2018-06-22 17:57 UTC, rallytime commented
@garethgreenaway That test is failing, however. Can you take a look?

2018-06-25 10:12 UTC, isbm approved these changes
@garethgreenaway thanks for the explanation comment.

2018-06-25 10:12 UTC, isbm commented on salt/client/__init__.py
> +            # the module is unavailable.
:+1:

2018-06-25 12:58 UTC, merged