Fixed apache.configfile to work with multiple same sestions.
saltstack/salt pull request #48244
Opened 2018-06-21 14:24 UTC by slivik

### What does this PR do?
Fixes `apache.configfile` so that it allows to create Apache config files with multiple same section containers. It is possible to define structure like before (through a dict) and newly also through lists which allows sections with same name, e.g. `<Directory>`. Behavior is backward compatible and the new one is described in updated doc section in `apache` state module.

As side-effect it also fixes issue that when two structures were used at the same salt state run, the second structure was wrong since the previous run removed all `this:` items. So intended `<Directory /some/path>` was always generated as `<Directory>`.

### What issues does this PR fix or reference?
[#38306 - The `apache.configfile` state does not allow multiple same sections](https://github.com/saltstack/salt/issues/38306)

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-06-21 18:29 UTC, rallytime reviewed
I realize you might be following what's already in the module, but is there some reason we're using `print` statements instead of `log`?

2018-06-21 18:29 UTC, rallytime commented on salt/states/apache.py
> +.. versionchanged:: 2018.3
This should be `Fluorine`.

2018-06-22 01:09 UTC, gtmanfred commented
Print is used to write to the config file. I will look at this tomorrow or Monday and review it.

2018-06-25 22:07 UTC, gtmanfred requested changes
I think this looks fine, but I would really like to see at least a unittest added for both this version and the old version to verify that we are not breaking backwards compatibility.

2018-07-11 13:22 UTC, rallytime approved these changes

2018-07-11 13:26 UTC, gtmanfred approved these changes

2018-07-11 17:41 UTC, merged