Virt init improvements
saltstack/salt pull request #48261
Opened 2018-06-22 08:29 UTC by cbosdo

### What does this PR do?

This PR makes `virt.init` more flexible for users. Rather than forcing all domain configuration in the minion configuration, `virt.init` now allows defining and/or overriding default disks and network interfaces. It also allows more graphic types than the VNC.

As an effort to understand `virt.init` before modifying it, the virt documentation has been improved a lot.

### What issues does this PR fix or reference?

Issue #48085 is also fixed in this PR.

### Previous Behavior

See description.

### New Behavior

See description

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-06-22 19:25 UTC, rallytime requested changes
Since I merged your other PR, this will need a rebase first.

2018-06-25 13:27 UTC, gtmanfred approved these changes

2018-06-25 14:10 UTC, cbosdo commented
hum... locale problems, I'll make the test more robust

2018-06-25 14:56 UTC, cbosdo commented
@rallytime Should be fixed by now the expected string is now computed based on the locale...

2018-06-25 20:14 UTC, rallytime commented
re-run py

2018-06-26 13:41 UTC, merged