Back-port #48193 to 2017.7
saltstack/salt pull request #48295
Opened 2018-06-25 14:27 UTC by rallytime

Back-port #48193 to 2017.7

Refs #42659

2018-06-25 14:44 UTC, gtmanfred approved these changes

2018-06-25 17:01 UTC, DmitryKuzmenko requested changes
Sorry my fault. I've missed this in the original PR. =(

2018-06-25 17:01 UTC, DmitryKuzmenko commented on salt/netapi/rest_tornado/saltnado.py
> +        min_wait_time = Future().set_result(True)
This shall be:
```python
min_wait_time = Future()
min_wait_time.set_result(True)
```

The same is in the original PR.

2018-06-25 17:01 UTC, DmitryKuzmenko commented on salt/netapi/rest_tornado/saltnado.py
> +        min_wait_time = Future().set_result(True)
It's the reason of the tests failures.

2018-06-25 17:09 UTC, DmitryKuzmenko commented on salt/netapi/rest_tornado/saltnado.py
> +        min_wait_time = Future().set_result(True)
@jacksontj could you please confirm my point?

2018-06-26 06:34 UTC, DmitryKuzmenko approved these changes

2018-06-26 23:42 UTC, merged