Handle packages with multiple versions properly with zypper
saltstack/salt pull request #48294
Opened 2018-06-25 14:21 UTC by meaksh

### What does this PR do?
This PR fixes some issues introduced after merging https://github.com/saltstack/salt/pull/47678 . 

### What issues does this PR fix or reference?
- Exclude `gpg-pubkey` entries from `zypper.list_pkg`
- Fix `changes` on `pkg.installed` output when dealing with packages with multiple versions installed.
- Fix `changes` on `pkg.installed` output when packages name include "arch".

### Previous Behavior
On a SUSE systems, given this SLS state file: 
```yaml
my_tests:
  pkg.installed:
    - pkgs:
      - kernel-default.x86_64: 4.4.138-94.39.1
      - iotop.noarch: 0.6-3.10
      - apache2.x86_64: 2.4.23-29.18.2
      - apache2-doc: 2.4.23-29.18.2
      - perseus-dummy.i586: 1.1-1.1
      - orion-dummy: 1.1-1.1
```

Applying `my_tests` state will produce:
```yaml
local:
----------
          ID: my_tests
    Function: pkg.installed
      Result: True
     Comment: 6 targeted packages were installed/updated.
     Started: 16:05:56.124001
    Duration: 24153.705 ms
     Changes:   
              ----------
              apache2:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              apache2-doc:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              apache2-prefork:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              gpg-pubkey:
                  ----------
                  new:
                      e6e5a213-5b291a5f
                  old:
                      39db7c82-5847eb1f,8a7c64f9-5aaa93ca,e6e5a213-5b291a5f
              iotop:
                  ----------
                  new:
                      0.6-3.10
                  old:
              orion-dummy:
                  ----------
                  new:
                      1.1-1.1
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  24.154 s
```

Notice that `perseus-dummy.x586` package, as well as `kernel-default`, are actually installed but not reported on `changes` (and they should). Also the non-desired `gpg-pubkey` entry is not excluded from `changes` since it's not actually a real package.

### New Behavior
Given the same SLS file:

```yaml
local:
----------
          ID: my_tests
    Function: pkg.installed
      Result: True
     Comment: 6 targeted packages were installed/updated.
     Started: 16:14:13.955445
    Duration: 24761.717 ms
     Changes:   
              ----------
              apache2:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              apache2-doc:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              apache2-prefork:
                  ----------
                  new:
                      2.4.23-29.18.2
                  old:
              iotop:
                  ----------
                  new:
                      0.6-3.10
                  old:
              kernel-default:
                  ----------
                  new:
                      4.4.138-94.39.1,4.4.73-5.1
                  old:
                      4.4.73-5.1
              orion-dummy:
                  ----------
                  new:
                      1.1-1.1
                  old:
              perseus-dummy.i586:
                  ----------
                  new:
                      1.1-1.1
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  24.762 s
```

Now, both `perseus-dummy.i586` and `kernel-default` are successfully reported on `changes`.

### Tests written?

No

### Commits signed with GPG?

Yes

2018-06-25 14:31 UTC, isbm requested changes
Tests?

2018-06-25 15:28 UTC, meaksh commented
@isbm - Right, currently working on them. I'll ping you back when I uploaded them.

2018-06-26 09:50 UTC, meaksh commented
@isbm - Tests are pushed now. This should be ready now for review. Thanks :+1:

2018-07-02 14:30 UTC, isbm requested changes
@meaksh very nice! One little nitpick and good to go.

2018-07-02 14:30 UTC, isbm commented on salt/modules/zypper.py
> +            if pkginfo is not None:
```python
if pkginfo:
    ...
```

2018-07-03 12:20 UTC, isbm approved these changes
@meaksh thanks!

2018-07-03 15:07 UTC, rallytime approved these changes

2018-07-03 15:08 UTC, merged