nilrt_ip: network module for older nilrt
saltstack/salt pull request #48400
Opened 2018-07-02 09:50 UTC by alexvasiu

Make nilrt_ip compatible with older nilrt. Since connman isn't pressent
in older nilrt distros, use available tools (nirtcfg, ip, ifconfig)
instead, to make this module partial compatible with newer nilrt part.
The functionality available for older nilrt distros is:
    - enable/disable the interfaces
    - get details about sigle interface
    - information about all interfaces
    - set dhcp with linklocal fallback
    - set dhcp only
    - set linklocal only
    - set static configuration

Signed-off-by: Heghedus Razvan <razvan.heghedus@ni.com>
Signed-off-by: Alexandru Vasiu <alexandru.vasiu@ni.com>
Signed-off-by: Rares POP <rares.pop@ni.com>

2018-07-05 08:21 UTC, alexvasiu commented on salt/modules/nilrt_ip.py
>      import pyconnman
I changed all **third-party** imports

2018-07-11 13:31 UTC, alexvasiu commented
@gtmanfred  May you please take a look at this ?

2018-07-11 13:33 UTC, gtmanfred commented on salt/modules/nilrt_ip.py
> +    configparser = None
This still needs to be imported from six.

`from salt.ext.six.moves import configparser`

Because the name changed between py2 and py3

2018-07-11 13:35 UTC, gtmanfred requested changes
configparser needs to still be imported from salt.ext.six.moves.

Otherthan that, this looks fine

2018-07-11 17:39 UTC, gtmanfred commented on salt/modules/nilrt_ip.py
> +from salt.ext.six.moves import map, range
so, you don't need a try except loop for configparser, it just needs to be added to the imports on this line.

2018-07-11 17:40 UTC, gtmanfred requested changes

2018-07-11 17:40 UTC, gtmanfred commented on salt/modules/nilrt_ip.py
> +    configparser = None
This will be unneeded.

2018-07-11 17:40 UTC, gtmanfred commented on salt/modules/nilrt_ip.py
> +        _assume_condition(configparser, 'The python package configparser is not installed')
again, unneeded, because it will always be in salt.ext.six.moves

2018-07-12 15:32 UTC, alexvasiu commented
@gtmanfred I changed that import for `configparser` and I removed all checks for it

2018-07-12 15:35 UTC, gtmanfred approved these changes

2018-07-12 16:59 UTC, merged