Improve handling of identifying json output (#43138)
saltstack/salt pull request #48492
Opened 2018-07-09 21:52 UTC by wyardley

### What does this PR do?
Rather than look for [ or { at the beginning of a line, it looks for equality. Since the JSON output of `npm install` seems to have the first character on its own, this seems to work, at least for the npm version I looked at -- however, I'm open to better / other approaches that would be better. I think the previous approach was a bit too limited, since there could be other output in the future that matches `^[` or `^{`.

### What issues does this PR fix or reference?
Idempotency issue - first run will "fail" with an error, even when packages get installed, if the output has a string like:
```[grpc] Success: "/usr/lib/node_modules/@google-cloud/monitoring/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote
```
More details in #43138 

### Tests written?
No - but willing to write one if you let me know where it should be go and what it should be modeled on. I threw together a quick one, but not sure if it's right.

### Commits signed with GPG?

Yes

2018-07-10 01:58 UTC, wyardley commented
I think the tests will need to be adjusted more than I realized, I'll take a look at it

https://github.com/saltstack/salt/blob/develop/tests/unit/modules/test_npm.py#L48-L49 is mocking the output of the response, right? Or am I misunderstanding? Is there a convention for mocking a long payload? I see some stuff in the tests building an array and then doing `'\n'.join(array)`, but that would get pretty ugly (vs. a heredoc) for something like this. I don't see a fixtures directory either?

Even going pretty far back (e.g., npm 2), the format is somewhat different, and also pretty predictable.

```
root@16b37a02a7bc:~# ./node_modules/.bin/npm install --json --silent --global '@google-cloud/monitoring@^0.4.1' 
[grpc] Success: "/usr/lib/node_modules/@google-cloud/monitoring/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote
[
  {
    "name": "@google-cloud/monitoring",
    "version": "0.4.1",
```

2018-07-10 05:08 UTC, wyardley commented on tests/unit/modules/test_npm.py
> -            with patch.object(salt.utils.json, 'loads', mock_err):
I'm not sure if dropping this second patch is better or not, seems like it shouldn't be needed here?

2018-07-10 05:08 UTC, wyardley commented on tests/unit/modules/test_npm.py
> +        mock = MagicMock(return_value={'retcode': 0, 'stderr': '',
I think stderr should typically empty on the successful runs?

2018-07-13 19:29 UTC, terminalmage requested changes
We already have a function that should make this much easier, `salt.utils.json.find_json()`: 

https://github.com/saltstack/salt/blob/develop/salt/utils/json.py#L31-L52

2018-07-14 00:31 UTC, wyardley commented
@terminalimage thanks, I’ll give that a shot. Do the changes to the tests look correct, and should I try to add any additional coverage?

2018-07-14 04:01 UTC, wyardley commented
@terminalmage: how's that look?

2018-07-14 04:57 UTC, wyardley commented on salt/modules/npm.py
> +    result = __salt__['cmd.run_all'](cmd,
I figure this is as good a time as any to switch this to be more vertical, but I can put it back if you'd prefer.

2018-07-18 15:28 UTC, terminalmage requested changes
It doesn't look like there's a test case where there is output before the JSON, which is what your PR is designed to fix. Can you add one more test which does this so that we can confirm that using `salt.utils.json.find_json()` works for that use case?

[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-18 19:02 UTC, closed without merging