Add salt_api execution module to allow a minion to run a runner
saltstack/salt pull request #48543
Opened 2018-07-12 12:25 UTC by loverend

### What does this PR do?

`salt.modules.saltutil.runner` allows a minion to run a runner but only
if the minion is running on the master. This module adds the ability for
any minion to be able to run a runner.

### What issues does this PR fix or reference?

n/a

### Tests written?

No

### Commits signed with GPG?

Yes

2018-07-13 20:02 UTC, gtmanfred requested changes
Why is this needed?

This is what publish.runner is for.

https://docs.saltstack.com/en/2017.7/ref/modules/all/salt.modules.publish.html#salt.modules.publish.runner

[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-13 20:04 UTC, gtmanfred commented on salt/modules/salt_api.py
> +    if async is True:
If this does get accepted, async cannot be a word used in the code, because it is a reserved word in python 3.7.

2018-07-18 22:59 UTC, cachedout commented
I'm with @gtmanfred here. I'd be extremely hesitant to accept this PR. :-/

2018-07-19 06:45 UTC, loverend commented
I fine with that. I will use `publish.runner`. Thanks.

2018-07-19 06:45 UTC, closed without merging