git.latest: Add support for shallow-cloning tags
saltstack/salt pull request #48596
Opened 2018-07-15 16:26 UTC by pritambaral

### What does this PR do?

Adds support for specifying a tag in the `rev` option when `depth` is used
with `git.latest`.

For long, we've supported shallow clones of branches only, since git-clone
supports only a `--branch` option but no `--tag` options.

Turns out, the same `--branch` option [supports tag names since Git
1.8.0](https://git-scm.com/docs/git-clone/1.8.0#git-clone---branchltnamegt) (released Oct 2012), so it's a good idea for us to support it too.

### Previous Behavior

Only branch names in `rev` allowed when `depth` is used.

### New Behavior

Tag names also allowed in `rev` when `depth` is used.

### Tests written?

No

### Commits signed with GPG?

Yes

2018-07-18 16:26 UTC, terminalmage requested changes
One minor documentation change is needed.

[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-19 05:58 UTC, pritambaral commented on salt/states/git.py
> +        compatible with revision IDs.
Clarfication added in rebase

2018-07-20 14:40 UTC, rallytime approved these changes

2018-07-20 14:54 UTC, terminalmage approved these changes
[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-20 16:32 UTC, merged