Thread safe loader 2
saltstack/salt pull request #48598
Opened 2018-07-16 00:20 UTC by mattp-

### What does this PR do?
this is a version of #45782 with latest develop merged in. I've not made any changes other than resolving merge conflicts; the original jenkins results have aged out so I'm creating this to re-run. If I figure out a solution I'll send PR to @smarsching and close this.

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-07-16 04:37 UTC, damon-atkins commented
Go Go Jenkins!

2018-07-16 09:11 UTC, DmitryKuzmenko approved these changes
LGTM

2018-07-16 16:08 UTC, gtmanfred requested changes
LGTM, needs the versionadded references updated to Fluorine.

[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-16 16:08 UTC, gtmanfred commented on salt/utils/msgpack.py
> +    .. versionadded:: Oxygen
Fluorine

2018-07-16 16:08 UTC, gtmanfred commented on salt/utils/msgpack.py
> +    .. versionadded:: Oxygen
Fluorine

2018-07-16 16:08 UTC, gtmanfred commented on salt/utils/msgpack.py
> +    .. versionadded:: Oxygen
Fluorine

2018-07-16 16:08 UTC, gtmanfred commented on salt/utils/msgpack.py
> +    .. versionadded:: Oxygen
Fluorine

2018-07-16 16:08 UTC, gtmanfred commented on salt/utils/thread_local_proxy.py
> +..versionadded:: Oxygen
Fluorine

2018-07-16 16:10 UTC, gtmanfred commented
Also, looks like there are some pylint warnings in salt/state.py https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48598/1/warnings52Result/

2018-07-16 21:57 UTC, cachedout commented on salt/transport/zeromq.py
> +
I'm confused about the relationship between loader thread-safety and these proposed changes to the transports.

2018-07-16 22:00 UTC, mattp- commented
Sorry, that accidentally snuck in. It's from my other PR that I put on
develop, not a feature branch. You can ignore.

On Mon, Jul 16, 2018, 5:57 PM Mike Place <notifications@github.com> wrote:

> *@cachedout* commented on this pull request.
> ------------------------------
>
> In salt/transport/zeromq.py
> <https://github.com/saltstack/salt/pull/48598#discussion_r202837848>:
>
> > @@ -433,7 +433,14 @@ def __del__(self):
>      def connect(self):
>          if not self.auth.authenticated:
>              yield self.auth.authenticate()
> -        self.publish_port = self.auth.creds['publish_port']
> +
>
> I'm confused about the relationship between loader thread-safety and these
> proposed changes to the transports.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/48598#pullrequestreview-137612747>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AACtVkRPslxi3_2VhSmeGf2YrC2kBLr2ks5uHQxLgaJpZM4VQclz>
> .
>

2018-07-16 22:07 UTC, thatch45 approved these changes

2018-07-16 22:11 UTC, cachedout commented
@isbm Does anybody on @saltstack/team-suse want to review this? We're getting close to merging this in.

2018-07-16 22:12 UTC, cachedout commented
@mattp- Can you rebase against the head of develop so we have only the related changes? That should clear out those transport changes so we know exactly what we're dealing with here.

2018-07-16 22:59 UTC, mattp- commented
@cachedout yep will do shortly. to be clear I haven't made any changes yet; though I did notice one incompatibility between how data.serializers.msgpack and data.utils.msgpack is handled that I need to look at more.

2018-07-16 23:11 UTC, mattp- commented
unassociated commit removed

2018-07-16 23:12 UTC, cachedout commented
@mattp- Cool. We also need the issues raised by @gtmanfred resolved before we can move forward, please.

2018-07-17 06:57 UTC, isbm approved these changes
LGTM

2018-07-23 21:36 UTC, cachedout commented
I spent some time looking at this today and I'm honestly not sure what's happening. It's failing in different ways on different platforms and, oddly enough, it seems to work just fine on my development machine.

2018-07-25 14:22 UTC, gtmanfred approved these changes

2018-11-27 14:47 UTC, mattp- commented
closing in favor of #50648

2018-11-27 14:47 UTC, closed without merging