Discard unicode type
saltstack/salt pull request #48604
Opened 2018-07-16 13:40 UTC by isbm

### What does this PR do?

Bugfix

### What issues does this PR fix or reference?

Removes `u''` in front of displayed strings in CLI

### Previous Behavior
```
 -l LOG_LEVEL, --log-level=LOG_LEVEL
                        Console logging log level. One of u'all', u'garbage',
                        u'trace', u'debug', u'profile', u'info', u'warning',
                        u'error', u'critical', u'quiet'. Default: 'warning'.
    --log-file=LOG_FILE
                        Log file path. Default: '/var/log/salt/master'.
    --log-file-level=LOG_LEVEL_LOGFILE
                        Logfile logging log level. One of u'all', u'garbage',
                        u'trace', u'debug', u'profile', u'info', u'warning',
                        u'error', u'critical', u'quiet'. Default: 'warning'.
```

### New Behavior

```
 -l LOG_LEVEL, --log-level=LOG_LEVEL
                        Console logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'profile', 'info', 'warning',
                        'error', 'critical', 'quiet'. Default: 'warning'.
    --log-file=LOG_FILE
                        Log file path. Default: '/var/log/salt/master'.
    --log-file-level=LOG_LEVEL_LOGFILE
                        Logfile logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'profile', 'info', 'warning',
                        'error', 'critical', 'quiet'. Default: 'warning'.
```

### Tests written?

No

2018-07-16 14:15 UTC, rallytime approved these changes

2018-07-16 21:45 UTC, cachedout approved these changes

2018-07-18 15:07 UTC, terminalmage requested changes
The proper fix for this would be to fix the `help` param for both `--log-level` and `--log-file-level` in `salt/utils/parsers.py`. For some weird reason both of them use `repr()`, which is what is actually causing this.

My only guess is that `repr()` was used in order to ensure that each log level would be quoted, but IMO A) that's an awful reason to use `repr()`, and B) the quotes around each log level seem completely unnecessary to me.

Therefore I would change

```python
', '.join([repr(l) for l in log.SORTED_LEVEL_NAMES])
```

to

```python
', '.join(log.SORTED_LEVEL_NAMES)
```

in both places where it occurs in `salt/utils/parsers.py`.

This also should have been opened against the `2018.3` branch to avoid the need to backport it.

Might be better to close this and open a new PR with the suggested change, against `2018.3`.

2018-07-26 21:38 UTC, rallytime commented
@isbm Did you see the comments above?

2018-07-31 08:13 UTC, isbm commented
@rallytime ah, right. Yes. I am preparing another PR in favour of this one.

2018-07-31 08:13 UTC, closed without merging