Excluding relative dirs in state.file.retention_schedule
saltstack/salt pull request #48662
Opened 2018-07-18 21:06 UTC by slaws

### What does this PR do?
It makes salt.state.file.retention_schedule ignoring relative directories `.` and `..` when using it without specifying a strpformat (using getmtime() )

### What issues does this PR fix or reference?
This commit should resolve #48637

### Previous Behavior
`.` and `..` were treated like the other files

### New Behavior
`.` and `..` are ignored.

### Tests written?

No

### Commits signed with GPG?

Yes

2018-07-19 08:11 UTC, rares-pop commented on salt/states/file.py
> +        if f == '.' or f == '..':
do we need this for get_file_time_from_strptime() too?

2018-07-20 14:31 UTC, terminalmage requested changes
[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-20 14:31 UTC, terminalmage commented on salt/states/file.py
> +            return (None,None)
You need a space after the comma, otherwise pylint will complain.

2018-07-31 15:44 UTC, terminalmage approved these changes
[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-31 16:15 UTC, merged