[2018.3] Fix mine.get not returning data
saltstack/salt pull request #48765
Opened 2018-07-25 10:37 UTC by FedericoCeratto

### What does this PR do?
Implements a workaround for #48020
Ported from https://github.com/openSUSE/salt/pull/102

### What issues does this PR fix or reference?

#48020

### Previous Behavior
mine.get would return no nodes

### New Behavior
mine.get returns the correct nodes

### Tests written?

No

### Commits signed with GPG?

No

2018-07-25 14:42 UTC, gtmanfred reviewed
This was added in https://github.com/saltstack/salt/pull/44890

I would like @terminalmage to look at it, since that was originally added by him.

2018-07-26 19:31 UTC, terminalmage requested changes
This is a good change. I mistook the cause for an error that is fired later on in the function when `salt.cmd` is used.

To fix the _actual_ issue I was trying to solve, can you please add the following after `pki_cache_fn` is defined? (line 243):

```python
try:
    os.makedirs(os.path.dirname(pki_cache_fn))
except OSError:
    pass
```

[![blind-review](https://github.com/blindreviews3.png)](https://github.com/zombie/blind-reviews "Review performed in blind mode")

2018-07-27 09:49 UTC, FedericoCeratto commented
Updated and rebased.

2018-07-27 13:36 UTC, terminalmage approved these changes
Excellent!

2018-07-27 18:01 UTC, merged

2018-08-02 20:44 UTC, cachedout commented
@terminalmage This is a partial revert of #44890.