Check dmidecoder executable on each "smbios" call to avoid race condition
saltstack/salt pull request #48781
Opened 2018-07-26 16:31 UTC by meaksh

### What does this PR do?
This PR fixes a race condition happening during core grains generation in case `dmidecode` or `smbios` are installed/removed during `salt-minion` execution.

As described on #35505, `smbios.DMIDECODER` is fixed to the `dmidecode` or `smbios` executables, and this is happening only **once while the module is loaded**. Then there are some calls to `smbios.get` performed while calculating the "core" grains which produces a race condition in case the results of `salt.utils.path.which_bin(['dmidecode', 'smbios'])` changes during execution time.

### What issues does this PR fix or reference?
Hopefully fixes https://github.com/saltstack/salt/issues/35505

### Previous Behavior
The situation appears in case neither `dmidecode` nor `smbios` are installed at the time of `salt-minion` is started, therefore `smbios.DMIDECODER` is set to `None`. Then, at some point, either `dmidecode` or `smbios` are installed on the minion and eventually the grains will be recalculated.
At this particular moment, when the "core" grains are being recalculated, https://github.com/saltstack/salt/blob/2018.3/salt/grains/core.py#L2310 is checking again if executables are now available, and if so, it would produce a call to `smbios.get` which will crash since `smbios.DMIDECODER` is set to `None`:

```
ERROR: Unable to run command '['None', '-s', 'bios-version']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -2, 'env': {'LC_NUMERIC': 'C', 'NOTIFY_SOCKET': '/run/systemd/notify', 'LC_MESSAGES': 'C', 'LC_IDENTIFICATION': 'C', 'LC_MONETARY': 'C', 'LC_COLLATE': 'C', 'LC_CTYPE': 'C', 'LC_ADDRESS': 'C', 'LC_MEASUREMENT': 'C', 'LC_TELEPHONE': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LC_TIME': 'C'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'cwd': '/root'}', reason: [Errno 2] No such file or directory
```

### New Behavior
Now `smbios.DMIDECODER` is refreshed on each `smbios` module call to prevent the race condition with the "core" grains. Besides of that, this PR introduces also a comprehensive error message in case of crashing:

```
2018-07-26 17:04:40,063 [salt.modules.smbios:337 ][ERROR   ][16331] SMBIOS: neither dmidecode nor smbios found!
```

### Tests written?

No

### Commits signed with GPG?

Yes

2018-07-26 20:40 UTC, rallytime commented
@meaksh Can you fix up the lint failures listed here?

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48781/1/warnings52Result/package.2029219534/

2018-07-27 08:14 UTC, meaksh commented
@rallytime - pylint issues fixed :+1:

2018-07-27 14:36 UTC, isbm requested changes
I will follow-up on this PR differently.

2018-07-27 14:36 UTC, isbm commented on salt/modules/smbios.py
> +    DMIDECODER = salt.utils.path.which_bin(['dmidecode', 'smbios'])
Why there is a need of this global variable at all? And this function is also not needed. I would discard this PR entirely and just refactor it the way that `which_bin` is just called.

2018-07-29 19:51 UTC, isbm commented
@rallytime Please close this. There is a better version of it here: https://github.com/saltstack/salt/pull/48814

2018-07-30 14:55 UTC, rallytime commented
Closed in favor of #48814

2018-07-30 14:55 UTC, closed without merging