Add module for Cisco IOS configuration manipulation
saltstack/salt pull request #48859
Opened 2018-08-01 13:22 UTC by mirceaulinic

### What does this PR do?

Adds a new module for Cisco IOS style configuration manipulation, and use the functionality into the NAPALM module to have the features directly applied on the configuration(s) of the managed device.

2018-08-01 13:44 UTC, rallytime requested changes
I have 2 small requests. Thank you for writing tests for this! 🎉 

There's also a pylint warning.

2018-08-01 13:44 UTC, rallytime commented on salt/modules/iosconfig.py
> +from collections import OrderedDict
This should use the `OrderedDicrt` from `salt.utils.odict`.

2018-08-01 13:44 UTC, rallytime commented on tests/unit/modules/test_iosconfig.py
> +from collections import OrderedDict
Same comment here. :)

2018-08-01 16:04 UTC, mirceaulinic commented
Wasn't aware of `salt.utils.odict` (or probably I forgot) - should be fixed via https://github.com/saltstack/salt/pull/48859/commits/062f161a7d61bd21eaded5ab3688deebb784f439 @rallytime.

2018-08-01 16:47 UTC, rallytime commented
@mirceaulinic Can you fix the lint error too? 

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48859/2/warnings52Result/

2018-08-02 10:44 UTC, mirceaulinic commented
Alright, seems like https://github.com/saltstack/salt/pull/48859/commits/ca254fbdfe224bbeb9ef5fa639a42e6663fb2241 fixed the lint.

2018-08-02 11:28 UTC, rallytime approved these changes

2018-08-02 11:28 UTC, merged