Add cmd module integration tests for windows and fix space in path issue
saltstack/salt pull request #48866
Opened 2018-08-01 19:09 UTC by Ch3LL

### What does this PR do?
Adds the cmdmod module integration tests to run on windows and fixes an issue on windows when there is a space in the path name of the `cwd` argument.

Given this state file:

```
test:
  cmd.script:
    - source: salt://test.py
    - cwd: "c:\\test 2"
    - args: 'saltine crackers biscuits=yes'
```

When run I see this error:

```
----------
          ID: test
    Function: cmd.script
      Result: False
     Comment: Command 'test' run
     Started: 12:11:28.997000
    Duration: 454.0 ms
     Changes:
              ----------
              pid:
                  38548
              retcode:
                  1
              stderr:
                  '"c:\test' is not recognized as an internal or external command,
                  operable program or batch file.
              stdout:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time: 454.000 ms
PS C:\testing>
```

If i use the powershell shell it works:

```
test:
  cmd.script:
    - source: salt://test.ps1
    - cwd: "c:\\test 2"
    - args: 'saltine crackers biscuits=yes'
    - shell: powershell
```

```
local:
----------
          ID: test
    Function: cmd.script
      Result: True
     Comment: Command 'test' run
     Started: 12:14:27.200000
    Duration: 954.0 ms
     Changes:
              ----------
              pid:
                  39572
              retcode:
                  0
              stderr:
              stdout:
                  hello

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
```

The reason this is occurring is because it tries to escape the quotes around the command leaving hte space unescaped. So the resulting command is this:

`chcp 437 > nul & ^"c:\test 2\__salt.tmp.al96jv.py^"` and if run in cmd.exe:

```
C:\Users\Administrator>chcp 437 > nul & ^"c:\test 2\__salt.tmp.al96jv.py^"
'"c:\test' is not recognized as an internal or external command,
operable program or batch file.
```

Also fixes an issue when it it attempts to clean the temp file here: https://github.com/saltstack/salt/blob/v2017.7.7/salt/modules/cmdmod.py#L2141

it cannot delete the temp file because it quotes the path `'"<path>"'` and whne it checks to see if its a valid path it fails. So this ensures we are using the inital path created from here: https://github.com/saltstack/salt/blob/v2017.7.7/salt/modules/cmdmod.py#L2084

Also this PR changes the expected return in windows on the tests so I could use some review if those returns are expected behavior or not.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44997

### Tests written?

Yes - adds tests and fixes something a test found

### Commits signed with GPG?

Yes

2018-08-01 22:56 UTC, twangboy requested changes

2018-08-01 22:56 UTC, twangboy commented on salt/utils/win_functions.py
>      '''
Please add this new parameter to the docs for this function

2018-08-02 01:16 UTC, damon-atkins commented
Ping @ciiqr

2018-08-02 01:30 UTC, damon-atkins commented
Why do we need `chcp 437`?  What is the background with this?

2018-08-02 23:42 UTC, twangboy approved these changes

2018-08-03 18:03 UTC, dwoz approved these changes

2018-08-03 21:03 UTC, merged