Add new google_chat module
saltstack/salt pull request #48919
Opened 2018-08-03 14:38 UTC by loverend

### What does this PR do?

Add a new `google_chat` module which allows you to send a message to a google chat room.

### What issues does this PR fix or reference?

N/A

### New Behavior
Send a message to a google chat room

### Tests written?

No

### Commits signed with GPG?

Yes

2018-08-03 15:45 UTC, cachedout requested changes
Excellent! Before we merge this, would you mind adding information about this new feature to the release notes?

2018-08-03 15:46 UTC, gtmanfred requested changes
Just one nitpick change.

Otherwise this looks good.

2018-08-03 15:46 UTC, gtmanfred commented on salt/modules/google_chat.py
> +    result = salt.utils.http.query(url,
instead of importing salt.utils.http, please use `__utils__['http.query']()`

2018-08-03 15:48 UTC, rallytime commented on salt/modules/google_chat.py
> +from __future__ import absolute_import
Can you add `print_function` and `unicode_literals` to this `__future__` import? We need that for PY2/PY3 compatibility. :)

2018-08-03 15:55 UTC, terminalmage approved these changes

2018-08-03 16:04 UTC, garethgreenaway approved these changes
Awesome! :grin:

2018-08-03 16:19 UTC, rallytime commented
@loverend If you could add this to the [Fluorine release notes](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/fluorine.rst) we can get this in pending tests. :)

Thanks for this addition!

2018-08-03 16:28 UTC, loverend commented
Added to release notes. There wasn't a `new modules` section like in previous release notes, so added this.

2018-08-03 17:09 UTC, rallytime approved these changes

2018-08-03 21:06 UTC, rallytime commented
@loverend Some of your new tests are having some trouble here. Can you take a look?

https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-48919/5/

2018-08-06 15:09 UTC, loverend commented
All tests now pass. I have addressed all comments. Please let me know if there are any further changes required.

2018-08-06 15:15 UTC, gtmanfred approved these changes
Awesome! thanks for this! looks great.

2018-08-06 19:49 UTC, merged