Python 3 related fix in highstate_return.py
saltstack/salt pull request #48997
Opened 2018-08-08 11:21 UTC by AVeenstra

In Python 3 key sets of dicts no longer support indexing:
`TypeError: 'dict_keys' object does not support indexing`

### What does this PR do?
It makes the highstate returner function under Python 3.

### What issues does this PR fix or reference?
Could not find any.

### Previous Behavior
```
2018-08-08 11:37:53,693 [salt.utils.schedule:740 ][ERROR   ][26560] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 732, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/highstate_return.py", line 481, in returner
    _produce_output(report, failed, setup)
  File "/usr/lib/python3/dist-packages/salt/returners/highstate_return.py", line 434, in _produce_output
    _generate_html(report, string_file)
  File "/usr/lib/python3/dist-packages/salt/returners/highstate_return.py", line 270, in _generate_html
    _generate_html_table(data, out, 0)
  File "/usr/lib/python3/dist-packages/salt/returners/highstate_return.py", line 190, in _generate_html_table
    name = subdata.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

### New Behavior
You get a mail about the highstate. Also when using Python 2.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-08-08 13:25 UTC, rallytime approved these changes

2018-08-08 19:13 UTC, terminalmage requested changes

2018-08-08 19:13 UTC, terminalmage commented on salt/returners/highstate_return.py
> +                value = list(subdata.values())[0]
How about using a generator, like so?

```python
name = next(six.iterkeys(subdata))
value = next(six.itervalues(subdata))
```

2018-08-08 19:56 UTC, AVeenstra commented on salt/returners/highstate_return.py
> +                value = list(subdata.values())[0]
Now using an iterator as requested

2018-08-09 16:36 UTC, terminalmage approved these changes

2018-08-09 17:57 UTC, merged