Add baremetal server support
saltstack/salt pull request #49101
Opened 2018-08-13 21:24 UTC by aajdinov

### What does this PR do?
This PR adds `avail_baremetal_images` function for listing baremetal server appliances, `baremetal_models` functions for listing baremetal models, and support for creating baremetal servers.

### What issues does this PR fix or reference?
None

### New Behavior
* List baremetal server appliances
* List baremetal models
* Create baremetal server
 
### Tests written?
No

### Commits signed with GPG?
Yes

2018-08-14 13:24 UTC, gtmanfred requested changes

2018-08-16 18:45 UTC, aajdinov commented on salt/cloud/clouds/oneandone.py
> +def avail_baremetal_images(conn=None, call=None):
@gtmanfred Thank you for your feedback. I've removed the `q=CLOUD' qurey, so it will include the baremetal images as well.

2018-08-16 18:46 UTC, gtmanfred commented on salt/cloud/clouds/oneandone.py
> +def avail_baremetal_images(conn=None, call=None):
perfect

2018-08-16 18:46 UTC, gtmanfred approved these changes

2018-08-18 00:39 UTC, gtmanfred approved these changes

2018-08-18 00:39 UTC, merged