allow for using multiple on* requisites on the same state
saltstack/salt pull request #49131
Opened 2018-08-15 15:22 UTC by gtmanfred

### What does this PR do?
onchanges and onfail in this case

### What issues does this PR fix or reference?
Fixes #49120

### Previous Behavior
If onchanges and onfail were both set, if the onfail state did not fail but had changes, checking onchanges was skipped.

### New Behavior
If onfail and onchanges are both specified, and either of them are `met` it will run the state.

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-08-17 14:53 UTC, cachedout requested changes
Some lint errors snuck in here.

2018-08-17 14:54 UTC, gtmanfred commented
There are also some tests that need to be fixed.

2018-08-20 18:15 UTC, thatch45 approved these changes
This is the perfect fix for this

2018-08-20 18:26 UTC, cachedout approved these changes

2018-08-21 13:11 UTC, gtmanfred reviewed
The problem is that now, the other requisites are going to behave differently because `met` has been returned, which is causing a bunch of tests to fail.

https://github.com/saltstack/salt/blob/2018.3/salt/state.py#L2462-L2662

I can change these tests so that they pass.  But I think this is actually going to require reworking how requisites resolution is handled in the develop branch.

thoughts @cachedout @thatch45 @saltstack/team-core ?

2018-08-28 13:37 UTC, gtmanfred commented
So, basically we have a whole set of if, elif, elif, else trees, and in order to handle this situation better, we need to change it to a series of if statements, so that more then one requisite can be on the same state chunk.

2018-09-28 14:31 UTC, gtmanfred commented
It can be closed.  I updated the issue, it will need to be reworked how we handle counting the different requisites so that more than one can be applied at the same time.

2018-09-28 14:31 UTC, closed without merging