Add timeout parameter to win_service functions
saltstack/salt pull request #49144
Opened 2018-08-15 22:23 UTC by twangboy

### What does this PR do?
Adds a timeout parameter to the following functions in win_service:

- start
- stop
- restart
- delete

Fix some documentation formatting issues

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/48163

### Tests written?
No

### Commits signed with GPG?
Yes

2018-08-16 02:34 UTC, damon-atkins requested changes
Please use  "time code" for timeout rather than attempts

2018-08-16 02:34 UTC, damon-atkins commented on salt/modules/win_service.py
> +            and attempts <= timeout:
The time out is doco as seconds not attempts please use the following code 

```
    end_t = time.time() + timeout 
    while info(name)['Status'] in ['Start Pending', 'Stopped'] \
          and time.time() < end_t:
        time.sleep(1)
```

2018-08-16 02:34 UTC, damon-atkins commented on salt/modules/win_service.py
> +            and attempts <= timeout:
dito

2018-08-16 02:34 UTC, damon-atkins commented on salt/modules/win_service.py
> +    while name in get_all() and attempts <= timeout:
dito

2018-08-16 05:06 UTC, damon-atkins commented
open a PR against your fix.

2018-08-17 02:33 UTC, damon-atkins commented on salt/modules/win_service.py
> +        wait_time = info_results['Status_WaitHint'] / 1000
Looks like I got this code slightly wrong.
Should not have the / 1000   see the else which should do this. This way we cover the off chance wait hint is 0.

``
else:
           wait_time = wait_time / 10000  # convert ms to seconds, and then divide by 10.
``

2018-08-20 23:38 UTC, twangboy commented
@damon-atkins Could you please review this one last time. I implemented the changes you suggested.

2018-08-21 15:24 UTC, damon-atkins approved these changes
DONE PR update with some more words around the timeout

2018-08-22 18:58 UTC, merged