[WIP] Use os.linesep.join instead of textwrap.dedent
saltstack/salt pull request #49235
Opened 2018-08-21 18:52 UTC by twangboy

### What does this PR do?
Uses `os.linesep.join` instead of `textwrap.dedent` to create the text strings. The problem with `textwrap.dedent` is that it always uses `posix-style` line endings.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/pull/48960

### Tests written?
Yes

### Commits signed with GPG?
Yes

2018-08-22 05:06 UTC, dwoz commented
@twangboy I've combined this with the other fixes from 2017.7 branch:

https://github.com/twangboy/salt/pull/12

2018-08-22 15:22 UTC, cachedout commented
@dwoz Do you recommend that we close this then?

2018-08-22 16:46 UTC, dwoz commented
@cachedout No, @twangboy can merge my PR into his branch and then we can merge his branch into 2017.7.8 which will fix the remaining failing tests there.

2018-08-22 16:54 UTC, terminalmage commented
I would still prefer using `textwrap.dedent`, for ease of maintainability. It wouldn't be hard to write a helper that used platform-specific newlines.

2018-08-22 16:56 UTC, terminalmage commented
That is, one that would call `textwrap.dedent()` and _then_ make sure that the newlines matched `os.linesep`.

2018-08-22 18:33 UTC, terminalmage commented
OK, let me know if you need any assistance.

2018-08-22 21:58 UTC, dwoz approved these changes

2018-08-23 13:12 UTC, terminalmage requested changes

2018-08-23 13:12 UTC, terminalmage commented on tests/support/helpers.py
> +        linesep = salt.utils.stringutils.to_unicode(linesep)
This needs to be `salt.utils.to_unicode(linesep)`, this function wasn't moved until 2018.3 and this PR has been opened against the 2017.7.8 release branch.

2018-08-23 13:12 UTC, terminalmage commented on tests/support/helpers.py
> +        linesep = salt.utils.stringutils.to_str(linesep)
Similarly, this needs to be `salt.utils.to_str(linesep)`.

2018-08-23 15:01 UTC, rallytime commented
@twangboy and @dwoz Why is this submitted against 2017.7.8? I was under the impression we were only working on some last package fixes, not code changes to meet the release deadline.

2018-08-23 18:33 UTC, dwoz commented
@rallytime, I think @twangboy was just trying to make the 2017.7.8 test suite for windows start passing. If we don't need or want these test fixes in 2017.7.8 then we can close this.

2018-08-23 20:35 UTC, rallytime commented
Ah, OK sounds good. I spoke with @twangboy offline as well and he confirmed the same thing. I'll close this.

2018-08-23 20:35 UTC, closed without merging