Added downloadonly to zypper upgrade
saltstack/salt pull request #49252
Opened 2018-08-22 13:16 UTC by grokrecursion

### What does this PR do?

This PR adds a downloadonly option for the pre-caching of updates so that packages will
be cached before update.

### What issues does this PR fix or reference?

Not being able to pre-cache packages even though functionality is already in zypper binary.

### Previous Behavior
No download only option

### New Behavior
Updates and dist updates now support download only of packages

### Tests written?

No

### Commits signed with GPG?

No

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.140-94.42-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
 

```

2018-08-22 14:24 UTC, meaksh requested changes
Thanks for this @grokrecursion ! :+1: 

There is a missing part here related with the returned output. Currently with this PR, since no packages are actually installed (if `downloadonly=True`) the internal comparison between `old` and `new` package dicts will show "no changes" even when packages were downloaded.

This needs to be adapted like we did here for the `install` method: https://github.com/saltstack/salt/blob/900510126df09616d2692aa10c613d7551a9f82c/salt/modules/zypper.py#L1345

So we look for "downloaded" packages (instead "installed") and therefore we can produce a proper output containing the actual downloaded packages when `downloadonly=True`:

```
old = list_pkgs() if not downloadonly else list_downloaded()
...
new = list_pkgs() if not downloadonly else list_downloaded()
```

2018-08-22 17:44 UTC, grokrecursion commented
Thanks @meaksh ! Good point. I'll look into it.

2018-08-29 18:51 UTC, cachedout commented
Hi @grokrecursion. Where are we on this one?

2018-09-28 14:21 UTC, rallytime commented
@grokrecursion Just a bump here. Did you get a chance to implement the feedback above?

2018-10-08 14:16 UTC, rallytime commented
Since we haven't heard back for a while here, I am going to close. Let us know when you're ready to make these changes and we will gladly re-open!

2018-10-08 14:16 UTC, closed without merging