[2018.3] Merge forward from 2017.7 to 2018.3
saltstack/salt pull request #49282
Opened 2018-08-23 15:54 UTC by rallytime

Conflicts:
  - salt/modules/file.py
  - salt/modules/win_service.py
  - salt/states/mount.py
  - salt/states/service.py
  - tests/integration/__init__.py
  - tests/integration/runners/test_state.py
  - tests/integration/states/test_file.py
  - tests/unit/states/test_file.py

2018-08-23 15:55 UTC, gtmanfred approved these changes

2018-08-23 20:14 UTC, dwoz requested changes

2018-08-23 20:14 UTC, dwoz commented on tests/unit/states/test_file.py
> +                            'changes': {name: {'directory': 'new'}}
I think we just want to skip this change.

https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-49282/1/testReport/junit/unit.states.test_file/TestFileState/test_directory/

2018-08-23 21:02 UTC, rallytime commented
The last 2 commits should fix 2 of the test failures. I need to investigate the final test failure more and discuss a fix from @terminalmage in the morning.

2018-08-24 13:45 UTC, rallytime commented
OK, this should be good now, pending tests.

2018-08-24 16:45 UTC, merged