Add dedent that sets line endings
saltstack/salt pull request #49291
Opened 2018-08-23 18:29 UTC by dwoz

### What does this PR do?

Add dedent helper that sets line endings

### Tests written?

No

### Commits signed with GPG?

Yes

2018-08-23 18:30 UTC, twangboy approved these changes

2018-08-23 21:03 UTC, dwoz commented
Looks like I need to circle back on this:
https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-49291/2/

2018-08-26 23:50 UTC, dwoz commented
@terminalmage Does this one look good to you?

2018-08-26 23:58 UTC, terminalmage requested changes

2018-08-26 23:58 UTC, terminalmage commented on tests/support/helpers.py
> +    if unicode_text.endswith(salt.utils.to_unicode('\n')):
`to_unicode` isn't really necessary here, since the newline character is part of the ASCII set. You can just use `u'\n'` instead.

2018-08-26 23:58 UTC, terminalmage commented on tests/support/helpers.py
> +        clean_text = clean_text + linesep
The `+=` operator can be used here.

2018-08-27 06:55 UTC, merged