OmniOS also supports pkgin
saltstack/salt pull request #49476
Opened 2018-08-31 19:39 UTC by sjorge

### What does this PR do?
As discovered in #49469 OmniOS is not loading the pkgin module while it is supported.
We remove SunOS and SmartOS from the OS list and enable pkgin for all members of the
Solaris family instead.

### What issues does this PR fix or reference?
This is a **partial** fix for #49469

### Previous Behavior
Only Sun/Oracle Solaris and SmartOS had pkgin support.

### New Behavior
The entire Solaris family has pkgin support, including OpenIndiana, OmniOS, ...

### Tests written?
No

### Commits signed with GPG?
No

2018-09-01 15:39 UTC, sjorge commented
Looks like this might need another small revision...

2018-09-01 18:53 UTC, sjorge commented
Reopened after using some feedback mentioned in #49469 by @damon-atkins ...

2018-09-04 09:45 UTC, damon-atkins commented
You might need to do this.
```
# Define the module's virtual name
__virtualname__ = 'pkgin'  if __grains__['os_family'] in supported_family else 'pkg' 
```
test out `salt-call sys.doc pkgin` vs `salt-call sys.doc pkg`

2018-09-04 10:03 UTC, damon-atkins commented
test out `salt-call sys.doc pkgin` vs `salt-call sys.doc pkg`

You might need a `def _main_pkg_provider()` which returns true or false. 
 ```
# Define the module's virtual name
__virtualname__ = 'pkg'  if _main_pkg_provider() else 'pkgin' 
```

2018-09-04 17:02 UTC, sjorge commented
This is the output with the patch as is:
```
root@urania:~# salt-call --local sys.doc pkgin
salt-call --local local:
    ----------
    pkgin.available_version:

        This function is an alias of ``latest_version``.

            .. versionchanged: 2016.3.0

            Return the latest version of the named package available for upgrade or
            installation.

            If the latest version of a given package is already installed, an empty
            string will be returned for that package.

            CLI Example:

                salt '*' pkg.latest_version <package name>
                salt '*' pkg.latest_version <package1> <package2> ...

    pkgin.file_dict:

            .. versionchanged: 2016.3.0

            List the files that belong to a package.

            CLI Examples:

                salt '*' pkg.file_dict nginx
                salt '*' pkg.file_dict nginx varnish

    pkgin.file_list:

            List the files that belong to a package.

            CLI Examples:

                salt '*' pkg.file_list nginx

    pkgin.install:

            Install the passed package

            name
                The name of the package to be installed.

            refresh
                Whether or not to refresh the package database before installing.

            fromrepo
                Specify a package repository to install from.


            Multiple Package Installation Options:

            pkgs
                A list of packages to install from a software repository. Must be
                passed as a python list.

                CLI Example:

                    salt '*' pkg.install pkgs='["foo","bar"]'

            sources
                A list of packages to install. Must be passed as a list of dicts,
                with the keys being package names, and the values being the source URI
                or local path to the package.

                CLI Example:

                    salt '*' pkg.install sources='[{"foo": "salt://foo.deb"},{"bar": "salt://bar.deb"}]'

            Return a dict containing the new package names and versions::

                {'<package>': {'old': '<old-version>',
                               'new': '<new-version>'}}

            CLI Example:

                salt '*' pkg.install <package name>

    pkgin.latest_version:

            .. versionchanged: 2016.3.0

            Return the latest version of the named package available for upgrade or
            installation.

            If the latest version of a given package is already installed, an empty
            string will be returned for that package.

            CLI Example:

                salt '*' pkg.latest_version <package name>
                salt '*' pkg.latest_version <package1> <package2> ...

    pkgin.list_pkgs:

            .. versionchanged: 2016.3.0

            List the packages currently installed as a dict::

                {'<package_name>': '<version>'}

            CLI Example:

                salt '*' pkg.list_pkgs

    pkgin.list_upgrades:

            List all available package upgrades.

            New in version 2018.3.0

            refresh
                Whether or not to refresh the package database before installing.

            CLI Example:

                salt '*' pkg.list_upgrades

    pkgin.purge:

            Package purges are not supported, this function is identical to
            ``remove()``.

            name
                The name of the package to be deleted.


            Multiple Package Options:

            pkgs
                A list of packages to delete. Must be passed as a python list. The
                ``name`` parameter will be ignored if this option is passed.

            New in version 0.16.0


            Returns a dict containing the changes.

            CLI Example:

                salt '*' pkg.purge <package name>
                salt '*' pkg.purge <package1>,<package2>,<package3>
                salt '*' pkg.purge pkgs='["foo", "bar"]'

    pkgin.refresh_db:

            Use pkg update to get latest pkg_summary

            force
                Pass -f so that the cache is always refreshed.

                New in version 2018.3.0


            CLI Example:

                salt '*' pkg.refresh_db

    pkgin.remove:

            name
                The name of the package to be deleted.


            Multiple Package Options:

            pkgs
                A list of packages to delete. Must be passed as a python list. The
                ``name`` parameter will be ignored if this option is passed.

            New in version 0.16.0


            Returns a list containing the removed packages.

            CLI Example:

                salt '*' pkg.remove <package name>
                salt '*' pkg.remove <package1>,<package2>,<package3>
                salt '*' pkg.remove pkgs='["foo", "bar"]'

    pkgin.search:

            Searches for an exact match using pkgin ^package$

            CLI Example:

                salt '*' pkg.search 'mysql-server'

    pkgin.upgrade:

            Run pkg upgrade, if pkgin used. Otherwise do nothing

            refresh
                Whether or not to refresh the package database before installing.

            Multiple Package Upgrade Options:

            pkgs
                A list of packages to upgrade from a software repository. Must be
                passed as a python list.

                CLI Example:

                    salt '*' pkg.upgrade pkgs='["foo","bar"]'

            Returns a dictionary containing the changes:

                {'<package>':  {'old': '<old-version>',
                                'new': '<new-version>'}}


            CLI Example:

                salt '*' pkg.upgrade

    pkgin.version:

            Returns a string representing the package version or an empty string if not
            installed. If more than one package name is specified, a dict of
            name/version pairs is returned.

            CLI Example:

                salt '*' pkg.version <package name>
                salt '*' pkg.version <package1> <package2> <package3> ...

root@urania:~# salt-call --local sys.doc pkg
local:
    ----------
    pkg.available_version:

        This function is an alias of ``latest_version``.

            The available version of the package in the repository.
            In case of multiple matches, it returns list of all matched packages.
            Accepts full or partial FMRI.
            Please use pkg.latest_version as pkg.available_version is being deprecated.

            CLI Example:

                salt '*' pkg.latest_version pkg://solaris/entire

    pkg.get_fmri:

            Returns FMRI from partial name. Returns empty string ('') if not found.
            In case of multiple match, the function returns list of all matched packages.

            CLI Example:

                salt '*' pkg.get_fmri bash

    pkg.install:

            Install the named package using the IPS pkg command.
            Accepts full or partial FMRI.

            Returns a dict containing the new package names and versions::

                {'<package>': {'old': '<old-version>',
                               'new': '<new-version>'}}


            Multiple Package Installation Options:

            pkgs
                A list of packages to install. Must be passed as a python list.


            CLI Example:

                salt '*' pkg.install vim
                salt '*' pkg.install pkg://solaris/editor/vim
                salt '*' pkg.install pkg://solaris/editor/vim refresh=True
                salt '*' pkg.install pkgs='["foo", "bar"]'

    pkg.is_installed:

            Returns True if the package is installed. Otherwise returns False.
            Name can be full or partial FMRI.
            In case of multiple match from partial FMRI name, it returns True.

            CLI Example:

                salt '*' pkg.is_installed bash

    pkg.latest_version:

            Th [...]

2018-09-04 17:39 UTC, sjorge commented
I need some more help on this I cannot get this to work.

Basically want want to be the default pkg provider for ```__grains__['os'] in ['NetBSD', 'DragonFly', 'Minix', 'Darwin', 'SmartOS']```. In other cases when `pkgin` is available we want to be an optional provider.

None of the  other pkg providers set a `__virtualname__` other than 'pkg' when I try to do fancy stuff sugested by @damon-atkins I cannot get it to work because `__grains__` is not available. If I move the _is_default_provider function before to the top.

The code as it is correct has the following effect,
SmartOS (or any os in the list above):
- pkg -> pkgin
- pking -> unavailable

OmniOS (or other os with pkgin present but not in the list above will still have the original provider):
- pkg -> solarisips 
- pkgin -> pkgin

2018-09-04 20:52 UTC, dmurphy18 approved these changes
looks fine

2018-09-05 09:52 UTC, damon-atkins commented
I have looked at the loader code.
Try not setting __virtualname__, if not set it uses the value returned by __virtual__ function.  I suspect it will work but the minions logs will have a warning.

To support this it seems the loader may need to be changed. But why do we need __virtual__  and __virtualname__ to match.

Ping @saltstack/team-core  re loader

Last resort is something simple  like `uname -s` to determine what to set __virtualname__ too.

2018-09-05 15:43 UTC, sjorge commented
Just to add a tiny bit to @damon-atkins last comment:

```
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.pkgin. Module will not be loaded: global name '__virtualname__' is not defined
'pkg.list_pkgs' is not available.
```

This is what happens when you drop __virtualname__ from the module. That being said the code as it is now seems to do what is expected, pkgin becomes 'pkg' on the set of platforms where it is the default package manager. Otherwise it becomes 'pkgin'.

2018-09-05 20:22 UTC, terminalmage approved these changes

2018-09-06 11:29 UTC, damon-atkins commented
@sjorge can you push up you latest code please.

2018-09-10 09:57 UTC, isbm requested changes
@sjorge can we avoid multiple returns when it is really not needed?

2018-09-10 09:57 UTC, isbm commented on salt/modules/pkgin.py
> +    return False
@sjorge bah...

```python
def _get_provider():
    return __grains__['os'] in ['NetBSD', 'DragonFly', 'Minix', 'Darwin', 'SmartOS'] and True or 'pkgin'
```

2018-09-10 09:57 UTC, isbm commented on salt/modules/pkgin.py
> +            'not detected on this platform.')
```python
return  (_check_pkgin() and _get_provider() or False,
        'The pkgin execution module cannot be loaded: pkgin was '
￼        'not detected on this platform.')

2018-09-11 16:50 UTC, sjorge commented
I've applied the corrections as asked by @isbm , I also rebased on develop.

SmartOS (where it is de default provider) still works as I pushed this to all my minions. I also did a quick test on OmniOS with pkgin installed.

```
root@inflaton:~# salt-call --local pkg.list_pkgs ; salt-call --local pkgin.list
_pkgs
local:
    ----------
    pkg://omnios/SUNWcs:
        0.5.11-0.151027:20180831T001257Z
    pkg://omnios/SUNWcsd:
        0.5.11-0.151027:20180831T001257Z
    pkg://omnios/compatibility/ucb:
        0.5.11-0.151027:20180831T001259Z
    pkg://omnios/compress/bzip2:
        1.0.6-0.151027:20180831T001517Z
    pkg://omnios/compress/gzip:
        1.9-0.151027:20180831T001540Z
    pkg://omnios/compress/p7zip:
        16.2-0.151027:20180831T001530Z
    pkg://omnios/compress/unzip:
        6.0-0.151027:20180831T001534Z
    pkg://omnios/compress/xz:
        5.2.4-0.151027:20180831T001641Z
    pkg://omnios/compress/zip:
        3.0-0.151027:20180831T001553Z
    pkg://omnios/consolidation/osnet/osnet-incorporation:
        0.5.11-0.151027:20180831T001257Z
    pkg://omnios/database/sqlite-3:
        3.24.0-0.151027:20180831T002244Z
    pkg://omnios/developer/build/make:
        0.5.11-0.151027:20180831T001301Z
    pkg://omnios/developer/debug/mdb:
        0.5.11-0.151027:20180831T001302Z
    pkg://omnios/developer/dtrace:
        0.5.11-0.151027:20180831T001302Z
    pkg://omnios/developer/linker:
        0.5.11-0.151027:20180831T001304Z
    pkg://omnios/developer/macro/gnu-m4:
        1.4.18-0.151027:20180831T094031Z
    pkg://omnios/diagnostic/cpu-counters:
        0.5.11-0.151027:20180831T001305Z
    pkg://omnios/diagnostic/diskinfo:
        0.5.11-0.151027:20180831T001306Z
    pkg://omnios/diagnostic/latencytop:
        0.5.11-0.151027:20180831T001306Z
    pkg://omnios/diagnostic/powertop:
        0.5.11-0.151027:20180831T001306Z
    pkg://omnios/driver/audio:
        0.5.11-0.151027:20180831T001307Z
    pkg://omnios/driver/crypto/dca:
        0.5.11-0.151027:20180831T001307Z
    pkg://omnios/driver/crypto/tpm:
        0.5.11-0.151027:20180831T001308Z
    pkg://omnios/driver/firewire:
        0.5.11-0.151027:20180831T001308Z
    pkg://omnios/driver/graphics/agpgart:
        0.5.11-0.151027:20180831T001308Z
    pkg://omnios/driver/graphics/atiatom:
        0.5.11-0.151027:20180831T001308Z
    pkg://omnios/driver/graphics/drm:
        0.5.11-0.151027:20180831T001308Z
    pkg://omnios/driver/i86pc/fipe:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/i86pc/ioat:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/i86pc/platform:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/misc/virtio:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/network/afe:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/network/amd8111s:
        0.5.11-0.151027:20180831T001309Z
    pkg://omnios/driver/network/atge:
        0.5.11-0.151027:20180831T001310Z
    pkg://omnios/driver/network/bfe:
        0.5.11-0.151027:20180831T001310Z
    pkg://omnios/driver/network/bge:
        0.5.11-0.151027:20180831T001310Z
    pkg://omnios/driver/network/bnx:
        0.5.11-0.151027:20180831T001310Z
    pkg://omnios/driver/network/bnxe:
        0.5.11-0.151027:20180831T001311Z
    pkg://omnios/driver/network/bpf:
        0.5.11-0.151027:20180831T001311Z
    pkg://omnios/driver/network/chxge:
        0.5.11-0.151027:20180831T001311Z
    pkg://omnios/driver/network/dmfe:
        0.5.11-0.151027:20180831T001311Z
    pkg://omnios/driver/network/e1000g:
        0.5.11-0.151027:20180831T001311Z
    pkg://omnios/driver/network/elxl:
        0.5.11-0.151027:20180831T001312Z
    pkg://omnios/driver/network/emlxs:
        0.5.11-0.151027:20180831T001312Z
    pkg://omnios/driver/network/eoib:
        0.5.11-0.151027:20180831T001312Z
    pkg://omnios/driver/network/fcip:
        0.5.11-0.151027:20180831T001312Z
    pkg://omnios/driver/network/fcp:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/fcsm:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/fp:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/hermon:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/hme:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/hxge:
        0.5.11-0.151027:20180831T001313Z
    pkg://omnios/driver/network/i40e:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/ib:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/ibdma:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/ibp:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/igb:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/iprb:
        0.5.11-0.151027:20180831T001314Z
    pkg://omnios/driver/network/ixgb:
        0.5.11-0.151027:20180831T001315Z
    pkg://omnios/driver/network/ixgbe:
        0.5.11-0.151027:20180831T001316Z
    pkg://omnios/driver/network/mxfe:
        0.5.11-0.151027:20180831T001316Z
    pkg://omnios/driver/network/myri10ge:
        0.5.11-0.151027:20180831T001316Z
    pkg://omnios/driver/network/nge:
        0.5.11-0.151027:20180831T001316Z
    pkg://omnios/driver/network/ntxn:
        0.5.11-0.151027:20180831T001316Z
    pkg://omnios/driver/network/nxge:
        0.5.11-0.151027:20180831T001317Z
    pkg://omnios/driver/network/ofk:
        0.5.11-0.151027:20180831T001317Z
    pkg://omnios/driver/network/pcn:
        0.5.11-0.151027:20180831T001317Z
    pkg://omnios/driver/network/platform:
        0.5.11-0.151027:20180831T001317Z
    pkg://omnios/driver/network/qlc:
        0.5.11-0.151027:20180831T001317Z
    pkg://omnios/driver/network/rds:
        0.5.11-0.151027:20180831T001318Z
    pkg://omnios/driver/network/rdsv3:
        0.5.11-0.151027:20180831T001318Z
    pkg://omnios/driver/network/rge:
        0.5.11-0.151027:20180831T001318Z
    pkg://omnios/driver/network/rpcib:
        0.5.11-0.151027:20180831T001318Z
    pkg://omnios/driver/network/rtls:
        0.5.11-0.151027:20180831T001318Z
    pkg://omnios/driver/network/sdp:
        0.5.11-0.151027:20180831T001319Z
    pkg://omnios/driver/network/sdpib:
        0.5.11-0.151027:20180831T001319Z
    pkg://omnios/driver/network/sfe:
        0.5.11-0.151027:20180831T001319Z
    pkg://omnios/driver/network/sfxge:
        0.5.11-0.151027:20180831T001319Z
    pkg://omnios/driver/network/tavor:
        0.5.11-0.151027:20180831T001320Z
    pkg://omnios/driver/network/usbecm:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/network/vioif:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/network/vmxnet3s:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/network/vr:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/network/xge:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/network/yge:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/pcmcia:
        0.5.11-0.151027:20180831T001321Z
    pkg://omnios/driver/serial/usbftdi:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbsacm:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbser:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbser_edge:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbsksp:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbsksp/usbs49_fw:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/serial/usbsprl:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/storage/aac:
        0.5.11-0.151027:20180831T001322Z
    pkg://omnios/driver/storage/adpu320:
        0.5.11-0.151027:20180831T001323Z
    pkg://omnios/driver/storage/ahci:
        0.5.11-0.151027:20180831T001323Z
    pkg://omnios/driver/storage/amr:
        0.5.11-0.151027:20180831T001323Z
    pkg://omnios/driver/storage/arcm [...]

2018-09-11 18:38 UTC, sjorge commented on salt/modules/pkgin.py
> +    return __grains__['os'] in ['NetBSD', 'DragonFly', 'Minix', 'Darwin', 'SmartOS'] and True or 'pkgin'
Seems to work Ok without it too.

2018-09-11 19:05 UTC, rallytime approved these changes

2018-09-12 09:54 UTC, isbm approved these changes
@sjorge thanks!

2018-09-12 13:09 UTC, damon-atkins commented
What the output from salt-call sys.doc pkg and pkgin like.

I assume there are still errors in the logs.   Maybe we need a special name to set  `__virtualname__`  too

e.g.
`__virtualname__ = '__dynamic__'`
And have the loader not error when it sees this.

We did not get a response from the `__virtualname__` on why this is needed or more to the point the loader complains if its missing.

2018-09-12 14:51 UTC, merged

2018-09-12 16:47 UTC, sjorge commented
```root@inflaton:~# salt-call --local sys.doc pkg
local:
    ----------
    pkg.available_version:

        This function is an alias of ``latest_version``.

            The available version of the package in the repository.
            In case of multiple matches, it returns list of all matched packages.
            Accepts full or partial FMRI.
            Please use pkg.latest_version as pkg.available_version is being deprecated.

            CLI Example:

                salt '*' pkg.latest_version pkg://solaris/entire

    pkg.get_fmri:

            Returns FMRI from partial name. Returns empty string ('') if not found.
            In case of multiple match, the function returns list of all matched packages.

            CLI Example:

                salt '*' pkg.get_fmri bash

    pkg.install:

            Install the named package using the IPS pkg command.
            Accepts full or partial FMRI.

            Returns a dict containing the new package names and versions::

                {'<package>': {'old': '<old-version>',
                               'new': '<new-version>'}}


            Multiple Package Installation Options:

            pkgs
                A list of packages to install. Must be passed as a python list.


            CLI Example:

                salt '*' pkg.install vim
                salt '*' pkg.install pkg://solaris/editor/vim
                salt '*' pkg.install pkg://solaris/editor/vim refresh=True
                salt '*' pkg.install pkgs='["foo", "bar"]'

    pkg.is_installed:

            Returns True if the package is installed. Otherwise returns False.
            Name can be full or partial FMRI.
            In case of multiple match from partial FMRI name, it returns True.

            CLI Example:

                salt '*' pkg.is_installed bash

    pkg.latest_version:

            The available version of the package in the repository.
            In case of multiple matches, it returns list of all matched packages.
            Accepts full or partial FMRI.
            Please use pkg.latest_version as pkg.available_version is being deprecated.

            CLI Example:

                salt '*' pkg.latest_version pkg://solaris/entire

    pkg.list_pkgs:

            List the currently installed packages as a dict::

                {'<package_name>': '<version>'}

            CLI Example:

                salt '*' pkg.list_pkgs

    pkg.list_upgrades:

            Lists all packages available for update.

            When run in global zone, it reports only upgradable packages for the global
            zone.

            When run in non-global zone, it can report more upgradable packages than
            ``pkg update -vn``, because ``pkg update`` hides packages that require
            newer version of ``pkg://solaris/entire`` (which means that they can be
            upgraded only from the global zone). If ``pkg://solaris/entire`` is found
            in the list of upgrades, then the global zone should be updated to get all
            possible updates. Use ``refresh=True`` to refresh the package database.

            refresh : True
                Runs a full package database refresh before listing. Set to ``False`` to
                disable running the refresh.

                Changed in version 2017.7.0

                In previous versions of Salt, ``refresh`` defaulted to ``False``. This was
                changed to default to ``True`` in the 2017.7.0 release to make the behavior
                more consistent with the other package modules, which all default to ``True``.

            CLI Example:

                salt '*' pkg.list_upgrades
                salt '*' pkg.list_upgrades refresh=False

    pkg.normalize_name:

            Internal function. Normalizes pkg name to full FMRI before running
            pkg.install. In case of multiple matches or no match, it returns the name
            without modifications.

            CLI Example:

                salt '*' pkg.normalize_name vim

    pkg.purge:

            Remove specified package. Accepts full or partial FMRI.

            Returns a list containing the removed packages.

            CLI Example:

                salt '*' pkg.purge <package name>

    pkg.refresh_db:

            Updates the remote repos database.

            full : False

                Set to ``True`` to force a refresh of the pkg DB from all publishers,
                regardless of the last refresh time.

            CLI Example:

                salt '*' pkg.refresh_db
                salt '*' pkg.refresh_db full=True

    pkg.remove:

            Remove specified package. Accepts full or partial FMRI.
            In case of multiple match, the command fails and won't modify the OS.

            name
                The name of the package to be deleted.


            Multiple Package Options:

            pkgs
                A list of packages to delete. Must be passed as a python list. The
                ``name`` parameter will be ignored if this option is passed.


            Returns a list containing the removed packages.

            CLI Example:

                salt '*' pkg.remove <package name>
                salt '*' pkg.remove tcsh
                salt '*' pkg.remove pkg://solaris/shell/tcsh
                salt '*' pkg.remove pkgs='["foo", "bar"]'

    pkg.search:

            Searches the repository for given pkg name.
            The name can be full or partial FMRI. All matches are printed. Globs are
            also supported.

            CLI Example:

                salt '*' pkg.search bash

    pkg.upgrade:

            Upgrade all packages to the latest possible version.
            When run in global zone, it updates also all non-global zones.
            In non-global zones upgrade is limited by dependency constrains linked to
            the version of pkg://solaris/entire.

            Returns a dictionary containing the changes:

                {'<package>':  {'old': '<old-version>',
                                'new': '<new-version>'}}

            When there is a failure, an explanation is also included in the error
            message, based on the return code of the ``pkg update`` command.


            CLI Example:

                salt '*' pkg.upgrade

    pkg.upgrade_available:

            Check if there is an upgrade available for a certain package
            Accepts full or partial FMRI. Returns all matches found.

            CLI Example:

                salt '*' pkg.upgrade_available apache-22

    pkg.version:

            Common interface for obtaining the version of installed packages.
            Accepts full or partial FMRI. If called using pkg_resource, full FMRI is required.

            CLI Example:

                salt '*' pkg.version vim
                salt '*' pkg.version foo bar baz
                salt '*' pkg_resource.version pkg://solaris/entire


root@inflaton:~# salt-call --local sys.doc pkgin
local:
    ----------
    pkgin.available_version:

        This function is an alias of ``latest_version``.

            .. versionchanged: 2016.3.0

            Return the latest version of the named package available for upgrade or
            installation.

            If the latest version of a given package is already installed, an empty
            string will be returned for that package.

            CLI Example:

                salt '*' pkg.latest_version <package name>
                salt '*' pkg.latest_version <package1> <package2> ...

    pkgin.file_dict:

            .. versionchanged: 2016.3.0

            List the files that belong to a package.

            CLI Examples:

                salt '*' pkg.file_dict nginx
                salt '*' pkg.file_dict nginx varnish

    pkgin.file_list:

            List the files that belong to a package.

            CLI Examples:

                salt '*' pkg.file_list nginx

    pkgin.install:

            Install the passed package [...]

2018-09-12 16:52 UTC, rallytime commented
Yeah, this all looks fine to me. Thanks for double checking. :)