yumpkg module: Add support for key_url parameter when adding repos
saltstack/salt pull request #49517
Opened 2018-09-05 15:35 UTC by bbczeuz

### What does this PR do?
The `pkgrepo` state module's `managed` function has a `key_url` parameter. This is currently implemented for deb repos, but silently ignored for rpm repos. The PR implements key downloading and importing for rpm based systems.

### What issues does this PR fix or reference?
#49516

### Previous Behavior
The `key_url` parameter is silently ignored on rpm systems

### New Behavior
The file at `key_url` is imported using 'rpm --import'

### Tests written?
Manually using sls (Centos7):
```
add_influxdata_repo:
  pkgrepo.managed:
    - name: influxdb
    - humanname: influxdata
    - baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    - key_url: salt://files/influxdb.key
    - gpgcheck: 1
```

### Commits signed with GPG?

No

2018-09-05 15:36 UTC, bbczeuz commented
The implementation is basically an adapted version from the aptpkg module

2018-09-05 19:47 UTC, bbczeuz commented
* In theory, we could implement code to avoid importing the same key everytime the state runs by comparing known keys to the new one, but this is the same as the apt-version does.
* The key file is not being stored at the usual location (/etc/pki/rpm-gpg/), but directly imported.

2018-09-06 14:46 UTC, terminalmage approved these changes

2018-09-11 10:01 UTC, isbm requested changes

2018-09-11 10:01 UTC, isbm commented on salt/modules/yumpkg.py
> +                'Error: failed to add key from {0}'.format(key_url)
It raises a question: "What key, again?". Let be more specific here.

2018-09-11 23:08 UTC, bbczeuz commented
@isbm : thanks for the review. Messages clarified.

2018-09-12 10:25 UTC, isbm requested changes

2018-09-12 19:27 UTC, bbczeuz commented
@isbm Done, thanks again :)

2018-09-12 22:09 UTC, isbm commented
> @isbm Done, thanks again :)

Next time don't just copypaste my mistakes. :stuck_out_tongue: Thanks!

2018-09-12 22:09 UTC, isbm approved these changes

2018-09-13 14:07 UTC, merged

2018-09-14 08:13 UTC, SooLFaa commented
Use CVE-2018-17027 
Use CVE-2018-17028 
for vulnerability auth bypass

2018-09-14 10:33 UTC, bbczeuz commented
@SooLFaa Can you elaborate on how this is relevant to the PR?

2018-09-14 10:46 UTC, SooLFaa commented
Please send this ticket, the one who is responsible for security.14.09.2018, 13:34, "Claudius Zingerli" <notifications@github.com>:@SooLFaa Can you elaborate on how this is relevant to the PR?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением, Алексей!