ping_interval: use service.restart instead of signaling
saltstack/salt pull request #49615
Opened 2018-09-11 20:00 UTC by terminalmage

When multiprocessing does not relat the signal properly, ping_interval will fail to respawn the multiprocessing.Process instance and the minion will end up in a bad state, where there are still salt-minion procs running but the minion is not connected to the master and thus does not respond to pubs from the it.

This commit ditches signaling in favor of using `service.restart` to restart the minion daemon.

2018-09-12 10:22 UTC, isbm requested changes
@terminalmage it is a _benevolent_ request. :wink:

2018-09-13 13:47 UTC, rallytime reviewed
I think this looks good, but it's probably a good idea to move that to a helper function for the future.

2018-09-17 15:47 UTC, terminalmage commented
The logic to get the service name has been moved to a separate function in `salt/minion.py`. I decided to make it a public function rather than private, since it could be useful outside of minion.py.

2018-09-17 15:50 UTC, terminalmage commented on salt/minion.py
> +                                )
Good idea. I just made this change.

2018-09-17 15:52 UTC, rallytime approved these changes

2018-09-21 08:03 UTC, isbm approved these changes

2018-09-21 13:26 UTC, merged