Fix typo (exsiting -> existing)
saltstack/salt pull request #49750
Opened 2018-09-23 08:18 UTC by jose1711

2018-09-23 11:10 UTC, MTecknology approved these changes

2018-09-24 13:02 UTC, gtmanfred requested changes
please revert all changes to doc/man/salt.7, we manage that from the other files, and it only gets updated with releases.

2018-09-24 13:39 UTC, rallytime commented
The man page changes are fine here, but just be aware that any changes made there will be overwritten the next time we generate the man pages (which we do before each release).

2018-09-24 13:39 UTC, rallytime commented
Thanks for contributing @jose1711!

2018-09-24 13:39 UTC, merged