Handle Auth exceptions in run_job
saltstack/salt pull request #49761
Opened 2018-09-24 19:39 UTC by Ch3LL

### What does this PR do?
Handles both AuthenticationError and AuthorizationError in run_job so we return a 401 instead of a 500 when using incorrect authentication in salt-api

### Previous Behavior

```
[root@702f242dd208 testing]# curl -sS localhost:8000/run     -H 'Accept: application/x-yaml'     -H 'Content-type: application/json'     -d '[{
        "client": "local",
        "tgt": "*",
        "fun": "test.ping",
        "token": "bad"
    }]' 
return: "Traceback (most recent call last):\n  File \"/testing/salt/netapi/rest_cherrypy/app.py\",
  line 858, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args,
  **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\",
  line 34, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File
  \"/testing/salt/netapi/rest_cherrypy/app.py\", line 2128, in POST\n    'return':
  list(self.exec_lowstate()),\n  File \"/testing/salt/netapi/rest_cherrypy/app.py\",
  line 1178, in exec_lowstate\n    ret = self.api.run(chunk)\n  File \"/testing/salt/netapi/__init__.py\",
  line 75, in run\n    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs',
  {}))\n  File \"/testing/salt/netapi/__init__.py\", line 103, in local\n    return
  local.cmd(*args, **kwargs)\n  File \"/testing/salt/client/__init__.py\", line 741,
  in cmd\n  File \"/testing/salt/client/__init__.py\", line 335, in run_job\n    try:\nSaltClientError:
  Authentication error occurred.\n"
status: 500
```

### New Behavior

```
[root@bf115f35ab7a /]# curl -sS localhost:8000/run     -H 'Accept: application/x-yaml'     -H 'Content-type: application/json'     -d '[{
        "client": "local",
        "tgt": "*",
        "fun": "test.ping",
        "token": "bad"
    }]' 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/testing/salt/netapi/rest_cherrypy/app.py", line 863, in hypermedia_handler
    raise cherrypy.HTTPError(401)
HTTPError: (401, None)
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

2018-09-24 19:39 UTC, rallytime approved these changes
👍

2018-09-25 09:24 UTC, isbm requested changes
@Ch3LL I am wondering do we need to include Python traceback while auth failed? For example, now I know you're running Python version 2.7 and your API handler is CherryPy (and [you know the drill](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-0252) what to do next). You even telling me the exact version of it: 3.2.2. Way too much of info for **unauthorised** :fire: :fire: :fire:  people.

I would remove all that and just say what it is: "Authentication error". Have a happy HTTP error code attached, bye-bye. :wink:

2018-09-25 11:43 UTC, gtmanfred requested changes
Yeah, for security reasons, we do not want to dump the stack trace in the return, we want that to go in /var/log/salt/api, but the return should just be a 401 error.

2018-09-25 14:47 UTC, Ch3LL commented
apologies in my example i had `debug` on for cherrypy. When changing debug to false:

```
[root@4058e6a357c4 /]# curl -sS localhost:8000/run     -H 'Accept: application/x-yaml'     -H 'Content-type: application/json'     -d '[{
        "client": "local",
        "tgt": "*",
        "fun": "test.ping",
        "token": "bad"
    }]' 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
[root@4058e6a357c4 /]# 
```

2018-09-25 14:53 UTC, isbm commented
Can we also remove this part:
```html
<div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
 </div>
```

2018-09-25 14:54 UTC, isbm requested changes
Can we also remove this part:
```html
<div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
 </div>
```

2018-09-25 15:08 UTC, gtmanfred commented
I would really like to see this us return an error message in json, instead of this html blob.

2018-09-25 15:10 UTC, gtmanfred approved these changes
looks like this has always been what this returns.

Lets get this in, and then get a fix for the html return in a future release.

2018-09-25 15:10 UTC, isbm commented
@gtmanfred I was actually wondering if JSON should be the case here. :laughing:

2018-09-25 15:14 UTC, rallytime commented
Yes, let's get this fixed in another PR and get this in. @Ch3LL is going to create a new issue and follow up with your comments. Thanks all!

2018-09-25 15:19 UTC, Ch3LL commented
yep I found this "Powered by" message is in Cherrypy's html template here: https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cperror.py#L467

so looks like @gtmanfred suggestion is what we need to do. creating issue now.

2018-09-25 15:21 UTC, isbm commented
@Ch3LL d'oh, it is easier than I thought then. :wink: Just JSON it up.

2018-09-25 16:11 UTC, cachedout commented
I'm fine with merging this but I do think we need a follow-up here. This pattern of re-raising exceptions that are custom-defined gives me the shivers a little bit. At the very least, in a follow-up, I think we should write a more generalized exception handler method and route exceptions through that.

2018-09-25 20:05 UTC, merged