New Docker Compose module
saltstack/salt pull request #49859
Opened 2018-10-02 03:32 UTC by sco0tr

Provides functionality to interact directly with the docker-compose CLI.

2018-10-02 17:19 UTC, gtmanfred requested changes
This looks great! i just have some requests for salt specific things.

This module will also need to have an autodoc file added to `doc/ref/modules/all/salt.modules.composeng.rst` and then composeng will need to be added to the `doc/ref/modules/all/index.rst` file in that directory so it gets rendered

I would also prefer this be named dockercomposeng, instead of just composeng.

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +from docopt import docopt
please do `import docopt` and refer to it as `docopt.docopt` otherwise, `composeng.docopt` will get added to the functions in the loader.

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +from operator import attrgetter
same with the above 3 things, we do not want to use `from` because it pollutes the loader namespace

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +    from compose.cli.command import get_project
This should also be treated like the above.

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +from salt.ext import six
`import salt.ext.six as six`

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +from compose.cli.main import TopLevelCommand, project_from_options
this should probably also be in the above compose lookup.

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +
can you add `:depends: docker-compose`

2018-10-02 17:19 UTC, gtmanfred commented on salt/modules/composeng.py
> +    :return:
All of these need a CLI Example like other salt modules.

2018-10-02 22:12 UTC, gtmanfred requested changes
Thanks for making those changes, just a few more sphinx things

2018-10-02 22:12 UTC, gtmanfred commented on salt/modules/dockercomposeng.py
> +    salt 'myminion' dockercomposeng.get_convergence_plans /path/to/project/dir
This will need to be indented

2018-10-02 22:34 UTC, gtmanfred commented
Ok, it all looks good now.

But as I have been looking at the other dockercompose module, I am not actually certain what this adds that makes it better?  and can you please include that in the description of the PR?

2018-10-02 22:34 UTC, gtmanfred commented
It would also be great to have some tests for this module.

2018-10-04 15:39 UTC, cachedout commented
I have the same question as @gtmanfred. It's unclear to me why we should replace what we have with something new. Could you please explain in detail why these changes are necessary and what advantages this move will have?

2018-10-04 18:29 UTC, dwoz commented
If we do replace what we have. I think it would be beneficial to have some tests to verify we are not loosing functionality.

2018-10-09 21:07 UTC, terminalmage reviewed
I'm not familiar with docker-compose so I will defer to @gtmanfred on this. I will say though that unless it changes radically how our current docker-compose support works, I'm not sure it's a great idea to make a completely new module for this.

The reason we had a `dockerng` module for a while was because there were significant design flaws in the previous module, and we did not want to impact current users that relied on the old module and cause their states to break overnight once they upgraded.

2018-10-16 10:11 UTC, cachedout commented
@sco0tr We haven't heard from you since you submitted this. Did you see the feedback that came in?

2018-10-18 01:44 UTC, sco0tr commented
@gtmanfred @cachedout We wrote this module to increase the amount of functionality we could extract from docker-compose. This module allows us to use any number of the available command line arguments and provides better error handling.  The idea behind this module is to maintain as much feature parity as possible with the previous module while offering support for new functionality out of docker-compose if and when it's released.

2018-10-18 01:46 UTC, gtmanfred commented
That is awesome, but what new functionality does this add? And is there a
reason it can't be added to the other module?

On Wed, Oct 17, 2018, 8:45 PM sco0tr <notifications@github.com> wrote:

> @gtmanfred <https://github.com/gtmanfred> @cachedout
> <https://github.com/cachedout> We wrote this module to increase the
> amount of functionality we could extract from docker-compose. This module
> allows us to use any number of the available command line arguments and
> provides better error handling. The idea behind this module is to maintain
> as much feature parity as possible with the previous module while offering
> support for new functionality out of docker-compose if and when it's
> released.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/49859#issuecomment-430846539>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAssocTS_XMf9J3s51B2EhSJsrA5nfnTks5ul90ygaJpZM4XDRLw>
> .
>

2018-10-22 22:18 UTC, sco0tr commented
`dockercomposeng` exposes a more accurate and direct interface to the original Compose library.

As the `compose` package from Docker is [intentionally undocumented](https://github.com/docker/compose/issues/4542), the new module chose to interface with Compose through the same code it's CLI interface uses via docopt (the argument parser). This should mean this new module will be more resilient to internal changes in the Compose library. New parameters and options to any `docker-compose` command we have already wraped will be supported with no code changes to the module. The new module also returns unmodified output directly from the Compose library in a more consistent format and throws exceptions when necessary making it easier to work with.

While the core functionality is very similar, the interface with this new module changes how caller's calls and handles output from this module, breaking backwards compatibility. IIRC Salt has a 3 release deprecation notice for breaking changes, this module is here for the transition period. We have no issue of it eventually replacing the old `dockercompose` module.

2018-10-23 01:19 UTC, gtmanfred commented
If this added tests i would :+1: it.  outside of that, i don't know that it should be merged in.

2018-10-31 09:36 UTC, leoxiong commented
I will finish off writing the tests/additional changes to the new module to help get it merged in, the ETA will be 19th of November when I get some time. @scootr and I worked on this module together so I am familiar with its design.

2018-12-10 20:50 UTC, cachedout commented
Hi @leoxiong Any update on the work that was going to be done here?

2019-04-26 17:57 UTC, dwoz commented
@sco0tr It seems this PR has gone stale so I am going to close it for now. If you find time to pick up it up again we'll be happy to accept another PR with these changes. Thanks!

2019-04-26 17:57 UTC, closed without merging