Use __context__ to optimize lgpo module
saltstack/salt pull request #49919
Opened 2018-10-06 03:12 UTC by twangboy

### What does this PR do?
Uses __context__ to store information that was being generated repeatedly. This should help with the speed issues.

@lomeroe Could you give this a once-over in case I broke something?

### Tests written?
No

### Commits signed with GPG?
Yes

2018-10-08 15:13 UTC, rallytime commented
Hey @twangboy Can you fixup this lint error?

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49919/2/

2018-10-09 15:58 UTC, cachedout commented
I don't see *any* automated testing for LGPO. Is that correct? If so, this is an awful big change to make without a safety net.

2018-10-09 17:21 UTC, dwoz requested changes

2018-10-09 17:21 UTC, dwoz commented on salt/modules/win_lgpo.py
> +    retcode = __salt__['cmd.retcode'](['secedit', '/configure', '/db', f_sdb,
Should this be in a try/finally to make sure we do not leave stale files around?

2018-10-11 18:50 UTC, lomeroe commented
@twangboy I haven't been able to really look at this, but I *tried* to add a module test in #50006

2018-10-18 11:44 UTC, cachedout commented
@dwoz Can you please take another swing back through here?

2018-10-18 21:41 UTC, lomeroe commented
@twangboy I don't see anything glaring when looking through it.  Throwing the test added in #50006 at it, the only failures are those that are fixed in that PR, so *seems* okay.

2018-10-19 16:23 UTC, dwoz approved these changes

2018-10-23 14:34 UTC, merged