Coerce string  when calling compile_template_str
saltstack/salt pull request #49943
Opened 2018-10-08 20:38 UTC by thetaurean

### What does this PR do?
This fixes a bug in the file_tree pillar which causes it to fail to render templates in python 3. The caller for the template rendering function passes bytes instead of string.

### What issues does this PR fix or reference?
Issue #49927 

### Previous Behavior
else:
                data = contents
                if template is True:
                    data = salt.template.compile_template_str(template=contents,
                                                              renderers=renderers,
                                                              default=render_default,
                                                              blacklist=renderer_blacklist,
                                                              whitelist=renderer_whitelist)

### New Behavior
else:
                data = contents
                if template is True:
                    data = salt.template.compile_template_str(template=_**to_str(contents),**_
                                                              renderers=renderers,
                                                              default=render_default,
                                                              blacklist=renderer_blacklist,
                                                              whitelist=renderer_whitelist)

### Tests written?

No. New functionality not added

### Commits signed with GPG?

Yes

2018-10-08 20:40 UTC, gtmanfred requested changes
just a styling change.

2018-10-08 20:40 UTC, gtmanfred commented on salt/pillar/file_tree.py
> +from salt.utils.stringutils import to_str
please don't import functions like this, it will add it to the functions in the modules.

```
import salt.utils.stringutils
```

2018-10-08 20:40 UTC, gtmanfred commented on salt/pillar/file_tree.py
> +                    data = salt.template.compile_template_str(template=to_str(contents),
`salt.utils.stringutils.to_str(contents)`

2018-10-08 20:40 UTC, gtmanfred commented
@terminalmage should this be to_str? or something else?

Thanks,
Daniel

2018-10-08 20:46 UTC, thetaurean commented
@gtmanfred  Addressed. Thank you.

2018-10-08 20:50 UTC, gtmanfred approved these changes
This looks good to me, still want @terminalmage or someone else to take a look.

2018-10-08 20:51 UTC, gtmanfred commented
I have also marked this to be backported, for future reference, PRs that fix bugs should be opened against the oldest feature release that the bug is present in, so in this case that would be the 2018.3 branch. (2018.3.3 is a release branch and not the main feature branch)

2018-10-08 21:06 UTC, thetaurean commented
@gtmanfred Good point, aww shucks!

I am happy to rebase the changes on 2018.3.3 and force push, thoughts?

2018-10-08 21:10 UTC, gtmanfred commented
There is 0 chance this makes it in 2018.3.3, it has already been tagged and is being packaged.

But i have marked it for backporting, so it will be in 2018.3.4

2018-10-09 08:14 UTC, isbm approved these changes

2018-10-09 18:19 UTC, dwoz approved these changes

2018-10-10 11:58 UTC, terminalmage requested changes
`salt.templates.compile_template_str()` writes the template to a tempfile in binary mode, and therefore encodes to UTF-8 before doing so. This is why Python 3 raised the error.

However, because we are encoding, we want the contents to be unicode first, otherwise Python 2 will break when non-ascii characters are present in the string we pass:

```pytb
>>> 'groß'.encode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

Therefore, please change from `to_str()` to `to_unicode()`.

2018-10-10 16:15 UTC, thetaurean commented
@terminalmage Addressed. Excellent observation and appreciate the insight gained from your thorough explanation 👍

2018-10-10 20:17 UTC, terminalmage approved these changes
Well done, thank you for contributing!

2018-10-11 13:01 UTC, merged

2020-07-29 17:08 UTC, roaldnefs commented
Already ported to master in #50052.