Make win_groupadd module behave like other modules
saltstack/salt pull request #50086
Opened 2018-10-16 21:06 UTC by twangboy

### What does this PR do?
Fixes issues with win_groupadd module where it was returning dictionaries instead of boolean values.
Adds logging
Returns CommandExecutionError on failure

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/pull/49794

### Tests written?
Yes

### Commits signed with GPG?
Yes

2018-10-17 14:09 UTC, rallytime commented
@twangboy There are some related tests failing on windows here. Can you take a look?

2018-10-17 15:02 UTC, damon-atkins commented
Raise CommandExecutionError how it should be, but it would need all other other group modules to be updated, to behavior the same way. states/group to support it.  Is with CommandExecutionError  is you can pass back why it failed, rather than just false. Most likely raise change should be in develop.

2018-10-17 15:17 UTC, twangboy commented
@damon-atkins Created an issue to add CommandExecutionError on failure.
https://github.com/saltstack/salt/issues/50096

2018-10-17 19:49 UTC, dwoz approved these changes

2018-10-18 11:05 UTC, cachedout requested changes

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug(msg)
Is `debug` the right log level for an error like this?
```suggestion
            log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug('The group {0} already exists.'.format(name))
Same question here.

```suggestion
        log.error('The group {0} already exists.'.format(name))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug('Successfully removed group {0}'.format(name))
```suggestion
            log.error('Successfully removed group {0}'.format(name))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug(msg)
```suggestion
            log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug('The group {0} does not exists.'.format(name))
```suggestion
        log.warning('The group {0} does not exists.'.format(name))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug(msg)
```suggestion
        log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug('Added user {0}'.format(username))
```suggestion
            log.info('Added user {0}'.format(username))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug('User {0} is already a member of {1}'.format(username, name))
```suggestion
            log.info('User {0} is already a member of {1}'.format(username, name))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug(msg)
```suggestion
        log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug(msg)
```suggestion
        log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +            log.debug('Removed user {0}'.format(username))
```suggestion
            log.info('Removed user {0}'.format(username))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug(msg)
```suggestion
        log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug('member_list is not a list')
```suggestion
        log.error('member_list is not a list')
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +        log.debug(msg)
```suggestion
        log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +                log.debug('User added: {0}'.format(member))
```suggestion
                log.info('User added: {0}'.format(member))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +                log.debug(msg)
```suggestion
                log.error(msg)
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +                log.debug('User removed: {0}'.format(member))
```suggestion
                log.info('User removed: {0}'.format(member))
```

2018-10-18 11:05 UTC, cachedout commented on salt/modules/win_groupadd.py
> +                log.debug(msg)
```suggestion
                log.error(msg)
```

2018-10-24 14:48 UTC, rallytime commented
@twangboy Did you see the feedback above?

2018-10-24 17:04 UTC, twangboy commented
@rallytime Yes, I added it to my list

2018-10-24 17:36 UTC, twangboy commented
@cachedout Added your changes and rebased

2018-11-06 18:28 UTC, twangboy commented
Updated the branch... Is this OK now?

2018-11-09 14:38 UTC, rallytime commented
@cachedout Can you review this one more time?

2018-11-15 19:21 UTC, twangboy commented
@cachedout @rallytime Rebased...

2018-12-10 20:30 UTC, cachedout approved these changes

2018-12-10 20:30 UTC, merged