Method-calling filter for use in Jinja's `map` filter.
saltstack/salt pull request #50152
Opened 2018-10-21 19:37 UTC by zer0def

### What does this PR do?
The purpose of this PR is to introduce a `method_call` Jinja filter which by itself doesn't expose new functionality, but when carefully used with other filters, like [`map()`](http://jinja.pocoo.org/docs/2.10/templates/#map), can lead to significant reduction in template boilerplate.

2018-10-21 20:55 UTC, zer0def commented
I'm also aware that returning `None` on a missing object method isn't the cleanest or most sane of ways to handle this exception and I need to evaluate better handling.

2018-10-22 11:53 UTC, gtmanfred reviewed
.

2018-10-22 11:54 UTC, gtmanfred approved these changes
lgtm

2018-10-22 17:48 UTC, cachedout approved these changes
This is clever. I like it.

2018-10-22 19:02 UTC, zer0def commented
Clever until someone stubs their toe on method mutating values in-place and returning `None`.

2018-10-23 13:59 UTC, rallytime requested changes
One quick change is needed from me. The `develop` branch is currently code-named `Neon`.

2018-10-23 13:59 UTC, rallytime commented on doc/topics/jinja/index.rst
> +.. versionadded:: develop
```suggestion
.. versionadded:: Neon
```

2018-10-23 14:40 UTC, cachedout commented
@rallytime I just went ahead and changed it if you would like to re-review this, please.

2018-10-23 14:52 UTC, rallytime approved these changes

2018-10-23 14:53 UTC, merged

2020-04-21 11:23 UTC, s0undt3ch commented
Port to master https://github.com/saltstack/salt/pull/56765