Beacon to check on status endpoint
saltstack/salt pull request #50317
Opened 2018-10-30 18:50 UTC by shaidar

### What does this PR do?
Beacon to manage and report the status of a server status endpoint. It fires an event when specified values in pillar don't match returned response.

Our particular use case for this is to use it in conjunction with the [django-server-status](https://pypi.org/project/django-server-status/) and verify that specified services in pillar are functional. 

However, this is not restricted to that package and can be used with others.

### What issues does this PR fix or reference?
Don't believe there's an existing issue. Wrote it to resolve a problem we were facing.

### Tests written?

No

### Commits signed with GPG?

Yes

2018-10-30 19:51 UTC, rares-pop reviewed
There should be more pythonic ways to do the validation - you shouldn't have to do if 'foo' in dict followed by if isinstance dict['foo'] ..., but rather if isinstance(dict.get('foo', None), ....
You do the validation but is partial (i.e. you don't check for 'comp' to be valid when you do the validation).
You say nothing about html_response.
Do you want to check if the whole configuration is valid (i.e. the 'comp' is valid in all cases)

2018-10-31 18:56 UTC, cachedout commented
This is one of those cases where I think that CodeClimate has some very valid points. I think it might be worth refactoring this a bit to avoid the deeply nested control statements.

2018-11-05 21:05 UTC, cachedout requested changes

2018-11-05 21:05 UTC, cachedout commented on salt/beacons/http_status.py
> +                if cmp and not cmp in comparisons:
`if cmp and cmp not in comparisons` to satisfy the linter, please.

2018-11-06 16:44 UTC, cachedout approved these changes

2018-11-06 16:44 UTC, merged

2019-10-07 08:20 UTC, max-arnold commented
@shaidar Interesting feature, however I found a couple of issues:

* The configuration example uses the `content-type` key, but the actual implementation contains `site_config.pop('content_type', 'json')` (note the underscore)
* The `content_type` variable seems to be unused (has no effect)
* It seems to be impossible to check if a html response contains some text, because it is always gets decoded as json
* It looks like the `if r.raise_for_status` check should be used with parentheses `()`, because it is a function, and also moved inside the `try/except` block
* No tests
* The event format is undocumented
* No release notes