Port json_query Jinja filter from Ansible
saltstack/salt pull request #50428
Opened 2018-11-08 08:52 UTC by max-arnold

### What does this PR do?

This is a port of Ansible `json_query` Jinja filter to make complex queries against json data structures. Query language http://jmespath.org/ parser depends on `jmespath` python library (optional).

It could be used to filter `pillar` data, `yaml` maps, and in combination with`http_query`. Can replace lots of ugly Jinja loops and in some cases help to avoid writing trivial custom modules https://docs.saltstack.com/en/latest/topics/tutorials/jinja_to_execution_module.html

Jinja template:

```
  Example 1: {{ [1, 2, 3, 4, [5, 6]] | json_query('[]') }}

  Example 2: {{
  {"machines": [
    {"name": "a", "state": "running"},
    {"name": "b", "state": "stopped"},
    {"name": "b", "state": "running"}
  ]} | json_query("machines[?state=='running'].name") }}

  Example 3: {{
  {"services": [
    {"name": "http", "host": "1.2.3.4", "port": 80},
    {"name": "smtp", "host": "1.2.3.5", "port": 25},
    {"name": "ssh",  "host": "1.2.3.6", "port": 22},
  ]} | json_query("services[].port") }}
```

Rendered output:

```
  Example 1: [1, 2, 3, 4, 5, 6]

  Example 2: ['a', 'b']

  Example 3: [80, 25, 22]
```

### Tests written?

Yes

### Commits signed with GPG?

No

P.S. The feature is not intrusive, how about including it into the Fluorine branch?

2018-11-08 08:58 UTC, dwoz approved these changes

2018-11-08 09:34 UTC, isbm requested changes

2018-11-08 09:34 UTC, isbm commented on salt/utils/data.py
> +        raise RuntimeError('json_query filter requires jmespath library which is not installed')
Please remove "which is not", this is redundant.

2018-11-08 09:34 UTC, isbm commented on salt/utils/data.py
> +    if jmespath is None:
Please add `log.error` to record this.

2018-11-08 10:03 UTC, max-arnold commented on salt/utils/data.py
> +    if jmespath is None:
Done

2018-11-08 12:49 UTC, isbm requested changes

2018-11-08 12:49 UTC, isbm commented on salt/utils/data.py
> +        err = 'json_query filter requires installed jmespath module'
"json_query requires jmespath module installed". No?

2018-11-08 13:34 UTC, max-arnold commented on salt/utils/data.py
> +        err = 'json_query filter requires installed jmespath module'
Fixed :)

2018-11-08 13:41 UTC, isbm approved these changes

2018-11-08 13:41 UTC, max-arnold commented
Are jinja filters accessible in other salt modules as simple functions?

2018-11-08 17:00 UTC, cachedout approved these changes
I really like this. Excellent idea.

2018-11-08 17:01 UTC, merged

2019-07-15 17:17 UTC, mchugh19 commented
Great! Probably needs a mention in the release notes as well.

2019-07-16 12:56 UTC, max-arnold commented
@mchugh19 Oops, I completely forgot about that. Thanks for the reminder!  Fixed in #53866