Acceptance wait time
saltstack/salt pull request #50457
Opened 2018-11-09 20:13 UTC by jacksontj

### What does this PR do?
Always enforce `acceptance_wait_time` if a retry is going to happen

### Previous Behavior
If the exception wasn't a `SaltClientError` it would spin indefinitely

### New Behavior
Wait the configured time

2018-11-09 20:47 UTC, cachedout approved these changes

2018-11-09 22:09 UTC, isbm requested changes

2018-11-09 22:09 UTC, isbm commented on salt/minion.py
> +                yield tornado.gen.sleep(auth_wait)  # TODO: log?
Please debug log this incident.

2018-11-09 22:09 UTC, isbm commented on salt/minion.py
> +                yield tornado.gen.sleep(auth_wait)  # TODO: log?
Yep. Debug log this please.

2018-11-13 19:50 UTC, jacksontj commented
I've added debug logging prior to the sleep which includes (1) what it is connecting to (2) how long it will sleep (3) what the max sleep is.

2018-11-16 20:00 UTC, cachedout commented
@isbm Can you please review these changes and approve them if you're happy with them? Thanks.

2018-11-19 10:12 UTC, isbm approved these changes

2018-11-20 17:25 UTC, merged