Set Windows winrepo_cache_expire_min improve performance for windows package processing
saltstack/salt pull request #50508
Opened 2018-11-14 14:46 UTC by damon-atkins

### What does this PR do?
Set Windows `winrepo_cache_expire_min` improve performance for windows package processing

### What issues does this PR fix or reference?
Slowness of the Windows Package System when repeating salt executions on minions, from recent comments in the 2018 Salt Conference.

### Previous & New Behavior
Examples
* Refresh package definitions every time a high state is called. Now only if the last high state was longer than 30 minutes ago.
* Effects other pkg functions which default to refresh=True.

Note: pkg.refresh_db will force a refresh.

### Tests written?
No - This feature has existing for several releases.

2018-11-14 14:47 UTC, isbm approved these changes

2018-11-14 17:34 UTC, dwoz approved these changes

2018-11-14 21:26 UTC, twangboy requested changes

2018-11-15 14:32 UTC, damon-atkins commented
Doco check failed due to python error.

2018-11-15 17:17 UTC, twangboy approved these changes

2018-11-16 19:40 UTC, cachedout approved these changes

2018-11-16 19:40 UTC, merged