[develop] Manage schedule and manage beacons cleanup
saltstack/salt pull request #50505
Opened 2018-11-13 22:55 UTC by garethgreenaway

### What does this PR do?
Manage schedule and manage beacons cleanup

### What issues does this PR fix or reference?
N/A

### Tests written?
No.  Existing tests for managing beacons and scheduler.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-11-14 10:40 UTC, isbm requested changes

2018-11-14 10:40 UTC, isbm commented on salt/minion.py
> +            funcs[func]
This is wrong. You've already called _all of the them_ while creating the `func` dictionary and then not sure what you're trying to do by accessing merely dictionary element. I think you wanted to do this:

```python
functions = {'delete': (name, persist)), 
            'add': (schedule, persist), 
            'modify': (name, schedule, persist)}  # ...and so on
try:
    getattr(self.schedule, functions.get(func))(*params)
except TypeError:
    log.error('Function %s not found', func)
    
```

2018-11-14 10:40 UTC, isbm commented on salt/minion.py
> +            funcs[func]
Please see the comment above.

2018-11-14 10:56 UTC, isbm commented
Also please add unit tests for this part and make sure proper functions are called on demand:

```
$ grep manage_schedule test_minion.py
$
```

2018-11-15 15:02 UTC, isbm requested changes

2018-11-16 17:40 UTC, terminalmage approved these changes

2018-11-16 19:41 UTC, merged