Fix inconsistency with `pkg.list_pkgs` when using `attr` on RHEL systems
saltstack/salt pull request #50563
Opened 2018-11-19 13:30 UTC by meaksh

### What does this PR do?
This PR fixes an issue on the `pkg.list_pkgs` method when using `attr` parameter on RHEL systems.

On past PRs we've introduced the use of `attr` on `pkg.list_pkgs` on the Zypper/Yum modules for collecting not only the package version string but instead getting the desired RPM attributes (like `epoch`, `install_date`, `release`, etc) in an unified and structured way.

So when using `attr` the output from `pkg.list_pkgs` will follow this specific format for `attr='release,arch'`):
```yaml
"package": [
  {
    "version": "value1",
    "release": "value2",
    "arch": "value3",
  },
  {
    "version": "value4",
    "release": "value5",
    "arch": "value6",
  }
]
```
As you can see, the format is meant to group all installed versions of the same package (with its RPM attributes) into a single key `package` which holds a list containing a dict with all attrs for each installed version.

### Previous Behavior

On SUSE systems there is no problem since packages with different architectures always have different names, like `glibc` and `glibc-32bit` :+1: 

But the problem is happening on RHEL systems, where the architecture is internally handled by Salt as part of the package name. This is leading into an inconsistent looking output from `pkg.list_pkgs` according with the proposed format when using `attr`:

```json
$ salt-call --local pkg.list_pkgs attr='arch,release' --output=json

...
        "glibc": [
            {
                "release": "1.212.el6", 
                "version": "2.12", 
                "arch": "x86_64"
            }
        ], 
        "glibc.i686": [
            {
                "release": "1.212.el6", 
                "version": "2.12", 
                "arch": "i686"
            }
        ],
...
```

### New Behavior

The expected output should consider `glibc` and `glibc.i686` as the same package and group them into the same dict key. The output should be:
```json
$ salt-call --local pkg.list_pkgs attr='arch,release' --output=json

...
        "glibc": [
            {
                "release": "1.212.el6", 
                "version": "2.12", 
                "arch": "i686"
            }, 
            {
                "release": "1.212.el6", 
                "version": "2.12", 
                "arch": "x86_64"
            }
        ], 
...
```

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-11-19 13:55 UTC, isbm requested changes

2018-11-19 13:55 UTC, isbm commented on salt/modules/pkg_resource.py
> +        return ret_attr
This loop over `attrs` is not even needed. Try/except here is also overkill. And `pass` in try/except is just not nice. I would write it differently (and shorter): 

```python
try:
    _name, _arch = name.rsplit('.', 1)
except ValueError:
    _name, _arch = None, None

for all_attr in ret[name]:
    pkgname, filtered_attr = None, {}
    for key in requested_attr:
        if all_attr.get(key):
            filtered_attr[key] = all_attr[key]
    versions.append(filtered_attr)
    if _name and filtered_attr.get('arch', None) == _arch:
        pkgname = _name
    ret_attr.setdefault(pkgname or name, []).extend(versions)
```

This is also covering bug you've missed when `"foo."` is splitted as `['foo', '']`. If `attrs['arch']` is an empty string, you're in trouble. While it is untested, you've got the picture. :wink:

2018-11-19 15:53 UTC, meaksh commented
@isbm this should be ready now :+1:

2018-11-21 10:26 UTC, isbm approved these changes

2018-11-26 18:05 UTC, terminalmage reviewed
This is the wrong approach, IMO. This is a yum-specific approach, and will break `pkg` states on distros which use APT-based package managers. This is because our current approach with regard to 32-bit packages on 64-bit distros is to match the package manager's naming convention. That means `pkgname.i686` when using yum/dnf, but `pkgname:i686` when using apt.

Moreover, if we're going to make a change to how `pkg.list_pkgs` works, it should coincide with a different approach in states as well, one where we pass the architecture as its own parameter and not in the package name. Any such change should be made in the `develop` branch, and _not_ in a point release, and it should be made in such a way that we ensure it works on all package managers.

2018-11-27 13:29 UTC, isbm requested changes
Ohh, @terminalmage, my fault approving this. Didn't noticed this is against `2018.3`, sorry. While I am not entirely sure this has that much impact, yet it indeed has to be against `develop` branch at first place. 

But seems the roots of these sort of issues are related to [this RFC](https://github.com/saltstack/salt/pull/45948). Seems like it was an attempt by @meaksh to [follow this comment](https://github.com/saltstack/salt/pull/45948#issuecomment-417336326) if I am not mistaken. While it is OK, I'd say first we need the final agreement on this.

@cachedout @terminalmage so what do we do with [this RFC](https://github.com/saltstack/salt/pull/45948)? I find @terminalmage 's [proposal](https://github.com/saltstack/salt/pull/45948#issuecomment-417336326) a nice, acceptable compromise. Can we all agree on that?

If we agreed on the RFC, then we should take care of states too, so not breaking anything, as @terminalmage pointed out.

2018-11-28 19:09 UTC, terminalmage commented
I think the format change for pkg.list_pkgs as @isbm and I discussed privately (and linked to [here](https://github.com/saltstack/salt/pull/45948#issuecomment-417336326)) is the right thing to do. However, this needs to be implemented across _all_ `pkg` virtual modules. And like I said in my review, we need accept the architecture as an argument (probably called `arch`) which must be properly handled by all the relevant `pkg` virtual modules in their `install`, `remove`, `purge`, etc. functions. Even those package managers which don't have a concept of alternate architectures (i.e. packages which don't match the OS arch) will need to _accept_ the argument and log something if the value is not `None`.

2018-12-13 11:56 UTC, meaksh commented
Hey @cachedout, I'd like to do it as soon as I have some free cycles to work on this. If you don't mind, please leave this here for some more time. Thanks :+1:

2018-12-13 16:51 UTC, cachedout commented
@meaksh No problem at all. Thanks for the update.

2019-01-09 11:40 UTC, meaksh commented
@isbm @terminalmage - I think this looks better now. I've also created the new PR to `develop`.

Closing this in favor of https://github.com/saltstack/salt/pull/51108

2019-01-09 11:40 UTC, closed without merging