git_pillar: Allow root and mountpoint parameters together
saltstack/salt pull request #50626
Opened 2018-11-24 20:09 UTC by sathieu

### What does this PR do?
It allows to specify both `mountpoint` and `root` parameters.

### What issues does this PR fix or reference?
Fixes: #50364

### Previous Behavior
Consider the following master config:
```yaml
ext_pillar:
  - git:
    - master https://mydomain.tld/top.git:
      - root: pillar
      - mountpoint: ''
    - master https://mydomain.tld/myapp1.git:
      - root: pillar/myapp1
      - mountpoint: myapp1
    - master https://mydomain.tld/myapp2.git:
      - root: pillar/myapp2
      - mountpoint: myapp2
```
The `root` parameter is ignored.

### New Behavior
The `root` parameter is properly applied.

### Tests written?

Yes

### Commits signed with GPG?

Yes

2018-11-27 11:24 UTC, isbm requested changes

2018-11-28 07:21 UTC, sathieu commented on salt/utils/gitfs.py
> +        lcachedest = repo.check_root()
Done

2018-11-28 17:49 UTC, cachedout commented
@sathieu This has caused quite a few test failures. Could you please investigate?

2018-11-28 20:29 UTC, sathieu commented
@cachedout Fixed.

2018-11-29 18:16 UTC, cachedout commented
Thanks, @sathieu. I would like to have @terminalmage look at this before it goes in but I think we're just about there. :)

2018-12-05 05:16 UTC, sathieu commented
@terminalmage Do you have the time to review?

2018-12-05 17:46 UTC, terminalmage approved these changes

2018-12-05 17:46 UTC, merged