Better handle errors in entry points
saltstack/salt pull request #50632
Opened 2018-11-26 04:26 UTC by astronouth7303

### What does this PR do?

Fixes entry point loading, so that if it fails, the exception is logged instead of propagated to the larger system. 

### What issues does this PR fix or reference?

None.

### Previous Behavior
The minion would fail to start if there was any kind of problem with entry point loading.

### New Behavior
The exception is logged instead.

### Tests written?

No, and I'm not sure how or where.

### Commits signed with GPG?

Yes.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2018-11-26 16:44 UTC, cachedout commented
Is there a bug filed against this issue? I have never heard of this failing before and I am curious as to why it would do so. I'd love to see the exact stacktrace here.

2018-11-26 22:44 UTC, astronouth7303 commented
I found problems where if you have a bad entry point declared (in my case, because of copy/paste errors and then the code wasn't being packaged), then salt won't start. There's also weird things that happen if there's a problem in the called function.

You probably hadn't heard of anyone encountering this problem because this feature is completely undocumented (see #50633) and nobody has used it as far as I know. (Except now, because this is super helpful for my own projects.)

2018-11-27 14:00 UTC, isbm requested changes

2018-11-27 17:57 UTC, cachedout commented
@astronouth7303 Thanks for the explanation. This is a reasonably safe change for us so we're happy to get this in but I do think you should make the changes that @isbm recommends before we merge it.

2018-11-28 19:53 UTC, astronouth7303 commented on salt/loader.py
> +                    log.exception("Error running entry point %r", entry_point)
The developer would certainly strongly appreciate the traceback, and I would consider any time this code is triggered to be a bug in some third-party code.

2018-11-28 20:56 UTC, astronouth7303 commented
Ok, logging is improved.

2018-11-29 18:17 UTC, cachedout requested changes

2018-11-29 18:17 UTC, cachedout commented on salt/loader.py
> +    """
The Salt style guide indicates that these should be three single-quotes.

2018-11-29 23:35 UTC, isbm approved these changes

2018-11-30 18:49 UTC, cachedout approved these changes

2018-11-30 18:49 UTC, merged