Add jsonnet salt module
saltstack/salt pull request #50735
Opened 2018-12-04 14:26 UTC by bbinet

This module provides parsing support of jsonnet format (which is a
data templating language based on json).

This module depends on the jsonnet Python module which can be installed
with "pip install jsonnet".

2018-12-06 18:18 UTC, cachedout requested changes

2018-12-06 18:18 UTC, cachedout commented on salt/modules/jsonnet.py
> +            with open(full_path) as f:
Please use `salt.utils.files.fopen`

2018-12-07 08:40 UTC, bbinet commented on salt/modules/jsonnet.py
> +            with open(full_path) as f:
@cachedout Done in 64b6054.

2018-12-10 17:07 UTC, cachedout approved these changes

2018-12-10 17:07 UTC, merged

2019-09-04 16:35 UTC, max-arnold commented
Maybe it would be better to convert this into a serializer module?