WIP Allow dynamic file_roots
saltstack/salt pull request #50784
Opened 2018-12-07 06:17 UTC by sathieu

### What does this PR do?
Implements Dynamic File Roots:
```
file_roots:
  base:
    - /srv/salt
  __env__:
    - /srv/default/salt
```

### What issues does this PR fix or reference?
Fixes: #48132. Similar to #46309 for `pillar_roots`.

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

No. Hence the WIP.

### Commits signed with GPG?

Not yet (WIP).

2018-12-10 16:36 UTC, cachedout commented
@sathieu We would want to put this into the develop branch. Right now it's on a bug fix branch which is not where it would ultimately get merged. You may wish to switch this. :)

2018-12-11 14:34 UTC, sathieu commented
Ok. Anyway it doesn't work. Any idea how to fix this?

does this means that 2018.3.4 is coming soon?

2018-12-11 16:33 UTC, cachedout commented
@sathieu What do you mean by "it doesn't work"? Do you mean that this feature isn't doing what you intend it to or are you referring to some other functionality that isn't working as expected?

2018-12-11 20:30 UTC, sathieu commented
@cachedout My PR doesn't work. I have other problems but they may come from my specific version (2018.3.3 + several PRs).

2019-01-17 14:23 UTC, sathieu commented
Now working. And rebased on top of #51211.

2019-01-17 17:30 UTC, dwoz approved these changes

2019-01-23 07:40 UTC, sathieu commented
@terminalmage can youbplease review? Without this, using gitfs with file_roots is limited to a list of branches

2019-01-23 14:58 UTC, terminalmage requested changes

2019-01-23 14:58 UTC, terminalmage commented on salt/state.py
> +                        statefiles = fnmatch.filter(self.avail[saltenv], sls_match)
The old code used a try/except, but your changes introduce a membership check, which seems to make the try/except redundant. In cases where the saltenv is not present and `__env__` is not configured in `file_roots`, we do both a membership check _and_ a lookup, which we _know will fail_, and we also incur the overhead of raising and handling the exception. IMO it's better to use the results of the membership check to determine whether or not the saltenv could be found, perhaps like this:

```python
if saltenv in self.avail:
    statefiles = fnmatch.filter(self.avail[saltenv], sls_match)
else:
    if '__env__' in self.avail:
        statefiles = fnmatch.filter(self.avail['__env__'], sls_match)
    else:
        all_errors.append(
            'No matching salt environment for environment '
             '\'{0}\' found'.format(saltenv)
        )
```

2019-01-26 09:12 UTC, sathieu commented
I've added doc in `doc/ref/configuration/master.rst`. @terminalmage please review...

2019-01-28 16:55 UTC, terminalmage approved these changes

2019-02-06 19:52 UTC, sathieu commented
@terminalmage @dwoz You both approved. Anything missing?

2019-02-06 20:01 UTC, terminalmage commented on doc/ref/configuration/master.rst
> +As of 2018.3.4, it is possible to have `__env__` as a catch-all environment.
Can you change this to "2018.3.5 and 2019.2.1"? This missed the branching for both 2018.3.4 and 2019.2.0. Other than that I have no problem merging it.

2019-02-08 10:10 UTC, sathieu commented
@terminalmage you can merge, I've updated the versions.

2019-02-08 18:09 UTC, merged

2019-02-08 18:59 UTC, sathieu commented
@terminalmage @dwoz thanks to you both!