fix error when exception message is not ascii
saltstack/salt pull request #50865
Opened 2018-12-14 15:15 UTC by Denislb

### What does this PR do?

Pass the exception string instead of the object when an error occured in multiprocessing logging.

### Previous Behavior

Sometimes, my minion gets an error like below. I discovered that was due to an errno message that contains utf-8 characters.

`Process Process-1:
Traceback (most recent call last):
  File "C:\salt\bin\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\salt\bin\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 1076, in __process_multiprocessing_logging_queue
    'queue thread: %s', exc, exc_info_on_loglevel=logging.DEBUG
  File "C:\salt\bin\lib\logging\__init__.py", line 1179, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 328, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "C:\salt\bin\lib\logging\__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 375, in makeRecord
    exc_info, func)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 209, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "C:\salt\bin\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 24: ordinal
 not in range(128) `

I do not really know why, but the memory increased exponentially like below.
![image](https://user-images.githubusercontent.com/7715984/50010357-7f9f9e80-ffb9-11e8-82f4-fb1b1b3c54dd.png)

### New Behavior

Now the error message is well displayed like below.
> [WARNING ] An exception occurred in the multiprocessing logging queue thread: [Errno 234] Plus de données sont disponibes

### Tests written?

No

### Commits signed with GPG?

No

2018-12-28 23:25 UTC, s0undt3ch reviewed
Although it solves your issue, this does not seem like the right fix.

If you do something like:
```
logging.getLogger(__name__).warning(
    u An exception occurred in the multiprocessing logging '
    u'queue thread: %s', exc,
    exc_info_on_loglevel=logging.DEBUG)
```
Does it work?

2019-01-02 08:46 UTC, Denislb commented
Hi,

I tried your first solution, I still have an exception error.

Then, I tried to use [decode](https://github.com/saltstack/salt/blob/develop/salt/utils/data.py#L79) and I still have am exception error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 24: ordinal not in range(128)`, same error when I try with [encode](https://github.com/saltstack/salt/blob/develop/salt/utils/data.py#L249).

2019-01-02 09:57 UTC, s0undt3ch commented
With `salt.utils.stringutils.to_unicode`?

2019-01-02 10:31 UTC, Denislb commented
An error occurred when I try this.

```Traceback (most recent call last):
  File "C:\salt\bin\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\salt\bin\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 1077, in __process_multiprocessing_logging_queue
    'queue thread: %s', salt.utils.stringutils.to_unicode(exc), exc_info_on_loglevel=logging.DEBUG
  File "C:\salt\bin\lib\site-packages\salt\utils\stringutils.py", line 125, in to_unicode
    raise TypeError('expected str or bytearray')
TypeError: expected str or bytearray

2019-05-03 08:47 UTC, dwoz commented
re-run all

2019-05-03 09:21 UTC, dwoz requested changes
Sorry it's taken so long to get this moved forward. I think I actually prefer this:

`'queue thread: %r', exc, exc_info_on_loglevel=logging.DEBUG`

2019-05-23 22:07 UTC, untra commented
whats the status of this? I think we are currently hitting the same issue in the 2018.3 salt-minion.

2019-12-14 00:54 UTC, dwoz commented
@Denislb We are no longer merging to the `develop` branch. Can you please rebase this to the `master` branch?

2019-12-27 23:55 UTC, dwoz commented
@Denislb I've updated this  branch and pointed the PR to master.

2019-12-27 23:56 UTC, dwoz approved these changes

2020-01-02 09:45 UTC, merged