user: add subuid/subgid user function
saltstack/salt pull request #50950
Opened 2018-12-20 23:31 UTC by toanju

This adds subuid/subgid configuration to support user namespaces in Linux.

2019-01-03 02:00 UTC, twangboy approved these changes

2019-01-03 02:01 UTC, garethgreenaway commented
@toanju Nice addition!  Some unit tests would be appreciated, then we can get this merged in.

2019-01-03 11:01 UTC, toanju commented
thanks, I will add them later this week.

2019-01-03 15:30 UTC, terminalmage requested changes

2019-01-03 15:30 UTC, terminalmage commented on salt/modules/useradd.py
> +        log.warning("'subuids' are only supported on GNU/Linux hosts.")
The warnings you've added in each of these functions are unnecessary, as this module will not be loaded on non-Linux minions (see [here](https://github.com/saltstack/salt/blob/501079fffc95f50f338d50eaa9dfd1078c8bc0c5/salt/modules/useradd.py#L40-L47)).

The warnings in each of the new functions you've added should be removed.

2019-01-03 15:31 UTC, terminalmage commented on salt/modules/useradd.py
> +        log.warning("'subuids' are only supported on GNU/Linux hosts.")
Oh, disregard... I was under the impression that pw was used on the other BSD variants, and AIX was also added to the list of OSes which uses this module.

My bad!

2019-01-03 15:31 UTC, terminalmage approved these changes

2019-02-14 02:57 UTC, merged

2022-06-06 19:52 UTC, Ch3LL commented
It needs to be merged into master. This PR https://github.com/saltstack/salt/pull/57020 attempts to do that but requires a changelog and test coverage as stated here: https://github.com/saltstack/salt/pull/57020#issuecomment-1013442471