Added a note in Release notes about py 2.7 EOL
saltstack/salt pull request #51234
Opened 2019-01-17 22:45 UTC by KChandrashekhar

### What does this PR do?
Added a note in Release notes about py 2.7 EOL

### What issues does this PR fix or reference?
NA

### Tests written?

Not needed

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-01-17 22:53 UTC, Ch3LL requested changes

2019-01-17 22:53 UTC, Ch3LL commented on doc/topics/releases/2019.2.0.rst
> +Note: In light of Python 2.7 reaching its End of Life (EOL) on Jan 1st 2020,
Might be good to add a header above here so its more obvious, something like:

```
Python 2.7 Deprecation
======================
```

2019-01-18 08:17 UTC, s0undt3ch approved these changes

2019-01-18 15:52 UTC, Ch3LL approved these changes

2019-01-18 15:53 UTC, merged