[fluorine] Merge forward from 2019.2 to develop
saltstack/salt pull request #51284
Opened 2019-01-22 20:34 UTC by garethgreenaway

Merge branch '2019.2' into merge-develop

 Conflicts:
   - Pipfile
   - doc/topics/releases/2019.2.0.rst
   - requirements/pytest.txt
   - salt/modules/cmdmod.py
   - salt/modules/nxos.py
   - salt/modules/virt.py
   - salt/modules/win_lgpo.py
   - salt/states/cmd.py
   - salt/states/virt.py
   - salt/utils/network.py
   - tests/unit/utils/test_network.py

2019-01-22 20:37 UTC, Ch3LL requested changes

2019-01-22 20:37 UTC, Ch3LL commented on salt/utils/network.py
> +>>>>>>> 2019.2
missed the '>>>>>'

2019-01-22 20:37 UTC, Ch3LL commented on salt/utils/network.py
> +<<<<<<< HEAD
missed merge conflict here too

2019-01-23 07:15 UTC, s0undt3ch approved these changes

2019-01-23 07:16 UTC, merged