Allow to override git_pillar_base per-remote
saltstack/salt pull request #51464
Opened 2019-02-01 12:58 UTC by sathieu

### What does this PR do?

Allow to override git_pillar_base per-remote

### What issues does this PR fix or reference?
None.

### New Behavior
Example:
```yaml

git_pillar_base: develop

ext_pillar:
  - git:
    - __env__ https://gitserver/git-pillar.git
    - __env__ https://gitserver/git-pillar2.git:
      - base: master
```

### Tests written?

No

### Commits signed with GPG?

Not yet

2019-02-02 08:11 UTC, sathieu commented
Yes. This is a feature.

Can we have any visibility on the release schedule?

2019-02-04 20:59 UTC, terminalmage commented
Can you please help me understand the purpose of this? git_pillar doesn't work like gitfs.

2019-02-05 08:52 UTC, sathieu commented
I know, and it's annoying. But with `__env__` it starts to behave similarly.

Our use case: we have different projects (I.e apps) some have develop, qa,staging and prod branches which corresponds to isolated salt master's `git_pillar_base`. But some projects (we call them infra, like DNS) have less branches (develop and master) and every salt-masters of every zones should point to the master branch.

2019-02-05 08:54 UTC, sathieu commented
Also, we don't configure saltenv and pillarenv on minions, but we can use them on CLI to test feature branches.

2019-02-12 14:21 UTC, terminalmage requested changes
This needs to be changed in the following two ways:

1. It must be opened against `develop`, not `2018.3`.
2. The dunder init for `Pygit2` and `GitPython` provider objects must be modified to log and run `failhard()` when `base` is used in instances where `self.branch != '__env__'`.

2019-02-13 21:19 UTC, dwoz commented
@sathieu We are currently working to stay on a 6 month release cadence. Historically we've had trouble hitting this mark but we're actively working on ways to improve in this area.

I'm going to close this PR, you can cherry-pick the change and make a PR to develop.

2019-02-13 21:19 UTC, closed without merging

2019-02-14 05:55 UTC, sathieu commented
Replaced by #51640.