fix for  grains ip6_interfaces returns ipv4 addresses if secondary #5…
saltstack/salt pull request #51513
Opened 2019-02-06 09:47 UTC by styx-tdo

…1481

### What does this PR do?
Fix ipv6 grains returning ipv4 secondary addresses

### What issues does this PR fix or reference?
#51481 

### Previous Behavior
IPv6 grains returned secondary ipv4 addresses, as the call to the network functions did not specify ipv6

### New Behavior
Filter return list to exclude ipv4

### Tests written?

No

### Commits signed with GPG?

No

2019-02-13 08:23 UTC, dwoz requested changes

2019-02-13 08:23 UTC, dwoz commented on salt/grains/core.py
> +            except:
Please add an explicit exception type here and only except the specific exception expected. This will also fix the linter. :)

2019-12-09 23:23 UTC, dwoz commented
@styx-tdo We are no longer accepting PRs to the `develop` branch. This needs to be re-opened against the `master` branch. You can link to this PR from the new one to preserve any disscussion history. Sorry for the confusion.

2019-12-09 23:23 UTC, closed without merging

2019-12-10 11:12 UTC, styx-tdo commented
nah, it's ok for me. i have fixed it in my version, so whatever. you can close and delete the request.