Allow Solarispkg to install packages which require a response file
saltstack/salt pull request #51568
Opened 2019-02-08 21:53 UTC by lomeroe

### What does this PR do?
Allows svr4 packages which require a response file to be installed by solarispkg's pkg.install

### What issues does this PR fix or reference?
#51567 

### Previous Behavior
Svr4 packages which require a response file cannot be installed via pkg.install

### New Behavior
A response file path can be provided to pkg.isntall

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-02-13 18:21 UTC, dwoz approved these changes

2019-02-13 19:48 UTC, terminalmage requested changes
This doesn't fit with how we handle remote source files in Salt. It would allow people to use http(s) sources without the protection against the remote file changes that Salt users have come to expect. 

Luckily, I wrote a state called `file.cached` which aims to address this for states/modules, by downloading a file to the minion cache and performing the typical checks. You can call this state using the `__states__` dunder. Here's an example of `archive.extracted` using it to make sure the source tar archive is cached:

https://github.com/saltstack/salt/blob/cb44691/salt/states/archive.py#L957-L975

You'd need to make minor tweaks to that to do what you need, but as long as `result['result']` is `True` the caching has succeeded and you can then use `__salt__['cp.is_cached'](response_source)` to get the local cache path. If the URL is cached, the path to it in the minion cache will be returned, and if not an empty string will be returned:

```
[root@88315cc5d355 /]# salt-call --local cp.cache_file https://docs.saltstack.com/en/latest/faq.html
local:
    /var/cache/salt/minion/extrn_files/base/docs.saltstack.com/en/latest/faq.html
[root@88315cc5d355 /]# salt-call --local cp.is_cached https://docs.saltstack.com/en/latest/faq.html
local:
    /var/cache/salt/minion/extrn_files/base/docs.saltstack.com/en/latest/faq.html
[root@88315cc5d355 /]# rm -f /var/cache/salt/minion/extrn_files/base/docs.saltstack.com/en/latest/faq.html
[root@88315cc5d355 /]# salt-call --local cp.is_cached https://docs.saltstack.com/en/latest/faq.html
local:
```

This would require you to add a `response_source_hash`, `response_source_hash_name`, and `saltenv` argument to this function, and pass them through to `__states__['file.cached']` in order to cache the response file.

2019-02-13 21:07 UTC, lomeroe commented
@terminalmage ok, admittedly I just copied what was in the module already for getting the "admin_source" parameter's file

2019-02-13 21:11 UTC, dwoz commented
@lomeroe Should we close this PR while you work on patching `file.cached`?

2019-02-14 14:46 UTC, lomeroe commented
@terminalmage what is the trick to access the  __states__ dunder in an execution module? I am getting that it is undefined if I attempt to use it...

https://docs.saltstack.com/en/latest/topics/development/modules/developing.html says __states__ is only defined in renderers and state...

I see only the "vbox_guest" execution module using the __states__ dunder, but nothing is jumping out at me that would be pulling it in to make it available there.  I also haven't tested that its usage actually works...

Some searching in code seems to turn up that many other execution modules, right or wrong, are doing what this one is doing, using the cp.cache_file execution module function to cache files that will be used by the module.

2019-02-17 01:10 UTC, terminalmage commented
Oh yeah, you might need to instantiate a loader there in the function. I think it's not typically available due to the chicken-and-egg problem of the states relying on execution modules being loaded first.

I'll look into it and let you know what you need to do.

2019-04-12 20:12 UTC, lomeroe commented
@terminalmage were you able to come up with how this should be done to meet your requested changes?

2019-11-21 17:26 UTC, terminalmage commented
@lomeroe I'm sorry I missed your reply several months ago. Yes, you will need to instantiate a loader to do it in an execution module. You could do it like so:

```python
states = salt.loader.states(
    __opts__,
    __salt__,
    __utils__,
    salt.loader.serializers(__opts__))

result = states['file.cached'](........)
```

2019-12-09 23:41 UTC, dwoz requested changes
@lomeroe Please check the linter failures.

2020-03-13 20:14 UTC, twangboy approved these changes

2020-03-13 21:44 UTC, twangboy requested changes

2020-03-13 21:44 UTC, twangboy commented on salt/modules/solarispkg.py
> +                cache_result = states['file.cached'](kwargs['admin_source'],
You should be able to use `__states__['file.cached']` here instead of going through all the loader stuff

2020-03-13 21:44 UTC, twangboy commented on salt/modules/solarispkg.py
> +                cache_result = states['file.cached'](kwargs['response_source'],
And here

2020-03-13 21:47 UTC, twangboy commented
We'll also need some tests for this

2020-03-13 22:41 UTC, thatch45 commented
I am sorry for this confusion to persist, If we want to allow calling states from execution modules we should not instantiate a new loader, that is very expensive and can mess up the loader's internal namspaces. This should be avoided. We don't have access to states from modules because there is a chicken and egg issue with the loader, because states rely on modules.
You can track down a loaded instance of states from sys.modules but this would be very strongly discouraged. logically you should not need to call states from modules. We have made MANY modules without needing to do this, we should not need to start doing it now.

2020-03-19 20:56 UTC, lomeroe commented
Thanks for the insight @thatch45, the use of the state for the file was at the request of @terminalmage 

I will revert to not using it to cache the file...

2020-05-18 22:55 UTC, twangboy commented on salt/modules/solarispkg.py
> +            __opts__, __salt__, __utils__, salt.loader.serializers(__opts__)
Aren't we going away from this?

2020-05-22 04:11 UTC, dwoz commented
@lomeroe We need the linter and docs fixed for this to make it into Sodium

2021-04-13 16:36 UTC, dmurphy18 commented
@Iomeroe Is this PR still being actively worked on, checking since the your last comment is just over a year ago.
The other reason for checking is that soon there will be a new Solaris 10 native minion available to open-source which is based on Tiamet and Python 3.7.8, and just recently during development resolved some pkg.install issues (minor).  During test development made use of the adminfile as defined in https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.solarispkg.html to by-pass response requests

2021-04-14 21:55 UTC, lomeroe commented
I think it needed tests, which I haven't circled back to.

The packages I was installing needed a response file, the adminfile wouldn't work at the time...

On April 13, 2021 11:36:46 AM CDT, David Murphy ***@***.***> wrote:
>@Iomeroe Is this PR still being actively worked on, checking since the
>your last comment is just over a year ago.
>The other reason for checking is that soon there will be a new Solaris
>10 native minion available to open-source which is based on Tiamet and
>Python 3.7.8, and just recently during development resolved some
>pkg.install issues (minor).  During test development made use of the
>adminfile as defined in
>https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.solarispkg.html
>to by-pass response requests
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/pull/51568#issuecomment-818878202

2021-04-14 23:07 UTC, dmurphy18 commented
@Iomeroe No PR is getting accepted without tests, and even if there are tests, they sometimes need to be adjusted for the exact condition which caused an issue. For example: tests/pytests/unit/modules/test_zfs_solaris10.py

For all new tests, it is recommended that they be placed in pytests, all new tests should make use of pytest.

2021-07-19 18:41 UTC, sagetherage commented
@lomeroe do you want to make this a WIP PR?

2021-07-26 18:35 UTC, sagetherage commented
Reviewed in Backlog Refinement 2021-JUL-26 considering closing

2021-08-04 15:47 UTC, lomeroe commented
@sagetherage that is fine or we can kill it...I'm not sure when I'll get around to the required tests and since this module has no existing tests (at least the last time I checked), it's unfortunately a considerable undertaking for me

2022-01-14 00:24 UTC, dmurphy18 commented
@lomeroe I have since added some Solaris 10 pytests which could be used as examples. Wondering if still interested in proceeding with this or should the issue be closed ?

For example: tests/pytests/unit/modules/test_solarispkg.py

2022-01-14 00:57 UTC, lomeroe commented
Yes, I will try to take a look at that sooner than later...

On January 13, 2022 6:24:14 PM CST, David Murphy ***@***.***> wrote:
***@***.*** I have since added some Solaris 10 pytests which could be used as examples. Wondering if still interested in proceeding with this or should the issue be closed ?
>
>For example: tests/pytests/unit/modules/test_solarispkg.py
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/pull/51568#issuecomment-1012638201
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

2022-02-11 17:53 UTC, dmurphy18 commented
@lomeroe Wondering how you are getting on with this.
I was never able to make response file work with Solaris 10, it appeared to ignore input etc, when trying with scripts on the machine.

2022-10-27 18:28 UTC, twangboy requested changes
This needs a test case and a changelog

2022-12-06 20:46 UTC, Ch3LL commented
@lomeroe did you want to come back to this PR and implement the feedback?

2023-04-19 16:43 UTC, dmurphy18 commented
The native minion support for Solaris 10 has just been released to community support, see

- https://saltproject.io/co-maintainers-wanted-for-native-minions
- https://github.com/vmware/salt-native-minion-for-solaris-10

With access to the code, perhaps you can determine the cause of the issue, and submit a PR with the fix.
I am still the maintainer for the GitHub repository, but VMware is inviting co-maintainers, if you are interested.

With support for Solaris 10 moving to a community repository, going to close this issue since not the correct place for it. Even when Salt did provide internal support for Solaris 10, it would have been actually duplicated in a GitLab repository where support for the various Native Minions was maintained, in their individual repositories.

Please duplicate the issue if you desire on the Git Hub repository https://github.com/vmware/salt-native-minion-for-solaris-10

2023-04-19 16:43 UTC, closed without merging