[develop] Merge forward from 2019.2 to develop
saltstack/salt pull request #51579
Opened 2019-02-11 18:31 UTC by garethgreenaway

Merge branch '2019.2' into merge-2019.2

 Conflicts:
   - .codecov.yml
   - pkg/osx/req.txt
   - requirements/pytest.txt
    - salt/modules/capirca_acl.py
    - salt/modules/ebuild.py
    - salt/modules/win_lgpo.py
    - salt/states/file.py
    - tests/conftest.py
    - tests/integration/__init__.py
    - tests/integration/states/test_file.py

2019-02-11 18:41 UTC, twangboy requested changes

2019-02-11 18:41 UTC, twangboy commented on tests/integration/states/test_file.py
> +<<<<<<< HEAD
Missed a thing here...

2019-02-11 18:41 UTC, twangboy commented
Windows stuff looks good

2019-02-11 18:55 UTC, twangboy approved these changes

2019-02-15 18:50 UTC, dwoz commented
I checked out develop and merged this branch. Then tried to re-produce the cherrypy test failure. It passed on centos7. In light of that I am going to merge this, if we still see that test failure I'll fix it.

2019-02-15 18:50 UTC, merged