[develop] Merge forward from 2019.2 to develop
saltstack/salt pull request #51675
Opened 2019-02-15 20:45 UTC by Ch3LL

Conflicts:
  - pkg/windows/req.txt
  - pkg/windows/req_win.txt
  - tests/integration/netapi/rest_tornado/test_app.py
  - tests/unit/states/test_file.py

2019-02-17 19:01 UTC, s0undt3ch requested changes

2019-02-19 20:04 UTC, dwoz approved these changes

2019-02-19 20:05 UTC, dwoz commented
@s0undt3ch I'm going to merge this since @Ch3LL fixed the extra comment in the Gemfile and the tests are passing.

2019-02-19 20:05 UTC, merged

2019-02-19 20:44 UTC, s0undt3ch commented
👍