grains/core: ignore HOST_NOT_FOUND errno in fqdns()
saltstack/salt pull request #51706
Opened 2019-02-19 13:24 UTC by aplanas

### What does this PR do?

We ignore also HOST_NOT_FOUND errno (actually h_errno) when trying to recover the fqdn.

2019-03-05 15:43 UTC, aplanas commented
Is ready for review. @isbm what do you think?

2019-05-14 08:44 UTC, brejoc approved these changes
lgtm

2019-05-31 22:14 UTC, waynew commented
@aplanas would it be reasonable to use the "warn once" method that we have elsewhere in the code, or does it make more sense to always ignore it?

2019-06-01 09:17 UTC, aplanas commented
Oh I like the idea. Makes sense for me. I will check how this was done before.

2019-06-03 10:44 UTC, aplanas commented
@waynew maybe I will need a bit of help here. The only place that I found where there is some kind of repetition filter for warnings is in [\_\_init\_\_.py](https://github.com/saltstack/salt/blob/develop/salt/__init__.py#L11), but this is related with exceptions, and not with logs.

2019-06-07 08:17 UTC, aplanas commented
this is potentially a bug, can we tag it for Neon?

2019-06-14 23:55 UTC, waynew commented
@aplanas I'll bring it up with @saltstack/team-core, but my feelings are that it should get in with the Neon release.

2019-08-26 08:15 UTC, aplanas commented
The clint complain is about this:

`salt/grains/core.py:51: [W1505(deprecated-method), linux_distribution] Using deprecated method _deprecated_linux_distribution()`

As I do not touch this piece of code at all, can we review the patch? This is taking too long IMHO.

2019-08-29 08:47 UTC, aplanas commented
> Looks like we should just tell lint to ignore that line, apparently we're already aware of it - especially if we want to put this change into neon as well. If we're just going into the Sodium release we should be able to just remove the entire other block of code.

I like your idea. If Sodium is Python3 there is no reason to maintain the old code that makes it compatible with Python2. Let me add an extra patch for this.

2019-08-30 16:37 UTC, waynew approved these changes

2019-10-11 15:59 UTC, aplanas commented
Rebased into the new master (from develop), any chance now?

2019-10-14 19:33 UTC, waynew requested changes
Hey @aplanas this is looking great (and, apologies for the lengthy process on this one 😞 )

Would you be able to write a test for this? I'm hoping that it shouldn't be too much effort and we have something already testing around this area...

2019-10-15 09:32 UTC, aplanas commented
@waynew I added a test. Can you re-review?

2019-10-17 13:28 UTC, waynew approved these changes
🚀 Sweet action!

I know we currently have some issues around our Mac testing infrastructure that we're working on, but otherwise this should be ready to go. I did notice some Centos failures that I need to check out before we merge this.

2019-10-17 13:29 UTC, waynew commented
Ah. It was a test from an unrelated thing (we *do* still need to fix that, so we'll probably need to do one more rebase 🤞 after we fix the mac/other issue elsewhere)

2019-11-06 10:15 UTC, aplanas commented
I am loosing hope that this, or any of my [others PR](https://github.com/saltstack/salt/pulls/aplanas?page=2&q=is%3Aopen+is%3Apr+author%3Aaplanas) will be merged ever: there is no way to have a green CI result after almost one year of rebasing (or moving the code between branches)

We have 49(!) checks in place, but they are still randomly failing, making very hard to differentiate between a useful failing report, from noise.

Can we have a more strict policy in place, where we trade off a super big number of checks with reliable ones? For example, if **ci/py2/macosxmojave** is broken, lets disable it with urgency before re-adding it once that is fixed.

2019-11-06 13:09 UTC, aplanas commented
**ci/py3/debian10** fail seems unrelated:

```
11:51:30         ======================================================================
11:51:30         FAIL [29.945s]: test_pkg_latest_version (integration.modules.test_pkg.PkgModuleTest)
11:51:30         ----------------------------------------------------------------------
11:51:30         Traceback (most recent call last):
11:51:30           File "/tmp/kitchen/testing/tests/support/helpers.py", line 121, in wrap
11:51:30             return caller(cls)
11:51:30           File "/tmp/kitchen/testing/tests/support/helpers.py", line 1154, in wrapper
11:51:30             return caller(cls)
11:51:30           File "/tmp/kitchen/testing/tests/support/helpers.py", line 1077, in decorator
11:51:30             return func(*args, **kwargs)
11:51:30           File "/tmp/kitchen/testing/tests/integration/modules/test_pkg.py", line 362, in test_pkg_latest_version
11:51:30             self.assertIn(pkg_latest, cmd_pkg)
11:51:30         AssertionError: "ERROR: E: Repository 'https://repo.saltstack.com/apt/debian/9/amd64/latest stretch InRelease' changed its 'Suite' value from 'stable' to 'oldstable'" not found in '\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nListing...\nfiglet/stable,now 2.2.5-3 amd64 [residual-config]'
```

2019-11-07 15:07 UTC, aplanas commented
This is as green as I can get. The current fails, IIUC, are timeouts. I am not able to diagnose the reason of the VM timeout, tho.

2019-12-09 23:36 UTC, merged