Fix file removal
saltstack/salt pull request #51844
Opened 2019-02-26 19:19 UTC by mbunkus

### What does this PR do?

It fixes the `file.remove` module function and `file.symlink` state function to handle removal of existing directory entry types other than files, symlinks or directories: both files failed when the existing entry was e.g. a socket or a FIFO.

### What issues does this PR fix or reference?

Both together fix #35621.

### Previous Behavior

Before the fix the `file.remove` module function did nothing and returned `False` when asked to remove an existing socket or FIFO.

The `file.symlink` state function returned an error that the entry already exists when asked to replace an existing socket or FIFO with a symlink, even if `force=True` was set. The function did not attempt to remove the entry.

### New Behavior

Both functions will now handle all existing entries: directories are still removed recursively whereas other existing entries are removed via `os.remove()` no matter their type.

### Tests written?

No

### Commits signed with GPG?

Yes

2019-03-25 03:40 UTC, cachedout requested changes
The logic here looks very sound but I think this behavior should be documented in a changelog entry before this is merged. It's possible that somebody was relying on the old (incorrect) behavior.

2019-03-25 10:26 UTC, mbunkus commented
I guess you mean adding such a `.. versionchanged:` section in the doc section of both functions? Sure, I can do that. Which version number should I put there?

2019-03-26 18:47 UTC, twangboy commented
@mbunkus Neon

2019-03-26 19:16 UTC, mbunkus commented
I've added `versionchanged` entries to the docs of both files, re-based on today's `develop` branch & force-pushed. Please re-review. Thanks :)

2019-03-26 19:43 UTC, mbunkus commented
Oh, wait. I'll take care of the tests, too.

2019-03-26 20:23 UTC, mbunkus commented
I've fixed the logic & force-pushed. For me `integration.modules.test_file` and
`integration.states.test_file` pass now.

However, ` unit.states.test_file.TestFileState.test_symlink` still fails with:

```
Traceback (most recent call last):
  File "/net/sweet-chili/home/mosu/prog/salt/tests/unit/states/test_file.py", line 298, in test_symlink
    backupname='SALT'),
  File "/net/sweet-chili/home/mosu/prog/salt/salt/states/file.py", line 1700, in symlink
    __salt__['file.symlink'](target, name)
KeyError: u'file.symlink'
```

I can't make heads or tails of it. Can someone please help with with why that happens? It seems like the `file` module could not be loaded… but there isn't really any other output that could shed some light on the problem.

2019-06-21 19:55 UTC, garethgreenaway commented
@mbunkus Updating your branch to get the tests to rerun, hopefully it was just a fluke.  Can you also include a note in the release notes here (https://github.com/saltstack/salt/blob/neon/doc/topics/releases/neon.rst) about that change?  Thanks!

2019-06-21 20:44 UTC, mbunkus commented
I've rebased my changes on the current `develop` branch and added a commit adding comments to `neon.rst`.

Then I tried running the `unit.states.test_file`, and that one still fails with the aforementioned `key error`. Like I said above, not being a regular Salt developer I really have no idea why that happens, much less how to fix the issue.

Can someone more knowledgeable with Salt's test procedures than me **please** help with this? Thanks.

2019-06-21 21:06 UTC, mbunkus commented
Alright, I know what's happening & how to fix it.

2019-06-21 21:09 UTC, mbunkus commented
I've fixed the tests & force-pushed. On my machine both the state & the module tests succeed now. Hopefully they do on Jenkins, too.

2019-06-23 13:32 UTC, mbunkus commented
Sooooo… now that all tests have passed, any chance of getting this merged? Anything else I can do?

2019-07-12 09:27 UTC, mbunkus commented
Ping! Anything else I can do to finally get this merged?

2020-01-07 08:23 UTC, mbunkus commented
I have to say I'm very disappointed how this PR has been handled. This is a bug fix, not some obscure feature enhancement. I've invested quite a lot of time figuring everything out wrt. test setups, running tests & how mocks work without a lot of (if any) help from the Salt community. And even after getting everything ready and pinging multiple times the PR hasn't been merged, nor has there been any feedback what's needed in order to get it merged. In short: it has been completely disregarded.

The bug it fixes is 3.75 years old now!

The handling of this bug is one of the reasons that motivated me to move away from Salt, meaning I won't spend any more time getting this thing merged (or even updated so that it works again). If you want the fix, please do something about it soon. I'll probably remove my cloned Salt git repo including the fix in a month or two.

2020-01-07 16:03 UTC, dwoz commented
@mbunkus Sorry for the extremely slow turn-around on this one. We've been making some changes to our process which should start to help us work through the PR backlog more quickly.  I've rebased this to `master` branch and will keep an eye on it.

2020-01-11 10:28 UTC, dwoz approved these changes

2020-01-11 10:28 UTC, merged