saltnado: don't include data root key
saltstack/salt pull request #51979
Opened 2019-03-05 18:54 UTC by mattp-

### What does this PR do?
made a minor mistake in my previous commit, since these rets are
straight off the get_event wire they come in that format; but the
subdict under 'data' is closer to what sync full_return would give.

sorry I missed this yesterday @dwoz 

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-05-16 15:47 UTC, Ch3LL requested changes
can you add a regression test for this fix?

2019-06-06 21:43 UTC, Ch3LL commented
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

2019-06-27 14:40 UTC, mattp- commented
@Ch3LL the regression tests for these are actually covered indirectly in the pepper test suite, which is covering salt-api via both cherrypy and tornado. I think that is sufficient for this?

2019-07-02 14:35 UTC, Ch3LL commented
If possible I would prefer to add tests here in salt as well so as we make changes in salt we can rely on your fix not regressing.

2021-12-13 21:53 UTC, Ch3LL commented
This needs to be moved to the master branch. Any chance you will have the bandwidth to add test coverage?

2022-11-03 20:28 UTC, Ch3LL commented
Did you want to come back to this one and migrate to the master branch and add test coverage?

2022-11-03 22:08 UTC, mattp- commented
Wow 4 years old. I do still plan to get to this at some point, but obviously not super high on my priority list at the moment.

2022-11-07 20:19 UTC, Ch3LL commented
Yeah, lets go ahead and close this since it still needs to be pushed to the `master` branch and then when you are ready to push the changes you can open a new PR. Thanks for following up.

2022-11-07 20:19 UTC, closed without merging