Copy opts to avoid cache poisioning
saltstack/salt pull request #51991
Opened 2019-03-06 00:50 UTC by waynew

### What does this PR do?

Creates a copy of the opts dictionary to avoid external pillars poisoning the opts cache

### What issues does this PR fix or reference?

#51578 

### Previous Behavior

If you create an external pillar, and then have it set `'ext_pillar':[]` and pass it to a `MasterPIllarUtil` class, as `opts` then the second time that master process runs it will fail to load the external pillar, because it has `'ext_pillar': []` in the cache.

### New Behavior

Now it will properly load the external pillar each time.

### Tests written?

No - I'm not sure what meaningful tests I *could* write

### Commits signed with GPG?

Yes

2019-03-06 19:34 UTC, twangboy submitted a review, later dismissed

2019-03-07 17:03 UTC, dwoz reviewed
@waynew Is it possible to create a test for this?

2019-03-07 18:22 UTC, waynew commented
@dwoz I had the same question 😕 

I could just test that the dictionary has a different ID, but it seems like that's of limited value?

The other test (not sure exactly what it would take to implement it) looks like this:

start a single-process master, with an ext_pillar that has a MasterPillarUtil, passing it an opts dict with `'ext_pillar': []`, then ensure that after a call to pillar.items, subsequent call to pillar.items loads the external pillar.

It's not clear to me if the tradeoff is worth it.

I *do* think that it's worth commenting this code if not, though.

2019-03-25 03:29 UTC, cachedout commented
IMHO this is not a complete fix and may introduce difficult-to-find bugs. 

This looks like you are doing a shallow copy of the opts dictionary which will do the right thing in top-level keys but *not* for nested keys, of which the opts dict contains many.

For example:

```
>>> a = {'1': {'2': '3'}}
>>> b = dict(a)
>>> a
{'1': {'2': '3'}}
>>> b
{'1': {'2': '3'}}
>>> a['1']['2'] = '9'
>>> a
{'1': {'2': '9'}}
>>> b
{'1': {'2': '9'}}```

Compare to a deep copy:

```
>>> import copy
>>> a = {'1': {'2': '3'}}
>>> b = copy.deepcopy(a)
>>> a['1']['2'] = '9'
>>> a
{'1': {'2': '9'}}
>>> b
{'1': {'2': '3'}}```

Even though the original issue is about a top-level key, if this is about `__opts__` needing to be isolated, this is an incomplete approach for solving that for any nested key in the dictionary.

2019-03-25 03:30 UTC, cachedout requested changes
See comment on in the main thread of the PR.

2019-03-25 14:57 UTC, waynew commented
> Even though the original issue is about a top-level key, if this is about `__opts__` needing to be isolated, this is an incomplete approach for solving that for any nested key in the dictionary.

From my discussions, it seems like any approach short of freezing `__opts__` is an incomplete approach :trollface: 

I guess what I'm ultimately saying is that this PR is not attempting a general fix of `__opts__` - and maybe we need someone to sit down and write a SEP about that, because from what I understand, `__opts__` causes a ton of subtle and hard to understand bugs already. TBH, the reason I *didn't* use `copy.deepcopy` here is because I'm entirely not sure if there is code that expects to be able to communicate via those nested values, and I didn't want to break that code, just because it's doing the right thing the wrong way 😝 

If you think that risk is worth the change, I'm more than happy to change that `dict` call to a `copy.deepcopy`. I was just punting on that until we decide what to do with `__opts__`. I also picked this limited approach due to the fact that when I was trying to figure out this change literally any kind of wrapping of the dict fixed this problem.

I just did a `class FancyDict(dict):` that literally stored the opts dict internally and wrapped getitem and setitem and it fixed this cache poisoning problem. I couldn't reproduce the behavior with any kind of wrapped spying.

---

Maybe it's worth specifying with a comment, and/or here in the PR, that currently `__opts__` can be abused so here be dragons? I very much welcome suggestions and/or information.

2019-03-25 15:17 UTC, cachedout commented
My concern in this instance comes from what I still see as a potentially security flaw here. If an external service can modify `__opts__` for a running master that is extremely problematic. 

If this fix is designed to prevent that, it needs to isolate all of `__opts__` and not just top-level keys. If it causes additional problems, so be it, but I just don't see how Salt can allow for a situation in which configuring an external pillar means that whomever can compromise that service can potentially control _any_ part of the running configuration of masters which consume from it.

2019-03-25 15:41 UTC, waynew commented
> My concern in this instance comes from what I still see as a potentially security flaw here. If an external service can modify __opts__ for a running master that is extremely problematic.

If you write code to do that, then yes, it can do that 🙂 

This PR does not introduce that capability, which is currently how Salt behaves.

My feeling is that properly ensuring the integrity of `__opts__` for the running master is far beyond the scope of this PR, which is just to fix #51578.

My suggestion is that we should create a new issue addressing the lack of isolation in `__opts__` so that we can properly audit, test, and fix the problems we'll find. I think that trying to address that problem within this PR will be much less effective than making this minor improvement, and then creating an issue that can properly address the broader scope, which I'm pretty sure will benefit from a broader visibility. Or am I missing something?

2019-03-26 15:01 UTC, austinpapp commented
just my 2 cents

> __opts__ causes a ton of subtle and hard to understand bugs already.

well, by only partially fixing this problem , i think you are just kicking the can. top level "works" but nested exerts a completely different behavior. that alone is massively confusing. 🤷‍♂️

2019-03-26 15:57 UTC, mattp- commented
I don't think that is the right place to make that copy (and I think it should be a deep copy). Why not add it to salt.cache.__init__ instead? 
the place it is being shared is through the masterapi.cache instance (through the mod.__opts__.update() you referenced), so it could probably be added to self.opts for deep copying as well.

2019-03-26 16:31 UTC, waynew commented
> well, by only partially fixing this problem , i think you are just kicking the can. 

Yes, I am 🙂 

I could *not* fix this particular issue, because properly fixing `__opts__` is the broadest, most correct fix. And from a purely theoretical point of view, that's the perfect thing to do.

But properly fixing `__opts__` is going to be a non-trivial enhancement. I'm betting there's more than a weeks worth of effort there to understand the impact and implement the change.

> top level "works" but nested exerts a completely different behavior. that alone is massively confusing.

We're both making the assumption that something is using `__opts__` inappropriately :trollface: 

If nothing is abusing opts then the fact that this isn't a comprehensive solution won't actually be a problem.

On the other hand, if there are things abusing opts then the fact that this isn't a comprehensive solution is actually a good thing, because it's making the minimal amount of change required to fix this specific issue so it's unlikely to break *other* things that are relying on doing the wrong things.

I'm all for fixing things that are doing wrong things (i.e. paying down technical debt), but I'm also comfortable saying that this is not the appropriate place or reason to make the payment on `__opts__`. Of course, that's based on the information that I currently have. If I get better information, I'm happy to change my mind, but I currently don't have any information that suggests that we currently need a more comprehensive fix.

This patch makes an improvement, fixes a bug, and *probably* doesn't introduce new bugs. And doesn't introduce a significant amount of technical debt.

2019-03-26 20:15 UTC, cachedout commented
> If nothing is abusing opts then the fact that this isn't a comprehensive solution won't actually be a problem.

Respectfully, I think it may be beneficial to have @thatch45 to weigh in here as he has a great deal of experience when it comes to debugging issues caused by bifurcating opts with shallow copies. :)

2019-03-26 22:51 UTC, thatch45 commented
This change would not be enough, and I think it is covering up deeper issues. Any way about it we need to make a special function to deeply copy a dict (I thought there was one in utils/dict.py). We also need to keep in mind that making it change for just one loader instance can cause confusion when writing plugins in general.

In the end I think it would make more sense to see what happens to the tests when we use the frozenset approach.

As for this, I think it is an ok way to fix the given issue, but we should be doing a propper nested deep dict copy

2019-03-26 23:01 UTC, mattp- commented
I take it by frozenset it is _not_ desirable for master opts to be mutable? I know in certain spots (ie minion master tune in), functionality is actually reliant on mutating opts, I'm sure it's elsewhere. Making the deepcopy on the input points (salt.cache constructor, which passes to salt.loader.cache, and salt.masterapi, which passes it to salt.cache and probably others) would be a cleaner spot to squash this bug imo

2019-03-27 19:23 UTC, thatch45 commented
As I look at this I am torn between making the loader create a deep copy of the opts dict when every loader instance happens, so one copy of opts for all of `__salt__` or to make the frozenset. Both approaches should resolve this in an elegant way

2019-04-09 23:02 UTC, waynew commented
@thatch45 do you have any preference for this yet?

FWIW, I think a healthy approach would be to stick the deepcopy in the loader for 2018.3, and then freeze `__opts__` in develop (and potentially wrap the `__opts__` setitem with a warning or something).

2019-04-09 23:17 UTC, thatch45 commented
You are spot on. Just make sure that you have one copy of opts per loader instance, not one copy per module :)

2019-12-28 00:00 UTC, dwoz commented
@waynew Can you port this to the master branch please?

2020-01-05 23:46 UTC, dwoz commented
@waynew I've updated this to point to master.

2020-01-07 04:53 UTC, waynew commented
@dwoz as soon as tests pass, this should be good to go.

2020-04-24 07:46 UTC, dwoz commented
@waynew Sorry, this needs another rebase.

2020-06-16 22:39 UTC, sagetherage commented
this isn't failing a test any longer so I removed that label, I am unsure what order we want to update PRs with master since currently we are in code freeze, so I am not touching that piece and will leave that to you @waynew :D

2021-11-16 00:26 UTC, waynew commented
This was fixed in https://github.com/saltstack/salt/pull/59832/files#diff-e8686c624191c5109ca13f27e7fee3ca5ac3703958fe784bfb3fd4a7cc08b51eR1317

2021-11-16 00:26 UTC, closed without merging