Update schedule.py
saltstack/salt pull request #52025
Opened 2019-03-07 14:37 UTC by vguevara

The documentation is incongruent with the module documentation. In the module the behaviour is stated as the fix  (https://docs.saltstack.com/en/latest/topics/jobs/#run-on-start), while the current doc suggest the schedule will not run at all if the value is set to False (which is wrong)

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-03-07 16:46 UTC, dwoz requested changes
Something about this reads a little weird to me. Does this work?
```
Whether the job will run when Salt minion starts,
or the job will be skipped it and run at the next scheduled run.  Value
should be a boolean.
```

2019-03-11 16:18 UTC, vguevara commented
Perhaps better:
```
Whether the job will run when Salt minion starts,
or the job will be skipped **once** and run at the next scheduled run.  Value
should be a boolean.
```

2020-01-05 23:54 UTC, dwoz commented
@vguevara I've updated this to point to the `master` branch and have added the working change. We'll get this merged after the docs build passes.

2020-01-05 23:54 UTC, dwoz approved these changes

2020-01-06 02:41 UTC, merged