[2019.2] Fix to rsync state
saltstack/salt pull request #52040
Opened 2019-03-07 19:56 UTC by garethgreenaway

### What does this PR do?
When the retcode is non-zero, there are no changes so should include the default empty dictionary.

### What issues does this PR fix or reference?
#52036

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-03-07 20:02 UTC, waynew approved these changes

2019-03-07 21:25 UTC, dwoz requested changes
@garethgreenaway Since this is a bugfix can you write a regression test for the change?

2019-03-07 23:38 UTC, garethgreenaway commented
@dwoz Done.

2019-03-08 04:17 UTC, dwoz approved these changes

2019-03-21 19:08 UTC, merged