Feature/51847
saltstack/salt pull request #52141
Opened 2019-03-11 17:53 UTC by xeacott

### What does this PR do?
Adds feature for pip.installed to support --user argument.

### What issues does this PR fix or reference?
 #51847 

### Previous Behavior
Currently, pip.installed state doesn't support it in any release.

### New Behavior
Now, pip.installed state does support this behavior.

### Tests written?

No (marked as WIP as setting environment up to tests to run)

### Commits signed with GPG?

Yes

2019-04-29 17:49 UTC, Oloremo commented
Any updates on this? I'm willing to test it if it's needed.

2019-05-15 20:28 UTC, waynew commented
@xeacott there are a couple of failures here... and some merge problems 😝

2019-05-16 23:04 UTC, xeacott commented
Yes, test if you'd like like! I apologize for the delay on this but working on getting Docker setup to test for the various OS's has proved to be a slight learning curve, nonetheless I still believe the logic implemented should be fine for these tests

2019-05-20 22:40 UTC, twangboy requested changes

2019-05-20 22:40 UTC, twangboy commented on tests/integration/states/test_pip_state.py
> +        path = ('{}/{}'.format(USER_SITE, pkg))
This may not work in Windows... maybe use...
```
os.path.join(USER_SITE, pkg)
```

2019-05-20 22:40 UTC, twangboy commented on tests/integration/states/test_pip_state.py
> +        path = ('{}/{}'.format(USER_SITE, pkg))
Unless that's some other type of path...

2019-05-20 22:40 UTC, twangboy commented on tests/integration/states/test_pip_state.py
> +            path = ('{}/{}'.format(site_pkg, pkg))
Same here...

2019-05-20 22:40 UTC, twangboy commented on tests/integration/states/test_pip_state.py
> +        site_pkg = os.path.join(venv_dir, 'lib/site-packages')
perhaps...
```
os.path.join(venv_dir, 'lib', 'site-packages')
```

2019-05-28 00:40 UTC, Oloremo commented
@xeacott any plans to resolve conflicts and bring this PR up to date?

2019-06-04 17:07 UTC, xeacott commented
> @xeacott any plans to resolve conflicts and bring this PR up to date?

Yep, will be cleaning this up very shortly. Had some downtime just getting up again.

2019-06-05 15:56 UTC, twangboy requested changes

2019-06-05 15:56 UTC, twangboy commented on salt/modules/pip.py
> +          verbose=False,
Where did this come from? Part of the merge conflict resolution maybe? Need to figure out where the docs forthis went or add them if you added this.

2019-06-05 15:56 UTC, twangboy commented on salt/modules/pip.py
> +def list_json(bin_env=None,
You mentioned getting rid of this... is that no longer the case?

2019-06-05 16:34 UTC, twangboy approved these changes

2019-06-06 15:01 UTC, merged

2019-11-11 17:44 UTC, max-arnold commented
@waynew I believe there is no need to backport this PR. Instead, it is better to port more generic one that allows arbitrary `pip` arguments: https://github.com/saltstack/salt/pull/52327