Check dir_mode recursively in file.directory
saltstack/salt pull request #52175
Opened 2019-03-14 03:45 UTC by amendlik

### What does this PR do?
Fixes a problem in `states.file` where directory permissions are not checked properly with `test=true`

### What issues does this PR fix or reference?
Partially fixes #52173

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-04-23 21:25 UTC, amendlik commented
Please tell me me what needs to be done to get this change merged.

2019-04-24 19:15 UTC, twangboy commented
@amendlik We need to get some tests written for this

2019-04-24 22:34 UTC, Akm0d commented on salt/states/file.py
> +                    if file_mode is not None and file_mode != stats.get('mode'):
the "mode" kwarg got changed to "dir_mode", so shouldn't this be "dir_mode" instead of "file_mode"?

2019-04-25 03:28 UTC, amendlik commented
The kwargs were confusing before this change. There was a 'mode' kwarg,
which specified the directory mode, and a 'file_mode' kwarg which specified
the file mode. To make matters worse, the section that set the file mode
shadowed the 'mode' variable, overwriting it's value and causing the next
section, which sets the directory mode, to misbehave. The section of the
file you have referenced is where the file mode is set. it relies on the
'file_mode' kwarg, which did not change.

On Wed, Apr 24, 2019 at 4:35 PM Akmod <notifications@github.com> wrote:

> *@Akm0d* commented on this pull request.
> ------------------------------
>
> In salt/states/file.py
> <https://github.com/saltstack/salt/pull/52175#discussion_r278343715>:
>
> > @@ -747,18 +748,18 @@ def _check_directory(name,
>                          fchange['user'] = user
>                      if group is not None and group != stats.get('group'):
>                          fchange['group'] = group
> -                    if mode is not None and mode != stats.get('mode'):
> -                        fchange['mode'] = mode
> +                    if file_mode is not None and file_mode != stats.get('mode'):
>
> the "mode" kwarg got changed to "dir_mode", so shouldn't this be
> "dir_mode" instead of "file_mode"?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/52175#pullrequestreview-230387810>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABN5M3BYIJXU77E5B33HUUTPSDOBVANCNFSM4G6MIWLA>
> .
>

2019-05-03 20:21 UTC, Akm0d requested changes
This looks good and works per my own manual test, before merging we really do need to add a test case.

2019-05-04 21:42 UTC, amendlik commented
@Akm0d, are you going to create the test case, or are you waiting for me to do that?

2019-05-17 15:32 UTC, amendlik commented
@Akm0d, are you going to create the test case, or are you waiting for me to do that?

2019-06-03 23:35 UTC, amendlik commented
Third try for a response: @Akm0d are you going to create the test case, or are you waiting for me to do that?

2019-06-04 16:48 UTC, Akm0d commented
I was waiting for you to create the test case.  Sorry it took me that long to get back to you... I didn't realize I had implied that I was going to write a test, as a reviewer I was re-affirming what @twangboy had said needed to be done for this to be merged.

2019-06-04 20:47 UTC, KChandrashekhar commented
@amendlik Thanks for this PR. Also, to ensure this gets into 2019.2.1 release, can you reopen this in 2019.2.1 branch ?

2019-06-05 02:43 UTC, bryceml commented
re-run docs

2019-06-05 16:45 UTC, Akm0d commented
We will write the test :+1:

2019-06-05 19:31 UTC, Akm0d commented
@amendlik, @twangboy and I wrote a test case for this, how do you think it looks?  It is currently failing because I think our options for  filestate._check_directory()" are incorrect.  I was hoping we could get some input/advice from your end so we can have this PR ready for merge.

2019-06-05 19:33 UTC, Akm0d commented on tests/unit/states/test_file.py
> +            ret = filestate._check_directory(root_tmp_dir, dir_mode=0o777, file_mode=0o777, recurse=['mode'])
I'm sure the test is failing because the options here are incorrect, what should we be putting in for options?

2019-06-05 20:22 UTC, Akm0d commented
I also accidentally did an auto-format of test_file.py from pycharm ... a lot of the indentation was really bad but idk if it's kosher to mix that into another PR or if cosmetic changes are allowed, should I go back and fix that @twangboy?

2019-06-05 21:30 UTC, Akm0d commented
Cherry-picked these changes to the 2019.2.1 branch and created a new PR https://github.com/saltstack/salt/pull/53385

2019-06-05 21:30 UTC, closed without merging