[2018.3] Don't save beacons when test=True
saltstack/salt pull request #52213
Opened 2019-03-16 00:16 UTC by garethgreenaway

### What does this PR do?
Don't save beacons when test=True

### What issues does this PR fix or reference?
N/A

### Previous Behavior
When test=true beacons would be saved to /etc/salt/minion.d/beacons.conf

### New Behavior
When test=True we shouldn't save.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-03-19 15:29 UTC, waynew requested changes

2019-03-19 15:29 UTC, waynew commented on salt/states/beacon.py
> +        if 'test' in __opts__ and __opts__['test']:
What about
```suggestion
if __opts__.get('test'):
```
Or if you wanted to be explicit,
```
if __opts__.get('test', False):
```
But (as you're no doubt aware) `.get` defaults to the falsey `None`.

2019-03-19 15:29 UTC, waynew commented on salt/states/beacon.py
> +        if 'test' in __opts__ and __opts__['test']:
Same here,
```suggestion
if __opts__.get('test'):
```

2019-03-19 18:47 UTC, waynew approved these changes

2019-03-29 01:04 UTC, dwoz approved these changes

2019-03-29 01:04 UTC, merged