Fix pip
saltstack/salt pull request #52327
Opened 2019-03-26 17:38 UTC by Akm0d

### What does this PR do?
Makes it possible to pass arbitrary arguments to pip from pip.installed

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/24751

### Previous Behavior
N/A

### New Behavior
 pip keyword and positional arguments not yet implemented in salt can be passed to pip through pip.installed

    .. code-block:: yaml

        pandas:
          pip.installed:
            - name: pandas
            - pip_future:
              - --latest-pip-kwarg:
                - param1
                - param2
              - --latest-pip-arg

    Will be translated into the following pip command:

    .. code-block:: bash

        pip install pandas --latest-pip-kwarg param1 --latest-pip-kwarg parm2 --latest-pip-arg

### Tests written?

Yes

### Commits signed with GPG?

Yes

2019-03-26 17:50 UTC, waynew commented
Uh... I think you might want to rebase your fixes :trollface: (or retarget your PR)

2019-03-26 18:50 UTC, twangboy commented
@Akmod Looks like you have some lint

2019-03-26 18:51 UTC, twangboy commented
https://jenkinsci.saltstack.com/job/pr-lint/job/PR-52327/1/warnings52Result/new/

2019-03-26 22:44 UTC, Akm0d commented
I don't understand why it's not passing the py3-centos-7 test.  I ran the tests manually using python3.6.1 on my own centos7 server and it all passed just fine

2019-03-27 15:44 UTC, Akm0d commented
Failing on Centos7 with python3 and windows, but not because of the commit.  Centos7 and Windows are having issues in Jenkins

2019-03-28 17:49 UTC, waynew commented
I'm not sure if the remaining problem is legit something with these tests - it is a problem in the pip state tests, so probably worth looking into 👍

2019-04-03 19:16 UTC, waynew approved these changes
👍

2019-04-08 19:41 UTC, thatch45 approved these changes

2019-04-18 22:25 UTC, twangboy requested changes
A few minor things. Looks great.

2019-04-18 22:25 UTC, twangboy commented on salt/modules/pip.py
> +        # have not yet been implemented in salt
`# These are any additional arguments to be passed as parameters to the pip command`

I don't think we need to specify that it's for arguments salt hasn't implemented yet

2019-04-18 22:25 UTC, twangboy commented on salt/modules/pip.py
> +        pip keyword and positional arguments not yet implemented in salt
`pip keyword and positional arguments to be passed as parameters to the pip command`

I don't think we need to denote `not yet implemented`

2019-04-18 22:25 UTC, twangboy commented on salt/states/pip_state.py
> +        pip keyword and positional arguments not yet implemented in salt
same here

2019-04-22 21:02 UTC, merged

2019-11-11 12:35 UTC, max-arnold commented
Can someone backport this to master branch?

2019-12-02 20:39 UTC, Akm0d commented
@max-arnold Done :+1: