Clean up exception handling
saltstack/salt pull request #52353
Opened 2019-03-29 01:00 UTC by dwoz

### What does this PR do?

Clean up a few instances of bare exception handling.

### Tests written?

No - Existing tests cover these cases

### Commits signed with GPG?

Yes

2019-03-29 01:09 UTC, garethgreenaway submitted a review, later dismissed

2019-03-29 02:27 UTC, twangboy requested changes

2019-03-29 02:27 UTC, twangboy commented on salt/fileserver/roots.py
> +            log.error("Unable to state file (%s)", exc)
Unable to `stat` file maybe...?

2019-03-29 02:27 UTC, twangboy commented on salt/utils/event.py
> +        # fact that __del__ is non deterministic. We shoold call destroy
should

2019-03-29 02:27 UTC, twangboy commented on salt/utils/files.py
> +        log.error("Exception while removing tem directory (%s)", exc)
temp

2019-03-29 03:31 UTC, waynew reviewed
So nice, :+1: from me after typo fixes

2019-03-29 18:12 UTC, twangboy approved these changes

2019-03-29 19:13 UTC, twangboy submitted a review, later dismissed

2019-04-22 19:31 UTC, dwoz commented
re-run all

2021-08-23 21:46 UTC, dwoz commented
Replaced by #60782

2021-08-23 21:46 UTC, closed without merging