Added virtual-machines to ext_pillars
saltstack/salt pull request #52386
Opened 2019-04-02 12:23 UTC by awlx

### What does this PR do?
Adds virtual-machines to ext_pillars netbox otherwise nothing will be returned for those hosts

### What issues does this PR fix or reference?

### Previous Behavior
Only devices in dcim/devices returned pillar information from netbox

### New Behavior
Virtual-machines also return pillar information from netbox

### Tests written?

No

### Commits signed with GPG?

No

2019-04-22 22:05 UTC, Akm0d requested changes
This looks really good, but I would also like to see a test case for the new behavior.

2019-04-28 20:51 UTC, awlx commented
What do you mean with test case for this behaviour? :) As far as I have seen there are no tests so far for the netbox.py pillar right now.

2020-05-26 19:33 UTC, sagetherage commented
@awlx can you rebase this against the master branch, please?

2021-04-05 11:19 UTC, ggiesen commented
Note I also have added virtual machines in #59500

2021-04-05 17:54 UTC, sagetherage commented
Reviewed in Grooming 2021-APR-05 deferring to the other PRs  see Gary's comment above and PR #58036

2021-04-05 17:54 UTC, closed without merging