Refactor test_cron test
saltstack/salt pull request #52385
Opened 2019-04-02 11:30 UTC by waynew

### What does this PR do?

Refactors the one `test_cron` state test that we have, because #52079

It's possible that the dict could contain some more helpful information
when/if this test fails again. This assertion improves the potential for
getting useful information in the test failure.

### What issues does this PR fix or reference?

#52079

### Previous Behavior

The assert statement failed to have any useful information in it.

### New Behavior

Now when the test fails, it should have some useful information in the failure

### Tests written?

Yes (changed the test - verified that changing the expected value failed the test and provided useful information, i.e. the entire contents of the changes, then changed it back and verified that the test passes)

### Commits signed with GPG?

Yes

2019-04-11 23:39 UTC, dwoz requested changes
@waynew Please have a look at the test failures.

2019-04-18 12:34 UTC, waynew commented
Well, I fixed the failing Ubuntu tests @dwoz - it just completely failed running on win 2016. I'm re-running that job 🤞 (but in general I don't think that that failure is related to my changes)

2019-04-18 13:19 UTC, waynew commented
Currently still running, so that's a promising sign

2019-04-27 01:32 UTC, dwoz approved these changes

2019-04-27 01:32 UTC, merged