Fix orch return processing
saltstack/salt pull request #52419
Opened 2019-04-04 21:47 UTC by roylarsen

### What does this PR do?

Extends the Salt Runner processing to allow cloud tasks to be processed correctly.

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/50939

### Previous Behavior

Cloud functions were showing as succeeding.

### New Behavior

Runner processing will now report failures from cloud functions

### Tests written?

Yes

### Commits signed with GPG?

No

2019-04-25 20:36 UTC, Ch3LL requested changes
thanks for the pr! looks like there is a lint and test failure, if you could just clean those up. Thanks!

2019-05-05 16:34 UTC, roylarsen commented
@Ch3LL - Sorry for the delay, I'll get those linting errors cleaned up and this re-submitted!

2019-07-15 13:17 UTC, pcn commented
This seems like it's in-line with how e.g. the sls or highstate modules describe the run as successful only if all states have succeeded. It seems like it'd be a good idea to add docstrings to this effect in this case though, since it's new behaviour.

2020-03-13 19:53 UTC, twangboy requested changes
This looks good. A few format errors. Also, we are no longer using the develop branch. All changes are being made on the master branch. Please rebase this against the master branch.

2020-03-13 19:53 UTC, twangboy commented on tests/unit/states/test_saltmod.py
> +          self.assertDictEqual(saltmod.runner(name), ret)
Indentation looks wrong here. Should be 4 spaces

2020-03-13 19:53 UTC, twangboy commented on tests/unit/states/test_saltmod.py
> +          self.assertDictEqual(saltmod.runner(name), ret)
Same here

2020-05-26 20:17 UTC, sagetherage commented
@roylarsen are you able to rebase this against master? Otherwise we may close it as abandoned.

2021-04-19 15:06 UTC, sagetherage commented
@roylarsen are you able to rebase this against master?

2021-05-03 22:53 UTC, sagetherage commented
Reviewed in Grooming 2021-MAY-03 closing

2021-05-03 22:53 UTC, closed without merging