encoding is deprecated; fixes #51741
saltstack/salt pull request #52480
Opened 2019-04-10 16:56 UTC by alxwr

### What does this PR do?

It replaces `encoding=encoding` with `raw=False` when using msgpack.

### What issues does this PR fix or reference?

It fixes the deprecation warning discussed in #51741.

### Previous Behavior

```
% salt 'example.test' test.ping                                 
[WARNING ] /usr/local/lib/python3.6/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

example.test:
    True
```

### New Behavior

```
% salt 'example.test' test.ping                                 
example.test:
    True
```

### Tests written?

No (Tried to run the tests, but failed.)

### Commits signed with GPG?

No

2019-04-10 16:57 UTC, thatch45 approved these changes

2019-04-11 23:21 UTC, dwoz requested changes
Based on the test failures, it looks like we need to detect the msgpack version and pass the arguments accordingly. I suggest we add a proxy method that accepts the newer api and can use the old api for older msgpack versions.

Pseudo code:
```
def loads(msg, use_list=True, ext_hook=ext_type_decoder, raw=False):
      if msgpack.__version__ <= 'x.x.x
         if raw == False':
            if six.PY2:
                encoding = None
            else:
                encoding = 'utf-8'
           return msgpack.loads(msg, use_list=use_list, ext_hook=ext_hook, encoding=encoding)
      else:
          return msgpack.loads(msg, use_list=use_list, ext_hook=ext_hook, raw=raw)
```

2019-04-18 21:59 UTC, dwoz commented
This has an alternate PR #52487

2019-04-18 22:01 UTC, dwoz commented
I think #52487, is a more comprehensive fix. Closing this PR.

2019-04-18 22:01 UTC, closed without merging