Show correct output when archive needs to be extracted w/tar CLI
saltstack/salt pull request #52502
Opened 2019-04-11 15:56 UTC by terminalmage

In cases where the tar CLI needs to be used (such as when tar options are passed to the state), the `extracted_files` item in the changes dict shows "no tar output so far" because the tar command being run doesn't include the `-v` option to show the paths that were extracted. This fixes that and provides a list just like when the `tarfile` module is used to extract.

2019-04-11 16:06 UTC, twangboy approved these changes

2019-04-11 20:37 UTC, dwoz requested changes
@terminalmage It looks like the failing tests are related, can you take a look?

2019-04-18 19:15 UTC, terminalmage commented
I'll have a look over the weekend, thanks for the heads-up.

2019-04-22 15:36 UTC, terminalmage commented
@dwoz The tests caught a flaw in my PR. I fixed it, updated the tests, and rebased onto the head of 2018.3.

2019-04-26 18:46 UTC, dwoz approved these changes

2019-04-26 18:46 UTC, merged