fix: #51842
saltstack/salt pull request #52553
Opened 2019-04-15 17:25 UTC by mattLLVW

### What does this PR do?

Fix #51842 Wrong model name
### What issues does this PR fix or reference?
 
#51842

2019-04-15 18:24 UTC, waynew commented on salt/auth/django.py
> +        minion_fn = models.CharField(max_length=255)
If there's an assumption of Postgres as the database, [there's no reason to add max_length](https://www.depesz.com/2010/03/02/charx-vs-varcharx-vs-varchar-vs-text/).

2019-04-15 18:29 UTC, waynew commented on salt/auth/django.py
> +        minion_fn = models.CharField(max_length=255)
Ah... I see it's [required in Django's CharField](https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.CharField)

2019-04-15 18:32 UTC, waynew commented on salt/auth/django.py
> +        minion_fn = models.CharField(max_length=255)
Apparently one needs to [make their own `CharField` to avoid Django's limit](https://stackoverflow.com/a/20116327)

2019-04-15 18:32 UTC, waynew approved these changes

2019-04-16 17:16 UTC, dwoz requested changes
@mattLLVW Is it possible to add a test for this change?

2019-04-16 17:18 UTC, mattLLVW commented
It's a documentation change...?

2019-04-17 13:59 UTC, dwoz approved these changes
@mattLLVW My bad I took a glance and it looked like a code change. Approved.

2019-04-17 13:59 UTC, merged