fix TypeError: argument of type int is not iterable
saltstack/salt pull request #52624
Opened 2019-04-19 08:51 UTC by tanlingyun2005

### What does this PR do?
fix a batch run bug, when batch_safe_limit or batch_safe_size is set to a integer, self.opts['batch'] is integer, and will resulting in "TypeError: argument of type 'int' is not iterable"

### What issues does this PR fix or reference?

### Tests written?

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-04-19 14:09 UTC, Ch3LL commented
@tanlingyun2005 thanks for the contribution! Looks like there are some test failures:

```
    unit.cli.test_batch.BatchTestCase.test_get_bnum_high_percentage
    unit.cli.test_batch.BatchTestCase.test_get_bnum_percentage
```

Also is it possible for you to write a regression test for this fix?

2019-04-19 16:17 UTC, tanlingyun2005 commented
> @tanlingyun2005 thanks for the contribution! Looks like there are some test failures:
> 
> ```
>     unit.cli.test_batch.BatchTestCase.test_get_bnum_high_percentage
>     unit.cli.test_batch.BatchTestCase.test_get_bnum_percentage
> ```
> Also is it possible for you to write a regression test for this fix?

OK，Let me see

2019-04-20 04:04 UTC, tanlingyun2005 commented
jenkins/pr/lint — Python lint test has failed

Incompatible Python 3 code found. Proposed fix:
--

because unicode type just exists in Python 2, so "isinstance(self.opts['batch'], unicode)" is not compatible to Python 3, but use "sys.version_info.major" as a conditional branch could avoid this question.

2019-04-22 12:41 UTC, waynew commented
@tanlingyun2005 there's some samples around the code of checking for bytes vs text using six - you'll probably want to follow one of those patterns.

2019-04-23 13:37 UTC, tanlingyun2005 commented
> @tanlingyun2005 there's some samples around the code of checking for bytes vs text using six - you'll probably want to follow one of those patterns.

Thanks remind

2019-04-23 16:51 UTC, Akm0d approved these changes
Looks good

2019-04-25 15:50 UTC, Ch3LL requested changes
would you mind writing a regression test for this so this issue does not pop up again? thanks :)

2019-04-26 15:47 UTC, tanlingyun2005 commented
> would you mind writing a regression test for this so this issue does not pop up again? thanks :)

sorry, I don't know how to write "regression test", could you give me some samples?
but I add a unit test case to tests/unit/cli/test_batch.py, this is a run result:
test_get_bnum_high_percentage (__main__.BatchTestCase)
[CPU:13.3%|MEM:41.5%]  ... ok
test_get_bnum_int (__main__.BatchTestCase)
[CPU:0.0%|MEM:41.5%]  ... ok
test_get_bnum_invalid_batch_data (__main__.BatchTestCase)
[CPU:25.0%|MEM:41.5%]  ... <type 'unicode'>
ok
test_get_bnum_percentage (__main__.BatchTestCase)
[CPU:0.0%|MEM:41.5%]  ... ok
test_get_bnum_str (__main__.BatchTestCase)
[CPU:0.0%|MEM:41.5%]  ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK

2019-04-27 01:35 UTC, dwoz approved these changes
@tanlingyun2005 

A 'regression test' is basically a tests that shows the bug when the tests fails. Generally, we write a regression test first before fixing the bug in question. The purpose of these types of tests is to make sure that once a bug is fixed it does not happen again in the future.

Your unit test looks good for this case. Thanks a ton!

2019-04-27 01:47 UTC, pullit commented on salt/cli/batch.py
> +            if isinstance(self.opts['batch'], six.string_types) and '%' in self.opts['batch']:
Love the `six.string_types` for Python 2 and 3 compatibility.

2019-04-29 13:15 UTC, Ch3LL approved these changes

2019-04-29 13:15 UTC, merged