Add the "merge" jinja filter
saltstack/salt pull request #52708
Opened 2019-04-26 09:08 UTC by bbinet

This filter can be really useful in states to merge two dicts recursively.

The code is trivial as it is just a matter of exposing the existing merge function as a jinja filter through the @jinja_filter('merge') decorator.
That is the reason why it seems safe to merge it in the 2019.2 branch instead of the develop branch.

2019-04-26 09:09 UTC, bbinet commented
Also, is there any chance this patch can be published in the 2019.2.1 release? (it would be helpful to me)

2019-04-26 17:38 UTC, dwoz requested changes
@bbinet Actually, this change should go to the develop branch as `2019.2.x` is bugfix only. Also, there should be some tests associated with the change.

2019-04-27 00:55 UTC, max-arnold commented
@bbinet Are you aware that [`merge_all`](https://github.com/saltstack/salt/pull/47679) function exists Salt since 2019.2.0?

2019-04-27 01:34 UTC, pullit commented on doc/topics/jinja/index.rst
> +  {'a1': {'b1': 'foo2'}, 'a2': 'bar', 'a3': 'bar3'}
The merged value of `b1` is more like a rewrite than a merge.  I would expect a JSON array.

2019-04-30 09:03 UTC, bbinet commented
Thanks @max-arnold, I was not aware of the slsutil module which I can actually use to merge my dicts.
So this PR can be closed.

2019-04-30 09:03 UTC, closed without merging