Pin kubernetes to <4.0
saltstack/salt pull request #52705
Opened 2019-04-25 23:15 UTC by dwoz

### What does this PR do?

Update kubernetes pinning in static requirements files. 

### Tests written?

No - Fixing existing tests

### Commits signed with GPG?

Yes

2019-04-25 23:20 UTC, s0undt3ch commented
To generate the static requirements:

```
pip install pre-commit
pre-commit -av
```

2019-04-25 23:47 UTC, dwoz commented
@s0undt3ch Fixed, thanks!

2019-04-26 17:06 UTC, s0undt3ch approved these changes

2019-04-26 19:57 UTC, Ch3LL commented
Do we have an issue open so we can track down why salt does not currently work with 4?

2019-04-26 20:25 UTC, s0undt3ch commented
Don't think we have.

2019-04-26 22:19 UTC, dwoz commented
re-run centos

2019-04-26 23:04 UTC, dwoz commented
re-run full all

2019-04-27 05:04 UTC, angrydead reviewed
Can this be simplified to the following?

```
if (name in proc.name() and _search(proc)) or search is None:
    return proc
```

2019-04-27 05:14 UTC, dwoz commented
@pullit

It seems like we'd be missing the `if name in proc.name():` after the first if. I think in order for it to be the exact same logic we would need to be something like:

```
if (name in proc.name() and _search(proc)) or (search is None and name in proc.name()):
    return proc
```

However, I also think it's debatable wether or not that's actually simpler. Also, having said that, I'm just trying to prevent some tests from raising and exception in this PR and I feel like changing too much will run the risk of introducing a bug. I'd prefer not to change it.

2019-04-27 05:17 UTC, dwoz commented
re-run full all

2019-04-27 05:17 UTC, pullit commented
@dwoz That's fair.  I'm new here and don't want to step on any toes.  In hindsight, your original implementation is more readable and scales better if additional functionality is needed.

2019-04-27 05:18 UTC, dwoz commented
@pullit Thanks, In any case your review is welcomed. An extra set of eyes no changes never hurts. :)

2019-04-27 05:42 UTC, dwoz commented
re-run full all

2019-04-27 05:52 UTC, s0undt3ch approved these changes

2019-04-27 09:33 UTC, dwoz commented
re-run full all

2019-04-27 09:53 UTC, dwoz commented
re-run full all

2019-04-27 13:44 UTC, s0undt3ch requested changes

2019-04-27 13:44 UTC, s0undt3ch commented on .ci/kitchen-centos6-py3
> +properties([
CentOS 6 under Py3?
We're not even building that on branch builds...

2019-04-27 14:29 UTC, s0undt3ch approved these changes

2019-04-27 20:35 UTC, s0undt3ch approved these changes

2019-04-27 20:36 UTC, merged