Fix typos (`the the` > `the`)
saltstack/salt pull request #52711
Opened 2019-04-26 15:06 UTC by eliasp

It looks like humans aren't only very bad at recognizing a double `the` in a sentence when reading [1], but they're also very good at sneaking them in unintentionally without noticing.

Fix this by running:
```
ack --ignore-dir=doc/man --ignore-dir=doc/topics/releases -i 'the the\W' -l | xargs sed -i 's|the the\(\W\)|the\1|g'
```

[1] Eye movements and word skipping during reading: Effects of word length and predictability: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3543826/

### What does this PR do?
Fixes a common typo

### What issues does this PR fix or reference?
None

### Tests written?
No

### Commits signed with GPG?
Yes

2019-04-26 19:53 UTC, Ch3LL submitted a review, later dismissed

2019-04-26 20:26 UTC, s0undt3ch submitted a review, later dismissed

2019-04-27 09:49 UTC, dwoz submitted a review, later dismissed

2020-03-27 17:04 UTC, waynew commented
Hey @eliasp looks like we missed merging this a while ago. Do you mind rebasing this on `master`?

Might be worth just running this against master to see if there are *more* double `the`'s there :trollface:

2020-03-27 23:01 UTC, eliasp commented
Rebased on `master` + re-created the commit by running it again.

2020-03-30 22:05 UTC, eliasp commented
Failing CI is completely unrelated (and only editing doc/comments shouldn't have any influence on CI anyways 😄)

2020-04-15 17:51 UTC, waynew submitted a review, later dismissed

2020-04-15 22:27 UTC, eliasp commented
Rebased against latest master to get some merge conflicts ouf of the way

2020-04-16 14:14 UTC, Ch3LL commented
looks like there are some failure that need to be resolved here. Looks like the rebase might have caused some issues. We recently added pre-commit which should run black against your code. I noticed that the PR has some single ticks where black requires double quotes.

2020-04-22 22:51 UTC, s0undt3ch requested changes

2020-04-22 22:51 UTC, s0undt3ch commented on doc/topics/development/tests/unit.rst
> +import when
All these imports.... :grin:

2020-04-22 22:51 UTC, s0undt3ch commented on doc/topics/tutorials/firewall.rst
> -from specific hosts or networks into your Salt Master. The first
Unintentional delete?

2020-04-23 20:16 UTC, waynew commented on doc/topics/tutorials/firewall.rst
> -from specific hosts or networks into your Salt Master. The first
fixed

2020-04-23 20:17 UTC, waynew commented on doc/topics/development/tests/unit.rst
> +import when
:eyes: 

:fire:

2020-04-27 19:31 UTC, waynew approved these changes
🎉

2020-04-27 19:32 UTC, waynew commented
@s0undt3ch are you good here?

2020-04-27 19:33 UTC, s0undt3ch approved these changes

2020-04-28 17:02 UTC, merged