Fix salt-cloud traceback in python 3
saltstack/salt pull request #52735
Opened 2019-04-28 23:11 UTC by NiCalderon

### What does this PR do?
Fix salt/cloud/clouds/ec2.py get_imageid to use sorted's key instead or cmp parameter (removed in python 3)
### What issues does this PR fix or reference?
No issue was filed
### Previous Behavior
Traceback when attempting to start an instance with an image not starting with "ami-"

### New Behavior
No more traceback and expected image is being used.

### Tests written?

No

### Commits signed with GPG?

No

2019-04-28 23:14 UTC, dwoz commented
@NiCalderon Was this submitted against the proper base branch? It definitely looks like something is off based on the number of files changed and the commit history.

2019-04-28 23:15 UTC, dwoz requested changes
@NiCalderon Was this submitted against the proper base branch? It definitely looks like something is off based on the number of files changed and the commit history.

2019-04-28 23:18 UTC, NiCalderon commented
It suggested to merge to develop by default and I forgot to change that to 2019.2, where the modified code was first introduced.

2019-04-28 23:20 UTC, NiCalderon commented
I edited it, but should I resubmit?

2019-04-29 01:11 UTC, dwoz commented
@NiCalderon might be a good idea, we'll need some test coverage for this change too.

2019-04-29 01:15 UTC, NiCalderon commented
I will resubmit. As far as testing, I looked to see if there was anything I could adapt, but the tests for this modules are very thin. Any suggestions as to how I should proceed?

2019-04-29 08:02 UTC, dwoz commented
@NiCalderon Just try to write a test that exposes the bug you are fixing. If the test fails when your patch is not present but passes when your patch is applied, that should be good.

2019-05-08 01:18 UTC, NiCalderon commented
Created a new PR (https://github.com/saltstack/salt/pull/52936), closing this one

2019-05-08 01:18 UTC, closed without merging