Switch firewalld state to use change_interface
saltstack/salt pull request #52743
Opened 2019-04-29 15:05 UTC by aaannz

### What does this PR do?
`firewalld.present` state allows to bind interface to given zone.
However if the interface is already bound to some other zone, calling `add_interface` will not change rebind the interface but report error.
Option `change_interface` however can rebind the interface from one zone to another.

This PR adds `firewalld.change_interface` call to firewalld module and updates `firewalld.present` state to use this call.

### What issues does this PR fix or reference?

### Previous Behavior
Using firewalld.present to assign already bound interface to different zone does not work.

### New Behavior
Using firewalld.present to assign already bound interface to different zone does rebind the interface to new zone.

### Tests written?

No.

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-04-29 17:33 UTC, dwoz requested changes
@aaannz Thanks for the contribution. Please write some test coverage for this change.

2020-05-26 21:29 UTC, sagetherage commented
@aaannz please rebase this against the master branch

2021-05-17 18:18 UTC, sagetherage commented
@aaannz 
Reviewed in Grooming this week considering closing

2021-05-17 21:27 UTC, aaannz commented
I have this rebased on master. I wrote unit tests for this some time ago, but imo these are not really useful. I wanted to write integration tests for firewalld as well, but I turned out to be bigger task I had time for.

2021-05-18 00:06 UTC, sagetherage commented
Unit tests are better than no tests! I asked Wayne to briefly review in the Test Clinic on Tuesday - tomorrow, requested a review from @dwoz as well and the tests are now running. Thank you very much for your contribution!

2022-07-08 09:33 UTC, meaksh commented
@dwoz @Ch3LL @s0undt3ch any chance to review this one? It should be ready. Thanks in advance!

2022-07-08 10:13 UTC, s0undt3ch requested changes
It also needs a `added` changelog file.

2022-08-15 08:40 UTC, aaannz commented
Rebased with changelog entry added and version 3006 set.

2023-12-10 05:05 UTC, dwoz commented
Closing due to lack of activity. Anyone should feel free to re-open or create a new PR if they want to see this through to the end.

2023-12-10 05:05 UTC, closed without merging