Runit: Only resolve link if path is a link
saltstack/salt pull request #52760
Opened 2019-04-30 12:58 UTC by bbczeuz

### What does this PR do?
Module runit: Check wether a service's path is really a link. If it is a link, resolve it; else directly add path.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52759

### Previous Behavior
service.running throws an exception at `os.readlink(el) (OSError: [Errno 22] Invalid argument: '/etc/service/salt-minion'` (see Issue; /etc/service/salt-minion exists as a normal directory, not as symlink)

### New Behavior
service.running runs without throwing an exception

### Tests written?
No

### Commits signed with GPG?
No

2019-04-30 19:29 UTC, dwoz requested changes
@bbczeuz Thanks for the contribution. Can you please add a unit (or integration) test to cover this change?

2019-04-30 20:13 UTC, waynew commented
Maybe we should be using [realpath](https://docs.python.org/3/library/os.path.html#os.path.realpath) instead?

2019-05-02 13:35 UTC, bbczeuz commented
> 
> 
> @bbczeuz Thanks for the contribution. Can you please add a unit (or integration) test to cover this change?

I'm thinking about this. Probably the easiest would be to base this on the test_service.py code. Are there any runit based integration test setups available? We're using this code in a phusion/baseimage Docker container.

2019-05-03 14:35 UTC, waynew commented
@bbczeuz It doesn't look like it - `grep -Inr runit tests` doesn't show up anything of note. We have an `runit` module (`salt/modules/runit.py`), but it doesn't look like we're testing it.

2020-05-26 21:28 UTC, sagetherage commented
@bbczeuz 
please rebase this against the master branch

2021-05-17 18:17 UTC, sagetherage commented
@bbczeuz 
Reviewed in Grooming this week considering closing

2021-05-24 20:39 UTC, closed without merging