Add watchdog as a bundled dependency on Windows
saltstack/salt pull request #52818
Opened 2019-05-02 22:09 UTC by twangboy

### What does this PR do?
Adds watchdog to the requirements file for Windows. This will add some `iNotify` behavior to Windows via the watchdog beacon.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52804

### Tests written?
NA

### Commits signed with GPG?
Yes

2019-05-02 22:11 UTC, dwoz approved these changes

2019-05-10 19:33 UTC, twangboy commented
re-run all

2019-05-10 19:35 UTC, twangboy commented
re-run full all

2019-05-10 21:08 UTC, Ch3LL commented
re-run full all

2019-05-10 21:09 UTC, Ch3LL commented
i want to make sure these tests run `tests/unit/beacons/test_watchdog.py` and do not get skipped.

2019-05-17 19:45 UTC, twangboy commented
@Ch3LL This should get the tests runnin: https://github.com/saltstack/salt-jenkins/pull/1404

2019-06-17 15:54 UTC, s0undt3ch approved these changes

2019-06-17 15:54 UTC, s0undt3ch commented on tests/unit/beacons/test_watchdog.py
> +        if salt.utils.platform.is_windows():
I would create two separate test cases...

2019-07-05 15:43 UTC, twangboy commented on tests/unit/beacons/test_watchdog.py
> +        if salt.utils.platform.is_windows():
Done

2019-07-05 15:51 UTC, s0undt3ch requested changes

2019-07-05 15:51 UTC, s0undt3ch commented on requirements/static/windows.in
> +# If running under windows, please uncomment the following 2 requirements before running
You don't really need to do this anymore.
In fact, will `watchdog` be a windows packaging dependency?
If so, let's move it to `pkg/windows/reqs.txt` and recompile requirements.

2019-07-05 22:32 UTC, s0undt3ch commented on requirements/static/windows.in
> +# If running under windows, please uncomment the following 2 requirements before running
The comment at the end?

2019-07-05 22:33 UTC, s0undt3ch approved these changes

2019-07-05 22:37 UTC, s0undt3ch commented
Sorry, I didn't think this through.
We need to keep `watchdog` out of `windows.in` but it should be included in the linux'es `.in` files and also OSX `.in` files if it's not present in `pkg/osx/reqs.txt`

So sorry.

2019-07-09 15:29 UTC, Akm0d approved these changes

2019-08-09 04:26 UTC, merged