zypperpkg: don't consider error a pattern not found
saltstack/salt pull request #52844
Opened 2019-05-06 08:19 UTC by aplanas

The `rpm -q --provides --whatprovides 'pattern()' command return
error code 1 when any pattern is present. This patch ignore the
return error code, as a not found pattern is not an error.

2019-05-07 19:26 UTC, Ch3LL requested changes
can you add a regression test?

2019-05-07 19:38 UTC, aplanas commented
@Ch3LL Not sure that is needed, as this code is tested already here:

https://github.com/saltstack/salt/blob/develop/tests/unit/modules/test_zypperpkg.py#L1305

The change is a cosmetic one, as affect the logs but in any case affect the behavior.

2019-05-09 15:33 UTC, Ch3LL commented
if I'm reading that test correctly it seems to test when the `rpm` command returns when a pattern is found. Might be worthy to add a test when a pattern is not found?

2019-05-09 15:38 UTC, aplanas commented
@Ch3LL You are correct, the rpm command search for all the patterns installed, that can be 0 or more. Somehow rpm return an exit status different from 0 when no pattern is available and an ERROR is logged, but this is not a real error.

The patch do not change the behavior, as 0 or more patterns founds is a valid outcome. Only makes salt to not log ERROR when there are not patterns.

2019-05-09 15:57 UTC, Ch3LL commented
I understand that it does not change the behavior, I only was looking for a way to add more test coverage to this module since its not currently testing when the pattern is not found  and this fix addresses that situation. But you make a good point, I agree with you that this would technically would not be a regression test, as it would not fail with/without the new change, so I'll go ahead and merge for now.

2019-05-09 15:57 UTC, merged

2019-05-09 18:03 UTC, aplanas commented
@Ch3LL Thanks for the review. Detecting and pointing missing tests is really critical.