Fallback to image id if we don't have an image name on query
saltstack/salt pull request #52990
Opened 2019-05-13 22:06 UTC by sblaisot

### What does this PR do?

When an openstack VM has been instanciated with an image that gets deleted from glance (openstack image store) while the VM is still running, salt-cloud cannot get back the image name. In this case, openstack, only returns the image id but cannot get the nae back. This leads to `salt-cloud -Q` not working and stange errors on instance deletion.

While working on this, I also found a bug in instance deletion in [this line](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/openstack.py#L809): __opts__ is not an object but a dict so we should get attributes with `get` instead of `getattr`
```
>>> a = {'a': 1}
>>> print(a.get('a'))
1
>>> print(getattr(a, 'a'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'a'
```

### What issues does this PR fix or reference?

This PR fixes #52984 and #49438 

### Previous Behavior

```
# salt-cloud -Q -m my-cloud.map 
ovh-gra3:
    ----------
    openstack:
        ----------
        server1.company.tld:
            Absent
```

### New Behavior

```
# salt-cloud -Q -m my-cloud.map 
ovh-gra3:
    ----------
    openstack:
        ----------
        server1.company.tld:
            ----------
            fixed_ips:
                - 1.2.3.4
                - 2001:8d5e:104:9a64::bde:3c46
                - 10.1.2.3
            floating_ips:
            id:
                609467bf-6082-454b-a999-0f3512548260
            image:
                04787255-134b-4c96-b4ac-ac7d81e4467d
            name:
                server1.company.tld
            private_ips:
                - 10.1.2.3
            public_ips:
                - 1.2.3.4
                - 2001:8d5e:104:9a64::bde:3c46
            size:
                b2-7
            state:
                ACTIVE
```

### Tests written?

No

### Commits signed with GPG?

No

2019-05-14 16:04 UTC, Ch3LL requested changes
Thanks for the PR! Would you mind adding a regression test to ensure this does not regress in the future?

Heres some documentation on our test suite: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html to hopefully point you in the right direction. But please let me know if you have any questions.

2019-05-14 16:17 UTC, sblaisot commented
There is currently absolutely **no unit tests** for openstack provider so I'm not going to add them now in this PR, that's out of scope.

https://github.com/saltstack/salt/tree/develop/tests/unit/cloud/clouds

If one add unit tests later for openstack provider, she could add test for that particular point at the same time.

2019-05-16 16:11 UTC, Ch3LL commented
There are currently openstack integration tests, but it might be easier to write a unit test for this particular regression , which they do not currently exist as you pointed out. It should be pretty easy to emulate the other cloud unit tests and transport that to openstack. I am more than willing to help walk you through it.

If you are not able to write a test I will go ahead and keep open and add the "Needs Testcase" label for others to add tests when they have time. We have recently started requiring tests to be included with bug fixes, so we will not be able to merge this until tests are added.

2019-06-05 17:13 UTC, sblaisot commented
Sorry for the delay. I don't have the skills nor time to learn implementing the tests myself the way you usually do but feel free to have someone else add them of cherry-pick my fix.
I understand it is good practice to add test to avoid future regression.

2020-01-17 15:21 UTC, closed without merging