Chore - fix misspellings
saltstack/salt pull request #53117
Opened 2019-05-18 22:38 UTC by clickthisnick

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-05-20 14:33 UTC, waynew commented
re-run all

2019-05-20 14:44 UTC, waynew requested changes

2019-05-20 14:44 UTC, waynew commented on salt/cloud/clouds/lxc.py
> +            # to handle the unresponsive of a specific command
Not the right fix here.

2019-05-20 14:44 UTC, waynew commented on salt/modules/glance.py
> +        # This doesn't really prevent the password to show up
Should be `really prevent the password from showing up`

2019-05-20 14:44 UTC, waynew commented on salt/modules/heat.py
> +    # This doesn't really prevent the password to show up
Same here

2019-05-20 14:44 UTC, waynew commented on salt/states/btrfs.py
> +    # happened that the subvolume is there, but we also need to set it
Should be `happen`

2019-05-20 14:44 UTC, waynew commented on salt/states/modjk_worker.py
> +    # Did we get any response from someone ?
Probably should read `Did we get a response from anyone?`

2019-06-05 18:59 UTC, waynew commented
@clickthisnick there are a couple of fixes to address here, are you still interested in getting this in?

2020-05-26 21:18 UTC, sagetherage commented
@clickthisnick can you please rebase this against the master branch?

2021-05-17 18:06 UTC, sagetherage commented
Reviewed in Grooming this week considering closing

2021-05-24 20:38 UTC, closed without merging