Fix visible name capability + initial zabbix_host state test coverage
saltstack/salt pull request #53112
Opened 2019-05-17 21:23 UTC by timdufrane

### What does this PR do?
Fixes missing documented Visible Name functionality and adds basic coverage 
### What issues does this PR fix or reference?
N/A
### Previous Behavior
Visible name not updated in Zabbix, no tests for zabbix_host state

### New Behavior
Visible name now updated in Zabbix, basic test coverage for zabbix_host state

### Tests written?

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

More test coverage is to come, it's slow going as this is my first time writing tests for Python. Things are, uh, a little different than I'm used to.

2019-05-20 22:31 UTC, twangboy approved these changes

2019-05-21 19:40 UTC, Ch3LL requested changes
I know you are still writing tests so I wont review those until its no longer a WIP. But just one small thing. Can you document the new parameters in salt/states/zabbix_host.py as well?

2020-05-26 21:20 UTC, sagetherage commented
@timdufrane can you rebase this against the master branch?

2021-03-23 18:31 UTC, piterpunk commented
@sagetherage what happens in this PR is present in #58604 which already is merged. I guess it can be closed.

2021-03-23 22:50 UTC, closed without merging