Update ec2.py
saltstack/salt pull request #53111
Opened 2019-05-17 21:09 UTC by grichmond-salt

Added "if(subnet.has_key("tagSet")):" to _get_subnetname_id(subnetname).

This resolved the following error when I subnet name is provided in the ec2 profile:
```
[ERROR   ] Failed to create VM <some-new-minion>. Configuration value u'key' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2632, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1914, in request_instance
    _new_eni = _create_eni_if_necessary(interface, vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1433, in _create_eni_if_necessary
    interface['SubnetId'] = _get_subnetname_id(interface['subnetname'])
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1246, in _get_subnetname_id
    if tag['key'] == 'Name' and tag['value'] == subnetname:
KeyError: u'key'
```

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-05-20 22:36 UTC, twangboy requested changes

2019-05-20 22:36 UTC, twangboy commented on salt/cloud/clouds/ec2.py
> +        if(subnet.has_key("tagSet")):
This is failing lint... should be:
```
if 'tagSet' in subnet:
```

2019-05-23 16:36 UTC, grichmond-salt commented on salt/cloud/clouds/ec2.py
> +        if(subnet.has_key("tagSet")):
Done - thanks!

2019-05-23 16:42 UTC, twangboy approved these changes

2021-05-17 18:08 UTC, sagetherage commented
@grichmond-salt are you still working on this PR?
Reviewed in Grooming this week considering closing if no response.

2021-05-24 20:38 UTC, closed without merging