Rabbitmq additions
saltstack/salt pull request #53123
Opened 2019-05-20 09:09 UTC by github-abcde

### What does this PR do?
It adds states (in `states/rabbitmq_upstream.py` and functions (in `modules/rabbitmq.py`) to manipulate rabbitMQ upstream definitions.

### What issues does this PR fix or reference?
None that I'm aware of

### Previous Behavior
Unable to add/remove/modify rabbitMQ upstreams.

### New Behavior
RabbitMQ upstream definitions can be made `_present` or `_absent` or manipulated via execution functions.

### Tests written?
Yes

### Commits signed with GPG?
Yes

2019-05-20 10:02 UTC, mchugh19 commented on salt/modules/rabbitmq.py
> +    .. code-block:: bash
This needs an empty newline before and after

2019-05-20 10:03 UTC, mchugh19 commented on salt/modules/rabbitmq.py
> +    .. code-block:: bash
Needs a newline before and after

2019-05-20 10:03 UTC, mchugh19 commented on salt/modules/rabbitmq.py
> +    .. code-block:: bash
newline before and after

2019-05-27 08:35 UTC, github-abcde commented
@mchugh19 Could you review this again? It feels like this MR is in limbo somewhat, waiting for review but on nobody's radar (and I can't seem to find a way to find the relevant people to request for review otherwise).

2019-05-27 20:48 UTC, mchugh19 commented
I know the feeling. Unfortunately I'm just a contributor, and don't have any merge powers. I too have a few PRs outstanding with no activity right now. I think folks are currently busy on a test improvement initiative for the 2019 point release and upcoming neon.

@KChandrashekhar any thoughts?

2019-06-06 20:00 UTC, Ch3LL commented
im going to be creating the neon branch today, i've tagged for this one to get migrated to that branch after the branch creation to ensure its included in the upcoming neon release. i'll try to make some time tomorrow or monday to review this one so we can make some progress on this one for ya @github-abcde

2019-06-06 21:31 UTC, Ch3LL commented
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

2019-06-07 07:47 UTC, github-abcde commented
@Ch3LL That's ok, I have local patches for the version of salt I'm running :)
Thanks for picking this up.

2019-06-10 21:17 UTC, Ch3LL requested changes
this looks great. Just have one small request. Do you think you could add a new note about this new feature to ./doc/topics/releases/neon.rst

Would love to have this highlighted in the release notes for neon

2019-06-10 21:20 UTC, Ch3LL commented
also it looks like there is a doc test failure. pretty much you just need to add a rst file for you new state module. you can look at `doc/ref/states/all/salt.states.rabbitmq_user.rst` for an example. And if you could add it to the list here: doc/ref/states/all/index.rst

2019-06-11 09:35 UTC, github-abcde commented
@Ch3LL Added the requested docs, and fixed up the docstring in `states/rabbitmq_upstream:present`.

2019-06-18 19:56 UTC, Ch3LL commented
Updating the branch . The windows tests are not running, I believe that issues is fixed.

2019-06-18 19:57 UTC, Ch3LL approved these changes

2020-01-03 11:01 UTC, github-abcde commented
Closing because https://github.com/saltstack/salt/pull/55767 is already merged.

2020-01-03 11:01 UTC, closed without merging