Backport #53142 to 2019.2.1
saltstack/salt pull request #53271
Opened 2019-05-28 10:46 UTC by s0undt3ch

Backport #53142 to 2019.2.1

> Use six.reraise for the greater good

> In Python2, `raise exc` obliterates the stack trace. That's no good.

> Fortunately, six has a useful syntax that works across Python versions.
> It does have the downside of adding `reraise` to the stacktrace, but
> otherwise, this should be better.

2019-05-28 17:03 UTC, DmitryKuzmenko commented
Looks good for me, just have a couple of questions/comments.
1. There are still a number of places in 2019.2.1 containing the pattern "except .. as ex: raise ex" that is completely removed from 2018.3 by the original commit. Is it OK?
2. This is true for the original PR too: in most of places we're not using the exception variable anymore. So maybe it's better to replace `except ... as ex` with `except ...`?

2019-05-28 17:26 UTC, s0undt3ch commented
After you comment @DmitryKuzmenko I went and look for additional occurrences which are now fixed.
As for `except Exception as blah`, if we use `blah` we should keep it, when not using it, we should remove it. See any place where it should be removed?

2019-05-28 17:35 UTC, waynew commented
IIRC the linter catches the unused `as blah:`... but I could be wrong!

2019-05-29 07:16 UTC, DmitryKuzmenko requested changes
Here are all places we got unused variable after this change.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on salt/scripts.py
> +        six.reraise(*sys.exc_info())
Unused `exc`.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on salt/utils/asynchronous.py
> +                six.reraise(*sys.exc_info())
Unused `ex`.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on salt/utils/json.py
> +            six.reraise(*sys.exc_info())
Unused `exc`.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on tests/integration/states/test_ssh_known_hosts.py
> +                six.reraise(*sys.exc_info())
The original code raises the first exception that is the `err`. The new code reraises the last (nested) AssertionError. Is is expected?

2019-05-29 07:16 UTC, DmitryKuzmenko commented on tests/integration/states/test_ssh_known_hosts.py
> +                six.reraise(*sys.exc_info())
The same as above.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on tests/runtests.py
> +    six.reraise(*sys.exc_info())
Unused `exc`.

2019-05-29 07:16 UTC, DmitryKuzmenko commented on tests/support/helpers.py
> +                    six.reraise(*sys.exc_info())
Unused `exc`.

2019-05-29 07:18 UTC, DmitryKuzmenko commented
@waynew Just checked in my dev environmant: lint says it's OK to have unused `as exc` variables.. ¯\_(ツ)_/¯

2019-05-29 11:18 UTC, s0undt3ch commented on salt/minion.py
>                      if attempts == tries:
Err, we disabled that pylint rule.
@DmitryKuzmenko I'll address that in a different PR

2019-05-29 11:19 UTC, DmitryKuzmenko commented on salt/minion.py
>                      if attempts == tries:
Sure! I'm just pointing things I've found. No problem.

2019-05-29 11:20 UTC, s0undt3ch commented on salt/minion.py
>                      if attempts == tries:
No, no, you did the right thing, Thanks!

2019-05-29 11:20 UTC, DmitryKuzmenko commented on tests/integration/states/test_ssh_known_hosts.py
> +                six.reraise(*sys.exc_info())
@s0undt3ch this one still need to be fixed here. It's minor, but it directly relates.

2019-05-29 11:39 UTC, s0undt3ch commented on salt/scripts.py
> +        six.reraise(*sys.exc_info())
This one needs to be re-thought

2019-10-19 17:23 UTC, closed without merging