stops pylint E1120 from showing
saltstack/salt pull request #53289
Opened 2019-05-28 21:55 UTC by cmcmarrow

### What does this PR do?
silences pylint E1120(no-value-for-parameter)

I don't believe there is a good way to fix this pylint warring. pylint is complaining about a method in a 3rd party library. The 3rd party library did something wrong. We add it default arguments to methods in the 3rd party library. 

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/53285

### Tests written?

No

### Commits signed with GPG?

Yes

2019-05-30 19:43 UTC, Akm0d approved these changes

2019-05-31 00:15 UTC, twangboy requested changes

2019-05-31 00:15 UTC, twangboy commented on tests/unit/modules/test_kubernetesmod.py
> +# pylint: disable=E1120
You need to enable this after the part that is failing.
```
# pylint: disable=E1120
some code
# pylint: enable=E1120
```

2019-05-31 20:59 UTC, garethgreenaway approved these changes

2019-05-31 21:19 UTC, twangboy approved these changes

2019-05-31 21:36 UTC, Akm0d approved these changes

2019-06-01 04:57 UTC, merged