Fix codespell issues
saltstack/salt pull request #53339
Opened 2019-06-02 14:52 UTC by mjtrangoni

### What does this PR do?
This fixed some trivial spelling issues found by [codespell](https://github.com/codespell-project/codespell).
I think this could be added to the CI, and if you agree, I can fix the remaining spelling issues in one or more separate PR.

### What issues does this PR fix or reference?
none

### Tests written?
No, no needed

### Commits signed with GPG?
No

2019-06-02 17:40 UTC, rares-pop approved these changes

2019-06-06 19:39 UTC, Ch3LL commented
@mjtrangoni looks like there is a merge conflict here, if you could take care of that.

Also @saltstack/team-core any thoughts on adding codespell to our test infrastructure?

2019-06-10 14:39 UTC, mjtrangoni commented
@Ch3LL done

2019-06-14 02:59 UTC, twangboy requested changes

2019-06-14 02:59 UTC, twangboy commented on salt/modules/glance.py
> +    # The trailing 'v2' causes URLs like these one:
this

2019-06-14 02:59 UTC, twangboy commented on salt/modules/highstate_doc.py
> +    processor = config.get('processor')
This whole section makes me a little nervous. Have all references to this function also been renamed?

2019-06-14 02:59 UTC, twangboy commented on salt/modules/highstate_doc.py
> +def processor_markdown(lowstate_item, config, **kwargs):
Same thing here...

2019-06-14 02:59 UTC, twangboy commented on salt/modules/localemod.py
> +    properties = dbus.Interface(localedbus, 'org.freedesktop.DBus.Properties')
`locale_dbus` or `locale_bus`... or just `locale` maybe

2019-06-14 02:59 UTC, twangboy commented on salt/modules/victorops.py
> +                # Should this failed on the wrong type.
fail

2019-06-14 02:59 UTC, twangboy commented on salt/modules/win_status.py
> +    #a proper run of the function, creating a nonsensically long out put.
output

2019-06-14 02:59 UTC, twangboy commented on salt/modules/zpool.py
> +    ## reopen all devices for a pool
from a

2019-06-14 16:10 UTC, waynew commented
I'm 👍 on adding codespell to testing

2019-06-22 15:47 UTC, mjtrangoni commented
@twangboy PTAL

2020-05-26 21:08 UTC, sagetherage commented
@mjtrangoni can you please rebase this against the master branch?

2021-04-19 14:44 UTC, sagetherage commented
@mjtrangoni can you please rebase this against the master branch?

2021-05-03 22:58 UTC, sagetherage commented
Reviewed in Grooming 2021-MAY-03 closing

2021-05-03 22:58 UTC, closed without merging