Fix salt-ssh pillar bug for state.sls_id function
saltstack/salt pull request #53348
Opened 2019-06-03 16:35 UTC by xuhcc

### What does this PR do?

Fixes #51353

### Previous Behavior

salt-ssh ignored `pillar` CLI argument during execution of `state.sls_id` function

### New Behavior

now it should work

### Tests written?

No

### Commits signed with GPG?

No

2019-06-05 16:06 UTC, Ch3LL reviewed
thanks for pushing the fix for this :) really appreciate it. any chance we can get a test added here to insure this does not regress in the future? Should be pretty easy to use the current state.sls_id tests in tests/integration/ssh/test_state.py for an idea on how to approach the test.

2019-06-06 08:24 UTC, xuhcc commented
@Ch3LL Unfortunately I can't get integration tests working. 

```
$ python tests/runtests.py -n integration.ssh.test_state.SSHStateTest.test_state_sls_id
 --------  Skipped Tests  ------------------------
   -> integration.ssh.test_state.SSHStateTest.test_state_sls_id  ->  SSH tests are disabled
```

2019-06-06 19:20 UTC, Ch3LL commented
what if you add the arg `--ssh`

2019-06-06 21:24 UTC, Ch3LL commented
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

2019-06-06 21:28 UTC, xuhcc commented
@Ch3LL `--ssh` worked, thank you! I added the test.

2019-06-07 18:03 UTC, Ch3LL requested changes

2019-06-07 18:32 UTC, xuhcc commented on tests/integration/ssh/test_state.py
> +        os.remove('/tmp/test_pillar')
Done.

2020-03-10 21:42 UTC, waynew submitted a review, later dismissed

2020-03-10 21:45 UTC, waynew commented
re-run all

2020-04-01 21:18 UTC, sagetherage commented
@xuhcc will you rebase against master, please?

2020-04-02 08:19 UTC, xuhcc commented
@sagetherage Done!

2020-04-23 14:47 UTC, Ch3LL commented
@xuhcc looks like there is a merge conflict here.

2020-04-27 14:20 UTC, Ch3LL commented
looks like just a lint and pre-commit failure now.

2020-04-28 15:52 UTC, Ch3LL approved these changes

2020-04-29 22:26 UTC, merged