Fixed napalm_beacon logic for python 3
saltstack/salt pull request #53433
Opened 2019-06-10 22:15 UTC by raddessi

### What does this PR do?
Fixes (for me) the napalm_beacon module's `validate` function when running on python 3.

### What issues does this PR fix or reference?
I hit a bug trying to use the napalm_beacon on python 3, due to the dict_keys and dict_values objects not being iterable any more.

With just the pillar code copied out of the napalm_beacon example page
```python
[CRITICAL] The beacon errored: 
Traceback (most recent call last):
  File "/opt/miniconda/envs/salt/lib/python3.6/site-packages/salt/minion.py", line 2592, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/opt/miniconda/envs/salt/lib/python3.6/site-packages/salt/minion.py", line 449, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/opt/miniconda/envs/salt/lib/python3.6/site-packages/salt/beacons/__init__.py", line 104, in process
    valid, vcomment = self.beacons[validate_str](b_config[mod])
  File "/opt/miniconda/envs/salt/lib/python3.6/site-packages/salt/beacons/napalm_beacon.py", line 290, in validate
    fun_cfg = mod.values()[0]
TypeError: 'dict_values' object does not support indexing
```

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-06-10 22:17 UTC, raddessi commented
Ah crap, my black plugin auto formatted everything in the file. I can revert, it's only 4 lines of change, but do you all have an auto formatter for this project already? If so I'll add that in to my editor.

2019-06-15 00:24 UTC, waynew commented
@raddessi no, we don't have auto formatting yet, though there's been some discussion about possibly adopting `black -S`, since we do prefer `'` wrapped strings.

2019-06-15 00:28 UTC, waynew requested changes
Just a couple of minor tweaks. Also, would it be possible to write a test for this? Or, if there's already some tests over this section, updating the test so it properly exercises this section on Python2 and 3.

Otherwise, 👍

2019-06-15 00:28 UTC, waynew commented on salt/beacons/napalm_beacon.py
> +        fun = list(mod.keys())[0]
This can just be `list(mod)[0]` - the default creating a list from mapping is to use the keys.

2019-06-15 00:28 UTC, waynew commented on salt/beacons/napalm_beacon.py
> +        fun = list(mod.keys())[0]
Same thing here - `list(mod)[0]`

2019-06-17 09:47 UTC, mirceaulinic approved these changes
Thanks!

2020-02-25 22:54 UTC, raddessi commented
I'm closing this out myself (I didn't realize we had that capability) as it is superceded by https://github.com/saltstack/salt/pull/56243, thanks all

2020-02-25 22:55 UTC, closed without merging