xfs: do not fails if type is not present
saltstack/salt pull request #53447
Opened 2019-06-11 15:23 UTC by aplanas

The command `blkid -o export` not always provides a 'TYPE' output
for all the devices. One example is non-partitioned devices, and
also Btrfs subvolumes.

This patch do not force the presence of this field in the blkid
output.

### Tests written?

No

2019-06-14 03:40 UTC, twangboy submitted a review, later dismissed

2019-07-22 11:25 UTC, aplanas commented
Rebased, in hope that the windows tests are fixed

2019-07-22 11:53 UTC, aplanas commented
backport in: https://github.com/saltstack/salt/pull/53941

2019-10-14 12:09 UTC, aplanas commented
Rebased into master

2019-10-15 13:28 UTC, waynew submitted a review, later dismissed
@aplanas looks great so far! Could you add one more test case, basically a dupe of the existing one, but remove the `TYPE=xfs` line?

We want to make sure that if `TYPE` is missing that we don't error, right? Looks like the existing test should pass with or without your change, but without companion test it's possible that someone could introduce a regression in the future.

(If there is already another test that does that, feel free to point me in that direction - just not seeing it near this code.)

2019-10-15 13:52 UTC, aplanas commented
> @aplanas looks great so far! Could you add one more test case, basically a dupe of the existing one, but remove the `TYPE=xfs` line?
> 
> We want to make sure that if `TYPE` is missing that we don't error, right? Looks like the existing test should pass with or without your change, but without companion test it's possible that someone could introduce a regression in the future.

I do not understand. This is already tested. You can see the /dev/sdb1 do not have a TYPE parameter, and the assertion is based only on the data of /dev/sda1.

To make it more clear I will change the PARTUUID section from /dev/sdb1 to be explicit that we do not expect it.

2019-10-17 13:47 UTC, aplanas commented
> Ah! I didn't realize that those were two separate blocks, my bad! I'm +1 now.

No problem! :+1: 

> Looks like we have some similar test failures to that other PR of yours. Checking on these failures now.

Do you think that is only on my PR? :thinking:

2019-10-17 13:49 UTC, waynew commented
The mac issues I know are global, and there are some timeout issues that I believe we *finally* have a resolution for (dhcp leases during long-running suites). The Windows failures I don't think I've seen recently - they might be related, though that would be surprising, I think 🤔

2019-10-17 13:54 UTC, aplanas commented
> The Windows failures I don't think I've seen recently - they might be related, though that would be surprising, I think

XFS tests are indeed not expected to be executed on Windows machines. And checking the log I do not see them.

I am very bad on Windows, so I do not think that I can help on the diagnosis.

2020-02-28 22:16 UTC, waynew requested changes
Hey @aplanas, thanks for the PR!

We've recently updated `master` to assume that mock actually exists everywhere. If mock doesn't at this point that should be a big problem. Can you go ahead and remove that from your tests?

2020-02-28 22:16 UTC, waynew commented on tests/unit/modules/test_xfs.py
> +    NO_MOCK_REASON,
```suggestion
```

2020-02-28 22:16 UTC, waynew commented on tests/unit/modules/test_xfs.py
> +@skipIf(NO_MOCK, NO_MOCK_REASON)
```suggestion
```

2020-03-02 09:47 UTC, aplanas commented on tests/unit/modules/test_xfs.py
> +    NO_MOCK_REASON,
Yes, thanks!!

2020-03-02 09:47 UTC, aplanas commented on tests/unit/modules/test_xfs.py
> +@skipIf(NO_MOCK, NO_MOCK_REASON)
Thanks!

2020-03-02 10:34 UTC, aplanas commented
Yep. Ignore the lint, is not related with my code:

************* Module salt.returners.django_return
salt/returners/django_return.py:42: [E0611(no-name-in-module), ] No name 'dispatch' in module 'django'

------------------------------------
Your code has been rated at 10.00/10

2020-04-15 18:51 UTC, waynew commented
Something weird seems to have happened with the tests, probably jenkins+aws+github. Updating your branch to see if that fixes it.

2020-04-15 19:14 UTC, waynew commented
looks like things are at least reporting now. A minor isort complaint, but I'm strongly inclined to ignore that if there aren't any other issues here.

2020-04-16 08:26 UTC, aplanas commented
Looks like the the `isort` pinned in the project produces a different output that the official release of `isort` in relation to comments on the import. Also I saw how the interaction between black a isort produces inestable results, so one do / undo the change of the other.

2020-04-16 22:26 UTC, waynew commented
> Looks like the the `isort` pinned in the project produces a different output that the official release of `isort` in relation to comments on the import

That's why we've pinned to a different version. The pinned version in question provides an option that agrees with Black on imports.

2020-04-16 22:27 UTC, waynew submitted a review, later dismissed
Looks good 👍

2020-05-15 06:37 UTC, aplanas commented
no failing test, re-review?

2020-05-18 23:08 UTC, dwoz approved these changes

2020-05-18 23:08 UTC, merged