Banner
saltstack/salt pull request #53499
Opened 2019-06-15 15:39 UTC by amendlik

### What does this PR do?
Address a number of issues with `slsutil.banner`
1. Typo in the default banner text
2. Issue when the comment character was padded with a space
3. More examples in the documentation
4. Unhandled exception when the width was too small

### What issues does this PR fix or reference?
None

### Tests written?
Yes

### Commits signed with GPG?
Yes

2019-06-24 19:43 UTC, amendlik commented
@cmcmarrow We'll want to put this on the neon branch, now that that exists.

2019-07-01 18:37 UTC, amendlik commented
@Ch3LL, @cmcmarrow Any update on this PR?

2019-07-02 14:39 UTC, Ch3LL commented
@amendlik i went ahead and added it to be backported to neon once this is merged.

bump @cmcmarrow waiting on your review here.

2019-07-08 18:54 UTC, amendlik commented
@Ch3LL, can you contact @cmcmarrow and let him know we're waiting on him? I had another PR that sat for 6 weeks and later found out the assignee had his GitHub notifications turned off. Maybe that is what's going on here.

2019-07-30 17:19 UTC, cmcmarrow requested changes

2019-07-30 17:19 UTC, cmcmarrow commented on salt/modules/slsutil.py
> +        #                       Copyright 2019 ACME Corp                       #
Can we change 'ACME Corp' to Salt for this example?

2019-07-30 17:20 UTC, cmcmarrow commented
@amendlik I just have one request for change. Other than that it looks good. Thanks for the test!

2019-07-30 17:37 UTC, cmcmarrow commented on salt/modules/slsutil.py
> +        #                       Copyright 2019 ACME Corp                       #
Its because ACME Corp is a thing. https://www.acmecorp.com/

2019-08-06 14:14 UTC, Ch3LL commented
ping  @cmcmarrow  this is ready for your re-review

2019-08-13 14:50 UTC, amendlik commented
@cmcmarrow @Ch3LL What is going on at SaltStack that PR's now take 2 months to be merged? It used to be a week at the most. I don't mean to sound critical, but the level of support for contributors has dropped drastically over the last year, and SaltStack has done nothing to manage expectations.

2019-08-13 14:57 UTC, Ch3LL commented
@amendlik we have been slowing down merges as we attempt to stabilize our test suite. There's a bit more explanation here: https://groups.google.com/forum/#!topic/salt-announce/5RJjtDYszx8

We want to lower the gap between merge and release time, but unfortunately that requires us to slow down on merges as we ensure our test suite is stabilized. I'll ping @cmcmarrow offline because it looks like we might be able to get this one in. Let me know if I can clarify anything else.

2019-08-13 15:49 UTC, merged

2020-04-21 14:34 UTC, s0undt3ch commented
Master port https://github.com/saltstack/salt/pull/56761