Pkgrepo
saltstack/salt pull request #53537
Opened 2019-06-19 20:11 UTC by Akm0d

### What does this PR do?
Makes pkgrepo.managed check for a changed key_url

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/4438

### Tests written?
Yes

### Commits signed with GPG?

Yes

2019-06-19 22:06 UTC, Akm0d commented on salt/states/pkgrepo.py
> +                if sorted(sanitizedkwargs[kwarg]) != sorted(pre[kwarg]):
Yes, that makes sense :+1:

2019-06-19 23:23 UTC, waynew requested changes

2019-06-19 23:23 UTC, waynew commented on salt/states/pkgrepo.py
> +            elif kwarg in ['comps', 'key_url']:
Mind changing this to a tuple?
```suggestion
            elif kwarg in ('comps', 'key_url'):
```

2019-06-20 00:03 UTC, waynew approved these changes

2019-06-20 00:03 UTC, merged