catch any exception on reading rsa key
saltstack/salt pull request #53555
Opened 2019-06-20 21:15 UTC by mattp-

### What does this PR do?
an unhandled exception thrown at this point of code will put MWorker into an unrecoverable hung state that leaks memory as MWorkerQueue continues passing it work that is ignored. In my case I encountered an RSAError but I see no reason to be specific for exception class here.

### Tests written?
No. not exactly sure how to write an integration test to trigger this since its embedded in _auth() in salt.transport.mixins.auth.

**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-06-20 21:48 UTC, s0undt3ch commented
re-run full all

2019-06-20 21:50 UTC, s0undt3ch requested changes
Lets add `exc_at_loglevel=logging.DEBUG` on the `log.error()` call too. We want the whole traceback.

2019-06-20 22:22 UTC, mattp- commented
@s0undt3ch sure - can you point me to what bit of logging you're talking about though? Not sure I know what you mean by exc_at_loglevel/don't see it documented 🙂

2019-06-20 22:41 UTC, s0undt3ch commented
Sure! An example can be found [here](https://github.com/saltstack/salt/blob/b44f0f1d0fd564690c6e45c6dd061c0e84d76def/salt/utils/mount.py#L60)

2019-06-21 13:58 UTC, mattp- commented
a-ha, its part of salt.log.setup,exc_info_at_loglevel not exc_at_loglevel 🙂 updated

2019-06-23 20:56 UTC, s0undt3ch approved these changes

2019-06-23 20:57 UTC, merged