Backport beacon test fix
saltstack/salt pull request #53626
Opened 2019-06-27 16:59 UTC by dwoz

### What does this PR do?

Backports fix for `integration.states.test_beacon.BeaconStateTestCase.test_present_absent` from 2019.2.1 to 2018.3

### Tests written?

No - Fixing existing test

### Commits signed with GPG?

Yes

2019-06-27 17:02 UTC, s0undt3ch requested changes
Just need to use the new pipelines in the base branch for the new pipelines you introduce here.

2019-06-27 19:31 UTC, s0undt3ch approved these changes

2019-07-03 14:56 UTC, waynew approved these changes

2019-07-03 14:57 UTC, garethgreenaway approved these changes

2019-07-03 14:58 UTC, merged