proxy minion __virtual__ error cleanup
saltstack/salt pull request #53631
Opened 2019-06-27 21:44 UTC by dhiltonp

### What does this PR do?
proxy minions may not have os/os_family/kernel set.

Let's use `__grains__.get('os')` appropriately so errors aren't written to logs.

2019-06-28 00:14 UTC, garethgreenaway requested changes

2019-06-28 00:14 UTC, garethgreenaway commented on salt/modules/gentoolkitmod.py
> +    if __grains__('os_family') == 'Gentoo' and HAS_GENTOOLKIT:
Should this include a get as well?

2019-06-28 00:35 UTC, dhiltonp commented on salt/modules/gentoolkitmod.py
> +    if __grains__('os_family') == 'Gentoo' and HAS_GENTOOLKIT:
thanks for the catch!

2019-06-29 17:24 UTC, dhiltonp commented
merged #53632

2019-06-29 17:24 UTC, closed without merging