[neon] Log which address failed to resolve
saltstack/salt pull request #53655
Opened 2019-06-28 10:17 UTC by s0undt3ch

### What does this PR do?
See title

### Tests written?
No - Log call change

2019-06-28 17:08 UTC, Akm0d approved these changes

2019-07-01 08:25 UTC, rares-pop approved these changes

2019-07-01 18:27 UTC, twangboy requested changes

2019-07-01 18:27 UTC, twangboy commented on salt/grains/core.py
> +    err_message = 'Exception during resolving address \'%s\': %s'
`Exception resolving address` sounds better
or
`An exception occurred resolving address`

2019-07-02 21:12 UTC, twangboy approved these changes

2019-12-19 19:45 UTC, closed without merging