Update list_containers call
saltstack/salt pull request #53811
Opened 2019-07-11 13:09 UTC by gecube

Add capability of filtering the containers with list_containers call as it is available with ps_ call.

### What does this PR do?

It implements of pass-through of filtering to lower ps_ call

### What issues does this PR fix or reference?

### Previous Behavior

list_containers just shows the flat list of containers names without any capability of filtering

### New Behavior

Add option to use filtering

### Tests written?

No

### Commits signed with GPG?

No

2019-07-11 13:11 UTC, gecube commented
Also I accidentally make the changes to the documentation as requested by #53601

2019-07-29 22:23 UTC, cmcmarrow commented
Hi @gecube! Thanks for the code. Just one problem. Can you write a test for this change?

2019-07-30 10:28 UTC, gecube commented
@cmcmarrow  Hm. OK. I will do it ASAP.

2020-03-17 17:45 UTC, cmcmarrow requested changes
Hi @gecube! Thanks for the code. Just one problem. Can you write a test for this change?

2020-05-26 20:54 UTC, sagetherage requested changes
please point this to the master branch instead of develop

2021-04-19 15:00 UTC, sagetherage commented
@gecube please point this to the master branch instead of develop, please?

2021-05-03 18:15 UTC, sagetherage commented
Reviewed in Grooming 2021-MAY-03 considering closing

2021-05-04 15:51 UTC, sagetherage commented
Corresponded with @gecube via saltstackcommunity.slack.com and George will rebase and get tests written - thank you!!

2021-05-17 18:55 UTC, cmcmarrow requested changes
Overall, this change is fine. But I see room for two improvements. 1. The filter Doc string should describe what it does rather than point to another doc string. 2 it does not have any tests. This add on is relatively small, so just one or two tests using the filter `*arg` should do the trick.

2021-05-17 19:05 UTC, sagetherage commented
@waynew this may be a good one for the Test Clinic tomorrow! :-)

2023-12-10 05:18 UTC, dwoz commented
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 05:18 UTC, closed without merging