fixed: zabbix_user on Zabbix 4.0+
saltstack/salt pull request #53865
Opened 2019-07-16 12:55 UTC by slivik

### What does this PR do?
Zabbix 4.x API has changed (user media object was removed) so adjustments in the zabbix_user module were necessary. Changes are backward compatible with Zabbix 3.x.
There was also a bug that test mode was not working. It is also fixed now.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/53203

### Tests written?
No

### Commits signed with GPG?
Yes

2020-01-16 15:59 UTC, waynew commented
@slivik thanks for the PR - my [comment on your other PR applies](https://github.com/saltstack/salt/pull/53550#issuecomment-575218904) could you rebase against master?

2020-02-25 10:01 UTC, remichristiaan commented
In what salt version this fix is going to be released?

2020-05-26 20:51 UTC, sagetherage commented
> In what salt version this fix is going to be released?

it needs to be rebased against the master branch to be considered for a release

2020-05-26 20:51 UTC, sagetherage requested changes
please rebase against the master branch

2020-05-27 19:02 UTC, waynew commented
@slivik if you rebase this against master, then it would be possible to get this merged for the Magnesium release.

2020-06-15 23:05 UTC, waynew requested changes
Hey @slivik, thanks again for the PR! We definitely appreciate your efforts so far! I tried rebasing this on master but it didn't work very well - and I'm not sure if the fix was already there or not.

We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.
 
Thanks again!

2021-04-19 15:50 UTC, sagetherage commented
@slivik 

Discussed in Grooming 2021-APR-19 we have requested more than once to rebase and no response, closing.

2021-04-19 15:50 UTC, closed without merging