xfs: do not fails if type is not present
saltstack/salt pull request #53941
Opened 2019-07-22 11:52 UTC by aplanas

The command `blkid -o export` not always provides a 'TYPE' output
for all the devices. One example is non-formatted partitions, like for
example the BIOS partition.

This patch do not force the presence of this field in the blkid
output.

(cherry picked from commit 42e72265fef5a52cfcd3fe760ce9f1c0c7723ef3)

2019-08-28 18:08 UTC, waynew requested changes
Hey @aplanas thanks for the PR! Would it be possible to toss together a small regression test for this?

Looks like this function is (fortunately) fairly minimal and the only things you might have to mock is `_get_mounts()` and `flt()`.

2019-08-29 11:27 UTC, aplanas commented
@waynew done, here and in https://github.com/saltstack/salt/pull/53447

2019-08-29 21:50 UTC, waynew approved these changes

2019-10-14 12:54 UTC, aplanas commented
Rebased on top of master in https://github.com/saltstack/salt/pull/53447

2019-10-14 12:54 UTC, closed without merging