auth: log details in case of user auth issue
saltstack/salt pull request #53990
Opened 2019-07-24 09:33 UTC by eliasp

When a local SaltClient sends a job as "root" while the Master runs as a non-root user, make it more clear why the message `Authentication failure of type "user" occurred.` is logged.

### What does this PR do?

Improve logging, to save the next one affected a few hours of debugging 😄 

### What issues does this PR fix or reference?

None

### Previous Behavior

When the Master runs as non-root user, but `root` is used locally on the CLI for any kind of operations (`salt \* test.ping`, ...), no Job could be created. The only message that was logged without any further indication what might cause the failure was `Authentication failure of type "user" occurred.`

### New Behavior
An additional log message (level: `warning`) was added which states:
```
Master runs as "some-other-user", but user in payload is "root"
```

### Tests written?

No - doesn't really apply, as it's just an added log message.

### Commits signed with GPG?

Yes

2019-07-24 18:40 UTC, waynew requested changes
Thanks for the PR!

This mostly looks great, just a minor change to the logging code.

2019-07-24 18:40 UTC, waynew commented on salt/auth/__init__.py
> +                    log.warning('Master runs as "{}", but user in payload is "{}"'.format(self.opts.get('user', 'root'), load['user']))
```suggestion
                    log.warning('Master runs as %r, but user in payload is %r', self.opts.get('user', 'root'), load['user'])
```

Salt prefers log formatting for logs. I'm surprised that the linter didn't complain about this one :suspect: Usually it does.

2019-07-25 15:55 UTC, waynew approved these changes

2019-07-25 15:59 UTC, twangboy approved these changes

2019-07-25 16:12 UTC, Akm0d approved these changes

2019-08-23 20:25 UTC, cmcmarrow approved these changes

2019-08-23 20:26 UTC, merged

2020-04-18 03:02 UTC, terminalmage commented
Ported to master in https://github.com/saltstack/salt/pull/56692