(Backport 53996) Fix kwargs iteration for chroot.call
saltstack/salt pull request #53997
Opened 2019-07-24 12:43 UTC by aplanas

### What does this PR do?

Fix a bug during the call of the kwargs parameters for chroot.call()

### Tests written?

Yes

(backpor #53996)

2019-08-28 18:04 UTC, waynew requested changes

2019-08-29 09:04 UTC, aplanas commented on tests/unit/modules/test_chroot.py
> +            salt_mock['cmd.run_chroot'].assert_called_once()
Makes sense, yes.

2019-08-29 09:50 UTC, aplanas commented on tests/unit/modules/test_chroot.py
> +            salt_mock['cmd.run_chroot'].assert_called_once()
Done here and in https://github.com/saltstack/salt/pull/53996

2019-09-10 19:17 UTC, Ch3LL commented
> Fix a bug during the call of the kwargs parameters for chroot.call()
Can you clarify what the bug is?

2019-09-16 15:38 UTC, Ch3LL approved these changes

2019-09-18 15:38 UTC, waynew approved these changes

2019-09-18 15:39 UTC, waynew commented
Just to leave ourselves a comment on this - changing the parameter name isn't a problem since this is an unreleased feature, but we do need to make sure that this goes in *with* the chroot feature.

2019-10-14 12:58 UTC, aplanas commented
Rebased on master as part of https://github.com/saltstack/salt/pull/54959

2019-10-14 12:59 UTC, closed without merging