[2019.2.1] Porting metaproxy changes in #50183 to 2019.2.1
saltstack/salt pull request #54001
Opened 2019-07-24 17:58 UTC by garethgreenaway

### What does this PR do?
Porting metaproxy changes in #50183 to 2019.2.1

### What issues does this PR fix or reference?
N/A

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.
Yes.  Proxy tests exist.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-07-29 18:11 UTC, xeacott approved these changes

2019-08-07 17:55 UTC, dwoz commented
re-run full all

2019-08-08 00:41 UTC, dwoz approved these changes

2019-08-08 01:47 UTC, twangboy requested changes

2019-08-08 01:47 UTC, twangboy commented on salt/minion.py
> +    log.debug('=== here ====')
Is this leftover from some debugging?

2019-08-08 01:47 UTC, twangboy commented on salt/proxy/dummy.py
> +This is the a dummy proxy-minion designed for testing the proxy minion subsystem.
Probably need to remove `the`

2019-08-08 04:24 UTC, dwoz commented
@twangboy In the interest of making progress towards the release I am going to merge this.

@garethgreenaway Please make another PR to resolve @twangboy's comments.

2019-08-08 04:24 UTC, merged