Key timeout thorium name match
saltstack/salt pull request #54098
Opened 2019-08-02 13:55 UTC by remijouannet

### What does this PR do?

adding name_match parameter to key.timeout thorium

### Previous Behavior
key.timeout is apply to every minion

### New Behavior
name_match add the behavior to only clean some minion

the following use case is i have some machine that must never be automatically delete from salt-master and on the other side i have hundred of machine that are run/terminate automatically with random hostname

2019-08-05 14:17 UTC, thatch45 submitted a review, later dismissed

2019-08-19 13:20 UTC, remijouannet commented
anyone ?

2019-08-21 15:39 UTC, waynew commented
Hi @remijouannet thanks for the PR! Would you be able to write some test(s) for this?

2019-08-21 15:42 UTC, remijouannet commented
Hello @waynew, it's not that i don't want to do it,
but i can't find in the code where do you put the tests for thorium module

2019-08-28 18:06 UTC, Akm0d submitted a review, later dismissed

2019-09-25 16:18 UTC, remijouannet commented
Hello, just upping this PR has I didn't have any answer about the tests

2019-12-26 12:46 UTC, remijouannet commented
Hello @cmcmarrow @thatch45 @waynew, 
this PR was open month ago, i was told to write some tests but there is currently 0 tests for thorium module so i don't know where to put them
do you mind helping me finish this PR ?

2020-03-11 20:20 UTC, cmcmarrow requested changes
Looks good all we need are some test.

2020-05-26 20:44 UTC, sagetherage commented
@remijouannet this now needs to be rebased against the master branch - as for writing tests, there is a test clinic this week that could help, @waynew can we put this on the test clinic agenda?

2020-05-27 09:49 UTC, remijouannet commented
hello @sagetherage, i rebased my branch and change the PR to master
I will be thankfull to have some help to finish this PR

2020-08-12 18:06 UTC, waynew commented
Hey @remijouannet I'd love to help you out with tests - would you be able to attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule)?

2020-08-13 13:16 UTC, remijouannet commented
Hello @waynew yes i can, the next test clinics is today 17:00 GMT+2 ?

2020-08-13 15:27 UTC, waynew commented
@remijouannet yes - starting a bit late today, had a couple of things pop up, but should be starting soon!

2022-11-09 21:22 UTC, Ch3LL commented
following up here. Any interest in pushing this PR to completion @remijouannet ?

2022-11-10 10:20 UTC, remijouannet commented
Hello @Ch3LL i'll be glad too, but you're asking to write tests for my change but there is currently 0 tests for thorium in the codebase and i have no idea on how to write the first tests ever for thorium, if someone could at least write just one test for thorium/key.py so i could take it as example to write mine

2022-11-10 18:03 UTC, Ch3LL commented
Thats a fair point. I'll add this to my backlog to help get a test added here.

2023-12-10 05:20 UTC, dwoz commented
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 05:20 UTC, closed without merging