replace pycrypto with pycryptodomex [2018.3]
saltstack/salt pull request #54241
Opened 2019-08-16 22:51 UTC by JanZerebecki

pycrypto is unmaintained and has open security issues.

Fixes: #54115

Forward port of https://github.com/saltstack/salt/pull/54119

### What does this PR do?
replace pycrypto with pycryptodomex, like it already is on many platforms

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/54115

### Previous Behavior
require pycrpto

### New Behavior
require pycryptodomex

### Tests written?
No, drop in replacement of functionality.

### Commits signed with GPG?
Yes

2019-08-18 12:39 UTC, JanZerebecki commented
Many CI failures also happen without this patch.

2019-08-28 07:24 UTC, s0undt3ch requested changes
Yes, we'd need to regenerate all static requirements.
```
pip install pre-commit
pre-commit run -av
```
Take a few cups of coffee.
First pre-commit run will show failures because files were updated, this is ok.
Second run should be all green.

2020-01-29 00:13 UTC, dmurphy18 requested changes
These changes need to be migrated to 'master' branch for Neon or later. the 2018.3 branch is CVE only.
Some tests for a PR are required, if only to confirm that pycryptodomex installed, noting that have run into issues with pycryptodomex in 32-bit environments

2020-05-21 17:05 UTC, s0undt3ch commented
We have switched to pycryptodome for the upcoming Sodium release on https://github.com/saltstack/salt/pull/56625

2020-05-21 17:05 UTC, closed without merging