Add in support for reserved_percentage kwarg and correct documentation.
saltstack/salt pull request #54500
Opened 2019-09-16 14:23 UTC by qcpeter

### What does this PR do?

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/54426

### Previous Behavior
Misleading documentation.

### New Behavior
Adds in `reserved_percentage` kwarg and updates documentation.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-09-16 15:07 UTC, Ch3LL requested changes
any chance we can get a test added here to ensure this does not regress? There are currently some unit tests here `./tests/unit/modules/test_extfs.py` Other than that this looks great, nice catch :)

2019-09-19 07:20 UTC, qcpeter commented
I'm afraid I'm going away for ten days so will be unable to take a look at this immediately. Presumably you're thinking of some sort of test that passes in the kwargs and tests the flags that are passed the `cmd.run` mock? The existing tests are pretty minimal.

2019-10-01 15:05 UTC, waynew commented
@qcpeter yeah, that should be sufficient. This doesn't really have a lot of logic, so it shouldn't be too difficult. There may be a test that already exists that could just be extended, but if not, what you described should be 👍

2019-12-14 23:46 UTC, dwoz commented
@qcpeter This needs to be re-opened against the `master` branch. We are no longer
accepting PRs to `2018.3`. You can link back to this PR to perserver the
discussion. Sorry taking so long to get to this and for any confusion.

2019-12-14 23:46 UTC, closed without merging