[2019.2.1] Porting #52502 to 2019.2.1
saltstack/salt pull request #54535
Opened 2019-09-18 23:32 UTC by garethgreenaway

Porting #52502 to 2019.2.1

2019-09-20 20:26 UTC, garethgreenaway commented
re-run full all

2019-10-11 16:06 UTC, dwoz approved these changes

2019-10-11 16:15 UTC, dwoz requested changes

2019-10-11 16:15 UTC, dwoz commented on salt/states/archive.py
> +                                if x not in ('v', '-v', '--verbose')]
What happens if someone passes `xv`? Should this check be something like:

```
if not x.startswith('-') and 'v' not in x
```

in addition to what it is checking now?

2019-10-11 16:15 UTC, dwoz commented on salt/states/archive.py
> +                        files = results['stdout'].splitlines()
What happens if someone extracts an archive with 100K + files?

2023-12-10 05:23 UTC, dwoz commented
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 05:23 UTC, closed without merging