[2019.2.1] Porting #52424 to 2019.2.1
saltstack/salt pull request #54540
Opened 2019-09-18 23:35 UTC by garethgreenaway

Porting #52424 to 2019.2.1

2019-09-18 23:43 UTC, twangboy approved these changes

2019-10-15 18:46 UTC, dwoz commented
re-run full all

2019-10-15 18:49 UTC, dwoz requested changes
This should get some tests

2019-12-03 20:04 UTC, garethgreenaway commented
Tests available in #55077

2019-12-27 18:22 UTC, garethgreenaway commented
Closing this out in favor of #55077

2019-12-27 18:22 UTC, closed without merging