[2019.2.1] Porting #50150 to 2019.2.1
saltstack/salt pull request #54551
Opened 2019-09-18 23:44 UTC by garethgreenaway

Porting #50150 to 2019.2.1

2019-10-21 16:13 UTC, dwoz requested changes

2019-10-21 16:13 UTC, dwoz commented on salt/states/http.py
> +            if data.get('status', '') == str(status):
Should this be `str(data.get('status', '')) == str(status)`? Assuming so, we should have a test for this case.

2020-01-13 13:16 UTC, max-arnold commented
I believe there is no need to backport this PR, because it was included into https://github.com/saltstack/salt/pull/55145

2023-12-10 05:26 UTC, dwoz commented
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 05:26 UTC, closed without merging