[2019.2.1] Porting #49837 to 2019.2.1
saltstack/salt pull request #54552
Opened 2019-09-18 23:44 UTC by garethgreenaway

Porting #49837 to 2019.2.1

2019-10-22 15:54 UTC, dwoz submitted a review, later dismissed

2019-10-22 15:55 UTC, dwoz commented
re-run full all

2019-11-07 19:15 UTC, dhiltonp submitted a review, later dismissed

2020-04-06 23:13 UTC, DmitryKuzmenko requested changes

2020-04-06 23:13 UTC, DmitryKuzmenko commented on salt/states/file.py
> +        .. versionchanged:: Neon
Sodium?

2020-04-06 23:13 UTC, DmitryKuzmenko commented on salt/states/file.py
> +        .. versionchanged:: Neon
Sodium?

2020-04-25 06:02 UTC, mchugh19 commented
@garethgreenaway are you able to fix up the doc strings? Or should I duplicate the PR to fix it up?

2020-04-26 23:55 UTC, garethgreenaway commented
@mchugh19 Thanks for the ping, the versionchanged strings have been updated.

2020-04-29 22:24 UTC, dwoz approved these changes

2020-04-29 22:25 UTC, merged