[2019.2.1] Porting #52670 to 2019.2.1
saltstack/salt pull request #54572
Opened 2019-09-19 00:00 UTC by garethgreenaway

Porting #52670 to 2019.2.1

2019-10-25 15:55 UTC, dwoz approved these changes

2019-10-28 18:25 UTC, s0undt3ch requested changes

2019-10-28 18:25 UTC, s0undt3ch commented on salt/modules/debian_ip.py
> +        cmd = ['ip', 'link', 'set', '{0}'.format(iface), 'down']
Why do we `.format()` `iface`? is it ever not going to be a string?

2019-10-28 18:25 UTC, s0undt3ch commented on salt/modules/debian_ip.py
> +        cmd = ['ip', 'link', 'set', '{0}'.format(iface), 'up']
Same as above.

2019-11-14 20:45 UTC, DmitryKuzmenko approved these changes

2019-11-14 20:46 UTC, DmitryKuzmenko commented on salt/modules/debian_ip.py
> +        cmd = ['ip', 'link', 'set', '{0}'.format(iface), 'up']
Fixed

2019-11-14 20:46 UTC, DmitryKuzmenko commented
@s0undt3ch I've updated the code, could you please approve this?

2019-11-14 20:54 UTC, s0undt3ch approved these changes

2019-12-04 09:40 UTC, merged