[2019.2.1] Porting #50505 to 2019.2.1
saltstack/salt pull request #54581
Opened 2019-09-19 00:08 UTC by garethgreenaway

Porting #50505 to 2019.2.1

2019-11-14 20:49 UTC, DmitryKuzmenko approved these changes

2019-11-15 01:21 UTC, dwoz requested changes
Looks like some of the test failures are related.

2020-03-27 09:09 UTC, DmitryKuzmenko requested changes

2020-03-27 09:09 UTC, DmitryKuzmenko commented on salt/minion.py
> +                 'enable_job': ('enable_job', (name, persist)),
Missing function here.
`'run_job': ('run_job', (name,)),`

2020-03-27 09:10 UTC, DmitryKuzmenko commented
@garethgreenaway could you please update this PR?

2020-03-31 08:09 UTC, DmitryKuzmenko commented on salt/minion.py
> +                 'enable_job': ('enable_job', (name, persist)),
I've fixed that during resolving merge conflicts.

2020-04-26 04:36 UTC, dwoz approved these changes

2020-04-26 04:36 UTC, merged