[2019.2.1] Porting #51344 to 2019.2.1
saltstack/salt pull request #54595
Opened 2019-09-19 00:18 UTC by garethgreenaway

Porting #51344 to 2019.2.1

2019-11-22 19:12 UTC, Ch3LL requested changes

2019-11-22 19:12 UTC, Ch3LL commented on doc/man/salt.7
> +    \- hashing-algorithm: layer2
this file is generated when we build the man pages for each release, so we should never directly edit this file

2019-11-22 19:16 UTC, Ch3LL commented on doc/man/salt.7
> +    \- hashing-algorithm: layer2
ping @waynew looks like you made this change originally, mind taking a look here? Or i can make the change

2020-01-02 17:49 UTC, waynew commented
@dwoz doc-only change here

2020-01-02 21:37 UTC, merged