[2019.2.1] Porting #51701 to 2019.2.1
saltstack/salt pull request #54649
Opened 2019-09-19 00:56 UTC by garethgreenaway

Porting #51701 to 2019.2.1

2020-01-09 23:31 UTC, waynew commented on salt/modules/chocolatey.py
> +            continue
No need for implicit continue

2020-01-09 23:35 UTC, waynew requested changes
Definitely needs tests, could use some updates.

2020-01-09 23:35 UTC, waynew commented on salt/modules/chocolatey.py
> +            packages[pkg] = {'installed': installed[pkg]}
I wonder - would this be better as `'available': available.get(pkg)`?

It produces an output like this:
```
local:
    ----------
    hosts:
        ----------
        available:
            None
        installed:
            - 1.1.0
```

Which feels better than:

```
local:
    ----------
    hosts:
        ----------
        installed:
            - 1.1.0
```

2020-04-23 22:21 UTC, closed without merging

2020-04-23 22:27 UTC, garethgreenaway commented
Replaced with https://github.com/saltstack/salt/pull/56870