[2019.2.1] Porting #49507 to 2019.2.1
saltstack/salt pull request #54644
Opened 2019-09-19 00:52 UTC by garethgreenaway

Porting #49507 to 2019.2.1

2019-11-06 21:03 UTC, waynew requested changes

2019-11-06 21:03 UTC, waynew commented on salt/modules/artifactory.py
> +        artifact_sum = salt.utils.stringutils.to_str(artifact_sum)
I'm not convinced that this is the correct fix for this problem.

The issue appears to be that `__download` is producing (sometimes) binary data as the result of a `url.read()` command. I'm pretty sure that we should be checking the `Content-type` header for `text/*`, which we can do with 
```
info = url.info()
# python3
main_type = info.get_content_maintype()
# python2
main_type = info.maintype

if main_type == 'text':
    content = salt.utils.stringutils.to_str(content)
```

Granted, this is the only place that's using this `__download`, but that should correctly fix it for all possible uses.

Note that this `__download` code is *also* found in `salt/modules/nexus.py` - so it's possible that it's got the same sort of failure. Not sure if we should extract `__download`. Looks like the original code was from back in 2014 so maybe we should just refactor these usages to use `salt.utils.http.query`?

2019-11-06 21:08 UTC, waynew commented on salt/modules/artifactory.py
> +        artifact_sum = salt.utils.stringutils.to_str(artifact_sum)
https://stackoverflow.com/a/36882727/344286 for more info about python2/3

2020-03-03 05:27 UTC, acornett commented
@waynew , I've taken a swing at resolving this issue (which is impacting me) by using the built in http util, PR#56291

2020-03-27 17:45 UTC, waynew commented
I'm going to go ahead and close this in favor of #56291 - feel free to reopen or ping me if anyone disagrees.

2020-03-27 17:45 UTC, closed without merging