[2019.2.1] Porting #49133 to 2019.2.1
saltstack/salt pull request #54654
Opened 2019-09-19 01:00 UTC by garethgreenaway

Porting #49133 to 2019.2.1

2020-01-15 05:39 UTC, garethgreenaway commented
Needs changes from #55866 to allow PY3 tests to pass.

2020-01-15 07:45 UTC, s0undt3ch requested changes

2020-01-15 07:45 UTC, s0undt3ch commented on tests/unit/returners/test_postgres_local_cache.py
> +            self.assertNotEqual(return_val, None)
Please use `assertIsNotNone` instead

2021-04-01 15:25 UTC, twangboy approved these changes, later dismissed

2021-04-01 17:15 UTC, s0undt3ch reviewed
Do you want to update to the comments I made?
The first change is an unused, and then overridden variable.
The second is an unnecessary call to `to_str`

2021-04-01 17:15 UTC, s0undt3ch commented on tests/unit/returners/test_postgres_local_cache.py
> +            search_string = salt.utils.stringutils.to_str("return")
```suggestion
            search_string = "return"
```
?

2021-04-01 17:15 UTC, s0undt3ch commented on tests/unit/returners/test_postgres_local_cache.py
> +
```suggestion
```

2021-04-01 17:22 UTC, garethgreenaway reviewed
Committing requested changes.

2021-04-01 17:49 UTC, s0undt3ch approved these changes, later dismissed

2021-04-02 10:20 UTC, merged