[2019.2.1] Porting #51141 to 2019.2.1
saltstack/salt pull request #54663
Opened 2019-09-19 01:06 UTC by garethgreenaway

Porting #51141 to 2019.2.1

2019-11-06 18:31 UTC, waynew approved these changes

2019-12-15 17:38 UTC, Akm0d requested changes

2019-12-15 17:38 UTC, Akm0d commented on salt/modules/lxd.py
> +.. note::
Should there be two colon's here?  I don't see that syntax anywhere else

2019-12-16 23:46 UTC, Akm0d approved these changes

2019-12-16 23:48 UTC, dwoz approved these changes

2019-12-16 23:48 UTC, merged