[2019.2.1] Porting #51840 to 2019.2.1
saltstack/salt pull request #54679
Opened 2019-09-19 01:18 UTC by garethgreenaway

Porting #51840 to 2019.2.1

2019-12-23 17:39 UTC, dwoz commented
@team-core the test failures, docs, and lint all look legit

2019-12-23 18:19 UTC, twangboy submitted a review, later dismissed

2020-04-13 07:44 UTC, dwoz commented
Black needs to be run on this.

2022-10-03 20:03 UTC, Ch3LL requested changes
this needs a changelog

2022-10-03 20:03 UTC, Ch3LL commented on salt/roster/sshknownhosts.py
> +"""
versionadded for 3006

2022-10-04 18:48 UTC, Ch3LL submitted a review, later dismissed

2022-10-05 12:49 UTC, Ch3LL approved these changes

2022-10-05 16:11 UTC, merged