[2019.2.1] Porting #49148 to 2019.2.1
saltstack/salt pull request #54682
Opened 2019-09-19 01:27 UTC by garethgreenaway

Porting #49148 to 2019.2.1

2020-01-04 23:50 UTC, dwoz commented on salt/grains/core.py
> +                    log.debug('=== processor %s %s ===', key, val)
I removed the log message while fixing a merge conflict

2020-01-05 00:22 UTC, s0undt3ch submitted a review, later dismissed

2022-09-27 18:42 UTC, Ch3LL requested changes
this port is missing this line: https://github.com/saltstack/salt/pull/49148/files#diff-1d38435cf2b529355dec413e02b3fdc26f1af1d89f119891c68c4e9cf5630062R143

is this on purpose?

also this will require a changelog

2022-09-27 20:21 UTC, garethgreenaway commented
@Ch3LL Good catch.  Looks like something that just got missed in the origin PR.

2022-09-27 20:22 UTC, Ch3LL commented
thanks, looks like this will also need a changelog

2022-09-27 20:34 UTC, garethgreenaway commented
@Ch3LL done.

2022-09-27 20:47 UTC, Ch3LL approved these changes

2022-09-28 13:37 UTC, merged