vmware.py VM creation with Datastore Cluster
saltstack/salt pull request #54697
Opened 2019-09-20 02:04 UTC by preussal

VM creation with Datastore Cluster
When cloning a template that resides in a datastore cluster, that already works.
With the customization, you can create a new VM without a template on a Datasore cluster.

What does this PR do?
VM creation with Datastore Cluster

What issues does this PR fix or reference?
Cannot create a new VM on Datasore Cluster, only on Datastore
When cloning a template that resides in a datastore cluster, that already works.

Previous Behavior
Cannot create a new VM on Datasore Cluster, only on Datastore

New Behavior
With the customization, you can create a new VM without a template on a Datasore Cluster.

Tests written?
No
Test only on my enviorment

Commits signed with GPG?
No

Please review Salt's Contributing Guide for best practices.

See GitHub's page on GPG signing for more information about signing commits with GPG.

2019-09-20 20:01 UTC, xeacott commented
Thanks for getting this together! I see that the lint tests are failing, those will need to get fixed and I'll also leave some code comments. And finally, since this PR introduces new logic I'm going to ask if you could put some tests together for this, too. We actually have a lot of examples in [here](https://github.com/saltstack/salt/blob/develop/tests/unit/modules/test_vsphere.py).

2019-09-20 20:11 UTC, xeacott requested changes

2019-09-20 20:11 UTC, xeacott commented on salt/cloud/clouds/vmware.py
> +                     log.trace(
Is this appropriate to add a log.trace here? Versus a log.info or log.msg?

2019-12-14 23:40 UTC, dwoz commented
@preussal We are no longer accepting PRs to the `develop` branch. This needs to be re-opened against the `master` branch. You can link to this PR from the new one to preserve any disscussion history. Sorry for the confusion.

2020-05-26 20:34 UTC, sagetherage commented
closing as abandoned

2020-05-26 20:34 UTC, closed without merging