Update dpkg_lowpkg to handle deb files that have spaces in `dpkg -I` output
saltstack/salt pull request #54740
Opened 2019-09-25 14:14 UTC by lomeroe

### What does this PR do?
use re.match to find Name/Architecture/Version instead of startswith, some dpkg -I output has spaces between the description and colon

### What issues does this PR fix or reference?
#54739 

### Previous Behavior
Deb packages that returned output of `dpkg -I` with spaces between the row name and the ':' would not install

for example
```
# dpkg -I /var/cache/salt/minion/files/base/apps/mcafee/agent/files/MFEdx-ma-5.0.0-568.x86_64.deb
 new Debian package, version 2.0.
 size 1333890 bytes: control archive=1142 bytes.
     260 bytes,     9 lines      control
    1788 bytes,    61 lines   *  postinst             #!/bin/sh
     342 bytes,    18 lines   *  postrm               #!/bin/sh
     401 bytes,    20 lines   *  preinst              #!/bin/sh
     588 bytes,    28 lines   *  prerm                #!/bin/sh
 Package        : MFEdx
 Version        : 5.0.0
 Maintainer     : McAfee, Inc.
 Description    : McAfee Data Exchange Layer
 Release        : 568
 Architecture   : all
 Section        : Network/Agent
 Summary        : McAfee Data Exchange Layer
 Pre-Depends    : MFErt
```

### New Behavior
Packages with this type of output are able to be installed

### Tests written?
Yes

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-10-02 20:39 UTC, xeacott commented
re-run full all

2019-10-04 17:20 UTC, xeacott commented
Pesky Windows, its failing like so...
```
[2019-10-03T03:37:40.571Z]         --------  Tests with Errors  ------------------------------------------------------------------------------------------
[2019-10-03T03:37:40.571Z]           -> setUpClass (unit.modules.test_zcbuildout.BuildoutOnlineTestCase)  ................................................
[2019-10-03T03:37:40.571Z]        Traceback (most recent call last):
[2019-10-03T03:37:40.571Z]          File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_zcbuildout.py", line 330, in setUpClass
[2019-10-03T03:37:40.571Z]            super(BuildoutOnlineTestCase, cls).setUpClass()
[2019-10-03T03:37:40.571Z]          File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_zcbuildout.py", line 98, in setUpClass
[2019-10-03T03:37:40.571Z]            'setuptools',
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 266, in check_call
[2019-10-03T03:37:40.571Z]            retcode = call(*popenargs, **kwargs)
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 247, in call
[2019-10-03T03:37:40.571Z]            with Popen(*popenargs, **kwargs) as p:
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 676, in __init__
[2019-10-03T03:37:40.571Z]            restore_signals, start_new_session)
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 957, in _execute_child
[2019-10-03T03:37:40.571Z]            startupinfo)
[2019-10-03T03:37:40.571Z]        FileNotFoundError: [WinError 2] The system cannot find the file specified
[2019-10-03T03:37:40.571Z]           .....................................................................................................................
[2019-10-03T03:37:40.571Z]           -> setUpClass (unit.states.test_zcbuildout.BuildoutTestCase)  .......................................................
[2019-10-03T03:37:40.571Z]        Traceback (most recent call last):
[2019-10-03T03:37:40.571Z]          File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\unit\modules\test_zcbuildout.py", line 98, in setUpClass
[2019-10-03T03:37:40.571Z]            'setuptools',
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 266, in check_call
[2019-10-03T03:37:40.571Z]            retcode = call(*popenargs, **kwargs)
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 247, in call
[2019-10-03T03:37:40.571Z]            with Popen(*popenargs, **kwargs) as p:
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 676, in __init__
[2019-10-03T03:37:40.571Z]            restore_signals, start_new_session)
[2019-10-03T03:37:40.571Z]          File "C:\Python35\Lib\subprocess.py", line 957, in _execute_child
[2019-10-03T03:37:40.571Z]            startupinfo)
[2019-10-03T03:37:40.571Z]        FileNotFoundError: [WinError 2] The system cannot find the file specified
[2019-10-03T03:37:40.571Z]           .....................................................................................................................
[2019-10-03T03:37:40.571Z]         -----------------------------------------------------------------------------------------------------------------------
[2019-10-03T03:37:40.571Z]        ========================================================================================================================
[2019-10-03T03:37:40.571Z]        FAILED (total=8532, skipped=1126, passed=7404, failures=0, errors=2)
```

I am unsure if this is specific to this build or just the branch 2018.3

2020-05-21 20:27 UTC, Akm0d commented
@lomeroe it looks like there are a couple linter errors that need fixed before this can be merged :)

2020-05-29 22:05 UTC, s0undt3ch requested changes

2020-05-29 22:05 UTC, s0undt3ch commented on tests/unit/modules/test_dpkg_lowpkg.py
>  # Import Salt Testing Libs
Could you please remove the above 2 comment lines?

2020-05-29 22:05 UTC, s0undt3ch commented on tests/unit/modules/test_dpkg_lowpkg.py
> +from tests.support.mock import NO_MOCK, NO_MOCK_REASON, MagicMock, patch
Please leave this import as it was before, ie, remove the `NO_MOCK*` imports

2020-06-01 21:22 UTC, xeacott approved these changes

2020-06-01 23:27 UTC, Akm0d approved these changes

2020-06-10 18:52 UTC, s0undt3ch approved these changes

2020-07-13 22:38 UTC, merged