Allow API key to be specified in zenoss config
saltstack/salt pull request #54842
Opened 2019-10-01 17:58 UTC by rossengeorgiev

#52236 # What does this PR do?
API Key is used as method of authentication with Zenoss Cloud

Details can be found at https://help.zenoss.com/dev/collection-zone-and-resource-manager-apis/using-curl

### Previous Behavior
Cannot be used with Zenoss Cloud

### New Behavior
Can be used with Zenoss Cloud

### Tests written?
No

### Commits signed with GPG?
Yes

2019-11-19 19:58 UTC, bryceml commented
Please re-open this to master, see https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0014-dev-overhaul.md

2019-11-19 21:16 UTC, rossengeorgiev commented
Hi @bryceml, I've updated the PR to point at `master`

2020-06-12 17:22 UTC, garethgreenaway submitted a review, later dismissed

2022-11-09 20:59 UTC, Ch3LL commented
ping @rossengeorgiev would you mind resolving the merge conflict?'

A changelog file will also need to be added.

2022-11-11 15:15 UTC, rossengeorgiev commented
@Ch3LL refactored the change set

2022-11-22 20:30 UTC, Ch3LL requested changes
Sorry I missed this in my original request but this will require test coverage and a changelog

2023-01-10 20:50 UTC, Ch3LL commented
@rossengeorgiev did you see my review?

2023-12-10 05:30 UTC, dwoz commented
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 05:30 UTC, closed without merging