Master thread safe loader
saltstack/salt pull request #54878
Opened 2019-10-03 23:57 UTC by Akm0d

### What does this PR do?
Merge PR from Neon 51e334caf51a508ce9d850ddfe1ca21280a2fdff

2019-10-05 01:29 UTC, max-arnold commented
@Akm0d FYI: the backported PR also needs #51499 to fix the infinite recursion bug.

2019-10-11 03:55 UTC, Akm0d commented
I'm getting this error on all the tests now: ```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/output/test_output.py", line 97, in test_output_yaml_namespaced_dict_wrapper
    assert isinstance(loaded_yaml, dict)
AssertionError```

2019-10-11 04:13 UTC, Akm0d commented
It looks like the PR fixing https://github.com/saltstack/salt/issues/49269 was merged into 2017 and 2018 but not into 2019.2.1

2019-10-15 22:23 UTC, Akm0d commented
The threadsafe loader has trouble representing undefined data types in the yamldumper (similar to https://github.com/saltstack/salt/issues/43694).

2019-10-16 16:58 UTC, Akm0d commented
re-run full opensuse15

2019-10-17 00:59 UTC, Akm0d commented
re-run full centos7

2019-10-17 18:16 UTC, garethgreenaway submitted a review, later dismissed

2019-10-19 18:52 UTC, s0undt3ch approved these changes
There's more than the thread proxy stuff right?
Separate changes?

2019-10-20 18:36 UTC, Akm0d commented
re-run full macosxmojave

2019-10-22 05:42 UTC, Akm0d commented
re-run full all

2019-10-23 06:05 UTC, Akm0d commented
re-run full macosxmojave

2019-10-23 06:06 UTC, Akm0d commented
re-run full debian10

2019-10-23 06:06 UTC, Akm0d commented
re-run full opensuse15

2019-10-23 06:06 UTC, Akm0d commented
re-run full windows2019

2019-10-23 15:15 UTC, Akm0d commented
re-run full macosxmojave

2019-10-23 15:16 UTC, Akm0d commented
re-run full windows2019

2019-10-31 22:30 UTC, Akm0d commented
> There's more than the thread proxy stuff right?
> Separate changes?

This is all the threadsafe loader + other changes required to make tests pass that failed with the threadsafe loader

2019-11-02 00:26 UTC, Akm0d commented
re-run full macosxmojave

2019-11-04 22:10 UTC, Akm0d commented
On this PR build the `Py3/macosxmojave` build hangs right after `test_unsupported_kwarg`. On a PR where the same build is passing, the subsequent test gives the following log:
```[2019-10-31T22:51:04.911Z]          test_unsupported_kwarg (integration.shell.test_arguments.ArgumentTestCase) ... OK (0.283s)
[2019-10-31T22:51:56.696Z]          test_pam_auth_invalid_user (integration.shell.test_auth.AuthTest) ... 16:51:55,145 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/localaccounts', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:51:56.696Z]        16:51:55,146 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:51:56.696Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:51:56.696Z]        16:51:55,146 [ERROR   ] retcode: 54
[2019-10-31T22:51:56.696Z]        16:51:55,178 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/everyone', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:51:56.696Z]        16:51:55,179 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:51:56.696Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:51:56.696Z]        16:51:55,179 [ERROR   ] retcode: 54
[2019-10-31T22:51:56.696Z]        16:51:55,210 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/_lpoperator', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:51:56.696Z]        16:51:55,211 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:51:56.696Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:51:56.696Z]        16:51:55,211 [ERROR   ] retcode: 54
[2019-10-31T22:51:56.696Z]        16:51:55,243 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/com.apple.sharepoint.group.1', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:51:56.696Z]        16:51:55,243 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:51:56.696Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:51:56.696Z]        16:51:55,244 [ERROR   ] retcode: 54
[2019-10-31T22:52:02.974Z]        16:52:01,936 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/everyone', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:52:02.974Z]        16:52:01,936 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:52:02.974Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:52:02.974Z]        16:52:01,937 [ERROR   ] retcode: 54
[2019-10-31T22:52:02.974Z]        16:52:01,971 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/com.apple.sharepoint.group.1', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:52:02.974Z]        16:52:01,971 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:52:02.974Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:52:02.974Z]        16:52:01,971 [ERROR   ] retcode: 54
[2019-10-31T22:52:02.974Z]        16:52:02,007 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/_lpoperator', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:52:02.974Z]        16:52:02,007 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:52:02.974Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:52:02.974Z]        16:52:02,008 [ERROR   ] retcode: 54
[2019-10-31T22:52:02.974Z]        16:52:02,077 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/localaccounts', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:52:02.974Z]        16:52:02,078 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:52:02.974Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:52:02.974Z]        16:52:02,078 [ERROR   ] retcode: 54
[2019-10-31T22:52:09.109Z]        OK (64.618s)
[2019-10-31T22:53:11.101Z]          test_pam_auth_valid_group (integration.shell.test_auth.AuthTest) ... 16:53:03,447 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/localaccounts', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:53:11.101Z]        16:53:03,447 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.101Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.101Z]        16:53:03,447 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.101Z]        16:53:03,479 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/everyone', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:03,480 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:03,480 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:03,512 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/_lpoperator', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:03,512 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:03,513 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:03,549 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/com.apple.sharepoint.group.1', 'GroupMembership', 'saltdev']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:03,549 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:03,550 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:10,109 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/_lpoperator', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:10,110 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:10,110 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:10,145 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/localaccounts', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:10,145 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:10,146 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:10,181 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/com.apple.sharepoint.group.1', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:10,181 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:10,181 [ERROR   ] retcode: 54
[2019-10-31T22:53:11.102Z]        16:53:10,248 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/everyone', 'GroupMembership', 'saltadm']' failed with return code: 54
[2019-10-31T22:53:11.102Z]        16:53:10,249 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
[2019-10-31T22:53:11.102Z]        <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
[2019-10-31T22:53:11.102Z]        16:53:10,249 [ERROR   ] retcode: 54
[2019-10-31T22:53:17.380Z]       [...]

2019-11-04 23:18 UTC, Akm0d commented
Verified, skipping `test_pam_auth_invalid_user` causes py3 mac tests to pass

2019-11-05 01:41 UTC, Akm0d commented
This issue is a problem again https://github.com/saltstack/salt-jenkins/issues/504

2019-11-05 21:50 UTC, Akm0d commented
Found it! This is the line of code causing all the trouble on mac:
`self.run_call('group.info {0}'.format(self.group))`

2019-11-07 01:03 UTC, Akm0d commented
The last PR did it, there might be a problem with the macosxmojave build or with the version of the grp module, but for now I think everything is working :)

2019-11-07 06:29 UTC, Akm0d commented
re-run full centos7

2019-11-07 06:29 UTC, Akm0d commented
re-run full opensuse15

2019-11-07 08:05 UTC, s0undt3ch requested changes

2019-11-07 08:05 UTC, s0undt3ch commented on salt/log/handlers/fluent_mod.py
> +        import salt.utils.msgpack
And do we need this try/except? Doesn't salt.utils.msgpack handle this now?

2019-11-07 20:51 UTC, s0undt3ch submitted a review, later dismissed

2019-11-07 20:55 UTC, Akm0d commented
re-run full debian10

2019-11-07 22:41 UTC, Akm0d commented
re-run full m2crypto

2019-11-08 04:45 UTC, Akm0d commented
re-run full centos7

2019-11-08 04:46 UTC, Akm0d commented
re-run full amazon2

2019-11-18 20:42 UTC, Akm0d commented
Since this is such a large PR we'll break it up into smaller PRs to get it into salt.  The msgpack stuff will come out first.

2019-12-17 21:46 UTC, Akm0d commented
This is dependent on https://github.com/saltstack/salt/pull/55354, once that get's merged this one can go in

2019-12-20 22:05 UTC, Akm0d commented
```
 test_pam_auth_valid_group (integration.shell.test_auth.AuthTest)
14:44:53         [CPU:0.0%|MEM:40.5%]  ... 14:44:51,449 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:44:53           *salt.utils.args.get_function_argspec(original_function)
14:44:53         
14:45:02         14:44:59,692 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:45:02           *salt.utils.args.get_function_argspec(original_function)
14:45:02         
14:45:11         14:45:10,718 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:45:11           *salt.utils.args.get_function_argspec(original_function)
14:45:11         
14:45:13         14:45:11,639 [WARNING ] /private/tmp/kitchen/testing/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
14:45:13           from collections import Iterable, Mapping, namedtuple
14:45:13         
14:45:13         14:45:12,603 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:45:13           *salt.utils.args.get_function_argspec(original_function)
14:45:13         
14:53:29         14:53:21,786 [tests.support.case                                          :271 ][ERROR   ] run_script timed out after 500 seconds (process killed)
14:53:29         14:53:21,786 [tests.support.case                                          :285 ][ERROR   ] run_script results for: salt-call  --config-dir /private/tmp/salt-tests-tmpdir/config group.info saltops
14:53:29         return code: None
14:53:29         stdout:
14:53:29         None
14:53:29         
14:53:29         stderr:
14:53:29         None
14:53:32         14:53:30,395 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:53:32           *salt.utils.args.get_function_argspec(original_function)
14:53:32         
14:53:32         14:53:31,219 [WARNING ] /private/tmp/kitchen/testing/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
14:53:32           from collections import Iterable, Mapping, namedtuple
14:53:32         
14:53:32         14:53:32,147 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
14:53:32           *salt.utils.args.get_function_argspec(original_function)
14:53:32         
15:01:51         15:01:41,829 [tests.support.case                                          :271 ][ERROR   ] run_script timed out after 500 seconds (process killed)
15:01:51         15:01:41,829 [tests.support.case                                          :285 ][ERROR   ] run_script results for: salt-call  --config-dir /private/tmp/salt-tests-tmpdir/config group.add saltops
15:01:51         return code: None
15:01:51         stdout:
15:01:51         None
15:01:51         
15:01:51         stderr:
15:01:51         None
15:01:51         15:01:50,797 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
15:01:51           *salt.utils.args.get_function_argspec(original_function)
15:01:51         
15:01:51         15:01:50,833 [WARNING ] /private/tmp/kitchen/testing/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
15:01:51           from collections import Iterable, Mapping, namedtuple
15:01:51         
15:01:51         15:01:50,875 [ERROR   ] Command '['dscl', 'localhost', '-append', '/Local/Default/Groups/saltops', 'GroupMembership', 'saltadm']' failed with return code: 185
15:01:51         15:01:50,876 [ERROR   ] stdout: append: Invalid Path
15:01:51         15:01:50,876 [ERROR   ] stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)
15:01:51         15:01:50,876 [ERROR   ] retcode: 185
15:02:16         15:02:13,866 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
15:02:16           *salt.utils.args.get_function_argspec(original_function)
15:02:16         
15:02:16         15:02:13,900 [WARNING ] /private/tmp/kitchen/testing/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
15:02:16           from collections import Iterable, Mapping, namedtuple
15:02:16         
15:02:16         15:02:13,957 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/_lpoperator', 'GroupMembership', 'saltadm']' failed with return code: 54
15:02:16         15:02:13,958 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
15:02:16         <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
15:02:16         15:02:13,958 [ERROR   ] retcode: 54
15:02:16         15:02:13,992 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/everyone', 'GroupMembership', 'saltadm']' failed with return code: 54
15:02:16         15:02:13,993 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
15:02:16         <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
15:02:16         15:02:13,993 [ERROR   ] retcode: 54
15:02:16         15:02:14,028 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/com.apple.sharepoint.group.1', 'GroupMembership', 'saltadm']' failed with return code: 54
15:02:16         15:02:14,029 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
15:02:16         <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
15:02:16         15:02:14,029 [ERROR   ] retcode: 54
15:02:16         15:02:14,066 [ERROR   ] Command '['dscl', 'localhost', '-delete', '/Local/Default/Groups/localaccounts', 'GroupMembership', 'saltadm']' failed with return code: 54
15:02:16         15:02:14,066 [ERROR   ] stderr: <main> attribute status: eDSAttributeNotFound
15:02:16         <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)
15:02:16         15:02:14,067 [ERROR   ] retcode: 54
15:02:16         FAIL (1051.732s)
15:02:16           test_pam_auth_valid_user (integration.shell.test_auth.AuthTest)
15:02:25         [CPU:0.0%|MEM:42.2%]  ... 15:02:23,907 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
15:02:25           *salt.utils.args.get_function_argspec(original_function)
15:02:25         
15:02:35         15:02:33,892 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
15:02:35           *salt.utils.args.get_function_argspec(original_function)
15:02:35         
15:02:57         15:02:56,976 [WARNING ] /private/tmp/kitchen/testing/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprec [...]

2019-12-23 03:37 UTC, Akm0d commented
re-run full windows2019

2020-01-03 19:42 UTC, Akm0d commented
re-run full windows2019

2020-01-03 19:43 UTC, Akm0d commented
re-run full ubuntu1604

2020-01-07 22:44 UTC, Akm0d commented
Needs testcase based on https://github.com/saltstack/salt/issues/23373

2020-01-09 20:32 UTC, Akm0d commented
re-run full macosxmojave

2020-01-10 00:33 UTC, Akm0d commented
The command that has issue on mac is `salt -a pam '*' test.ping --username saltadm`.  The error message "Authentication error occurred" is given when an incorrect password is used

2020-01-10 21:17 UTC, Akm0d commented
```
[ERROR   ] Command '['dscl', 'localhost', '-append', '/Local/Default/Groups/saltops', 'GroupMembership', 'saltadm']' failed with return code: 185", '13:50:55,820 
[ERROR   ] stdout: append: Invalid Path', '13:50:55,820 
[ERROR   ] stderr: <dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)', '13:50:55,820 
[ERROR   ] retcode: 185']
```

2020-01-15 06:38 UTC, Akm0d commented
re-run full amazon2

2020-01-16 15:08 UTC, dwoz commented
re-run full all

2020-01-17 18:06 UTC, Akm0d commented
The centos7 test failure is a serious issue with this PR:
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/scheduler/test_skip.py", line 301, in test_run_seconds_skip
    self.schedule.eval(now=run_time)
  File "/tmp/kitchen/testing/salt/utils/schedule.py", line 1593, in eval
    now)
  File "/tmp/kitchen/testing/salt/utils/schedule.py", line 224, in _check_max_running
    current_jobs = salt.utils.minion.running(self.opts)
  File "/tmp/kitchen/testing/salt/utils/minion.py", line 33, in running
    data = _read_proc_file(path, opts)
  File "/tmp/kitchen/testing/salt/utils/minion.py", line 73, in _read_proc_file
    data = serial.loads(buf)
  File "/tmp/kitchen/testing/salt/payload.py", line 140, in loads
    exc,
  File "/tmp/kitchen/testing/salt/ext/six.py", line 725, in raise_from
    raise value
SaltDeserializationError: Could not deserialize msgpack message. See log for more info.
```

2020-04-11 07:38 UTC, dwoz approved these changes

2020-04-11 07:40 UTC, dwoz submitted a review, later dismissed

2020-04-26 04:41 UTC, dwoz commented
@Akm0d I believe this is being addressed in a more comprehensive way for the proxy minion work @garethgreenaway is working on. We should hold off on this to see how that work pans out.

2020-04-27 21:22 UTC, closed without merging