Check the type of the data passed to salt.matcher.confirm_top is a list instead of assuming an implicit false is a "bad data" error.
saltstack/salt pull request #54883
Opened 2019-10-04 02:27 UTC by arizvisa

### What does this PR do?
This checks that the type of the data being passed to salt.matcher.confirm_top is not iterable before complaining that it was passed bad data. This pretty much cleans up a general error message that is emitted when given an empty list instead of actually bad data.

### What issues does this PR fix or reference?
Closes #54882 

### Previous Behavior
If an empty list is declared in the topfile such as for a placeholder, a log of level "ERROR" is made which informs the user that bad data was passed via the topfile. 

### New Behavior
This actually checks if the data is badly formatted (according to the error message that gets emitted) by verifying that the data is a list before complaining.

### Tests written?
Nope. This is just a one-liner that cleans up a misleading log.

2019-11-19 19:58 UTC, bryceml commented
Please re-open this to master, see https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0014-dev-overhaul.md

2019-11-25 02:08 UTC, arizvisa commented
Re-based onto the master branch.

2019-12-05 21:57 UTC, waynew requested changes
@arizvisa thanks for the PR! This would certainly need some tests. I will bring this up in our architecture meeting tomorrow to see if this change is the desired behavior.

2020-01-24 21:33 UTC, waynew commented
Hi @arizvisa,

We discussed this and we like where you're going but after some discussion it looks like this could be improved:

1. This function should never see anything *but* a list, at least according to Tom's recollection. Could you please search the code to verify that? Basically just do `grep -Inr confirm_top .` and see what's using it. According to the discussion, there should only be a list coming into this function.
2. Given (1), lines 21-24 are superfluous or unnecessary.
3. We *are* requiring tests for bug fixes and other changes. It doesn't look like *this* code explicitly has any tests, but it also looks like it would be super simple to add some tests that mock `salt.loader.matchers` that say when `data` is an empty list, it should return the result of calling the appropriate matcher. `tests/unit/matchers/test_confirm_top.py` I believe should be the right name for that function.

If you're up for making those changes, that would be an awesome simplification for Salt 👍 If you need help, I'm `waynew` in #salt on freenode, and also on the community Slack.

Thanks again!
-W

2020-01-24 23:08 UTC, arizvisa commented
Hey @Waynew, I think you're misunderstanding kind-of. I get it though, because the code that is proposed for addition is actually not really the focus of the PR, but rather that `log.error`. I tried to retain the previous logic because the original author put it there for some reason. Essentially the logic logic is claiming that an "empty-list" is "bad data" and logs an error. Technically an empty list isn't bad data and should just result in nothing happening.

(The following points correspond directly to your points numerically)
1. I totally agree that this function should not see anything but a list. That the explicit testing of whether data is False in order to log an error is not intending to fix an issue with the type itself, but is essentially improving a guard that the original developer wrote.
2. You're totally right that those lines are superfluous and unnecessary. However, I just didn't think it was right to remove a guard that the original developer included. Nonetheless, It'd be better to just remove all of this as really it's just there to mask an exception, hide a backtrace, and serves no other purpose. 
3. Again, this PR isn't for validating the type that is being passed. It's for masking away a log made by the original author of this code..

Without this patch, if you have a topfile that reads like:
```
base:
    '*':
        - blah1
        - blah2
    # type in your windows-specific states here
    'minion-windows-*':
        []
    'minion-linux-*':
        - blah1
...
```

Everytime you apply a state, you'll get a master log that says:
```
2020-01-23 01:25:17,679 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][48] Received bad data when setting the match from the top file
2020-01-23 01:25:18,546 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][47] Received bad data when setting the match from the top file
2020-01-23 01:28:16,874 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][52] Received bad data when setting the match from the top file
2020-01-23 01:28:17,366 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][47] Received bad data when setting the match from the top file
2020-01-24 03:09:11,801 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][48] Received bad data when setting the match from the top file
2020-01-24 05:06:57,773 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][47] Received bad data when setting the match from the top file
2020-01-24 22:34:52,594 [/usr/lib/python3.7/site-packages/salt/matchers/confirm_top.py:22  ][ERROR   ][47] Received bad data when setting the match from the top file
```

I was assuming that as the original author treats the `data` parameter as a sequence later in the function, they were attempting to guard against a bunk type ("bad data") being passed to hide a potentially more "violent" exception containing a stacktrace, or something similar. The author might've introduced this guard as they assume it's a particular type when it's used.

But really, if one can guarantee that only a list is passed to `confirm_top` throughout the lifetime of `confirm_top`, then we can really just remove all of those lines that the original author wrote. Its just that an empty list is not necessarily badly formed data, but rather just "no" data.

I'm not sure what your irc schedule is, but I can start idling on freenode so it'll be easier to explain these things in the future.

2020-01-30 00:43 UTC, waynew commented
> I tried to retain the previous logic because the original author put it there for some reason.

Right.

Talking to Tom & the rest of the core team, whatever the original motivation was, the existing code *is not currently valid*, and should be removed.

So while this (current) change is good, we can make it better, and we should 😃

2020-01-30 07:45 UTC, arizvisa commented
Ok. Just to confirm 100%, I can totally remove that whole test?

2020-03-19 22:39 UTC, waynew commented
@arizvisa Sorry for the long delay - yes that understanding is correct - that whole `if` statement should be removed.

Though we *do* still require tests ([see #3](https://github.com/saltstack/salt/pull/54883#issuecomment-578310479))

2020-03-24 21:01 UTC, arizvisa commented
(force pushing due to rebase)

2020-03-24 21:08 UTC, arizvisa commented
@waynew, ok. if these tests complete then this PR should be good to go.

2020-05-23 00:12 UTC, arizvisa commented
Force-pushed due to rebase.

2020-05-23 04:25 UTC, arizvisa commented
ci/py3/archIts erroring out is not related to this code. please do not tag as has-failing-test.

```
Error Message

0 != 1 : The file: /tmp/kitchen/testing/salt/runners/manage.py has an incorrect spelling for the release name in the warn_utils call:         salt.utils.versions.warn_until(             "3001",. Expecting one of these release names: {'Hydrogen': (2014, 1), 'Helium': (2014, 7), 'Lithium': (2015, 5), 'Beryllium': (2015, 8), 'Boron': (2016, 3), 'Carbon': (2016, 11), 'Nitrogen': (2017, 7), 'Oxygen': (2018, 3), 'Fluorine': (2019, 2), 'Neon': (3000,), 'Sodium': (3001,), 'Magnesium': (9223372036854775710, 0), 'Aluminium': (9223372036854775711, 0), 'Silicon': (9223372036854775712, 0), 'Phosphorus': (9223372036854775713, 0)}
```

2020-05-23 20:55 UTC, arizvisa commented
The other error that is happening is also not related to this PR
```
Error Message

'sudo_ec2amaz-8l5hpic\\administrator' != 'ec2amaz-8l5hpic\\administrator' - sudo_ec2amaz-8l5hpic\administrator ? ----- + ec2amaz-8l5hpic\administrator 

Stacktrace

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_cmdmod.py", line 544, in test_cmd_run_whoami
    self.assertEqual(user.lower(), cmd.lower())
AssertionError: 'sudo_ec2amaz-8l5hpic\\administrator' != 'ec2amaz-8l5hpic\\administrator'
- sudo_ec2amaz-8l5hpic\administrator
? -----
+ ec2amaz-8l5hpic\administrator
```

2020-05-27 01:14 UTC, waynew commented
@arizvisa I'm pretty sure both of those issues have been fixed on master, would you mind merging or rebasing again?

2020-05-27 04:26 UTC, arizvisa commented
Force-pushed due to re-base.

2020-05-27 04:27 UTC, arizvisa commented
Has it been fixed in master? Nobody seems to have written a unit test for it??

2020-05-27 04:27 UTC, arizvisa commented
Oh, nvm. You're referring to the CI testing issues. Gotcha.

2020-06-23 17:41 UTC, arizvisa commented
force-pushed due to rebase.

2020-06-23 18:11 UTC, arizvisa commented
Ok. Just waiting for these tests to pass and then I'll @ you, waynew.

2020-06-23 20:06 UTC, arizvisa commented
@waynew, all the lint tests and the regular tests (with the new one) seem to pass now. So this is ready to be merged to squash that error message that minions include in their log.

2020-06-24 14:29 UTC, waynew approved these changes

2020-06-24 14:31 UTC, waynew requested changes
Dang it - I hit the approve button too fast. I've got to get better at that.

Can you add a [changelog](https://docs.saltstack.com/en/latest/topics/development/changelog.html) file here?

2020-06-24 18:43 UTC, arizvisa commented
Okay, added it.

That's really very cool that you guys aren't managing changelog generation manually any more.

2020-07-17 19:06 UTC, waynew submitted a review, later dismissed

2020-09-23 22:53 UTC, sagetherage commented
@arizvisa since this PR has been around the block a few times, I bet it is failing because now we require a [pre-commit hook](https://docs.saltstack.com/en/latest/topics/development/contributing.html#pre-commit), and I think this was introduced in 3001 so very recently.

2020-09-23 23:19 UTC, arizvisa commented
@waynew, okay. what do we do? it's essentially a negative commit that just removes 3 lines.

2020-09-30 22:14 UTC, sagetherage commented
@arizvisa this failing on pre-commit, you will need to run pre-commit locally

2020-09-30 22:44 UTC, sagetherage commented
we are working on a fix for this, but for now if you can run pre-commit locally it will move this along

2020-10-01 13:31 UTC, arizvisa commented
ok. give me a bit to re-create a dev environment for salt and install pre-commit, then.

2020-10-06 22:08 UTC, twangboy approved these changes

2020-10-07 20:38 UTC, merged

2020-10-08 02:50 UTC, arizvisa commented
awesome. thx u, twangboy.