Added Elasticsearch cluster settings get and put methods plus the flu…
saltstack/salt pull request #54917
Opened 2019-10-07 20:53 UTC by Oloremo

### What does this PR do?
Adding `get_settings` and `put_settings` cluster method for Elasticsearch module plus the `flush_synced` method.

### What issues does this PR fix or reference?
#54505

### Previous Behavior
Elasticsearch module doesn't support these methods

### New Behavior
Elasticsearch module does support these methods

### Tests written?

Yes

### Commits signed with GPG?

Yes

2019-11-06 23:07 UTC, dwoz commented
re-run full debian10-py3
re-run full centos7-py2

2019-11-06 23:07 UTC, dwoz approved these changes

2019-11-07 15:34 UTC, Ch3LL requested changes
also would you mind add an entry in the CHANGELOG.md file under `Added` for the neon release. thanks

2019-11-07 15:34 UTC, Ch3LL commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
```suggestion
    .. versionadded:: Neon
```
this will be in neon

2019-11-07 15:34 UTC, Ch3LL commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
```suggestion
    .. versionadded:: Neon
```

2019-11-07 15:34 UTC, Ch3LL commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
```suggestion
    .. versionadded:: Neon
```

2019-11-07 15:41 UTC, Oloremo commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
done

2019-11-07 15:41 UTC, Oloremo commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
done

2019-11-07 15:41 UTC, Oloremo commented on salt/modules/elasticsearch.py
> +    .. versionadded:: Sodium
done

2019-11-07 16:26 UTC, Ch3LL commented
@Oloremo not sure if you saw my comment about adding a note to the changelog. This new feature is great and i think would be great to highlight for the neone release. See above for details

2019-11-07 19:34 UTC, Oloremo commented
@Ch3LL sorry, missed that. Added.

2019-11-07 19:35 UTC, Ch3LL approved these changes

2019-11-08 11:58 UTC, s0undt3ch approved these changes

2019-11-10 00:26 UTC, merged