(Backport 50635) btrfs: add new btrfs state
saltstack/salt pull request #54962
Opened 2019-10-11 14:14 UTC by aplanas

### What does this PR do?

Add a new btrfs state to create and delete subvolumes.

### Tests written?

Yes

(backport #50635, already merged in develop)

2019-12-23 17:48 UTC, dwoz requested changes

2019-12-23 17:48 UTC, dwoz commented on salt/states/btrfs.py
> +# Copyright 2018 SUSE LINUX GmbH, Nuernberg, Germany.
Copyright should be removed. Also, the windows test failures need to be addressed.

2020-04-22 20:26 UTC, Ch3LL commented
looks like there are some merge conflicts here @aplanas

2020-04-23 07:58 UTC, aplanas commented
This is excellent, the code was already merged in a branch that was using this same code. I will close it.

2020-04-23 07:58 UTC, closed without merging