fixed db_remove() if db is still in use.
saltstack/salt pull request #54963
Opened 2019-10-11 14:25 UTC by guettli

### What does this PR do?

fix db_remove() if db is still in use.

### What issues does this PR fix or reference?

 https://github.com/saltstack/salt/issues/42833

2019-10-21 12:21 UTC, guettli commented
Could someone please review this pull request?

2019-11-06 08:26 UTC, DmitryKuzmenko commented
@guettli can we add a test for this?
Also could you please fix lint errors and the existing tests errors?

2019-11-06 08:29 UTC, DmitryKuzmenko requested changes

2019-11-06 08:29 UTC, DmitryKuzmenko commented on salt/modules/postgres.py
> +        if  ret['retcode'] != 0:
Double spaces before `ret`.

2019-11-06 08:29 UTC, DmitryKuzmenko commented on salt/modules/postgres.py
> -
PEP8 requires 2 blank lines here.

2019-11-06 14:54 UTC, guettli commented
I have no clue how to test this. If you could please provide some guidance. A link to an existing test might be enough.

2019-11-14 00:44 UTC, DmitryKuzmenko commented
@guettli sorry for delay.
I think it's enough to:
1. Fix the existing test unit test `unit.modules.test_postgres.PostgresTestCase.test_db_remove`.
2. Add one more test very similar to `unit.modules.test_postgres.PostgresTestCase.test_db_remove` but checking the "error" case.

2019-11-15 11:42 UTC, guettli commented
Do you mean first number one, then number two. Or do you mean do number one OR number two?

2019-11-15 11:49 UTC, guettli commented
Sorry, I am busy. I think this is an internship tasks. Saltstack is company. Don't you have a some students for this?

2020-03-27 11:51 UTC, DmitryKuzmenko approved these changes

2020-03-27 11:54 UTC, DmitryKuzmenko commented
re-run full amazon2-py2
re-run full macosxmojave-py2
re-run full centos7-py3-proxy

2020-03-31 08:16 UTC, DmitryKuzmenko commented
re-run full macosxmojave-py2

2020-03-31 11:08 UTC, DmitryKuzmenko commented
re-run full macosxmojave-py2

2020-03-31 16:35 UTC, DmitryKuzmenko commented
re-run full macosxmojave-py2

2020-04-02 10:22 UTC, DmitryKuzmenko commented
Py2 ci builds are isabled so this PR is green now. There's nothing to update to force rebuild all here. So I'm marking this as merge ready.

2020-04-13 21:37 UTC, DmitryKuzmenko commented
@guettli could you please resolve the merge conflicts and run the pre-commit script on your code to re-format it with `isort` and `black` we're using now.
```
pip install pre-commit
pre-commit install
FILES="$(git show --pretty="" --name-only master..HEAD)"
pre-commit run isort $FILES
pre-commit run black $FILES
```
next time you'll commit it will be ran automatically.

2020-04-14 09:29 UTC, guettli commented
@DmitryKuzmenko sorry, I can't reformat it. I switched the job and don't use salt any more. Sorry.

2020-04-14 09:42 UTC, DmitryKuzmenko commented
@guettli thank you for clarification. I'll take care of this. Thank you for contribution

2020-04-14 10:18 UTC, DmitryKuzmenko commented
Closing in favor of #56631.

2020-04-14 10:18 UTC, closed without merging