(Backport 50725) mount: add fstab_{present,absent} states
saltstack/salt pull request #54965
Opened 2019-10-11 14:46 UTC by aplanas

### What does this PR do?

Add two new states in mount:

* fstab_present: Makes sure that a fstab entry is present, without mounting the device.
* fstab_absent: Makes sure that a fstab entry is absent, without unmounting the device.

The code is adjusted to work on Linux, MacOS and AIX.

### Tests written?

Yes

(backport #50725, already merged in develop)

2019-12-04 15:43 UTC, dhiltonp commented
Thank you so much for this PR with these 2 backports. Could you split them up in to two separate PRs?

The functionality of these 2 PRs overlaps and I'm not sure both should go in.

2019-12-04 15:44 UTC, dhiltonp requested changes
Thank you so much for this PR with these 2 backports. Could you split them up in to two separate PRs?

The functionality of these 2 PRs overlaps and I'm not sure both should go in.

2019-12-04 15:56 UTC, aplanas commented
@dhiltonp they overlap, as the second one is build as a change for the first one. You can see it, for example, here: https://github.com/saltstack/salt/pull/54965/commits/ae341590ce7a4993ad55f679b3479bbd4f5382e0#diff-ba2bfb2cb504d0deb9fc5af6584c9032L994

2019-12-04 16:31 UTC, dhiltonp commented
Yeah. It is annoying having PRs that depend on each other.

I certainly see why the 52962 port PR would include the 50725 commits, but there is value in also having an individual port PR for 50725.

2019-12-05 09:56 UTC, aplanas commented
@dhiltonp very well. I split the PR in two, the other backport is living here in #55516

2019-12-05 20:50 UTC, dwoz approved these changes

2019-12-05 20:50 UTC, merged