(Backport 51074) disk: support setting FAT size for format_
saltstack/salt pull request #54967
Opened 2019-10-11 15:41 UTC by aplanas

### What does this PR do?

Add new optional parameter `fat` in disk.format_ to specify the FAT size (12, 16 or 32).

### Tests written?

Yes

(backport #51074, already merged in develop)

2019-11-19 20:15 UTC, dwoz approved these changes

2019-12-03 18:20 UTC, garethgreenaway approved these changes

2019-12-20 23:36 UTC, dwoz requested changes
@aplanas Looks like the mac os test failures are related to this change.

2019-12-21 16:26 UTC, dwoz requested changes
@aplanas The mac test failures seem too be related.

2020-01-03 01:52 UTC, closed without merging