Master-port #52441
saltstack/salt pull request #54985
Opened 2019-10-13 09:00 UTC by mchugh19

cron return a single line

### What does this PR do?
Ports #52441 to master

Add get_entry to cron module to return a single cron entry. This allows for use in tools like saltcheck:

```
validate_cron.{{ task }}_exists:                                          
  module_and_function: cron.get_entry                                     
  args:                                                                   
    - root                            
    - {{ task }}                                                          
  assertion: assertEqual                                                  
  assertion_section: identifier                                           
  expected-return: {{ task }}
```

2019-12-04 17:09 UTC, dhiltonp requested changes
This PR needs some tests. 

It's a good candidate for unit tests - patch list_tab to return sample data, then verify that it breaks if cmd and identifier are specified, and works if identifier or cmd are specified.

Is it possible for the same identifier to occur multiple times in the crontab? What about the same command at different intervals?

2019-12-04 22:16 UTC, myii requested changes

2019-12-04 22:17 UTC, myii commented
Apologies, I started that review weeks ago but I wsited for the PR route but both were closed.

2019-12-16 23:57 UTC, dwoz commented
@mchugh19 Can you address the comments?

2019-12-17 15:17 UTC, mchugh19 commented
Added tests and @myii's changes. I think this should be good to go!

2019-12-17 15:17 UTC, mchugh19 commented on salt/modules/cron.py
> +        salt '*' cron.identifier_exists root identifier=task1
Corrected

2019-12-17 15:17 UTC, mchugh19 commented on salt/modules/cron.py
> +        salt '*' cron.identifier_exists root identifier=task1
Corrected

2019-12-17 15:18 UTC, mchugh19 commented on salt/modules/cron.py
> +    cron_entries = list_tab(user).get('crons', False)
Corrected

2020-01-11 07:19 UTC, mchugh19 commented
re-run pr-py3-centos-8

2020-01-11 07:20 UTC, mchugh19 commented
re-run pr-ubuntu1604-py3-m2crypto

2020-02-15 12:10 UTC, mchugh19 commented
re-run pr-ubuntu1604-py2-m2crypto

2020-03-12 18:23 UTC, dhiltonp submitted a review, later dismissed

2020-04-02 10:20 UTC, mchugh19 commented
re-run pr-amazon2-py2

2020-04-02 11:18 UTC, DmitryKuzmenko commented
There are no py2 anymore. I've updated the branch to force refreshing of the tests list.

2020-04-13 10:45 UTC, dwoz approved these changes

2020-04-13 10:45 UTC, merged