(Backport 52182) mdadm_raid: convert metadata to text
saltstack/salt pull request #55002
Opened 2019-10-14 09:18 UTC by aplanas

### What does this PR do?

Convert the metadata parameter to text, as can be represented as a float in the pillar (0.9, 1.0, 1.2, etc)

### Tests written?

Yes

(backport #52182, already merged in develop)

2019-12-03 20:15 UTC, dwoz requested changes
@aplanas Looks like the test failures are related

2019-12-04 09:50 UTC, aplanas commented
Ouch. Fixed the test.

2019-12-20 05:30 UTC, dwoz requested changes
@aplanas Several suites are still failing:

https://jenkinsci.saltstack.com/job/pr-amazon2-py3/job/PR-55002/7/testReport/junit/unit.modules.test_mdadm_raid/MdadmTestCase/test_create_metadata/

2019-12-20 23:29 UTC, dwoz approved these changes

2019-12-20 23:30 UTC, merged