Fix novaclient api
saltstack/salt pull request #55050
Opened 2019-10-17 23:15 UTC by Akm0d

### What does this PR do?
Port https://github.com/saltstack/salt/pull/49977/commits to master

2019-12-05 21:15 UTC, dwoz commented
@Akm0d The linter is still failing here.

2019-12-12 02:01 UTC, Akm0d commented
re-run full all

2019-12-12 07:02 UTC, Akm0d commented
re-run full windows2016

2019-12-12 07:02 UTC, Akm0d commented
re-run full windows2019

2019-12-12 07:02 UTC, Akm0d commented
re-run full opensuse15

2019-12-12 09:52 UTC, s0undt3ch approved these changes

2019-12-12 19:13 UTC, dwoz commented on salt/utils/openstack/nova.py
> +        #        except Exception as esc:
why not just remove this?

2019-12-12 19:15 UTC, dwoz requested changes

2019-12-12 19:15 UTC, dwoz commented on salt/utils/openstack/nova.py
> +        verify = kwargs.get('verify', False)
This doesn't make sense, how would verify get in `kwargs` when it's defined as a keyword argument on line 273?

2019-12-12 19:18 UTC, dwoz commented on salt/utils/openstack/nova.py
> +                                               endpoint_filter={'service_type': identity_service_type}).json().get(
This line is still really long, I suggest

```
   self.catalog = conn.client.session.get(
        '/auth/catalog',
        endpoint_filter={
            'service_type': identity_service_type
        }
    ).json().get('catalog', [])
```

2020-01-02 09:34 UTC, dwoz commented
2019 windows tests are passing:

```
05:57:53         OK (total=9282, skipped=1213, passed=8069, failures=0, errors=0)
```

merging pr

2020-01-02 09:34 UTC, merged