[master] Initial work for the new logging setup for salt
saltstack/salt pull request #55055
Opened 2019-10-18 12:57 UTC by s0undt3ch

### What does this PR do?
Starts moving code around to support the new Salt logging support.
This is part of https://github.com/saltstack/salt/pull/55043 so that it gets implemented/reviewed in smaller chunks.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/pull/55043

### Commits signed with GPG?

Yes/No

2019-10-18 15:12 UTC, Akm0d approved these changes

2019-10-18 20:45 UTC, waynew requested changes
I see that your PR is in chunks now 😂

2019-10-18 20:45 UTC, waynew commented on salt/_logging/__init__.py
> +    although, as best effort, we'll try not to break code relyin on it.
```suggestion
    although, as best effort, we'll try not to break code relying on it.
```

2019-10-18 20:45 UTC, waynew commented on salt/_logging/__init__.py
> +    The ``salt._logging`` package should be imported as soon as possible since salt teaks
```suggestion
    The ``salt._logging`` package should be imported as soon as possible since salt tweaks
```

2019-10-18 20:46 UTC, s0undt3ch commented on salt/_logging/__init__.py
> +    although, as best effort, we'll try not to break code relyin on it.
Will fix

2019-10-18 20:48 UTC, s0undt3ch commented on salt/_logging/__init__.py
> +    although, as best effort, we'll try not to break code relyin on it.
Fixed

2019-10-18 20:49 UTC, s0undt3ch commented on salt/_logging/__init__.py
> +    The ``salt._logging`` package should be imported as soon as possible since salt teaks
Fixed

2019-10-18 20:51 UTC, waynew approved these changes
😞emoji, y u no have :log:???

2019-10-19 16:49 UTC, dwoz approved these changes

2019-10-20 21:23 UTC, merged