Fix empty reactor traceback in reactor.py
saltstack/salt pull request #55062
Opened 2019-10-19 05:20 UTC by mattLLVW

### What does this PR do?

This PR prevent traceback when trying to list reactors when none are configured

### What issues does this PR fix or reference?

Fixes #53334
### Previous Behavior

`Passed invalid arguments: 'NoneType' object has no attribute '__getitem__'`

### New Behavior
`None`

### Tests written?

No

2019-12-20 14:24 UTC, mattLLVW commented
@garethgreenaway could you please check this MR?
Thank you.

2020-01-13 22:53 UTC, dwoz commented
@mattLLVW Can you please look into writing a test for this?

2020-01-14 21:23 UTC, mattLLVW commented
@dwoz sure, i'll look into it.

2021-02-18 04:17 UTC, garethgreenaway commented
@mattLLVW Apologies for the delay on this one.  Were you able to put a test together for the changes?  Please let us know if you need help writing them.  This would be a great fix to get in.

2021-02-18 19:49 UTC, garethgreenaway commented
There are some existing tests for the reactor runner, I added a couple more use cases to include the fix in this PR.  Some additional fixes as well.

2021-02-19 10:34 UTC, s0undt3ch requested changes

2021-02-19 10:34 UTC, s0undt3ch commented on salt/runners/reactor.py
> +        reactors = results.get('reactors', None)
```suggestion
        reactors = results.get('reactors')
```
This does exactly the same.

2021-02-19 10:34 UTC, s0undt3ch commented on salt/runners/reactor.py
> +        return res.get('result', None)
```suggestion
        return res.get("result")
```

2021-02-19 10:34 UTC, s0undt3ch commented on salt/runners/reactor.py
> +        return res.get('result', None)
```suggestion
        return res.get("result")
```

2021-02-19 11:05 UTC, mattLLVW commented
@garethgreenaway @s0undt3ch I added the tests you provided and removed the useless `get(param, None)` 
Let me know if it's ok.

2021-02-19 13:26 UTC, s0undt3ch submitted a review, later dismissed

2021-02-19 13:29 UTC, s0undt3ch commented
Looks like there's still Lint and Pre commit stuff to fix.

https://docs.saltproject.io/en/latest/topics/development/contributing.html#quickstart

2021-02-19 14:30 UTC, garethgreenaway submitted a review, later dismissed

2021-02-19 14:45 UTC, s0undt3ch approved these changes, later dismissed

2021-02-19 16:24 UTC, Ch3LL approved these changes

2021-02-19 16:37 UTC, twangboy approved these changes

2021-02-19 18:17 UTC, merged