Respect argline passed into jinja renderer
saltstack/salt pull request #55126
Opened 2019-10-25 17:15 UTC by terminalmage

Resolves #55124.

2019-10-28 17:22 UTC, dwoz submitted a review, later dismissed

2019-10-29 17:35 UTC, terminalmage commented
I just realized that I opened this PR against master. The goal is to have this fix in 2019.2.3, does it need to be rebased against a different branch for this?

2019-12-27 17:20 UTC, waynew requested changes

2019-12-27 17:20 UTC, waynew commented on tests/integration/modules/test_state.py
> +
Lint says too many blank lines (should be 1)

2019-12-27 17:24 UTC, waynew commented
Looks like there are some possibly related test failures?

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_jinja.py", line 1492, in test_normlookup
    ret = self.render(tmpl_str)
  File "/tmp/kitchen/testing/tests/unit/utils/test_jinja.py", line 1483, in render
    return self.jinja(tmpl_str, context=context or {}, from_str=True).read()
  File "/tmp/kitchen/testing/salt/renderers/jinja.py", line 71, in render
    **kws)
TypeError: render_tmpl() got multiple values for keyword argument 'from_str'
	
```

2020-01-02 15:30 UTC, terminalmage commented
The tests that were failing were failing because they were not designed properly. `from_str` is supposed to be derived from the argline, not passed in via the double-asterisk catch-all. I fixed the failing tests.

2020-01-04 09:36 UTC, dwoz commented
@terminalmage @waynew the windows failures look legit.

2020-01-15 14:59 UTC, terminalmage commented
@dwoz I pushed an update to the tests, and rebased to bring it up to date with master.

2020-03-19 22:17 UTC, sagetherage commented
@terminalmage looks like there are pending conflicts when you get time :) I'm  updating the labels to next release so that it isn't confusing

2020-03-20 14:20 UTC, terminalmage commented
Rebased again.

2020-04-07 02:57 UTC, terminalmage commented
Rebased yet again. It has been 5 1/2 months since this PR was opened. It's a one-line code change, and was submitted _with tests_.

Can we please get this re-re-re-reviewed and merged?

2020-04-07 10:45 UTC, DmitryKuzmenko approved these changes

2020-04-12 06:59 UTC, dwoz approved these changes

2020-04-12 06:59 UTC, merged