Use packaged msgpack
saltstack/salt pull request #55354
Opened 2019-11-18 21:59 UTC by Akm0d

### What does this PR do?
Separates msgpack changes from https://github.com/saltstack/salt/pull/54878

2019-11-19 17:13 UTC, dwoz commented
re-run full all

2019-11-19 17:18 UTC, dwoz requested changes

2019-11-19 17:18 UTC, dwoz commented on salt/log/handlers/fluent_mod.py
> +        return msgpack.packb(packet, _msgpack_module=msgpack)
What is the driver allowing the use of a different msgpack module. I think we should keep things consistent by always using the module imported in `utils.msgpack`

2019-11-19 17:19 UTC, waynew approved these changes
🚀

2019-11-25 17:51 UTC, Akm0d commented
re-run full archlts

2019-12-12 02:01 UTC, Akm0d commented
re-run full all

2019-12-12 07:01 UTC, Akm0d commented
re-run full tcp

2019-12-12 16:31 UTC, Akm0d commented
re-run full amazon1

2019-12-15 06:21 UTC, Akm0d commented
re-run full debian8

2019-12-15 08:39 UTC, Akm0d commented
Cleaned up the history now that it's all green :+1:. @dwoz I tried to move as much msgpack logic as possible from salt/payload.py to salt/utils/msgpack.py.   If I move much more then the msgpack module starts behaving too differently from the base msgpack module

2019-12-15 17:03 UTC, Akm0d commented
re-run full amazon1

2019-12-15 17:04 UTC, Akm0d commented
re-run full pycryptodomex

2019-12-15 17:06 UTC, Akm0d commented
re-run full fedora30

2019-12-16 09:25 UTC, Akm0d commented
re-run full debian8

2019-12-16 15:22 UTC, waynew approved these changes
Does this replace all of the `import msgpack`?

It would be full of winning if we could add a lint rule to stop any `import msgpack` - though I'm not sure if those rules are in this repo.

2019-12-16 16:18 UTC, Akm0d commented
re-run full windows2016

2019-12-16 16:18 UTC, Akm0d commented
re-run full windows2019

2019-12-16 16:26 UTC, Akm0d commented
> Does this replace all of the `import msgpack`?
> 
> It would be full of winning if we could add a lint rule to stop any `import msgpack` - though I'm not sure if those rules are in this repo.

It replaces most `import msgpack`.  The exception is a few linters, loggers, and tests where it would cause a circular dependency

2019-12-18 00:01 UTC, Akm0d commented
re-run full debian8

2019-12-18 08:58 UTC, Akm0d commented
re-run full macosxmojave

2019-12-18 21:06 UTC, dwoz approved these changes

2019-12-18 21:06 UTC, merged