Do not close singleton instances.
saltstack/salt pull request #55399
Opened 2019-11-21 20:57 UTC by Nate-Watts

This must be done by GC when there are no references to it.

### What does this PR do?
Port #50798 to master

### What issues does this PR fix or reference?
#45839

### Tests written?

No

### Commits signed with GPG?

No

2019-11-25 18:06 UTC, xeacott commented
Appears to be some left over output from `diff` in the code. Clean that out and I'm sure this will pass. :)

2019-12-02 17:10 UTC, dwoz requested changes

2019-12-02 17:10 UTC, dwoz commented on salt/transport/ipc.py
> +<<<<<<< HEAD
@Nate-Watts It looks like there are merge conflicts included in this change

2019-12-05 21:05 UTC, dwoz requested changes
@Nate-Watts The linter is failing and I am concerned about the amount of test suites that timed out with this change.

2020-03-26 14:57 UTC, frogunder commented
@Nate-Watts You mind stopping by this one and look at the lint and test failures?

Thanks.

2020-05-27 20:01 UTC, closed without merging