Port 50896
saltstack/salt pull request #55396
Opened 2019-11-21 20:39 UTC by Nate-Watts

### What does this PR do?
Port of #50896 to master

### What issues does this PR fix or reference?
n/a

### Tests written?
No

### Commits signed with GPG?
No

2020-04-06 15:34 UTC, DmitryKuzmenko commented
There are merge conflicts now. Also tests are needed for this change.

2020-11-18 18:36 UTC, sagetherage commented
@salty-blue-mango if you can help with the merge conflicts here, pretty please?

2021-01-19 20:43 UTC, waynew commented
@sagetherage fixed the merge conflicts, and added tests

2021-02-22 19:17 UTC, xeacott approved these changes

2021-02-24 19:36 UTC, Ch3LL requested changes

2021-02-24 19:36 UTC, Ch3LL commented on salt/modules/event.py
> +        event = salt.utils.event.get_event(
we should still use `with` here to ensure everything is closed properly with salt's event class.

2021-12-16 21:01 UTC, Ch3LL commented
Just following up on this PR. Any chance you saw my review from earlier?

2022-03-09 21:21 UTC, Ch3LL commented
ping @waynew mind fixing the merge conflict here again?

2023-12-10 06:12 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 06:12 UTC, closed without merging