Decide if the source should be actually skipped
saltstack/salt pull request #55402
Opened 2019-11-21 21:03 UTC by Nate-Watts

### What does this PR do?
Port of #50792

### What issues does this PR fix or reference?
Bugfix. If there is a Debian repo with signed-by option, Salt doesn't show it.

### Tests written?
No

### Commits signed with GPG?

No

2019-12-06 00:26 UTC, dwoz requested changes

2019-12-06 00:26 UTC, dwoz commented on salt/modules/aptpkg.py
> +def _skip_source(source):
`_skip_source` should get unit tested

2020-01-08 00:08 UTC, garethgreenaway submitted a review, later dismissed

2020-01-08 00:08 UTC, garethgreenaway commented on salt/modules/aptpkg.py
> +def _skip_source(source):
Added a test for _skip_source.

2020-03-18 19:50 UTC, cmcmarrow submitted a review, later dismissed

2020-03-24 15:20 UTC, frogunder submitted a review, later dismissed

2020-04-11 10:31 UTC, dwoz commented
@Nate-Watts Black needs to be run on this

2020-04-13 07:41 UTC, dwoz commented
@Nate-Watts Black needs to be run on these changes.

2020-05-04 08:17 UTC, dwoz approved these changes

2020-05-04 08:18 UTC, merged