Refactored cloud tests to use 'assertCreateInstance'
saltstack/salt pull request #55435
Opened 2019-11-25 19:19 UTC by Akm0d

### What does this PR do?
Refactor the cloud tests to use `assertCreateInstance`
Combine all digital ocean tests into the same directory

2019-11-26 23:30 UTC, Akm0d commented
The cloud test suite on `master` currently shows a bunch of false positives.  
With this refactor we properly blow up on bootstrap failures and creation errors:
https://jenkinsci.saltstack.com/view/Akm0d%20Jobs/job/Develop%20Py3%20Cloud/280/

2019-11-26 23:33 UTC, Akm0d commented
https://github.com/saltstack/salt/pull/55046 is an attempt to solve the win2012r2 psexec and winrm tests

2019-11-27 21:53 UTC, dwoz requested changes

2019-11-27 21:53 UTC, dwoz commented on tests/integration/cloud/clouds/test_vultrpy.py
> -    # Commented for now, Vultr driver does not yet support key management
This can be removed.

2019-11-27 22:13 UTC, Akm0d commented on tests/integration/cloud/clouds/test_vultrpy.py
> -    # Commented for now, Vultr driver does not yet support key management
It is :+1:

2019-12-09 21:54 UTC, Akm0d commented
integration.cloud.clouds.test_msazure.AzureTest.test_instance
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_msazure.py", line 60, in test_instance
    self.assertCreateInstance(timeout=TIMEOUT)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 79, in assertCreateInstance
    self.assertInstanceExists(creation_ret=stdout, instance_name=instance_name, stderr=stderr)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 93, in assertInstanceExists
    self.fail('\n'.join(stderr))
AssertionError: [WARNING ] There's no master defined on the 'cloud-test-azu-hvbbe' VM settings.
No ECDSA host key is known for 40.112.223.183 and you have requested strict checking.
Host key verification failed.```

2019-12-09 21:55 UTC, Akm0d commented
integration.cloud.clouds.test_gogrid.GoGridTest.test_instance 
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_gogrid.py", line 24, in test_instance
    self.assertCreateInstance(timeout=TIMEOUT)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 79, in assertCreateInstance
    self.assertInstanceExists(creation_ret=stdout, instance_name=instance_name, stderr=stderr)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 93, in assertInstanceExists
    self.fail('\n'.join(stderr))
AssertionError: [WARNING ] SSL Error on 13 ('50.18.48.147', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
[WARNING ] There's no master defined on the 'cloud-test-gog-vedul' VM settings.
[WARNING ] SSL Error on 9 ('184.169.137.160', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
[ERROR   ] There was a profile error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)```

2019-12-09 21:56 UTC, Akm0d commented
integration.cloud.clouds.test_vultrpy.VultrTest.test_instance 
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_vultrpy.py", line 115, in test_instance
    self.assertCreateInstance(timeout=TIMEOUT + 300)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 79, in assertCreateInstance
    self.assertInstanceExists(creation_ret=stdout, instance_name=instance_name, stderr=stderr)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 93, in assertInstanceExists
    self.fail('\n'.join(stderr))
AssertionError: [WARNING ] There's no master defined on the 'cloud-test-vul-jgfqa' VM settings.
Warning: Permanently added '45.63.6.140' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).```

2020-08-17 19:14 UTC, Ch3LL requested changes
looks like this has some merge conflicts that need to be resolved and pre-commit failing

2021-12-16 21:02 UTC, Ch3LL commented
Is this still being worked on? If not can this be closed?

2022-03-09 21:21 UTC, Ch3LL commented
Closing due to inactivity

2022-03-09 21:21 UTC, closed without merging