Fix service.reload in gentoo_service module
saltstack/salt pull request #55452
Opened 2019-11-27 22:38 UTC by vulnbe

### What does this PR do?
It fixes gentoo_service.py module.

### What issues does this PR fix or reference?
gentoo_service module has reload_ function but service.reload doesn't work because there is no 'reload' alias defined.

### Tests written?
I believe the existing tests are enough for such changes.

### Commits signed with GPG?

Yes

2019-12-02 18:17 UTC, dwoz approved these changes

2019-12-02 18:18 UTC, dwoz requested changes
@vulnbe Please fix the linter issue

2019-12-03 06:53 UTC, vulnbe commented
@dwoz done.

2019-12-03 09:25 UTC, dwoz approved these changes

2019-12-03 09:25 UTC, merged