Catch `CommandExecutionError` when stopping a service
saltstack/salt pull request #55508
Opened 2019-12-04 10:57 UTC by eliasp

### What does this PR do?
It adds handling of a previously unhandled exception in `states.service.dead`.

### What issues does this PR fix or reference?
It's a follow-up to a previous PR (#54797) which targeted `2019.2`, now against `master`.

### Previous Behavior
The state `service.dead` could fail like this:
```
An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1913, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1898, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\states\service.py", line 593, in dead
    func_ret = __salt__['service.stop'](name, **stop_kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 453, in stop
    'Failed To Stop {0}: {1}'.format(name, exc[2]))
CommandExecutionError: Failed To Stop w3svc: The service cannot accept control messages at this time.
```

### New Behavior
The state will now handle this case properly with `Result: False` and show the corresponding exception error string as comment instead.

### Tests written?
Yes, but I don't have an environment to run SaltStack's Windows tests (depending on `pywintypes` being available) right now, so I'll have to wait for the CI pipeline to verify it...

### Commits signed with GPG?

Yes

2019-12-15 16:23 UTC, eliasp commented
Any suggestions on how to fix the `unit.modules.test_win_service.WinServiceTestCase.test_stop_refused` test?
I don't quite get it, why it is failing...

2019-12-27 18:18 UTC, waynew requested changes
Just a simple typo, I think.

2019-12-27 18:18 UTC, waynew commented on tests/unit/modules/test_win_service.py
> +            side_effect=pywintypes.error(1061,
```suggestion
            side_effect=pywintypes.error(1062,
```
This just has the wrong error code for the win_service:
```
    try:
        win32serviceutil.StopService(name)
    except pywintypes.error as exc:
        if exc.winerror != 1062:
            raise CommandExecutionError(
                'Failed To Stop {0}: {1}'.format(name, exc.strerror))
        log.debug('Service "{0}" is not running'.format(name))
```

2023-12-10 06:17 UTC, closed without merging

2023-12-10 06:17 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.