Fix for issue #55562
saltstack/salt pull request #55563
Opened 2019-12-09 05:56 UTC by colin-stubbs

Ensures changes is returned as a dictionary rather than an empty string.

### What does this PR do?

Fixes return handling from opsgenie states by ensuring changes is a dictionary. Failing to do this means the create_alert and close_alert states always appear to have failed (return becomes False) even if OpsGenie API call was successful.

### What issues does this PR fix or reference?

Issue #55562

### Previous Behavior

create_alert and close_alert states always return false as state return receiving code triggers exception when trying to use changes as dictionary. True return value is ignored.

### New Behavior

create_alert and close_alert states always return true or false as appropriate along with changes as an empty dictionary. No exception triggered in receiving code.

### Tests written?

No

### Commits signed with GPG?

No

2019-12-09 14:46 UTC, waynew commented
Hey @colin-stubbs, thanks for the PR!

I'm guessing that there aren't (m)any existing tests for this state - given the failure being something extremely simple.

This is the kind of thing that has driven us to **require** passing tests for merging all PRs.

The options at this point are:

1. You already have a good idea about how the tests work, and could modify (if there are any) or add tests to ensure that the state returns proper information.
2. You don't know how the tests work, but want to write the tests and lack the knowledge. We are planning to start up online testing workshops to help train folks how to actually write & run tests for Salt.
3. You're not interested in writing tests, and this is as much contribution as you feel like making. We add the [needs testcase] and [help wanted] label, and someone else takes over and writes the test.

Just let us know which option you prefer, so we can get things moving from there. Thanks again!

2020-07-17 19:08 UTC, waynew commented
Hey, @colin-stubbs - are you interested in getting this to completion?

We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.

If you need help writing documentation, we have a [documentation working group](https://github.com/saltstack/docs-hub) that would love to help out.

If you're struggling with writing tests, reach out to the [testing working group](https://github.com/saltstack/community/tree/master/working_groups/wg-Testing) or attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

Thanks again!

2020-07-17 19:09 UTC, waynew requested changes
Hey, @colin-stubbs - are you interested in getting this to completion?

We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.

If you need help writing documentation, we have a [documentation working group](https://github.com/saltstack/docs-hub) that would love to help out.

If you're struggling with writing tests, reach out to the [testing working group](https://github.com/saltstack/community/tree/master/working_groups/wg-Testing) or attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

Thanks again!

2021-07-19 18:43 UTC, sagetherage commented
@colin-stubbs can you please address these merge conflicts? Thank you!

2023-12-10 06:18 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 06:18 UTC, closed without merging