Added a support for a global proxy to pip module
saltstack/salt pull request #55596
Opened 2019-12-10 21:21 UTC by Oloremo

### What does this PR do?
Added support for a global Salt proxy to pip module

### What issues does this PR fix or reference?
#55593

### Previous Behavior
pip module and state doesn't support salt global proxy

### New Behavior
pip module and state does support salt global proxy

### Tests written?

Yes

### Commits signed with GPG?

Yes

2019-12-12 09:42 UTC, s0undt3ch requested changes

2019-12-12 09:42 UTC, s0undt3ch commented on salt/modules/pip.py
> +            you should pass the ``False`` as a value.
'you should pass ``False`` as'...

2019-12-12 14:30 UTC, Oloremo commented on salt/modules/pip.py
> +            you should pass the ``False`` as a value.
tx. done

2019-12-12 15:38 UTC, s0undt3ch reviewed
I would also do something like:
```python
    elif proxy is not False and config.get('proxy_host') and config.get('proxy_port'):
        if config.get('proxy_username') and config.get('proxy_password'):
            http_proxy_url = 'http://{proxy_username}:{proxy_password}@{proxy_host}:{proxy_port}'.format(**config)
        else:
            http_proxy_url = 'http://{proxy_host}:{proxy_port}'.format(**config)
```

2019-12-12 17:03 UTC, Oloremo commented
@s0undt3ch  Very cool, added!

2019-12-12 17:07 UTC, s0undt3ch approved these changes

2019-12-12 17:38 UTC, Oloremo commented
re-run full  opensuse15-py2

2019-12-12 20:34 UTC, Oloremo commented
re-run full ubuntu1604-py2

2019-12-13 00:04 UTC, Oloremo commented
re-run full macosxmojave-py2

2019-12-13 10:58 UTC, Oloremo commented
re-run full windows2019-py3

2019-12-14 02:58 UTC, merged

2020-01-16 09:44 UTC, max-arnold commented
Nitpick: it is worth documenting that the `no_proxy` global setting has no effect on pip