guestfs: create mount folder if initially computed one is busy
saltstack/salt pull request #55672
Opened 2019-12-17 09:34 UTC by cbosdo

# What does this PR do?

When mounting an image, if the computed folder is already existing and
not empty, then we try to find another one that could be used. But then
we need to create the folder if needed.

### What issues does this PR fix or reference?

Issue 55349.

### Previous Behavior

Running this fails:

```
mkdir -p /tmp/guest/var.testsuite-data.disk-image-template.qcow2/foobar
salt-call --local guestfs.mount /var/testsuite-data/disk-image-template.qcow2
```

### New Behavior

Running the same mounts the image without error

### Tests written?

Yes

### Commits signed with GPG?

Yes

2019-12-17 09:35 UTC, cbosdo commented
@waynew since you were involved in the issue, you may want to review that PR

2019-12-27 09:24 UTC, dwoz requested changes

2019-12-27 09:24 UTC, dwoz commented on salt/modules/guestfs.py
> +                    # Somehow the path already exists
Lets log that the path exists?

2019-12-30 08:47 UTC, cbosdo commented on salt/modules/guestfs.py
> +                    # Somehow the path already exists
Done now.

2020-01-06 01:05 UTC, dwoz commented
re-run full centos

2020-01-06 17:45 UTC, dwoz approved these changes

2020-01-06 17:45 UTC, merged