runners/net.py Python 3 fixes
saltstack/salt pull request #55690
Opened 2019-12-18 08:06 UTC by chonty

### What does this PR do?
Fixes errors when using Python 3.  Very small changes which also work in Python 2.

### What issues does this PR fix or reference?

```
[root@salt runners]# salt-run net.find 1.2.3.4
Details for all interfaces that include network 1.2.3.4/32 - only best match returned
ARP Entries for IP 1.2.3.4
Exception occurred in runner net.find: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 377, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 894, in find
    device, interface, mac = _find_interfaces_mac(ip)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 228, in _find_interfaces_mac
    ip_addresses.extend(interface_ipaddrs.get('ipv6', {}).keys())
AttributeError: 'dict_keys' object has no attribute 'extend
```

and

```
[root@salt runners]# salt-run net.find 1.2.3.4

Passed invalid arguments: '>' not supported between instances of 'IPNetwork' and 'NoneType'
```
### Previous Behavior
When using Python 3, net.find <ip address> would return errors.

### New Behavior
net.find returns desired, error-free output.

### Tests written?
No

### Commits signed with GPG?
No

2020-01-01 12:58 UTC, s0undt3ch requested changes

2020-01-01 12:58 UTC, s0undt3ch commented on salt/runners/net.py
> +                                if not best_net_match: compare = []
Please split into 2 lines.

2020-01-03 11:05 UTC, s0undt3ch approved these changes

2020-04-15 18:48 UTC, DmitryKuzmenko commented on salt/runners/net.py
> +                                    compare = []
This looks better for me:
```python
compare = [best_net_match] if best_net_match else []
```

2020-06-11 17:46 UTC, sagetherage commented
@chonty can you address the merge conflict, please?

2020-06-17 06:31 UTC, chonty commented
Merged PR #55421 fixes the same problems

2020-06-17 06:32 UTC, closed without merging