linux_lvm: accept more than one pv for lvcreate
saltstack/salt pull request #55698
Opened 2019-12-19 12:23 UTC by veym4os

If you want to create one lv on specific extents of multiple pvs,
lvcreate simply takes multiple lv[:extents] arguments. This patch
extends lvm.lvcreate to pass more than one lv parameter to lvcreate.

### Tests written?
No

2020-09-22 19:29 UTC, krionbsd submitted a review, later dismissed

2020-09-22 19:31 UTC, bryceml commented
only cb744f0828080a3e33646d61127b8655951108a4 was on the pr before I moved it to master.

2021-02-11 14:57 UTC, twangboy commented
@veym4os This probably needs to be rebased... conflicts need to be resolved. I don't think this change should be modifying this many files.

2022-10-28 14:42 UTC, twangboy requested changes
This needs a changelog and a testcase

2023-12-10 06:19 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 06:19 UTC, closed without merging