Fix the mem_total and swap_total tests on FreeBSD and OpenBSD
saltstack/salt pull request #55736
Opened 2019-12-26 17:09 UTC by asomers

They were comparing a float to an int.  AFAICT these tests have never
passed.  Tested on FreeBSD 13.

### What does this PR do?
Fixes two unit tests

### What issues does this PR fix or reference?
No open issues

### Previous Behavior
the mem_total test would fail with an error like "8158 != 8158.6278486"

### New Behavior
The mem_total test passes

### Tests written?
No - existing test fixed instead

### Commits signed with GPG?
Yes

2019-12-26 18:14 UTC, asomers commented
The test failures are not the fault of my changes.  Jenkins never gets as far as building Salt.  It fails with error messages like this:
```
10:12:51  nohup: failed to run command 'sh': Permission denied
11:12:53  process apparently never started in /var/jenkins/workspace/pr-windows2016-py3_PR-55736@tmp/durable-1adec101
```

2019-12-26 22:16 UTC, dwoz requested changes
@asomers This needs to be rebased and opened against the `master` branch, not `2018.3`

2019-12-26 22:29 UTC, asomers commented
The instructions at https://docs.saltstack.com/en/latest/topics/development/contributing.html#salt-s-branch-topology say that PRs should be opened against the "develop" branch for new features or the oldest supported release branch otherwise.  There is no mention of the "master" branch.  Is that document out of date?

2019-12-27 18:27 UTC, waynew commented
@asomers yes, it's currently out of date.

2019-12-27 19:23 UTC, asomers commented
So what is the current practice?

On Fri, Dec 27, 2019, 11:27 AM Wayne Werner <notifications@github.com>
wrote:

> @asomers <https://github.com/asomers> yes, it's currently out of date.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/55736?email_source=notifications&email_token=AAA7VOLNEEOKQ6VD5LVWQILQ2ZCINA5CNFSM4J7NC4E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXSQRQ#issuecomment-569321542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA7VOM3LGAJ4QFHQQRXCEDQ2ZCINANCNFSM4J7NC4EQ>
> .
>

2019-12-27 23:32 UTC, dwoz commented
@asomers I've update the branch and pointed the PR to `master`

2019-12-27 23:46 UTC, asomers commented
Your rebase looks fine to me.

2019-12-29 01:47 UTC, dwoz approved these changes

2019-12-29 01:47 UTC, merged