Fix the test_patch*failure tests on FreeBSD
saltstack/salt pull request #55737
Opened 2019-12-26 18:09 UTC by asomers

FreeBSD's patch command has a slightly different error message than GNU
patch.  Adjust the tests' expectations to accept either error message.

Tested on FreeBSD 13 with the master branch.

### What does this PR do?
Fixes two integration tests

### What issues does this PR fix or reference?
None

### Previous Behavior
These two tests would fail because of a string mismatch

### New Behavior
These two tests will pass

### Tests written?
No - existing tests modified

### Commits signed with GPG?
Yes

2019-12-26 18:19 UTC, asomers commented
The build failures are not the fault of my changes.  They failed with messages like:
```
11:09:34  ERROR: Could not find credentials entry with ID 'AWS_ACCESS_KEY_ID'
```

2019-12-26 22:15 UTC, dwoz requested changes
@asomers This needs to be rebased and opened against the `master` branch, not `2019.2`

2019-12-27 23:29 UTC, dwoz commented
@asomers I've updated the branch and pointed this PR to `master`

2019-12-27 23:45 UTC, asomers commented
Thanks @dwoz.  The rebase looks fine to me.

2019-12-28 10:25 UTC, dwoz approved these changes

2019-12-28 10:26 UTC, merged