Fix the linux_acl module on FreeBSD (and probably Illumos)
saltstack/salt pull request #55750
Opened 2019-12-28 15:59 UTC by asomers

### What does this PR do?
Fixes all of the commands in the linux_acl module on FreeBSD.  It probably fixes them for Illumos too, but I haven't tested on that platform.

### What issues does this PR fix or reference?
No open issues

### Previous Behavior
`linux_acl.getfacl` would return an error on FreeBSD because `--absolute-names` was unrecognized.  `linux_acl.{wipefacls,modfacl,delfacl}` with the `recursive` flag would probably return an error on Illumos (but I didn't check) because `-R` was unrecognized.

### New Behavior
`linux_acl.getfacl` now works on FreeBSD, as long as `recursive` isn't specified.  If it is, a `CommandExecutionError` will be raised.  The other commands, when used with the `recursive` flag on Illumos, will now also raise a `CommandExecutionError`

### Tests written?
No.  The existing tests in tests/unit/modules/test_linux_acl.py and tests/integration/modules/test_linu_acl.py provide adequate coverage.  I modified them so that all will pass on FreeBSD.

### Commits signed with GPG?

Yes

2020-01-02 22:21 UTC, dwoz requested changes
@asomers please look into the linter failure

2020-01-03 00:15 UTC, asomers commented
I haven't forgotten @dwoz;I've just been on vacation.

2020-01-06 20:22 UTC, asomers commented
Lint error fixed.  Also, rebased onto master.

2020-01-08 18:07 UTC, asomers commented
The test failures are timeouts.  They are unrelated to my changes.

2020-01-20 15:42 UTC, sjorge commented
Do you have an example state? If so I could probably pull in the patch and run the state on a SmartOS zone.

2020-01-20 16:29 UTC, asomers commented
For example state just look at the integration tests, @sjorge .  I don't have anything beyond that.

2020-01-21 14:59 UTC, sjorge commented
I guess from looking at the module, it makes sense. `dentry` is set to `''`

2023-12-10 06:30 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 06:30 UTC, closed without merging