GPG renderer security and performance improvements
saltstack/salt pull request #55772
Opened 2019-12-31 14:18 UTC by sathieu

### What does this PR do?
- Use [Python bindings](https://www.gnupg.org/related_software/gpgme/) when available
- Cache gpg data if requested

### What issues does this PR fix or reference?

### Previous Behavior

Doing `salt  <matcher> pillar.items` matching 60 minions with several pillars encrypted, we got timeout error.

### New Behavior

The commands returns within 2 to 4 seconds.

### Tests written?

No

### Commits signed with GPG?

No

2020-01-01 22:11 UTC, dwoz requested changes
@sathieu It looks like the test failures are related to this change, please take a look.

2020-01-02 11:14 UTC, sathieu commented
@dwoz Yes, this `AttributeError: 'module' object has no attribute 'errors'` error is strange because I don't have it, and this is [per doc](http://files.au.adversary.org/crypto/gpgme-python-howto.html#Decryption).

2020-01-07 09:59 UTC, sathieu commented
@dwoz I've removed the _Use Python bindings when available_, the most usefull feature being `gpg_cache`.

2020-05-14 11:55 UTC, sathieu commented
@dwoz Please review again, the failing tests are not related to this PR.

2020-05-14 18:56 UTC, sathieu commented
@dwoz @Akm0d Please review, now al checks have passed :v: .

2020-05-14 19:01 UTC, Akm0d approved these changes

2020-05-18 21:46 UTC, merged