requisite_any: dont fall in an infinite loop when req doesnt exist
saltstack/salt pull request #55777
Opened 2020-01-03 00:07 UTC by dwoz

Rebase of #50689

### What does this PR do?
the missing req logic wasn't picking up the _any variants causing an
infinite loop. this fixes that.

### What issues does this PR fix or reference?
not sure if any outstanding issues, but if you try to run a state with onchange_any: something_nonexistant the state engine will recursively loop and stacktrace.

### Tests written?
Yes

### Commits signed with GPG?
Yes

2020-01-03 04:04 UTC, max-arnold commented
Maybe this one is related: https://github.com/saltstack/salt/issues/55542

2020-01-04 04:10 UTC, dwoz commented
re-run full all

2020-01-04 23:17 UTC, dwoz commented
Looks like this change causes a bunch of tests to fail.

2021-02-11 14:49 UTC, twangboy approved these changes, later dismissed

2021-02-11 14:50 UTC, twangboy commented
@dwoz Please rebase and address the conflicts

2023-12-20 20:27 UTC, twangboy submitted a review, later dismissed

2023-12-20 20:27 UTC, twangboy commented
Got some pre-commit failures

2024-01-03 22:45 UTC, twangboy approved these changes

2024-10-11 13:12 UTC, bdrx312 commented
This fix was probably addressed by #66135, but a test could still be useful.

2025-03-27 15:30 UTC, twangboy requested changes
Changelog

2026-04-05 00:57 UTC, twangboy approved these changes

2026-04-05 09:37 UTC, merged