WIP: Job acknowledgement events
saltstack/salt pull request #55820
Opened 2020-01-08 22:11 UTC by lukasraska

### What does this PR do?
Implements new event type `salt/job/<JID>/ack/<MID>` that is fired everytime minion receives job for execution.

It also reenables reworked `tests/integration/modules/test_event.py` due to changes done in `SaltMinionEventAssertsMixin`.

### What issues does this PR fix or reference?
saltstack/salt-enhancement-proposals#23

### Tests written?
Yes, but I assume they will fail on Win / MacOSX minions

### Commits signed with GPG?
Yes

TODO:
- update known events documentation
- update minion configuration documentation
- fix any test issues

2020-01-09 11:28 UTC, lukasraska commented
re-run pr-opensuse15-py3

2020-01-12 22:07 UTC, dwoz commented
@lukasraska Please add your integration tests. I will take a look at making them less flaky.

2020-01-13 22:34 UTC, lukasraska commented
@dwoz Thanks for looking into this, I've pushed them and rebased to latest master. From my tries, the `setUpClass` method can sometimes raise `Empty` for no apparent reason (some environments work almost all the time, some raise it almost every time). Also I don't know if the Win test failures are related to this PR, but running just these tests is working fine on my win-server setup.

It also might be worth noting, before the change in logging, these tests using multithreaded Queue were completely failing on Win and OSX (they worked when print was put strategically, as I mentioned on SaltConf).

If you can think of how to make them more successful, `tests.integration.modules.test_event` can reuse the same mixin and can be re-enabled.

2020-01-16 21:27 UTC, waynew commented
> It also might be worth noting, before the change in logging, these tests using multithreaded Queue were completely failing on Win and OSX (they worked when print was put strategically, as I mentioned on SaltConf).

That's interesting, and hints at a race condition. It may be something else, but `print` involves a pretty hefty wait on that thread along with the system call(s). You should check if a `time.sleep(1)` accomplishes the same thing. That would be a strong indication that we're running into a race condition. If it's only the `print` that works, though, that's pretty confusing.

2023-12-10 06:37 UTC, dwoz commented
@lukasraska  are you still interested in pushing this over the finish line?

2023-12-20 21:26 UTC, twangboy requested changes
The tests need to be migrated to pytest

2023-12-20 21:26 UTC, twangboy commented on doc/ref/configuration/minion.rst
> +
Chlorine or Argon

2023-12-20 21:27 UTC, twangboy commented
Also needs a changelog

2024-07-05 04:53 UTC, dwoz commented
This can be re-based and re-opened if it should get into `3008.x`

2024-07-05 04:53 UTC, closed without merging