update neon reference
saltstack/salt pull request #55875
Opened 2020-01-15 18:28 UTC by frogunder

### What does this PR do?

Update Neon to 3000

2020-01-15 19:37 UTC, Ch3LL requested changes

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2016.11.9.rst
> +* **PR** `#43456`_: (`rallytime`_) Add 3000 to version list
we probably shouldn't update commit messages as those should be set to what they were previously

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2016.11.9.rst
> +  * 35c1d8898d Add 3000 to version list
here as well, should be changed back to neon

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2017.7.3.rst
> +      * 35c1d8898d Add 3000 to version list
here too

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2018.3.1.rst
> +  * 0adfee9b11 Updating a couple tests.  Fixing check_whitelist_blacklist to work with PY3 when non-iterables are passed.  Adding warning about lst_avg results being wrong and future updates in 3000.
here as well

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2018.3.1.rst
> +* **PR** `#46720`_: (`rallytime`_) Bump deprecation notices in nacl module & runner to 3000
^

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2018.3.1.rst
> +  * 5102c0310c Bump deprecation notices in nacl module & runner to 3000
^

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2018.3.3.rst
> +* **PR** `#48824`_: (`rallytime`_) Bump deprecation in win_servermanager state to 3000
^

2020-01-15 19:37 UTC, Ch3LL commented on doc/topics/releases/2018.3.3.rst
> +  * 6ef5412528 Bump deprecation in win_servermanager state to 3000
^

2020-01-15 19:37 UTC, Ch3LL commented on salt/cloud/deploy/bootstrap-salt.sh
> -    UBUNTU_DERIVATIVES="(trisquel|linuxmint|linaro|elementary_os|neon)"
this should stay neon and all changes in this file. we should not update the bootstrap script so remove all changes here. There is an ubuntu derivative named neon

2020-01-15 19:37 UTC, Ch3LL commented on salt/cloud/deploy/bootstrap-salt.sh
> +    3000_16_ubuntu_base="16.04"
here too ^

2020-01-15 19:37 UTC, Ch3LL commented on salt/grains/core.py
> +    '3000': 'KDE 3000',
this should stay neon as its the name of kde release

2020-01-15 19:37 UTC, Ch3LL commented on salt/grains/core.py
> -    'neon': 'Debian',
here too

2020-01-15 19:37 UTC, Ch3LL commented on salt/grains/core.py
> +    'KDE 3000': 'Debian',
and here ^

2020-01-15 19:37 UTC, Ch3LL commented on salt/modules/aptpkg.py
> +    if repo.startswith('ppa:') and __grains__['os'] in ('Ubuntu', 'Mint', '3000'):
this should go back to neon for same reasons as above, there is an actual kde release named neon

2020-01-15 19:37 UTC, Ch3LL commented on salt/modules/aptpkg.py
> +    if repo.startswith('ppa:') and __grains__['os'] in ('Ubuntu', 'Mint', '3000'):
and here

2020-01-15 19:37 UTC, Ch3LL commented on salt/modules/aptpkg.py
> +        if __grains__['os'] in ('Ubuntu', 'Mint', '3000'):
^

2020-01-15 19:37 UTC, Ch3LL commented on salt/modules/aptpkg.py
> +    if repo.startswith('ppa:') and __grains__['os'] in ('Ubuntu', 'Mint', '3000'):
^

2020-01-15 20:15 UTC, Ch3LL requested changes

2020-01-15 20:15 UTC, Ch3LL commented on salt/cloud/deploy/bootstrap-salt.sh
> +    neon="16.04"
this should still be `neon_16_ubuntu_base`

2020-01-15 20:15 UTC, Ch3LL commented on salt/cloud/deploy/bootstrap-salt.sh
> +    neon="16.04"
shouldn't see any updates in bootstrap-salt.sh file unless doing a bootstrap release

2020-01-15 20:22 UTC, Ch3LL approved these changes

2020-01-16 03:46 UTC, max-arnold commented
@frogunder @Ch3LL I found a few other issues.

Version numbers should be allocated here:

```
doc/topics/releases/version_numbers.rst:- Neon: ``TBD``
salt/version.py:        'Neon'          : (MAX_SIZE - 99, 0),
```

A couple of Neon features were wrongly attributed to Sodium:

```
% grep -r -E '\.\. version' doc | grep -i sodium

doc/topics/mine/index.rst:.. versionchanged:: Sodium
doc/topics/mine/index.rst:.. versionadded:: Sodium
doc/topics/mine/index.rst:.. versionchanged:: Sodium

% grep -r -E '\.\. version' salt | grep -i sodium

salt/states/azurearm_dns.py:.. versionadded:: Sodium
salt/states/azurearm_dns.py:    .. versionadded:: Sodium
salt/states/azurearm_dns.py:    .. versionadded:: Sodium
salt/states/azurearm_dns.py:    .. versionadded:: Sodium
salt/states/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/mine.py:    .. versionchanged:: Sodium
salt/modules/azurearm_dns.py:.. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/azurearm_dns.py:    .. versionadded:: Sodium
salt/modules/cmdmod.py:        .. versionadded:: Sodium
salt/modules/hashutil.py:    .. versionadded:: Sodium
salt/beacons/cert_info.py:.. versionadded:: Sodium
```

Some features are still attributed to Fluorine (I have no idea when they were actually merged, please check the PRs):

```
% grep -r -E '\.\. version' salt | grep -i -E '(flourine|fluorine)'

salt/grains/nvme.py:.. versionadded:: Flourine
salt/modules/gpg.py:        .. versionadded:: fluorine
salt/modules/debuild_pkgbuild.py:        .. versionadded:: fluorine
salt/modules/debuild_pkgbuild.py:        .. versionadded:: fluorine
```

Lowercase `neon` (although the PR addresses that):

```
% grep -r -E '\.\. version' salt | grep  'neon'

salt/pillar/git_pillar.py:.. versionadded:: neon
salt/engines/fluent.py:.. versionadded:: neon
salt/states/virt.py:        .. versionadded:: neon
salt/states/virt.py:        .. versionadded:: neon
salt/states/virt.py:        .. versionadded:: neon
salt/modules/virt.py:        .. versionadded:: neon
salt/modules/virt.py:        .. versionadded:: neon
salt/modules/virt.py:        .. versionadded:: neon
salt/modules/virt.py:        .. versionadded:: neon
salt/modules/virt.py:    .. versionadded:: neon
```

A couple of `.. versionadded` have no space (not sure how that would be rendered by sphinx):

```
% grep -r -E '\.\.version' salt | grep -i -E 'neon'

salt/modules/virt.py:        ..versionadded:: Neon
salt/modules/virt.py:        ..versionadded:: Neon
```

2020-01-17 17:33 UTC, merged