Added dnf support on Centos > 7 #55898
saltstack/salt pull request #55910
Opened 2020-01-18 16:38 UTC by giany

### What does this PR do?

Enables dnf support for CentOS 8 systems.

### What issues does this PR fix or reference?

Fixes #55898 

### Previous Behavior

If you tried to use pkg.installed this error appears:
```
          ID: timezone
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Failed to find executable yum: No such file or directory
```

### Tests written?

No (but will try)

### Commits signed with GPG?

Yes

2020-01-21 22:28 UTC, waynew commented
Hey @giany thanks for the PR!

We require tests for all new code/fixes - would you be able to add some tests for this? A good place to add them would be to `tests/unit/modules/test_yumpkg.py`. For a change like this, I think it would be enough to just have a test that does a mock.patch_dict on `__grains__`. Probably two tests, one that checks centos >7, and one that tests <=7 and ensure that `_yum` correctly returns `yum` or `dnf`.

If you want to go ahead and add some tests for the Fedora branch, that would be A-OK, but otherwise at least those couple of tests would be most excellent.

You should be able to safely ignore the two existing failures - one is due to a known flakiness that we're addressing, and the other was due to a timeout which shouldn't be related to this code.

If you're unable/unwilling to write the tests, please just let us know so we can mark that this just needs some tests written.

Thanks again!

2020-01-22 12:44 UTC, giany commented
I can give a try @waynew . Any idea how to test locally these tests? Can't find proper documentation related to this.

2020-01-22 16:20 UTC, waynew commented
The tests are currently in flux, so documentation *is* a bit spotty right now. If you haven't ever tested salt locally, the *easiest* way to do so, if you have a good Internet connection, involves pulling down a Docker image that I've created.

I use fish shell with the following function:

```
function saltt
	docker run --rm -it -v "$PWD/salt":/usr/lib/python2.7/dist-packages/salt -v "$PWD/salt":/usr/local/lib64/python3.6/site-packages/salt -e LANG=en_US.UTF-8 -v "$PWD":/testing $argv
end
```

But you could easily create a bash alias like:

    $ alias saltt='docker run --rm -it -v "$PWD/salt":/usr/lib/python2.7/dist-packages/salt -v "$PWD/salt":/usr/local/lib64/python3.6/site-packages/salt -e LANG=en_US.UTF-8 -v  "$PWD":/testing'

Then I would run these tests like so:

    saltt waynew/salt-sprints nox -e 'pytest-zeromq-3(coverage=False)' -- tests/unit/modules/test_yumpkg.py; say "done with test"

(waynew/salt-sprints is the Docker image, IIRC it's ~1.3GB in size, because it starts with Centos7 and bundles salt master/minion and all of its dependencies)

If you need any other help, feel free to hit me up - waynew in #salt on [freenode](https://webchat.freenode.net/#salt), or on the Salt community Slack.

HTH!

2020-03-10 21:53 UTC, waynew commented
@giany any progress here?

2020-03-18 21:37 UTC, waynew requested changes
@giany are you still interested in writing tests and getting this PR completed?

2020-04-13 12:49 UTC, greut commented on salt/modules/yumpkg.py
> +           and int(__grains__['osrelease'].split('.')[0]) > 7):
greater than matches how it's done with Fedora.

```suggestion
           and int(__grains__['osrelease'].split('.')[0]) >= 8):
```

2020-04-13 12:51 UTC, greut commented
@waynew I've taken a look at the test file and it looks like the tests are worse than the code itself, and at the end of the day not testing anything but mocks.

2020-04-15 05:34 UTC, greut commented
@waynew It seems that this PR may be closed, https://github.com/saltstack/salt/pull/56355

Thanks!

2020-04-15 11:40 UTC, DmitryKuzmenko commented
@greut Thanks for pointing on that.
This one is replaced with #56355. Closing.

2020-04-15 11:40 UTC, closed without merging