Master-port #49860 selinux support for file.manage
saltstack/salt pull request #55922
Opened 2020-01-21 06:59 UTC by mchugh19

Master port of #42060 
This looks good to me, but happy to get more eyes on it. See conversation in #42060  for more information

### What does this PR do?
Recursion not supported for persist=True on file.get_selinux_context execution module

Add selinux functionality to file.managed
```
/tmp/selinux.test
  file.managed:
    - user: root
    - selinux:
        seuser:  system_u
        serole: object_r
        setype: system_conf_t
        seranage: s0
```
```
# salt-call --local state.sls selinux test=True
local:
----------
          ID: check_selinux
    Function: file.managed
        Name: /tmp/selinux.test
      Result: None
     Comment: File /tmp/selinux.test not updated
     Started: 10:54:39.418112
    Duration: 17.911 ms
     Changes:
              ----------
              selinux context:
                  ----------
                  New:
                      User: system_u Type: system_conf_t
                  Old:
                      User: unconfined_u Type: user_tmp_t

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  17.911 ms
```

### What issues does this PR fix or reference?
#40703 and possibly #1349

### New Behavior
Uses file.get_selinux_context and file.set_selinux_context to determine if selinux updates are needed. As mentioned in a ticket #1349, set_selinux_context uses the chcon command, which might not be persistent. Feedback welcome.

### Tests written?
Yes - but could always use more eyes

2020-03-12 15:05 UTC, twangboy requested changes

2020-03-12 15:05 UTC, twangboy commented on salt/modules/file.py
> +    .. versionchanged:: Neon
Sodium

2020-03-12 15:05 UTC, twangboy commented on salt/modules/file.py
> +    .. versionchanged:: Neon
Sodium

2020-03-12 15:05 UTC, twangboy commented on salt/modules/file.py
> +        .. versionadded:: Neon
These should all be Sodium

2020-03-12 15:05 UTC, twangboy commented on salt/modules/file.py
> +
Sodium

2020-03-12 15:05 UTC, twangboy commented on salt/states/file.py
> +        .. versionadded:: Neon
Sodium

2020-03-13 07:06 UTC, mchugh19 commented on salt/modules/file.py
> +    # after = _sed_esc(after, escape_all)
I'm not responsible for the commented code, or the comment. But I've removed the dead code as suggested.

2020-03-13 07:06 UTC, mchugh19 commented on salt/modules/file.py
> +    .. versionchanged:: Neon
Done

2020-03-13 07:06 UTC, mchugh19 commented on salt/modules/file.py
> +    .. versionchanged:: Neon
Done

2020-03-13 07:06 UTC, mchugh19 commented on salt/modules/file.py
> +        .. versionadded:: Neon
Done

2020-03-13 07:06 UTC, mchugh19 commented on salt/modules/file.py
> +
Done

2020-03-13 07:06 UTC, mchugh19 commented on salt/states/file.py
> +        .. versionadded:: Neon
Done

2020-04-01 18:00 UTC, twangboy submitted a review, later dismissed

2020-04-15 20:57 UTC, twangboy commented
Hey, @mchugh19 

Looks like this needs to be rebased and have pre-commit run on it. Do you mind doing that?

https://docs.saltstack.com/en/latest/topics/development/contributing.html#quickstart

2020-04-16 08:46 UTC, mchugh19 commented
@twangboy 
> Looks like this needs to be rebased and have pre-commit run on it. Do you mind doing that?

I'm not sure what you mean. These files have been run through isort and black already. I tried manually running `pre-commit run --files filenames` but there weren't any changes. and there don't appear to be any conflicts with master. What needs rebasing?

2020-04-17 17:05 UTC, waynew commented
I'm not sure either 😂 

Pre-commit looks fine and is passing, but there are some other failures that look to be related to this PR. Can you take a look?

2020-04-18 05:51 UTC, mchugh19 commented
tests were missing a `cmd.run_all` mapping. Not sure how it ever worked before, or why it only failed on centos (maybe selinux is only enabled on redhat?). Should be good to go now though.

2020-04-18 19:05 UTC, mchugh19 commented
re-run pr-windows2019-py3

2020-04-18 19:05 UTC, mchugh19 commented
re-run pr-windows2016-py3

2020-04-22 05:50 UTC, mchugh19 commented
re-run pr-centos7-py3

2020-04-23 04:59 UTC, mchugh19 commented
Ugh. Centos is stuck on 
```
File "/tmp/kitchen/testing/tests/integration/states/test_docker_network.py", line 133, in tearDownClass
    if process.returncode != 0 and "No such image" not in output:
TypeError: a bytes-like object is required, not 'str'
```

2020-04-24 02:07 UTC, dwoz approved these changes

2020-04-24 02:07 UTC, merged