Fix etcd cache
saltstack/salt pull request #56001
Opened 2020-01-28 10:50 UTC by malletp

### What does this PR do?

Fix ls function of etcd cache and improve performance when etcd cache is used with many minions.

### What issues does this PR fix or reference?

#55305
#55988

### Previous Behavior
Error message like
'''
SaltCacheError: There was an error reading the key, /salt_cache/minions/minion_id/mine/data: Not a directory : /salt_cache/minions/minion_id/mine
'''

Filtering minions with grains/pillar takes time when etcd cache is used with many minions.

### New Behavior

Error fixed and performance improved.

### Tests written?

No

### Commits signed with GPG?

Yes

2020-03-27 13:41 UTC, DmitryKuzmenko requested changes

2020-03-27 13:41 UTC, DmitryKuzmenko commented on salt/cache/etcd_cache.py
> +            for leave in data.leaves:
Could you please change `leave` to `leaf`?

2020-03-31 08:22 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-03-31 08:23 UTC, DmitryKuzmenko commented
@malletp i've fixed the typo, don't care about that.
Are you able to write a test for your change please?

2020-04-01 11:40 UTC, DmitryKuzmenko commented
@malletp also sorry I've missed the key point: please switch this PR to target to the `master` branch.

2020-04-13 21:40 UTC, DmitryKuzmenko commented
@malletp Could you please update your PR onto the top of master branch and run the pre-commit script on your code to re-format it with `isort` and `black` we're using now.
```
pip install pre-commit
pre-commit install
FILES="$(git show --pretty="" --name-only master..HEAD)"
pre-commit run isort $FILES
pre-commit run black $FILES
```
next time you'll commit it will be ran automatically.

2020-04-14 14:10 UTC, malletp commented
@DmitryKuzmenko, thanks' for the fix. 
Regarding the test, I don't find any existing test for the different supported cache module, and I have no idea how to add it.
And regarding the branch, I try to update the PR this week.

2020-04-14 23:53 UTC, DmitryKuzmenko commented
@malletp thank you! Let's rebase this to the master as a first step then we'll check what to do with the tests. It should be pretty simple since we already have some cache unit tests.

2020-04-15 15:01 UTC, DmitryKuzmenko commented
@malletp I'm sorry if it wasn't clear. It's not enough to just change the target branch. You have to rebase your commits to master locally using `git rebase -i --onto master 2018.3 fix-etcd-cache`. This command will rebase the only your commits to the top of master.
After that please install and run the pre-commit hook as I suggested. This will make your code clean.

2021-01-14 13:57 UTC, Ch3LL requested changes
Can you add test coverage for this change?

2022-03-09 21:24 UTC, Ch3LL commented
@malletp did you see my review comments? Also there is a merge conflict and failing tests.

2022-11-09 21:24 UTC, Ch3LL commented
any interest in pushing this PR to completion @malletp ?

2022-11-28 20:07 UTC, Ch3LL commented
Closing due to inactivity. Please let me know if you want me to re-open or please submit a PR against the master branch with the requested changes.

2022-11-28 20:07 UTC, closed without merging