Do not allow msgpack 1.0.0rc1
saltstack/salt pull request #56009
Opened 2020-01-28 18:15 UTC by dwoz

This pins msgpack to lower than 1.0.0 until we can address #56007

### Tests written?

No

### Commits signed with GPG?

Yes

2020-01-28 18:17 UTC, s0undt3ch approved these changes

2020-01-28 18:19 UTC, garethgreenaway approved these changes

2020-01-28 18:47 UTC, waynew approved these changes

2020-01-28 19:31 UTC, twangboy approved these changes

2020-01-28 19:31 UTC, twangboy requested changes
Probably need to update the seperate osx and windows req files. Nope, looks like they're pinned to 0.5.6

2020-01-28 19:32 UTC, twangboy approved these changes

2020-01-28 21:40 UTC, merged

2020-02-21 22:09 UTC, prometheanfire commented
when can this be reverted?

2020-02-25 09:17 UTC, s0undt3ch commented
@prometheanfire, when we fix our code to support 1.0.0, but why?

2020-02-25 16:44 UTC, prometheanfire commented
because the cap prevents salt from being co-installed with other things that require msgpack.  The world does not consist of only salt.