Update to python 3.7 - Remove Py2
saltstack/salt pull request #56077
Opened 2020-02-06 00:28 UTC by twangboy

### What does this PR do?
Updates Windows installer scripts to use Python 3.7.4 as the version of python to be bundled for Windows. Removes references to Python 2. Updates a few dependencies required by Python 3.7.

### Previous Behavior
Python 2.7.15 and Python 3.5.4

### New Behavior
Python 3.7.4

### Tests written?
No

### Commits signed with GPG?
Yes

2020-02-06 12:58 UTC, s0undt3ch submitted a review, later dismissed

2020-02-07 10:32 UTC, dwoz requested changes
Please separate this into two PRs. One for the python3 change and one for the python2 change.

2020-04-14 15:55 UTC, markuskramerIgitt commented
### Regarding salt/version.py 
Hi @twangboy  please replace commit 

    Update msi_conformant_version for 3000  6837d07

by the commits of https://github.com/saltstack/salt/pull/56352/commits

- The function `msi_conformant_version()` should be removed
- This should resolve the version.py conflicts

2020-04-14 15:59 UTC, marbx requested changes
Same comment as in https://github.com/saltstack/salt/pull/56120

### Regarding salt/version.py 
Hi @twangboy  please replace commit 

    Update msi_conformant_version for 3000  6837d07

by the commits of https://github.com/saltstack/salt/pull/56352/commits

- The function `msi_conformant_version()` should be removed
- This should resolve the version.py conflicts

2020-04-14 17:00 UTC, markuskramerIgitt commented on pkg/windows/req.txt
> -enum34==1.1.6
Nice cleanup

2020-04-29 13:40 UTC, Ch3LL submitted a review, later dismissed

2020-05-04 08:20 UTC, dwoz submitted a review, later dismissed

2020-05-04 08:21 UTC, dwoz commented
@twangboy we've got conflicts again.

2020-05-04 21:25 UTC, twangboy commented
@dwoz Fixed conflicts

2020-05-05 21:29 UTC, merged