Remove python2
saltstack/salt pull request #56120
Opened 2020-02-11 00:13 UTC by twangboy

### What does this PR do?
Remove Python2 from the build scripts

2020-04-14 15:57 UTC, marbx requested changes
### Regarding salt/version.py 
Hi @twangboy  please replace commit 

    Update msi_conformant_version for 3000  6837d07

by the commits of https://github.com/saltstack/salt/pull/56352/commits

- The function `msi_conformant_version()` should be removed
- This should resolve the version.py conflicts

2020-04-26 04:56 UTC, dwoz commented
> ### Regarding salt/version.py
> Hi @twangboy please replace commit
> 
> ```
> Update msi_conformant_version for 3000  6837d07
> ```
> 
> by the commits of https://github.com/saltstack/salt/pull/56352/commits
> 
> * The function `msi_conformant_version()` should be removed
> * This should resolve the version.py conflicts

@twangboy Has this been addressed?

2020-04-29 22:03 UTC, twangboy commented
@dwoz Yeah, his PR has been merged. Conflicts resolved here. The offending method has been removed.

2020-05-04 08:19 UTC, dwoz approved these changes

2020-05-04 08:19 UTC, merged