[WIP] Fix for unless requisite when pip is not installed
saltstack/salt pull request #56215
Opened 2020-02-20 21:08 UTC by dwoz

### What does this PR do?

Fix for #56131

### What issues does this PR fix or reference?

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes/No

### Commits signed with GPG?

Yes

2020-02-26 14:31 UTC, Ch3LL requested changes

2020-02-26 14:31 UTC, Ch3LL commented on tests/integration/modules/test_state.py
> +        print('*' * 80)
do we want to keep these prints here?

2020-03-01 13:58 UTC, max-arnold commented
@dwoz I believe this line should start with `if` (not `or`), otherwise it will iterate and delete all modules:

https://github.com/saltstack/salt/blob/1746e6ac60d1b6f9f2d3cb372e043d2aad66fcc0/salt/states/pip_state.py#L54

2020-03-10 23:43 UTC, dwoz commented
> @dwoz I believe this line should start with `if` (not `or`), otherwise it will iterate and delete all modules:
> 
> https://github.com/saltstack/salt/blob/1746e6ac60d1b6f9f2d3cb372e043d2aad66fcc0/salt/states/pip_state.py#L54

Good catch, thanks!

2020-03-10 23:43 UTC, dwoz commented on tests/integration/modules/test_state.py
> +        print('*' * 80)
Nope, will resolve this

2020-03-11 13:46 UTC, Ch3LL approved these changes

2020-03-11 13:47 UTC, Ch3LL commented
looks like there are some lint failures that need to be cleaned up

2020-03-11 14:39 UTC, DmitryKuzmenko approved these changes

2020-03-11 16:45 UTC, waynew approved these changes

2020-03-11 22:04 UTC, merged