Changed StrictVersion checking of setuptools to LooseVersion
saltstack/salt pull request #56218
Opened 2020-02-21 05:11 UTC by raddessi

### What does this PR do?
Fixes an installation issue in conda envs

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/56184

### Previous Behavior
Install doesnt work

### New Behavior
Install works

### Tests written?
No

### Commits signed with GPG?
No... I know I should know better it's on my list

2020-02-26 14:23 UTC, Ch3LL approved these changes

2020-02-26 14:25 UTC, Ch3LL requested changes

2020-02-26 14:25 UTC, Ch3LL commented on setup.py
>          from distutils.version import StrictVersion
actually would you mind removing this import, looks like it wont be used anymore.

2020-02-26 14:27 UTC, s0undt3ch requested changes
As Megan pointed out. Let's remove the unused import.

2020-02-26 14:30 UTC, raddessi commented
Oh nice, i didnt catch that. Will do

Hey should i open a separate issue asking about if you all are open to setting up black/precommit to auto format and check for stuff like this automatically?

Sent from ProtonMail mobile

-------- Original Message --------
On Feb 26, 2020, 7:27 AM, Pedro Algarvio wrote:

> @s0undt3ch requested changes on this pull request.
>
> As Megan pointed out. Let's remove the unused import.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/saltstack/salt/pull/56218?email_source=notifications&email_token=ABTCBHXNQEUEHG4F2OAUVITREZ33ZA5CNFSM4KY4NR62YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXAI4ZY#pullrequestreview-364940903), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ABTCBHXAB3647TJXLK2TIELREZ33ZANCNFSM4KY4NR6Q).

2020-02-26 14:32 UTC, s0undt3ch commented
We will `black`en salt as soon as we start merging into master.
Lint should have caught this but we might have disabled the check somewhere.

2020-02-26 18:35 UTC, raddessi commented
Will 3000.1 be the first merge to master?

2020-02-26 21:35 UTC, s0undt3ch approved these changes

2020-02-26 21:36 UTC, Ch3LL approved these changes

2020-02-26 21:37 UTC, Ch3LL commented
> Will 3000.1 be the first merge to master?

I'm not sure what you are asking? 3000.1 release will be tagged from the master branch if that is what you are asking.

2020-02-26 21:40 UTC, raddessi commented
Ah sorry I thought you all were going to do a mass merge of all the items marked for 3000.1 and then tag it, I must misunderstand something, I'll re read the new merge strategy doc. Thanks again

2020-02-26 21:44 UTC, Ch3LL commented
Oh no worries, i think i just misunderstood the question. This is the project board we are using to track what issues need to get in for 3000.1, looks like your issue is under commit, so looks like we will get this one in :)

2020-02-26 21:45 UTC, Ch3LL commented
errr sometimes it helps to include links you refer to lol https://github.com/saltstack/salt/projects/8

2020-02-26 21:47 UTC, raddessi commented
Totally, I got what you meant. Yes that was the board I was thinking of also :) thanks

2020-03-10 23:59 UTC, dwoz approved these changes

2020-03-10 23:59 UTC, merged