config.option returns empty string not None
saltstack/salt pull request #56220
Opened 2020-02-21 11:23 UTC by mirceaulinic

``__salt__['config.option']`` can never return `None`:

```bash
# salt tgt config.option fake --out=raw
{u'tgt': u''}
```

Therefore, those statements are never evaluated, which
results in surprising behaviour and wasted hours of debugging.

2020-03-05 21:45 UTC, twangboy approved these changes

2020-03-12 15:48 UTC, dhiltonp commented on salt/modules/s3.py
>      if path_style is None:
There is another of these checks 3 lines down, that should also be included!

2020-03-12 15:50 UTC, dhiltonp requested changes
This looks good.

I did a quick check through the rest of the code base and we seem fine, except for one more occurrence just a few lines down!

2023-12-10 07:39 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 07:39 UTC, closed without merging