Fix deprecation warnings for imports from collections
saltstack/salt pull request #56225
Opened 2020-02-21 13:06 UTC by bdrung

DeprecationWarning: Using or importing the ABCs from `collections` instead of from `collections.abc` is deprecated since Python 3.3, and in 3.9 it will stop working.

Therefore try to import the abstract base classes from `collections.abc` before falling back to `collections`.

2020-02-22 10:21 UTC, mchugh19 commented
This looks to be a superset of #55900

2020-02-22 11:51 UTC, bdrung commented
Right. I wasn't aware that there is already a similar pull request. I just grepped for `DeprecationWarning` in the unit test output and fixed all occurrences.

2020-03-05 21:39 UTC, twangboy submitted a review, later dismissed

2020-03-27 14:04 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-03-31 16:34 UTC, DmitryKuzmenko commented
re-run full ubuntu1604-py3-pycryptodomex
re-run full centos7-py2-tornado
re-run full centos7-py2
re-run full amazon2-py2

2020-04-07 00:26 UTC, DmitryKuzmenko commented
@bdrung could you please resolve merge conflicts?

2020-04-15 19:08 UTC, Ch3LL commented
ping @DmitryKuzmenko and @twangboy looks like this is waiting on your approval

2020-04-22 21:26 UTC, DmitryKuzmenko requested changes
I'm sorry for later response and for asking you for another one change. This probably wasn't officially introduced but `salt/ext` contains foreign code that we're keeping as close to the original as possible to don't have much troubles updating it. So could you please revert or rebase dropping your last commit e1f57d6207ba4e6d30f9d7c69c52398dc98065ca that is blacking the `salt/ext/tornado/httputil.py`.
Just leave your `collections` rfelated` changes there.
Thank you for understanding.

2020-04-22 22:48 UTC, twangboy submitted a review, later dismissed

2020-04-24 07:58 UTC, bdrung commented
I removed e1f57d6 and rebased the branch to fix the merge conflicts. Expect some linter checks to fail after this removal.

2020-04-24 19:15 UTC, merged