Force bytestrings to string in tomcat module
saltstack/salt pull request #56270
Opened 2020-02-28 11:27 UTC by sabtom

### What does this PR do?
This PR fixes the issue #56269 
It converts the byte strings into strings before using it elsewhere in the module.

### What issues does this PR fix or reference?
#56269 

### Tests written?
No, current tests should still be adequate/behave the same

### Commits signed with GPG?
No

2020-02-28 12:14 UTC, sabtom commented
FYI, just checked the linter fails, because some dependencies arent installed:
``` bash
12:11:44  Command pylint --rcfile=.pylintrc --disable=I setup.py noxfile.py salt/ failed with exit code 2
12:11:44  ************* Module salt.returners.django_return
12:11:44  salt/returners/django_return.py:42: [E0611(no-name-in-module), ] No name 'dispatch' in module 'django'
```

2020-02-28 13:47 UTC, sabtom commented
Also checked why the macosxmojave failed, but that's also seems to be because of missing dependencies:
```
13:39:12            -> unit.beacons.test_twilio_txt_msg.TwilioMsgTxtBeaconTestCase.test_receive_message                                                                                                                                                                                      ->  twilio.rest is not available
13:39:12            -> unit.beacons.test_twilio_txt_msg.TwilioMsgTxtBeaconTestCase.test_validate_dictionary_config                                                                                                                                                                           ->  twilio.rest is not available
13:39:12            -> unit.beacons.test_twilio_txt_msg.TwilioMsgTxtBeaconTestCase.test_validate_empty_config                                                                                                                                                                                ->  twilio.rest is not available
13:39:12            -> unit.beacons.test_twilio_txt_msg.TwilioMsgTxtBeaconTestCase.test_validate_missing_config_item                                                                                                                                                                         ->  twilio.rest is not available
```

2020-03-05 21:25 UTC, twangboy submitted a review, later dismissed

2020-03-05 21:29 UTC, twangboy commented
@sabtom Tests need to be written to address this issue so it doesn't regress. Since it wasn't caught by current tests, we need to make sure we would catch this in the future.

2020-03-06 09:42 UTC, sabtom commented
@twangboy Apparently there didn't exists a unittest for module/tomcat yet, so added it.  
Don't really have time to spend to test all methods, but have added a test that will fail when a bytestring is returned by the _wget method of the tomcat module.

2020-03-10 13:38 UTC, sabtom commented
Hmm all tests seem to fail on the zcbuildout module, but haven't touched that one.
```
09:40:12          -----------------------------------------------------------------------------------------------------------------------
09:40:12          --------  Tests with Errors  ------------------------------------------------------------------------------------------
09:40:12            -> setUpClass (unit.modules.test_zcbuildout.BuildoutOnlineTestCase)  ................................................
09:40:12         Traceback (most recent call last):
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 353, in setUpClass
09:40:12             super(BuildoutOnlineTestCase, cls).setUpClass()
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 91, in setUpClass
09:40:12             download_to(url, dest)
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 61, in download_to
09:40:12             fic.write(urlopen(url, timeout=10).read())
09:40:12           File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
09:40:12             return opener.open(url, data, timeout)
09:40:12         AttributeError: 'bool' object has no attribute 'open'
09:40:12            .....................................................................................................................
09:40:12            -> setUpClass (unit.modules.test_zcbuildout.BuildoutTestCase)  ......................................................
09:40:12         Traceback (most recent call last):
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 91, in setUpClass
09:40:12             download_to(url, dest)
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 61, in download_to
09:40:12             fic.write(urlopen(url, timeout=10).read())
09:40:12           File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
09:40:12             return opener.open(url, data, timeout)
09:40:12         AttributeError: 'bool' object has no attribute 'open'
09:40:12            .....................................................................................................................
09:40:12            -> setUpClass (unit.states.test_zcbuildout.BuildoutTestCase)  .......................................................
09:40:12         Traceback (most recent call last):
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 91, in setUpClass
09:40:12             download_to(url, dest)
09:40:12           File "/tmp/kitchen/testing/tests/unit/modules/test_zcbuildout.py", line 61, in download_to
09:40:12             fic.write(urlopen(url, timeout=10).read())
09:40:12           File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
09:40:12             return opener.open(url, data, timeout)
09:40:12         AttributeError: 'bool' object has no attribute 'open'
09:40:12            .....................................................................................................................
09:40:12          -----------------------------------------------------------------------------------------------------------------------
09:40:12         ========================================================================================================================
09:40:12         FAILED (total=10532, skipped=1430, passed=9099, failures=0, errors=3) 
09:40:12         ================================================  Overall Tests Report  ================================================
```

2020-04-06 10:39 UTC, DmitryKuzmenko requested changes

2020-04-06 10:39 UTC, DmitryKuzmenko commented on salt/modules/tomcat.py
> +            ret['msg'][key] = item.decode('utf-8')
Could you please use `salt.utils.stringutils.to_unicode` instead?

2020-04-06 23:47 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-04-06 23:50 UTC, DmitryKuzmenko commented
@sabtom could you please resolve the merge conflicts?

2020-04-12 06:11 UTC, dwoz commented
@sabtom Maybe try re-basing this on top of the current master and running black as a part of the pre-commit. Hopefully that'll resolve the weird test failures.

2020-04-15 14:04 UTC, DmitryKuzmenko requested changes
Please update the test to not return `True` from the `tomcat._auth` module function.

2020-04-15 14:04 UTC, DmitryKuzmenko commented on tests/unit/modules/test_tomcat.py
> +        with patch("salt.modules.tomcat._auth", MagicMock(return_value=True)):
Here is what is breaking the zcbuildout tests.
The `_auth` function in tomcat module either returns `False` that makes the underlying `_wget` to return an error or returns an `opener` that is being directly installed as a default opener to urllib that breaks urllib for further calls.

2020-04-20 10:59 UTC, DmitryKuzmenko commented
@sabtom thank you! Now it should be good!

2020-04-22 19:14 UTC, dwoz approved these changes

2020-04-22 19:15 UTC, merged