Allow skipping test cases that need Internet access
saltstack/salt pull request #56280
Opened 2020-03-02 12:10 UTC by bdrung

Mark test cases that need Internet access and allow skipping them by setting the environment variable `NO_INTERNET`.

2020-03-05 21:20 UTC, twangboy submitted a review, later dismissed

2020-03-17 14:37 UTC, frogunder submitted a review, later dismissed

2020-03-26 14:50 UTC, frogunder commented
@bdrung seems like there is a conflict here, can you take a look?

Thanks.

2020-03-26 16:31 UTC, bdrung commented
Rebased and resolved the conflict.

2020-04-03 00:28 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-04-11 05:17 UTC, dwoz requested changes
I'd prefer we try to detect if we have internet access and then skip the tests automatically. It's a more holistic approach IMO.

2020-04-14 13:44 UTC, bdrung commented
For our use-case (reproducible running tests), we want to disable all tests that need Internet access – regardless if the system has actually Internet access or not. On some buildsystems pip is configured to work locally. So a Internet check could be tricked to assume Internet is there, but pip would fail.

2020-04-21 16:29 UTC, frogunder commented
@dwoz Is this one good now?

2020-04-22 08:48 UTC, bdrung commented
Rebased the merge request on master and resolved the merged conflicts.

2020-04-22 20:56 UTC, dwoz approved these changes

2020-04-22 20:56 UTC, merged