On start, update git_pillar on second loop
saltstack/salt pull request #56316
Opened 2020-03-06 10:56 UTC by sathieu

### What does this PR do?

Before this patch, the master would wait `git_pillar_update_interval` before doing the first update. When this setting is big (we set it to one week at work), this can lead to unfetched repositories.

### What issues does this PR fix or reference?

PR #53621

### Previous Behavior
The first `git_pillar` update would run at _start time_ + `git_pillar_update_interval`.

### New Behavior
The first git_pillar update would run at _start time_ + `loop_interval`.

### Tests written?

No

### Commits signed with GPG?

No

2020-03-06 10:59 UTC, sathieu commented on salt/master.py
> +        last_git_pillar_update = last - git_pillar_update_interval + self.loop_interval
Alternatively, we can set `last_git_pillar_update = 0`, i.e. update `git_pillar` on first loop.

- Pros: code is simpler
- Cons: Higher load on start?

2020-03-09 16:44 UTC, Ch3LL commented
can we get an associated issue open alongside this PR, so its clear what issue we are fixing and in case anyone else is running into the issue its easily discoverable?

2020-03-11 14:44 UTC, sathieu commented
@Ch3LL Issue created: #56356.

2020-03-12 21:18 UTC, Ch3LL requested changes
any chance we can get a test case here to ensure it does not regress in the future?

2020-04-03 08:58 UTC, sathieu commented
@Ch3LL I have no idea of how to test this.

2020-04-08 15:00 UTC, Ch3LL commented
I would suggest a unit test here `tests/unit/test_master.py` and add a new test ckass for the maintenance class and add a test for the run function with `git_pillar_update_interval` set to different values.

2020-05-05 21:51 UTC, xeacott commented
Hey @sathieu any follow up on this? I can help you write a test if you need for this PR. 😄

2020-05-14 19:20 UTC, sathieu commented
@xeacott Yes, please help me with a test.

2020-05-14 20:24 UTC, sathieu commented
> I would suggest a unit test here `tests/unit/test_master.py` and add a new test ckass for the maintenance class and add a test for the run function with `git_pillar_update_interval` set to different values.

@Ch3LL OK but how to escape the `while True` loop?

2020-05-20 18:29 UTC, xeacott commented
I would suggest something like this to get you started...
```
class MaintenanceTestCase(TestCase, AdaptedConfigurationTestCaseMixin):
    """
    TestCase for salt.master.Maintenance class
    """

    def setUp(self):
        self.opts = salt.config.master_config(None)
        self.main_class = salt.master.Maintenance(self.opts)

    def tearDown(self):
        del self.main_class

    def test_run_func(self):
        """
        Test the run function inside Maintenance class.
        """
        with patch("salt.utils.process", autospec=True):
            with patch("salt.master", autospec=True):
                self.main_class.run()

```

2020-05-28 12:52 UTC, sathieu commented
@Ch3LL Please review again. There are (passing :smile:) tests now!

2020-05-28 12:57 UTC, sathieu commented
Also @xeacott please review ...

2020-05-29 19:15 UTC, xeacott commented
Oh yes will do, thanks for writing those tests!

2020-05-29 19:36 UTC, waynew submitted a review, later dismissed
@xeacott Tests look good to me - I'd double check the docs to make sure we don't specify a different behavior (I'm guessing not).

2020-05-29 19:45 UTC, xeacott submitted a review, later dismissed

2020-08-05 13:32 UTC, Ch3LL submitted a review, later dismissed

2020-08-26 07:21 UTC, sathieu commented
@xeacott  You've marked this PR *Merge Ready*. I've now rebased and fixed `pre-commit` and `Pylint`. Hope you merge it now ...

2020-09-09 19:57 UTC, Ch3LL approved these changes

2020-09-09 20:30 UTC, merged