add -r support to setup.py
saltstack/salt pull request #56335
Opened 2020-03-09 21:23 UTC by cmcmarrow

### What does this PR do?
lets salt-bin run

### New Behavior
"-r <file>" is now ran in setup.py

### Tests written?
no

### Commits signed with GPG?
Yes

2020-03-09 21:32 UTC, Akm0d submitted a review, later dismissed

2020-03-09 21:34 UTC, xeacott submitted a review, later dismissed

2020-03-09 21:35 UTC, dmurphy18 reviewed
Worried that fixing this issue for 3000.1 will change current mode of operation (even if it is wrong) and now building will have a slew of new requirements appear, similar to what happened with the change from distutils to setuptools in 3000.  Perhaps this would be better postponed till Sodium.  But open to persuasion on the matter

2020-03-09 22:34 UTC, s0undt3ch reviewed
I would advise against merging this for 3000.1

There's an open PR which fixes the requirements for 3000.1 in a less intrusive way.

https://github.com/saltstack/salt/pull/56099

For Sodium, as long as the packaging is not broken, I'm ok with this change.

2020-03-09 22:56 UTC, cmcmarrow commented
Windows and Apple are the only two that have -r from what I can see. The normal Windows installer catches all missing modules that this catches. The only place I can see go wrong is Apple and that's just because I don't know how the processes.

2020-03-09 23:06 UTC, twangboy requested changes

2020-03-09 23:06 UTC, twangboy commented on setup.py
> +            if not line or line.startswith('-r'):
Would `not line` ever be evaluated here considering the if statement above?

2020-04-06 10:52 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-04-30 09:33 UTC, s0undt3ch commented
This is superseded by https://github.com/saltstack/salt/pull/56904

2020-05-09 12:52 UTC, DmitryKuzmenko commented
@s0undt3ch maybe close it then?

2020-05-09 13:39 UTC, s0undt3ch commented
It will get closed when the linked PR is merged.

2020-05-15 20:52 UTC, DmitryKuzmenko commented
Hm... So this one or #56904?

2020-05-15 20:52 UTC, DmitryKuzmenko commented
@s0undt3ch ^^^

2020-05-15 20:57 UTC, DmitryKuzmenko commented
Just checked this part in #56904 it also handles an inline hash-comments.
I'd better like #56904

2020-05-15 21:25 UTC, Akm0d approved these changes

2020-05-15 21:29 UTC, dmurphy18 approved these changes

2020-05-15 21:54 UTC, s0undt3ch commented
None for Sodium.
If the issue is salt-bin, we'll address it when building(again for Sodium).

2020-05-16 03:23 UTC, DmitryKuzmenko approved these changes

2020-05-16 08:20 UTC, cmcmarrow commented
@s0undt3ch the PR is open due to salt-bin.

2020-09-30 12:26 UTC, closed without merging