Fixes AzureRM create_object_model util
saltstack/salt pull request #56379
Opened 2020-03-14 16:23 UTC by Ajnbro

### What does this PR do?
This PR fixes the Microsoft Azure Resource Manager create_object_model util. Currently, the util is not properly building some object models. The issue is caused by the util improperly handling the existence of parameters because it does not account for the existence of parameters that are set as Boolean values (specially False). 

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Object models with parameters that may have contained Boolean values (specially False) were being built improperly. 

### New Behavior
Object models with parameters that may contain Boolean values (specially False) are being built properly. 

### Tests written?
No

### Commits signed with GPG?
Yes

2020-03-16 20:25 UTC, Ch3LL requested changes
can we get some tests added here? and can you create an issue with details of the issue and tie it to this PR, to make it easier for others running into the issue to see it.

2020-03-17 17:55 UTC, nicholasmhughes commented
@Ch3LL test case added. This issue was actually something that we ran into in Idem, but also could apply to Salt... we just don't have any concrete errors to report.

2020-03-18 14:49 UTC, Ch3LL submitted a review, later dismissed

2020-04-14 18:12 UTC, dwoz commented
Merge conflicts need to be resolved.

2020-04-15 13:59 UTC, Ch3LL approved these changes

2020-04-15 18:44 UTC, merged