Update issue and PR templates, add config
saltstack/salt pull request #56485
Opened 2020-03-31 02:56 UTC by sagetherage

### What does this PR do?
Uses GitHub templates for [Bug] and [Feature Request] adds labels, easier to find by syntax search, adds syntax to PR template `Fixes:` to close issues linked with PRs as stated in the Contributing Guidelines, plus adds a config file with links for questions and discussions.

### What issues does this PR fix or reference?
Fixes: #55853

### Tests written?
No

### Commits signed with GPG?
Yes

2020-03-31 03:10 UTC, waynew requested changes
Found a missing `e` :upside_down_face:

2020-03-31 03:10 UTC, waynew commented on .github/ISSUE_TEMPLATE/config.yml
> +     - name: Salt on Freenod
```suggestion
     - name: Salt on Freenode
```

2020-03-31 19:35 UTC, Ch3LL submitted a review, later dismissed

2020-03-31 20:22 UTC, sagetherage commented on .github/ISSUE_TEMPLATE/config.yml
> +     - name: Salt on Freenod
@waynew ok all fixed thank you!

2020-04-03 06:38 UTC, max-arnold commented
May I suggest adding the following snippet to the versions report section to make it collapsed by default?

    <details><summary>salt --versions-report</summary>
    
    ```
    PASTE HERE
    ```
    </details>

Another suggestion is to consider adding the `Docs & changelog written?` section to the PR template (in order to improve the docs coverage).

2020-04-03 21:29 UTC, bryceml commented
https://github.com/saltstack/salt/pull/56075

could probably be taken care of on this pr and that one closed.

2020-04-03 21:40 UTC, sagetherage commented
I guess I decided @dwoz when you review this for merging, please comment.

2020-04-06 22:30 UTC, waynew requested changes
I think this will render the GFM checkbox?

2020-04-06 22:30 UTC, waynew commented on .github/PULL_REQUEST_TEMPLATE.md
> +
Maybe do:

```suggestion
- [ ] Docs
- [ ] Changelog

```

2020-04-07 16:23 UTC, waynew approved these changes

2020-04-10 17:01 UTC, merged