Pending reboot
saltstack/salt pull request #56489
Opened 2020-03-31 20:31 UTC by twangboy

### What does this PR do?
Adds a new `pending_reboot` grain for Windows systems.

This moves code from many functions in the `salt.modules.win_system` execution module to a new `salt.utils.win_system` salt util. This code used by the new grain to determine if the system needs to be rebooted and must be available on minion start.

### Tests written?
Yes

### Commits signed with GPG?
Yes

2020-04-01 15:07 UTC, Ch3LL requested changes
Looks like there are a couple failing tests. 
Also Can you update the changelog and the sodium release notes with this new feature?

I think there would be added value in adding an integration test here as well to coincide with the unit tests?

2020-04-01 17:33 UTC, twangboy commented on tests/unit/modules/test_win_system.py
> -    def test_get_pending_computer_name(self):
The functions have been moved to the new salt util and are being tested there.

2020-04-09 14:42 UTC, Ch3LL submitted a review, later dismissed

2020-04-09 14:43 UTC, Ch3LL commented
@twangboy looks like it needs to be rebased and run black against this PR. Unfortunately I cannot see the test results so we will see the results after the rebase

2020-04-14 21:54 UTC, xeacott commented
This also links here ...
https://github.com/saltstack/release-planning/issues/197

2020-04-15 21:44 UTC, cmcmarrow submitted a review, later dismissed

2020-04-26 05:14 UTC, dwoz approved these changes

2020-04-26 05:14 UTC, merged