Cherry-Pick #52517 onto master branch
saltstack/salt pull request #56604
Opened 2020-04-10 14:27 UTC by Ch3LL

### What does this PR do?
Cherry-Pick #52517 onto the master branch

2020-04-20 18:58 UTC, cmcmarrow approved these changes

2020-04-20 19:09 UTC, cmcmarrow requested changes
This carry pick is getting an assert version == metadata.find("version").text on line 632.

2020-04-23 20:20 UTC, Ch3LL commented
@cmcmarrow  ready for re-review

2020-04-24 06:27 UTC, dwoz approved these changes

2020-04-24 06:27 UTC, merged