Port #53622 to master (runners.git_pillar: Also match the repo parameter against the repo name)
saltstack/salt pull request #56605
Opened 2020-04-10 14:48 UTC by sathieu

### What does this PR do?

Port #53622 to master.

2020-04-10 14:52 UTC, DmitryKuzmenko requested changes

2020-04-10 14:52 UTC, DmitryKuzmenko commented on salt/runners/git_pillar.py
> +    .. versionchanged:: 2020.2.0
~~2020.2.0~~ Sodium

2020-04-10 14:53 UTC, DmitryKuzmenko commented
@sathieu thank you for porting this to master. I understand that the original PR contains no tests but currently our testing strategy is changed: we don't merge anything not covered with at least regression tests. Could you please write one for this?

2020-05-14 18:59 UTC, sathieu commented
@DmitryKuzmenko Please review again. Tests added.

2020-05-15 16:53 UTC, DmitryKuzmenko approved these changes

2020-05-18 22:36 UTC, merged