Port #52305 to master
saltstack/salt pull request #56785
Opened 2020-04-21 18:21 UTC by xeacott

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-04-21 22:56 UTC, dwoz commented
@xeacott Test failures look legit

2020-05-04 08:34 UTC, dwoz requested changes

2020-05-04 08:34 UTC, dwoz commented on salt/fileclient.py
> -# pylint: enable=no-name-in-module,import-error
I'm not down with removing these for the whole file.

2020-05-04 08:34 UTC, dwoz commented on salt/fileclient.py
> -            except Exception as exc:  # pylint: disable=broad-except
This shouldn't be changing unless we are actually going to put a more applicable exception type here (which would be the preference).

2020-05-04 15:08 UTC, xeacott commented
Thanks for reviewing, I'll add them back. This PR was very troublesome not sure how all the extra changes weren't caught by the linter...

2020-05-06 22:21 UTC, cmcmarrow approved these changes

2020-05-07 23:14 UTC, merged