steveno <oliver.steven@gmail.com>
saltstack/salt pull request #56805
Opened 2020-04-21 20:04 UTC by joechainz

Correct indenting issues from linter

### What does this PR do?
https://github.com/saltstack/salt/pull/50708/commits
### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-05-01 14:07 UTC, Ch3LL commented
it looks like you are trying to port https://github.com/saltstack/salt/pull/50708 to the master branch, but it looks like its not bringing over the changes to salt/modules/win_file.py and tests/integration/modules/test_file.py

Is there a reason for not including these changes?

2020-08-03 17:28 UTC, Ch3LL requested changes
still waiting on response to this comment: https://github.com/saltstack/salt/pull/56805#issuecomment-622402332

also this will need a test case added.

2023-10-04 09:28 UTC, mdschmitt commented
Any update on this?

2023-12-10 07:55 UTC, dwoz commented
@joechainz Are you still interested in getting this over the finish line?

2023-12-20 21:11 UTC, twangboy requested changes

2023-12-20 21:11 UTC, twangboy commented on salt/modules/file.py
> +    .. versionadded:: Neon
Chlorine now, probably, maybe Argon

2023-12-20 21:12 UTC, twangboy commented
Also needs a changelog and a test

2024-01-03 21:34 UTC, dwoz commented
@joechainz Ping.

2024-07-05 04:54 UTC, dwoz commented
This can be re-based and re-opened if it should get into `3008.x`

2024-07-05 04:54 UTC, closed without merging