Add function postgres_default_privileges to grant and revoke default …
saltstack/salt pull request #56808
Opened 2020-04-21 20:20 UTC by dwoz

…privileges to users in postgres instances

The objects in a schema (with or without group) covered are:
- functions
- tables
- sequences

master port of #51904
See
https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-05-10 20:15 UTC, DmitryKuzmenko commented
@dwoz linter is still not okay here.

2023-12-20 21:09 UTC, twangboy requested changes

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +    .. versionadded:: 2019.0.0
3007?

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +    .. versionadded:: 2019.0.0
3007

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +    .. versionadded:: 2016.3.0
3007

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +    .. versionadded:: 2019.0.0
3007

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +            query = ' ALTER DEFAULT PRIVILEGES GRANT {0} TO "{1}" WITH ADMIN OPTION'.format(
Space after the single-quote

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +            query = ' ALTER DEFAULT PRIVILEGES IN SCHEMA {2} GRANT {0} ON {1}S TO "{3}"'.format(
Space after single quote

2023-12-20 21:09 UTC, twangboy commented on salt/modules/postgres.py
> +    .. versionadded:: 2019.0.0
3007

2023-12-20 21:09 UTC, twangboy commented on salt/states/postgres_default_privileges.py
> +.. versionadded:: 2016.3.0
3007

2023-12-20 21:09 UTC, twangboy commented on salt/states/postgres_default_privileges.py
> +        Database port if different from config or default
Needs an example

2023-12-20 21:09 UTC, twangboy commented on salt/states/postgres_default_privileges.py
> +        Database port if different from config or default
Needs an example state

2026-06-08 01:38 UTC, dwoz commented
@twangboy your 2023 review is addressed at 74da6a25a55 (rebased onto current master):

- `versionadded` directives on new code bumped to `3009.0` in `salt/modules/postgres.py` (`default_privileges_list` L3254, `has_default_privileges` L3454, `default_privileges_grant` L3733, `default_privileges_revoke` L3898) and `salt/states/postgres_default_privileges.py` L18. The `has_privileges` (L3593) versionadded is `2016.3.0` correctly — that's pre-existing code, not new in this PR.
- SQL spacing cleaned up: no more leading space after the opening quote, no more `ON  {1}S  TO` double-spaces in the `ALTER DEFAULT PRIVILEGES` queries.
- Example states added to both `present` (L158) and `absent` (L300) docstrings.

Could you re-review or dismiss the stale CHANGES_REQUESTED?

2026-06-09 15:01 UTC, twangboy approved these changes

2026-06-09 22:11 UTC, merged