Port #47620 to master
saltstack/salt pull request #56817
Opened 2020-04-21 22:48 UTC by Ch3LL

Port #47620 to master

2020-04-23 17:40 UTC, Ch3LL commented
ping @cbosdo would you mind reviewing here. I had to rebase with the changes you recently got merged and make some changes from the original PR to ensure loader worked with the new defined function as well.

2020-04-24 07:32 UTC, cbosdo commented
@Ch3LL I completely forgot about that PR... and there are some bits in the UEFI / loader handling that would need to be rethinked.

* For libvirt before 5.4.0 the user would need to provide both the loader and the nvram template for most UEFI cases (maybe not bhyve) and after, just a simple flag saying UEFI is wanted will suffice. For this I would move the `virt.init()` `loader` parameter in the `boot` one. This would allow adding `nvram` and other boot-related params later.

* This PR only touches the `virt.init()` function, but not the `virt.update()` one... and thus there will be problems when reapplying the `virt.running` or `virt.defined` states.

How do you see this backport PR? Just stick to what was in the original PR and then file another PR to fix the above mentioned points or add the above points to this PR? In the latter case I would probably have to take over your PR to complete and fix it.

2020-04-24 08:23 UTC, cbosdo requested changes
Apart from the missing documentation in the new `virt.defined` state, the backport is matching the original PR. However as mentioned in the previous comment, the original PR would have needed changes. These may be lifted in a subsequent PR.

2020-04-24 08:23 UTC, cbosdo commented on salt/states/virt.py
> +        .. versionadded:: Sodium
That parameter documentation should also be in the `defined()` state

2020-04-24 08:23 UTC, cbosdo commented on tests/unit/modules/test_virt.py
> +
Missing a test case for `virt.update` with loader defined

2020-04-24 10:13 UTC, cbosdo commented
For reference the UEFI part of this PR overlaps with merged PR #56613

2020-04-24 12:33 UTC, cbosdo commented
@Ch3LL PR #56882 is my attempt at the backport removing all the loader parameters since those have been added in the `boot` parameter already. The only missing thing is the possibility to set the `secure="yes"` flag. But I think I will have a go at it later

2020-04-27 07:13 UTC, cbosdo commented
since the other PR has been merged, this one can be closed

2020-04-27 15:36 UTC, Ch3LL commented
Thanks your awesome!

2020-04-27 15:36 UTC, closed without merging