Windows: uninstall msi-installed Salt
saltstack/salt pull request #56883
Opened 2020-04-24 12:39 UTC by markuskramerIgitt

### What does this PR do?
On Windows, uninstall msi-installed Salt

2020-04-24 17:27 UTC, twangboy requested changes

2020-04-24 17:27 UTC, twangboy commented on pkg/windows/installer/Salt-Minion-Setup.nsi
> +    MessageBox MB_YESNOCANCEL|MB_ICONQUESTION  "Uninstalling a previous version of ${PRODUCT_NAME}" IDNO UninstallMSI_nomsi IDYES UninstallMSI_yesmsi
Actually I think the logic here needs to be more like this:
```
Function UninstallMSI
    ; $R0 === product code
    MessageBox MB_OKCANCEL|MB_ICONEXCLAMATION \
        "${PRODUCT_NAME} is already installed.$\n$\n\
        Click `OK` to remove the existing installation." \
        /SD IDOK IDOK UninstallMSI
    Abort

    UninstallMSI:
        ExecWait '"msiexec.exe" /x $R0 /qn /quiet /norestart'

FunctionEnd
```

2020-04-24 17:27 UTC, twangboy commented on pkg/windows/installer/Salt-Minion-Setup.nsi
> +    MessageBox MB_YESNOCANCEL|MB_ICONQUESTION  "Uninstalling a previous version of ${PRODUCT_NAME}" IDNO UninstallMSI_nomsi IDYES UninstallMSI_yesmsi
I don't think we need to prompt them when the uninstall is completed. It should just continue.

2020-05-04 08:51 UTC, markuskramerIgitt commented on pkg/windows/installer/Salt-Minion-Setup.nsi
> +    MessageBox MB_YESNOCANCEL|MB_ICONQUESTION  "Uninstalling a previous version of ${PRODUCT_NAME}" IDNO UninstallMSI_nomsi IDYES UninstallMSI_yesmsi
Committed your logic. 
Please feel free to change the PR yourself, if you see more room for improvement.

2020-05-04 08:55 UTC, markuskramerIgitt commented on pkg/windows/installer/Salt-Minion-Setup.nsi
> +    MessageBox MB_YESNOCANCEL|MB_ICONQUESTION  "Uninstalling a previous version of ${PRODUCT_NAME}" IDNO UninstallMSI_nomsi IDYES UninstallMSI_yesmsi
I committed your logic

2020-05-04 08:59 UTC, markuskramerIgitt commented
Why the branch has a conflict?

2020-05-04 12:28 UTC, markuskramerIgitt commented
Replaced by https://github.com/saltstack/salt/pull/57068 due to merge conflicts

2020-05-04 12:28 UTC, closed without merging