Port #50168 to master
saltstack/salt pull request #56881
Opened 2020-04-24 11:54 UTC by DmitryKuzmenko

Port #50168 to master

I've tried to rework it to resolve crossing with functionality added to master by DWoz in #54942.

Original comment:

> Allow to refresh pillar synchronously
> This PR adds the optional ability to run saltutil.refresh_pillar Allow to refresh pillar synchronously, saying saltutil.refresh_pillar async=False. I tried to follow the explanatory comment from @gtmanfred and I believe that this works, still I am not sure about the mentioned use of the _gather_pillar() method. I am happy to rework the PR if something is missing.

2020-04-24 19:14 UTC, dwoz requested changes

2020-04-24 19:14 UTC, dwoz commented on salt/modules/saltutil.py
> -        if not event_ret or event_ret["complete"] is False:
I'd like to still warn if the refresh times out.

2020-05-10 17:46 UTC, DmitryKuzmenko commented
@dwoz I've updated the code accordingly to your request.

2020-05-12 00:27 UTC, dwoz approved these changes

2020-05-12 00:27 UTC, merged