Port #51993 to master
saltstack/salt pull request #56907
Opened 2020-04-27 13:18 UTC by alexey-zhukovin

### What does this PR do?

### What issues does this PR fix or reference?
Port #51993 to master

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-04-27 13:35 UTC, s0undt3ch requested changes

2020-04-27 13:35 UTC, s0undt3ch commented on salt/modules/flatpak.py
> +.. versionadded:: Neon
Please change Neon to Sodium

2020-04-27 13:35 UTC, s0undt3ch commented on salt/states/flatpak.py
> +.. versionadded:: Neon
Same here

2020-05-13 23:03 UTC, waynew commented
I'm working on adding tests for this, I believe I'll have 'em done on Thursday

2020-05-28 20:09 UTC, waynew requested changes
needs tests (I've been working through adding them during test clinic)

2021-05-23 21:59 UTC, fzoske commented
@waynew Any news on this pullrequest? Would be super happy to see this get merged :)

2023-12-10 08:05 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 08:05 UTC, closed without merging