Rework static requirements
saltstack/salt pull request #56904
Opened 2020-04-27 00:32 UTC by s0undt3ch

### What does this PR do?
All requirements are now compiled to static requirements.
This includes Windows and Darwin packaging requirements.

### What issues does this PR fix or reference?
Refs https://github.com/saltstack/release-planning/issues/238

2020-05-07 18:11 UTC, s0undt3ch commented
Conflicts solved again.

2020-05-07 23:02 UTC, twangboy commented
Rebase?

2020-05-07 23:15 UTC, twangboy commented on requirements/static/ci/py3.5/windows-crypto.txt
> +m2crypto==0.35.2
I don't think there are wheels available for 35.2 on Windows...

2020-05-07 23:15 UTC, twangboy commented on requirements/static/ci/py3.5/windows-crypto.txt
> +m2crypto==0.35.2
Nope. Pretty sure M2Crypto won't build off the source with pip on Windows. That's why I've been bundling pycryptodome on Windows packages.

2020-05-15 21:00 UTC, DmitryKuzmenko commented on setup.py
> +                    line.split("-r")[1].split("#")[0].strip(),
I'm not sure, but isn't there a chance to have a file name with spaces? Maybe `line.split(' ', 1)`?

2020-08-03 17:27 UTC, Ch3LL requested changes
looks like this requires a rebase

2020-09-15 07:33 UTC, s0undt3ch commented
@twangboy I need your review on the updated macOS and Windows builds scripts.

2020-09-16 14:40 UTC, twangboy approved these changes, later dismissed

2020-09-16 19:13 UTC, twangboy approved these changes, later dismissed
Looks good on Windows and Mac

2020-09-17 06:18 UTC, s0undt3ch commented
re-run full all

2020-09-22 16:43 UTC, s0undt3ch commented
re-run full all

2020-09-25 14:10 UTC, s0undt3ch commented
re-run full all

2020-09-27 20:11 UTC, s0undt3ch commented
re-run full all

2020-09-29 17:49 UTC, Ch3LL submitted a review, later dismissed
Is there documentation that covers how to update dependencies for packages and test dependencies? If not we should add some, although does not need to be in this PR.

Also, will salt-pkg need to be udpated, because it is currently pulling in the requirements here: https://gitlab.com/saltstack/open/salt-pkg/-/blob/master/redhat/sources/requirements.txt

2020-09-30 12:26 UTC, merged

2020-09-30 12:28 UTC, s0undt3ch commented
> Is there documentation that covers how to update dependencies for packages and test dependencies? If not we should add some, although does not need to be in this PR.
No and we should add some.

> Also, will salt-pkg need to be udpated, because it is currently pulling in the requirements here: https://gitlab.com/saltstack/open/salt-pkg/-/blob/master/redhat/sources/requirements.txt
Yes.