fix force-confnew/force-confdef options in aptpkg
saltstack/salt pull request #57051
Opened 2020-05-02 16:26 UTC by terrible-broom

### What does this PR do?
Fix of force-confnew/force-confdef/force-confold dpkg options in aptpkg module.

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/23501
https://github.com/saltstack/salt/issues/40558

### Previous Behavior
Options force-confnew and force-confdef were used together.

### New Behavior
Option force-confnew is used on its own, and force-confold and force-confdef are used together.

### Commits signed with GPG?
No

2020-05-02 20:17 UTC, terrible-broom commented
Honestly have no idea why code coverage changed. Please give a hint how to fix.

2020-05-05 18:24 UTC, cmcmarrow requested changes
Thank you for your fix, but can we get some tests?

2020-05-07 07:02 UTC, terrible-broom commented
> Thank you for your fix, but can we get some tests?

Okay, i've made very basic tests. I hope this is the right way to do it.

2020-05-11 07:30 UTC, dwoz approved these changes

2020-05-11 07:30 UTC, merged