Allow set higher priority failhard on the client-side
saltstack/salt pull request #57237
Opened 2020-05-13 07:28 UTC by rongzeng54

### What does this PR do?
Allow set higher priority failhard on the client-side.
Failhard is a cool feature, because in many case fast fail is better.
Global failhard control is hard to use, client-side can control itself seems better.

### What issues does this PR fix or reference?
Fixes: No

### Previous Behavior
Server-side can set global failhard.

### New Behavior
Client-side can set higher priority failhard.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-05-13 22:46 UTC, waynew commented on salt/state.py
> +                opts['failhard'] = False
```suggestion
          opts.setdefault('failhard', False)
```
This will only set failhard if it's not already set.

2020-05-13 22:48 UTC, waynew commented on salt/state.py
> +                opts['failhard'] = mopts.get('failhard', False)
```suggestion
            opts.setdefault('failhard', mopts.get('failhard', False))
```
Same - will only set failhard if not already set.

2020-05-13 22:52 UTC, waynew requested changes
@rongzeng54 thanks for the PR! We require tests to merge PRs, would you be able to write some tests for this? It should be relatively straightforward.

Also please add a [changelog entry](https://docs.saltstack.com/en/master/topics/development/changelog.html)

If you're able to get this PR updated before Monday we will be able to get it merged in for the Sodium release (3001).

Thanks again!

2020-05-18 23:19 UTC, dwoz commented
@rongzeng54 This should not have been opened against `develop`. Please point this to `master` instead.

2021-04-19 15:16 UTC, sagetherage commented
@rongzeng54 This should not have been opened against develop. Please point this to master instead.

2021-05-03 22:36 UTC, sagetherage commented
Reviewed in Grooming 2021-MAY-03 closing

2021-05-03 22:36 UTC, closed without merging