Add COPR support to states.pkgrepo
saltstack/salt pull request #57259
Opened 2020-05-14 00:59 UTC by mymindstorm

### What does this PR do?

Adds a COPR option to `pkgrepo.absent` and `pkgrepo.managed`. This is a shortcut for either manually downloading the repo file or using cmd.run to add the COPR repository.

### What issues does this PR fix or reference?
Fixes #57258 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

I'm new to Python, I might be missing a few things in the code.

2020-05-18 19:15 UTC, waynew submitted a review, later dismissed

2020-05-18 19:17 UTC, waynew commented
Hey @mymindstorm thanks for the PR! Looks reasonable to me!

2020-05-19 03:41 UTC, mymindstorm commented
Looks like tests didn't actually run when I made this for some reason. I almost messed up pkgrepo on RedHat based computers.

2020-05-19 22:48 UTC, mymindstorm commented
Test failures seem to be unrelated? I'm not really sure what to make of the new ones that popped up.

2020-05-20 23:52 UTC, dwoz commented
re-run full all

2020-05-27 18:52 UTC, waynew commented
re-run windows2016-py3

2020-05-28 20:27 UTC, waynew submitted a review, later dismissed
As far as I can see, this is :+1: but the Windows test is _extremely_ unhappy here.

2020-07-12 01:58 UTC, mymindstorm commented
Do I need to do anything to get this merged? None of this should even execute on Windows...

2020-09-09 19:16 UTC, Ch3LL requested changes
just a small request and if you could rebase.

2020-09-09 19:16 UTC, Ch3LL commented on salt/states/pkgrepo.py
> +    copr
Can you add `.. versionadded:: 3002` for this new argument?

2020-09-09 19:16 UTC, Ch3LL commented on salt/states/pkgrepo.py
> +    copr
`.. versionadded:: 3002` here as well

2020-09-09 20:15 UTC, Ch3LL submitted a review, later dismissed

2020-09-15 12:00 UTC, Ch3LL commented
looks like pre-commit is just failing. then we can get this in

2020-09-18 00:23 UTC, sagetherage commented
@mymindstorm here are the [docs on pre-commit](https://docs.saltstack.com/en/latest/topics/development/contributing.html#pre-commit) in case that is helpful : )

2020-09-18 01:06 UTC, mymindstorm commented
> @mymindstorm here are the [docs on pre-commit](https://docs.saltstack.com/en/latest/topics/development/contributing.html#pre-commit) in case that is helpful : )

Thanks for the link, I don't have that much time to fix (and properly rebase) it right now. I will see if I can get to it this weekend.

2020-09-25 23:24 UTC, dwoz approved these changes

2020-09-25 23:25 UTC, merged