Port #51205 to master
saltstack/salt pull request #57443
Opened 2020-05-23 18:12 UTC by terminalmage

See https://github.com/saltstack/salt/pull/51205

```
Lint: Fix str-format-in-logging, len-as-condition, etc. (6)

This fixes violations found in the following locations:

- salt/state.py
- salt/states/
- salt/tops/
- salt/transport/
```

2020-05-26 16:03 UTC, waynew requested changes
Thanks for the port 🚀 

Just one tweak (-six) and one question (assert??) and should be good 👍

2020-05-26 16:04 UTC, waynew commented
I'm guessing the test failures are fixed on master, too, FWIW. At a glance they don't look related.

2020-05-26 16:23 UTC, terminalmage commented on salt/states/btrfs.py
> +            ret["comment"].append(six.text_type(e))
Done.

2020-05-26 16:28 UTC, terminalmage commented on salt/states/ldap.py
> +                    assert not results
Actually, I'm not going to make any changes for this one. There are in total three asserts in this module, and while to be honest we should never use them in non-test code, both of the following are true:

1. I did not write this code
2. I do not understand how it is supposed to work.

In the interest of not introducing new bugs, I think that a new issue should be opened to replace all the asserts in this module.

At first glance, I don't think any of these asserts should be fatal for the state. It's possible that they were once used as a crude signaling measure, but there no longer appears to be anything catching them. But again, I'm not familiar with this code. This PR is solely to resolve lint issues.

2020-05-26 16:56 UTC, waynew commented on salt/states/ldap.py
> +                    assert not results
I agree with that - I wasn't sure to bring it up even, but figured I'd err on the side of calling out the oddity. If you haven't opened an issue, let me know and I can go ahead and do that.

2020-05-26 16:56 UTC, waynew submitted a review, later dismissed

2023-12-10 08:48 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 08:48 UTC, closed without merging