use null in sls file to map None object
saltstack/salt pull request #57451
Opened 2020-05-25 07:52 UTC by gqlo

### What does this PR do?
Passing `None` in boot parameters in sls file is handled as a string. We could pass `null` so that it will be translated to Python `None` object by YAML. It makes more sense to do so.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-05-25 08:08 UTC, cbosdo requested changes
LGTM, but the doc changes are not needed. What could be done in the doc is to provide an example of SLS file with a `null` however.

2020-05-25 08:08 UTC, cbosdo commented on salt/modules/virt.py
> +        pass null object, for instance: 'kernel': ``null``.
Don't mention `null` in that documentation since this is a YAML/SLS-specific value for `None`

2020-05-25 08:08 UTC, cbosdo commented on salt/modules/virt.py
> +        To switch back to BIOS boot, specify ('loader': ``null`` and 'nvram': ``null``)  or 'efi': ``False``
Same here

2020-05-25 15:40 UTC, cbosdo submitted a review, later dismissed
:+1:

2020-05-29 22:28 UTC, cmcmarrow submitted a review, later dismissed

2020-07-28 13:04 UTC, gqlo commented
@dwoz

2020-07-29 10:22 UTC, gqlo commented
re-run all

2020-07-29 10:54 UTC, gqlo commented
re-run all

2020-07-29 11:03 UTC, gqlo commented
re-run full all

2020-07-29 11:04 UTC, gqlo commented
re-run full [ windows | all | etc. ]

2020-07-29 11:31 UTC, gqlo commented
re-run ci/pre-commit

2020-07-29 12:37 UTC, gqlo commented
re-run all

2020-07-29 16:33 UTC, dwoz commented
@gqlo Looks like black needs to run before the pre-commit check will pass

2020-07-30 02:45 UTC, gqlo commented
re-run all

2020-07-30 21:58 UTC, dwoz approved these changes

2020-07-30 21:58 UTC, merged