Port #51684 to master
saltstack/salt pull request #57500
Opened 2020-05-29 22:17 UTC by terminalmage

See https://github.com/saltstack/salt/pull/51684

2020-06-03 22:16 UTC, xeacott submitted a review, later dismissed

2022-10-06 20:21 UTC, Ch3LL commented
@terminalmage mind fixing the merge conflict here?

2022-11-01 18:12 UTC, Ch3LL requested changes
This will also require a changelog

2022-11-01 18:12 UTC, Ch3LL commented on salt/modules/boto_dynamodb.py
> +              resource_arn=arn:aws:dynamodb:us-east-1:012345678901:table/my-table
can you add a versionadded for 3006

2022-11-01 18:12 UTC, Ch3LL commented on salt/modules/boto_dynamodb.py
> +              tags='{Name: my-table, Owner: Ops}'
version added here as well

2022-11-01 18:12 UTC, Ch3LL commented on salt/modules/boto_dynamodb.py
> +            return None
I think it makes more sense to return False here to keep in line with the other ffunctions.

2022-11-01 18:12 UTC, Ch3LL commented on salt/modules/boto_dynamodb.py
> +              tag_keys='[Name, Owner]'
versionadded here as well

2022-11-01 19:49 UTC, terminalmage commented
@Ch3LL I thought I already had rebased onto master, but I might be mistaken. I did a rebase, and I think I've covered all the review comments.

2022-11-03 18:35 UTC, Ch3LL approved these changes

2022-11-04 14:19 UTC, merged