57501
saltstack/salt pull request #57502
Opened 2020-05-30 04:30 UTC by jude

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #57501 

### Previous Behavior
A deprecation warning was logged in the minion logs.

### New Behavior
No deprecation warning is logged.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [N/A] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

2020-06-01 19:16 UTC, Akm0d submitted a review, later dismissed

2020-06-01 22:00 UTC, cmcmarrow submitted a review, later dismissed

2020-10-02 21:49 UTC, Ch3LL requested changes

2020-10-02 21:49 UTC, Ch3LL commented on salt/serializers/msgpack.py
> +                options.setdefault("raw", six.PY2)
we no longer support python2, so we do not need to add support for this. Also we should be handling this  in salt/utils/msgpack.py instead so it handles all cases of msgpack using encoding.

As you can see we are already doing this for versions 1.0 https://github.com/saltstack/salt/blob/master/salt/utils/msgpack.py#L72 and here  https://github.com/saltstack/salt/blob/master/salt/utils/msgpack.py#L86

2023-12-10 08:52 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 08:52 UTC, closed without merging