Py3 unicode
saltstack/salt pull request #57515
Opened 2020-06-01 17:27 UTC by twangboy

### What does this PR do?
Adds some tests for Unicode Support with Py3
Adds the ability to pass file content to the `@with_tempfile` helper
Adds the ability to pass the code page to use with run commands on Windows (`chcp`)

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/pull/56028, https://github.com/saltstack/salt/issues/54447, https://github.com/saltstack/salt/issues/36031

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-07-12 08:32 UTC, markuskramerIgitt commented
This is a step forward.

I replaced 437 with 65001 by notepad c:\salt\bin\Lib\site-packages\salt-3001-py3.7.egg\salt\modules\cmdmod.py

Observations:
- Run with salt-call on Windows, ` chcp 65001 > nul & ` does has no effect on the first run, but on the 2nd and 3rd.
- In a new Windows console, the problem reappears.
- Run with salt from the master, ` chcp 65001 > nul & ` has no effect on the first run, but on the 2nd and 3rd.

```
\salt\salt-call  cmd.run "dir \windows\temp\salt-test"
[ERROR   ] Failed to decode stdout from command chcp 65001 > nul & dir \windows\temp\salt-test, non-decodable characters have been replaced
local:
     Datentr�ger in Laufwerk C: ist Windows
     Volumeseriennummer: EA6E-94D5

     Verzeichnis von C:\windows\temp\salt-test

    10.07.2020  18:05    <DIR>          .
    10.07.2020  18:05    <DIR>          ..
    10.07.2020  18:05                12 ausgef�hrt.txt
    10.07.2020  17:51                13 Datentr�ger.txt
                   2 Datei(en),             25 Bytes
                   2 Verzeichnis(se), 328.308.600.832 Bytes frei

\salt\salt-call  cmd.run "dir \windows\temp\salt-test"
local:
     Datenträger in Laufwerk C: ist Windows
     Volumeseriennummer: EA6E-94D5

     Verzeichnis von C:\windows\temp\salt-test

    10.07.2020  18:05    <DIR>          .
    10.07.2020  18:05    <DIR>          ..
    10.07.2020  18:05                12 ausgeführt.txt
    10.07.2020  17:51                13 Datenträger.txt
                   2 Datei(en),             25 Bytes
                   2 Verzeichnis(se), 328.307.232.768 Bytes frei

```

## Further comment on PR 57515

### Removed chcp in cmdmod.py

For investigation, I installed a minion from git (`git checkout v3001` and `pip install -e .`)  and removed setting of chcp in cmdmod.py.

### Tried PYTHONUTF8

 [PEP540 UTF8-Mode in Python 3.7](https://www.python.org/dev/peps/pep-0540/) offers command line option `python.exe -X utf8` and environment variable PYTHONUTF8

As I don't know which salt-call is used, I used the environment variable.

Unfortunately PYTHONUTF8 has no effect :
- Setting $env:PYTHONUTF8 = 1  from PowerShell
- salt-call --local cmd.run "dir" from PowerShell
- ä is `„ `

### Tried chcp from PowerShell
chcp has instant effect, switches back and forth:

- Good
  - chcp 65001 from Powershell
  - salt-call --local cmd.run "dir" from PowerShell
  - ä is ä

- Bad
  - chcp 437 from Powershell
  - salt-call --local cmd.run "dir" from PowerShell
  - ä is `„ `

I think chcp should be called before python.exe.

2020-07-15 18:47 UTC, cmcmarrow approved these changes

2020-07-15 19:56 UTC, cmcmarrow requested changes
Why use 437? Python is utf-8 so why not just use 65001 by default? Also the code page change does not take effect until the second call. So we can just call _run with just the code page change so it takes effect right away!

2020-07-15 19:56 UTC, cmcmarrow commented on salt/modules/cmdmod.py
>              if python_shell:
```suggestion
            if python_shell and chcp is not None:
                _run(cmd="chcp {0} > nul".format(chcp),
                        cwd=cwd,
                        stdin=stdin,
                        stdout=stdout,
                        stderr=stder,
                        output_encoding=output_encoding,
                        output_loglevel=output_loglevel=,
                        log_callback=log_callback,
                        runas=runas,
                        group=group,
                        shell=shell,
                       python_shell=python_shell,
                       env=env,
                       clean_env=clean_env,
                       prepend_path=prepend_path,
                       rstrip=rstrip,
                       template=template,
                       umask=umask,
                       timeout=timeout,
                       with_communicate=with_communicate,
                       reset_system_locale=reset_system_locale,
                       ignore_retcode=ignore_retcode,
                       saltenv=saltenv,
                       pillarenv=pillarenv,
                       pillar_override=pillar_override,
                       use_vt=use_vt,
                       password=password,
                       bg=bg,
                       encoded_cmd=encoded_cmd,
                       success_retcodes=success_retcodes,
                       chcp=None,
                       **kwargs)
```

2020-07-15 19:56 UTC, cmcmarrow commented on salt/modules/cmdmod.py
>              if python_shell:
Why uses 437? Python is utf-8 so why not just use 65001 by default? Also the code page change does not take effect until the second call. So we can just call _run with just the code page change so it takes effect right away!

2020-07-15 20:04 UTC, cmcmarrow commented
It alos looks like the `echo Datenträger` test is not effective

2020-07-15 20:14 UTC, cmcmarrow commented
Also `chcp 65001 > nul` gives me an error but `chcp 65001 > null` does not

2020-07-22 18:19 UTC, markuskramerIgitt commented
@chad, on the 3001 Minion I successfully hacked two things within cmdmod.py:
1) I removed `chcp 437 > nul &`
2) I added `subprocess.run("C:\\Windows\\System32\\chcp.com 65001", stdout=subprocess.DEVNULL)` before  `proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)`


Success means letter ä is decoded always (and from the first time)

hack means I do not want to make a pull request with that code. 

I don't understand where you call _run(), but hopefully your and my solution are more or less doing the same,



These are lines 687: 

```
    if not use_vt:
        # This is where the unicode magic happens
        try:
            subprocess.run("C:\\Windows\\System32\\chcp.com 65001", stdout=subprocess.DEVNULL)
        except (BaseException) as exc:
            msg = (
                "Unable to run chcp 65001 before command '{0}' , "
                "reason: {1}".format(
                    cmd if output_loglevel is not None else "REDACTED", exc
                )
            )
            raise CommandExecutionError(msg)


        # This is where the magic happens
```


![image](https://user-images.githubusercontent.com/8489107/88212594-ca829d00-cc57-11ea-8d0a-d786f9759f22.png)

2020-10-05 21:29 UTC, closed without merging