Changed query get_jids
saltstack/salt pull request #57534
Opened 2020-06-03 17:11 UTC by mazovladimir

### What does this PR do?
This PR solves issue related to bug 
[BUG] jobs.list_jobs shows "Target": unknown-target when using pgjsonb returner #57524
### What issues does this PR fix or reference?
Fixes:
Incorret get_jids method for pgjsonb salt_returner
### Previous Behavior
Unknown target when use jobs.list_jobs command 
### New Behavior
Correct Target name when use jobs.list_jobs command
### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-06-03 17:22 UTC, twangboy requested changes

2020-06-03 17:22 UTC, twangboy commented on salt/returners/pgjsonb.py
> +        sql = '''SELECT j.jid as jid, j.load as load, jsonb_agg(sr.id) as tgt FROM jids j
This is probably going to fail  pre-commit... should be double-quotes `"""`

2020-06-03 19:30 UTC, twangboy commented
@mazovladimir Looks good. Now we'll need some tests.

2020-06-07 17:27 UTC, mazovladimir commented
Colleagues, I suppose I found the issue, no need to replace sql query, there was a missing tgt in minion file. Please see commit above.

2020-06-07 17:39 UTC, mazovladimir commented
I suppose this bug related to multiple returners, and should be applied globally to all minions. I tried to add this line in commit and it works perfect.

2022-11-14 19:15 UTC, dmurphy18 requested changes
@mazovladimir Are you still interested in this PR ?, if so, please add test cases and address outstanding review comments. If unresponsive, this PR shall be closed after several days

2022-11-28 20:10 UTC, Ch3LL commented
Closing due to inactivity. Please let me know if you want me to re-open or please submit a PR against the master branch with the requested changes.

2022-11-28 20:10 UTC, closed without merging