Adding some missing entries to the changelog.
saltstack/salt pull request #57589
Opened 2020-06-08 21:38 UTC by garethgreenaway

### What does this PR do?
Adding missing PRs into the change log for Sodium

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-06-08 21:55 UTC, waynew requested changes

2020-06-08 21:55 UTC, waynew commented on CHANGELOG.md
> +- Port #53537 to master (#56835)
This is already in here - I'm suspecting the other ones will be as well - https://github.com/saltstack/salt/pull/53537 fixes issue https://github.com/saltstack/salt/issues/4438

2020-06-09 12:01 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-06-22 16:57 UTC, waynew requested changes
A couple of these entries are already in the changelog

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Remove salt/utils/vt.py duplication from filename map. (#57004)
This isn't a feature removal - also it's only in the `tests` dir, so really not user-facing.

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Update `formulas.rst` with new IRC channel and links to IRC logs (#51628)
I don't feel strongly that this *shouldn't* be added, but I don't feel strongly that it should be added either.

I guess I have a weak preference that it doesn't /really/ belong in the changelog, in that I would be shocked if someone was led to the correct IRC channel by encountering the entry here in the changelog.

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Wrong isinstance in ini options absent (#53874)
https://github.com/saltstack/salt/blame/master/CHANGELOG.md#L134 already there

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Fix issue with finding the real python executable during tests (#56460)
https://github.com/saltstack/salt/pull/56460 wrong #?

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Fix broken link regarding the 1024 character limit for YAML keys (#56540)
another doc change that seems low impact.

2020-06-22 16:57 UTC, waynew commented on CHANGELOG.md
> +- Virt disks fixes (#56666)
Already exists as https://github.com/saltstack/salt/blame/master/CHANGELOG.md#L353

2020-06-25 11:42 UTC, DmitryKuzmenko approved these changes

2020-09-14 17:06 UTC, waynew approved these changes

2020-10-01 16:42 UTC, merged