Disk grains should not show virtual devices fix issue 57612
saltstack/salt pull request #57613
Opened 2020-06-10 02:16 UTC by piterpunk

### What does this PR do?
Changes the disks.py to populate "disks" and "SSDs" only with real devices, skipping virtual devices like devmaps, loopback and RAM disks.

### What issues does this PR fix or reference?
Fixes: #57612 

### Previous Behavior
In a machine with only one disk the grains shows:

```
# salt-call grains.get disks
local:
    - loop1
    - dm-1
    - loop6
    - dm-6
    - loop4
    - dm-4
    - loop2
    - dm-2
    - loop0
    - dm-0
    - loop7
    - dm-7
    - sda
    - loop5
    - dm-5
    - loop3
    - dm-3
# salt-call grains.get SSDs
local:
    - ram2
    - ram0
    - ram9
    - ram14
    - ram7
    - ram12
    - ram5
    - ram10
    - ram3
    - ram1
    - ram15
    - ram8
    - ram13
    - ram6
    - ram11
    - ram4
```

### New Behavior
Now it shows only the real device:

```
# salt-call grains.get SSDs
local:
# salt-call grains.get disks
local:
    - sda
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
[salt-runtests-20200609201317.log](https://github.com/saltstack/salt/files/4755812/salt-runtests-20200609201317.log)

### Commits signed with GPG?
No

2020-06-15 14:30 UTC, piterpunk commented
Also fixes #51898

2020-06-15 22:08 UTC, waynew requested changes
Hey @piterpunk thanks for the PR!

This looks great - just needs a couple of tests here to prevent regressions. If you need some help writing tests, I'd be happy to help out - I run test clinics [on Twitch](https://www.twitch.tv/saltstackinc/schedule) on Tuesday and Thursday. You can also ping me in #salt on freenode or on the community Slack.

Let me know if you have any questions!

2020-06-16 22:53 UTC, waynew requested changes
Hey thanks for the update! I mentioned in IRC, but here's the changes.

You can actually pre-define your patches and then use them in the `with` block. If you don't like doing that, that's OK. But definitely add `autospec=True`.

Otherwise, this looks great, thanks!

2020-06-16 22:53 UTC, waynew commented on tests/unit/grains/test_disks.py
> +        ), patch("salt.utils.files.fopen", mock_open(read_data=contents)):
```suggestion
       patch_glob = patch("glob.glob", autospec=True, return_value=files)
       patch_readlink = patch("salt.utils.path.readlink", autospec=True, side_effect=links)
       patch_fopen = patch("salt.utils.files.fopen", mock_open(read_data=contents), autospec=True)
       with patch_glob, patch_readlink, patch_fopen:
```

I'm pretty sure that's the right syntax. Anyway, the most important part of the change is `autospec=True` - basically what that does is ensure that the patched thing looks/behaves like the thing it's patching - so if the underlying API changes then this test will also (correctly) break. IIRC, patch will produce a MagicMock by default - you can just give it a return_value or side_effect.

2020-06-16 23:57 UTC, piterpunk commented
Done. Only mock_open doesn't accept autospec=True, which makes sense, since mock_open() already explicit mocks the open() call.

Thanks with the help! I'll use the lessons learned in next tests.

2020-06-22 17:03 UTC, waynew approved these changes
🚀 Looks great! Thanks for the changes 👍 

We're currently in code freeze, so expect a couple of weeks before this gets merged (post 3001.1 release)

2020-06-22 17:07 UTC, waynew requested changes
Ah whoops - spoke a moment too soon! Can you also add a [changelog entry?](https://docs.saltstack.com/en/latest/topics/development/changelog.html)

*then* we'll be good 👍

2020-06-23 14:28 UTC, waynew submitted a review, later dismissed
:rocket:

2020-06-24 16:49 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-07-07 07:40 UTC, remichristiaan commented
A question not related to this fix in particular but to the naming of the grain.
  
[Salt doc states](https://docs.saltstack.com/en/latest/topics/grains/): _Grains resolve to lowercase letters. For example, FOO, and foo target the same grain._

The grain SSDs is not lowercase (all the other standard grains are) and is not usable as lowercase .. e.g. 
`salt-call grains.item SSDs`  works but `salt-call grains.item ssds` not. 

Can this be changed so that it complies with what the docs state?

2020-07-07 13:36 UTC, piterpunk commented
> A question not related to this fix in particular but to the naming of the grain.
>
> The grain SSDs is not lowercase (all the other standard grains are) and is not usable as lowercase .. e.g. `salt-call grains.item SSDs` works but `salt-call grains.item ssds` not.
> 
> Can this be changed so that it complies with what the docs state?

I can change the "SSDs" grain name to "ssds", the grain is not used by any Salt module or state, I did a quick check on saltstack-formulas and looks it's unused there too.

Should I do the change?

2020-07-07 14:38 UTC, DmitryKuzmenko commented
@remichristiaan good catch. Thank you!
@piterpunk yes please. This sounds correct to have it lowercase accordingly to the docs.

2020-07-07 20:51 UTC, DmitryKuzmenko approved these changes

2020-07-13 22:42 UTC, merged