Added ability to filter docs for specific runner
saltstack/salt pull request #57757
Opened 2020-06-23 01:19 UTC by doesitblend

### What does this PR do?
Updates `doc.runner` to make use of the already underlying functionality to supply an argument to look at docs for a specific runner.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Calling `salt-run doc.runner` would dump all runner docs

### New Behavior
You can now call `salt-run doc.runner winrepo` or `salt-run doc.runner manage.down` to get docs specific to that module, or method.

2020-07-03 08:31 UTC, max-arnold commented
Maybe it also makes sense to do the same for `doc.wheel` and `doc.execution` functions for consistency purposes?

2020-09-03 16:39 UTC, waynew commented
Hey @doesitblend I went ahead and wrote some tests here: https://github.com/waynew/salt/pull/new/tc/update-doc-runner-57757

2021-09-15 14:01 UTC, s0undt3ch requested changes

2021-09-15 14:01 UTC, s0undt3ch commented on tests/pytests/unit/runners/test_doc.py
> +def setup_loader(request):
This needs to be updated to the new way of setting loader modules.
Please check the other tests on how.

2023-12-10 09:00 UTC, closed without merging

2023-12-10 09:00 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.