Print jinja line numbers & error context on UndefinedError
saltstack/salt pull request #57852
Opened 2020-07-02 09:07 UTC by frebib

This provides both the line number on which the error occurred in the
Jinja template, and also several lines of context around the error in
the Jinja template source.

The one caveat to this change is that if paired with jinja2<2.11 it
could possibly report incorrect line numbers for some errors. This was
fixed in https://github.com/pallets/jinja/pull/1109

Traces/errors before were vague and ambiguous:

    File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 387, in render_jinja_tmpl
      buf=tmplstr)
    SaltRenderError: Jinja variable 'str object' has no attribute 'items'

This gives a line number and multiple lines of context:

    File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 387, in render_jinja_tmpl
      tmplstr)
    SaltRenderError: Jinja variable 'str object' has no attribute 'items'; line 5

    ---
    # {{ salt.pillar.get('managed_by_salt_message', '') }}
    # salt template: {{ source }}

    {%- for section in sections %}
      {%- for name, config in section.items() %}    <======================
    [{{ name }}]
        {%- for line in config %}
    {{ line }}
        {%- endfor %}
      {%- endfor %}
    [...]
    ---

Signed-off-by: Joe Groocock <jgroocock@cloudflare.com>

### What does this PR do?
Makes Jinja undefined error messages more helpful

### What issues does this PR fix or reference?
Fixes: #21298

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-07-17 19:29 UTC, waynew requested changes
Hey @frebib thanks for the PR! I love to see fixes when dependencies get fixed 😄 

This should get a [changelog entry](https://docs.saltstack.com/en/master/topics/development/changelog.html), and we'll also need some tests before we can merge. If you need help, feel free to drop by the Test Clinic on Tuesdays & Thursdays on https://twitch.tv/saltstackinc!

2020-07-18 01:50 UTC, max-arnold commented on salt/utils/templates.py
> +        raise SaltRenderError("Jinja variable {0}{1}".format(exc, out), line, tmplstr)
Can `line` be `None` here? Does it make sense to print it then?

2020-10-24 20:04 UTC, ixs commented
This is a really nice functionality and I'd really prefer that functionality in salt.

As far as I remember, original jinja prints line numbers but salt disabled that because of the way the salt render pipeline works, the line numbers can be off.

Unfortunately, this still seems to be the case. I've added the patch to my local salt build to see how it performs and the lines seem off in some cases:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 32, in top-level template code
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 884, in render_pstate
    **defaults
  File "/usr/lib/python3.6/site-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/renderers/jinja.py", line 79, in render
    **kws
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 260, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 543, in render_jinja_tmpl
    "Jinja error: {}{}".format(exc, out), line, tmplstr, trace=tracestr
salt.exceptions.SaltRenderError: Jinja error: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 32, in top-level template code
TypeError: can't multiply sequence by non-int of type 'float'

; line 32

---
[...]
      general_log_file: /var/log/mariadb/query.log
      general_log: 0
      bind-address: 0.0.0.0
#      old_passwords: 1
      connect_timeout: 15
#      skip-name-resolve: 1    <======================
      slave_net_timeout: 30
      innodb_buffer_pool_size: {{ (salt['grains.get']('mem_total') * 0.6) | int }}
      innodb_buffer_pool_instances: 4
      innodb_log_buffer_size: 4MB
      innodb_read_io_threads: 4
[...]
```

The render error is because a client connected without sending any grains, which means the grains.get call failed. Which is fine.
But the line that is shown as broken is off... 😟

2022-06-06 19:47 UTC, Ch3LL commented
Looks like this functionality was added here: https://github.com/saltstack/salt/pull/61553 

I will close this in favor of https://github.com/saltstack/salt/pull/61553

2022-06-06 19:47 UTC, closed without merging

2022-07-20 16:07 UTC, jfindlay commented
@ixs the line offset issue could be caused by an old version of jinja where that was a common problem.