pkg: report stdout when stderr is redirected to stdout
saltstack/salt pull request #57863
Opened 2020-07-04 00:52 UTC by marmarek

Fixes b40e21284b7b0e0accc41abfd1680c5551e2bc7b
Fixes #57862

### What does this PR do?

When 'redirect_stderr=True' is set, stderr is empty and both
stdout+stderr are logged into stdout. Include the right one in the
output.

### What issues does this PR fix or reference?
Fixes: 57862

### Previous Behavior
Empty `errors` field on errors.

### New Behavior
`errors` field populated.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2020-07-04 16:29 UTC, cmcmarrow commented
@marmarek I know it’s a little redundant but can we get a test to verify that does not turn back into a regression again? Also thanks for the PR! The failing test are not related to you at this time. It’s a problem on are end.

2020-07-04 16:32 UTC, cmcmarrow requested changes
I think it would be good to include `stdout` and `stderr`. I think someone changed it to `stdout` because they were not getting info need from `stderr`

2020-07-04 17:08 UTC, marmarek commented
> I think it would be good to include `stdout` and `stderr`

In this specific case it doesn't make sense, as stderr is redirected to stdout. Maybe two other cases should also have `redirect_stderr=True` instead of logging stdout and stderr separately?

2020-07-05 23:47 UTC, terminalmage commented
@marmarek Yeah, I think I mistakenly "corrected" the line you're fixing in this PR, I should have left it alone. Can you revert the other two from b40e2128 but also add `redirect_stderr=True` to the `_call_yum()` function call? That seems like the best fix here.

2020-07-11 15:24 UTC, terminalmage commented
@marmarek Just checking back in since I haven't heard back from you. Can you make those changes I mentioned in my last comment?

2020-08-02 22:13 UTC, marmarek commented
I've finally found some time to finish this, sorry for the delay.

2020-08-03 03:40 UTC, terminalmage commented
Thanks! This looks good, just need a few fixes identified by pre-commit.

2020-08-03 04:02 UTC, marmarek commented
pre-commit seems to look at the whole file, not only changed parts. Should I include reformatting and various other updates like removing `six` in the commit? Sounds unrelated to this PR...

2020-08-03 04:34 UTC, terminalmage commented
I know that the core team will not merge this without the tests failing. It seems that the failures are related to some automated code reformatting to ditch usage of six and associated code conventions that ensure Python 2.7 compatibility, now that Python 2 support has been dropped.

Perhaps one of the core team can apply the pre-commit hooks and push to this PR branch.

2020-08-07 17:25 UTC, cmcmarrow submitted a review, later dismissed

2020-10-05 13:43 UTC, Ch3LL commented
I went ahead and ran pre-commit and fixed some merge conflicts on rebase.

2020-10-05 13:47 UTC, Ch3LL commented
ping @terminalmage would you mind re-reviewing since I have technically pushed code to this now would be nice to get one more review.

2020-10-05 13:48 UTC, Ch3LL approved these changes, later dismissed

2020-10-05 13:55 UTC, terminalmage approved these changes, later dismissed
Looks great :+1:

2020-10-05 22:46 UTC, merged