Add ARM64 support for Ubuntu20 pipeline
saltstack/salt pull request #57997
Opened 2020-07-21 20:08 UTC by krionbsd

### What does this PR do?
Add ARM64 support for Ubuntu20 pipeline

2020-07-21 20:14 UTC, bryceml approved these changes
This looks good after we get the kitchen config and jenkins multi-branch pipeline in for it.

2020-08-19 18:20 UTC, bryceml requested changes
We need to hard-code the ami, since we're making that change elsewhere.

2021-02-03 14:23 UTC, Ch3LL commented
@bryceml can you re-review?

2021-02-04 05:28 UTC, bryceml approved these changes, later dismissed

2021-02-04 18:47 UTC, Ch3LL commented
thanks. @krionbsd looks like there is some ub20 arm64 errors here that need to be cleaned up: https://jenkins.saltproject.io/job/pr-arm64-ubuntu2004-py3-pytest/job/PR-57997/4/#showFailuresLink

2021-02-10 19:52 UTC, garethgreenaway submitted a review, later dismissed

2021-03-26 18:38 UTC, bryceml commented
we decided we can skip the failing tests on arm64 with a link to https://github.com/saltstack/salt/issues/59884

Need to add that, we haven't skipped based on architecture before so we need to figure out the best way to do that.  Most thing use salt.utils.platform but arch isn't in there.

2021-04-06 17:05 UTC, bryceml commented on tests/integration/pillar/test_git_pillar.py
> +pytestmark = [
I don't think we want to skip the whole file, just the SSH pygit2 tests.  Or if we want all the pygit2 tests.  We shouldn't skip the GitPython tests.

And we use the same version of libgit2-dev on x86_64, so it's not that it's outdated, it's just buggy.

2021-04-22 16:58 UTC, bryceml approved these changes

2021-04-26 18:16 UTC, twangboy approved these changes

2021-04-26 18:24 UTC, merged