Merge pull request #49901 from twangboy/fix_startup_issues
saltstack/salt pull request #58048
Opened 2020-07-28 17:36 UTC by twangboy

### What does this PR do?
Fix issues with startup in Windows

### What issues does this PR fix or reference?
Merges #49901 into master branch

2020-08-11 22:50 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-08-28 10:05 UTC, DmitryKuzmenko requested changes
Found just one mistype. Other things are good.

2020-08-28 10:05 UTC, DmitryKuzmenko commented on salt/grains/core.py
> +            "biosversion": __salt_gg_["smbios.get"]("bios-version"),
`__salt_gg_` is a mistype?

2020-08-28 10:07 UTC, DmitryKuzmenko approved these changes

2020-08-28 10:07 UTC, DmitryKuzmenko commented on salt/grains/core.py
> +            "biosversion": __salt_gg_["smbios.get"]("bios-version"),
I've updated it.

2020-08-28 18:53 UTC, twangboy commented
@DmitryKuzmenko Thanks for catching that!

2020-09-09 20:33 UTC, merged