[merge jam] port 49200
saltstack/salt pull request #58045
Opened 2020-07-28 15:37 UTC by waynew

### What does this PR do?

Ports #49200

### What issues does this PR fix or reference?

N/A

### New Behavior

user/passwd functionality added to couchdb returner

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2022-10-27 21:58 UTC, twangboy requested changes
Pretty sure this will need some tests as well

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +
Is there a reason this try statement is in here twice?

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        auth_basic = "Basic {0}".format(auth_encode)
Pretty sure these format statements will need to have the numbers removed. So just `{}`

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +    Create a object that will be saved into the database based in
Create **_an_** object that will be saved into the database based **_on_**

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +            )
You can use newer formatting strings with log messages:
```
log.error(
    'Nothing logged! Lost data. Unable to create database "%s"', options["db"]
)

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +            log.debug("_response object is: {0}".format(_response))
```
log.debug("_response object is: %s", _response)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        )
Should this maybe be a warning?

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +    log.debug("events data is: {}".format(events))
```
log.debug("events data is: %s", events)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        log.info('Creating database "{0}"'.format(event_db))
```
log.info('Creating database "%s"', event_db)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +            )
```
log.error(
    'Nothing logged! Lost data. Unable to create database "%s"', event_db
)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        log.info('Created database "{0}"'.format(event_db))
```
log.info('Created database "%s"', event_db)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        log.debug("event data is: {}".format(event))
```
log.debug("event data is: %s", event)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +            )
```
log.error(
    'Nothing logged! Lost data. Unable to create document: "%s"', _response
)
```

2022-10-27 21:58 UTC, twangboy commented on salt/returners/couchdb_return.py
> +        log.error('Unable to get JID "{0}" : "{1}"'.format(jid, _response))
```
log.error('Unable to get JID "%s" : "%s"', jid, _response)
```

2023-12-10 09:17 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 09:17 UTC, closed without merging