[PR port] Port #53823 - Enable master stats for tests
saltstack/salt pull request #58099
Opened 2020-07-30 16:54 UTC by barneysowood

PR port #53823
- [ ] Docs
- [X] Changelog
- [ ] Tests written/updated

2020-07-30 16:55 UTC, Akm0d submitted a review, later dismissed

2022-09-28 19:47 UTC, Ch3LL commented
@barneysowood would you mind resolving the merge conflicts?

2022-11-08 19:08 UTC, barneysowood commented
> @barneysowood would you mind resolving the merge conflicts?

@Ch3LL - no problem, I've done that now.

2022-11-16 20:53 UTC, Ch3LL requested changes

2022-11-16 20:53 UTC, Ch3LL commented on salt/master.py
> +            log.error("STATS %s", pprint.pformat(stats_last))
I wonder if we want to error here. I know you weren't the original author so @dwoz do you still want to log error here. Seems a bit noisy

2023-12-20 21:00 UTC, twangboy requested changes

2023-12-20 21:00 UTC, twangboy commented on salt/master.py
> +import pprint
This is probably your pre-commit failure... pprint is unused

2026-06-15 21:05 UTC, dwoz commented
Rebased on current master and stripped the PR down to its functional core:

- Removed `log.error("STATS ...")` and `pprint` import (addressed @Ch3LL's review feedback)
- Removed `latency` field from stats defaultdict (was unused; not in the original #53823 scope)
- Added `master_stats: true` to integration test master conf (the original intent)
- Updated changelog to current format (`58099.changed.md`)

2 files changed, net +4 lines.

2026-07-01 17:31 UTC, twangboy approved these changes

2026-07-03 11:53 UTC, merged