master function unable to detect connection to master on ipv6 address
saltstack/salt pull request #58095
Opened 2020-07-30 14:21 UTC by trootnev

### What does this PR do?
If minion and master are connected only using ipv6 addresses then this function always returns false marking minion disconnected. This causes minion stopping returning any results back to master after 1 hour because by default once in an hour the scheduled job calls state.master.
The root cause is that the function is using netstat command output with parameter -n -p TCP. It shows only IPv4 connections. To see both IPv4 and IPv6 we need to omit -p parameter completely and filter out non-TCP connections afterwards. Also we need to remove square brackets in IPv6 addresses returned as we will compare those to the ones without brackets later in code.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Every time the master function run on windows minion with only IPv6 address connected to salt-master it (function) used to conclude that minion is disconnected and responses were sent since that moment until minion restart.

### New Behavior
Minion connection status gets evaluated correctly on both IPv6 and IPv4 addresses

### Merge requirements satisfied?
No. Sorry, Windows environment is used, test setup is too complicated for Windows. This change is very easy to check and I checked it in my test environment manually.
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-07-30 16:25 UTC, trootnev commented
something's clearly wrong with those tests... Linux-related tests are failing on something unrelated to what has been changed and the module itself is aiming windows systems only.

2020-08-06 22:04 UTC, cmcmarrow requested changes
@trootnev thanks for the PR! If you need help with pre-commit please read https://pre-commit.com/. Also this PR still needs a test.

2021-08-23 16:07 UTC, waynew commented on salt/modules/win_status.py
> +            remotes.add(remote_host.replace('[', '').replace(']', ''))
**question** would it be a good idea to use the [`ipaddress` module](https://docs.python.org/3/library/ipaddress.html) here, or is that overkill?

2022-01-14 20:06 UTC, garethgreenaway commented
@trootnev Following up on this one and checking that you saw the comments above, as well as the request for a automated test.  Thanks!

2023-12-10 09:47 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 09:47 UTC, closed without merging