[merge jam] Master port 49261
saltstack/salt pull request #58101
Opened 2020-07-30 19:24 UTC by garethgreenaway

### What does this PR do?
Master port 49261

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-08-31 18:03 UTC, waynew requested changes
This does need a `changelog` file. Otherwise 👍

2021-04-14 16:44 UTC, krionbsd approved these changes, later dismissed

2021-04-14 19:32 UTC, twangboy submitted a review, later dismissed

2021-11-22 18:18 UTC, waynew submitted a review, later dismissed

2021-12-13 22:38 UTC, waynew approved these changes, later dismissed
I'm pretty sure those were flaky test failures. Re-running the tests.

2022-01-05 00:22 UTC, waynew commented
@garethgreenaway looks like black/pre-commit failures, wanna run that locally?

2022-01-19 19:55 UTC, Ch3LL requested changes

2022-01-19 19:55 UTC, Ch3LL commented on salt/modules/consul.py
> +        ret["message"] = "Updating ACL " "{} failed.".format(kwargs["name"])
```suggestion
        ret["message"] = "Updating ACL {} failed.".format(kwargs["name"])
```

2022-01-19 19:55 UTC, Ch3LL commented on salt/states/consul.py
> +
Can you add a versioned added for 3004?

2022-01-19 21:11 UTC, garethgreenaway commented on salt/states/consul.py
> +
Should be 3005 right?

2022-01-19 21:39 UTC, Ch3LL commented on salt/states/consul.py
> +
yeah lol

2022-01-19 21:41 UTC, Ch3LL approved these changes

2022-01-20 21:19 UTC, merged