Reconfigure syndic publication to publish to all upstream masters
saltstack/salt pull request #58194
Opened 2020-08-13 19:09 UTC by MasonEdgel

### What does this PR do?
Solves an issue with events being forwarded to only one master by syndic nodes.

### What issues does this PR fix or reference?
Fixes: #58193 

### Previous Behavior
Would return on first successful master pub

### New Behavior
Publishes to all masters possible and returns a failure if none are successful

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-09-09 19:30 UTC, Ch3LL commented
ping @DmitryKuzmenko would you mind giving this a review since i believe you have previously been in this part of the code.

2020-09-09 20:38 UTC, DmitryKuzmenko commented
The changed behavior could be a problem if the failure reason was a temporary master overload. I'll take a deeper look at this tomorrow.

2020-09-10 13:41 UTC, DmitryKuzmenko commented on salt/minion.py
> -                        return False
The idea of this block is: if syndic still has unsent data for the targeted master at this moment it means we got back here too fast and the data wasn't sent yet.
Full removal of this block would make syndic sending data randomly to different masters when syndic is on load. I'd better suggest to write good tests for the particular case you're trying to resolve first to have a way to check the fix works in the correct way.

2020-09-10 13:41 UTC, DmitryKuzmenko commented
Also I'd be glad to discuss possible scenarios to get a clear look to the problem.

2020-09-17 16:49 UTC, MasonEdgel commented
@DmitryKuzmenko Thank you for the context!  I wasn't aware the return value would be used to attempt a republish in the future.  With that in mind, I've adjusted the PR and confirmed it still works as expected.

2020-09-23 10:46 UTC, Ch3LL requested changes

2020-09-23 10:46 UTC, Ch3LL commented on doc/man/salt.7
> -.SS \fBsyndic_forward_all_events\fP
this file should not be directly edited. It will be generated at release time

2020-09-24 08:54 UTC, DmitryKuzmenko commented
@MasonEdgel now there's a possible situation when `self.delayed` contents would be updated multiple times with the same content.
There are to major points regarding your idea:
1. Such behavior change must be configurable. Someone would like to send pubs back to the source master only. Someone wants always receive the pubs by all masters.
2. If you want to send pubs to all masters it's better to implement it separately. At least each master will have it's own unsent queue. Maybe it's better to try to move to asyncio queues.
And last but not least: we require tests for any code change in a PR.

2023-12-10 09:51 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 09:51 UTC, closed without merging