Add ~user expansion for various git states
saltstack/salt pull request #58242
Opened 2020-08-19 09:15 UTC by dkacar-oradian

### What does this PR do?

Add ~user expansion for the target parameter in git.{cloned,detached,latest} states.

Note that ~user expansion already works for `git.present`, so there's no need to add it.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior

Test file:

```
latest:
  git.latest:
    - name: https://github.com/saltstack/salt-bootstrap.git
    - target: ~dave/salt-bootstrap
    - branch: master
    - user: dave
    
cloned:
  git.cloned:
    - name: https://github.com/saltstack/salt-bootstrap.git
    - target: ~dave/salt-bootstrap
    - branch: master
    - user: dave
    
detached:
  git.detached:
    - name: https://github.com/saltstack/salt-bootstrap.git
    - target: ~dave/detached-bootstrap
    - rev: develop
    - user: dave
```
Running it gives this:
```
----------
          ID: latest
    Function: git.latest
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: False
     Comment: target '~dave/salt-bootstrap' is not an absolute path
     Started: 11:04:55.859000
    Duration: 5.994 ms
     Changes:   
----------
          ID: cloned
    Function: git.cloned
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: False
     Comment: 'target' path must be absolute
     Started: 11:04:55.865580
    Duration: 4.093 ms
     Changes:   
----------
          ID: detached
    Function: git.detached
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: False
     Comment: Target '~dave/detached-bootstrap' is not an absolute path
     Started: 11:04:55.870181
    Duration: 4.346 ms
     Changes:   
```

### New Behavior
Now it works.

```
----------
          ID: latest
    Function: git.latest
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: True
     Comment: https://github.com/saltstack/salt-bootstrap.git cloned to /home/dave/salt-bootstrap. Branch 'master' checked out, with remote HEAD (69bfde2) as a starting point.
     Started: 11:08:53.001141
    Duration: 3929.469 ms
     Changes:   
              ----------
              new:
                  https://github.com/saltstack/salt-bootstrap.git => /home/dave/salt-bootstrap
              revision:
                  ----------
                  new:
                      69bfde2d63e155d8c98b1bc85568b297cc8418df
                  old:
                      None
----------
          ID: cloned
    Function: git.cloned
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: True
     Comment: Repository already exists at /home/dave/salt-bootstrap and is checked out to branch 'master'
     Started: 11:08:56.931151
    Duration: 148.563 ms
     Changes:   
----------
          ID: detached
    Function: git.detached
        Name: https://github.com/saltstack/salt-bootstrap.git
      Result: True
     Comment: https://github.com/saltstack/salt-bootstrap.git cloned to /home/dave/detached-bootstrap. Commit ID 69bfde2d63e155d8c98b1bc85568b297cc8418df was checked out at /home/dave/detached-bootstrap.
     Started: 11:08:57.080597
    Duration: 3999.005 ms
     Changes:   
              ----------
              HEAD:
                  ----------
                  new:
                      69bfde2d63e155d8c98b1bc85568b297cc8418df
                  old:
                      None

```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-08-19 09:23 UTC, krionbsd commented
@dkacar-oradian thank you for contribution! Could you please run pre-commit hook and re-commit your changes? It would be also awesome if you could add a test case for your changes in `tests/unit/states/test_git.py`

2020-08-19 09:24 UTC, krionbsd requested changes
@dkacar-oradian thank you for contribution! Could you please run pre-commit hook and re-commit your changes? It would be also awesome if you could add a test case for your changes in tests/unit/states/test_git.py

2020-08-19 11:16 UTC, dkacar-oradian commented
Tests for this should go into `tests/integration/states/test_git.py`, I think. I've been looking at that a bit, but I don't understand much. Maybe one of these days.

2023-12-10 09:51 UTC, closed without merging

2023-12-10 09:51 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.