Fix dnsutil.parse_zone SOA parsing
saltstack/salt pull request #58285
Opened 2020-08-26 09:41 UTC by codeurimpulsif

### What does this PR do?

- Parse SOA record of a zone file when TTL and Class are present or absent
- Handle all DNS classes from [section 3.2.4 of RFC 1035](https://tools.ietf.org/html/rfc1035#section-3.2.4)

Thanks to @madrisan for his help

### What issues does this PR fix or reference?
Fixes: #26315 

### Previous Behavior
Can't parse SOA record from zone file

### New Behavior
Can parse SOA record from zone file and handle other classes

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2020-08-27 14:07 UTC, Ch3LL requested changes
can we get a changelog entry (https://docs.saltstack.com/en/master/topics/development/changelog.html) and a regression test added. We are currently working on migrating our test runner to pytest so with any new tests it would be great if you can add them to tests/pytests instead so we do not have to migrate them later on.

2020-08-28 08:15 UTC, codeurimpulsif commented
> can we get a changelog entry (https://docs.saltstack.com/en/master/topics/development/changelog.html) 

Yes, I just added it :smiley: 

> and a regression test added. We are currently working on migrating our test runner to pytest so with any new tests it would be great if you can add them to tests/pytests instead so we do not have to migrate them later on.

I'm not familiar with pytest but I can try, will take some time though. So if anyone else wants to do it: go ahead.

2020-10-28 11:32 UTC, Ch3LL commented
just checking back in here @codeurimpulsif did you need some direction to add a test here?

2020-10-29 11:13 UTC, madrisan commented
I can try to add the required test myself. A documentation is available?

2020-11-03 14:42 UTC, Ch3LL commented
thanks @madrisan . The test documentation is located here: https://docs.saltstack.com/en/master/topics/tutorials/writing_tests.html

let me know if you need more direction. thanks!

2023-12-10 09:56 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 09:56 UTC, closed without merging