[x509] Fix comparison of certificate values
saltstack/salt pull request #58296
Opened 2020-08-26 21:06 UTC by alxwr

### What does this PR do?

### What issues does this PR fix or reference?
Fixes an aspect of #56556

### Previous Behavior
Freshly created certificates are overwritten during the next run because the comparison of the certificate's values didn't work.

i.e.:

```                                                                    
              Status:                                                                                                 
                  ----------                                                                                          
                  New:                                                                                                
                      Certificate is valid and up to date                                                             
                  Old:                                                                                                
                      Certificate properties are different: Public Key
```

Acutally, the public key did not change!

### New Behavior

The certificate is not changed any more at very run of `salt`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs (none changed, this is a bugfix
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written

### Commits signed with GPG?
No

----

@glynnforrest @s0undt3ch This may interest you.

2020-08-27 14:10 UTC, Ch3LL requested changes
looks like there is a failing test that needs to be investigated

2020-08-31 21:12 UTC, Ch3LL requested changes

2020-08-31 21:23 UTC, s0undt3ch commented on salt/states/x509.py
> +        if type(v) == str:
Why type and not isinstance?

2020-09-08 21:59 UTC, alxwr commented on salt/states/x509.py
> +        if type(v) == str:
Thanks, good catch!

2020-09-08 22:04 UTC, alxwr commented on CHANGELOG.md
> +- Fixed comparison of certificate values
Thanks, didn't know that! (TIL) :-)

2020-09-09 07:19 UTC, alxwr commented
@Ch3LL @s0undt3ch I added your requested changes. Please review! Thanks! :-)

2020-09-09 20:33 UTC, Ch3LL submitted a review, later dismissed

2020-09-09 20:34 UTC, Ch3LL commented
looks like you have a merge conflict that needs to be cleaned up

2020-09-20 08:39 UTC, alxwr commented
@Ch3LL Please review again! :-)

2020-10-12 20:46 UTC, Ch3LL approved these changes

2020-11-12 23:55 UTC, s0undt3ch approved these changes

2020-11-13 03:29 UTC, merged

2020-11-21 20:45 UTC, alxwr commented
@dwoz  Thanks! 🎊