[master] Ensure proxy_config reads proxy specific configuration
saltstack/salt pull request #58307
Opened 2020-08-27 22:21 UTC by garethgreenaway

### What does this PR do?
Make proxy_config read in the proxy specific configuration which is typically found in /etc/salt/proxy.d/minionid/.

### What issues does this PR fix or reference?
Fixes: #58146 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-08-28 09:29 UTC, DmitryKuzmenko approved these changes

2020-08-28 09:42 UTC, DmitryKuzmenko requested changes

2020-08-28 09:42 UTC, DmitryKuzmenko commented on salt/config/__init__.py
> +        mod_fun, fun_kwargs = next(opts["id_function"].items())
```suggestion
        mod_fun, fun_kwargs = next(iter(opts["id_function"].items()))
```

2020-08-28 11:01 UTC, DmitryKuzmenko commented on salt/config/__init__.py
> +        mod_fun, fun_kwargs = next(opts["id_function"].items())
Fixed

2020-08-28 11:01 UTC, DmitryKuzmenko approved these changes, later dismissed

2020-08-28 15:13 UTC, garethgreenaway commented on salt/config/__init__.py
> +        mod_fun, fun_kwargs = next(opts["id_function"].items())
Thanks @DmitryKuzmenko!

2020-09-15 15:41 UTC, DmitryKuzmenko submitted a review, later dismissed

2020-10-02 10:00 UTC, merged