Loader fix
saltstack/salt pull request #58332
Opened 2020-08-31 15:52 UTC by cbosdo

### What does this PR do?

Refactor the way the virtual machine description XML is modified in `virt.udpate()`. This has two advantages:
  * it makes it easier to modify more values in the future
  * properly handles the boot parameters modifications (issue #58331)

### What issues does this PR fix or reference?
Fixes: #58331

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

2020-08-31 16:27 UTC, Akm0d commented
re-run full all

2020-08-31 16:28 UTC, Akm0d submitted a review, later dismissed

2020-09-01 06:22 UTC, krionbsd commented
re-run all

2020-09-01 06:27 UTC, krionbsd commented
re-run all

2020-09-01 07:43 UTC, cbosdo commented
Rebased on master, fixed the black issues (how comes they weren't there yesterday?) and add the changelog file that I forgot to `git add`

2020-09-01 16:57 UTC, cbosdo commented
rebased on master, removed the black changes due to new version rollback.

2020-09-01 20:43 UTC, s0undt3ch requested changes

2020-09-01 20:43 UTC, s0undt3ch commented on tests/unit/utils/test_data.py
> +def test_get_value_simple_path():
Please place these tests under `tests/pytests`

2020-09-01 20:43 UTC, s0undt3ch commented on tests/unit/utils/test_xmlutil.py
> +@pytest.fixture
Please place these under `tests/pytests`

2020-09-02 07:22 UTC, cbosdo commented
@s0undt3ch rebased on master and moved the new tests to the `tests/pytest` folder

2020-09-02 15:43 UTC, cbosdo commented
@s0undt3ch @Akm0d all tests green and the requested changes are in. Will hit the 'update branch' button

2020-09-02 15:43 UTC, Akm0d approved these changes

2020-09-02 20:58 UTC, s0undt3ch approved these changes

2020-09-03 07:04 UTC, cbosdo commented
@dwoz since it's all green now, could you merge it?

2020-09-04 22:21 UTC, merged