Allow filtering public/private IPv6 addresses in network.ip_addrs6
saltstack/salt pull request #58383
Opened 2020-09-04 18:06 UTC by rmcintosh

* Allow filtering public/private IPv6 addresses in network.ip_addrs6
* Clean up network.ip_addrs to match network.ip_addrs6

### What does this PR do?
This PR allows filtering private/public addresses when calling network.ip_addrs6, in the same way that network.ip_addrs allows doing this.

### What issues does this PR fix or reference?
Fixes: always getting e.g. link-local v6 addresses returned in network.ip_addrs6 output.

### Previous Behavior
Previously the output would always include e.g. link-local v6 addresses, which (from my POV) is probably not useful for most users.

### New Behavior
The output is the same by default, but if you pass the new "type" argument, you can get output with just the specified type of addresses.

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2020-09-04 18:10 UTC, rmcintosh commented on salt/modules/network.py
> +    if type == "public":
alternately, we can define the lists of addresses inside of each if statement and then have a single return at the bottom (for a function of this length/complexity, i'm not sure it matters, though)

2020-09-09 07:06 UTC, krionbsd commented
@rmcintosh thank you for contribution! Could you please run `pre-commit -av` and re-commit the changes? Could you please add a test case for this change?

2020-09-09 17:23 UTC, rmcintosh commented
@krionbsd I think I managed to wrangle the pre-commit - let me know if I somehow botched it (this is my first salt contribution when using that tool).

I'll get to work on adding a testcase 👍

2020-09-09 17:46 UTC, krionbsd commented
> @krionbsd I think I managed to wrangle the pre-commit - let me know if I somehow botched it (this is my first salt contribution when using that tool).
> 
> I'll get to work on adding a testcase 👍

That's awesome @rmcintosh ! Thank you so much!

2020-09-10 17:05 UTC, rmcintosh commented
@krionbsd I added a test case which accounts for calling the function with `type` set to each of `private`/`public`, as well as without the argument supplied 👍 let me know how it looks!

2020-09-10 17:07 UTC, rmcintosh commented on tests/unit/modules/test_network.py
> +        ipv6_addrs = ["fe80::f03c:91ff:fef1:21e3", "2600:3c03::f03c:91ff:fef1:21e3"]
I grabbed these examples from a random old machine of mine as python's IP address validation did not like purely example addresses that I had tried

2020-09-21 15:38 UTC, krionbsd approved these changes

2020-09-28 15:05 UTC, krionbsd submitted a review, later dismissed

2020-10-15 20:56 UTC, rmcintosh commented
I noticed some conflicts have arisen on this PR in the past couple of weeks - I assume you all would like me to get those fixed up for this to move forward?

2020-10-22 17:00 UTC, rmcintosh commented
conflicts resolved 👍

2020-10-24 17:03 UTC, krionbsd submitted a review, later dismissed

2021-03-26 16:17 UTC, rmcintosh commented
fixed the merge conflict on this one 👍🏽

2023-03-15 18:55 UTC, rmcintosh commented
Still willing to do anything necessary to get this one over the finish line 🙂

2023-03-15 19:35 UTC, Ch3LL commented
Looks like pre-commit is failing. Once its passing I'll give this a review.

2023-03-15 19:54 UTC, rmcintosh commented
@Ch3LL thank you for pointing that out and for your time 🙇🏽 I think I have resolved the pre-commit errors, please let me know if you notice anything else 👍🏽

2023-03-20 19:32 UTC, Ch3LL requested changes
Also it looks like you deleted salt/client/ssh/__init__.py which I believe is a mistake. Can you re-add that?

2023-03-20 19:32 UTC, Ch3LL commented on salt/modules/network.py
> +    addresses will be returned. Ditto for 'type'='private'.
Can you add a versionadded here for this new arg for the version 3007.0.

2023-03-20 19:32 UTC, Ch3LL commented on salt/modules/win_network.py
> +        If option set to 'public' then only public addresses will be returned.
same here, can you add a versionadded for 3007.0 for this new option.

2023-12-10 10:14 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 10:14 UTC, closed without merging