Add Welcome bot
saltstack/salt pull request #58414
Opened 2020-09-09 17:34 UTC by krionbsd

### What does this PR do?
Add Welcome bot

2020-09-09 17:36 UTC, bryceml commented
can we put links to all the resources mentioned?

```
   Community Wiki
    Salt’s Contributor Guide
    Join our Community Slack
    IRC on Freenode
    SaltStack YouTube channel
    SaltStackInc Twitch channel```

2020-09-09 17:45 UTC, krionbsd commented
> can we put links to all the resources mentioned?
> 
> ```
>    Community Wiki
>     Salt’s Contributor Guide
>     Join our Community Slack
>     IRC on Freenode
>     SaltStack YouTube channel
>     SaltStackInc Twitch channel```
> ```

yeah, forgot it, done

2020-09-09 18:01 UTC, bryceml submitted a review, later dismissed

2020-09-09 22:25 UTC, ScriptAutomate requested changes
Some suggestions on adding links to our Code of Conduct.

I'm also wondering whether we should need anything in here about the Working Groups? New contributors may not know of them. Maybe an additional link like:

```
- [SaltStack Working Groups](https://github.com/saltstack/community)
```

Rendering to:
- [SaltStack Working Groups](https://github.com/saltstack/community)

Though, I do think we should review and update the community repository `README.md` file, along with information about the `docs-hub` Documentation Working Group.

_Tagging @cassandrafaris and @sagetherage for input^_

2020-09-09 22:25 UTC, ScriptAutomate commented on .github/config.yml
> +  Please be sure to review our Code of Conduct. Also, check out some of our community
```suggestion
  Please be sure to review our [Code of Conduct](https://github.com/saltstack/salt/blob/master/CODE_OF_CONDUCT.md). Also, check out some of our community
```

2020-09-09 22:25 UTC, ScriptAutomate commented on .github/config.yml
> +  Please be sure to review our Code of Conduct. Also, check out some of our community
```suggestion
  Please be sure to review our [Code of Conduct](https://github.com/saltstack/salt/blob/master/CODE_OF_CONDUCT.md). Also, check out some of our community
```

2020-09-10 13:07 UTC, DmitryKuzmenko approved these changes
Probably it'd be good to add a direct link to Cassandra's profile in SaltCommunity Slack. But what Slack gives to me https://saltstackcommunity.slack.com/team/UQP614KNG doesn't work in my environment.

2020-09-10 17:53 UTC, ScriptAutomate commented
> Probably it'd be good to add a direct link to Cassandra's profile in SaltCommunity Slack. But what Slack gives to me https://saltstackcommunity.slack.com/team/UQP614KNG doesn't work in my environment.

The link to her profile properly opens when I open that link in Slack, for me.

2020-09-10 18:02 UTC, bryceml approved these changes

2020-09-14 15:54 UTC, sagetherage commented
> Some suggestions on adding links to our Code of Conduct.
> 
> I'm also wondering whether we should need anything in here about the Working Groups? New contributors may not know of them. Maybe an additional link like:
> 
> ```
> - [SaltStack Working Groups](https://github.com/saltstack/community)
> ```
> 
> Rendering to:
> 
>     * [SaltStack Working Groups](https://github.com/saltstack/community)
> 
> 
> Though, I do think we should review and update the community repository `README.md` file, along with information about the `docs-hub` Documentation Working Group.
> 
> _Tagging @cassandrafaris and @sagetherage for input^_

That is fine, those can be separate PRs in those repositories, correct? I can create issues for work to be done, but I cannot do that work this week, perhaps in 2 or 3 weeks.

2020-09-14 18:31 UTC, krionbsd commented
> https://saltstackcommunity.slack.com/team/UQP614KNG

doesn't work for me in browser, I think providing the email makes more sense though, as not everyone is ready to join the slack to ask the questions

2020-09-14 18:52 UTC, s0undt3ch approved these changes

2020-09-15 16:19 UTC, krionbsd commented
re-run full windows

2020-09-15 21:21 UTC, merged