Add missing import back missed the port
saltstack/salt pull request #58618
Opened 2020-10-02 23:18 UTC by xeacott

### What does this PR do?
This PR adds a import to the winrepo module, as the winrepo runner needs this import during runtime. The module does not need it, however this code by design has to exist in the module as the module is loaded first.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/58596

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-03 07:33 UTC, s0undt3ch requested changes
Six should not be re-added. We want to get rid of it.
The right approach is remove `six` usage in `salt/runners/winrepo.py`.

To achieve this in a simple way, edit `salt/runners/winrepo.py` and just add a new line to the end of it so pre-commit see's it as a changed file.
Then, try to commit the file.
Pre commit will remove Py2 code and any `six` usage it finds.
Clean up if necessary, and commit again.

If there are additional failures about the missing `six` import, clean those up too.

2020-10-04 21:46 UTC, xeacott commented
> Six should not be re-added. We want to get rid of it.
> The right approach is remove `six` usage in `salt/runners/winrepo.py`.
> 
> To achieve this in a simple way, edit `salt/runners/winrepo.py` and just add a new line to the end of it so pre-commit see's it as a changed file.
> Then, try to commit the file.
> Pre commit will remove Py2 code and any `six` usage it finds.
> Clean up if necessary, and commit again.
> 
> If there are additional failures about the missing `six` import, clean those up too.

Will do. Wasn't sure of the situation of six at this moment in time, so thanks for the headsup!

2020-10-09 06:43 UTC, s0undt3ch requested changes

2020-10-09 06:43 UTC, s0undt3ch commented on 58596.fixed
> +Add missing import back to winrepo.
This needs to change?

2020-10-09 13:55 UTC, twangboy approved these changes

2020-10-09 13:56 UTC, s0undt3ch approved these changes

2020-10-13 20:50 UTC, merged