added info logs
saltstack/salt pull request #58621
Opened 2020-10-03 14:49 UTC by singhsangeet7

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-04 06:51 UTC, s0undt3ch commented
Why?

2020-10-07 13:23 UTC, Ch3LL commented on salt/auth/file.py
> +    log.info("filetype is {}".format(filetype))
can you elaborate why you are adding these log statements?

2020-10-07 13:24 UTC, Ch3LL requested changes

2020-10-07 13:24 UTC, Ch3LL commented on salt/auth/file.py
> +    log.info("filetype is {}".format(filetype))
can you elaborate why you are adding these log statements?

2023-12-10 10:07 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 10:07 UTC, closed without merging