Added tests for "Master port 50826"
saltstack/salt pull request #58647
Opened 2020-10-06 08:04 UTC by chotea

Added tests for https://github.com/saltstack/salt/pull/57007
Did a rebase on Alexey's branch and added tests on top of it.

2020-10-06 20:12 UTC, Akm0d approved these changes

2020-10-15 16:43 UTC, cmcmarrow approved these changes

2020-10-20 22:24 UTC, twangboy approved these changes

2020-11-04 11:47 UTC, s0undt3ch requested changes

2020-11-04 11:47 UTC, s0undt3ch commented on salt/modules/opkg.py
> +def _process_restartcheck_result(rs_result, **kwargs):
Why do we need to use `**kwargs` instead of `always_restart_services=True`?

2020-11-04 11:47 UTC, s0undt3ch commented on salt/modules/opkg.py
> +    always_restart_services
Why isn't this added to the `install` function as a keyword argument?

2021-02-22 16:49 UTC, garethgreenaway commented
@chotea Looks like you've got some merge conflicts and some requests for changes from @s0undt3ch.  Mind swinging back on this one?

2021-09-15 14:07 UTC, s0undt3ch requested changes
Still think we might not need to use `**kwargs`

2023-12-10 10:07 UTC, closed without merging

2023-12-10 10:07 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.