Fix msgpack encoding/raw handling for older versions
saltstack/salt pull request #58658
Opened 2020-10-07 11:45 UTC by oeuftete

### What does this PR do?

This is an update of @jude's work in #57502, meant to address the outstanding change requests.

### What issues does this PR fix or reference?
Fixes: #57501

### Previous Behavior

A deprecation warning was logged in the minion logs.

### New Behavior

No deprecation warning is logged.

### Merge requirements satisfied?

- n/a Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?

No

2020-10-07 13:17 UTC, Ch3LL requested changes

2020-10-07 13:17 UTC, Ch3LL commented on salt/utils/msgpack.py
> -        kwargs.setdefault("raw", True)
why removing this? This is needed for msgpack versions 1.0.0

2020-10-07 13:17 UTC, Ch3LL commented on salt/serializers/msgpack.py
> -            options.setdefault("raw", False)
why are we removing the options here and on https://github.com/saltstack/salt/pull/58658/files#diff-0d5904efab02aab32413f541cbd67382L66 ? Different versions of msgpack will support different args.

2020-10-07 13:17 UTC, Ch3LL commented on salt/utils/msgpack.py
> +    if version >= (0, 5, 2):
Would be best to define this as versions >= 0.5.2 and <1.0.0 to ensure we do not hit this if statement when running versions >= 1.0.0

2020-10-24 16:28 UTC, oeuftete commented
The work I added was overreaching and wrong.  (Other than that...)

#57501 appears to have been fixed as a result of other improvements, so closing this one up.

2020-10-24 16:28 UTC, closed without merging