Do not access /var/lib/dpkg/info/<package>.list directly
saltstack/salt pull request #58735
Opened 2020-10-15 17:22 UTC by bdrung

salt contains modules, which directly access the dpkg internal database, instead of using one of the public interfaces provided by dpkg. This is a problem for several reasons, because even though the layout and format of the dpkg database is administrator friendly, and it is expected that those might need to mess with it, in case of emergency, this “interface” does not extend to other programs besides the dpkg suite of tools. The admindir can also be configured differently at dpkg build or run-time. And finally, the contents and its format, will be changing in the near future.

So use something like:

```
dpkg-query --showformat '${db-fsys:Last-Modified}\n' --show $pkg
```

to get the mtime from /var/lib/dpkg/info/<package>.list files.

This merge request is a first of three commits to address all occurrences.

Bug: https://github.com/saltstack/salt/issues/52605
Bug-Debian: https://bugs.debian.org/944970

2020-10-21 17:41 UTC, cmcmarrow approved these changes, later dismissed

2020-10-21 17:42 UTC, cmcmarrow commented
@bdrung thanks for the fix!

2020-11-09 14:00 UTC, krionbsd submitted a review, later dismissed

2021-12-11 14:31 UTC, bdrung commented
Rebased on master.

2021-12-17 09:36 UTC, bdrung commented
Any updates on this? maybe @Ch3LL?

2022-12-14 20:11 UTC, Ch3LL commented
Looks like some of the test failures are related. I can give a review once they are cleaned up. Thanks

2025-04-01 19:16 UTC, twangboy requested changes
This needs a changelog. The test needs to be migrated to pytests. This needs to be rebased and conflicts resolved.

2026-06-12 23:47 UTC, dwoz approved these changes

2026-06-12 23:47 UTC, merged