salt.returners demote log statements to debug
saltstack/salt pull request #58740
Opened 2020-10-15 23:42 UTC by jfindlay

These logs tend to produce a great amount of low value log records which
would not be useful unless you were debugging returner code.  For
example:

```
2020-10-12 12:37:04,228 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
2020-10-12 12:37:04,232 [salt.returners   :166 ][INFO    ] Using default for db_returner ignored_retcodes
2020-10-12 12:37:04,235 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
2020-10-12 12:37:04,246 [salt.returners   :166 ][INFO    ] Using default for db_returner ignored_retcodes
2020-10-12 12:37:04,248 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
2020-10-12 12:37:04,252 [salt.returners   :166 ][INFO    ] Using default for db_returner ignored_retcodes
2020-10-12 12:37:04,255 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
2020-10-12 12:37:04,265 [salt.returners   :166 ][INFO    ] Using default for db_returner ignored_retcodes
2020-10-12 12:37:04,267 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
2020-10-12 12:37:04,270 [salt.returners   :166 ][INFO    ] Using default for db_returner ignored_retcodes
2020-10-12 12:37:04,272 [salt.returners   :166 ][INFO    ] Using default for db_returner db_path
```

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-15 23:44 UTC, Akm0d approved these changes, later dismissed

2020-10-17 07:39 UTC, s0undt3ch approved these changes
Justin!!! How are you?

2020-10-17 07:42 UTC, s0undt3ch requested changes
Oh, you need pre-commit to run against your changed file.

```
pip install pre-commit
git reset --soft HEAD~1
git commit -av
```
The above should do it since you have 1 commit in this PR.

2020-11-03 21:14 UTC, jfindlay commented
Hi Pedro, things are going great.  It looks like you have tuned up this code change process quite well.

2021-03-05 09:22 UTC, s0undt3ch approved these changes

2021-03-05 17:26 UTC, twangboy approved these changes

2021-04-06 18:36 UTC, Ch3LL approved these changes

2021-04-06 18:36 UTC, merged