fix virt if
saltstack/salt pull request #58833
Opened 2020-10-28 16:47 UTC by cmcmarrow

### What does this PR do?
fixes redundant if statement
  
### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/58683

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-28 18:30 UTC, Akm0d approved these changes, later dismissed

2020-10-28 21:53 UTC, cmcmarrow commented
tests/unit/modules/test_virt.py
and
tests/unit/states/test_virt.py

both pass

2020-11-05 23:36 UTC, dwoz requested changes

2020-11-05 23:36 UTC, dwoz commented on salt/modules/virt.py
> -
This has the potential of returning None now. Is that intended?

2020-11-05 23:36 UTC, dwoz commented on tests/unit/modules/test_virt.py
> -      <acpi default='on' toggle='yes'/>
Do we only want to test the case where this is True or should we test with both True and False?

2020-11-10 22:02 UTC, merged