Port pkgrepo and pkg support for Photon OS
saltstack/salt pull request #58856
Opened 2020-11-01 17:15 UTC by oeuftete

### What does this PR do?

Ports @lomeroe's #51912 and #52550, which added `pkg` and `pkgrepo` support, respectively, for VMWare's Photon OS.

### Merge requirements satisfied?

- [ ] Docs
  - needs reference somewhere along with annotation of the added version
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?

No

2020-11-24 20:25 UTC, dwoz approved these changes, later dismissed

2020-11-24 20:34 UTC, s0undt3ch requested changes

2020-11-24 20:34 UTC, s0undt3ch commented on salt/modules/rpm_lowpkg.py
> +    if not isinstance(ignore_types, (list, (str,))):
```suggestion
    if not isinstance(ignore_types, (list, str)):
```

2020-11-24 20:34 UTC, s0undt3ch commented on salt/modules/rpm_lowpkg.py
> +    if not isinstance(verify_options, (list, (str,))):
```suggestion
    if not isinstance(verify_options, (list, str)):
```

2020-11-24 20:58 UTC, s0undt3ch approved these changes, later dismissed

2020-12-15 21:24 UTC, whytewolf commented
Just my own two cents about this PR, Since proton, isn't its own os_family but is a Redhat variant. the os_family should be mapped to RedHat. This will make a lot of these changes have less bite as well as making the tests easier as not as many changes are needed.

2020-12-15 21:36 UTC, oeuftete commented on salt/modules/rpm_lowpkg.py
> +    enabled = ("amazon", "xcp", "xenserver", "virtuozzolinux")
Not directly related to this PR, but found this to be incorrect along the way.

2020-12-15 21:42 UTC, oeuftete commented
> Just my own two cents about this PR, Since proton, isn't its own os_family but is a Redhat variant. the os_family should be mapped to RedHat. This will make a lot of these changes have less bite as well as making the tests easier as not as many changes are needed.

Thanks @whytewolf, I think this is the right approach.  I've made the fixes.

2020-12-22 01:27 UTC, lomeroe commented
The changelog definitely needs to mention that photon will now have an os_family of "RedHat".  Anyone like me using "VMware Photon OS" or "VMware Photon" in a default "grains.filter_by" statement start getting unexpected results with that portion of the update.

2020-12-22 10:03 UTC, s0undt3ch submitted a review, later dismissed

2020-12-22 10:06 UTC, s0undt3ch commented
> The changelog definitely needs to mention that photon will now have an os_family of "RedHat". Anyone like me using "VMware Photon OS" or "VMware Photon" in a default "grains.filter_by" statement will start getting unexpected results with that portion of the update

Actually, besides mentioning this on the changelog, it's worthy of a release notes entry.

https://github.com/saltstack/salt/blob/master/doc/topics/releases/3003.rst

2020-12-22 16:47 UTC, oeuftete commented
> The changelog definitely needs to mention that photon will now have an os_family of "RedHat". Anyone like me using "VMware Photon OS" or "VMware Photon" in a default "grains.filter_by" statement will start getting unexpected results with that portion of the update.

@lomeroe @s0undt3ch Good feedback, thanks.  I've added additional docs in 8549c3f708.

2021-01-04 09:35 UTC, s0undt3ch approved these changes, later dismissed

2021-02-04 12:01 UTC, Ch3LL commented
Looks like there is a merge conflict here @oeuftete

2021-02-04 13:44 UTC, oeuftete commented
> Looks like there is a merge conflict here @oeuftete

Thanks for the reminder @Ch3LL.  Hopefully this rebase is the last one. :)

2021-02-04 17:13 UTC, Ch3LL approved these changes

2021-02-04 17:50 UTC, s0undt3ch approved these changes

2021-02-04 18:31 UTC, merged