Gate elasticsearch runner requirements
saltstack/salt pull request #58851
Opened 2020-10-30 19:18 UTC by garethgreenaway

### What does this PR do?
Ensure that elasticsearch.index_exists is available before loading the elasticsearch returner.

### What issues does this PR fix or reference?
Fixes: #58015 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-30 19:19 UTC, cmcmarrow approved these changes, later dismissed

2020-10-30 19:19 UTC, cmcmarrow submitted a review, later dismissed

2020-11-04 11:38 UTC, s0undt3ch requested changes
Don't log on `__virtual__`, return `False, "the error"` instead...

2020-11-04 11:38 UTC, s0undt3ch commented on salt/returners/elasticsearch_return.py
> +        return False
```suggestion
        return False, "Elasticsearch module not availble.  Check that the elasticsearch library is installed."
```

2020-11-12 22:57 UTC, dwoz approved these changes

2020-11-12 22:57 UTC, merged