Updating email references from nmadhok@clemson.edu to nmadhok@g.clemson.edu
saltstack/salt pull request #58919
Opened 2020-11-11 09:35 UTC by nmadhok

# What does this PR do?
Updates email references from nmadhok@clemson.edu to nmadhok@g.clemson.edu

### Commits signed with GPG?
Yes

2021-02-03 13:42 UTC, Ch3LL requested changes

2021-02-03 13:42 UTC, Ch3LL commented on doc/man/salt.7
> +\fBAuthor\fP: Nitin Madhok <\fI\%nmadhok@g.clemson.edu\fP>
the man pages should not be edited directly. They are generated at release time

2021-02-11 19:11 UTC, Ch3LL approved these changes

2021-02-16 16:09 UTC, twangboy approved these changes

2021-02-16 16:09 UTC, garethgreenaway approved these changes

2021-02-16 16:15 UTC, merged