58944 added requirements parsing fix
saltstack/salt pull request #58945
Opened 2020-11-13 18:42 UTC by jweede

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #58944 

### Previous Behavior
invalid requirements link parsing

### New Behavior
extracts requirements file links correctly.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [?] Docs
- [?] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

2020-11-16 20:26 UTC, waynew commented
Hey @jweede, thanks for the PR! This definitely looks like an issue, and certainly one we should fix.

That being said, I'm not 100% sure if this fix is the one we really want :thinking:

@s0undt3ch -- do you have any opinion/thoughts here?

2020-11-16 20:52 UTC, s0undt3ch commented
Hmm, we should either fix the regex or `.rsplit("#", 1)` each line. Or use pip's parsing machinery to parse the lines....
Shlex might not be the best approach....

We do have to look out for requirements that look like `git+https://domain.tld/git#egg=PackageName`....

2020-11-16 21:12 UTC, jweede commented
Thanks @s0undt3ch. That makes sense. I assumed since pip docs and code mention `shlex` that would be enough. 

I read over their reqs parsing code a little closer this time and noticed they strip comments out via `COMMENT_RE = re.compile(r'(^|\s+)#.*$')`. I could rewrite the PR to use this and a version of the prior regex to find requirements links while ignoring comments.

2020-11-16 21:18 UTC, s0undt3ch commented
@jweede that would be awesome!

2020-11-16 22:10 UTC, s0undt3ch requested changes

2020-11-16 22:10 UTC, s0undt3ch commented on tests/unit/modules/test_pip.py
> +                        b"-e git+ssh://git.example.com/MyProject#egg=MyProject # the project\n"
Let's duplicate this one, this time without the comment in front. Please  :)

2020-11-16 22:28 UTC, s0undt3ch submitted a review, later dismissed
Superb!

2020-11-20 15:48 UTC, cmcmarrow approved these changes, later dismissed

2020-11-23 02:33 UTC, s0undt3ch commented
re-run all

2021-06-16 02:35 UTC, sagetherage commented
@jweede can you rebase this against the `master` branch, please? we are no longer accepting changes on `develop` thank you!

2021-06-16 13:36 UTC, jweede commented
@sagetherage rebased to master :+1:

2021-07-15 17:59 UTC, Ch3LL requested changes
looks like there is a merge conflict and this will also require a changelog entry.

2021-07-15 18:42 UTC, jweede commented
@Ch3LL resolved the conflict and added a changelog entry as requested :+1:

2021-07-20 18:11 UTC, Ch3LL approved these changes

2021-07-21 18:40 UTC, sagetherage commented
re-run pr-centosstream-8-x86_64-py3-pytest

2021-08-18 12:30 UTC, s0undt3ch approved these changes

2021-08-18 12:40 UTC, merged