fix formatting for terse output mode
saltstack/salt pull request #58953
Opened 2020-11-15 15:40 UTC by erwindon

### What does this PR do?
This PR fixes a small layout defect in the TERSE output mode for state information.

### What issues does this PR fix or reference?
None, a separate issue was not raised.

### Previous Behavior
Output was like:
`Name: apache2 - Function: pkg.installed - Result: Clean Started: - 06:03:52.163350 Duration: 20.209 ms`

### New Behavior
Output now like:
`Name: apache2 - Function: pkg.installed - Result: Clean - Started: 06:03:52.163350 Duration: 20.209 ms`
"`-`" was used to separates name-value pairs. The start of the line was fine. But the end of the line needed a few small corrections.

### Merge requirements satisfied?
- [ ] Docs
no docs to update; previous situation is not described in that detail
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated
no unit test need updates; previous situation was not tested

### Commits signed with GPG?
No

2022-10-20 15:18 UTC, twangboy approved these changes

2022-10-20 15:39 UTC, twangboy requested changes
Please provide a changelog and a test case.

2022-10-22 21:48 UTC, erwindon commented
ah, that was not a refresh button (i clicked re-request review)...
still need to add the testcase...

2022-11-14 17:00 UTC, twangboy approved these changes

2022-11-14 17:03 UTC, garethgreenaway approved these changes

2022-11-14 17:03 UTC, merged