Fix incorrect hostname quoting on Red Hat family OS
saltstack/salt pull request #58957
Opened 2020-11-16 19:45 UTC by ixs

network.mod_hostname() will incorrectly set a duplicate
hostname string in the configuration file. Fix that.

Fixes #58956

2020-12-08 13:40 UTC, Ch3LL requested changes
can you add a test for the issue this fixes?

2021-04-21 01:37 UTC, ixs commented
@Ch3LL Tests have been added.

2021-04-21 17:56 UTC, Ch3LL requested changes
Can you add a changelog and this will be good to go

2021-04-21 18:04 UTC, ixs commented
Done. @Ch3LL thanks for the review.

2021-04-21 18:06 UTC, Ch3LL approved these changes

2021-04-21 19:19 UTC, twangboy approved these changes

2021-04-21 19:41 UTC, garethgreenaway approved these changes

2021-04-21 19:44 UTC, merged