[BUGFIX] State 'pkg.installed' was not found fix for openEuler and Issabel PBX
saltstack/salt pull request #58973
Opened 2020-11-18 12:23 UTC by ioncebotari

### What does this PR do?
This PR adds support for package installation using Salt on openEuler and IssabelPBX.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/57490

### Previous Behavior
Installation would fail on both openEuler and Issabel PBX with the following error:
![image](https://user-images.githubusercontent.com/3043499/99529883-3cba8280-29a9-11eb-9cf8-1dc1c78b9dbc.png)

### New Behavior
Installation successful on both distributions. Tested manually using Virtualbox VMs

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-12-16 13:17 UTC, Ch3LL requested changes
can you add a changelog entry for this change?

2020-12-16 15:38 UTC, ioncebotari commented
@Ch3LL I've added the changelog. This is my first experience doing it, please review if done correctly. Thank you

2021-03-29 18:50 UTC, Ch3LL approved these changes

2021-03-29 18:51 UTC, Ch3LL commented
@ioncebotari apologies I let this one go a little too long. I resolved a merge conflict and the tests are running and then i'll get this merged.

2021-03-30 13:38 UTC, garethgreenaway approved these changes

2021-03-30 14:33 UTC, twangboy approved these changes

2021-03-30 17:22 UTC, merged