Add ssh shell unit tests
saltstack/salt pull request #58994
Opened 2020-11-20 19:43 UTC by Ch3LL

2020-11-20 20:23 UTC, s0undt3ch submitted a review, later dismissed

2020-11-20 23:30 UTC, garethgreenaway submitted a review, later dismissed

2020-11-22 09:56 UTC, s0undt3ch requested changes

2020-11-22 09:56 UTC, s0undt3ch commented on tests/unit/client/ssh/test_shell.py
> +
Decorate this class with the requires system binaries helper, the windows failures are valid

2020-11-24 20:52 UTC, s0undt3ch submitted a review, later dismissed

2021-04-30 09:11 UTC, s0undt3ch requested changes
Cleaner?

2021-04-30 09:11 UTC, s0undt3ch commented on tests/pytests/unit/client/ssh/test_shell.py
> +        assert ret.decode().startswith("ssh-rsa")
```suggestion
import os
import subprocess
import types

import pytest
import salt.client.ssh.shell as shell


@pytest.fixture
def keys(tmp_path):
    pub_key = tmp_path / "ssh" / "testkey.pub"
    priv_key = tmp_path / "ssh" / "testkey"
    return types.SimpleNamespace(pub_key=pub_key, priv_key=priv_key)


@pytest.mark.skip_on_windows(reason="Windows does not support salt-ssh")
@pytest.mark.skip_if_binaries_missing("ssh", "ssh-keygen", check_all=True)
def test_ssh_shell_key_gen(self, keys):
    """
    Test ssh key_gen
    """
    shell.gen_key(str(keys.priv_key))
    assert keys.priv_key.exists()
    assert keys.pub_key.exists()
     # verify there is not a passphrase set on key
    ret = subprocess.check_output(
        ["ssh-keygen", "-f", str(keys.priv_key), "-y"], timeout=30,
    )
    assert ret.decode().startswith("ssh-rsa")
```

2021-04-30 12:08 UTC, s0undt3ch approved these changes, later dismissed

2021-04-30 14:46 UTC, s0undt3ch approved these changes

2021-04-30 18:20 UTC, merged

2021-05-03 07:58 UTC, krionbsd commented
Should we add `__init__.py` into `tests/pytests/unit/client` ?
It seems `tests/unit/client/test_ssh.py` still exists, it's intended?
`tests/pytests/unit/client/ssh/test_ssh.py` misses `salt.utils.thin` and `salt.utils.parsers` imports