Fix Xen DomU detection in grains
saltstack/salt pull request #59001
Opened 2020-11-22 10:05 UTC by ixs

Current code has two issues:
 - Parses dmesg for "xen:" messages. This will only work when initial kernel
   messages are still available via dmesg. After some uptime other messages
   (e.g. OOM) will have evicted the initial boot messages from the ringbuffer.
   This leads to the weird situation that a grain changes depending on uptime.
 - Checks if /sys/bus/xen/drivers/xenconsole is a file to verify it's running
   under Xen. Unfortunately, this path is not a file but a directory.

This change swaps the order, first check for xenconsole being a directory, then
run dmesg as a fallback.

2020-12-07 14:45 UTC, Ch3LL requested changes
can we get test coverage for this change?

2021-04-21 07:33 UTC, ixs commented
@Ch3LL tests added.

2021-04-21 17:46 UTC, Ch3LL requested changes
Could you also add a changelog? If not I can push one.

2021-04-21 17:55 UTC, ixs commented
@Ch3LL done. Haven't done changelog files before, is that the right format and all?

2021-04-21 17:57 UTC, Ch3LL approved these changes

2021-04-21 19:21 UTC, twangboy approved these changes

2021-04-21 19:39 UTC, garethgreenaway approved these changes

2021-04-21 19:39 UTC, merged