Tests and delete() for SQLite3 SDB
saltstack/salt pull request #59109
Opened 2020-12-09 10:17 UTC by samilaine

### What does this PR do?

Add integration tests for SQLite3 SDB. The number of tests before: 0. The number of tests now: 6.

Add delete() fro SQLite3 SDB.

### What issues does this PR fix or reference?
-

### Previous Behavior
Calls to delete() for SDB using SQLite3 driver failed.

### New Behavior
Calls to delete() for SDB using SQLite3 driver do what they're supposed to do.

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog
- [X] Tests written/updated

### Commits signed with GPG?
No

2020-12-12 10:24 UTC, krionbsd approved these changes

2020-12-13 00:02 UTC, dwoz requested changes

2020-12-13 00:02 UTC, dwoz commented on tests/integration/sdb/test_sqlite3.py
> +#
This should be in the doc string above instead of a comment.

2020-12-13 00:02 UTC, dwoz commented on tests/integration/sdb/test_sqlite3.py
> +    # The test below tests that when the keyword argument "create" for the
This should be the test's docstring.. Something like:

```
When the keyword argument "create" for the  SQLite3 SDB driver is present and
 its value is True, any call to SDB will create the database.
```

2020-12-13 16:20 UTC, closed without merging