WIP: Module rh ip support ethtool set channels
saltstack/salt pull request #59134
Opened 2020-12-14 15:56 UTC by msciciel

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-01-08 10:28 UTC, msciciel commented
@cmcmarrow may I ask for some hint? I've changed my code to disappear from diff in `Pre-Commit / Run Pre-Commit Against Salt (pull_request)` test but it still fails and I have no clue why.

2021-01-20 19:59 UTC, sagetherage commented
> @cmcmarrow may I ask for some hint? I've changed my code to disappear from diff in `Pre-Commit / Run Pre-Commit Against Salt (pull_request)` test but it still fails and I have no clue why.

I apologize I missed this - I will get someone to help you with the dreaded pre-commit. @s0undt3ch @waynew can one of you help with pre-commit failures, here?

2021-01-20 20:09 UTC, ScriptAutomate commented
@msciciel For setting up `pre-commit`, check the following guidance:
- https://docs.saltproject.io/en/master/topics/development/contributing.html#pre-commit-and-nox-setup

In the above link, depending on how your dev environment is setup, you'll see how you need to install `pre-commit` via `pip`, and then run `pre-commit install` in the root of the `salt` repo fork that you have locally.

Once you've followed those directions, you need to run the following to apply any fixes or guidance against the two files you are modifying:

```
pre-commit run --files salt/modules/rh_ip.py salt/states/network.py
```

In the future, `pre-commit` will handle changes automatically without you having to run this command because it will run before any `git commit` is able to complete. :)

2021-02-03 11:41 UTC, msciciel commented
All checks have passed. Please review my contribution and i'm waiting for feedback.

2021-02-08 19:49 UTC, dmurphy18 reviewed
@msciciel Might have missed it, but wondering how the changes for channels are displayed or output, that is, is there any function doing the equivalent of '-l --show-channels', or is there a need ?

2021-02-09 14:53 UTC, msciciel commented
> @msciciel Might have missed it, but wondering how the changes for channels are displayed or output, that is, is there any function doing the equivalent of '-l --show-channels', or is there a need ?

Example state output looks like:
```
----------
          ID: eth0
    Function: network.managed
      Result: True
     Comment: Interface eth0 updated.
     Started: 14:36:08.176177
    Duration: 1830.047 ms
     Changes:
              ----------
              interface:
                  ---
                  +++
                  @@ -3,4 +3,5 @@
                   USERCTL="no"
                   TYPE="Ethernet"
                   ONBOOT="yes"
                  +ETHTOOL_OPTS="-L eth0  rx 4 tx 4 combined 4"
                   NM_CONTROLLED="no"
              status:
                  Interface eth0 restart to validate

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.830 s

```

Example pillar:
```
# cat /srv/salt/ethtools.sls
eth0:
  network.managed:
  - enabled: True
  - type: eth
  - channels:
      rx: 4
      tx: 4
      combined: 4
```
To verify that interface is brought up with proper number of channels it is required to use `ethtool -l eth0`. Unfortunately salt module `ethtool` lacks such functionality because it is based on `python-ethool` module which also lacks such feature.

Altering channels number and ring size during interface initialization is safier than on busy system. I've experienced many cases where alteration of these parameter on busy system caused even kernel panic on some specific network card.

@dmurphy18 do I properly addressed your question or You have mean something else?

2021-02-09 16:58 UTC, dmurphy18 submitted a review, later dismissed
Thanks for the response, looks good

2021-02-17 18:22 UTC, Ch3LL requested changes
This will need test coverage added

2021-02-19 18:32 UTC, msciciel commented
@Ch3LL Please verify if provided test is enough.

2021-02-19 20:07 UTC, Ch3LL requested changes

2021-02-19 20:07 UTC, Ch3LL commented on tests/unit/modules/test_rh_ip.py
> +        print(results)
```suggestion

```

2021-02-19 20:16 UTC, msciciel commented on tests/unit/modules/test_rh_ip.py
> +        print(results)
Fixed.

2021-02-23 18:16 UTC, Ch3LL requested changes
Apologies I did not notice this on first review, but this will require a changelog entry. I can add it if you are not able to.

2021-02-24 11:12 UTC, Ch3LL approved these changes

2021-02-24 11:15 UTC, msciciel commented
> Apologies I did not notice this on first review, but this will require a changelog entry. I can add it if you are not able to.

Thanks. Next time I will try to add changelog entry.

2021-02-24 16:30 UTC, garethgreenaway approved these changes

2021-02-24 16:41 UTC, twangboy approved these changes

2021-02-24 16:43 UTC, s0undt3ch approved these changes

2021-02-24 17:11 UTC, merged