Always store git sha in _version.py during installation
saltstack/salt pull request #59137
Opened 2020-12-14 19:52 UTC by bryceml

### What does this PR do?
It always puts the git sha in salt/_version.py when it's generating it's version automatically.

The main difference that tagged versions will include the git sha in that file so it can be figured out later what exact sha is being run, I don't think there should be any other changes anywhere.

### What issues does this PR fix or reference?

### Previous Behavior
tagged versions did not store the git sha

### New Behavior
tagged versions also store the git sha

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

2020-12-16 13:41 UTC, Ch3LL requested changes
What's the use case where you would need the sha? I would assume when you tag a version you only want the tag version not the sha included

2020-12-16 16:08 UTC, bryceml commented
It doesn't show up graphically anywhere, or in any output.  It's mainly so when we do the nightly builds, you can track down the exact sha it came from.

For the non-tiamat packages, you can't have a `-` in the version in the egg info of the python package or rpmbuild errors out.

2020-12-16 16:55 UTC, Ch3LL approved these changes

2021-01-07 21:00 UTC, s0undt3ch approved these changes

2021-01-25 18:58 UTC, merged