WIP Read auth_tries from config instead using 3
saltstack/salt pull request #59178
Opened 2020-12-19 22:43 UTC by markuskramerIgitt

### What does this PR do?
There was code that was overriding the value of `auth_tries` regardless
of what was set in the configuration. It was overriding it to be 3.

### What issues does this PR fix or reference?
This change:
- has been tested to fix issue #59174 according to its test-procedure
- can serve as a workaround for issue #59064

### Previous Behavior
The send function never tried to read `auth_tries` from configuration or another source.

### New Behavior
Because the send function does read `detect_mode` from configuration, a successful attempt was made to also read `auth_tries` from configuration. 

### Merge requirements satisfied?

This Draft PR could be used as a hint or even serve as starting point for a Non-Draft Pull request.

**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-01-19 17:15 UTC, twangboy requested changes

2021-01-19 17:15 UTC, twangboy commented on salt/transport/zeromq.py
> +        tries = self.opts.get("auth_tries", 3)
```
if tries is None:
    tries = self.opts.get("auth_tries", 3)
```

2021-03-17 19:37 UTC, s0undt3ch requested changes
We should also add a test where we make sure different `auth_tries` in the config are not ignored

2021-03-17 19:37 UTC, s0undt3ch commented on salt/transport/zeromq.py
> +            tries = self.opts.get("auth_tries", 3)
```suggestion
            tries = self.opts.get("auth_tries") or 3
```
If `auth_tries` is set to None, we would never default to 3.

2021-04-20 16:21 UTC, twangboy commented
Re-run all

2021-04-20 16:45 UTC, s0undt3ch approved these changes

2021-04-20 17:38 UTC, Ch3LL requested changes
"There was code that was overriding the value of auth_tries regardless"

2021-05-26 19:27 UTC, twangboy commented
I don't know how to write tests for this... and I don't know where in the stack to fix this.

2021-05-28 14:00 UTC, marbx commented
> > "There was code that was overriding the value of auth_tries regardless"
> 
> What part of the code was overriding the `auth_tries`?
> 
It was the default value `3` of the parameter `tries` in function `send`, which is now replaced by `None`

> I would assume the tcp transport would also be impacted by this and this change would not resolve that transport as well. Thats why I'm trying to understand where we are overriding `auth_tries` because I'm wondering if the fix should be higher in the stack.
> 
> This change would also require test coverage and a changelog file

In the stacktrace of https://github.com/saltstack/salt/issues/59064, I find the zmqtransport , but not the TCP transport. Where do you find the TCP transport?

I would like to better understand how Salt uses ZMQ, where should I start?

2021-05-28 14:01 UTC, marbx commented
> I don't know how to write tests for this... and I don't know where in the stack to fix this.

@twangboy: who can?

2021-07-15 17:41 UTC, Ch3LL commented
I did a little more investigation here. Upon investigation of your stack trace I noticed the call that is sending `3` is here: 

```
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\minion.py", line 1587, in _send_req_async
    ret = yield channel.send(load, timeout=timeout)
```

Looks like this PR https://github.com/saltstack/salt/pull/59237 added a new option: `return_retry_tries` which sets it at 3. 

If you increase that option to 5 in your configuration does it resolve the issue for you?

2021-07-15 17:43 UTC, Ch3LL commented
err i mean set it to whatever value you want. I think in your original issue you were trying to set it to 60.

2021-07-20 15:51 UTC, marbx commented
@Ch3LL , cool finding😃

I only have a smartphone, now.

By looking at the code, #59237seems to fix this issue, but doesnt `return_retry_tries` duplicate `auth_tries`?


`auth_tries` seems to be obsolete.

2021-07-20 16:08 UTC, Ch3LL commented
`auth_tries` and `return_retry_tries` accomplish two different tasks. From the docs:

`auth_tries`:
> The number of attempts to authenticate to a master before giving up. Or, more technically, the number of consecutive SaltReqTimeoutErrors that are acceptable when trying to authenticate to the master.

`return_retry_tries`:
> The maximum number of retries for a minion return attempt.

So `auth_tries` is not obsolete but is used for when the minion is attempting to authenticate.

2021-07-28 18:22 UTC, Ch3LL commented
Based off of this information are you okay closing this PR?

2021-07-29 19:26 UTC, marbx commented
I want to test that

On Wed, Jul 28, 2021, 20:22 Megan Wilhite ***@***.***> wrote:

> Based off of this information are you okay closing this PR?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/59178#issuecomment-888523479>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAYRE3F4JMT44JXK4ELH6DT2BDIBANCNFSM4VCTTUUA>
> .
>

2021-08-23 18:34 UTC, Ch3LL commented
@marbx  any luck testing this?

2021-08-24 07:01 UTC, marbx commented
I tested above setting, the test failed, unfortunately

On Mon, Aug 23, 2021, 20:34 Megan Wilhite ***@***.***> wrote:

> @marbx <https://github.com/marbx> any luck testing this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/saltstack/salt/pull/59178#issuecomment-904014259>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAYRE2B6AHB444V6ZJFMDLT6KIE7ANCNFSM4VCTTUUA>
> .
>

2021-08-24 10:31 UTC, marbx commented
Please provide an installer or instructions how to test the release which contains `return_retry_tries`, or perform the test, ideally automatically.

2021-08-24 15:48 UTC, Ch3LL commented
The change to add that configuration is in all of these releases:

```
v3003
v3003.0rc0
v3003.1
v3003.2
v3003_docs
v3003rc0
v3003rc1
```

So you can install the latest v3003.2 in all of the similar ways you can install Salt today: packages, pip, or installing from source.

2021-08-25 20:01 UTC, closed without merging