Added nosync switch to lvcreate
saltstack/salt pull request #59193
Opened 2020-12-26 18:41 UTC by t0fik

### What does this PR do?
Adds support for `nosync` switch to lvcreate.
Switch disables initial syncing of raid logical volumes, nice to have if raid is big ;)
### What issues does this PR fix or reference?
N/A

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2021-03-05 23:54 UTC, twangboy approved these changes, later dismissed

2021-04-01 18:24 UTC, Ch3LL requested changes
This will require a changelog file.

2021-04-28 18:57 UTC, Ch3LL approved these changes

2021-04-28 18:57 UTC, Ch3LL commented
would you mind rebasing against master? The test failures should be resolved.

2021-04-29 19:36 UTC, garethgreenaway approved these changes

2021-04-29 21:17 UTC, twangboy approved these changes

2021-04-30 20:07 UTC, merged