Add support for opaque switch_type to vmware cloud provider
saltstack/salt pull request #59287
Opened 2021-01-13 15:21 UTC by BurningNetel

### What does this PR do?
Adds supports for the 'opaque' switch type to the vmware cloud provider.
This switch type is for example used by NSX-T Segments.

### What issues does this PR fix or reference?
n/a

### Previous Behavior
It was not possible to deploy a VM on an opaque switch_type

### New Behavior
It is possible to deploy a VM on an opaque switch_type

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2021-01-13 20:48 UTC, s0undt3ch requested changes
Can we please have unit tests covering this change?

2021-01-14 09:18 UTC, BurningNetel commented
I would have created unit tests if the other switch_types already had them. It is a too big of a time investment for me to write these because this means getting up to speed with the whole testing framework instead of having some reference material that does a similar test for another network device or any device at all.

I hope someone can support this PR by providing at least an example of a similar test.

2021-08-05 07:27 UTC, marnovdm commented
@s0undt3ch what can we do to get this merged? We've been using this in production by manually patching for almost a year now and it works well. With the acquisition of SaltStack by VMware I had expected support like this to improve dramatically but as it is right now out of the box SaltStack does not even support NSX-T, unless I'm missing something? Are we the only one deploying to vCenter with NSX-T? The original pull request submitter is no longer working with us so he can't handle this anymore. I feel his reason for not adding a test is very reasonable. What can we do to get this on track for next release? I think a lot of people could benefit from this addition and the change is rather clearly scoped so not a lot of risk of unintended side effects.

2023-12-10 12:15 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 12:15 UTC, closed without merging