Fixes to file state when mode is None and test is True
saltstack/salt pull request #59282
Opened 2021-01-12 21:30 UTC by garethgreenaway

### What does this PR do?
When checking if the mode had changed, only do so if the passed mode is not None.

### What issues does this PR fix or reference?
Fixes: #59276 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-01-14 21:51 UTC, dstoliker submitted a review, later dismissed

2021-01-26 00:17 UTC, xeacott submitted a review, later dismissed

2021-02-01 11:44 UTC, Ch3LL requested changes

2021-02-01 11:44 UTC, Ch3LL commented on changelog/59276.fixed
> +When checking if the mode had changed, only do so if the passed mode is not None.
Can you elaborate for which module, to make it easier for users reading the changelog

2021-02-03 13:58 UTC, Ch3LL approved these changes

2021-02-03 15:40 UTC, merged