Updates to pkg beacon, fire when installed or removed
saltstack/salt pull request #59316
Opened 2021-01-18 18:15 UTC by garethgreenaway

### What does this PR do?
Updating the pkg beacon to fire the events when there are upgrades to packages, but also when watched packages are installed or removed.  Breaking out the logic for listing pkgs from __context__ into a separate function to aid in testing.  Updating tests to ensure __context__ is not used when use_context option to list_pkgs is False.

https://github.com/saltstack/salt-enhancement-proposals/pull/39

### What issues does this PR fix or reference?
Fixes: N/A

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-01 11:41 UTC, Ch3LL commented
@garethgreenaway  Looks like there is some conflicts to resolve

2021-02-08 11:49 UTC, Ch3LL requested changes

2021-02-08 11:49 UTC, Ch3LL commented on salt/modules/pacmanpkg.py
> +    foo = __salt__["pkg_resource.version"](*names, **kwargs)
was this on purpose? Asking, because `foo` is usually used for demonstration purposes.

2021-02-08 11:49 UTC, Ch3LL commented on salt/modules/pkg_resource.py
> +                "=== returning in the try - pkg_resource.version - ret %s ===", ret
need to be removed from debugging session?

2021-02-08 11:49 UTC, Ch3LL commented on salt/modules/pkg_resource.py
> +    log.debug("=== pkg_resource.version - ret %s ===", ret)
same as here?

2021-02-08 11:49 UTC, Ch3LL commented on tests/unit/modules/test_aptpkg.py
> +    def test_list_pkgs(self):
can you convert all the new tests you added to pytest

2021-02-09 02:33 UTC, garethgreenaway commented
One more test to move over to pytest.

2021-02-09 19:52 UTC, closed without merging