Fixing _sanitze_comments to use sqlparse instead of re.sub
saltstack/salt pull request #59358
Opened 2021-01-25 22:17 UTC by garethgreenaway

### What does this PR do?
Fixing _sanitze_comments to use sqlparse instead of re.sub.  Adding additional tests.

### What issues does this PR fix or reference?
Fixes: #59336 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-01-26 09:13 UTC, s0undt3ch requested changes
We should add `sqlparse` on the module docstring as a requirement and also add `sqlparse` to the `common.ci` static requirements file.

2021-01-26 09:14 UTC, s0undt3ch commented
Also don't know why `pyupgrade` didn't remove six but https://github.com/saltstack/salt/pull/59358/files#diff-1b1e37a49bc7761e9e4f7233bc24167394b67fbc3095dbe32ec264cd4de1797bR50 should also be removed.

2021-01-26 09:15 UTC, s0undt3ch commented
https://github.com/saltstack/salt/blob/5e17fb88e997cb4fd19eb85e9ce0e08579256255/salt/modules/mysql.py#L50

2021-02-01 17:29 UTC, s0undt3ch approved these changes, later dismissed

2021-02-02 11:14 UTC, Ch3LL approved these changes

2021-02-02 11:14 UTC, merged