Fix service beacon validation
saltstack/salt pull request #59367
Opened 2021-01-27 21:01 UTC by garethgreenaway

### What does this PR do?
Adding missing error case to the validation for service beacon.  Adding additional tests.

### What issues does this PR fix or reference?
Fixes: #56623 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-01-28 12:52 UTC, Ch3LL requested changes

2021-01-28 12:52 UTC, Ch3LL commented on changelog/56623.fixed
> +
remove extra line?

2021-01-29 13:25 UTC, s0undt3ch submitted a review, later dismissed
What @Ch3LL said, but approved.

2021-01-29 17:36 UTC, s0undt3ch approved these changes

2021-01-29 21:40 UTC, Ch3LL approved these changes

2021-02-01 11:23 UTC, merged