Implement tcp_reconnect_backoff minion option
saltstack/salt pull request #59432
Opened 2021-02-04 21:41 UTC by lukasraska

### What does this PR do?
Implements new `tcp_reconnect_backoff` minion config option for dynamic reconnect interval on TCP transport

### What issues does this PR fix or reference?
Fixes: #59431

### Previous Behavior
Minion would try to reconnect exactly after 1 second from previous disconnect

### New Behavior
Reconnect backoff follows `tcp_reconnect_backoff` option (with 1 second default)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2021-02-11 11:56 UTC, Ch3LL approved these changes, later dismissed

2021-03-01 14:44 UTC, twangboy approved these changes

2021-03-01 20:26 UTC, dwoz approved these changes

2021-03-01 20:28 UTC, dwoz requested changes
Please change `tcp_authentication_retries` to`authentication_retries` so we can parody this feature in other transports.

2021-03-01 21:50 UTC, lukasraska commented
@dwoz This PR implements `tcp_reconnect_backoff` option (the `tcp_authentication_retries` had just misnamed anchor in docs, so I've changed it since it's in the same section). I can rename the `tcp_reconnect_backoff` option to `reconnect_backoff` so it can be reused for ZeroMQ (for ZMQ_RECONNECT_IVL or similar) as well. I can also change the `tcp_authentication_retries`  to `authentication_retries` If you want, but since it's existing opt, I would do that in separate PR.

2021-03-03 19:15 UTC, dwoz commented
> @dwoz This PR implements `tcp_reconnect_backoff` option (the `tcp_authentication_retries` had just misnamed anchor in docs, so I've changed it since it's in the same section). I can rename the `tcp_reconnect_backoff` option to `reconnect_backoff` so it can be reused for ZeroMQ (for ZMQ_RECONNECT_IVL or similar) as well. I can also change the `tcp_authentication_retries` to `authentication_retries` If you want, but since it's existing opt, I would do that in separate PR.

Okay, that makes sense. I just prefer we consolidate them in some manner in a future PR. Thanks!

2021-03-03 19:16 UTC, dwoz approved these changes

2021-03-04 12:35 UTC, merged