Remove six usage from stringutils
saltstack/salt pull request #59434
Opened 2021-02-05 00:03 UTC by xeacott

### What does this PR do?
Removes py2 and six usage from stringutils.py

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/58749 https://github.com/saltstack/salt/issues/59063

### Previous Behavior
Potentially unexpected behavior when on Windows and you must pass through salt.utils.stringutils.to_str. This PR addresses those issues when experiencing encoding issues. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-08 11:56 UTC, Ch3LL reviewed
Is there test coverage for all of these different functions you are editing? If not can we add some?

2021-02-08 20:53 UTC, xeacott commented
> Is there test coverage for all of these different functions you are editing? If not can we add some?

Yep, there is decent test coverage just taking longer than expected to convert to pytest :)

2021-02-09 11:02 UTC, Ch3LL requested changes

2021-02-09 11:02 UTC, Ch3LL commented on tests/pytests/unit/utils/test_stringutils.py
> +UNICODE = "中国語 (繁体)"
We want to try to avoid module level variables as these have caused headaches in the past when clashing with other test modules in the future.

2021-02-10 19:38 UTC, garethgreenaway approved these changes, later dismissed

2021-02-10 19:38 UTC, garethgreenaway commented
Approved pending the recommended change from @Ch3LL

2021-02-11 00:57 UTC, garethgreenaway approved these changes, later dismissed

2021-02-11 11:18 UTC, Ch3LL requested changes
I forgot one other thing. Can you delete the tests that you replaced from `tests/unit/utils`

2021-02-16 18:16 UTC, Ch3LL approved these changes

2021-02-17 13:49 UTC, merged