Updates to pkg beacon, fire when installed or removed
saltstack/salt pull request #59463
Opened 2021-02-09 19:55 UTC by garethgreenaway

### What does this PR do?
Updating the pkg beacon to fire the events when there are upgrades to packages, but also when watched packages are installed or removed. Breaking out the logic for listing pkgs from context into a separate function to aid in testing. Updating tests to ensure context is not used when use_context option to list_pkgs is False.  

saltstack/salt-enhancement-proposals#39

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-10 11:47 UTC, Ch3LL commented
Is this the same as this? https://github.com/saltstack/salt/pull/59316  but the tests do not seem to be migrated to pytest.

2021-02-10 17:18 UTC, garethgreenaway commented
@Ch3LL Yes.  The previous PR got lost in merge-conflict nonsense and now looks like I missed some files.

2021-02-11 16:42 UTC, Ch3LL requested changes

2021-02-11 16:42 UTC, Ch3LL commented on tests/pytests/unit/modules/test_aptpkg.py
> +APT_KEY_LIST = r"""
If possible we want to avoid module level variables in tests

2021-02-11 16:42 UTC, Ch3LL commented on tests/pytests/unit/modules/test_yumpkg.py
> +LIST_REPOS = {
here as well

2021-02-16 11:30 UTC, Ch3LL approved these changes

2021-02-16 16:16 UTC, merged