Bump `cryptography` requirement to 3.3.2 due to CVE-2020-36242
saltstack/salt pull request #59468
Opened 2021-02-10 06:26 UTC by s0undt3ch

### What does this PR do?
Bump `cryptography` requirement to 3.3.2 due to CVE-2020-36242

Vulnerable versions: >= 3.1, < 3.3.2
Patched version: 3.3.2
Impact: When certain sequences of update() calls with large values (multiple GBs) for symetric encryption or decryption occur, it's possible for an integer overflow to happen, leading to mishandling of buffers.
References:
 - pyca/cryptography#5615

2021-02-10 08:08 UTC, krionbsd submitted a review, later dismissed

2021-02-19 18:08 UTC, s0undt3ch commented
The in progress build actually passed.

2021-02-19 18:31 UTC, twangboy requested changes
In some instances the version was lowered... is that the intent?

2021-02-19 18:31 UTC, twangboy commented on requirements/static/ci/py3.5/cloud.txt
> +cryptography==3.0         # via requests-ntlm, smbprotocol
Why are we going down here?

2021-02-19 18:31 UTC, twangboy commented on requirements/static/ci/py3.5/darwin.txt
> +cryptography==3.0
And here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/ci/py3.5/freebsd.txt
> +cryptography==3.0
here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/ci/py3.5/linux.txt
> +cryptography==3.0
here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/ci/py3.5/windows.txt
> +cryptography==3.0
here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/pkg/py3.5/freebsd.txt
> +cryptography==3.0         # via pyopenssl
here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/pkg/py3.5/linux.txt
> +cryptography==3.0         # via pyopenssl
here

2021-02-19 18:31 UTC, twangboy commented on requirements/static/pkg/py3.5/windows.txt
> +cryptography==3.0
here

2021-02-19 18:35 UTC, s0undt3ch commented
@twangboy 

> For Py3.5 requirements we dropped cryptography to version 3.0 which is not vulnerable to the CVE in question.
This decision was made consciously because the Salt Project creates packages for the supported distributions which still use Py3.5 and those even rely on an even older version of cryptography.
Upgrading to the latest version was not possible because the cryptography project dropped Py3.5 support.

2021-02-19 19:15 UTC, twangboy approved these changes

2021-02-23 11:02 UTC, krionbsd approved these changes

2021-02-23 15:10 UTC, waynew approved these changes

2021-02-23 15:13 UTC, Ch3LL approved these changes

2021-02-23 15:13 UTC, merged