Fix pkg.latest on FreeBSD by stripping 'with_origin' dict.
saltstack/salt pull request #59461
Opened 2021-02-09 14:56 UTC by krionbsd

Related to https://github.com/saltstack/salt/pull/54074 and
https://github.com/saltstack/salt/issues/55630

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/55630

2021-02-09 15:02 UTC, s0undt3ch requested changes

2021-02-09 15:02 UTC, s0undt3ch commented on salt/states/pkg.py
> +            "The following packages were {}d: " "{}.".format(action, ", ".join(targets))
```suggestion
            "The following packages were {}d: {}.".format(action, ", ".join(targets))
```

2021-02-09 15:02 UTC, s0undt3ch commented on salt/states/pkg.py
> +            ] = "An error was encountered while purging " "package(s): {}".format(exc)
```suggestion
            ] = "An error was encountered while purging package(s): {}".format(exc)
```

2021-02-19 17:28 UTC, Ch3LL requested changes
tests?

2021-02-19 23:26 UTC, sagetherage commented
@waynew maybe we can attempt to write tests for this one at the Test Clinic next week? this one is a good PR example like many of the [Ports to Master](https://github.com/saltstack/salt/pull/59461) PRs that need to be merged, but also need tests written - we should do a write tests code jam.

2021-03-02 08:25 UTC, krionbsd commented
> tests?

I think we don't really need a test case for this PR, because what we do for FreeBSD is just strip `with_origin` from the dict, and the `test_fulfills_version_string` test in tests/pytests/unit/states/test_pkg.py covers this scenario for FreeBSD as well

2021-03-02 08:31 UTC, s0undt3ch submitted a review, later dismissed

2021-03-02 15:08 UTC, Ch3LL commented
This is fixing a bug and our previous tests did not catch this, we need to add a tests that fails without this change, and passes with the change.

2021-07-15 17:22 UTC, Ch3LL commented
bump on my comment above ^

2021-07-22 22:33 UTC, sagetherage commented
@krionbsd when you are back online let's address the testcases here, pretty please

2021-11-08 12:04 UTC, closed without merging