Set VM name in Proxmox.
saltstack/salt pull request #59501
Opened 2021-02-14 22:02 UTC by laundry-96

### What does this PR do?
Sets the VM Name in the Proxmox UI
### What issues does this PR fix or reference?

### Previous Behavior
The VM name would be a copy of the template

### New Behavior
Sets the name of the VM to the name of the minion

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-14 22:03 UTC, laundry-96 commented
@sagetherage This is the second (and last) commit I'd like for approval! Thanks!

2021-02-16 17:27 UTC, Ch3LL requested changes
This change will require test coverage

2021-02-16 18:51 UTC, sagetherage commented
@laundry-96 looks like this needs a test case - let us know if you need help with that, today and Thursday there is a test clinic with @waynew

2022-10-20 17:54 UTC, twangboy requested changes
This needs a changelog and test case

2022-10-20 17:54 UTC, twangboy commented on salt/cloud/clouds/proxmox.py
> +
Couldn't you just add name to the regex here?
```
        if re.match(r"^(ide|sata|scsi|name)(\d+)$", setting):
```

2022-11-04 18:17 UTC, Ch3LL commented
Closing due to inactivity. Please let me know if we need to re-open, or open up a new PR against master.

2022-11-04 18:17 UTC, closed without merging