Fix Consul module PUT request
saltstack/salt pull request #59511
Opened 2021-02-16 11:58 UTC by ruial

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: Issues when using **salt.modules.consul.put** with a token or other params.

### Previous Behavior
When using the put method of the consule module, it can fail in 3 ways:
- The token is not propagated, causing error 403 when token is valid.
- When *kas* or *release* param is set, it handles a previous response from Consul as an object, making it impossible to release a lock this way. Consul returns a list of objects. The size can be bigger on GET operations with the recurse param.
- If the response body of the PUT operation is false, it is showing a success message, despite the write failure. Even if http response code is 200, the body must be checked.

References: https://www.consul.io/api-docs/kv

### New Behavior
- Propagate token and authenticate with success
- Able to use *kas* or *release* params with success
- Show error if write failed

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-16 12:06 UTC, krionbsd approved these changes, later dismissed

2021-02-16 12:18 UTC, krionbsd approved these changes

2021-02-16 16:13 UTC, twangboy requested changes
Please write some tests for this

2021-02-16 19:00 UTC, ruial commented
> Please write some tests for this

Hello @twangboy, I did not find existing tests for the consul module that I could edit. Writing unit and/or integration tests for this module will require some time as there are many alternative paths, so I will not be able to commit them. Let me know if I should open an issue or if additional information is required to reproduce the mentioned scenarios.

2021-02-22 19:56 UTC, sagetherage commented
@waynew may be a good candidate for the test clinic
@ruial we can't merge in PRs without tests even if the module is lacking test coverage, but we do have on Tuesdays from 1-2 pm MST and 7-8 pm UTC and Thursdays from 8-10 AM MST and 3-5 PM UTC test clinics with @waynew on [Twitch](https://www.twitch.tv/saltstackinc)

2023-12-10 10:50 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 10:50 UTC, closed without merging