Fix 20789 - Window's user creation and password policy requirements
saltstack/salt pull request #59563
Opened 2021-02-20 01:06 UTC by xeacott

### What does this PR do?
Surface the errors that occur when user account creation fails on a Window's box.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/20789

### Previous Behavior
```
          ID: johndoe
    Function: user.present
      Result: False
     Comment: Failed to create new user johndoe
     Started: 11:28:05.724000
    Duration: 109.0 ms
     Changes:  

    [INFO    ] Running state [johndoe] at time 10:54:56.555000
    [INFO    ] Executing state user.present for johndoe
    [INFO    ] Executing command ['net', 'user', 'johndoe', '/add'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
    [ERROR   ] Command ['net', 'user', 'johndoe', '/add'] failed with return code: 2
    [ERROR   ] stderr: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.

    More help is available by typing NET HELPMSG 2245.
    [ERROR   ] retcode: 2
    [ERROR   ] Failed to create new user johndoe
    [INFO    ] Completed state [johndoe] at time 10:54:56.680000
```

### New Behavior
```
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: create_user
    Function: user.present
        Name: testuser123
      Result: False
     Comment: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.
     Started: 16:00:47.406333
    Duration: 99.254 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  99.254 ms
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-02-20 17:38 UTC, twangboy requested changes
Let's raise a CommandExecutionError when the command fails

2021-02-20 17:38 UTC, twangboy commented on salt/modules/win_useradd.py
> +                 home=\\server\\homeshare\bob homedrive=U:
Probably need another slash before bob as well

2021-02-20 17:38 UTC, twangboy commented on salt/modules/win_useradd.py
> +        return exc.strerror
Let's raise a CommandExecutionError here instead:
```
raise CommandExecutionError(exc.strerror)
```

2021-02-24 18:44 UTC, twangboy requested changes

2021-02-24 18:44 UTC, twangboy commented on salt/states/user.py
> +        if result is not True and salt.utils.platform.is_windows():
Why is this Windows specific?
If it is Windows specific, what happens when it is `not True` but not Windows?

2021-04-01 22:37 UTC, twangboy approved these changes

2021-04-02 03:50 UTC, garethgreenaway approved these changes

2021-04-02 07:01 UTC, krionbsd approved these changes

2021-04-02 10:26 UTC, merged