Move cmd state test to pytest
saltstack/salt pull request #59581
Opened 2021-02-23 08:46 UTC by krionbsd

### What does this PR do?
Move cmd state test to pytest

2021-02-23 17:37 UTC, krionbsd commented on tests/pytests/unit/states/test_cmd.py
> +        "commnd": "Must supply a password if runas argument is used on Windows.",
Yep, fixed

2021-02-23 17:37 UTC, krionbsd commented on tests/pytests/unit/states/test_cmd.py
> +    #         func = 'myfunc'
Fixed

2021-02-26 20:28 UTC, twangboy requested changes

2021-02-26 20:28 UTC, twangboy commented on salt/states/cmd.py
> +        ret["command"] = "Must supply a password if runas argument is used on Windows."
I would suspect this is supposed to be `comment` if it's part of the state return. I don't know what the state does with additional keys... they may be ignored

2021-02-27 21:28 UTC, twangboy submitted a review, later dismissed

2021-03-01 16:46 UTC, s0undt3ch commented
@Ch3LL, @twangboy : Do we need a changelog entry for the typo fixed?

2021-03-17 10:59 UTC, Ch3LL commented
Yeah, I think it would be good since it changes something for the user.

2021-04-02 18:39 UTC, Ch3LL approved these changes

2021-04-02 19:06 UTC, twangboy approved these changes

2021-04-02 20:38 UTC, garethgreenaway approved these changes

2021-04-02 22:28 UTC, merged