improves secure_password in salt/utils/pycrypto.py (#59486)
saltstack/salt pull request #59599
Opened 2021-02-24 10:37 UTC by root360-AndreasUlm

### What does this PR do?

This PR changes the default character set used by `utils.pycrypto.secure_password()` and implements arguments to control the used character set. (see #59486)

### What issues does this PR fix or reference?
Fixes: None
Closes: #59486
Updated PR for https://github.com/saltstack/salt/pull/59533

### Previous Behavior

`utils.pycrypto.secure_password()` generated random string based on `string.ascii_letters + string.digits`.

### New Behavior

`utils.pycrypto.secure_password()` generates random string based on given character controlling arguments.
The default is now `string.ascii_lowercase + string.ascii_uppercase + string.digits + string.punctuation`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

2021-02-24 10:39 UTC, root360-AndreasUlm commented
FYI: This PR was created with pre-commit-hooks disabled due to limitations on development system and hooks not running with containers (yet) (see https://github.com/saltstack/salt/issues/59486#issuecomment-781790748)

2021-02-24 10:56 UTC, s0undt3ch requested changes

2021-02-24 10:56 UTC, s0undt3ch commented on salt/modules/mod_random.py
> +def get_str(length=20, **kwargs):
Please be explicit on the keyword arguments and their defaults. We don't really need this to be `**kwargs`

2021-02-24 10:56 UTC, s0undt3ch commented on salt/modules/mod_random.py
> +    return salt.utils.pycrypto.secure_password(length, **kwargs)
as above, pass explicit keyword arguments and their values

2021-02-24 10:56 UTC, s0undt3ch commented on salt/utils/pycrypto.py
> +def secure_password(length=20, use_random=True, **kwargs):
Please add the supported keyword arguments and their default values, we don't need this to be `**kwargs`

2021-02-24 12:23 UTC, root360-AndreasUlm commented
* force rebased the PR on master
* solved linting issues 
* solved coding comments of @s0undt3ch

2021-02-25 10:55 UTC, s0undt3ch commented
I pushed a commit with changes to the docstring

2021-02-25 10:58 UTC, root360-AndreasUlm commented
> I pushed a commit with changes to the docstring

nice thank you.
I haven't found a documentation about the possible keys to indicate version, yet.
Is there a documentation?

2021-02-25 11:01 UTC, s0undt3ch commented
The version numbers? the `versionadded`, `versionchanged`?

2021-02-25 11:05 UTC, root360-AndreasUlm commented
> The version numbers? the `versionadded`, `versionchanged`?

yes those.

2021-02-25 11:15 UTC, s0undt3ch commented
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

2021-02-25 15:10 UTC, s0undt3ch submitted a review, later dismissed

2021-02-26 07:58 UTC, root360-AndreasUlm commented
@s0undt3ch Do all checks have to be successful and the branch always up-to-date for a valid merge request?
I'm currently facing CI-jobs being canceled and multiple times a day I get the message that the branch is out-dated.

2021-02-26 10:12 UTC, s0undt3ch commented
> Do all checks have to be successful

Yes

> and the branch always up-to-date for a valid merge request?

Not necessarily

> I'm currently facing CI-jobs being canceled and multiple times a day I get the message that the branch is out-dated.

Yes, our Jenkins instance had problems yesterday and there's some instability in our CI jobs which we're trying to address.

2021-03-08 16:30 UTC, root360-AndreasUlm commented
@s0undt3ch I fixed file conflicts and now all checks have passed.

2021-03-08 16:50 UTC, s0undt3ch approved these changes, later dismissed

2021-09-13 14:32 UTC, s0undt3ch commented
Conflicts fixed. updated `versionadded`, `versionchanged` to `3004.0`

2021-09-14 20:01 UTC, dwoz approved these changes
I'm good with these changes but `tests/unit/utils/test_pycrypto.py` should be removed if we're not using it.

2021-09-21 23:07 UTC, merged