Document pytest fixutres usage over global variable usage
saltstack/salt pull request #59623
Opened 2021-02-26 15:02 UTC by Ch3LL

2021-02-26 15:04 UTC, s0undt3ch requested changes

2021-02-26 15:04 UTC, s0undt3ch commented on doc/topics/development/tests/index.rst
> +processing time because all globals are evaulated when collecting tests. For example,
```suggestion
processing time because all globals are evaluated when collecting tests. For example,
```

2021-02-26 16:29 UTC, OrangeDog commented
To avoid cases where you forget to include the fixture argument, and end up referring to the function instead of the value, perhaps it should be recommended to always set a fixture name different to the function name. See e.g. #59034 where I did this.

2021-02-26 19:02 UTC, s0undt3ch commented
@OrangeDog newer versions of pytest fail if you try to use a function which has been decorated with `pytest.fixture`, however we can't upgrade until we drop Py3.5

2021-02-26 19:11 UTC, s0undt3ch commented
> To avoid cases where you forget to include the fixture argument, and end up referring to the function instead of the value, perhaps it should be recommended to always set a fixture name different to the function name ...

You mean the ids function? Yes, that's usually simpler than scattering lambdas....

2021-02-26 21:09 UTC, OrangeDog commented
I mean mistakes like this:
```python
@pytest.fixture
def my_thing():
    return ...

@pytest
def test_something():
    do_something(my_thing)
```
IDEs think that's fine, but will give you a big warning for this:
```python
@pytest.fixture(name="my_thing")
def fixture_my_thing():
    return ...

@pytest
def test_something():
    do_something(my_thing)
```

2021-04-14 17:03 UTC, Ch3LL commented
It seems this error is found in newer versions of pytest as @s0undt3ch stated. I think it should be okay to merge this in as is and we can handle that situation in a separate PR if its found the newer version still does not detect it.

2021-04-14 17:04 UTC, Ch3LL commented
@s0undt3ch can you re-review please

2021-04-14 17:18 UTC, s0undt3ch approved these changes

2021-04-14 18:58 UTC, garethgreenaway approved these changes

2021-04-14 19:29 UTC, twangboy approved these changes

2021-04-15 10:54 UTC, merged