Add option to disable clients in netapi
saltstack/salt pull request #59622
Opened 2021-02-26 08:45 UTC by barneysowood

### What does this PR do?

Adds a new config option "netapi_disable_clients" that takes a list of clients to disable in the netapi.

Checks the list early in handling the the request before authentication occurs. Should be useful where certain clients (eg ssh or wheel) aren't required and should be disabled to reduce attack surface in the salt-api.

replaces https://github.com/saltstack/salt/pull/58872

### What issues does this PR fix or reference?

### New Behavior

Adds "netapi_disable_clients" list option to the config which is checked when a request is passed to NetApiClient.run() and an exception raised if the requested client is in the list.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X]  Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2021-03-06 12:26 UTC, barneysowood commented
re-run ci/py3/macosxmojave/pytest

2021-03-06 12:28 UTC, barneysowood commented
re-run pr-macosxmojave-py3-pytest

2021-03-17 17:05 UTC, sagetherage commented
@barneysowood I updated the branch with `master` as I think we have fixed these tests that are failing, here. That reruns the full test suite so I will check back, as well. I hope that that helps!

2021-03-18 12:17 UTC, barneysowood commented
> @barneysowood I updated the branch with `master` as I think we have fixed these tests that are failing, here. That reruns the full test suite so I will check back, as well. I hope that that helps!

Thanks @sagetherage. Looks like the failing tests are fixed now - thanks! Unfortunately seems to have times out on ci/py3/centos7/pycryptodome/pytest - I'll try that again now.

2021-03-18 12:18 UTC, barneysowood commented
re-run pr-centos7-py3-pycryptodome-pytest

2021-03-18 14:04 UTC, barneysowood commented
OK, tests now all green.

@garethgreenaway - if you get a chance to review that would be great, thanks!

2021-04-21 18:04 UTC, Ch3LL approved these changes, later dismissed

2021-04-21 18:05 UTC, Ch3LL commented
I approved but look like there is a merge conflict.  Would also like to get @dwoz review here as well.

2021-04-22 17:09 UTC, barneysowood commented
Hmm, have totally messed up the rebase trying to sort the conflict. Will fix that and re-push

2021-04-30 10:34 UTC, barneysowood commented
re-run pr-freebsd-122-amd64-py3-pytest

2021-04-30 10:35 UTC, barneysowood commented
re-run pr-ubuntu-2004-arm64-py3-pytest

2021-04-30 10:36 UTC, barneysowood commented
re-run pr-macosx-mojave-x86_64-py3-pytest

2021-05-03 07:10 UTC, barneysowood commented
@Ch3LL and @dwoz - merge conflict resolved and all tests now passing. If you could review that would be great, thanks.

2021-05-18 11:20 UTC, Ch3LL approved these changes, later dismissed

2021-05-18 19:40 UTC, garethgreenaway submitted a review, later dismissed

2021-05-19 11:09 UTC, barneysowood commented
re-run pr-fedora-34-x86_64-py3-pytest

2021-05-20 16:13 UTC, barneysowood commented
re-run pr-fedora-34-x86_64-py3-pytest

2021-05-21 11:23 UTC, barneysowood commented
re-run pr-macosx-catalina-x86_64-py3-pytest

2021-05-21 11:24 UTC, barneysowood commented
re-run pr-macosx-mojave-x86_64-py3-pytest

2021-05-24 22:14 UTC, dwoz requested changes
Honestly, due to the amount of problems we've had with the netapi I think this should be an opt in scenario rather than opt out. Meaning it'd be `netapi_enable_clients` and they are all disabled by default.

2021-05-25 10:51 UTC, barneysowood commented
> Honestly, due to the amount of problems we've had with the netapi I think this should be an opt in scenario rather than opt out. Meaning it'd be `netapi_enable_clients` and they are all disabled by default.

@dwoz - I would tend to agree, but I was trying to avoid a breaking change. If everyone is OK with that I'm happy rework this to be `netapi_enable_clients` and also add some documentation for that.

The other option would be to set the default (either using the `netapi_enable_clients` or `netapi_disable_clients` form) to disable the ssh client by default as that has tended to be the most problematic.

2022-02-15 01:05 UTC, barneysowood commented
re-run pr-amazon-2-x86_64-py3-pytest

2022-02-15 20:09 UTC, Ch3LL commented
@dwoz I really like the idea of the opt in as well, but that seems like a big change for users of salt-api. Shouldn't we add a deprecation notice somehow or give users notice before we make this change?

2022-11-11 13:10 UTC, barneysowood commented
Closing in favour of https://github.com/saltstack/salt/pull/63050

2022-11-11 13:10 UTC, closed without merging