Move mdadm_raid state tests to pytest
saltstack/salt pull request #59627
Opened 2021-02-26 16:57 UTC by krionbsd

### What does this PR do?
Move mdadm_raid state tests to pytest

2021-02-26 16:59 UTC, twangboy approved these changes, later dismissed

2021-02-26 18:07 UTC, s0undt3ch approved these changes

2021-02-27 21:26 UTC, twangboy approved these changes, later dismissed

2021-03-01 04:05 UTC, s0undt3ch requested changes

2021-03-01 04:05 UTC, s0undt3ch commented on tests/pytests/unit/states/test_mdadm_raid.py
> +            " ['6be5fc45:05802bba:1c2d6722:666f0e03', 'ffffffff:ffffffff:ffffffff:ffffffff'].",
```suggestion
            "comment": (
                "Devices are a mix of RAID constituents with multiple MD_UUIDs: "
                "['6be5fc45:05802bba:1c2d6722:666f0e03', 'ffffffff:ffffffff:ffffffff:ffffffff']."
                ),
```

2021-03-01 16:48 UTC, s0undt3ch approved these changes

2021-03-01 16:48 UTC, merged