Fix some issues after CVE fixes
saltstack/salt pull request #59664
Opened 2021-03-01 15:15 UTC by meaksh

### What does this PR do?
We've detected few issues after February CVE fixes:

- The `extra_filerefs` parameter is discarded for the SSHClient
- The `cmd.run` function crashes if passing tuple arg:

```console
[root@suma-test-min-centos7 ~]# salt-call --local partition.mklabel /dev/vda3 msdos
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'tuple' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/parted_partition.py", line 450, in mklabel
    out = __salt__['cmd.run'](cmd, python_shell=False).splitlines()
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1177, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 387, in _run
    _log_cmd(cmd),
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 81, in _log_cmd
    return cmd.split()[0].strip()
AttributeError: 'tuple' object has no attribute 'split'
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-01 15:15 UTC, meaksh commented
@dwoz here you have it :+1:

2021-03-01 16:27 UTC, twangboy submitted a review, later dismissed

2021-03-02 13:26 UTC, s0undt3ch approved these changes

2021-03-02 13:27 UTC, s0undt3ch requested changes
The failures on windows were introduced in this PR and look valid.

2021-03-02 13:42 UTC, meaksh commented
Hey @s0undt3ch, the previously failing test for windows is a new test I've just introduced with this PR - it was not an existing one.

I've skipped it on Windows since it seems doesn't like calling `echo` like this. I don't have a Windows machine here to easily test this.

Do you want this test to be also implemented to run on Windows?

2021-03-02 13:43 UTC, s0undt3ch commented
> Hey @s0undt3ch, the previously failing test for windows is a new test I've just introduced with this PR - it was not an existing one

Yes, I explained myself incorrectly :)

2021-03-03 09:52 UTC, meaksh commented
@s0undt3ch I've fixed the test for Windows.

I see now some other failures for "windows2019" and "macosxcatalina" after rebasing with master, but I think they're not related to this PR.

2021-03-04 17:22 UTC, s0undt3ch approved these changes

2021-03-04 17:42 UTC, Ch3LL approved these changes

2021-03-05 14:51 UTC, krionbsd approved these changes

2021-03-05 15:00 UTC, merged