Move npm related state tests to pytest
saltstack/salt pull request #59678
Opened 2021-03-02 14:14 UTC by krionbsd

### What does this PR do?
Move npm related state tests to pytest

2021-03-02 21:30 UTC, twangboy approved these changes, later dismissed

2021-03-03 12:12 UTC, s0undt3ch requested changes

2021-03-03 12:12 UTC, s0undt3ch commented on tests/pytests/unit/states/test_npm.py
> +            comt = "Package(s) 'coffee-script' " "satisfied by coffee-script@1.2"
```suggestion
            comt = "Package(s) 'coffee-script' satisfied by coffee-script@1.2"
```

2021-03-03 12:12 UTC, s0undt3ch commented on tests/pytests/unit/states/test_npm.py
> +            comt = "Package(s) 'coffee-script' " "satisfied by coffee-script@1.2"
```suggestion
            comt = "Package(s) 'coffee-script' satisfied by coffee-script@1.2"
```

2021-03-03 17:01 UTC, krionbsd commented on tests/pytests/unit/states/test_npm.py
> +            comt = "Package(s) 'coffee-script' " "satisfied by coffee-script@1.2"
Fixed

2021-03-03 17:01 UTC, krionbsd commented on tests/pytests/unit/states/test_npm.py
> +            comt = "Package(s) 'coffee-script' " "satisfied by coffee-script@1.2"
Fixed

2021-03-05 09:41 UTC, s0undt3ch approved these changes

2021-03-05 09:42 UTC, merged