Add all ssh kwargs to sanitize_kwargs method
saltstack/salt pull request #59748
Opened 2021-03-08 15:11 UTC by Ch3LL

### What does this PR do?
Adding upon this PR: https://github.com/saltstack/salt/pull/59664  adding all ssh options users can safely pass.

2021-03-08 15:38 UTC, s0undt3ch requested changes

2021-03-08 15:38 UTC, s0undt3ch commented on tests/pytests/conftest.py
> +
```suggestion
```

2021-03-08 15:38 UTC, s0undt3ch commented on tests/pytests/unit/client/test_ssh.py
> +        assert ssh_obj.opts.get(opt_key, None) == opt_value
```suggestion
def test_ssh_kwargs(temp_salt_master, test_opts):
    """
    test all ssh kwargs are not excluded from kwargs
    when preparing the SSH opts
    """

    ssh_kwargs = salt.utils.parsers.SaltSSHOptionParser().defaults
    opt_key = test_opts[0]
    opt_value = test_opts[1]
    # Is the kwarg in salt.utils.parsers?
    in_parser = test_opts[2]

    opts = {
        "eauth": "auto",
        "username": "test",
        "password": "test",
        "client": "ssh",
        "tgt": "localhost",
        "fun": "test.ping",
        opt_key: opt_value,
    }
    client = salt.client.ssh.client.SSHClient(
        mopts=temp_salt_master.config.copy(), disable_custom_roster=True
    )
    if in_parser:
        assert opt_key in ssh_kwargs

    with patch("salt.roster.get_roster_file", MagicMock(return_value="")):
        ssh_obj = client._prep_ssh(**opts)
        assert ssh_obj.opts.get(opt_key, None) == opt_value
```

2021-03-08 15:39 UTC, s0undt3ch commented
Let's try the above and see if it's enough.

2021-03-08 15:55 UTC, Ch3LL commented
re-run full all

2021-03-08 15:59 UTC, Ch3LL commented
re-run full all

2021-03-08 16:02 UTC, Ch3LL commented
re-run full all

2021-03-08 16:47 UTC, s0undt3ch approved these changes, later dismissed

2021-03-09 18:13 UTC, s0undt3ch approved these changes

2021-03-09 18:59 UTC, cmcmarrow approved these changes

2021-04-02 18:26 UTC, closed without merging