Add missing word in syndic docs
saltstack/salt pull request #59799
Opened 2021-03-14 10:21 UTC by krionbsd

### What does this PR do?
Add missing word in syndic docs

2021-03-16 18:55 UTC, Ch3LL approved these changes

2021-03-16 18:55 UTC, Ch3LL requested changes

2021-03-16 18:55 UTC, Ch3LL commented on doc/man/salt.7
> +as well, so the Salt client does not know how long to wait for all returns. The
Almost missed this... we are not supposed to directly edit the man pages. These are generated at release time.

2021-03-19 10:58 UTC, Ch3LL approved these changes

2021-03-25 18:46 UTC, twangboy approved these changes

2021-03-25 18:46 UTC, ScriptAutomate approved these changes

2021-03-25 18:49 UTC, waynew approved these changes

2021-03-29 15:00 UTC, merged