Add Codecov badge to README
saltstack/salt pull request #59791
Opened 2021-03-12 22:47 UTC by thomasrockhu

### What does this PR do?
Tom from Codecov here. I thought I would go ahead and add the Codecov badge here in case it's useful!

### What issues does this PR fix or reference?
Fixes: N/A

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-16 19:07 UTC, Ch3LL approved these changes

2021-03-16 20:08 UTC, twangboy approved these changes

2021-03-17 12:11 UTC, s0undt3ch requested changes
The reason why we don't have the badge yet is because there's no point directing users to the salt project on codecov when it's not working properly.

Today I tried looking at the project and the coverage chart never loads.
We also cannot seem to be able to upload all the reports needed for proper coverage reporting.

Take [this](https://codecov.io/gh/saltstack/salt/commit/649b9f9a503d7095c3002b88df1111c14fdbae24/build) example, we should have at least 48 reports uploaded, there's 24(although here we might have changed our CI not to upload so many a while back to see if codecov could cope).

If we try to load the PR on codevov, [this pr](https://app.codecov.io/gh/saltstack/salt/compare/59821), it doesn't load.

So, until we can get codecov to actually show useful reports and support the amount of data we need to upload, there's no point showing the badge.

2021-05-12 02:22 UTC, thomasrockhu commented
@Ch3LL that's fine for now! I took the feedback internally and we are working on some fixes.

2021-05-12 02:22 UTC, closed without merging