Fix/wheel file roots find
saltstack/salt pull request #59803
Opened 2021-03-14 15:18 UTC by kevthehermit

### What does this PR do?

Adds `subdir=True` to `wheel.file_roots.find`

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/59800

### Previous Behavior

When attempting to read a file in a subdirectory with `wheel.file_roots.read` it would fail as `wheel.file_roots.find` is not able to read from a subdirectory. 

### New Behavior

You can successfully read a file in a subdirectory

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-16 11:28 UTC, Ch3LL requested changes
This will require test coverage

2021-03-16 11:29 UTC, Ch3LL commented
@dwoz would you mind reviewing here. Looks like this was changed here: d5801df94b05158dc8e48c5e6912b065044720f3

2021-03-16 16:21 UTC, dwoz reviewed
While looking at the implementation of subdir=True, I am a bit confused

```
    if subdir:
        if real_path.startswith(real_root):
            return real_path
    else:
        if os.path.dirname(real_path) == os.path.normpath(real_root):
            return real_path
```

Why are we calling `normpath` in the else and not the `subdir` case?

2021-03-17 20:31 UTC, dwoz commented
> @dwoz would you mind reviewing here. Looks like this was changed here: [d5801df](https://github.com/saltstack/salt/commit/d5801df94b05158dc8e48c5e6912b065044720f3)

I approve provided we have tests.

2021-03-22 22:24 UTC, kevthehermit commented
I didn't see any existing test in place for these modules to extend so will have to read up on tests and put something together

2021-04-30 03:35 UTC, sagetherage commented
@waynew maybe a good candidate for the Test Clinic next Tuesday

2023-06-06 18:36 UTC, MKLeb commented
This will close the corresponding issue with a comprehensive test suite: https://github.com/saltstack/salt/pull/64429.

2023-06-06 18:36 UTC, closed without merging