Bump keystone deprecation warning to Silicon
saltstack/salt pull request #59813
Opened 2021-03-16 15:52 UTC by garethgreenaway

### What does this PR do?
Bump keystone deprecation warning to Silicon

### What issues does this PR fix or reference?
Fixes: #58032 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-17 17:00 UTC, Ch3LL requested changes

2021-03-17 17:00 UTC, Ch3LL commented on salt/modules/keystone.py
> +        "Phosphorous",
```suggestion
        "Phosphorus",
```

2021-03-19 17:28 UTC, Ch3LL approved these changes

2021-03-19 20:05 UTC, s0undt3ch approved these changes

2021-03-22 12:47 UTC, krionbsd approved these changes

2021-03-22 17:12 UTC, merged