Removing the _ext_nodes deprecation warning and alias.
saltstack/salt pull request #59826
Opened 2021-03-17 00:20 UTC by garethgreenaway

### What does this PR do?
Removing the _ext_nodes deprecation warning and alias.

### What issues does this PR fix or reference?
Fixes: #59804 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-22 12:41 UTC, Ch3LL requested changes
changelog file. This looks like it will break compatibility between Salt versions so we should probably call that out specifically in the changelog file.

2021-03-22 17:22 UTC, Ch3LL approved these changes, later dismissed

2021-03-22 18:13 UTC, cmcmarrow approved these changes, later dismissed

2021-03-22 18:19 UTC, s0undt3ch submitted a review, later dismissed

2021-03-23 17:29 UTC, Ch3LL approved these changes

2021-03-24 16:52 UTC, Ch3LL commented
This was included int eh merge forward from freeze: https://github.com/saltstack/salt/pull/59879

2021-03-24 16:52 UTC, closed without merging