Merge 3002.6 bugfix changes
saltstack/salt pull request #59822
Opened 2021-03-16 21:59 UTC by dwoz

### What does this PR do?

Merge 3002.6 bugfix changes

2021-03-16 22:12 UTC, twangboy submitted a review, later dismissed

2021-03-17 17:21 UTC, Ch3LL requested changes

2021-03-17 17:21 UTC, Ch3LL commented on tests/pytests/unit/test_version.py
> -def test_versions_report_includes_salt_extensions():
I don't think these two tests should be getting removed?

2021-03-18 10:43 UTC, Ch3LL approved these changes

2021-03-18 12:18 UTC, s0undt3ch approved these changes

2021-03-18 14:34 UTC, twangboy approved these changes

2021-03-18 14:38 UTC, merged