Fixes to gpg states.
saltstack/salt pull request #59843
Opened 2021-03-19 10:55 UTC by OrangeDog

### Previous Behavior
`gpg.absent` ignores parameters when checking keychain.
`gpg.present` can report wrong key in comments.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

2025-03-28 15:15 UTC, twangboy requested changes

2025-03-28 15:15 UTC, twangboy commented on changelog/59843.fixed
> +
This file should have a `.md` file extension
The text should be more clear that these issues are fixed. This is what will be displayed in the changelog.

2025-03-28 15:15 UTC, twangboy commented
This also needs a test

2025-07-04 08:40 UTC, lkubb commented
I'm pretty sure this is already resolved by https://github.com/saltstack/salt/pull/63162

2025-08-01 20:59 UTC, closed without merging