Add pytest Solaris 11.4 IPS packaging tests
saltstack/salt pull request #59867
Opened 2021-03-22 17:03 UTC by dmurphy18

### What does this PR do?
Adds pytest based tests for Solaris 11.4 IPS packaging, install / remove / get_fmri and their different flavors.
This is part of the preparation for introduction of Python 3 Tiamat based native minion support for Solaris 11.4 (Intel - completed, Sparc - under development)

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/59306
https://gitlab.com/saltstack/open/salt-pack-extras/-/issues/184

### Previous Behavior
Used old unit non-pytest based IPS packaging for Solaris 11.3 (which is EOL'd and version format was different), and were Python 2 based.

### New Behavior
Adds new pytest based tests for IPS packaging and allows for package version format change in Solaris 11.4 IPS packages

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-22 23:33 UTC, dmurphy18 commented
re-run macos

2021-03-23 18:01 UTC, s0undt3ch requested changes

2021-03-23 18:27 UTC, dmurphy18 commented on tests/pytests/unit/modules/test_solarisipspkg.py
> +
Made the change, re-running tests
That is what I get for looking at test_yumpkg.py as an example.  should remove the same code from there as part of clean up at some point

2021-03-23 22:57 UTC, dmurphy18 commented
re-run all

2021-03-26 15:58 UTC, dmurphy18 commented
re-run all

2021-03-29 21:11 UTC, s0undt3ch approved these changes

2021-03-31 15:35 UTC, dmurphy18 commented
re-run all

2021-04-01 10:23 UTC, Ch3LL approved these changes

2021-04-01 11:13 UTC, krionbsd approved these changes

2021-04-01 15:26 UTC, twangboy approved these changes

2021-04-01 17:58 UTC, merged