[freeze] Removing the _ext_nodes deprecation warning and alias.
saltstack/salt pull request #59866
Opened 2021-03-22 15:49 UTC by garethgreenaway

### What does this PR do?
Removing the _ext_nodes deprecation warning and alias.

### What issues does this PR fix or reference?
Fixes: #59804

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-03-22 16:04 UTC, Ch3LL requested changes

2021-03-22 16:04 UTC, Ch3LL commented on changelog/59804.changed
> +Removing the _ext_nodes deprecation warning and alias to the master_tops function.  This change will break compatibility with a Salt master running versions 3003 and newer and Salt minions running ve
The filename should be `.removed`

2021-03-22 17:19 UTC, Ch3LL approved these changes, later dismissed

2021-03-22 18:20 UTC, s0undt3ch approved these changes, later dismissed

2021-03-23 17:23 UTC, Ch3LL approved these changes

2021-03-23 17:24 UTC, bryceml approved these changes

2021-03-23 17:24 UTC, s0undt3ch approved these changes

2021-03-23 17:27 UTC, merged