Deprecate/utils boto3 elasticsearch
saltstack/salt pull request #59882
Opened 2021-03-23 21:18 UTC by major0

### What does this PR do?

Deprecate usage of `utils/boto3_elasticsearch.py`

### Previous Behavior
The `utils/boto3_elasticsearch.py` was a thin wrapper around botocore to supply the boto3_elasticsearch with the ability to query the _waiter_ objects.  Presumably this was due to a bug in Boto3 at one point in which the waiters where not made available in the ES connection object.

> Botocore waiters for elasticsearch that are not present in boto3+botocore (yet).

The methods in question have been available in the ES connection object for some time now and these utility functions are no longer necessary.

### New Behavior
Use the ES `conn.get_waiter()` from the ES object instead of the botocore.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2021-04-06 16:21 UTC, sagetherage commented
@major0 we are working on these test failures - they likely don't have to do with your PR

2021-07-15 17:16 UTC, Ch3LL requested changes
Just one small change and then we can get this merged.

2021-07-15 17:16 UTC, Ch3LL commented on salt/utils/boto3_elasticsearch.py
> +@salt.utils.decorators.is_deprecated(globals(), "Phosphorus")
```suggestion
@salt.utils.decorators.is_deprecated(globals(), "Sulfur")
```

2021-07-15 17:16 UTC, Ch3LL commented on salt/utils/boto3_elasticsearch.py
> +@salt.utils.decorators.is_deprecated(globals(), "Phosphorus")
```suggestion
@salt.utils.decorators.is_deprecated(globals(), "Sulfur")
```

2021-08-17 11:30 UTC, Ch3LL approved these changes

2021-08-17 17:31 UTC, waynew approved these changes

2021-08-17 17:32 UTC, merged