Fix failing jenkins tests
saltstack/salt pull request #59914
Opened 2021-03-26 19:46 UTC by twangboy

### What does this PR do?
Removes the logfile check from `test_start_shutdown` test in `cli/test_api.py`. This was causing the `test_pub_not_allowed` test in `master\test_clear_funcs.py` to fail and a stack trace that would repeat until the test suite ends.

Also fixes a typo in `test_pub_not_allowed`.

For reference, here's the stacktrace:

```
Traceback (most recent call last):
  File "/home/shane/salt/.nox/pytest-parametrized-3-coverage-false-crypto-none-transport-zeromq/lib/python3.6/site-packages/saltfactories/plugins/log_server.py", line 151, in process_logs
    record = logging.makeLogRecord(record_dict)
  File "/usr/lib/python3.6/logging/__init__.py", line 370, in makeLogRecord
    rv = _logRecordFactory(None, None, "", 0, "", (), None, None)
  File "/home/shane/salt/salt/_logging/impl.py", line 148, in __init__
    self.colorname = "{}[{:<17}]{}".format(LOG_COLORS["name"], self.name, reset)
TypeError: unsupported format string passed to NoneType.__format__
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2021-03-26 21:00 UTC, s0undt3ch submitted a review, later dismissed

2021-03-26 21:04 UTC, krionbsd submitted a review, later dismissed

2021-03-30 05:08 UTC, s0undt3ch requested changes

2021-03-30 05:08 UTC, s0undt3ch commented on salt/_logging/impl.py
> +            if isinstance(item, str) and not isinstance(item, str):
```suggestion
            if isinstance(item, bytes) and not isinstance(item, str):
```

2021-03-30 16:30 UTC, twangboy commented on salt/_logging/impl.py
> +            if isinstance(item, str) and not isinstance(item, str):
I will use bytes

2021-03-30 17:28 UTC, Ch3LL approved these changes

2021-03-30 18:45 UTC, s0undt3ch approved these changes

2021-03-30 19:43 UTC, xeacott approved these changes

2021-03-30 22:35 UTC, merged