Add ssl argument to Mongo connection
saltstack/salt pull request #59927
Opened 2021-03-29 17:26 UTC by babs

### What does this PR do?
Add ssl argument to Mongo connection

2021-11-22 18:41 UTC, waynew requested changes
I really like this addition, for obvious reasons :smile: 

We *do* require test coverage for code that's changed, and we don't really have that here. Is that something that you'd be wiling to add?

If not, no big deal - we'll just add the help-wanted label and will be able to merge when we can write tests for it.

Also this will need a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html)

2021-11-22 18:41 UTC, waynew commented on salt/states/mongodb_user.py
> +
**suggestion** add versionadded, e.g.

```suggestion
    ssl
        Use ssl/tls to connect

        .. versionadded:: Phosphorus

```

2021-11-22 19:00 UTC, babs commented
I'll call for help on that :/

2022-03-30 00:36 UTC, waynew commented
I went ahead and implemented the changes+tests. Just re-merged the latest changes from master in, so :crossed_fingers: hopefully all the tests pass now.

2022-09-12 23:42 UTC, babs commented
@waynew done :)
sorry for the delay.

2023-12-10 12:16 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-11 02:42 UTC, babs commented
It's still relevant unless another PR has been merged that adds ssl to mongodb...

2023-12-18 06:32 UTC, dwoz commented
@babs Please rebase and fix the conflicts.

2023-12-20 14:15 UTC, babs commented
@waynew might need a second pair of eyes and possibly hands to check the rebase :)

2023-12-21 12:58 UTC, babs commented
@waynew might need your help on mongo ssl tests

2024-01-06 09:48 UTC, babs commented
@dwoz do you know somebody that could give me a hand on fixing the instace tests ?

2024-01-07 15:15 UTC, babs commented
@dwoz do you know somebody that could give me a hand on fixing the instance tests ?

2024-01-12 08:40 UTC, babs commented
re-run all

2024-01-12 21:38 UTC, babs commented
re-run all

2024-01-15 21:23 UTC, dwoz approved these changes

2024-01-15 21:24 UTC, merged