Fix #59935: pillar_roots.write on pillar subdirs
saltstack/salt pull request #59944
Opened 2021-04-01 09:55 UTC by niflostancu

### What does this PR do?
Fixes the `pillar_roots.write`'s call to `salt.utils.verify.clean_path` to account for subdirectory writes.

### What issues does this PR fix or reference?
Fixes: #59935

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2021-04-01 14:48 UTC, twangboy approved these changes, later dismissed

2021-05-04 16:47 UTC, Ch3LL requested changes
This will require a changelog and would you please add a test similar to this: https://github.com/saltstack/salt/commit/aafc5ed6de60403c90201d85963299df351147ec#diff-e3e8844bfd715f8094e0c7e1d4294e6d638132fd46e14786ff2ab948e7b48511R34  but testing with a subdir. For example: `sub/../root_dir/`.

2021-09-30 17:41 UTC, Ch3LL commented
@niflostancu bump, did you see my change requests?

2021-09-30 17:57 UTC, niflostancu commented
Oh god, sorry, I completely forgot about this (I've been busy with other projects) :( 
I will fix them tomorrow ;)

2021-10-08 15:24 UTC, Ch3LL approved these changes

2021-10-19 20:39 UTC, dwoz approved these changes

2021-10-20 11:24 UTC, merged