WIP: [DOCS] Update nxos installation docs to use python3
saltstack/salt pull request #59956
Opened 2021-04-02 11:20 UTC by ggiesen

### What does this PR do?
Updates the NX-OS guestshell installation instructions to install Salt using Python3

### What issues does this PR fix or reference?
Fixes: #59750

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-04-30 16:17 UTC, dmurphy18 approved these changes, later dismissed

2021-05-03 10:56 UTC, Ch3LL commented
Is this still a WIP?

2021-07-08 21:53 UTC, ggiesen commented
> 
> 
> Is this still a WIP?

@Ch3LL I was stalling on not having access to a Nexus 3k to test for, and that won't change any time soon, but given how out of date the doc currently is, I think it's better to merge this even if it's not 100% complete rather than let the currently completely out of data doc stand. Any thoughts @dmurphy18?

2021-07-09 16:13 UTC, dmurphy18 commented
Update the docs, better than what is there

2021-07-15 16:13 UTC, Ch3LL approved these changes, later dismissed

2021-07-16 14:36 UTC, ggiesen commented
re-run pr-arch-lts-x86_64-py3-pytest

2021-08-10 12:00 UTC, s0undt3ch requested changes

2021-08-10 12:00 UTC, s0undt3ch commented on doc/topics/installation/nxos.rst
>  .. _here: https://repo.saltstack.com/#rhel
```suggestion
.. _here: https://repo.saltproject.io/#rhel
```

2021-08-10 13:44 UTC, garethgreenaway approved these changes, later dismissed

2021-08-10 22:05 UTC, ScriptAutomate approved these changes

2021-08-10 22:07 UTC, garethgreenaway approved these changes

2021-08-10 22:17 UTC, twangboy approved these changes

2021-08-10 23:04 UTC, merged