fixup nftables.build_rule for saddr/daddr
saltstack/salt pull request #59958
Opened 2021-04-02 19:50 UTC by toanju

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

nftables.build_rule does not correctly build nftables rules when saddr
or daddr is used due to missing whitespace. This PR adds the missing
whitespace to corretly build the rule.

### Previous Behavior
all states that use saddr or daddr fail due to invalid rule

### New Behavior
rules are built in the applicable form

2021-04-06 18:52 UTC, Ch3LL requested changes
would you mind adding a changelog file and test coverage for this change.

2021-04-09 17:34 UTC, toanju commented
here you go @Ch3LL

2021-04-14 16:54 UTC, Ch3LL reviewed
Thanks for updating it, looks good other than just a pre-commit failure that needs to be fixed.

2021-04-16 20:39 UTC, toanju commented
Fixed the pre-commit failures. Thanks for reviewing!

2021-04-21 16:41 UTC, Ch3LL approved these changes

2021-04-21 19:25 UTC, twangboy approved these changes

2021-04-21 19:30 UTC, garethgreenaway approved these changes

2021-04-21 19:30 UTC, merged