[freeze] Add contextvars from site-packages to thin tarball
saltstack/salt pull request #59981
Opened 2021-04-07 00:57 UTC by dwoz

### What does this PR do?

Adds contextvars package from site-packages to thin tarball instead of python's builtin contextvars if the contextvars package from pypi is installed. This makes salt-ssh work with targets that have python <3.7

### What issues does this PR fix or reference?

Fixes: #59942

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

2021-04-13 18:22 UTC, Ch3LL requested changes

2021-04-13 18:22 UTC, Ch3LL commented on salt/utils/thin.py
> +    log.warn("Using contextvars %r", contextvars)
I think this aligns better with a debug log type instead of warn.

2021-04-14 17:11 UTC, Ch3LL submitted a review, later dismissed

2021-04-14 17:14 UTC, Ch3LL commented
looks good other than some test failures on mac

2021-04-15 07:22 UTC, s0undt3ch approved these changes

2021-04-15 20:51 UTC, dwoz commented
re-run macos centos

2021-04-19 16:31 UTC, Ch3LL approved these changes

2021-04-19 17:24 UTC, garethgreenaway approved these changes

2021-04-19 19:21 UTC, merged