Fix regression, allow for templates without keywords specified
saltstack/salt pull request #60052
Opened 2021-04-19 18:42 UTC by dmurphy18

### What does this PR do?
Fixes a regression, allows for the use of templates in files without having to specify keywords to have the template rendered.  A previous PR introduced HandleFileCopy which had the assumption that templates would only be used with keywords incorrectly.  This PR reverts this invalid assumption.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/57665 and https://github.com/saltstack/salt/issues/59333

### Previous Behavior
Files with templates, the templates were ignored unless a keyword was specified.

### New Behavior
Files with templates, the templates are rendered without the need to a specify a keyword, that is, files are now always rendered, reverting to previous mode of operation prior to the introduction of HandleFileCopy commit 5edbbe250a8960b22cb6d40613bcaaa47fc2609d

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-04-19 18:45 UTC, dmurphy18 commented
@vnitinv Can you also review this PR which fixes the regression

2021-04-19 20:02 UTC, s0undt3ch requested changes
Nitpicks, but looks good.

2021-04-19 20:02 UTC, s0undt3ch commented on salt/modules/junos.py
> +        except Exception as exception:  # pylint: disable=broad-except
```suggestion
        except Exception as exc:  # pylint: disable=broad-except
```
No need to be so verbose and it's also more consistent with the bad majority of our code.
Yes, this module has other bad examples :)

2021-04-20 11:31 UTC, vnitinv commented
Looks good to me @dmurphy18 
Thanks for taking care of this.

2021-04-20 15:36 UTC, dmurphy18 commented
@s0undt3ch can you re-review, included your suggestions

2021-04-20 16:44 UTC, s0undt3ch requested changes

2021-04-20 16:44 UTC, s0undt3ch commented on salt/modules/junos.py
> +                exception
```suggestion
                exc
```
The variable changed :)

2021-04-20 16:56 UTC, dmurphy18 commented
@s0undt3ch took suggestion

2021-04-21 17:26 UTC, Ch3LL submitted a review, later dismissed

2021-04-21 17:31 UTC, s0undt3ch requested changes

2021-04-21 17:31 UTC, s0undt3ch commented on salt/modules/junos.py
> +                mhash = master_hash.get("hsum")
```suggestion
```

2021-04-21 17:38 UTC, dmurphy18 commented on salt/modules/junos.py
> +                mhash = master_hash.get("hsum")
Done

2021-04-21 17:49 UTC, s0undt3ch approved these changes

2021-04-21 19:15 UTC, twangboy approved these changes

2021-04-21 19:29 UTC, garethgreenaway approved these changes

2021-04-21 19:29 UTC, merged