Migrate some state tests into pytest
saltstack/salt pull request #60099
Opened 2021-04-28 18:50 UTC by krionbsd

### What does this PR do?
Migrate some state tests into pytest

2021-04-28 21:36 UTC, twangboy approved these changes

2021-04-28 21:37 UTC, twangboy requested changes
Looks like the BTRFS tests are failing on Windows

2021-04-29 17:34 UTC, krionbsd commented
> Looks like the BTRFS tests are failing on Windows

yeah, we have to skip all btrfs tests for Windows, as in original test suite, will commit it shortly, sorry for that

2021-04-30 17:54 UTC, twangboy approved these changes

2021-05-03 19:14 UTC, merged