[WIP] Moving deltaproxy to open
saltstack/salt pull request #60090
Opened 2021-04-27 19:42 UTC by garethgreenaway

### What does this PR do?
Moving deltaproxy to open

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-04-30 20:37 UTC, s0undt3ch requested changes

2021-04-30 20:37 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +from salt.ext import six
These can go away :)
I mean, all `six` usage...

2021-04-30 20:37 UTC, s0undt3ch commented on tests/pytests/integration/conftest.py
> +    yield
```suggestion
    with top_tempfile, ... other temp files.... :
        yield
```

2021-05-01 07:43 UTC, s0undt3ch requested changes

2021-05-01 07:43 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_list_pkgs(salt_cli, salt_proxy):
```suggestion
def test_list_pkgs(salt_cli, salt_delta_proxy):
```
?

2021-05-04 18:02 UTC, s0undt3ch submitted a review, later dismissed
I know, it's a lot :grin:

2021-05-04 18:02 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +                assert value["result"] is True
```suggestion
@pytest.fixture(scope="module")
def proxy_id(salt_delta_proxy):
    cachefile = os.path.join(
        salt_delta_proxy.config["cachedir"], "dummy-proxy-{}.cache".format(salt_delta_proxy.id)
    )
    if os.path.exists(cachefile):
        os.unlink(cachefile)
    try:
        yield salt_delta_proxy
    finally:
        if os.path.exists(cachefile):
            os.unlink(cachefile)


@pytest.fixture(scope="module", params=["dummy_proxy_one", "dummy_proxy_two"])
def proxy_id(salt_delta_proxy, request):
    proxy_id = request.param
    cachefile = os.path.join(
        salt_delta_proxy.config["cachedir"], "dummy-proxy-{}.cache".format(proxy_id)
    )
    if os.path.exists(cachefile):
        os.unlink(cachefile)
    try:
        yield proxy_id
    finally:
        if os.path.exists(cachefile):
            os.unlink(cachefile)


def test_can_it_ping_control_proxy(salt_cli, salt_delta_proxy):
    """
    Ensure the proxy can ping
    """
    ret = salt_cli.run("test.ping", minion_tgt=salt_delta_proxy.id)
    assert ret.json is True


def test_can_it_ping_delta_proxy(salt_cli, proxy_id):
    """
    Ensure the proxy can ping
    """
    ret = salt_cli.run("test.ping", minion_tgt=proxy_id)
    assert ret.json is True


def test_list_pkgs(salt_cli, proxy_id):
    """
    Package test 1, really just tests that the virtual function capability
    is working OK.
    """
    ret = salt_cli.run("pkg.list_pkgs", minion_tgt=proxy_id)
    assert "coreutils" in ret.json
    assert "apache" in ret.json
    assert "redbull" in ret.json


def test_install_pkgs(salt_cli, proxy_id):
    """
    Package test 2, really just tests that the virtual function capability
    is working OK.
    """
    ret = salt_cli.run("pkg.install", "thispkg", minion_tgt=proxy_id)
    assert ret.json["thispkg"] == "1.0"

    ret = salt_cli.run("pkg.list_pkgs", minion_tgt=proxy_id)

    assert ret.json["apache"] == "2.4"
    assert ret.json["redbull"] == "999.99"
    assert ret.json["thispkg"] == "1.0"


def test_remove_pkgs(salt_cli, proxy_id):
    ret = salt_cli.run("pkg.remove", "apache", minion_tgt=proxy_id)
    assert "apache" not in ret.json


def test_upgrade(salt_cli, proxy_id):
    ret = salt_cli.run("pkg.upgrade", minion_tgt=proxy_id)
    assert ret.json["coreutils"]["new"] == "2.0"
    assert ret.json["redbull"]["new"] == "1000.99"


def test_service_list(salt_cli, proxy_id):
    ret = salt_cli.run("service.list", minion_tgt=proxy_id)
    assert "ntp" in ret.json


def test_service_stop(salt_cli, proxy_id):
    ret = salt_cli.run("service.stop", "ntp", minion_tgt=proxy_id)
    ret = salt_cli.run("service.status", "ntp", minion_tgt=proxy_id)
    assert ret.json is False


def test_service_start(salt_cli, proxy_id):
    ret = salt_cli.run("service.start", "samba", minion_tgt=proxy_id)
    ret = salt_cli.run("service.status", "samba", minion_tgt=proxy_id)
    assert ret.json is True


def test_service_get_all(salt_cli, proxy_id):
    ret = salt_cli.run("service.get_all", minion_tgt=proxy_id)
    assert ret.json
    assert "samba" in ret.json


def test_grains_items(salt_cli, proxy_id):
    ret = salt_cli.run("grains.items", minion_tgt=proxy_id)
    assert ret.json["kernel"] == "proxy"
    assert ret.json["kernelrelease"] == "proxy"



@pytest.fixture(scope="module")
def proxy_state_tree(tmp_path, base_env_state_tree_root_dir):
    test_file = tmp_path / "testfile"
    top_sls = """
    base:
      '*':
        - core
    """
    core_state = """
    {}:
      file:
        - managed
        - source: salt://testfile
        - makedirs: true
    """.format(
        test_file
    )

    with pytest.helpers.temp_file(
        "top.sls", top_sls, base_env_state_tree_root_dir
    ), pytest.helpers.temp_file("core.sls", core_state, base_env_state_tree_root_dir):
        yield


@pytest.mark.usefixtures("proxy_state_tree")
def test_state_apply(salt_cli, proxy_id):
    ret = salt_cli.run("state.apply", "core", minion_tgt=proxy_id)
    for value in ret.json.values():
        assert value["result"] is True


@pytest.mark.slow_test
@pytest.mark.usefixtures("proxy_state_tree")
def test_state_highstate(salt_cli, proxy_id):
    ret = salt_cli.run("state.highstate", minion_tgt=proxy_id)
    for value in ret.json.values():
        assert value["result"] is True
```

2021-05-04 18:03 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +        assert "redbull" in ret.json
Next comment reworks the whole test module...

2021-05-04 18:11 UTC, garethgreenaway commented on salt/metaproxy/deltaproxy.py
> +        self.opts["master"] = master
We had discussed this, if `pillar_opts` is enabled on the Salt master then `master` is overridden and we want to ensure it's set correctly to the value passed in.

2021-05-04 18:15 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +        self.opts["master"] = master
Yes, I know. Let's add a comment to the code too, so no one feels tempted to move it?

2021-05-04 18:40 UTC, garethgreenaway commented on tests/pytests/conftest.py
> +
Did you mean move it to `tests/pytests/integration/conftest.py` since it's already in `tests/pytests/conftest.py`?

2021-05-04 18:44 UTC, s0undt3ch commented on tests/pytests/conftest.py
> +
Yes, only have it in `tests/pytests/contest.py`

2021-07-06 17:51 UTC, Ch3LL requested changes

2021-07-06 17:51 UTC, Ch3LL commented on salt/proxy/deltaproxy.py
> +    log.debug("Deltaproxy control proxy __virtual__() called...")
This doesn't seem necessary.

2021-07-06 17:51 UTC, Ch3LL commented on salt/proxy/deltaproxy.py
> +    log.debug("deltaproxy proxy init() called...")
or this

2021-07-07 16:54 UTC, Ch3LL approved these changes, later dismissed

2021-07-13 17:22 UTC, Ch3LL approved these changes, later dismissed

2021-07-14 03:32 UTC, s0undt3ch requested changes

2021-07-14 03:32 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +        tag = "deltaproxy/start"
Shouldnt all Salt's own events be `salt/` prefixed?

2021-07-14 03:32 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +
```suggestion

    proxy_init_func_name = "{}.init".format(fq_proxyname)
    
```

2021-07-14 03:32 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +        "{}.init".format(fq_proxyname) not in self.proxy
Use `proxy_init_func_name` here

2021-07-14 03:32 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +    proxy_init_fn = self.proxy[fq_proxyname + ".init"]
```suggestion
    proxy_init_fn = self.proxy[proxy_init_func_name]
```

2021-07-14 03:32 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +
Ignore this, just marking where I am...

2021-08-03 17:19 UTC, Ch3LL commented
@garethgreenaway is this ready for re-review?

2021-08-03 17:24 UTC, garethgreenaway commented
@Ch3LL I wasn't sure if @s0undt3ch had any additional reviews he was working through.

2021-08-03 17:59 UTC, s0undt3ch commented
Yes, i should finish my review...

2021-08-03 18:27 UTC, s0undt3ch requested changes
K. Done reviewing,

2021-08-03 18:27 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +    _id = opts["id"]
```suggestion

```
Not needed right?

2021-08-03 18:27 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +
```suggestion

```
Not needed right?

2021-08-03 18:27 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +            if "{}.allow_missing_func" in minion_instance.executors
```suggestion
            if "{}.allow_missing_func".format(executor) in minion_instance.executors
```

2021-08-03 18:27 UTC, s0undt3ch commented on salt/proxy/dummy.py
> +    __context__["dummy_proxy"]["id"] = opts["id"]
```suggestion
    __context__["dummy_proxy"] = {"id": opts["id"]}
```

2021-08-03 18:27 UTC, s0undt3ch commented on salt/proxy/napalm.py
> +    __context__["napalm_device"]["details"]["initialized"] = True
```suggestion
    __context__["napalm_device"] = {
        "opts": opts,
        "id": opts["id"],
        "network_device": salt.utils.napalm.get_device(opts),
        "details": {"initialized": True}
    }
```

2021-08-03 18:27 UTC, s0undt3ch commented on salt/proxy/rest_sample.py
> +    __context__["rest_sample"]["url"] = opts["proxy"]["url"]
The whole `__context__["rest_sample"]` dictionary can be constructed in full as suggested on the previous file.

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/conftest.py
> +    config_defaults["master"] = "127.0.0.1"
```suggestion
    config_defaults = {
        "root_dir": str(root_dir),
        "hosts.file": os.path.join(RUNTIME_VARS.TMP, "hosts"),  # Do we really need this for these tests?
        "aliases.file": os.path.join(RUNTIME_VARS.TMP, "aliases"),  # Do we really need this for these tests?
        "transport": salt_master_factory.config["transport"],
        "user": salt_master_factory.config["user"],
        "metaproxy": "deltaproxy",
        "master": "127.0.0.1",
    }
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +@pytest.fixture(scope="module")
```suggestion
@pytest.fixture(scope="module", autouse=True)
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_list_pkgs(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_list_pkgs(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_install_pkgs(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_install_pkgs(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_remove_pkgs(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_remove_pkgs(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_upgrade(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_upgrade(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_service_list(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_service_list(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_service_stop(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_service_stop(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_service_start(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_service_start(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_service_get_all(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_service_get_all(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +def test_grains_items(salt_cli, salt_delta_proxy, proxy_id):
```suggestion
def test_grains_items(salt_cli, proxy_id):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +):
```suggestion
def test_state_apply(
    salt_cli, tmp_path, base_env_state_tree_root_dir, proxy_id
):
```

2021-08-03 18:27 UTC, s0undt3ch commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +):
```suggestion
def test_state_highstate(
    salt_cli, tmp_path, base_env_state_tree_root_dir, proxy_id
):
```

2021-08-24 16:28 UTC, dwoz approved these changes

2021-08-24 17:40 UTC, merged