modules/ssh.py: allow all additional ssh key types
saltstack/salt pull request #60128
Opened 2021-05-04 18:27 UTC by MEschenbacher

### What does this PR do?

Propose a fix for #59429 by extending the list of allowed ssh public key types in `salt/modules/ssh.py` as of openssh 8.5.

### What issues does this PR fix or reference?
Fixes: #59429

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-08-12 00:39 UTC, xeacott commented
Hey @MEschenbacher are you still wanting to make more changes to this PR? We can get this into Si just need to keep moving along

2021-08-12 07:37 UTC, MEschenbacher commented
The PR should be complete as far as changes to code are concerned. Are you fine with the changes themselves?

I'm assuming in order to move along, I need to check all boxes?

2021-08-12 19:12 UTC, Ch3LL commented on salt/modules/ssh.py
> +
looks like @dwoz preferred option 1 from this comment https://github.com/saltstack/salt/issues/59429#issuecomment-794576844

@dwoz would you mind reviewing here.

2021-08-12 19:12 UTC, Ch3LL requested changes
This will require a changelog file.

2021-08-17 07:19 UTC, MEschenbacher commented
Okay, I'm now waiting for the final call as to whether we allow any pubkey type or continue maintaining an allowlist of types.

2021-08-30 21:41 UTC, xeacott commented
I think the debian test is the last one to address here, and there's only one, and then we should be good to go!

2021-09-14 19:48 UTC, dwoz requested changes
Pre-commit and tests need to be fixed still.

2021-09-18 10:23 UTC, MEschenbacher commented
I've added a few tests and I'm not sure if they assert that all salt modules and states with a ssh key type accept the additional key types. As far as the failing test for debian jinja filters is concerned: need to look into it.

2021-09-22 00:02 UTC, Ch3LL commented
The jinja filters tests is a know failing test that someone else is working on and is not related to this PR. The pre-commit and lint test failures will need to be cleaned up though.

2021-09-30 18:00 UTC, Ch3LL commented
I went ahead and pushed a fix for pre-commit and lint. Just waiting on the test results.

2021-09-30 18:01 UTC, Ch3LL commented
@MEschenbacher is this still WIP? Or is it ready for review and merge?

2021-10-03 16:30 UTC, MEschenbacher commented
Ready for review and merge.

2021-10-05 15:50 UTC, Ch3LL approved these changes

2021-10-19 20:36 UTC, dwoz approved these changes

2021-10-20 11:24 UTC, merged