Use os-release ID_LIKE for the os-family grain
saltstack/salt pull request #60171
Opened 2021-05-11 16:15 UTC by evelikov

### What does this PR do?

This MR parses the `ID_LIKE` token in the `os-release` file and uses it for the `os-family` grain, before falling back to the old heuristics.

As result this paves the way to more scale-able Linux distribution handling. In particular, today each new distro needs an entry in `_OS_FAMILY_MAP` (and potentially `_OS_NAME`), while the information is readily available within `os-release`. It also opens the path to cleanup the parsing of non `os-release` release files and remove the vast part of `_OS_NAME_MAP` and `_OS_FAMILY_MAP`.

But all those can follow in due course.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
`os-family` grain is used based on the `os` grain and `_OS_FAMILY_MAP`

### New Behavior
`os-family` grain is set to a valid distribution entry, as based on `ID_LIKE` and `_OS_NAME_MAP`. If missing or invalid, we fallback to the old behaviour.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-05-13 15:30 UTC, evelikov commented
Can anyone share why the CI is failing - the output is truncated :-\

2021-05-15 18:43 UTC, xmsk commented
> Can anyone share why the CI is failing - the output is truncated :-\

If you click on 'Details' on the failing job all the way at the bottom there is a link to the Jenkins build where you can check the console output, e.g. https://jenkins.saltproject.io/job/pr-ubuntu-2004-amd64-py3-pytest/job/PR-60171/1/console

2021-05-31 08:43 UTC, evelikov commented
The logs are not so helpful why things are failing. Especially in the macosx case - the series does not touch any non-linux code.
Can anyone guide me in the right direction? Thanks

2022-10-21 19:10 UTC, twangboy requested changes
This needs a changelog and a test case

2022-10-21 19:29 UTC, evelikov commented
@twangboy do you have any PR or anything else I can use as a reference? Also happy 1 year anniversary :-P

2023-12-10 11:03 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 11:03 UTC, closed without merging

2024-07-17 17:45 UTC, dmurphy18 commented
@evelikov The following command gives lots of examples of testing grains, cut & paste & manipulate for the test to exercise your code changes.  Testing a grain is pretty simple.
```
david@david-XPS-15-9570:~/devcode/dgm_salt_3006/salt$ find tests/pytests/ -name "test*grains*"
tests/pytests/integration/ssh/test_grains.py
tests/pytests/integration/modules/saltutil/test_grains.py
tests/pytests/pkg/integration/test_salt_grains.py
tests/pytests/functional/grains/test_grains.py
tests/pytests/unit/states/test_grains.py
tests/pytests/unit/modules/test_grains.py
david@david-XPS-15-9570:~/devcode/dgm_salt_3006/salt$ 
```
For your changes, recommend doing a unit test since very simple change.
Also the changelog can be a one-liner, similar to a git commit string, look at other for examples: