[WIP] Fix race condition in batch logic #56273
saltstack/salt pull request #60256
Opened 2021-05-26 01:06 UTC by dwoz

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-05-27 22:21 UTC, cmcmarrow approved these changes, later dismissed

2021-05-27 22:21 UTC, garethgreenaway approved these changes, later dismissed

2021-06-04 15:32 UTC, s0undt3ch requested changes

2021-06-04 15:32 UTC, s0undt3ch commented on salt/client/__init__.py
> +    :param bool mopts: When provided the local client will use is dictionary of
```suggestion
    :param bool mopts: When provided the local client will use this dictionary of
```

2021-06-04 15:32 UTC, s0undt3ch commented on salt/client/__init__.py
> +        :param bool mopts: When provided the local client will use is dictionary of
```suggestion
        :param bool mopts: When provided the local client will use this dictionary of
```

2021-06-04 22:05 UTC, garethgreenaway submitted a review, later dismissed

2021-06-05 00:44 UTC, Oloremo commented on changelog/56273.fixed
> +Fix race condition in batch logic. Adds an option to `salt.client.LocalClient`
Not sure about verbose but entry is a need. Not sure what is "not client-facing" - we're facing that issue on a daily basis! :-)

2021-06-16 21:37 UTC, dwoz commented on changelog/56273.fixed
> +Fix race condition in batch logic. Adds an option to `salt.client.LocalClient`
I've lessened the verbosity of this changelog

2021-06-18 21:44 UTC, dwoz commented
re-run all

2021-06-19 01:29 UTC, dwoz commented
These changes were put in 3003.1 (#60310) and will be merged into master with #60396

2021-06-19 01:29 UTC, closed without merging