update bug_template.md
saltstack/salt pull request #60255
Opened 2021-05-26 00:17 UTC by sagetherage

Add checkboxes for on-prem, VMs, containers, etc.

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-05-26 00:19 UTC, cmcmarrow approved these changes, later dismissed

2021-05-26 00:20 UTC, ScriptAutomate approved these changes, later dismissed

2021-05-26 03:26 UTC, s0undt3ch submitted a review, later dismissed

2021-05-26 06:23 UTC, krionbsd requested changes

2021-05-26 06:23 UTC, krionbsd commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] VM (Virtualbox, KVM, etc. please specify)
it might be VMs running on cloud services as well, we have to add an input field to add explicit comments to elaborate it.

2021-05-26 06:23 UTC, krionbsd commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
... jails if it's about FreeBSD

2021-05-27 19:21 UTC, s0undt3ch approved these changes

2021-05-28 06:34 UTC, krionbsd approved these changes

2021-06-29 18:25 UTC, Ch3LL commented
This is consistently failing. Can you take a look here @sagetherage

2021-08-17 22:28 UTC, ScriptAutomate approved these changes
Looks fine, I think. Errors in this PR are unrelated, since they have to do with the `salt` codebase. Examples:

- Error rooted in `pr-lint` which is doing static code analysis: https://jenkins.saltproject.io/job/pr-lint/job/PR-60255/14/console
```
16:09:58  [Static Analysis] [-ERROR-] Setting the reference job has been deprecated, please use the new reference recorder
16:09:58  [Static Analysis] [-ERROR-] Configured reference job 'pr-lint/env.CHANGE_TARGET' does not exist
16:09:58  [Static Analysis] No valid reference build found that meets the criteria (No history found)
16:09:58  [Static Analysis] All reported issues will be considered outstanding
16:09:58  [Static Analysis] Evaluating quality gates
16:09:58  [Static Analysis] -> FAILED - Total (any severity): 5 - Quality QualityGate: 1
16:09:58  [Static Analysis] -> Some quality gates have been missed: overall result is FAILED
16:09:58  [Static Analysis] Health report is disabled - skipping
16:09:58  [Static Analysis] Created analysis result for 5 issues (found 0 new issues, fixed 0 issues)
16:09:58  [Static Analysis] Attaching ResultAction with ID 'analysis' to build 'pr-lint/PR-60255 #14'.
16:09:59  [GitHub Checks] GitHub check (name: Static Analysis, status: COMPLETED) has been published.
```
- Static analysis errors/warnings against Salt codebase: https://jenkins.saltproject.io/job/pr-lint/job/PR-60255/14/analysis/
  - These have to do with Python static code analysis of the `salt/*` dir

I'm not sure what the other failures may be, but these failures above are unrelated. If tickets aren't opened around these, or if they aren't being reviewed/address, they need to be looked at as they will cause failures across other PRs.

2021-08-17 22:32 UTC, garethgreenaway approved these changes

2021-08-17 22:32 UTC, merged