Add #60262 to freeze
saltstack/salt pull request #60283
Opened 2021-06-01 11:23 UTC by Ch3LL

Add #60262 to freeze

2021-06-01 12:34 UTC, s0undt3ch submitted a review, later dismissed

2021-06-01 15:08 UTC, waynew requested changes
Just a lil' typo in the changelog, but otherwise :+1:

2021-06-01 15:08 UTC, waynew commented on changelog/60049.fixed
> +IPCMessageSubscriber objects expose their connect method as a corotine so they
**suggestion**: typo
```suggestion
IPCMessageSubscriber objects expose their connect method as a coroutine so they
```

2021-06-03 16:30 UTC, twangboy approved these changes

2021-06-04 17:20 UTC, merged