Removing unsupported version of Salt from compat tests
saltstack/salt pull request #60348
Opened 2021-06-09 18:32 UTC by garethgreenaway

### What does this PR do?
Removing unsupported version of Salt from tests.pytests.scenarios.compat.test_with_versions.py

### What issues does this PR fix or reference?
Fixes: #59753

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-06-10 06:47 UTC, krionbsd approved these changes, later dismissed

2021-06-13 08:38 UTC, s0undt3ch submitted a review, later dismissed

2021-06-14 16:28 UTC, Ch3LL requested changes

2021-06-14 16:28 UTC, Ch3LL commented on changelog/59753.changed
> +Removing unsupported version of Salt from tests.pytests.scenarios.compat.test_with_versions.py
Test fixes should not include a changelog, unless its changing Salt code.

2021-06-23 18:12 UTC, Ch3LL approved these changes

2021-06-24 12:28 UTC, Ch3LL commented
re-run all

2021-06-24 17:25 UTC, merged