Address leaks in fileserver caused by git backends
saltstack/salt pull request #60386
Opened 2021-06-16 21:07 UTC by dwoz

### What does this PR do?

At this time we do not have the ability to fix the upstream memory leaks
in the gitfs backend providers. Work around their limitations by
periodically restarting the file server update proccess. This will at
least partially address #50313

### What issues does this PR fix or reference?
Fixes: #50313

### Previous Behavior

File server update process would run indefinitely continuing to leak memory. 

### New Behavior

File server update process will restart periodically to release held memory.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

2021-06-17 06:19 UTC, krionbsd submitted a review, later dismissed

2021-06-18 02:20 UTC, dwoz commented
re-run mac

2021-06-20 07:19 UTC, s0undt3ch requested changes

2021-06-20 07:19 UTC, s0undt3ch commented on salt/master.py
> +                        "Updating %s fileserver cache for the following " "targets: %s",
```suggestion
                        "Updating %s fileserver cache for the following targets: %s",
```

2021-06-20 07:19 UTC, s0undt3ch commented on salt/master.py
> +                    "Uncaught exception while updating %s fileserver " "cache",
```suggestion
                    "Uncaught exception while updating %s fileserver cache",
```

2021-06-23 12:11 UTC, Ch3LL approved these changes

2021-06-23 12:11 UTC, merged

2021-06-23 12:18 UTC, afischer-opentext-com commented
Sorry for the spamming, but a big THANKS for this!

2021-07-12 20:16 UTC, dwoz commented
I believe this should resolve most, if not all of #59360