FEAT 60430: Add ability for wait_for_event to handle list event_id values
saltstack/salt pull request #60443
Opened 2021-06-25 16:28 UTC by jwyoungpm

### What does this PR do?

Adds support for comparing `id_list` with a list when the value for `event_id` is a list in the `salt.wait_for_event` module. 

### What issues does this PR fix or reference?
~Fixes~ Implements:

#60430 

### Previous Behavior

Previously, `salt.wait_for_event` only supported `event_id` values that where `str`.

### New Behavior

In addition to the previous behavior, now supports `event_id` values that are lists. 

Given the event:

```json
{
   "data": {
      "new": [], 
      "lost": [
         "some_old_node"
      ], 
      "_stamp': '2021-06-23T15:02:04.621354"
     }, 
     "tag": "salt/presence/change"
}
```

the following `salt.wait_for_event` would not work peviously: 

```yaml
wait-for-node-death:
  salt.wait_for_event:
    - name: salt/presence/change
    - id_list:
       - some_old_node
    - timeout: 3000
    - event_id: lost
```

This PR checks if the `val` returned by the `event_id` location in the event is a list and if so, pops off any values from `id_list` that it finds in `val`

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs - **Docs do not diferentiate between value types returned by `event_id` so I did not update**
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-07-14 03:17 UTC, s0undt3ch requested changes

2021-07-14 03:17 UTC, s0undt3ch commented on salt/states/saltmod.py
> +                        if len(val_list) == 0:
```suggestion
                        if not val_list:
```

2021-07-14 03:17 UTC, s0undt3ch commented on salt/states/saltmod.py
> +                        elif len(val_list) > 0:
```suggestion
                        elif val_list:
```

2021-07-14 03:17 UTC, s0undt3ch commented on salt/states/saltmod.py
> +                        elif len(val_list) > 0:
```suggestion
                        else:
```
This might even be more appropriate.

2021-07-14 19:46 UTC, s0undt3ch approved these changes

2021-07-25 15:53 UTC, jwyoungpm commented
@krionbsd sorry I haven't come back and checked on this, out on paternity :) 

Could someone have a look at this? Let me know if there are any blockers to merging.

2021-07-26 09:15 UTC, krionbsd approved these changes

2022-01-12 18:34 UTC, jwyoungpm commented
@krionbsd @s0undt3ch Sorry for the very late follow up on this...I got back from paternity leave not long ago, I believe this is still a valid MR. Is this still something I could get merged? You both have approved but I can't click the merge button. 

Thanks!

2022-10-05 18:43 UTC, merged