Wildcard fixes to yumpkg.  Moving tests to pytest.
saltstack/salt pull request #60461
Opened 2021-06-30 01:23 UTC by garethgreenaway

### What does this PR do?
Adding the ability for yumpkg.remove to handle package names with widdcards.  Moving missing yumpkg unit tests over to pytests and removing the unit/modules/test_yumpkg.py test file.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-06-30 06:32 UTC, krionbsd submitted a review, later dismissed

2021-06-30 06:57 UTC, s0undt3ch requested changes

2021-06-30 06:57 UTC, s0undt3ch commented on salt/modules/yumpkg.py
> +    for pkg_param in copy.deepcopy(pkg_params):
```suggestion
    for pkg_param in list(pkg_params):
```
A copy of the keys should be enough?

2021-06-30 06:57 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_yumpkg.py
> +@patch("salt.modules.yumpkg._yum", Mock(return_value="dnf"))
`with patch(....):` instead of the decorator?

https://engblog.nextdoor.com/what-your-mocks-do-when-you-aren-t-looking-b278e0d9e201

2021-06-30 06:57 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_yumpkg.py
> +    pytest.raises(CommandExecutionError, yumpkg.services_need_restart)
```suggestion
    with pytest.raises(CommandExecutionError):
       yumpkg.services_need_restart()
```
I'm not asking to change here, but you know this also works?

Again, not a required change.

2021-06-30 14:58 UTC, s0undt3ch approved these changes

2021-06-30 14:58 UTC, krionbsd approved these changes

2021-06-30 18:06 UTC, Ch3LL approved these changes

2021-07-06 17:26 UTC, merged

2021-07-06 18:05 UTC, sharkbruhaha commented
thanks all!