add debian 11 to ci tests
saltstack/salt pull request #60473
Opened 2021-07-01 04:25 UTC by bryceml

### What does this PR do?
Adds debian 11 (not released yet) to CI pipelines so we can easily release when debian 11 actually comes out.

2021-07-01 18:54 UTC, s0undt3ch requested changes

2021-07-01 18:54 UTC, s0undt3ch commented on cicd/jenkins/pr-debian-11-amd64-py3-pytest
> +    //splits: ['unit', 'integration', 'multimaster'],
This comment can go away

2021-07-01 18:54 UTC, s0undt3ch commented on cicd/jenkins/pr-debian-11-amd64-py3-pytest
> +    //fast_slow_staged_testrun: true
This one too

2021-07-02 15:14 UTC, bryceml commented
re-run full centos-7

2021-07-02 15:14 UTC, bryceml commented
re-run full arch

2021-07-02 15:14 UTC, bryceml commented
re-run full mojave

2021-07-02 15:14 UTC, bryceml commented
re-run full windows

2021-07-02 15:32 UTC, krionbsd approved these changes

2021-07-02 15:39 UTC, joechainz approved these changes
Looks Good

2021-07-02 15:45 UTC, s0undt3ch approved these changes

2021-07-06 15:26 UTC, bryceml commented
re-run full centos-7
re-run full windows
re-run full pr-ubuntu-2004-amd64-py3-pycryptodome
re-run full debian-11
re-run full arch
re-run full mojave

2021-07-07 12:01 UTC, merged