Fix Salt API TypeError With External Auth
saltstack/salt pull request #60493
Opened 2021-07-05 18:32 UTC by s0undt3ch

### What does this PR do?
See title

### What issues does this PR fix or reference?
Fixes: #56495

2021-10-20 17:22 UTC, twangboy submitted a review, later dismissed

2022-06-15 14:37 UTC, waynew requested changes, later dismissed
**question** Would it be possible/reasonable/a good idea to add (functional?) test cases matching each of the syntaxes that we have in our docs?

IIUC the ExternalAuthConfig tests the part once it's been parsed, but would it make sense to have test cases from YAML -> ???

2022-06-15 14:39 UTC, s0undt3ch commented
> **question** Would it be possible/reasonable/a good idea to add (functional?) test cases matching each of the syntaxes that we have in our docs?
> 
> IIUC the ExternalAuthConfig tests the part once it's been parsed, but would it make sense to have test cases from YAML -> ???

Could we do that after release? Maybe even during the RC.
I just don't think its reason enough to block merging this issue.

2022-06-15 18:14 UTC, Ch3LL approved these changes

2022-06-15 18:28 UTC, merged