Fixing various functions in the file state module that use user.info
saltstack/salt pull request #60502
Opened 2021-07-07 18:35 UTC by garethgreenaway

### What does this PR do?
Fixing various functions in the file state module that use user.info to get group information, certain hosts particularly proxy minions do not have the user.info function avaiable.  In those cases we fall back to using the username for the group name.  Also moving the existing file state module unit tests over to pytest and breaking them out into seperate files for easier management.

### What issues does this PR fix or reference?
Fixes: #57786

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-07-13 11:05 UTC, s0undt3ch requested changes

2021-07-13 11:05 UTC, s0undt3ch commented on tests/pytests/unit/states/file/test_private_functions.py
> +        shutil.rmtree(root_tmp_dir)
```suggestion
def test__check_directory(tmp_path):
    """
    Test the _check_directory function
    Make sure that recursive file permission checks return correctly
    """
    # set file permissions
    # Run _check_directory function
    # Verify that it returns correctly
    # Delete tmp directory structure
    root_tmp_dir = str(tmp_path / "test__check_dir")
    expected_mode = 0o770
    changed_mode = 0o755
    depth = 3
    def create_files(tmp_dir):
        for f in range(depth):
            path = os.path.join(tmp_dir, "file_{:03}.txt".format(f))
            with salt.utils.files.fopen(path, "w+"):
                os.chmod(path, expected_mode)

    # Create tmp directory structure
    os.mkdir(root_tmp_dir)
    os.chmod(root_tmp_dir, expected_mode)
    create_files(root_tmp_dir)

    for d in range(depth):
        dir_name = os.path.join(root_tmp_dir, "dir{:03}".format(d))
        os.mkdir(dir_name)
        os.chmod(dir_name, expected_mode)
        create_files(dir_name)
        for s in range(depth):
            sub_dir_name = os.path.join(dir_name, "dir{:03}".format(s))
            os.mkdir(sub_dir_name)
            os.chmod(sub_dir_name, expected_mode)
            create_files(sub_dir_name)
    # Symlinks on linux systems always have 0o777 permissions.
    # Ensure we are not treating them as modified files.
    target_dir = os.path.join(root_tmp_dir, "link_target_dir")
    target_file = os.path.join(target_dir, "link_target_file")
    link_dir = os.path.join(root_tmp_dir, "link_dir")
    link_to_dir = os.path.join(link_dir, "link_to_dir")
    link_to_file = os.path.join(link_dir, "link_to_file")

    os.mkdir(target_dir)
    os.mkdir(link_dir)
    with salt.utils.files.fopen(target_file, "w+"):
        pass
    os.symlink(target_dir, link_to_dir)
    os.symlink(target_file, link_to_file)
    for path in (target_dir, target_file, link_dir, link_to_dir, link_to_file):
        try:
            os.chmod(path, expected_mode, follow_symlinks=False)
        except (NotImplementedError, SystemError, OSError):
            os.chmod(path, expected_mode)

    # Set some bad permissions
    changed_files = {
        os.path.join(root_tmp_dir, "file_000.txt"),
        os.path.join(root_tmp_dir, "dir002", "file_000.txt"),
        os.path.join(root_tmp_dir, "dir000", "dir001", "file_002.txt"),
        os.path.join(root_tmp_dir, "dir001", "dir002"),
        os.path.join(root_tmp_dir, "dir002", "dir000"),
        os.path.join(root_tmp_dir, "dir001"),
    }
    for c in changed_files:
        os.chmod(c, changed_mode)

    ret = filestate._check_directory(
        root_tmp_dir,
        dir_mode=oct(expected_mode),
        file_mode=oct(expected_mode),
        recurse=["mode"],
    )
    assert changed_files == set(ret[-1].keys())
```
We could also use `pathlib.Path(...).{touch,mkdir,chmod}()` here too, but not a blocker.

2021-07-13 11:05 UTC, s0undt3ch commented on tests/pytests/unit/states/file/test_rename.py
> +            comt = 'Source file "{}" has already been moved out of ' "place".format(
```suggestion
            comt = 'Source file "{}" has already been moved out of place'.format(
```

2021-07-13 11:05 UTC, s0undt3ch commented on tests/pytests/unit/states/file/test_rename.py
> +            comt = 'The target file "{}" exists and will not be ' "overwritten".format(
```suggestion
            comt = 'The target file "{}" exists and will not be overwritten'.format(
```

2021-07-13 11:05 UTC, s0undt3ch commented on tests/pytests/unit/states/file/test_rename.py
> +                comt = 'Failed to delete "{}" in preparation for ' "forced move".format(
```suggestion
                comt = 'Failed to delete "{}" in preparation for forced move'.format(
```

2021-07-13 17:38 UTC, Ch3LL submitted a review, later dismissed
yay for taking the time to migrate the file tests :) Looks good other than what pedro mentioned

2021-08-04 17:44 UTC, Ch3LL approved these changes, later dismissed

2021-08-10 17:46 UTC, Ch3LL submitted a review, later dismissed

2021-08-24 15:42 UTC, Ch3LL approved these changes

2021-08-24 15:43 UTC, merged