Migrate netapi tests to PyTest
saltstack/salt pull request #60544
Opened 2021-07-14 16:08 UTC by s0undt3ch

### What does this PR do?
See title
This is also the precursor for the fix to #56495 on https://github.com/saltstack/salt/pull/60493

2021-07-27 17:20 UTC, Ch3LL approved these changes, later dismissed

2021-08-11 12:14 UTC, Ch3LL requested changes

2021-08-11 12:14 UTC, Ch3LL commented on tests/pytests/integration/netapi/test_ssh_client.py
> +    tgt = "www.zerodayinitiative.com"
How about we use https://pytest-httpserver.readthedocs.io/en/latest/ here or something similar, so we are not depending on external resources.

2021-08-11 19:19 UTC, s0undt3ch commented on tests/pytests/integration/netapi/test_ssh_client.py
> +    tgt = "www.zerodayinitiative.com"
Yep, that might be a good approach going forward.

2021-09-30 17:45 UTC, Ch3LL commented on tests/pytests/integration/netapi/test_ssh_client.py
> +    tgt = "www.zerodayinitiative.com"
Did you want to handle that in this PR or a follow up one? I'm fine either way.

2021-09-30 18:33 UTC, s0undt3ch commented on tests/pytests/integration/netapi/test_ssh_client.py
> +    tgt = "www.zerodayinitiative.com"
This one still needs work, i have to revisit this.
But probably on a separate PR, where we address all webservers we use ...

2022-03-09 20:06 UTC, Ch3LL commented
Are there still plans to try to get this in for phosphorus or can I take off the phosphorus label?

2022-03-10 08:11 UTC, s0undt3ch commented
Switched to 3006 and converted to draft

2022-06-11 07:15 UTC, s0undt3ch commented
re-run full all

2022-06-13 19:14 UTC, Ch3LL approved these changes

2022-06-13 19:14 UTC, merged