Add heist and heist-salt runner
saltstack/salt pull request #60556
Opened 2021-07-15 15:53 UTC by Ch3LL

### What does this PR do?
Adds the heist and heist-salt runner.

2021-07-17 03:11 UTC, garethgreenaway commented on changelog/60556.added
> +Add the heist and heist-salt runner.
Super minor but is the `the` in the wrong place?

2021-07-17 03:16 UTC, garethgreenaway approved these changes

2021-07-18 11:59 UTC, s0undt3ch requested changes

2021-07-18 11:59 UTC, s0undt3ch commented on tests/pytests/unit/runners/test_heist_salt.py
> +def test_hub():
Same as the other test module

2021-07-18 11:59 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_hub.py
> +def test_hub():
Same as the other test modules

2021-07-20 16:49 UTC, Ch3LL commented
closing as i will work on migrating this to a salt-extension project.

2021-07-20 16:49 UTC, closed without merging