Deny ability for creation of files/folders on windows if user is not found on the system
saltstack/salt pull request #60550
Opened 2021-07-14 22:02 UTC by xeacott

### What does this PR do?
Validate the requested user has an account before modifying a windows system for file/folder creation.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-07-29 00:16 UTC, twangboy approved these changes, later dismissed

2021-08-10 18:25 UTC, Ch3LL requested changes
changelog

2021-08-10 18:25 UTC, Ch3LL commented on salt/modules/win_file.py
> +
`.. versionadded:: 3004`

2023-12-10 22:28 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 22:28 UTC, closed without merging