Move to pytests
saltstack/salt pull request #60571
Opened 2021-07-19 18:05 UTC by cmcmarrow

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-07-19 18:07 UTC, cmcmarrow commented
https://github.com/saltstack/salt/pull/60526

2021-07-20 19:28 UTC, s0undt3ch requested changes

2021-07-20 19:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_crypt.py
> +    # make sure reinit cryptot does not crash
```suggestion
    # make sure reinit crypto does not crash
```

2021-07-20 19:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_crypt.py
> +    # make sure the right liberty is used for random
```suggestion
    # make sure the right library is used for random
```

2021-07-20 19:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_crypt.py
> +        with patch("salt.utils.crypt.Random", None):
This patch is not needed, right?

2021-07-20 19:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_crypt.py
> +        with patch("salt.utils.crypt.Random", None):
Because `Random` usage is always behind an `if HAS_CRYPTO`....

2021-08-23 20:19 UTC, closed without merging