Fixing the state aggregation system to properly handle requisities
saltstack/salt pull request #60604
Opened 2021-07-23 00:02 UTC by garethgreenaway

### What does this PR do?
Fixing the state aggregation system to properly handle requisities.
Fixing pkg state to exclude packages from aggregation if the hold attribute is in the state. 
Moving tests/unit/test_state.py to pytest.

### What issues does this PR fix or reference?
Fixes: #47628 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-07-23 00:02 UTC, garethgreenaway commented
I did notice one change to make with the move to pytest, need to remove one instance of RUNTIME_VARS.

2021-07-27 16:27 UTC, Ch3LL requested changes

2021-07-27 16:27 UTC, Ch3LL commented on salt/state.py
> +            log.debug("==== _aggregate_requisites - chunk %s ===", chunk)
Does this need to be removed?

2021-07-27 16:27 UTC, Ch3LL commented on salt/state.py
> +        log.debug("==== _aggregate_requisites - requisites %s ===", requisites)
here too

2021-07-27 16:27 UTC, Ch3LL commented on salt/state.py
> +                    log.debug("==== after mod_aggregate - low %s ===", low)
here as well

2021-07-27 16:27 UTC, Ch3LL commented on salt/state.py
> +
remove new line

2021-07-27 16:27 UTC, Ch3LL commented on salt/states/pkg.py
> +    log.debug("=== low %s chunks %s running %s ===", low, chunks, running)
remove here too

2021-07-27 16:27 UTC, Ch3LL commented on salt/states/pkg.py
> +    log.debug("=== in mod_aggregate - low %s ===", low)
here too

2021-07-29 17:19 UTC, Ch3LL approved these changes, later dismissed

2021-08-09 20:06 UTC, waynew requested changes
I'd like to also check the test code (I'm assuming that most of this was the UnitTest->pytest conversion, so that stuff is probably fairly solid...) but I figured I could get these questions in now.

2021-08-09 20:06 UTC, waynew commented on salt/state.py
> +                for req in STATE_REQUISITE_IN_KEYWORDS:
**question**: is it requisite (har har) that we loop over these independently, or would `for req in STATE_REQUISITE_KEYWORDS + STATE_REQUISITE_IN_KEYWORDS` (or `itertools.chain(...)`) be clearer here?

2021-08-09 20:06 UTC, waynew commented on salt/states/pkg.py
> +                # If hold exists in the chunk, do not add to aggregation
**question** this describes the what - can we describe the why?

2021-08-12 17:54 UTC, waynew approved these changes
:+1:

2021-08-12 18:38 UTC, merged