Moving remaining beacon tests to pytest
saltstack/salt pull request #60687
Opened 2021-08-06 23:05 UTC by garethgreenaway

### What does this PR do?
Moving remaining beacon tests to pytest.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-08-08 06:03 UTC, dwoz submitted a review, later dismissed

2021-08-09 17:12 UTC, Ch3LL requested changes

2021-08-09 17:12 UTC, Ch3LL commented on tests/pytests/unit/beacons/test_salt_proxy.py
> +PATCH_OPTS = dict(autospec=True, spec_set=True)
I'm not seeing `PATCH_OPTS` or `FakeProcess` being used anywhere. We also don't want to be using mutable objects at the global level.

2021-08-09 17:12 UTC, Ch3LL commented on tests/pytests/unit/beacons/test_service.py
> +PATCH_OPTS = dict(autospec=True, spec_set=True)
I'm not seeing `PATCH_OPTS` or `FakeProcess` being used anywhere. We also don't want to be using mutable objects at the global level.

2021-08-09 17:12 UTC, Ch3LL commented on tests/pytests/unit/beacons/test_smartos_imgadm.py
> +MOCK_CLEAN_STATE = {"first_run": True, "images": []}
we shouldn't be using mutable objects at the global level ( https://docs.saltproject.io/en/master/topics/development/tests/index.html#module-global-level-variables)

This includes this dictionary and the ones below.

2021-08-09 17:12 UTC, Ch3LL commented on tests/pytests/unit/beacons/test_smartos_vmadm.py
> +MOCK_CLEAN_STATE = {"first_run": True, "vms": []}
we shouldn't be using mutable objects at the global level ( https://docs.saltproject.io/en/master/topics/development/tests/index.html#module-global-level-variables)

This includes this dictionary and the ones below.

2021-08-10 17:32 UTC, Ch3LL submitted a review, later dismissed

2021-08-10 17:43 UTC, Ch3LL commented
looks like the telegram and twilio tests are being skipped (https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-m2crypto-pytest/job/PR-60687/3/testReport/tests.pytests.unit.beacons/test_telegram_bot_msg/)

https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-m2crypto-pytest/job/PR-60687/3/testReport/tests.pytests.unit.beacons/test_twilio_txt_msg/

should be able to add telegram and twilio to the requirements file.

2021-08-16 17:35 UTC, Ch3LL approved these changes

2021-08-17 11:29 UTC, merged