moving rest of the renderer unit tests over to pytest.
saltstack/salt pull request #60746
Opened 2021-08-17 00:44 UTC by garethgreenaway

### What does this PR do?
moving rest of the renderer unit tests over to pytest.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-08-17 00:45 UTC, garethgreenaway commented
@s0undt3ch wasn't sure how to best convert the function in the `test_stateconf`.py` test over to not run `RUNTIME_VARS`.

2021-08-17 06:44 UTC, s0undt3ch requested changes
In addition to the requested changes, all of the `# pylint: disable`, make sure they're really necessary.

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_aws_kms.py
> +def test__session_profile(aws_profile):  # pylint: disable=no-self-use
```suggestion
def test__session_profile(aws_profile):
```

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_aws_kms.py
> +def test__kms():  # pylint: disable=no-self-use
```suggestion
def test__kms():
```

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_aws_kms.py
> +def test__api_decrypt(encrypted_data_key):  # pylint: disable=no-self-use
```suggestion
def test__api_decrypt(encrypted_data_key):
```

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_aws_kms.py
> +            )  # pylint: disable=no-member
This pylint dissable is really necessary?

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_stateconf.py
> +
```suggestion
@attr.s
class Renderer:
    tmp_path = attr.ib()
    
    def __call__(self, content, sls="", saltenv="base", argline="-G yaml . jinja", **kws):
        state_tree_dir = self.tmp_path / "state_tree"
        cache_dir = self.tmp_path / "cachedir"
        state_tree_dir.mkdir()
        cache_dir.mkdir()
        config = salt.config.minion_config(None)
        config["root_dir"] = str(root_dir)
        config["state_events"] = False
        config["id"] = "match"
        config["file_client"] = "local"
        config["file_roots"] = dict(base=[str(state_tree_dir)])
        config["cachedir"] = str(cache_dir)
        config["test"] = False
        _renderers = salt.loader.render(config, {"config.get": lambda a, b: False})
        return _renderers["stateconf"](
            io.StringIO(content),
            saltenv=saltenv,
            sls=sls,
            argline=argline,
            renderers=salt.loader.render(config, {}),
            **kws
        )

@pytest.fixture
def renderer(tmp_path)
    return Renderer(tmp_path)
```

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_stateconf.py
> +        """
```suggestion
def test_state_config(renderer):
    result = renderer(
        """
```
See where I'm getting at?

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_stateconf.py
> +        assert result["state_id"]["cmd.run"][2][req][0]["cmd"] == "test::test"
```suggestion
@pytest.mark.parametrize("req", REQUISITES)
def test_dot_state_id_in_requisites(req):
    result = _render_sls(
            """
.test:
  cmd.run:
    - name: echo renamed
    - cwd: /

state_id:
  cmd.run:
    - name: echo not renamed
    - cwd: /
    - {}:
      - cmd: .test

""".format(
                req
            ),
            sls="test",
        )
    assert len(result) == 2
    assert "test::test" in result
    assert "state_id" in result
    assert result["state_id"]["cmd.run"][2][req][0]["cmd"] == "test::test"
```

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_stateconf.py
> +def test_relative_include_with_requisites():
parametrize REQUISITES as suggested above

2021-08-17 06:44 UTC, s0undt3ch commented on tests/pytests/unit/renderers/test_stateconf.py
> +def test_multilevel_relative_include_with_requisites():
parametrize REQUISITES as suggested above

2021-08-17 21:11 UTC, s0undt3ch approved these changes

2021-08-24 12:02 UTC, s0undt3ch approved these changes

2021-08-24 17:34 UTC, merged