moving the remaining engines unit tests over to pytest
saltstack/salt pull request #60761
Opened 2021-08-18 22:26 UTC by garethgreenaway

### What does this PR do?
moving the remaining engines unit tests over to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-08-18 22:58 UTC, twangboy approved these changes, later dismissed

2021-08-24 11:59 UTC, s0undt3ch requested changes
Mostly let's remove the patch decorators.

2021-08-24 11:59 UTC, s0undt3ch commented on tests/pytests/unit/engines/test_libvirt_events.py
> +
Can we not use the `patch` as a decorator and instead use a with statement?

2021-08-24 11:59 UTC, s0undt3ch commented on tests/pytests/unit/engines/test_libvirt_events.py
> +@patch("salt.engines.libvirt_events.libvirt", VIR_PREFIX_FOO=0, VIR_PREFIX_BAR_FOO=1)
Same as above.
Of you end up needing to patch the same thing over and over, use a fixture. You can then decorate the test function with `@pytest.mark.usefixture("the fixture name")`

2021-08-24 11:59 UTC, s0undt3ch commented on tests/pytests/unit/engines/test_sqs_events.py
> +
Instead of patcher.start/stop you can do:
```python
with patch(.....) as foo:
    yield foo
```

2021-09-14 19:18 UTC, Ch3LL requested changes
The slack tests are being skipped: https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pytest/job/PR-60761/1/testReport/tests.pytests.unit.engines/test_slack/

2021-09-27 20:47 UTC, garethgreenaway commented
@Ch3LL The Slack engine is broken with later version of the Slackclient python library, probably a good idea to leave them disabled until the engine is fixed.

2021-10-01 18:16 UTC, Ch3LL commented
I'm okay with that. Can you open an issue to track getting these tests re-enabled so we do not forget?

2021-10-01 18:16 UTC, Ch3LL approved these changes

2021-10-05 17:34 UTC, merged