Python 2.7 is gone away. Python 3.8 is now default.
saltstack/salt pull request #60768
Opened 2021-08-19 07:52 UTC by ari

### What does this PR do?
Fix bad docs.

2021-08-19 08:03 UTC, krionbsd submitted a review, later dismissed

2021-08-23 10:04 UTC, s0undt3ch requested changes

2021-08-23 10:04 UTC, s0undt3ch commented on doc/topics/installation/freebsd.rst
> +In Python 3.8 is currently default, install from packages like this:
```suggestion
Python 3.8 is currently default, install from packages like this:
```

2021-08-23 12:13 UTC, krionbsd approved these changes

2021-08-26 11:54 UTC, merged