Add language for early-access
saltstack/salt pull request #60776
Opened 2021-08-20 21:21 UTC by sagetherage

Add language for early-access to security.md file for future use

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-08-20 21:21 UTC, twangboy submitted a review, later dismissed

2021-08-20 21:28 UTC, sagetherage commented
I don't expect this to pass test BTW

2022-09-15 21:39 UTC, ScriptAutomate approved these changes, later dismissed

2022-09-16 05:34 UTC, s0undt3ch approved these changes, later dismissed

2022-09-16 20:42 UTC, twangboy requested changes

2022-09-16 20:42 UTC, twangboy commented on SECURITY.md
> +* Detailed steps to reproduce the vulnerability  (POC scripts, screenshots, and logs are all helpful to us).
Two spaces before the `(`

2022-09-16 20:42 UTC, twangboy commented on SECURITY.md
> +    coordinate the fix, release, and announcement.
Trailing space

2022-09-16 20:43 UTC, ScriptAutomate commented on SECURITY.md
> +    coordinate the fix, release, and announcement.
```suggestion
    coordinate the fix, release, and announcement.
```

2022-09-16 20:44 UTC, ScriptAutomate approved these changes, later dismissed

2022-09-16 20:46 UTC, twangboy approved these changes, later dismissed

2022-09-16 20:48 UTC, s0undt3ch submitted a review, later dismissed

2023-02-06 17:18 UTC, barbaricyawps approved these changes

2023-02-13 16:52 UTC, barbaricyawps submitted a review, later dismissed
This PR is old, but it looks really important and I'd like to get it merged in. Last week I talked to Anil to make sure this policy was still accurate. He said it was and said the only change he wanted was to note that "Emails will be addressed as soon as possible" rather than committing to a 3 day timeline. I've made that suggestion. Is it possible to commit that before merging?

2023-02-13 16:52 UTC, barbaricyawps commented on SECURITY.md
> +security-related bug reports or questions. Emails will be addressed within 3 business days.
```suggestion
security-related bug reports or questions. Emails will be addressed as soon as possible.
```

2023-04-05 17:18 UTC, ScriptAutomate commented
@barbaricyawps Looks like we'd want to mirror updates to https://github.com/saltstack/salt/blob/master/doc/security/index.rst unless we do something like change `SECURITY.md` to `SECURITY.rst` and run an `include` so that the files will always be synced (like how we include the README somewhere)

2023-04-05 18:47 UTC, barbaricyawps commented
@ScriptAutomate , probably to do that we'd want to close this PR down and just recreate, which we can take up after the 3006 release. Let's leave this as-is for now. A fresh PR will be helpful for policy conversations anyhow.

2023-06-20 19:06 UTC, barbaricyawps submitted a review, later dismissed

2024-02-09 21:06 UTC, dmurphy18 requested changes
Need to update the **security@saltstack.com** email address

2024-02-09 21:06 UTC, dmurphy18 commented on SECURITY.md
> +The Salt Project Security Team is available at security@saltstack.com for
need to update the email address

2024-02-12 18:34 UTC, dmurphy18 submitted a review, later dismissed

2025-03-28 14:52 UTC, twangboy approved these changes, later dismissed

2025-03-28 15:27 UTC, scriptautomate-bc requested changes

2025-03-28 15:27 UTC, scriptautomate-bc commented on SECURITY.md
> +[Salt Project Security RSS feed](https://saltproject.io/feed/?post_type=security)
```suggestion
[Salt Project Security RSS feed](https://saltproject.io/security-announcements/index.xml)
```

2025-03-28 15:27 UTC, scriptautomate-bc commented on SECURITY.md
> +[Salt Project Community Slack](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg).
```suggestion
[Salt Project Community Discord](https://discord.gg/J7b7EscrAs).
```

2025-03-28 15:27 UTC, scriptautomate-bc commented on SECURITY.md
> +[Salt Community mailing list](https://groups.google.com/forum/#!forum/salt-users)
```suggestion
[Salt Project GitHub Discussions](https://github.com/saltstack/salt/discussions)
```

2025-03-28 15:29 UTC, scriptautomate-bc approved these changes
Updated some links, but looks good now

2025-03-28 15:32 UTC, twangboy approved these changes

2025-03-28 16:10 UTC, dmurphy18 approved these changes

2025-05-05 23:04 UTC, merged