Merge Freeze into Master (3003.2)
saltstack/salt pull request #60797
Opened 2021-08-26 13:33 UTC by Ch3LL

2021-08-26 16:15 UTC, krionbsd submitted a review, later dismissed

2021-08-28 07:21 UTC, s0undt3ch requested changes

2021-08-28 07:21 UTC, s0undt3ch commented on tests/pytests/unit/loader/test_context.py
> -def test_named_loader_context():
I believe this test file should stay?

2021-08-30 12:37 UTC, Ch3LL commented
re-run full all

2021-09-09 08:48 UTC, s0undt3ch submitted a review, later dismissed

2021-09-14 19:57 UTC, dwoz commented on salt/modules/saltutil.py
> +                st_.client.destroy()
This is no longer needed because HighState is being used as a context manager.

2021-09-23 14:33 UTC, Ch3LL commented
Closing as these changes where included in this merge: https://github.com/saltstack/salt/pull/60924

2021-09-23 14:33 UTC, closed without merging