Explicitly document group arg for cmd.run
saltstack/salt pull request #60813
Opened 2021-08-30 16:59 UTC by ScriptAutomate

### What does this PR do?

Explicitly documents the `group` arg for `cmd.run` state, as it otherwise was only picked up by `**kwargs` as an arg that the user needed to dig for in order to see as an option.

### What issues does this PR fix or reference?

Fixes: #54378

### Previous Behavior

`group` was not an explicitly documented arg for `cmd.run` state

### New Behavior

`group` is now an explicitly documented arg for `cmd.run` state

### Merge requirements satisfied?

- [x] Docs

### Commits signed with GPG?
Yes

2021-08-30 18:21 UTC, Ch3LL requested changes
Would you be willing to add a test here. I noticed there is not test coverage for the test kwarg in any of the state cmd tests. Would you be willing to add a test for `group`. You can look at previous tests that are using the `runas` syntax as inspiration. Could you also add a changelog file.

2021-09-07 17:29 UTC, ScriptAutomate commented
> Would you be willing to add a test here. I noticed there is not test coverage for the test kwarg in any of the state cmd tests. Would you be willing to add a test for `group`. You can look at previous tests that are using the `runas` syntax as inspiration. Could you also add a changelog file.

Ah, I may try another approach then since this is meant to be a small documentation update rather than an addition to the test suite.

Since the `cmd.run` state ultimately makes use of either `cmdmod.run_all`, or `cmdmod.run_chroot`:

https://github.com/saltstack/salt/blob/8ce39ddb2594358d47e24628af85a9b260ff1fe1/salt/states/cmd.py#L857-L865

I can point to those as where the `**kwargs` are being passed on to the following, which both have `group` as an arg, and both have `group` documented (among other args that `cmd.run` would be sending to them):

https://github.com/saltstack/salt/blob/8ce39ddb2594358d47e24628af85a9b260ff1fe1/salt/modules/cmdmod.py#L2036-L2041

https://github.com/saltstack/salt/blob/8ce39ddb2594358d47e24628af85a9b260ff1fe1/salt/modules/cmdmod.py#L3245-L3251

Like so:

![image](https://user-images.githubusercontent.com/5951023/132386185-0c23f30f-34d9-4b82-8a7c-17bef45d7258.png)

Though, this may bring up a bigger conversation that can be raised in maybe another issue:

- What is the standard for salt state modules wrapped around salt exec modules, when it comes to documenting function args, and documenting the arg definitions?
- How many args default to `**kwargs`, and how many args should be documented in the state module?

In this case, I'm defaulting to saying that the user should look to the `cmdmod.run_all` or `cmdmod.run_chroot` documentation, depending on whether they are using `runas` or not.

**NOTE:** This still means there are no tests going on, as before, in regard to testing out `group` in the underlying exec modules. Though, this is just a documentation update, and I don't want it to scope creep too much (as I'd have to audit all args that `**kwargs` is passing onto, and to see what is/isn't being tested).

2021-09-07 17:47 UTC, krionbsd approved these changes

2021-09-07 17:48 UTC, waynew approved these changes
:rocket:

2021-09-08 20:31 UTC, garethgreenaway approved these changes

2021-09-08 20:31 UTC, merged