Add clarification to docs for cron.absent
saltstack/salt pull request #60823
Opened 2021-08-31 17:33 UTC by twangboy

### What does this PR do?
Clarify the handling of the `identifier` parameter in the docs.

### What issues does this PR fix or reference?
Fixes: #60649 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2021-09-14 19:11 UTC, Ch3LL requested changes

2021-09-14 19:11 UTC, Ch3LL commented on changelog/60649.fixed
> +Clarify docs for cron.absent
Doc changes do not require changelogs

2021-09-24 23:29 UTC, twangboy commented on changelog/60649.fixed
> +Clarify docs for cron.absent
Removed

2021-09-27 16:11 UTC, waynew approved these changes

2021-09-27 16:19 UTC, Ch3LL approved these changes

2021-09-27 16:21 UTC, garethgreenaway approved these changes

2021-09-27 16:23 UTC, merged