Remove all Silicon deprecations
saltstack/salt pull request #60895
Opened 2021-09-17 22:03 UTC by waynew

### What does this PR do?

Removes the bits that  were deprecated for Silicon

### What issues does this PR fix or reference?

#60893 

### Previous Behavior

Warning messages would appear about deprecated features

### New Behavior

Deprecated features are gone and you get errors instead.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2021-09-17 22:06 UTC, waynew commented
@cbosdo I *think* this is the correct way to adjust the tests for this deprecated removal - if there's a better way, please let me know!

2021-09-20 07:23 UTC, cbosdo submitted a review, later dismissed
LGTM

2021-09-20 21:04 UTC, s0undt3ch requested changes

2021-09-20 21:04 UTC, s0undt3ch commented on changelog/60893.removed
> +Removed deprecated virt.migrate_non_shared ,virt.migrate_non_shared_inc, ssh from virt.migrate, and python2/python3 args from salt.utils.thin.gen_min and .gen_thin
```suggestion
Removed deprecated virt.migrate_non_shared, virt.migrate_non_shared_inc, ssh from virt.migrate, and python2/python3 args from salt.utils.thin.gen_min and .gen_thin
```

2021-09-20 22:53 UTC, waynew commented on changelog/60893.removed
> +Removed deprecated virt.migrate_non_shared ,virt.migrate_non_shared_inc, ssh from virt.migrate, and python2/python3 args from salt.utils.thin.gen_min and .gen_thin
Nice catch! :+1:

2021-09-21 06:28 UTC, cbosdo commented
@rst0git could you have a look at this PR? you know that code better than anyone else :grin:

2021-09-21 19:40 UTC, rst0git commented on salt/modules/virt.py
>         .. deprecated:: 3002
Perhaps we could drop this `.. deprecated:: 3002` comment as well?

2021-09-22 20:37 UTC, rst0git approved these changes

2021-09-23 01:50 UTC, merged