Fix grains metadata on EC2
saltstack/salt pull request #60892
Opened 2021-09-17 10:56 UTC by tomdoherty

### What does this PR do?

Fixes issue with `grains.get meta-data` and gzipped meta-data on AWS EC2

### What issues does this PR fix or reference?
Fixes: #59541 

### Previous Behavior

salt crashes

### New Behavior

salt continues to work and adds valuable meta-data to grains

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-09-17 10:58 UTC, tomdoherty commented
Hi @gtmanfred

Could you kindly take a look at this?

Thank you

2022-01-13 20:04 UTC, Ch3LL requested changes
This will also require a changelog and test

2022-03-09 20:09 UTC, Ch3LL commented
bump @tomdoherty did you see my review comments?

2022-03-14 12:31 UTC, tomdoherty commented on salt/grains/metadata.py
> +            try:
Hi @Ch3LL 

Thanks for the review - I have modified accordingly. Do you want me to add the CHANGELOG.md change too?

2022-03-15 19:58 UTC, Ch3LL requested changes

2022-03-15 20:42 UTC, tomdoherty commented on salt/grains/metadata.py
> +    except:
Hi @Ch3LL I have fixed both

2022-03-16 20:05 UTC, Ch3LL approved these changes

2022-03-16 20:09 UTC, tomdoherty commented
Thanks for approving this @Ch3LL! When can we expect it to make it into a release?

2022-03-16 20:11 UTC, Ch3LL commented
The only 2 remaining items is:

1. Get two more approvals. Since this PR does not have test coverage 2 other core members have to approve it not having test coverage. I have requested the other reviews.
2. Tests pass
3. Then we can merge and it will be included in the 3005 release if merged in before April 11th.

2022-03-16 20:14 UTC, tomdoherty commented
Wonderful! Thanks for all the help with this

2022-03-16 20:43 UTC, twangboy approved these changes

2022-03-16 21:55 UTC, waynew commented
Question: this definitely appears to be _a_ fix, but is it the best fix?


 Is it possible to check the headers and detect that the content is gzipped and un-gzip it? Is that something we're doing elsewhere?

2022-09-21 18:02 UTC, Ch3LL commented
bump @tomdoherty did you see @waynew 's comment?

2022-10-11 20:11 UTC, Ch3LL commented
closing due to inactivity. Please let me know if this needs to be re-opened or open a new PR with a response to @waynew 's feedback.

2022-10-11 20:11 UTC, closed without merging