Fix pillar propagation error for "chroot" and "transactional_update" modules
saltstack/salt pull request #60903
Opened 2021-09-21 12:18 UTC by meaksh

### What does this PR do?

This PR fixes an issue with pillar propagation inside `transactional-update` and `chroot` modules on Salt 3003 and greater. Same code was working for 3002 codebase.

```
# salt-call transactional_update.apply foobarstate
...
2021-09-21 13:09:03,005 [salt.minion      :1980][WARNING ][1439] Passed invalid arguments to state.apply: Object of type 'NamedLoaderContext' is not JSON serializable
...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1909, in _thread_return
    function_name, function_args, executors, opts, data
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1865, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2276, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2291, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/executors/transactional_update.py", line 123, in execute
    opts, data, __salt__[DELEGATION_MAP[fun]], args, kwargs
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2276, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2291, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2276, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2291, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/transactional_update.py", line 1043, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/transactional_update.py", line 1183, in sls
    chunks, file_refs, test, hash_type, activate_transaction
  File "/usr/lib/python3.6/site-packages/salt/modules/transactional_update.py", line 1055, in _create_and_execute_salt_state
    salt.fileclient.get_file_client(__opts__), chunks, file_refs, __pillar__
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/state.py", line 203, in prep_trans_tar
    salt.utils.json.dump(pillar, fp_)
  File "/usr/lib/python3.6/site-packages/salt/utils/json.py", line 126, in dump
    return json_module.dump(obj, fp, **kwargs)  # future lint: blacklisted-function
  File "/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'NamedLoaderContext' is not JSON serializable
```

### New Behavior
After this PR, the `transactional_update` module is able to proceed and execute the corresponding state successfully.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-09-21 12:36 UTC, aplanas submitted a review, later dismissed
LGTM, I was no aware of this change. Lets wait the tests, tho.

2021-10-05 18:46 UTC, Ch3LL requested changes
this will also require a changelog

2021-10-05 18:46 UTC, Ch3LL commented on tests/unit/modules/test_chroot.py
> +        loader_context = salt.loader.context.LoaderContext()
Both of these tests do not fail without this fix. Can you add a regression test that will catch this in the future?

2021-10-21 18:39 UTC, Ch3LL approved these changes

2021-10-21 18:39 UTC, merged