Fix URL for ez_setup.py script
saltstack/salt pull request #60987
Opened 2021-10-01 15:10 UTC by dcarriger

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/59604

### Previous Behavior
```==> vagrant.base: [INFO    ] Executing command [u'/usr/local/bin/virtualenv', u'--python=/usr/bin/python3', u'/home/ubuntu/py34env'] as user 'ubuntu' in directory '/home/ubuntu'
==> vagrant.base: [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1981, in call
==> vagrant.base:     **cdata['kwargs'])
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1977, in wrapper
==> vagrant.base:     return f(*args, **kwargs)
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 209, in managed
==> vagrant.base:     **kwargs
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/modules/virtualenv_mod.py", line 297, in create
==> vagrant.base:     path, venv_python, user, saltenv=saltenv, use_vt=use_vt
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/modules/virtualenv_mod.py", line 484, in _install_script
==> vagrant.base:     fn_ = __salt__['cp.cache_file'](source, saltenv)
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 517, in cache_file
==> vagrant.base:     result = _client().cache_file(path, saltenv, source_hash=source_hash)
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 193, in cache_file
==> vagrant.base:     path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
==> vagrant.base:   File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 700, in get_url
==> vagrant.base:     raise MinionError('Error: {0} reading {1}'.format(query['error'], url))
==> vagrant.base: MinionError: Error: HTTP 404: Not Found reading https://bitbucket.org/pypa/setuptools/raw/default/ez_setup.py```

### New Behavior
Salt succeeds without an error

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-10-25 15:25 UTC, Ch3LL requested changes
can you add a changelog?

2021-11-11 17:27 UTC, Ch3LL approved these changes

2021-11-11 18:05 UTC, garethgreenaway approved these changes

2021-11-11 19:35 UTC, waynew approved these changes

2021-11-11 20:02 UTC, s0undt3ch approved these changes

2021-11-29 20:19 UTC, merged