Add percent success/failure of state runs in highstate summary output
saltstack/salt pull request #60991
Opened 2021-10-02 14:09 UTC by nicholasmhughes

### What does this PR do?
This PR adds a new master and minion configuration to modify the display of the summary information int he highstate output module. It will show successful and failed operations in a state run as a percentage of total operations.

### What issues does this PR fix or reference?
Fixes: #60990

### Previous Behavior
Summary output as shown.

```
Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    2
------------
Total states run:     4
Total run time:   4.088 ms
```

### New Behavior
When setting `state_output_pct: True`, the summary output will include two new lines showing the percent of successful and failed states in the run.

```
Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    2
Success %: 50.0
Failure %: 50.0
------------
Total states run:     4
Total run time:   4.088 ms
```

### Merge requirements satisfied?

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

2021-10-11 18:33 UTC, Ch3LL requested changes

2021-10-12 19:03 UTC, Ch3LL submitted a review, later dismissed

2021-11-09 20:12 UTC, Ch3LL approved these changes

2021-11-10 13:52 UTC, nicholasmhughes commented
re-run pr-ubuntu-2004-arm64-py3-pytest

2021-11-10 15:26 UTC, nicholasmhughes commented
re-run pr-debian-11-arm64-py3-pytest

2021-11-10 17:45 UTC, merged