job_status: Convert datetime objects into formatted strings
saltstack/salt pull request #61043
Opened 2021-10-13 15:19 UTC by bdrung

`salt-call schedule.job_status` will return empty values for the `datetime.datetime` objects. So convert the `datetime.datetime` objects into formatted strings. Then they will be shown correctly:

```
$ sudo salt-call schedule.job_status __mine_interval
local:
    ----------
    _last_run:
        2021-11-01T12:36:57
    _next_fire_time:
        2021-11-01T13:36:57
    _next_scheduled_fire_time:
        2021-11-01T13:36:57
    _run_on_start:
        False
    _seconds:
        3600
    _splay:
        None
    enabled:
        True
    function:
        mine.update
    jid_include:
        True
    maxrunning:
        2
    minutes:
        60
    name:
        __mine_interval
    return_job:
        False
    run:
        True
    run_on_start:
        True
    splay:
        None
```

2021-10-13 18:57 UTC, Ch3LL requested changes
this will require a changelog and test coverage.

2021-11-01 13:00 UTC, bdrung commented
Added changelog and enhanced `test_job_status` to cover this change.

2021-11-10 19:56 UTC, Ch3LL submitted a review, later dismissed

2021-11-11 10:00 UTC, bdrung commented
Just rebased on master

2021-12-07 21:55 UTC, Ch3LL commented
Can you rebase again, Fedora 35 was removed form the pipelines until we can take the time to fix all the tests.

2021-12-07 22:02 UTC, bdrung commented
Rebased.

2021-12-10 19:34 UTC, Ch3LL approved these changes

2021-12-10 19:34 UTC, merged