remove a faulty dot
saltstack/salt pull request #61095
Opened 2021-10-21 15:37 UTC by whitx

remove a dot that cause a bug while creating bridge interfaces see #58195

### What does this PR do?

Fix a bug

### What issues does this PR fix or reference?
Fixes: #58195 

### Merge requirements satisfied?

### Changelog
Remove unnecessary dot in template that cause the bridge interface to fail on debian. Fixes #58195 

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-10-21 18:01 UTC, Ch3LL requested changes
thanks for tracking this down. Would you be willing to add a test and changelog entry for this fix so we don't miss this next time?

2021-11-02 19:10 UTC, Ch3LL commented
I'm not seeing the changelog entry. Since the debian_ip code uses the debian_eth.jinja you should be able to add a test in `tests/unit/modules/test_debian_ip.py` to ensure this file is accurately rendered.  The `get_interface` method renders it. You can write a test that calls this method and assures the returned data is what you would expect.

2021-11-08 10:56 UTC, whitx commented
Added changelog and unit test

2021-11-08 17:54 UTC, Ch3LL commented
Thanks for adding the test, I really appreciate it. Looks like the debian_ip tests are failing, so that will just need to be cleaned up for this PR.

2021-11-10 18:57 UTC, Ch3LL commented
I'm still seeing some failures on most OSs.

2021-11-11 18:03 UTC, Ch3LL submitted a review, later dismissed

2021-11-12 10:17 UTC, whitx commented
alright we should be good had to spend some time on this test to be right :sweat_smile:

2021-11-15 15:56 UTC, bdrung commented
Can you rebase your merge request on master and squash your commits into one commit (with a nice commit message)? This bug was reported in Debian (https://bugs.debian.org/998655) and I want to pick that fix.

2021-11-16 12:56 UTC, bdrung commented
Thanks for squashing. "removeing" contains a spelling mistake, but you should use imperative in the commit title anyway ("Remove faulty[...]"). See https://chris.beams.io/posts/git-commit/ for a reasoning.

2021-11-17 15:50 UTC, bdrung commented on tests/unit/modules/test_debian_ip.py
> +
Empty lines with spaces.

2021-11-18 09:52 UTC, whitx commented on tests/unit/modules/test_debian_ip.py
> +
fixed and the commit message as well :)

2021-12-02 21:31 UTC, Ch3LL approved these changes

2021-12-14 19:30 UTC, merged