Update iam.py to prevent error during logging on undefined variable
saltstack/salt pull request #61159
Opened 2021-11-01 18:32 UTC by clickthisnick

### What does this PR do?
When log.warning happens exc is undefined. So instead of passing, retrying, and logging, this throws a stacktrace on first error.

ie 
```
a = {}

try:
    a['hi']
except Exception as exc:
    pass

print(exc)
```

Gives:
```
  File "/Users/foo/test.py", line 8, in <module>
    print(exc)
NameError: name 'exc' is not defined
```

### What issues does this PR fix or reference?
Fixes: undefined variable

### Previous Behavior
Throw a stack trace

### New Behavior
Retry and successfully log warning

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**  - TODO

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-12-15 18:19 UTC, waynew requested changes
Hey @clickthisnick thanks for the PR! Nice find!

Only two things - 
this needs a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html) and tests. 
If you need help - attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltprojectoss/schedule).

Thanks again!

2022-01-05 00:23 UTC, waynew commented
@clickthisnick no rush - just a ping, are you planning to finish this up?

2022-02-04 18:29 UTC, waynew commented
@clickthisnick just bringing this back up, no rush, but are you interested in finishing this up?

2022-02-06 16:40 UTC, clickthisnick commented
maybe in future, for now, I'm not using aws so will close

2022-02-06 16:40 UTC, closed without merging