vra2917 - update utils.vt.terminal.isalive to return false if ChildProcessError is raised
saltstack/salt pull request #61151
Opened 2021-10-29 17:39 UTC by whytewolf

### What does this PR do?

adds functionality that checks if the terminal process is already terminated and returns false if it is. 

### What issues does this PR fix or reference?
Fixes: #61160

### Merge requirements satisfied?
- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2021-11-01 18:45 UTC, Ch3LL requested changes
This will require a changelog. Would you also create an issue explaining the issue this change is resolving?

2021-11-01 18:56 UTC, whytewolf commented
> 
> 
> This will require a changelog. Would you also create an issue explaining the issue this change is resolving?

can do, #61160 bug report added.

2021-11-08 18:57 UTC, Ch3LL approved these changes, later dismissed

2021-12-02 21:28 UTC, Ch3LL approved these changes

2022-02-08 18:03 UTC, garethgreenaway approved these changes

2022-02-08 18:03 UTC, merged