Set virtual grain on FreeBSD EC2 instances
saltstack/salt pull request #61169
Opened 2021-11-02 20:13 UTC by amendlik

### What does this PR do?
Set the virtual grain on FreeBSD EC2 instances running on AWS Nitro hypervisor.

### What issues does this PR fix or reference?
Fixes: 61094

### Previous Behavior
```
salt-call grains.get virtual
local:
    physical
```

### New Behavior
```
salt-call grains.get virtual
local:
    Nitro
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-11-02 20:22 UTC, krionbsd submitted a review, later dismissed

2022-03-16 20:30 UTC, Ch3LL requested changes
this will require a changelog

2022-03-17 20:04 UTC, Ch3LL approved these changes

2022-03-17 20:07 UTC, MKLeb approved these changes

2022-03-17 20:43 UTC, garethgreenaway approved these changes

2022-03-17 20:57 UTC, s0undt3ch approved these changes

2022-03-18 07:22 UTC, krionbsd approved these changes

2022-03-18 13:28 UTC, merged