yaml modules for working towards troubleshooting easement
saltstack/salt pull request #61183
Opened 2021-11-03 21:23 UTC by whytewolf

### What does this PR do?

Adds a yaml module and yamllint utils module to work towards adding tools to better help in troubleshooting salt. 

### What issues does this PR fix or reference?
#61182 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2022-02-24 21:34 UTC, Ch3LL requested changes

2022-02-24 21:34 UTC, Ch3LL commented on salt/modules/yaml.py
> +
can you document that the usage of this module requires yamllint is installed.

and add a versionadded for 3005

2022-02-24 21:34 UTC, Ch3LL commented on salt/modules/yaml.py
> +        if saltenv is None:
since you are setting the default to be "base" in the config.get call is there any case where saltenv would be none here still?

2022-03-03 20:24 UTC, Ch3LL approved these changes

2022-03-25 18:32 UTC, whytewolf commented
rerun all

2022-04-06 18:53 UTC, merged

2022-06-26 14:05 UTC, max-arnold commented
@whytewolf Hey! Trying the new `yaml.lint` function and it breaks in an obscure way. Ubuntu 20.04, `apt install yamllint`:

```yaml
# phosphorus/foo.sls

foo:
  test.configurable_test_state:
    - changes: True
    - comment: A comment
```

```
salt-call yaml.lint salt://phosphorus/foo.sls

[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003rc1+2349.g87f6189e58', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/call.py", line 50, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/modules/yaml.py", line 56, in lint
    return __utils__["yamllint.lint"](yaml_out)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/utils/yamllint.py", line 49, in lint
    conf = YamlLintConfig(yamlconf)
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 43, in __init__
    self.validate()
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 121, in validate
    self.rules[id] = validate_rule_conf(rule, self.rules[id])
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 149, in validate_rule_conf
    raise YamlLintConfigError(
yamllint.config.YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003rc1+2349.g87f6189e58', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/call.py", line 50, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/modules/yaml.py", line 56, in lint
    return __utils__["yamllint.lint"](yaml_out)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/utils/yamllint.py", line 49, in lint
    conf = YamlLintConfig(yamlconf)
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 43, in __init__
    self.validate()
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 121, in validate
    self.rules[id] = validate_rule_conf(rule, self.rules[id])
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 149, in validate_rule_conf
    raise YamlLintConfigError(
yamllint.config.YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
```

Am I doing something wrong?

2022-06-26 15:20 UTC, whytewolf commented
@max-arnold must be a version issue. what version of yamllint did you end up with that doesn't have check-keys as one of the truthy rules? 

for the record here is the config used to get as close to salt style yaml as possible

```
        extends: relaxed
        rules:
          line-length: { max: 256, level: warning }
          empty-lines: disable
          empty-values: {forbid-in-block-mappings: false, forbid-in-flow-mappings: true}
          trailing-spaces: disable
          key-ordering: disable
          truthy: {level: warning, check-keys: false }
```

2022-06-26 16:14 UTC, max-arnold commented
The `yamllint` version is the default one on Ubuntu 20.04: `1.20.0-1`

2022-06-26 16:17 UTC, max-arnold commented
Maybe a version-dependent config should be implemented? Or if that is too much hassle, then a minimal version check at the module's `__init__()`?

2022-06-28 15:14 UTC, whytewolf commented
@max-arnold Can you create a new issue for this? I"ll try and get around to it soon.