Skip MySQL Docker tests on CentOS7
saltstack/salt pull request #61202
Opened 2021-11-08 23:40 UTC by garethgreenaway

### What does this PR do?
Skip MySQL Docker tests on CentOS7 due to frequent Docker related failures.

### What issues does this PR fix or reference?
Fixes: N/A

### Previous Behavior
MySQL integration tests that are running in Docker are frequently failing on CentOS 7.

### New Behavior
Skip the MySQL Integration tests that are running in Docker when run on CentOS 7.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-11-09 06:31 UTC, s0undt3ch requested changes

2021-11-09 06:31 UTC, s0undt3ch commented on tests/pytests/integration/modules/test_mysql.py
> +@requires_system_grains
```suggestion
```

2021-11-09 06:31 UTC, s0undt3ch commented on tests/pytests/integration/modules/test_mysql.py
> +@requires_system_grains
We already have a `grains` fixture, no need to use the decorator.

2021-11-09 20:06 UTC, Ch3LL reviewed
Why are we skipping? If I remember correctly, right now Centos 7 is the only host that runs docker tests. Are other OSs now running the docker tests as well? I'm concerned if we skip this test on Centos7 then we will not be testing MySQL at all.

2022-03-21 22:46 UTC, garethgreenaway commented
Closing this one out since we don't want to skip these long term.  This was meant to be a quick fix.

2022-03-21 22:46 UTC, closed without merging