Adding documentation for deltaproxy.
saltstack/salt pull request #61219
Opened 2021-11-10 16:45 UTC by garethgreenaway

### What does this PR do?
Adding documentation for deltaproxy.

### What issues does this PR fix or reference?
Fixes: N/A

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2021-11-10 19:38 UTC, Ch3LL requested changes
we should also add this to the freeze branch so we can create a new docs tag so these docs show up in the 3004 release.

2021-11-10 19:38 UTC, Ch3LL commented on changelog/61220.added
> +Adding documentation for deltaproxy.
changelogs are not needed for documentation changes.

2021-11-10 19:38 UTC, Ch3LL commented on doc/ref/configuration/delta_proxy.rst
> +    Alternatively, you can request consulting services for assistance.
```suggestion
    Alternatively, you can request consulting services for assistance.
```

Is this required? How would a user know how to contact consulting services?

2021-11-10 19:38 UTC, Ch3LL commented on doc/ref/configuration/delta_proxy.rst
> +-------------------------------------
looks like a couple extra `-`

2021-11-10 19:38 UTC, Ch3LL commented on doc/ref/configuration/delta_proxy.rst
> +    .. _delta-proxy-install:
I *think* this needs to be moved back a couple spaces but not certain.

2021-11-10 22:01 UTC, barbaricyawps requested changes
**Praise:** Hey, thank you for putting these docs together, Gareth. This is a huge weight off my shoulders.

I have a bunch of minor suggestions. I hope they don't feel overwhelming. Let me know what I can do to help.

2021-11-23 19:09 UTC, garethgreenaway commented on doc/ref/configuration/delta_proxy.rst
> +Salt can target network devices through `Salt proxy minions
I believe this one is resolved but is still showing.

2021-12-01 17:03 UTC, barbaricyawps approved these changes
Looks good!

2021-12-01 21:15 UTC, Ch3LL approved these changes

2021-12-01 22:07 UTC, cmcmarrow approved these changes

2021-12-01 22:10 UTC, merged