Move module tests to pytest
saltstack/salt pull request #61227
Opened 2021-11-11 16:21 UTC by krionbsd

### What does this PR do?
Move module tests to pytest

2021-11-15 12:39 UTC, s0undt3ch requested changes

2021-11-15 12:39 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_pw_user.py
> +)
```suggestion

pwd = pytest.importorskip("pwd", reason="Tests can only run on systems with the python pwd module"

log = logging.getLogger(__name__))
```

2021-11-17 07:30 UTC, krionbsd commented on tests/pytests/unit/modules/test_pw_user.py
> +)
Fixed

2021-11-17 11:16 UTC, s0undt3ch approved these changes

2021-11-17 14:54 UTC, merged