docs: Support building documentation locally
saltstack/salt pull request #61248
Opened 2021-11-17 14:29 UTC by bdrung

Building the documentation locally without Internet access will fail, because sphinx will try to download the intersphinx inventory from http://docs.python.org/3/objects.inv.

Support building the documentation locally without Internet access by searching for locally installed intersphinx inventory first.

Bug-Debian: https://bugs.debian.org/755026

2021-11-29 20:44 UTC, waynew requested changes
At least on Arch, there's a different path that should be added:

```
diff --git a/doc/conf.py b/doc/conf.py
index 4b96bae628..40154b21ee 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -40,6 +40,7 @@ intersphinx_mapping = {
             "/usr/share/doc/python{}.{}/html/objects.inv".format(
                 sys.version_info[0], sys.version_info[1]
             ),
+            "/usr/share/doc/python/html/objects.inv",
             None,
         ),
     )
```

That allowed me to build while offline

2021-11-30 09:23 UTC, bdrung commented
Okay. I included `/usr/share/doc/python/html/objects.inv` in the merge request.

2021-12-02 15:46 UTC, waynew approved these changes, later dismissed

2021-12-11 14:37 UTC, bdrung commented
Just a rebase on master (to hopefully get a green CI).

2021-12-13 16:57 UTC, waynew approved these changes

2021-12-13 19:49 UTC, merged