Use salt.utils.path.readlink to handle junctions on Windows
saltstack/salt pull request #61326
Opened 2021-12-03 22:48 UTC by twangboy

### What does this PR do?
Attempts to handle the readlink function properly by using the salt util instead of `os.readlink` directly.

### What issues does this PR fix or reference?
Fixes: #61170 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2021-12-15 22:41 UTC, waynew requested changes
This looks reasonable to me, but needs a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html) and test(s).

2022-01-14 23:36 UTC, twangboy commented
@waynew After looking more closely at the issue, this does not fix #61170 . This addresses an issue with symlinks. Issue #61170 is an issue with shortcuts, not symlinks.

2022-01-20 20:46 UTC, Ch3LL requested changes

2022-01-20 20:46 UTC, Ch3LL commented on salt/modules/file.py
> +def symlink(src, path, force=False):
`force` is a new feature. Can you add a changelog for the new force argument and a versionadded for the argument in the module doc.

2022-01-20 20:46 UTC, Ch3LL commented on salt/modules/file.py
> +        except Exception as exc:  # pylint: disable=broad-except
Why are you catching all exceptions? I would rather avoid catching everything

2022-01-20 20:46 UTC, Ch3LL commented on tests/pytests/functional/modules/file/test_replace.py
> +# nox -e pytest-zeromq-3.8(coverage=False) -- -vvv --run-slow --run-destructive tests\pytests\functional\modules\file\test_replace.py
This comment should be removed.

2022-01-20 22:02 UTC, twangboy commented on tests/pytests/functional/modules/file/test_replace.py
> +# nox -e pytest-zeromq-3.8(coverage=False) -- -vvv --run-slow --run-destructive tests\pytests\functional\modules\file\test_replace.py
Dune

2022-01-20 22:07 UTC, Ch3LL approved these changes

2022-01-21 18:04 UTC, merged