Fix ansible roster docs 60370
saltstack/salt pull request #61350
Opened 2021-12-10 18:48 UTC by waynew

### What does this PR do?

Adds the correct incantation for ansible roster, and fixes `__virtual__`.

### What issues does this PR fix or reference?

Fixes: 60370

### Previous Behavior

Copy/pasting commands from docs failed to work. If ansible was uninstalled, an error message was presented. 

### New Behavior

Copy/pasting commands works, and the correct failure is produced.

### Merge requirements satisfied?

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2021-12-11 06:01 UTC, MKLeb submitted a review, later dismissed

2021-12-11 06:01 UTC, MKLeb commented
Adding @Ch3LL for a better salt-ssh opinion

2021-12-13 19:57 UTC, Ch3LL requested changes

2021-12-13 19:57 UTC, Ch3LL commented on salt/roster/ansible.py
> +    excample, ``chmod +x /etc/salt/hosts``.
```suggestion
    example, ``chmod +x /etc/salt/hosts``.
```

2021-12-13 22:30 UTC, waynew commented on salt/roster/ansible.py
> +    excample, ``chmod +x /etc/salt/hosts``.
Nice catch :+1:

2021-12-14 18:57 UTC, Ch3LL approved these changes

2021-12-14 20:24 UTC, merged