port batch tests and fix returncode logic
saltstack/salt pull request #61519
Opened 2022-01-26 02:32 UTC by MKLeb

### What does this PR do?
Fixes retcode logic with batch execution and ports relevant tests to pytest

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/60361

### Previous Behavior
Wrong retcode (or error)

### New Behavior
Correct retcode and no error

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-01-26 20:42 UTC, MKLeb commented
re-run full all

2022-01-27 21:59 UTC, MKLeb commented
re-run full all

2022-01-31 04:02 UTC, MKLeb commented
re-run all

2022-02-02 17:22 UTC, twangboy requested changes

2022-02-02 17:22 UTC, twangboy commented on tests/pytests/integration/cli/test_batch.py
> +    Ensure that running multiple modules at the same time works in batch.
We're not running multiple modules in this test

2022-02-02 17:29 UTC, twangboy approved these changes

2022-02-10 19:20 UTC, Ch3LL approved these changes

2022-02-24 14:36 UTC, merged