Don't block startup when controlled proxy minions fail.
saltstack/salt pull request #61665
Opened 2022-02-18 00:48 UTC by garethgreenaway

### What does this PR do?
wrap the call to the proxy init functions in a try except, so we are able to continue with the rest in case one has an issue.

### What issues does this PR fix or reference?
Fixes: #61377 

### Previous Behavior
When starting up if one of the controlled proxy minions threw an exception during it's initialization, eg. a failed SSH connection, then the deltaproxy would continue trying to run the initialization fir tat proxy minion.

### New Behavior
Wrap the call to the individual proxy initialization functions in a try...except, catching the exception, logging n error and moving onto the next proxy minion.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-02-20 12:03 UTC, s0undt3ch requested changes

2022-02-20 12:03 UTC, s0undt3ch commented on tests/pytests/integration/cli/test_salt_deltaproxy.py
> +    )
```suggestion
    top_tempfile = salt_master.pillar_tree.base.temp_file(
        "top.sls", top_file
    )
    controlproxy_tempfile = salt_master.pillar_tree.base.temp_file(
        "controlproxy.sls", controlproxy_pillar_file
    )
    dummy_proxy_one_tempfile = salt_master.pillar_tree.base.temp_file(
        "dummy_proxy_one.sls",
        dummy_proxy_one_pillar_file
    )
    broken_proxy_one_tempfile = salt_master.pillar_tree.base.temp_file(
        "broken_proxy_one.sls",
        broken_proxy_one_pillar_file
    )
    broken_proxy_two_tempfile = salt_master.pillar_tree.base.temp_file(
        "broken_proxy_two.sls",
        broken_proxy_two_pillar_file
    )
```

2022-02-20 12:03 UTC, s0undt3ch commented on tests/pytests/integration/cli/test_salt_deltaproxy.py
> +        assert ret.exitcode == salt.defaults.exitcodes.EX_OK, ret
```suggestion
        with factory.started():
            # Let's issue a ping the control proxy
            ret = salt_cli.run("test.ping", minion_tgt=proxy_minion_id)
            assert ret.exitcode == 0
            assert ret.json is True

            # Let's issue a ping to one of the controlled proxies
            ret = salt_cli.run("test.ping", minion_tgt="dummy_proxy_one")
            assert ret.exitcode == 0
            assert ret.json is True

    assert not factory.is_running()
    assert ret.exitcode == salt.defaults.exitcodes.EX_OK, ret
```

2022-02-20 16:30 UTC, s0undt3ch requested changes

2022-02-20 16:30 UTC, s0undt3ch commented on tests/pytests/integration/cli/test_salt_deltaproxy.py
> +    )
```suggestion
    controlproxy_tempfile = salt_master.pillar_tree.base.temp_file(
        "controlproxy.sls", controlproxy_pillar_file
    )
```

2022-02-21 04:59 UTC, s0undt3ch approved these changes

2022-02-23 19:29 UTC, Ch3LL approved these changes

2022-02-24 14:32 UTC, merged