Raise exception when SoftLayer domain not configured
saltstack/salt pull request #61727
Opened 2022-02-25 20:29 UTC by adamckay

An exception was initialised but not actually raised when a domain was
not specified in the SoftLayer configuration

2022-03-07 21:25 UTC, Ch3LL requested changes
Can you add a changelog?

2022-03-19 17:53 UTC, adamckay commented
Hi @Ch3LL, changelog file added.

2022-03-22 19:46 UTC, Ch3LL approved these changes

2022-03-22 19:56 UTC, garethgreenaway approved these changes

2022-07-25 19:45 UTC, s0undt3ch approved these changes

2022-07-25 19:49 UTC, merged