[WIP] Ensure config module loads opts from the named_context.
saltstack/salt pull request #61732
Opened 2022-02-27 17:51 UTC by garethgreenaway

### What does this PR do?
Ensure opts is included in pack for minion_mods and config loads opts from the named_context.

### What issues does this PR fix or reference?
Fixes: #61297 

### Previous Behavior
When used with deltaproxy, the config module would use the `__opts__` from the last sub proxy minion that used the `config` module and end up with incorrect values.

### New Behavior
Load `__opts__` from the Salt loader's named_context to ensure we're using the  `__opts__` for the correct minion.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-02-28 00:16 UTC, garethgreenaway commented
run full-all

2022-02-28 00:25 UTC, garethgreenaway commented
re-run full all

2022-03-03 21:14 UTC, Ch3LL requested changes
changelog

2022-03-07 20:48 UTC, Ch3LL approved these changes, later dismissed
Approve, but want to make sure @dwoz approves too on this one.

2022-03-08 17:52 UTC, dwoz requested changes

2022-03-08 17:52 UTC, dwoz commented on tests/pytests/integration/proxy/test_deltaproxy.py
> +    assert True is True
This looks like cruft.

2022-03-08 18:04 UTC, dwoz approved these changes

2022-03-08 20:33 UTC, merged