[WIP] Add aptkey=False to use pkgrepo.managed without apt-key
saltstack/salt pull request #61760
Opened 2022-03-07 17:27 UTC by Ch3LL

### What does this PR do?
Allows users to not use apt-key. Apt-key is on a deprecation path right now so this PR adds the ability to use `aptkey: False` with the pkgrepo.managed state to not use the `apt-key` cli command. Also if `apt-key` does not exist `apt-key is not used automatically.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/59785

2022-03-07 21:51 UTC, OrangeDog commented on salt/states/pkgrepo.py
> +        the repository will use. This is required in apt-key is False.
required **if** apt-key

2022-03-07 21:51 UTC, OrangeDog commented on salt/states/pkgrepo.py
> +    signedby:
How does this interact with `name`?
Can you put it in the name instead?
Does this override the one in the name if present?

2022-04-14 13:02 UTC, Ch3LL commented
re-run all

2022-05-23 20:53 UTC, twangboy approved these changes, later dismissed

2022-05-31 20:07 UTC, MKLeb submitted a review, later dismissed

2022-06-01 13:51 UTC, waynew requested changes
just a few questions, otherwise from just looking on my phone it looks good

2022-06-01 13:51 UTC, waynew commented on salt/states/pkgrepo.py
> +    aptkey: Use the binary apt-key
*question* would be appropriate to note that this is ignored if apt-key is not found on the path?

2022-06-01 13:51 UTC, waynew commented on salt/modules/aptpkg.py
> +            self.signedby = ""
**question** why the rename? Was the previous name buggy? I'm on my phone ATM so can't easily search for uses of this within salt - just want to make sure the rename doesn't catch anything

2022-06-01 20:21 UTC, waynew approved these changes

2022-06-09 12:55 UTC, merged