Update mac build scripts to use .pyenv
saltstack/salt pull request #61779
Opened 2022-03-11 01:22 UTC by twangboy

### What does this PR do?
Fix failing MacOS builds using pyenv to build python environment.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-03-11 23:05 UTC, waynew submitted a review, later dismissed

2022-04-05 19:30 UTC, Ch3LL requested changes

2022-04-05 19:30 UTC, Ch3LL commented on pkg/osx/pkg-scripts/postinstall
> +find "$INSTALL_DIR/.pyenv/versions/3.7.12" \
There are a lot of paths in this PR that hardcode `3.7.12` . Can we use the `PY_DOT_VERSION` variable instead?

2022-04-14 19:27 UTC, Ch3LL requested changes
I'm still seeing the hard coded path to `3.7.12` in a couple of files in this PR. I think it would make sense to make that a variable so its easy to change versions.

2022-05-20 18:00 UTC, Ch3LL commented
It looks like you force pushed, but I'm still seeing 3.7.12 hard coded.

2022-05-23 13:24 UTC, Ch3LL approved these changes

2022-05-23 21:30 UTC, s0undt3ch approved these changes

2022-05-24 20:21 UTC, garethgreenaway approved these changes

2022-05-24 20:22 UTC, merged