Allow passing metadata during service registration.
saltstack/salt pull request #61793
Opened 2022-03-15 21:05 UTC by tomdoherty

e.g.

```
consul.agent_service_register:
  module.run:
    - consul_url: "http://localhost:8500"
    - token: foo
    - kwargs:
        name: prometheus-node-exporter
        id: prometheus-node-exporter
        port: 9100
        tags: ["metrics"]
        metadata:
          appid: "prometheus"
        check:
          interval: 5m
          timeout: 10s
          http: "http://localhost:9100/metrics"
          name: "Node Exporter HTTP checks"
```

Fixes #61792

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-03-16 20:03 UTC, Ch3LL requested changes
Thanks for this. Could you please add test coverage for this change?

2022-03-16 20:06 UTC, tomdoherty commented
> Thanks for this. Could you please add test coverage for this change?

My pleasure. Adding tests is currently beyond my capabilities. I have been testing this in AWS using terraform and configuring salt via cloud-init. If you link me to similar example tests I can have a try though. 

Thanks for approving these changes. When should it be released?

2022-03-16 20:06 UTC, tomdoherty commented
> Thanks for this. Could you please add test coverage for this change?

My pleasure. Adding tests is currently beyond my capabilities. I have been testing this in AWS using terraform and configuring salt via cloud-init. If you link me to similar example tests I can have a try though. 

Thanks for approving these changes. When should it be released?

2022-03-16 20:11 UTC, tomdoherty commented
> Thanks for this. Could you please add test coverage for this change?

Hi @Ch3LL adding tests for this is currently beyond my capabilities. I’ve been testing this against a real Consul instance. Do you have examples of how I could mock something similar?

2022-03-16 20:13 UTC, Ch3LL commented
You can look at tests/pytests/unit/modules/test_consul.py::test_agent_service_register as inspiration to add a test that passes in the new metadata kwarg and ensure it gets added to data.

2023-12-11 20:28 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-11 20:28 UTC, closed without merging