Update Salt to work with Jinja >= and <= 3.1.0
saltstack/salt pull request #61856
Opened 2022-03-25 15:43 UTC by Ch3LL

### What does this PR do?
Updates Markup and contextfunction to work with all versions of Jinja2. Markup was moved to markupsafe and contextfunction was changed to pass_context in Jinja 3.1

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/61848 https://github.com/saltstack/salt/issues/60745

2022-03-25 15:59 UTC, s0undt3ch requested changes

2022-03-25 15:59 UTC, s0undt3ch commented on salt/utils/jinja.py
> +
```suggestion
try:
    from markupsafe import Markup
except ImportError:
    # jinja < 3.1
    from jinja2 import Markup

```

2022-03-25 15:59 UTC, s0undt3ch commented on salt/utils/jinja.py
> +    contextfunction = jinja2.pass_context
```suggestion
try:
    contextfunction = jinja2.pass_context
except AttributeError:
    contextfunction = jinja2.contextfunction
```

2022-03-25 21:01 UTC, twangboy submitted a review, later dismissed

2022-03-25 21:08 UTC, s0undt3ch submitted a review, later dismissed

2022-03-28 06:26 UTC, krionbsd commented
re-run all

2022-03-28 14:53 UTC, waynew submitted a review, later dismissed

2022-03-29 12:19 UTC, myii commented
I've used this patch when building the `master` branch images for this week's testing across the Formulas' org -- all seems to be working well, thanks.

2022-03-29 12:22 UTC, myii commented
Perhaps this will also close #60745 -- I haven't tested that.

2022-03-29 16:59 UTC, MKLeb commented
re-run all

2022-03-30 19:47 UTC, MKLeb approved these changes

2022-03-30 22:23 UTC, garethgreenaway approved these changes

2022-03-30 22:27 UTC, waynew approved these changes

2022-03-30 22:28 UTC, merged

2022-04-04 16:20 UTC, jpic commented
Great! Is this going to be backported on older salt versions?