Enforce config types
saltstack/salt pull request #61852
Opened 2022-03-24 21:43 UTC by twangboy

### What does this PR do?
Enforces config types as specified in the VALID_OPTS dictionary.

### What issues does this PR fix or reference?
Fixes: #57873

### Previous Behavior
Config types were not enforced in all cases. This allowed for a config type that was supposed to be a list that was passed a string would end up with something like `['s', 't', 'r', 'i', 'n', 'g']`

### New Behavior
Does not allow config types where they cannot be cleanly converted to the expected type

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-04-12 15:35 UTC, MKLeb approved these changes

2022-04-12 16:24 UTC, waynew requested changes
Will check the rest of this after our meeting

2022-04-12 16:51 UTC, waynew approved these changes
:+1:

2022-04-19 23:44 UTC, garethgreenaway approved these changes

2022-04-19 23:44 UTC, merged