WIP: ipwrap() Jinja filter
saltstack/salt pull request #61933
Opened 2022-04-08 18:10 UTC by ggiesen

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #61931

### New Behavior
Adds ipwrap() jinja filter to wrap IPv6 addresses with brackets.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-04-11 09:12 UTC, OrangeDog commented
Would it make sense to implement this as an execution function rather than a filter? Then it can be used elsewhere too.

2022-05-12 19:25 UTC, MKLeb commented
@ggiesen is this still WIP?

2022-10-05 20:09 UTC, MKLeb commented
Since this PR was submitted, the `ip_bracket` util function was added, so I switched this over to using that.  @ggiesen any thoughts?  Still WIP to you?

2022-10-10 18:47 UTC, Ch3LL requested changes

2022-10-10 18:47 UTC, Ch3LL commented on doc/topics/jinja/index.rst
> +.. versionadded:: 3005.0
```suggestion
.. versionadded:: 3006.0
```

2022-10-10 18:48 UTC, Ch3LL approved these changes

2022-10-10 20:21 UTC, twangboy approved these changes

2022-10-11 19:32 UTC, MKLeb approved these changes

2022-10-11 20:24 UTC, garethgreenaway approved these changes

2022-10-12 13:03 UTC, merged