Stop copying system packages into the virtualenv
saltstack/salt pull request #61936
Opened 2022-04-09 08:22 UTC by s0undt3ch

See title

2022-04-09 08:23 UTC, s0undt3ch commented
re-run full all

2022-04-11 13:06 UTC, Ch3LL requested changes
changelog needed for the aptpkg.py changes

2022-04-11 13:33 UTC, twangboy submitted a review, later dismissed

2022-04-11 19:02 UTC, Ch3LL approved these changes

2022-04-11 19:02 UTC, merged