60316
saltstack/salt pull request #61935
Opened 2022-04-08 23:05 UTC by whytewolf

### What does this PR do?

updates `com.docker.network.bridge.name` in comparison network so there isn't a conflict. and ignores the setting in the comparison. 

### What issues does this PR fix or reference?
Fixes: #60316

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

2022-04-11 15:49 UTC, twangboy submitted a review, later dismissed

2022-04-11 19:40 UTC, Ch3LL requested changes

2022-04-11 19:40 UTC, Ch3LL commented on salt/states/docker_network.py
> +            kwargs2 = kwargs
why kwargs2?

2022-04-14 19:23 UTC, Ch3LL approved these changes

2022-04-18 13:38 UTC, merged