Fix 61010 - master pillar_cache caching _errors
saltstack/salt pull request #61989
Opened 2022-04-26 20:48 UTC by waynew

### What does this PR do?

What it says on the tin.

### What issues does this PR fix or reference?

Fixes #61010

### Previous Behavior

When rendering pillars, if any of the pillar renders produced `_errors` we
would store that in the pillar cache (see 61010). Since errors aren't actually
pillar data it doesn't make any sense to store them.

### New Behavior

Now we filter out the `_errors` from returned pillar data, and no longer cache
it.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

~- [ ] Docs~
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?

Yes

2022-04-28 19:17 UTC, Ch3LL requested changes

2022-04-28 19:17 UTC, Ch3LL commented on salt/pillar/__init__.py
> +        if "_errors" in pillars:
Don't we still want the user to see the warning?:

```
local:
    ----------
    _errors:
        - Rendering SLS 'default' failed. Please see master log for details.
  ```

I understand not wanting the error in the actual pillar cache. I tested with your PR and I do not see the error anymore when I run pillar.items:

```
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt   fix/61010-pillar-cache-_errors  salt \* pillar.items           
/home/ch3ll/.pyenv/versions/3.8.6/envs/heist-3.8/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
poc-minion:
    ----------
```

2022-05-23 23:21 UTC, waynew commented on salt/pillar/__init__.py
> +        if "_errors" in pillars:
Let me see if I can make this happen. I know that it does stick the error in the log... :thinking:

2022-05-23 23:57 UTC, waynew commented
Okay, so as it turns out we actually just depend on `_errors` being in pillar data, so it doesn't make sense for us to filter that out. That's apparently a design decision, even if I don't know the history behind it.

2022-05-23 23:57 UTC, closed without merging