Document vCenter ESXi proxy options. Cleanup headers of all VMware proxies. Fixes #61987
saltstack/salt pull request #61990
Opened 2022-04-27 01:03 UTC by ggiesen

### What does this PR do?
Documents vCenter options for ESXi proxy.  Spelling, formatting and consistency cleanups of all VMware proxy docs.

### What issues does this PR fix or reference?
Fixes: #61987

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-02-06 17:15 UTC, barbaricyawps approved these changes
@ggiesen , sorry that it's taken me awhile to look at this. I've approved this PR. Just be aware we'll need to rebase this because I've added some warnings to this module that users should use the VMware Salt extension instead.

2023-02-06 17:17 UTC, barbaricyawps requested changes
Actually, I had to revoke my approval because it looks like we're getting a missing docstring warning on this?

@ggiesen, what's your take on the missing docstring error flagged by the GitHub actions bot?

2023-12-16 19:13 UTC, dwoz commented
Pre-commit failing.

2025-03-28 15:20 UTC, twangboy requested changes

2025-03-28 15:20 UTC, twangboy commented on salt/proxy/esxi.py
> +.. _ESXCLI for vSphere 7.0: https://developer.vmware.com/docs/11789/getting-started-with-esxcli/GUID-E35D6CFC-4AAD-4D29-AE09-01E21BFA38A5.html
I'm guessing these URL's need to be updated

2025-07-03 18:12 UTC, twangboy commented
This module and its associated states and tests have been transitioned to community support and are no longer maintained by the Salt Core team. The code has been removed from the Salt code-base and can be found in this repository: https://github.com/salt-extensions/community-extensions-holding/

There is currently discussion and work being done on the salt-extensions Discord channel (https://discordapp.com/channels/1200072194781368340/1208165123240370197) to document and build the infrastructure for community-supported salt extensions. There is also a Salt-Extensions Working Group that takes place on the 1st and 3rd Thursday of every month to coordinate salt-extension efforts.

2025-07-03 18:12 UTC, closed without merging