Add dig.cname function
saltstack/salt pull request #61992
Opened 2022-04-27 14:42 UTC by nicholasmhughes

### What does this PR do?
This PR adds a function to the `dig` execution module which supports returning CNAME records for a given host.

### What issues does this PR fix or reference?
Fixes: #61991

### New Behavior
New function to support CNAME record queries via dig.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-04-28 16:56 UTC, nicholasmhughes commented
re-run pr-ubuntu-2004-amd64-py3-pycryptodome-pytest

2022-04-28 18:50 UTC, Ch3LL requested changes

2022-04-28 20:32 UTC, nicholasmhughes commented on salt/modules/dig.py
> +    return cmd["stdout"]
The RFC only allows for a one-to-one relationship for CNAMEs.

2022-04-28 22:03 UTC, nicholasmhughes commented
re-run pr-alma-8-x86_64-py3-pytest

2022-04-28 22:04 UTC, nicholasmhughes commented
re-run pr-centos-7-x86_64-py3-pytest

2022-04-28 22:04 UTC, nicholasmhughes commented
re-run pr-centos-7-x86_64-py3-pytest

2022-04-28 22:05 UTC, nicholasmhughes commented
re-run pr-centosstream-8-x86_64-py3-pytest

2022-04-29 12:51 UTC, nicholasmhughes commented
re-run pr-debian-9-amd64-py3-pytest

2022-04-29 13:08 UTC, nicholasmhughes commented
re-run pr-debian-9-amd64-py3-pytest

2022-05-05 16:56 UTC, merged