add tcp transport support for ipv6-only hosts
saltstack/salt pull request #62009
Opened 2022-04-29 19:12 UTC by sakateka

### What does this PR do?
At the moment, the 'tcp' transport only works in ipv4-only mode. This pull request adds ipv6 support.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
ipv6-only masters and minions crash

### New Behavior
ipv6-only masters and minions are working properly

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-05-11 20:52 UTC, MKLeb approved these changes, later dismissed

2022-05-18 05:55 UTC, sakateka commented
@MKLeb Hi, could you merge this, I can't do it myself.

2022-06-16 16:32 UTC, sakateka commented
@MKLeb please merge it.

2022-06-16 16:58 UTC, MKLeb commented
Going to pull in the master changes to ensure this runs on the new OS's that have been added

2022-06-17 23:35 UTC, sakateka commented
re-run pr-ubuntu-2004-arm64-py3-pytest
re-run pr-freebsd-131-amd64-py3-pytest

2022-06-18 07:27 UTC, sakateka commented
@garethgreenaway all the required tests have been passed, please merge this PR.

2022-06-18 15:02 UTC, garethgreenaway commented
re-run full all

2022-06-19 09:43 UTC, sakateka commented
re-run pr-centosstream-8-x86_64-py3-pytest
re-run pr-centos-7-x86_64-py3-pytest

2022-06-19 12:20 UTC, sakateka commented
re-run pr-centos-7-x86_64-py3-pytest

2022-06-21 06:44 UTC, sakateka commented
@garethgreenaway All tests have been successfully completed, merge please.

2022-06-21 16:22 UTC, dmurphy18 approved these changes, later dismissed

2022-07-03 16:02 UTC, sakateka commented
re-run pr-ubuntu-2004-amd64-py3-pytest
re-run pr-freebsd-131-amd64-py3-pytest
re-run pr-alma-8-x86_64-py3-pytest

2022-07-04 02:48 UTC, sakateka commented
re-run pr-freebsd-131-amd64-py3-pytest

2022-07-07 00:24 UTC, sakateka commented
@Ch3LL merge this pr please.

2022-07-07 03:00 UTC, sakateka commented
re-run pr-ubuntu-2004-amd64-py3-pytest
re-run pr-freebsd-131-amd64-py3-pytest

2022-07-07 03:00 UTC, sakateka commented
re-run pr-ubuntu-2004-arm64-py3-pytest

2022-07-07 20:30 UTC, Ch3LL requested changes

2022-07-16 10:26 UTC, sakateka commented
re-run pr-alma-8-x86_64-py3-pytest
re-run pr-centos-7-x86_64-py3-pycryptodome-pytest

2022-07-19 07:36 UTC, sakateka commented
@Ch3LL PTAL

2022-07-19 19:14 UTC, Ch3LL approved these changes

2022-07-19 19:14 UTC, merged