Add support for `name`, `pkgs` and `diff_attr` parameters to `zypperpkg.upgrade()`/`yumpkg.upgrade()`
saltstack/salt pull request #62033
Opened 2022-05-06 11:24 UTC by agraul

### What does this PR do?
Add `diff_attr` to `yumpkg.upgrade()` and add it, together with `name` and `pkgs`, to `zypperpkg.upgrade()`.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62030
Fixes: https://github.com/saltstack/salt/issues/62031
Fixes: https://github.com/saltstack/salt/issues/62032

### Previous Behavior
`name` and `pkgs` parameters are ignored in `zypperpkg.upgrade()`. The `diff_attr` parameter is ignored by both `yumpkg.upgrade()` and `zypperpkg.upgrade()`

### New Behavior
`name` and `pkgs` parameters are used in `zypperpkg.upgrade` to only update/upgrade the specified package(s). `diff_attr` is used by `zypperpkg.upgrade()` and `yumpkg.upgrade()` to output additional attributes.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-05-06 11:33 UTC, SchoolGuy submitted a review, later dismissed
I have debugged this together with @agraul. The PR is LGTM for me.

2022-09-20 19:52 UTC, Ch3LL commented
looks like there is a test failure that might be related to this change

2022-09-30 10:26 UTC, agraul commented
> looks like there is a test failure that might be related to this change

After rebasing the PR on top of the current master commit, I don't see the test failure locally anymore. Let's see if jenkins' test executions agree.

2022-09-30 18:31 UTC, Ch3LL requested changes

2022-09-30 18:31 UTC, Ch3LL commented on salt/modules/yumpkg.py
> +    diff_attr=None,
can you add documentation below for this new argument

2022-10-06 18:27 UTC, Ch3LL approved these changes

2022-10-06 18:27 UTC, merged