Hotfix/ubuntu 2204 test fixes
saltstack/salt pull request #62073
Opened 2022-05-16 21:14 UTC by MKLeb

### What does this PR do?
Preps the test suite for ubuntu 22.04

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-05-16 23:08 UTC, MKLeb commented
re-run full all

2022-05-17 16:38 UTC, s0undt3ch requested changes

2022-05-17 16:38 UTC, s0undt3ch commented on tests/unit/modules/test_pdbedit.py
> +        print(osname, osrelease, oscodename)
```suggestion
```
Let's remove this print statement.

2022-05-19 16:50 UTC, MKLeb commented
re-run all

2022-05-19 21:26 UTC, waynew approved these changes

2022-05-20 05:09 UTC, krionbsd approved these changes

2022-05-20 13:42 UTC, garethgreenaway approved these changes

2022-05-20 13:43 UTC, merged