Fixed humanname for zypperpkg
saltstack/salt pull request #62086
Opened 2022-05-19 19:03 UTC by 515k4

### What does this PR do?
The pkgrepo renames humanname argument to name for RedHat ana Suse os_family but zypperpkg does expect only humanname. Moreover the argument is missing in documentation and it used --name='{0}' which leaves trailing single quote marks as part of the name.

### What issues does this PR fix or reference?
Fixes: #62053

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-10-12 16:30 UTC, twangboy requested changes
This will also need a changelog and some tests written.

2022-10-12 16:30 UTC, twangboy commented on salt/modules/zypperpkg.py
> -        cmd_opt.append("--name='{}'".format(kwargs.get("humanname")))
You can't just remove an option without deprecation. Please add a deprecation warning under humanname:
```suggestion
    if "humanname" in kwargs:
        salt.utils.versions.warn_until(
            3009,
            "Passing 'humanname' to 'mod_repo' is deprecated, slated "
            "for removal in {version}. Please use 'name' instead."
        )
        cmd_opt.append("--name='{}'".format(kwargs.get("humanname")))
```

2022-10-16 11:47 UTC, 515k4 commented
> This will also need a changelog and some tests written.

I added both changelog and simple test.

2022-10-20 14:30 UTC, twangboy approved these changes

2022-10-20 15:13 UTC, garethgreenaway approved these changes

2022-10-20 15:13 UTC, merged