Fix #62092: Catch zmq.error.ZMQError to set HWM for zmq >= 3
saltstack/salt pull request #62119
Opened 2022-05-30 10:36 UTC by mirceaulinic

It looks like before release 23.0.0, when trying to access zmq.HWM it
was raising ``AttributeError``, which is now wrapped under pyzmq's own
``zmq.error.ZMQError``.
Simply caching that, should then set the HWM correctly for zmq >= 3
and therefore fix #62092.

2022-05-30 13:24 UTC, nicholasmhughes commented
re-run pr-windows-2019-x64-py3-pytest

2022-05-30 13:32 UTC, nicholasmhughes submitted a review, later dismissed
After some cursory testing, this fixes the issues I was seeing running the master branch code on Debian 10.

2022-05-31 13:38 UTC, Ch3LL requested changes
Can you add a changelog

2022-05-31 19:40 UTC, mirceaulinic commented
@Ch3LL added in fa5c3d8b04.

2022-05-31 19:45 UTC, Ch3LL approved these changes

2022-06-01 00:45 UTC, nicholasmhughes commented
re-run pr-ubuntu-2004-arm64-py3-pytest

2022-06-01 00:45 UTC, nicholasmhughes commented
re-run pr-centos-7-x86_64-py3-pycryptodome-pytest

2022-06-01 00:45 UTC, nicholasmhughes commented
re-run pr-centos-7-x86_64-py3-pytest

2022-06-01 02:29 UTC, waynew approved these changes

2022-06-01 13:55 UTC, s0undt3ch approved these changes

2022-06-01 14:31 UTC, merged