``clear_funcs`` is not always a valid clear funcs object.
saltstack/salt pull request #62116
Opened 2022-05-27 10:04 UTC by s0undt3ch

```
Process MWorker-1:
Traceback (most recent call last):
  File "/home/vampas/.pyenv/versions/3.7.12/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/utils/process.py", line 1034, in wrapped_run_func
    return run_func()
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/master.py", line 1136, in run
    self.key,
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/master.py", line 1981, in __init__
    self.masterapi = salt.daemons.masterapi.LocalFuncs(opts, key)
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/daemons/masterapi.py", line 1079, in __init__
    self.local = salt.client.get_local_client(mopts=self.opts)
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/client/__init__.py", line 129, in get_local_client
    listen=listen,
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/client/__init__.py", line 233, in __init__
    self.functions = salt.loader.minion_mods(self.opts, utils=self.utils)
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/loader/__init__.py", line 308, in minion_mods
    pack_self="__salt__",
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/loader/lazy.py", line 314, in __init__
    super().__init__()  # late init the lazy loader
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/utils/lazy.py", line 37, in __init__
    self.clear()
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/loader/lazy.py", line 561, in clear
    self._refresh_file_mapping()
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/loader/lazy.py", line 459, in _refresh_file_mapping
    dirname, basename = os.path.split(filename)
  File "/home/vampas/.pyenv/versions/3.7.12/lib/python3.7/posixpath.py", line 111, in split
    if head and head != sep*len(head):
  File "/home/vampas/projects/SaltStack/pytest/salt-factories/branches/master/.nox/tests-3/lib/python3.7/site-packages/salt/master.py", line 980, in _handle_signals
    self.clear_funcs.destroy()
AttributeError: 'MWorker' object has no attribute 'clear_funcs'
```

Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-05-27 18:32 UTC, Ch3LL requested changes
test coverage?

2022-05-27 18:34 UTC, s0undt3ch commented
@Ch3LL previously we would get tracebacks, not every single time, this just clears them, and makes sure any remaining code runs...
How do you suggest we add test coverage to this?

2022-05-27 18:39 UTC, Ch3LL commented
Is there a way to force MWorker to not contain the clear_func attribute and ensure when that method is called we don't see a traceback?

2022-05-31 19:50 UTC, Ch3LL approved these changes

2022-05-31 19:51 UTC, Ch3LL commented
I went ahead and approved. Lets get 2 more approvals to see if others are okay without test coverage.

2022-05-31 19:56 UTC, MKLeb approved these changes

2022-05-31 21:01 UTC, twangboy approved these changes

2022-06-01 13:21 UTC, merged