Add version report automated test
saltstack/salt pull request #62133
Opened 2022-06-02 00:31 UTC by MKLeb

### What does this PR do?
Adds a test to ensure the `--versions-report` flag and its equivalents output in the correct format and with the correct versions

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/61107

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-06-13 19:45 UTC, Ch3LL approved these changes, later dismissed

2022-06-14 09:55 UTC, s0undt3ch requested changes
This doesn't need to be an integration test, you don't need the daemons running.
Should be a functional if you need to parse the output for formatting, or maybe even a unit if you only need to match what's reported.

2022-06-14 19:29 UTC, Ch3LL approved these changes

2022-06-14 19:49 UTC, s0undt3ch approved these changes

2022-06-14 21:04 UTC, garethgreenaway approved these changes

2022-06-14 21:04 UTC, merged