Add exception for Arch in timezone zone_compare
saltstack/salt pull request #62136
Opened 2022-06-06 06:41 UTC by ipaqmaster

Resubmission of #61390

Like FreeBSD an Archlinux host may not have a /etc/localtime symlink yet which can cause a comparison error during provisioning. It would be nice to not have to work around this problem any more with this small addition.

_If tests are required I could use a hand writing a suitable one._

### What does this PR do?

Prevents `zone_compare` in `salt/modules/timezone.py` throwing an error when /etc/localtime is missing on Archlinux hosts.

### What issues does this PR fix or reference?
Fixes: #61296

### Previous Behavior

```
[ERROR   ] Unable to compare desired timezone 'Australia/Melbourne' to system timezone: Failed to read /etc/localtime to determine current timezone: No such file or directory
local:
----------
          ID: Australia/Melbourne
    Function: timezone.system
      Result: False
     Comment: Unable to compare desired timezone 'Australia/Melbourne' to system timezone: Failed to read /etc/localtime to determine current timezone: No such file or directory
     Started: 06:37:43.845836
    Duration: 0.653 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.653 ms
```

### New Behavior

```
local:
----------
          ID: Australia/Melbourne
    Function: timezone.system
      Result: True
     Comment: Set timezone Australia/Melbourne
     Started: 06:38:29.172314
    Duration: 78.068 ms
     Changes:   
              ----------
              timezone:
                  Australia/Melbourne

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  78.068 ms
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-06-07 23:59 UTC, ipaqmaster commented
Been trying to get this officially fixed for a while, any help or guidance on how to make this happen would be greatly appreciated.

2022-06-09 08:34 UTC, raymonad commented
`"Arch"` by itself is Truthy, so this is not an exception for Arch but a check for all (supported) OSes. I don't understand why a missing file should be treated differently on some OSes in the first place and I see this also came up in the referenced issue.

The special cases for AIX/Solaris are documented, but this one (whether for FreeBSD/Arch only or as a general check) is not. It could also be argued that, if you don't want to throw an exception, you should simply return False if /etc/localtime doesn't exist, because it can't possibly compare equal to any zone file. Then Salt (states.timezone) would always create /etc/localtime; now it won't if the desired timezone is equal to the system default (probably UTC).

2022-06-13 08:07 UTC, ipaqmaster commented
You're right that the statement was Truthy. I've fixed this in a new push but I have not been able to write tests.

Is there any 'gotcha' on why this section cannot just be:
```
    if not os.path.isfile(_get_localtime_path()):
        return timezone == get_zone()
```

Without an OS check?

2022-09-20 19:50 UTC, Ch3LL requested changes
this will require a changelog and it should be pretty easy to add some test coverage.

There are already tests in tests/unit/modules/test_timezone.py, if you could just add a test that mocks grains to be arch or freebsd so we ensure we are testing this code path as well. thanks

2022-09-21 00:48 UTC, ipaqmaster commented
Thank you Ch3LL, I'm in a bit of a pickle at the moment with time management but I'll try and get this done

2022-09-21 18:07 UTC, Ch3LL commented
k, i'm more than willing to help write the tests, so let me know if you can't find the time.

2022-10-10 04:27 UTC, ipaqmaster commented
Sorry I won't be able to take care of this one at the current time. Despite how badly I'm itching to get this problem fixed.

2022-10-10 15:47 UTC, waynew requested changes
Yeah, this definitely does need changes, I also had a suggestion and a question.

Tests should be pretty easy to write - if you need some help feel free to come by one of the [Test Clinics on Twitch](https://www.twitch.tv/saltprojectoss/schedule).

2022-10-10 15:47 UTC, waynew commented on salt/modules/timezone.py
> +    if __grains__["os_family"] in {"Arch", "FreeBSD"}:
**suggestion**: FWIW a tuple `(...)` is typically preferred over a set `{...}` for this kind of comparison:

```suggestion
    if __grains__["os_family"] in ("Arch", "FreeBSD"):
```

though looking at the code around it, would it be more appropriate to do

```
if "Arch" in __grains__["os_family"] or "FreeBSD" in __grains__["os_family"]:
```
? It seems like at least the other checks are thinking that `os_family` could be a list-type, or that they might contain more than just say "FreeBSD" but might have something like "Cool FreeBSD" or something to that effect.

2022-10-17 18:06 UTC, waynew commented
@ipaqmaster are you interested in adding the tests and getting this merged in?

2022-10-17 19:46 UTC, Ch3LL commented
He previously stated he doesn't have the time. I'm willing to add some tests coverage here unless you want to tackle this in your test clinic @waynew .

Just let me know

2022-10-20 23:57 UTC, waynew commented
@Ch3LL I probably won't be able to tackle this before mid Nov/Dec, so if you get to it before that, feel free to take it on!

2022-11-01 19:56 UTC, Ch3LL commented
I went ahead and pushed some test coverage, and made the requested changes.

@waynew and @ipaqmaster can you give it a look and see if everything looks good.

2022-11-21 14:54 UTC, garethgreenaway approved these changes

2022-11-21 14:54 UTC, merged