Add typing_extensions to salt-ssh thin tarball
saltstack/salt pull request #62234
Opened 2022-06-28 20:56 UTC by lastmikoi

### What does this PR do?

When one uses `salt-ssh` 3003+ on python3.6-running targets (who are numerous, see RHEL, CentOS, RockyLinux, etc..., as OS vendors are supporting python3.6 and fixing security issues themselves even if upstream py36 is End Of Life), salt-ssh will include a backport of python3.7's `contextvars` module in the salt thin tarball.

However, the `contextvars` backport makes uses of the `immutables` module.

This module went through a typing refactor (see https://github.com/MagicStack/immutables/pull/62) which landed in its v0.16 release on August 2021.

However, that typing refactor added a new dependency, `typing_extensions`, but only on pre-3.8 deployments (see https://github.com/MagicStack/immutables/blob/master/immutables/_protocols.py#L13).

This third-order dependency (!) is nowhere to be found on the salt ssh thin tarball, which leads to several issues (#59942) as that import error triggers a cascade of exceptions.

This PR aims to fix that issue by adding `typing_extensions` to the thin tarball.

*Note: First-time Salt contributor here, don't hesistate to walk me through stuff if you think I missed something in my reading of the Contributor's Guide !*

### What issues does this PR fix or reference?
Fixes: #59942

### New Behavior
salt-ssh will add `typing_extensions` to the thin tarball in the cases where `immutables` is imported (i.e. target is running python 3.6)

### Merge requirements satisfied?
- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-07-07 19:46 UTC, Ch3LL requested changes

2022-07-07 19:46 UTC, Ch3LL commented on salt/utils/thin.py
> +        mods.append(typing_extensions)
I did some testing and I can only replicate the issue when my master and the target are python 3.6. If master is 3.8 and target is 3.6 it works. Can we add some logic here that only adds the typing_extensions if the master is running < python 3.8.

2022-08-31 19:35 UTC, Ch3LL commented
@lastmikoi are you able to loop back to this PR with the feedback I previously submitted?

2022-09-29 19:10 UTC, Ch3LL commented
bump @lastmikoi did you see my feedback?

2022-10-11 08:46 UTC, lastmikoi commented
Hi @Ch3LL !

I have seen your feedback, I've been trying to find time to work on it as I remembered I could reproduce the issue on my 3.6 salt-master, but I haven't found the time to take care of it just yet. I'll get you updated !

2022-10-15 11:17 UTC, lastmikoi commented
@Ch3LL I have been able to reproduce the issue on a clean(-ish) Python3.9 master virtualenv with Salt 3005 against a freshly installed CentOS7 target.

<details><summary>`salt-ssh test.ping` Traceback</summary>

```
        Traceback (most recent call last):
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/context.py", line 10, in <module>
            import _contextvars as contextvars
        ModuleNotFoundError: No module named '_contextvars'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/var/tmp/.lastmikoi_dd8a91_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/scripts.py", line 435, in salt_call
            import salt.cli.call
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/cli/caller.py", line 12, in <module>
            import salt.channel.client
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/channel/client.py", line 13, in <module>
            import salt.crypt
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/crypt.py", line 26, in <module>
            import salt.payload
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/payload.py", line 12, in <module>
            import salt.loader.context
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/__init__.py", line 15, in <module>
            import salt.config
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * 0.5
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/config/__init__.py", line 88, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/grains/core.py", line 31, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/modules/cmdmod.py", line 31, in <module>
            import salt.utils.templates
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/utils/templates.py", line 27, in <module>
            from salt.loader.context import NamedLoaderContext
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/context.py", line 13, in <module>
            import contextvars
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/contextvars/__init__.py", line 4, in <module>
            import immutables
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/immutables/__init__.py", line 18, in <module>
            from ._protocols import MapKeys as MapKeys
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/immutables/_protocols.py", line 17, in <module>
            from typing_extensions import Protocol
        ModuleNotFoundError: No module named 'typing_extensions'
        [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
        ModuleNotFoundError: No module named 'typing_extensions'
        Traceback (most recent call last):
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/context.py", line 10, in <module>
            import _contextvars as contextvars
        ModuleNotFoundError: No module named '_contextvars'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/var/tmp/.lastmikoi_dd8a91_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/scripts.py", line 435, in salt_call
            import salt.cli.call
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/cli/caller.py", line 12, in <module>
            import salt.channel.client
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/channel/client.py", line 13, in <module>
            import salt.crypt
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/crypt.py", line 26, in <module>
            import salt.payload
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/payload.py", line 12, in <module>
            import salt.loader.context
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/__init__.py", line 15, in <module>
            import salt.config
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * 0.5
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/config/__init__.py", line 88, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/grains/core.py", line 31, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/modules/cmdmod.py", line 31, in <module>
            import salt.utils.templates
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/utils/templates.py", line 27, in <module>
            from salt.loader.context import NamedLoaderContext
          File "/var/tmp/.lastmikoi_dd8a91_salt/pyall/salt/loader/context.py", line 13, in <module>
            import contextvars
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/contextvars/__init__.py", line 4, in <module>
            import immutables
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/immutables/__init__.py", line 18, in <module>
            from ._protocols import MapKeys as MapKeys
          File "/var/tmp/.lastmikoi_dd8a91_salt/py3/immutables/_protocols.py", line 17, in <module>
            from typing_extensions import Protocol
        ModuleNotFoundError: No module named 'typing_extensions'


```
</details>

<details><summary>`salt-ssh --versions-report`</summary>

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.9.12 (main, May 15 2022, 19:24:24)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: arch  
        locale: utf-8
       machine: x86_64
       release: 5.18.15-arch1-1
        system: Linux
       version: Arch Linux
```
</details>

By applying my patch, *installing typing_extensions<4.2.0*, and rebuilding the thin with `-t`, the issue dissapears. Rolling back my patch (but keeping typing_extensions installed on the target) make the issue appear once again.

This seems harder to reproduce outside of my environment than I anticipated, so I'm available for further testing until we figure out this thing.

2022-10-18 19:23 UTC, Ch3LL commented
And what python version is your target? python 3.6?

in 3006 we will only be supporting python >=3.7. Does this also show up when the target version python is 3.7. I'm assuming it does, but if you are willing to confirm I would appreciate it.

2022-10-20 20:30 UTC, lastmikoi commented
Spent an hour or so getting a py37 working on my CentOS7 environment to make sure I could test it.

The issue does **not** impact py37 targets, as the `contextvars` module is present in stdlib, which skips the backport entirely, its broken third-order dependency included.

I understand the need to move past py36 for future releases of SaltStack, but I will have to manage py36 hosts for at least a year and a half (EL 7 EOL), so I would still consider applying my patch if only for 3005, which I would pin my EL7 minions to.

2022-11-03 19:00 UTC, Ch3LL commented
I wonder if this would work for your use case: https://docs.saltproject.io/en/latest/topics/ssh/ssh_ext_alternatives.html#ssh-ext-alternatives

Also, another thought is to make this configurable instead of adding typing_extensions. So in the future a user could easily add a library to the tarball.

2023-12-10 22:39 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-10 22:39 UTC, closed without merging