moving tests/integration/modules/test_cmdmod.py to pytest.
saltstack/salt pull request #62322
Opened 2022-07-12 16:36 UTC by garethgreenaway

### What does this PR do?
moving tests/integration/modules/test_cmdmod.py to pytest.

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-12-11 00:11 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-11 00:12 UTC, dwoz commented
Re-opening. I'll move this across the finish line for 3008.

2023-12-20 20:47 UTC, twangboy approved these changes

2023-12-26 07:22 UTC, s0undt3ch requested changes
@dwoz added some review comments.

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +    yield runas_usr
```suggestion
@pytest.fixture
def runas_usr():
    yield runas_usr
        with pytest.helpers.create_account() as account:
            yield account.username
    else:
        yield "nobody"
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +    yield salt.utils.path.which_bin(["python", "python2", "python2.6", "python2.7"])
```suggestion
    yield salt.utils.path.which_bin(["python", "python3"])
```
Let's stop searching for python 2

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +pytestmark = [pytest.mark.windows_whitelisted]
```suggestion
pytestmark = [
    pytest.mark.windows_whitelisted,
]
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +            usermod.delete(name, remove=True)
```suggestion
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +        cwd_runas = cmdmod.run_stdout(cmd, cwd=tmp_cwd, runas=runas_usr).rstrip("\n")
```suggestion
    cwd_runas = cmdmod.run_stdout(cmd, cwd=tmp_cwd, runas=runas_usr).rstrip("\n")
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +        user_path = cmdmod.run_stdout('printf %s "$PATH"', runas=runas_usr)
```suggestion
    user_path = cmdmod.run_stdout('printf %s "$PATH"', runas=runas_usr)
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +        )
```suggestion
    cmd_result = cmdmod.run_all(
        'pwd; pwd; : $(echo "You have failed the test" >&2)',
        cwd=tmp_cwd,
        runas=runas_usr,
    )
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +        out = cmdmod.run("env", runas=runas_usr).splitlines()
```suggestion
    out = cmdmod.run("env", runas=runas_usr).splitlines()
```

2023-12-26 07:22 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_cmdmod.py
> +@pytest.mark.skip_unless_on_windows(reason="Minion is not Windows")
```suggestion
@pytest.mark.skip_unless_on_windows
```
No need to customize message, does not add anything.

2024-01-02 18:40 UTC, dmurphy18 commented
@dwoz Have https://github.com/saltstack/salt/pull/65679 actively moving this forward

2024-01-03 22:08 UTC, dwoz commented
This will be closed when #65679 passes.

2024-01-03 22:42 UTC, twangboy approved these changes

2024-01-08 21:32 UTC, dmurphy18 commented
Closing since associated fixing PR https://github.com/saltstack/salt/pull/65679 is merged

2024-01-08 21:32 UTC, closed without merging