Update release candidate documentation
saltstack/salt pull request #62352
Opened 2022-07-20 20:35 UTC by barbaricyawps

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-07-20 21:04 UTC, dmurphy18 submitted a review, later dismissed

2022-07-20 21:12 UTC, twangboy requested changes

2022-07-20 21:12 UTC, twangboy commented on doc/topics/releases/releasecandidate.rst
> +The builds should include the latest version of the operating system that is currently available.
Not sure what this means... latest version of what operating system. Maybe you mean kind of what the note below says...  "New operating systems will only get Tiamat packages"?

2022-07-20 21:46 UTC, twangboy approved these changes

2022-07-21 12:52 UTC, Ch3LL approved these changes

2022-07-21 12:52 UTC, merged