modules.mac_brew_pkg: don't use sudo -i
saltstack/salt pull request #62395
Opened 2022-07-28 19:17 UTC by rvandegrift

sudo -i is used for starting interactive sessions.  It causes sudo to
tell the shell to run a login session, which triggers reading e.g.
~/.bash_profile.

Since that's intended for interactive use cases, it may produce output.
But any output on stdout will be read as brew's json output - breaking
states.pkg.

Fixes: https://github.com/saltstack/salt/issues/62394

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-08-31 19:55 UTC, Ch3LL requested changes
this will require a changelog

2022-08-31 20:02 UTC, dmurphy18 approved these changes

2022-09-01 07:03 UTC, SMillerDev requested changes
I expect this to break for any host on Apple Silicon since brew is not in PATH by default there. The only way I see around that is `--preserve-env=PATH` and telling users to add `brew` to PATH for root.

2022-09-01 19:37 UTC, twangboy approved these changes

2022-09-13 22:42 UTC, MKLeb approved these changes

2022-09-13 22:43 UTC, MKLeb commented
@rvandegrift Are you able to add a changelog file and a test for this?

2022-09-14 02:49 UTC, rvandegrift commented
> I expect this to break for any host on Apple Silicon since brew is not in PATH by default there. The only way I see around that is `--preserve-env=PATH` and telling users to add `brew` to PATH for root.

From [1], it sounds like they plan to move `brew` to `/opt/homebrew` on all platforms eventually.  Seems like salt should hardcode that path (or at least check it first - though admittedly, it's annoying to have to re-implement `PATH`).

[1] - https://github.com/Homebrew/brew/issues/7857

2022-09-14 02:53 UTC, rvandegrift commented
> @rvandegrift Are you able to add a changelog file and a test for this?

Sorry I'm not too keen on doing release management work, especially with the specific requests about changelog format.

2022-09-14 05:25 UTC, SMillerDev commented
As a homebrew maintainer I can assure you, there are no plans to move the install location on x86 macs. Eventually all macs will be ARM and therefore /opt/Homebrew by default though. But that doesn't account for systems where homebrew is installed in a custom location (like in a lot of big companies).

Essentially this change is a big regression in favor of a niche bugfix from my point of view.

2022-09-14 19:06 UTC, MKLeb commented
@rvandegrift, given @SMillerDev 's comments, I do think we should allow this as an option to the mac pkg commands.  Something like `interactive=True` by default.

2022-09-24 00:01 UTC, rvandegrift commented
@MKLeb I'm not sure I agree - if @SMillerDev is right, that option will just break the module for users that happen to have the Mac silicon behavior of brew.  Who knew printing messages in an interactive shell was a niche feature! :)

2022-09-26 17:37 UTC, Ch3LL commented
So how do you want to progress this PR? Keep investigating a fix or close?

2022-09-27 20:56 UTC, rvandegrift commented
I looked at `states/pkg.py` to see about plumbing an option through to the exec module, and it wasn't quite obvious enough for me to take a swing.

2022-09-27 20:56 UTC, closed without merging