Change Tiamat to onedir in release notes
saltstack/salt pull request #62397
Opened 2022-07-28 20:57 UTC by barbaricyawps

### What does this PR do?

This MR changes all references to the Tiamat packaging system to "onedir" instead.
If you're a community member, first off: hi! 👋 

You might be wondering why this change was made. The simple explanation is that we're changing references to Tiamat to "onedir" because it's a more accurate. The goal of providing a onedir package are to make the installation process easier by making it so that all of Salt's dependencies are included in one directory. We want our documentation to use a name that describes the goal of the installation process, not the underlying tool it is using.

The change in question was to rename the wording around the new onedir packages that are being built for 3005 using the Tiamat tool.  The core team discussed this topic at length and decided that it was more accurate and descriptive to refer to these packages as onedir rather than refering them to tiamat.  This gives us a clear distinction between the new onedir packages and the classic packages by focusing on the concept these are built in rather than the tool used to build them.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

2022-07-28 21:18 UTC, garethgreenaway approved these changes, later dismissed

2022-08-01 19:11 UTC, Ch3LL requested changes

2022-08-01 19:11 UTC, Ch3LL commented on doc/topics/releases/3005.rst
> -Known issues
Why are you removing this known issues?

2022-08-01 19:50 UTC, barbaricyawps commented on doc/topics/releases/3005.rst
> -Known issues
Looks like a mistake. I'll fix that.

2022-08-02 13:41 UTC, Ch3LL approved these changes

2022-08-02 13:41 UTC, merged