[WIP] netmiko poxy import fixes
saltstack/salt pull request #62404
Opened 2022-08-01 21:51 UTC by garethgreenaway

### What does this PR do?
Due to changes in the Netmiko library for the exception paths, need to check the version of Netmiko python library and then import the exceptions from different locations depending on the result.

### What issues does this PR fix or reference?
Fixes: N/A

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-08-02 20:56 UTC, garethgreenaway commented
Change in Netmiko mentioned here: https://github.com/ktbyers/netmiko/releases/tag/v4.0.0

2022-08-02 20:58 UTC, whytewolf approved these changes, later dismissed

2022-08-02 22:04 UTC, dmurphy18 approved these changes, later dismissed

2022-08-03 13:27 UTC, Ch3LL requested changes
changelog?

2022-08-03 16:46 UTC, s0undt3ch requested changes

2022-08-03 16:46 UTC, s0undt3ch commented on salt/proxy/netmiko_px.py
> +    if _LooseVersion(found_netmiko_version) <= _LooseVersion("3.4.0"):
I'd do a simple `try/catch ImportError`, it's faster and doesn't require version comparisons.
Try to import from the newer module, fallback to the old.

2022-08-05 17:55 UTC, s0undt3ch approved these changes

2022-08-06 16:25 UTC, s0undt3ch approved these changes

2022-08-06 16:25 UTC, s0undt3ch commented
Tests are passing and includes changelog.
Merging.

2022-08-06 16:26 UTC, s0undt3ch commented
Dam, @garethgreenaway looks like you need to rebase.

2022-08-08 15:20 UTC, merged