netmiko poxy import fixes
saltstack/salt pull request #62412
Opened 2022-08-02 21:24 UTC by garethgreenaway

### What does this PR do?
need to check the version of Netmiko python library and then import the exceptions from different locations depending on the result.

### What issues does this PR fix or reference?
Fixes: #62404

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-08-02 21:24 UTC, garethgreenaway commented
Change in Netmiko mentioned here: https://github.com/ktbyers/netmiko/releases/tag/v4.0.0

2022-08-02 22:04 UTC, dmurphy18 approved these changes, later dismissed

2022-08-02 22:32 UTC, waynew approved these changes, later dismissed

2022-08-03 13:28 UTC, Ch3LL requested changes
changelog?

2022-08-03 18:38 UTC, Ch3LL approved these changes

2022-08-04 14:04 UTC, merged