pkg: update mac brew pkg to use combined cask/formula commands
saltstack/salt pull request #62437
Opened 2022-08-07 17:03 UTC by SMillerDev

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: improves interaction with Homebrew package manager

### Previous Behavior
Specific to macOS and no usage of shared commands for cask and formula

### New Behavior
Allow Homebrew anywhere and optimize commands

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-09-26 19:57 UTC, Ch3LL commented
Does this PR https://github.com/saltstack/salt/pull/59439/files implement your fix?

2022-09-26 20:37 UTC, SMillerDev commented
It seems there is some overlap yes, I'll rebase.

2023-02-26 16:32 UTC, SMillerDev commented
Took a while, but I finally rebased it

2023-03-22 19:46 UTC, Ch3LL requested changes
this will also require a changelog

2023-03-22 19:46 UTC, Ch3LL commented on salt/modules/mac_brew_pkg.py
> +    ret = {}
I don't think this is needed here?

2023-03-23 08:43 UTC, SMillerDev commented
> this will also require a changelog

@Ch3LL where/how do I write that?

2023-12-11 20:43 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-11 20:43 UTC, closed without merging