Fix payload and defaults
saltstack/salt pull request #62458
Opened 2022-08-11 18:36 UTC by twangboy

### What does this PR do?
Changes the default to `...` to allow `None` to be passed as a valid option to bypass throwing an error. We can't set default to be an object because msgpack can't serialize it and causes `sys.argparse` to fail when returning data to the master.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62450

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-08-11 19:13 UTC, s0undt3ch submitted a review, later dismissed

2022-08-15 15:24 UTC, Ch3LL requested changes
changelog? and does there need to be test coverage?

2022-08-15 16:40 UTC, twangboy commented
There was a test written in the original PR. I think it covers the changes here:
https://github.com/saltstack/salt/pull/61089

2022-08-16 14:26 UTC, Ch3LL commented
It doesn't look like those tests are covering the issue created in https://github.com/saltstack/salt/issues/62450 . It should be easy to add a test that ensures none is returned when default none is passed. 

`salt-call --local pillar.get doesnotexist default=None`

2022-08-17 11:00 UTC, frebib commented
I tend to agree with Wayne's comment (https://github.com/saltstack/salt/issues/62450#issuecomment-1212262538) suggesting to use a static constant instead of magic behaviour based on internal python values to avoid any chance of conflict or ambiguity. Arguably using `None` in the first place is the same idea as using `...` but just with a more commonly used constant

2022-08-17 15:20 UTC, s0undt3ch commented
> I tend to agree with Wayne's comment ([#62450 (comment)](https://github.com/saltstack/salt/issues/62450#issuecomment-1212262538)) suggesting to use a static constant instead of magic behaviour based on internal python values to avoid any chance of conflict or ambiguity. Arguably using `None` in the first place is the same idea as using `...` but just with a more commonly used constant

A static constant would involve more code to support it(more imports in the code base).

`...` is not magical, [it's a built-in constant](https://docs.python.org/3/library/constants.html#Ellipsis), and in this context, it serves the exact same purpose as `None` without the side-effects that `None` caused, and with no additional imports in the code.

2022-08-17 15:22 UTC, s0undt3ch submitted a review, later dismissed

2022-08-17 15:29 UTC, s0undt3ch commented
Would this cause less potential confusion if we used `False` instead of `...`?

2022-08-17 17:47 UTC, s0undt3ch commented
After some internal discussion, I retracted my proposal and we implemented a "constant".

2022-08-17 22:26 UTC, Ch3LL approved these changes

2022-08-17 22:38 UTC, waynew approved these changes
One thought, but it's not a blocker at all. This looks good - I didn't run the tests locally, so trusting that happened correctly on your end :slightly_smiling_face:

2022-08-17 22:38 UTC, waynew commented on salt/defaults/__init__.py
> +        return self.value == other.value
**suggestion (non-blocking)** could be `return self.name == other.name and self.value == other.value`, but that's not an essential change

2022-08-18 00:24 UTC, merged