Deprecate `pytest` nox session names in favour `test` nox session names.
saltstack/salt pull request #62518
Opened 2022-08-23 06:34 UTC by s0undt3ch

### What does this PR do?
See title.
Now that we only use `pytest`, it's redundant to call the sessions `pytest`.

2022-08-23 16:34 UTC, twangboy submitted a review, later dismissed

2022-08-23 18:55 UTC, Ch3LL requested changes
Are there any docs that need to be udpated with the new session name?

2022-08-23 18:56 UTC, s0undt3ch commented
> Are there any docs that need to be udpated with the new session name?

Looking.

2022-08-23 20:15 UTC, s0undt3ch commented
Docs updated.

2022-08-24 19:51 UTC, Ch3LL approved these changes

2022-08-25 13:00 UTC, merged