Display conflicing policy names in error message
saltstack/salt pull request #62605
Opened 2022-09-01 20:35 UTC by twangboy

### What does this PR do?
When conflicting policies are found display possible long names in the error message

### What issues does this PR fix or reference?
Fixes: #62594

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-09-01 20:51 UTC, whytewolf approved these changes, later dismissed

2022-09-02 13:09 UTC, Ch3LL requested changes

2022-09-02 13:09 UTC, Ch3LL commented on changelog/62594.fixed
> +win_lgpo: Display conflicting policy names when more than one policy is found
the number 62594 seems to point to this issue: https://github.com/saltstack/salt/issues/62594

can you please change the filename to the issue that this PR Is fixing

2022-09-22 15:36 UTC, Ch3LL commented
bump @twangboy did you see my comment? Also there is a merge conflict

2022-09-27 18:18 UTC, Ch3LL approved these changes

2022-09-28 13:34 UTC, merged