[WIP] Fix runas when using the onedir bundled packages
saltstack/salt pull request #62617
Opened 2022-09-02 19:07 UTC by Ch3LL

### What does this PR do?
Updates the runas command that detects the environment for the runas user to work with the onedir bundled packages

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62565

### Previous Behavior
`[ERROR   ] Environment could not be retrieved for user 'root': stderr='Must pass in a salt command, available commands are:\nminion\nmaster\ncall\napi\ncloud\ncp\nextend\nkey\nproxy\npip\nrun\nshell\nspm\nssh\nsupport\nsyndic\npython\n' stdout=''`

### New Behavior
Environment variables are returned for the runas user.

2022-09-08 20:37 UTC, dwoz submitted a review, later dismissed

2022-09-13 18:56 UTC, garethgreenaway approved these changes

2022-09-13 20:01 UTC, s0undt3ch requested changes

2022-09-13 20:01 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_cmdmod.py
> +    bundled = [False, True]
Same parametrize comment as the other PR

2022-09-14 01:26 UTC, s0undt3ch approved these changes

2022-09-14 01:27 UTC, merged