Fix the the Pyinstaller hooks to preserve the environment if None ispassed.
saltstack/salt pull request #62630
Opened 2022-09-06 21:26 UTC by garethgreenaway

### What does this PR do?
Fix the the Pyinstaller hooks to preserve the environment if None ispassed.

### What issues does this PR fix or reference?
Fixes: TBD

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-09-06 22:38 UTC, MKLeb approved these changes, later dismissed

2022-09-06 22:45 UTC, whytewolf approved these changes, later dismissed

2022-09-07 01:18 UTC, s0undt3ch approved these changes, later dismissed

2022-09-07 21:44 UTC, garethgreenaway commented
@s0undt3ch If you're able to please double check the changes to the tests.

2022-09-07 22:56 UTC, MKLeb approved these changes, later dismissed

2022-09-08 04:59 UTC, s0undt3ch approved these changes, later dismissed

2022-09-08 13:07 UTC, Ch3LL requested changes
changelog?

2022-09-08 15:50 UTC, s0undt3ch approved these changes

2022-09-08 19:31 UTC, merged