Fix groupadd.* functions hard code relative command name
saltstack/salt pull request #62658
Opened 2022-09-12 15:39 UTC by nicholasmhughes

### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #62657

### Previous Behavior
`groupadd` (and other commands in the module) would not be found if the `PATH` environment variable was not set properly.

### New Behavior
Now an effort is made to find the command using the `which` util

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-09-12 18:41 UTC, nicholasmhughes commented
re-run pr-windows-2016-x64-py3-pytest

2022-09-16 17:21 UTC, MKLeb submitted a review, later dismissed

2022-09-16 20:44 UTC, twangboy approved these changes, later dismissed

2022-09-19 18:51 UTC, Ch3LL requested changes

2022-09-19 18:51 UTC, Ch3LL commented on tests/pytests/unit/modules/test_groupadd.py
> +def test_add():
Can we also add a test that ensures if the command does not exist that we raise the `CommandExecutionError`

2022-09-20 19:55 UTC, Ch3LL approved these changes

2022-09-20 19:56 UTC, merged