Fix runas when using the onedir bundled packages
saltstack/salt pull request #62673
Opened 2022-09-13 14:51 UTC by Ch3LL

port https://github.com/saltstack/salt/pull/62617 to master

2022-09-13 18:56 UTC, garethgreenaway submitted a review, later dismissed

2022-09-13 19:16 UTC, MKLeb approved these changes, later dismissed

2022-09-13 20:00 UTC, s0undt3ch requested changes

2022-09-13 20:00 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_cmdmod.py
> +    bundled = [False, True]
Instead of for looping, parametrize bundled.
```python
@pytest.mark.parametrize("bundled", [True, False])
def blah(bundled):
```

2022-09-13 20:00 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_cmdmod.py
> +    bundled = [False, True]
Same here.

2022-09-14 16:25 UTC, s0undt3ch requested changes

2022-09-14 16:25 UTC, s0undt3ch commented on tests/pytests/functional/modules/cmd/test_runas.py
> +def test_run_as(account, caplog):
```suggestion
def test_run_as(account):
```

2022-09-14 16:35 UTC, s0undt3ch approved these changes

2022-09-14 20:07 UTC, merged