Migrate LGPO tests to pytest
saltstack/salt pull request #62731
Opened 2022-09-21 22:09 UTC by twangboy

### What does this PR do?
Migrates LGPO tests to pytest. Enables the tests so they run.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/61717

### Previous Behavior
LGPO tests were not running

### New Behavior
LGPO tests now run

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-09-21 22:13 UTC, whytewolf approved these changes, later dismissed

2022-09-21 22:14 UTC, whytewolf commented
@twangboy pre-commit fail.

2022-09-22 00:08 UTC, whytewolf approved these changes, later dismissed

2022-09-22 17:45 UTC, whytewolf submitted a review, later dismissed

2022-09-22 17:50 UTC, dmurphy18 submitted a review, later dismissed

2022-09-22 17:51 UTC, Ch3LL requested changes

2022-09-22 17:51 UTC, Ch3LL commented on tests/pytests/functional/modules/win_lgpo/test_admx_policy.py
> +    if not os.path.exists(r"C:\Windows\System32\lgpo.exe"):
```suggestion
    sys_dir = pathlib.Path("C:\\", "Windows", "System32", "lgpo.exe")
    if not (sys_dir / "lgpo.exe").exists():
```

2022-09-22 17:51 UTC, Ch3LL commented on tests/pytests/functional/modules/win_lgpo/test_admx_policy.py
> +        sys_dir = pathlib.Path(r"C:\Windows\System32")
```suggestion

```

2022-09-22 17:51 UTC, Ch3LL commented on tests/pytests/functional/modules/win_lgpo/test_admx_policy.py
> +        if os.path.exists(sys_dir / "LGPO_30"):
```suggestion
        if (sys_dir / "LGPO_30").exists():
```

2022-09-22 17:51 UTC, Ch3LL commented on tests/pytests/functional/modules/win_lgpo/test_admx_policy.py
> +    reg_pol.unlink()
same here

2022-09-22 23:20 UTC, whytewolf approved these changes

2022-09-23 04:32 UTC, merged