Use `.select()` for entrypoints under `importlib_metadata>=5.0.0`
saltstack/salt pull request #62854
Opened 2022-10-10 21:30 UTC by MKLeb

### What does this PR do?
importlib_metadata>=5.0.0 deprecates the dict structure of the entrypoints object, so we use `.select()` instead for iterating over them if needed.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-10-10 22:42 UTC, whytewolf submitted a review, later dismissed

2022-10-11 15:50 UTC, s0undt3ch requested changes
We should probably also do a followup PR where we update the version of importlib_metadata we vendor in `salt/ext/`.

2022-10-11 15:50 UTC, s0undt3ch commented on salt/utils/entrypoints.py
> +    # pre importlib-metadata 5.0.0
try/catch is faster than `hasattr` and let's account for the newer way first, ie:
```python
def iter_entry_points(group, name=None):
    entry_points_listing = []
    entry_points = importlib_metadata.entry_points()

    try:
        for entry_point in entry_points.select(group=group):
            if name is not None and entry_point.name != name:
                continue
            entry_points_listing.append(entry_point)
    except AttributeError:
        # importlib-metadata < 5.0.0
        for entry_point_group, entry_points_list in entry_points.items():
            if entry_point_group != group:
                continue
            for entry_point in entry_points_list:
                if name is not None and entry_point.name != name:
                    continue
                entry_points_listing.append(entry_point)

    return entry_points_listing
```

2022-10-11 18:32 UTC, s0undt3ch approved these changes

2022-10-11 18:38 UTC, merged

2022-10-31 12:44 UTC, akshaypurohit commented
@MKLeb @s0undt3ch  Are there plans to merge this change to previous versions as well?

2022-10-31 18:20 UTC, MKLeb commented
@akshaypurohit I would say it is unlikley, as the previous major versions are all past Phase 2 support and have entered the CVE only phase. (https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html)