Add +X capability to linux_acl
saltstack/salt pull request #62852
Opened 2022-10-10 20:23 UTC by leifliddy

### What does this PR do?
It adds the +X setfacl capability feature. 
"The character X stands for the execute  permission  if  the file is a directory or already has execute permission for some user."

### What issues does this PR fix or reference?
References: https://github.com/saltstack/salt/issues/33921

### Previous Behavior
The setfacl character```X``` was not supported

### New Behavior
The setfacl character```X``` is now supported

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-10-29 10:25 UTC, leifliddy commented
Is there any update on this PR?

2022-10-31 21:37 UTC, dwoz requested changes
Can we add a test or `X` rather than changing the test which uses `x`.. Seems like by changing this we're removing coverage or `x`

2022-10-31 21:40 UTC, leifliddy commented
Agreed. I wasn't sure quite how to handle that. I'll see what I can do -- but this might be beyond my current abilities. Thanks.

2023-02-14 01:50 UTC, thecosmicfrog commented
Hi @leifliddy, @dwoz. Has any progress been made on this? Thanks.

2023-02-15 07:29 UTC, leifliddy commented
Yes, progress has been made on this. The proposed PR has added support for the setfacl `X` character 
All that's needed now is a functional unit test to be drafted. 
TBH, I just don't have the will/desire/time to write + test that out at the moment. 
If you look at the current  `test_present` linux_acl.py unit test -- it's nearly 300 lines long.
https://github.com/saltstack/salt/blob/master/tests/unit/states/test_linux_acl.py

So what needs to be done is to create a similar test that tests for the `rwX` acl

At that topic -- there's likely hundreds of PRs that are stuck in limbo due to the fact that not everyone is familiar with mock object library. The salt team must have known that imposing a hard unit test requirement would lead to this -- so it shouldn't be a total surprise that this has stymied progress on some level. Sorry, but I'm not spending several hours of my time to try and satisfy the unit test requirement when I can just run a `cmd.run` setfacl function instead to accomplish the same thing. 

Feel free the submit your own proposal for that though.

2023-02-16 07:09 UTC, leifliddy commented
On second thought, I should probably finish this. I'll revisit the unit test this weekend.

2023-08-30 22:25 UTC, twangboy requested changes

2023-08-30 22:25 UTC, twangboy commented on tests/unit/states/test_linux_acl.py
> +        perms = "rwX"
Could you add new test that tests `rxX` so that we can test both scenarios?

2023-08-31 01:26 UTC, leifliddy commented
@twangboy Can you please this change and see if that satisfies the requirement of having a separate test?
Feel free to phrase, reword, modify...etc anything in the PR.

2023-09-05 20:05 UTC, dwoz commented
@leifliddy This looks good to me now, any chance you can re-base to the HEAD of master?

2023-09-05 20:05 UTC, dwoz approved these changes, later dismissed

2023-09-05 22:33 UTC, leifliddy commented
Sure

2023-09-30 11:28 UTC, leifliddy commented
It looks like this is ready to be merged.

2023-10-24 00:16 UTC, leifliddy commented
@twangboy What was the issue with this? Why did it never get merged?

2023-10-25 01:55 UTC, leifliddy commented
@dwoz Are you still tracking this? I just re-requested a review. I can easily rebase my changes no problem -- but I need at least some sort of acknowledgement from the reviewers that they're tracking this.

2023-11-04 03:26 UTC, leifliddy commented
@twangboy @dwoz Is anyone going to respond to this? If not -- please assign this PR a reviewer that will respond. 
I shouldn't have to wait months after making the requested changes -- for a reviewer to respond.

2023-11-07 21:56 UTC, leifliddy commented
I'm just going to close the PR, open up a new one -- and hopefully get assigned some different reviewers.

2023-11-27 10:58 UTC, OrangeDog commented
Apparently this is being ignored because there are failing tests, even though they have nothing to do with your changes.
https://saltstackcommunity.slack.com/archives/C8832QN4U/p1700852406066979?thread_ts=1700828180.622949&cid=C8832QN4U

2023-11-27 11:08 UTC, leifliddy commented
oh really, I can rebase the changes and have the tests re-run no problem. So the reviewers weren't being notified?

2023-11-27 11:37 UTC, lkubb commented
I would assume they were still notified, but `two failing checks` was the reaction of a core dev - might be an indication of the general core team workflow. (I have also been ignored on passing CI, but maybe less so)

Better wait with a rebase until the master branch CI is fixed, currently it's crashing hard.

2023-12-11 03:04 UTC, dwoz commented
@leifliddy Can you please add a changelog entry?

2023-12-11 04:49 UTC, leifliddy commented
@dwoz damn, forgot about that. Ok, I just pushed it.

2023-12-11 05:07 UTC, dwoz approved these changes, later dismissed

2023-12-11 20:50 UTC, leifliddy commented
@dwoz Can you please remove the `needs-changelog-file` label?

2023-12-20 20:52 UTC, twangboy approved these changes

2024-01-15 00:55 UTC, leifliddy commented
Can this get merged please?

2024-01-16 17:56 UTC, twangboy commented
These tests probably won't pass until we get 3006.x and 3007.x merged in to master

2024-07-12 22:51 UTC, dwoz commented
@twangboy I think this should be back-ported to 3006.x and then merged forward as it's a long standing bug.

2024-07-16 14:44 UTC, twangboy commented
@leifliddy Could you rebase this PR against the 3006.x branch please?

2025-03-28 19:33 UTC, twangboy approved these changes, later dismissed

2025-12-09 20:45 UTC, twangboy commented
Please rebase and address conflicts

2026-06-10 00:16 UTC, dwoz approved these changes

2026-06-10 00:17 UTC, merged