[WIP] Deltaproxy concurrent experiment
saltstack/salt pull request #62897
Opened 2022-10-15 16:55 UTC by garethgreenaway

### What does this PR do?
Deltaproxy concurrent experiment

### What issues does this PR fix or reference?
Fixes: TBA

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-10-15 21:23 UTC, s0undt3ch reviewed
I like where this is going.

2022-11-03 18:33 UTC, Ch3LL requested changes

2022-11-03 18:33 UTC, Ch3LL commented on changelog/61153.fixed
> +Initial work to allow parallel startup of proxy minions when used as sub proxies with Deltaproxy.
File extension should be `.added` since this is a new feature.

2022-11-03 18:33 UTC, Ch3LL commented on salt/metaproxy/deltaproxy.py
> +        log.debug("Doing parallel startup")
```suggestion
        log.debug("Initiating parallel startup for proxies")
```

2022-11-03 18:33 UTC, Ch3LL commented on salt/metaproxy/deltaproxy.py
> +        log.debug("Doing non-parallel startup")
```suggestion
        log.debug("Initiating non-parallel startup for proxies")
```

2022-11-03 19:17 UTC, Ch3LL approved these changes

2022-11-03 19:55 UTC, twangboy approved these changes

2022-11-15 17:49 UTC, s0undt3ch approved these changes

2022-11-15 20:56 UTC, merged