cmdmod.py: Don't reset output vars inside loop
saltstack/salt pull request #62903
Opened 2022-10-18 10:18 UTC by roelvanmeer

The stdout and stderr variables are used to collect the output of the command. These should not be reset inside the loop, because then the output that was already collected gets lost.

This problem was likely introduced by c7d275662da, which seems to be a purely formatting commit.

Fixes: 60365

2022-10-18 19:04 UTC, Ch3LL requested changes
Thanks for this change. This will require a changelog and test coverage.

2022-10-18 19:37 UTC, roelvanmeer commented
Can you please label this as `Needs Testcase` and `Help Wanted` then, since I won't have time to figure out how to do those any time soon. Thanks!

2022-11-17 21:16 UTC, Ch3LL approved these changes

2022-11-18 17:38 UTC, twangboy approved these changes

2022-11-18 19:32 UTC, merged