Add environment file serializer
saltstack/salt pull request #62984
Opened 2022-10-31 17:13 UTC by nicholasmhughes

### What does this PR do?
Add an environment file serializer

### What issues does this PR fix or reference?
Fixes: #62983

### New Behavior
`file.serialize` can output a dataset such as:

```
foo: bar
wang: chung
```

or

```
- [foo, bar]
- [wang, chung]
```

as

```
foo=bar
wang=chung
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-11-01 13:44 UTC, OrangeDog commented
I think `properties` or `keyvalue` would be better names than `envfile`.

2022-11-01 16:41 UTC, cmcmarrow requested changes
Look like `assert serialized == "foo=bar baz\nsalt=rocks", serialized` will lead to test failer on windows because /r/n

2022-11-01 21:44 UTC, OrangeDog commented
> Look like `assert serialized == "foo=bar baz\nsalt=rocks", serialized` will lead to test failer on windows because /r/n

Perhaps there should also be an option to choose line endings?

The options that are there do need to be documented though.

2022-11-02 16:18 UTC, nicholasmhughes commented
re-run pr-freebsd-131-amd64-py3-pytest

2022-11-02 19:54 UTC, cmcmarrow approved these changes

2022-11-02 21:32 UTC, cmcmarrow requested changes
I agree with orange dog that /r/n should be an option and documented

2022-11-07 19:55 UTC, OrangeDog commented on salt/serializers/keyvalue.py
> +        serialization or dequoted (``False``) during deserialization.
This doesn't seem right. Surely when `True` it should both quote when serializing and dequote when deserializing?

When `False` it should write and read raw values.

2022-11-07 19:56 UTC, Ch3LL requested changes

2022-11-07 19:56 UTC, Ch3LL commented on salt/serializers/keyvalue.py
> +    salt.serializers.keyvalue
can you add a versionadded for 3006

2022-11-07 19:56 UTC, OrangeDog commented on salt/serializers/keyvalue.py
> +        serialization or dequoted (``False``) during deserialization.
It also doesn't say what the default is.

2022-11-07 19:57 UTC, OrangeDog commented on salt/serializers/keyvalue.py
> +        String representing the character(s) used when concatenating or reading
Presumably you mean the separator between the key and the value?

It also doesn't say what the default is.

2022-11-07 20:30 UTC, Ch3LL approved these changes

2022-11-07 20:32 UTC, OrangeDog commented on salt/serializers/keyvalue.py
> +        serialization or dequoted (``False``) during deserialization.
According to the tests it also uses single quotes. There should probably be an option for double quotes.

2022-11-07 22:02 UTC, nicholasmhughes commented
re-run pr-windows-2019-x64-py3-pytest

2022-11-08 16:12 UTC, cmcmarrow approved these changes

2022-11-08 19:53 UTC, merged