influxdb_continuous_query: [fix] client connection
saltstack/salt pull request #63007
Opened 2022-11-03 14:53 UTC by skob

### What does this PR do?
state influxdb_continuous_query was broken if influxdb_host param passed throw state

### Commits signed with GPG?
No

2022-11-07 20:44 UTC, Ch3LL requested changes
This will require a changelog. If you could open an issue with the error that you were running into that will help me understand the reasoning for this change.

I'll ask the team to see if we are going to require test coverage here or not. thanks

2022-11-08 08:53 UTC, skob commented
related issue https://github.com/saltstack/salt/issues/59766

2022-11-08 20:20 UTC, Ch3LL commented
Thanks, can you add a changelog. 

@waynew stated he is willing to investigate writing a test for this one.

2022-11-08 21:43 UTC, waynew commented
@Ch3LL tests have been written and I went ahead and added a changelog while I was at it :+1:

2022-11-08 22:17 UTC, garethgreenaway approved these changes

2022-11-08 23:58 UTC, twangboy approved these changes

2022-11-09 01:47 UTC, merged