Fix old root_dir paths on Windows
saltstack/salt pull request #63030
Opened 2022-11-07 17:09 UTC by twangboy

### What does this PR do?
Fixes the cloud salt util to place minion config in the correct Root Directory.

### What issues does this PR fix or reference?
Fixes:
- Keys : https://github.com/saltstack/salt/issues/62968
- Keys : https://github.com/saltstack/salt/issues/63016
- Grains : https://github.com/saltstack/salt/issues/63024

### Previous Behavior
All config laid down by Salt Cloud was placed in the old Root Directory (`C:\Salt`)

### New Behavior
All config laid down by Salt Cloud is not placed in the new Root Directory (`%PROGRAMDATA%\Salt Project\Salt`)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-11-07 23:24 UTC, MKLeb submitted a review, later dismissed

2022-11-08 17:14 UTC, MKLeb submitted a review, later dismissed

2022-11-08 20:01 UTC, Ch3LL requested changes
changelog and test coverage

2022-11-10 19:02 UTC, MKLeb approved these changes, later dismissed

2022-11-10 19:17 UTC, MKLeb approved these changes

2022-11-13 08:59 UTC, s0undt3ch approved these changes

2022-11-14 17:02 UTC, garethgreenaway approved these changes

2022-11-14 17:02 UTC, merged