Cleanup PAexec on disconnect
saltstack/salt pull request #63031
Opened 2022-11-07 17:11 UTC by twangboy

### What does this PR do?
Attempts to use the cleanup() function of the pypsexec client to clean up binaries on disconnect.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62152

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2022-11-07 20:33 UTC, Ch3LL requested changes
tests and changelog

2022-11-16 19:26 UTC, Ch3LL approved these changes

2022-11-16 19:28 UTC, MKLeb approved these changes

2022-11-16 19:29 UTC, whytewolf approved these changes

2022-11-16 19:29 UTC, merged