Restore old Slack engine, add dreprecation, rename new Slack engine
saltstack/salt pull request #63095
Opened 2022-11-21 18:39 UTC by garethgreenaway

### What does this PR do?
Restore the previous slack engine and deprecate it, rename replace the slack engine to slack_bolt until deprecation

### What issues does this PR fix or reference?
Fixes:  #62957

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-11-21 19:17 UTC, Ch3LL requested changes

2022-11-21 19:17 UTC, Ch3LL commented on changelog/63095.added
> +Restore the previous slack engine and deprecate it, rename replace the slack engine to slack_bolt until deprecation
We should probably add a separate `.deprecated` changelog for noting the slack engine being depprecated as well as the added

2022-11-21 19:17 UTC, Ch3LL commented on salt/engines/slack_bolt_engine.py
> +.. versionadded:: 2016.3.0
```suggestion
.. versionadded:: 3006.0
```

2022-11-21 19:18 UTC, Ch3LL commented
I'm also not seeing slack_bolt in our tests requirements so I'm guesing the tests are getting skipped

2022-11-21 19:20 UTC, garethgreenaway commented
@Ch3LL The tests will only run if the two Slack Python libraries are installed, the newer one we can install but the older one has difficulties with newer versions of Python.

2022-11-22 03:06 UTC, twangboy requested changes

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +                        "Got an error from trying to get the message text %s", msg_err
Got an error trying

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +        It's possible for None or False to be the result of either, which means
```
``None`` or ``False``
```

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +
args need to be documented

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +            Validate cmd against the group to return the target, or a null target
Document `cmd`

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +        Print out YAML using the block mode
Docs for data and function

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +        cmdline: list
Maybe a description as well for cmdline

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +        completed.
Docs for the arg

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +        the values of fire_all and command
Docs for the args

2022-11-22 03:06 UTC, twangboy commented on salt/engines/slack_bolt_engine.py
> +    """
Docs for the args

2022-11-22 03:07 UTC, twangboy requested changes
Need to standardize on the type/parameter for all the arguments in the docs for the functions. You're doing it on some and not others.

2022-12-06 20:33 UTC, Ch3LL approved these changes

2022-12-07 16:13 UTC, merged