Add ethtool execution and state module functions for pause
saltstack/salt pull request #63129
Opened 2022-11-28 22:00 UTC by nicholasmhughes

### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #63128

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-11-29 22:44 UTC, twangboy approved these changes, later dismissed

2022-11-30 20:20 UTC, Ch3LL requested changes

2022-11-30 20:20 UTC, Ch3LL commented on salt/modules/ethtool.py
> +    """
can you add a versionadded for all the new functions?

2022-12-05 19:33 UTC, Ch3LL approved these changes

2022-12-05 19:47 UTC, cmcmarrow approved these changes

2022-12-06 16:23 UTC, merged