remove boto dependency from boto3mod
saltstack/salt pull request #63135
Opened 2022-11-29 15:22 UTC by keslerm

### What does this PR do?
Removes the Boto dependency from Boto3mod

### What issues does this PR fix or reference?
Fixes: [62672](https://github.com/saltstack/salt/issues/62672)

### Previous Behavior
Boto3 commands are unusable unless the four year old module is installed

### New Behavior
Will work correctly

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-11-29 22:40 UTC, twangboy submitted a review, later dismissed

2022-11-30 20:18 UTC, Ch3LL reviewed
This module is also importing `boto.exception` which would require the old boto library. Can this be replaced with the the boto3 library?

2022-12-01 22:56 UTC, keslerm commented
@Ch3LL I'll give it a look tomorrow. I originally honestly gave this a create just to see if it would at least pass tests.

2022-12-02 16:43 UTC, whytewolf submitted a review, later dismissed

2022-12-02 19:55 UTC, Ch3LL requested changes
thanks this looks good. Apologies for not mentioning this previously, but can you add a changelog file for this change. https://docs.saltproject.io/en/latest/topics/development/changelog.html

2022-12-02 20:38 UTC, keslerm commented
@Ch3LL No problem - added.

2022-12-02 20:40 UTC, Ch3LL approved these changes

2022-12-06 16:27 UTC, s0undt3ch approved these changes

2022-12-06 16:30 UTC, whytewolf approved these changes

2022-12-06 16:56 UTC, twangboy approved these changes

2022-12-06 23:59 UTC, merged