Add keyring param to gpg modules, final cleanup
saltstack/salt pull request #63179
Opened 2022-12-02 00:27 UTC by lkubb

### What does this PR do?
- Adds `keyring` param to all functions (if sensible)
- Adds option to delete empty keyring file to `gpg.absent`
- Finally brings all functions up to speed by having `user`, `gnupghome` and `keyring` (if sensible)
- Adds functional tests for both modules
- Fixes some miscellaneous bugs surfaced by the tests (I would be very happy to not write a report for each one tbh, I'm quite exhausted with all the bug reports for the `gpg` modules)
- Fixes some copy & paste doc issues

Outstanding:
- [ ] add `gnupghome` and `keyring` to `trust_key`
- [ ] see if tests pass in CI/correct them
- [ ] read the docs and correct some more errors

This is based off of https://github.com/saltstack/salt/pull/63162, so that one would have to be merged before.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/59783

### Previous Behavior
always uses default keyring

### New Behavior
keyring can be specified

### Merge requirements satisfied?
- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-05-08 17:41 UTC, twangboy requested changes

2023-05-08 17:41 UTC, twangboy commented on salt/modules/gpg.py
> +    Search keys on a keyserver
Search *for* keys on a keyserver

2023-12-11 08:58 UTC, lkubb commented
@twangboy Can we still get this into 3007? This PR has celebrated its first birthday recently.

2023-12-11 21:05 UTC, dwoz approved these changes

2023-12-11 21:05 UTC, merged