[WIP] Attempt to make the VMware instant clone test less flaky
saltstack/salt pull request #63174
Opened 2022-12-01 17:39 UTC by MKLeb

### What does this PR do?
See title

This is WIP, still have some statements in here that serve a debugging purpose.  Will remove them if it solves it.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62614

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-12-05 19:45 UTC, cmcmarrow approved these changes, later dismissed

2022-12-07 16:47 UTC, twangboy approved these changes

2022-12-07 17:12 UTC, Ch3LL requested changes

2022-12-07 17:32 UTC, MKLeb commented on tests/integration/cloud/clouds/test_vmware.py
> +        handler = TstSuiteLoggingHandler(format=log_format, level=logging.INFO)
I tried that, and it failed because we aren't providing fixtures for our unittest-based tests.  So, I resorted to this.

2022-12-07 17:46 UTC, Ch3LL approved these changes

2022-12-07 17:47 UTC, merged