Add automated performance test
saltstack/salt pull request #63233
Opened 2022-12-07 02:15 UTC by MKLeb

### What does this PR do?
See title

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/61106

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2022-12-07 19:59 UTC, Ch3LL requested changes

2022-12-07 19:59 UTC, Ch3LL commented on tests/pytests/scenarios/performance/test_performance.py
> +        print(ret)
can this print be removed?

2022-12-07 20:20 UTC, MKLeb commented on tests/pytests/scenarios/performance/test_performance.py
> +        print(ret)
```suggestion
```

2022-12-07 20:35 UTC, Ch3LL approved these changes, later dismissed

2022-12-08 17:21 UTC, MKLeb commented
re-run all

2022-12-09 16:59 UTC, MKLeb commented
re-run all

2022-12-12 18:21 UTC, MKLeb commented
re-run all

2022-12-20 17:43 UTC, MKLeb commented
re-run all

2023-01-12 20:10 UTC, Ch3LL approved these changes, later dismissed

2023-02-13 14:54 UTC, MKLeb commented
re-run full all

2023-02-14 20:27 UTC, MKLeb commented
re-run pull all

2023-02-15 15:37 UTC, MKLeb commented
re-run full all

2023-03-01 20:50 UTC, Ch3LL approved these changes

2023-03-02 17:32 UTC, merged