Initial commit of relenv debian package
saltstack/salt pull request #63254
Opened 2022-12-07 23:15 UTC by dwoz

### What does this PR do?

* Pulling in debian packaging from salt-pkg back into the main salt repository.
* Using relenv for 'onedir' packaging approach

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2022-12-08 17:53 UTC, dwoz commented
re-run all

2022-12-13 18:07 UTC, Ch3LL requested changes

2022-12-13 18:07 UTC, Ch3LL commented on pkg/deb/debian/changelog
> +  * Build of Salt {{version}} with Tiamat
```suggestion
  * Build of Salt {{version}} with relenv
```

2022-12-15 21:23 UTC, s0undt3ch requested changes

2022-12-15 21:23 UTC, s0undt3ch commented on pkg/salt-api.service
> +Documentation=man:salt-api(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
```suggestion
Documentation=man:salt-api(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
```
This line had the correct URL

2022-12-15 21:23 UTC, s0undt3ch commented on pkg/salt-master.service
> +Documentation=man:salt-master(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
This too

2022-12-15 21:23 UTC, s0undt3ch commented on pkg/salt-minion.service
> +Documentation=man:salt-minion(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
And this

2022-12-15 21:23 UTC, s0undt3ch commented on pkg/salt-proxy@.service
> +Documentation=man:salt-proxy(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
And this

2022-12-19 22:35 UTC, s0undt3ch requested changes

2022-12-19 22:35 UTC, s0undt3ch commented on pkg/README
> +common/ - Files common to multiple pacakges.
```suggestion
common/ - Files common to multiple packages.
```

2022-12-19 22:35 UTC, s0undt3ch commented on pkg/debian/changelog
> +  * Build of Salt {{version}} with Tiamat
```suggestion
  * Build of Salt {{version}} with Relenv
```

2022-12-19 22:35 UTC, s0undt3ch commented on pkg/debian/control
> +Homepage: http://saltstack.org/
```suggestion
Homepage: http://saltproject.io
```
?

2022-12-19 22:35 UTC, s0undt3ch commented on pkg/old/README.md
> +relying these files. Please file a bug report if you are relying any files that
```suggestion
relying on these files. Please file a bug report if you are relying any files that
```

2022-12-20 18:16 UTC, Ch3LL requested changes

2022-12-20 18:16 UTC, Ch3LL commented on pkg/old/README.md
> +The things found in this directory have been depericated and will be removed in
```suggestion
The things found in this directory have been deprecated and will be removed in
```

2022-12-20 18:32 UTC, s0undt3ch submitted a review, later dismissed

2022-12-22 14:58 UTC, Ch3LL approved these changes

2022-12-22 14:59 UTC, merged