Put back deprecation warnings
saltstack/salt pull request #63315
Opened 2022-12-13 19:26 UTC by waynew

### What does this PR do?

Fixes #62185 - now we emit DeprecationWarnings again.

Can test against the MCVE in https://github.com/saltstack/salt/pull/59917

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- ~[x] Docs~
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- ~[ ] Tests written/updated~

### Commits signed with GPG?
Yes

2022-12-13 19:51 UTC, s0undt3ch approved these changes, later dismissed

2022-12-13 20:59 UTC, Ch3LL submitted a review, later dismissed

2022-12-21 14:43 UTC, Ch3LL approved these changes, later dismissed

2022-12-25 09:12 UTC, s0undt3ch requested changes
Test failures look valid.

2023-01-10 19:19 UTC, waynew commented
@s0undt3ch test failures look to be sorted, finally :upside_down_face:

2023-01-10 19:51 UTC, s0undt3ch approved these changes

2023-01-10 19:53 UTC, merged