Add salt-pip wrapper script
saltstack/salt pull request #63358
Opened 2022-12-21 20:18 UTC by dwoz

### What does this PR do?

Adding salt-pip wrapper script for user convenience

2022-12-21 20:28 UTC, twangboy approved these changes, later dismissed

2022-12-22 15:03 UTC, Ch3LL approved these changes, later dismissed

2022-12-22 15:03 UTC, Ch3LL commented
looks good, just has a merge conflict.

2022-12-22 17:54 UTC, s0undt3ch requested changes

2022-12-22 17:54 UTC, s0undt3ch commented on salt/scripts.py
> +    sys.exit(ret)
```suggestion
    ret = subprocess.run(command, shell=False, check=False)
    sys.exit(ret.returncode)
```

2022-12-22 21:44 UTC, s0undt3ch submitted a review, later dismissed

2022-12-23 14:45 UTC, Ch3LL approved these changes

2022-12-23 16:24 UTC, merged