Allow passing --update=.. args to raid.present
saltstack/salt pull request #63396
Opened 2022-12-30 10:04 UTC by frebib

mdraid complains loudly if you call raid.create with update= kwargs, even though they are entirely valid for raid.assemble. Given that the user can't influence whether the raid will be assembled or created, helpfully strip out invalid --update=.. args when not assembling an array to avoid any nasty surprises when the raid doesn't exist:

    [INFO    ] Executing state udevraid.present for [/dev/md/all]
    [INFO    ] Executing command mdadm in directory '/root'
    [INFO    ] Executing command 'mdadm' in directory '/root'
    [DEBUG   ] stderr: mdadm: No md superblock detected on /dev/mapper/luks-nvme0n1p2.
    [DEBUG   ] retcode: 1
    [INFO    ] Executing command 'mdadm' in directory '/root'
    [DEBUG   ] stderr: mdadm: No md superblock detected on /dev/mapper/luks-nvme1n1p2.
    [DEBUG   ] retcode: 1
    [INFO    ] Executing command 'mdadm' in directory '/root'
    [DEBUG   ] stderr: mdadm: No md superblock detected on /dev/mapper/luks-nvme2n1p2.
    [DEBUG   ] retcode: 1
    [INFO    ] Executing command mdadm in directory '/root'
    [ERROR   ] Command 'mdadm' failed with return code: 2
    [ERROR   ] stdout: mdadm: :option --update not valid in create mode
    [ERROR   ] retcode: 2
    [ERROR   ] Command 'mdadm' failed with return code: 2
    [ERROR   ] output: mdadm: :option --update not valid in create mode
    [INFO    ] Executing command mdadm in directory '/root'
    [INFO    ] Executing command mdadm in directory '/root'
    [INFO    ] Executing command '/bin/udevadm' in directory '/root'
    [INFO    ] Executing command mdadm in directory '/root'
    [ERROR   ] Raid /dev/md/all failed to be created.

Signed-off-by: Joe Groocock <jgroocock@cloudflare.com>

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-06 16:44 UTC, cmcmarrow requested changes
Can we log when we are trashing "update" and give a little into to the user why? Thx for the test.

2023-03-06 16:44 UTC, cmcmarrow commented on salt/states/mdadm_raid.py
> +            del kwargs["update"]
Can we add a log statement here?

2023-03-08 20:41 UTC, Ch3LL requested changes

2023-12-12 00:56 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

@frebib Feel free to re-open this and I'll work with you to get it into a relase.

2023-12-12 00:56 UTC, closed without merging