migrate test_iosconfig to pytest
saltstack/salt pull request #63426
Opened 2023-01-06 20:59 UTC by frogunder

### What does this PR do?

migrate test_iosconfig to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-01-07 21:50 UTC, s0undt3ch reviewed
Just a typo

2023-01-07 21:50 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_iosconfig.py
> +    extected_merge_text = textwrap.dedent(
```suggestion
    expected_merge_text = textwrap.dedent(
```

2023-01-09 15:17 UTC, frogunder commented on tests/pytests/unit/modules/test_iosconfig.py
> +    extected_merge_text = textwrap.dedent(
Fixed typo, thanks.

2023-01-09 19:11 UTC, s0undt3ch requested changes

2023-01-09 19:11 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_iosconfig.py
> +# Import Salt modules
```suggestion
```

2023-01-09 19:11 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_iosconfig.py
> +    return {}
```suggestion
    return {isoconfig: {}}
```
?

2023-01-09 19:40 UTC, frogunder commented on tests/pytests/unit/modules/test_iosconfig.py
> +    return {}
Thanks Pedro.

2023-01-10 20:20 UTC, s0undt3ch approved these changes

2023-01-10 20:26 UTC, merged