migrate test_xml to pytest
saltstack/salt pull request #63485
Opened 2023-01-13 21:27 UTC by frogunder

### What does this PR do?

migrate test_xml to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-01-16 02:59 UTC, s0undt3ch requested changes

2023-01-16 02:59 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_xml.py
> +def XML_STRING():
```suggestion
def XML_STRING():
```
Lowercase the fixture name

2023-01-16 02:59 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_xml.py
> +    os.remove(xml_file.name)
```suggestion
def test_get_value(XML_STRING, tmp_path):
    """
    Verify xml.get_value
    """
    xml_file = tmp_path / "name-it-as-you-like.xml"
    xml_file.write_text(XML_STRING)
    xml_result = xml.get_value(str(xml_file), ".//actor[@id='2']")
    assert xml_result == "Liam Neeson"
```
Do the same for the other tests

2023-01-17 18:21 UTC, frogunder commented on tests/pytests/unit/modules/test_xml.py
> +    os.remove(xml_file.name)
Thank you

2023-01-18 17:39 UTC, frogunder commented
re-run all

2023-01-20 14:24 UTC, s0undt3ch approved these changes, later dismissed

2023-03-16 12:47 UTC, s0undt3ch approved these changes

2023-03-16 12:47 UTC, merged