migrate test_vagrant to pytest
saltstack/salt pull request #63512
Opened 2023-01-19 17:36 UTC by frogunder

### What does this PR do?

migrate test_vagrant to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-01-20 14:16 UTC, s0undt3ch requested changes

2023-01-20 14:16 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_vagrant.py
> +    return {vagrant: vagrant_globals}
```suggestion
    return {vagrant: {"__opts__": local_opts}}
```

2023-01-20 14:16 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_vagrant.py
> +    }
```suggestion
@pytest.fixture
def local_opts(tmp_path):
    return {
        "extension_modules": "",
        "vagrant_sdb_data": {
            "driver": "sqlite3",
            "database": str(tmp_path / "test_vagrant.sqlite"),
            "table": "sdb",
            "create_table": True,
        },
    }
```

2023-01-20 14:16 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_vagrant.py
> +        path_nowhere = "c:{}".format(path_nowhere)
```suggestion
def test_vagrant_init_positional(local_opts, tmp_path):
    path_nowhere = str(tmp_path / "tmp" / "nowhere")
```

2023-01-20 14:16 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_vagrant.py
> +        path_mydir = "c:{}".format(path_mydir)
```suggestion
def test_vagrant_destroy(local_opts, tmp_path):
    path_mydir = str(tmp_path / "my" / "dir")
```

2023-12-12 22:31 UTC, dwoz approved these changes

2023-12-12 22:31 UTC, merged