Handle access denied
saltstack/salt pull request #63510
Opened 2023-01-19 16:00 UTC by twangboy

### What does this PR do?
Fixes issue with the minion starting when it doesn't have access to the registry key where `root_dir` is defined. The `win_reg.read_value` function was stacktracing with an "Access is denied" error. Now we handle that and fall back to sane defaults.

### Previous Behavior
Stacktrace when the minion didn't have permissions to the registry key for `root_dir`

### New Behavior
No stacktrace. Falls back to default value.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-01-21 08:46 UTC, s0undt3ch approved these changes, later dismissed

2023-01-23 20:08 UTC, Ch3LL requested changes
This will need a changelog

2023-01-24 16:54 UTC, Ch3LL approved these changes

2023-01-31 22:43 UTC, garethgreenaway approved these changes

2023-01-31 22:44 UTC, merged