Set set_enable_fqdns_grains to be False by default.
saltstack/salt pull request #63555
Opened 2023-01-25 23:50 UTC by garethgreenaway

### What does this PR do?
Set set_enable_fqdns_grains to be False by default.

### What issues does this PR fix or reference?
Fixes: N/A

### Previous Behavior
enable_fqdns_grains was True by default on non-Windows and non-proxy hosts.

### New Behavior
enable_fqdns_grains is not set as False by default.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-01-26 16:34 UTC, dmurphy18 approved these changes, later dismissed
yeah, about time we did that

2023-01-26 16:58 UTC, twangboy approved these changes, later dismissed

2023-01-31 18:24 UTC, Ch3LL requested changes
changelog

2023-01-31 19:28 UTC, Ch3LL approved these changes

2023-02-02 02:05 UTC, merged