migrate test_dnsutil to pytest
saltstack/salt pull request #63564
Opened 2023-01-26 16:05 UTC by frogunder

### What does this PR do?

migrate test_dnsutil to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-04 18:00 UTC, s0undt3ch requested changes

2023-04-04 18:00 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_dnsutil.py
> +        log.debug(dnsutil.parse_zone("/var/lib/named/example.com.zone"))
This doesn't test anything, we either delete it, or we fix it so that it tests something.

2023-04-11 15:26 UTC, frogunder commented on tests/pytests/unit/modules/test_dnsutil.py
> +
Removed

2023-12-12 22:41 UTC, dwoz approved these changes

2023-12-12 22:41 UTC, merged