Add a few more nice to have hooks
saltstack/salt pull request #63632
Opened 2023-02-04 19:24 UTC by s0undt3ch

### What does this PR do?
See title

2023-02-06 17:21 UTC, twangboy requested changes

2023-02-06 17:54 UTC, dmurphy18 approved these changes, later dismissed
Just the comment on the support URL

2023-02-06 19:29 UTC, s0undt3ch commented on SUPPORT.rst
>  `<http://www.saltstack.com/support>`_
That URL is a 404. And should be fixed on a PR specifically addressing that.
This is just automated fixes provided by the pre-commit hooks.

2023-02-06 19:34 UTC, s0undt3ch commented on pkg/macos/pkg-resources/conclusion.rtf
> +\f0\fs24  has been installed into
Should be fixed now

2023-02-06 19:34 UTC, s0undt3ch commented on pkg/macos/pkg-resources/welcome.rtf
> +\f0 ) will be installed to
Should be fixed now

2023-02-06 23:12 UTC, dmurphy18 approved these changes

2023-02-07 00:59 UTC, twangboy approved these changes

2023-02-07 07:10 UTC, s0undt3ch commented
PR approved and passing. Merging.

2023-02-07 07:10 UTC, merged