migrate test_dig to pytest
saltstack/salt pull request #63644
Opened 2023-02-06 20:30 UTC by frogunder

### What does this PR do?

migrate test_dig to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-04 17:54 UTC, s0undt3ch requested changes

2023-12-11 14:46 UTC, s0undt3ch requested changes

2023-12-11 14:46 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_dig.py
> +    ), "Not a valid ip address"
```suggestion
def test_check_ip():
    assert dig.check_ip("127.0.0.1")


def test_check_ip_ipv6():
    assert dig.check_ip(
        "1111:2222:3333:4444:5555:6666:7777:8888"
    )
```

2023-12-11 14:46 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_dig.py
> +    assert not dig.check_ip(""), "Did not detect empty value as invalid"
```suggestion
def test_check_ip_neg():
    assert not dig.check_ip("-127.0.0.1")


def test_check_ip_empty():
    assert not dig.check_ip("")
```

2023-12-12 22:43 UTC, dwoz approved these changes

2023-12-12 22:43 UTC, merged