migrate unit_test_template to pytest
saltstack/salt pull request #63688
Opened 2023-02-09 17:55 UTC by frogunder

### What does this PR do?

migrate unit_test_template to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-02-24 17:35 UTC, cmcmarrow approved these changes, later dismissed

2023-04-04 17:49 UTC, s0undt3ch requested changes

2023-04-04 17:49 UTC, s0undt3ch commented on tests/pytests/unit/test_template.py
> +    blacklist = whitelist = []
```suggestion
    blacklist = []
    whitelist = []
```
```python
Python 3.9.10 (main, Nov 15 2022, 11:40:21)
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> blacklist = whitelist = []
>>> blacklist.append(1)
>>> blacklist
[1]
>>> whitelist
[1]
>>>
```

2023-04-04 17:49 UTC, s0undt3ch commented on tests/pytests/unit/test_template.py
> +    assert [("fake_json_func", "")] == ret
```suggestion
    assert [("fake_json_func", "")] == ret
    ret = template.check_render_pipe_str("jinja|json", render_dict, None, ["jinja"])
    assert [("fake_jinja_func", "")] == ret
    ret = template.check_render_pipe_str(
        "jinja|json", render_dict, ["jinja"], ["jinja"]
    )
    assert [] == ret
    ret = template.check_render_pipe_str(
        "jinja|json", render_dict, ["jinja"], ["jinja", "json"]
    )
    assert [("fake_json_func", "")] == ret
```
Assert what we get against what we expect.

2023-04-12 19:28 UTC, frogunder commented
Closing this as there already is a file with same name in pytest directory.

2023-04-12 19:28 UTC, closed without merging