migrate unit_states_test_glusterfs to pytest
saltstack/salt pull request #63720
Opened 2023-02-14 20:23 UTC by frogunder

### What does this PR do?

migrate unit_states_test_glusterfs to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-15 15:06 UTC, s0undt3ch requested changes

2023-03-15 15:06 UTC, s0undt3ch commented on tests/pytests/unit/states/test_glusterfs.py
> +                ).format(name)
```suggestion
                comt = "Failed to peer with {0}, please check logs for errors".format(name)
```

2023-03-15 15:06 UTC, s0undt3ch commented on tests/pytests/unit/states/test_glusterfs.py
> +            comt = ("Volume {0} already exists" + " and will be started").format(name)
```suggestion
            comt = "Volume {0} already exists and will be started".format(name)
```

2023-03-15 15:06 UTC, s0undt3ch commented on tests/pytests/unit/states/test_glusterfs.py
> +            comt = ("Volume {0} will be created" + " and started").format(name)
```suggestion
            comt = "Volume {0} will be created and started".format(name)
```

2023-12-12 22:44 UTC, dwoz approved these changes

2023-12-12 22:45 UTC, merged