migrate unit_states_test_grains to pytest
saltstack/salt pull request #63730
Opened 2023-02-16 20:17 UTC by frogunder

### What does this PR do?

migrate unit_states_test_grains to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-15 14:31 UTC, s0undt3ch requested changes

2023-04-12 16:41 UTC, frogunder commented on tests/pytests/unit/states/test_grains.py
> +        },
Not sure how to fix this part, I can't get it to work with the suggested changes or other things I have tried.

The other issues should all be resolved.

2023-12-12 22:46 UTC, dwoz commented on tests/pytests/unit/states/test_grains.py
> +        },
@s0undt3ch Is the suggestion to put the directory creation in a different fixture?

2023-12-13 05:35 UTC, s0undt3ch approved these changes
Pushed my fixes

2023-12-15 18:01 UTC, twangboy approved these changes

2023-12-16 08:30 UTC, merged