migrate unit_states_test_jboss7 to pytest
saltstack/salt pull request #63751
Opened 2023-02-21 20:55 UTC by frogunder

### What does this PR do?

migrate unit_states_test_jboss7 to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-02-24 17:34 UTC, cmcmarrow approved these changes, later dismissed

2023-04-04 17:33 UTC, s0undt3ch requested changes

2023-04-04 17:33 UTC, s0undt3ch commented on tests/pytests/unit/states/test_jboss7.py
> +            assert str(e) == "Incorrect binding name."
```suggestion
        with pytest.raises(CommandExecutionError) as exc:
            jboss7.bindings_exist(
                name="bindings",
                jboss_config={},
                bindings={"env": "DEV2"},
                profile=None,
            )
        assert str(exc.value) == "Incorrect binding name."
```
This is how we should test code that should raise exceptions

2023-06-06 19:44 UTC, Ch3LL approved these changes

2023-06-06 19:44 UTC, merged