migrate unit_states_test_kubernetes to pytest
saltstack/salt pull request #63765
Opened 2023-02-23 20:23 UTC by frogunder

### What does this PR do?

migrate unit_states_test_kubernetes to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-04 07:54 UTC, s0undt3ch requested changes

2023-04-04 07:54 UTC, s0undt3ch commented on tests/pytests/unit/states/test_kubernetes.py
> +        reason="Kubernetes client lib is not installed. Skipping test_kubernetes.py",
```suggestion
        reason="Kubernetes client lib is not installed.",
```

2023-04-04 07:54 UTC, s0undt3ch commented on tests/pytests/unit/states/test_kubernetes.py
> +    } == error
```suggestion
    assert error == {
        "changes": {},
        "result": False,
        "name": "testme",
        "comment": "'source' cannot be used in combination with 'data'",
    }
```
Always assert what we get against what we expect...

There are other assertions like this in the module.

2023-06-06 19:43 UTC, Ch3LL approved these changes

2023-06-06 19:43 UTC, merged