WIP: Fix regex cache exception in sweep function
saltstack/salt pull request #63886
Opened 2023-03-15 16:11 UTC by msciciel

### What does this PR do?
Use lambda function to properly sort patterns using usage counter and avoid exception: TypeError: '<' not supported between instances of '_sre.SRE_Pattern' and '_sre.SRE_Pattern'

### What issues does this PR fix or reference?
Fixes: #59437

### Previous Behavior
salt -b 1 '*' cmd.run 'true'
 
Traceback (most recent call last):
 File "/usr/bin/salt", line 10, in <module>
  salt_main()
 File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 516, in salt_main
  client.run()
 File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 66, in run
  self._run_batch()
 File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 284, in _run_batch
  for res in batch.run():
 File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 210, in run
  part = next(queue)
 File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 922, in cmd_iter_no_block                                               
  **kwargs):
 File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1107, in get_iter_returns                                               
  for raw in ret_iter:
 File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1041, in get_returns_no_block                                             
  no_block=True, auto_reconnect=self.auto_reconnect)
 File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 651, in get_event
  ret = self._get_event(wait, tag, match_func, no_block)
 File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 564, in _get_event
  if not match_func(ret['tag'], tag):
 File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 516, in _match_tag_regex
  return self.cache_regex.get(search_tag).search(event_tag) is not None
 File "/usr/lib/python3.6/site-packages/salt/utils/cache.py", line 265, in get
  self.sweep()
 File "/usr/lib/python3.6/site-packages/salt/utils/cache.py", line 250, in sweep
  paterns.sort()
TypeError: '<' not supported between instances of '_sre.SRE_Pattern' and '_sre.SRE_Pattern'

### New Behavior
No exception

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2023-12-16 11:28 UTC, dwoz commented
Looks good but this could really use a regression test.

2024-01-19 22:08 UTC, dwoz requested changes, later dismissed
@msciciel Any chance you can add a test for this change?

2024-01-24 16:09 UTC, msciciel commented
> @msciciel Any chance you can add a test for this change?

Yes. I will try.

2025-03-28 15:55 UTC, twangboy requested changes
Still need a test for this

2026-01-14 12:51 UTC, msciciel commented
@twangboy @dwoz required test added. What could be done to fix failing checks?

2026-01-15 21:03 UTC, twangboy commented
Once the master branch is green, you'll need to rebase. That should take care of the failures.

2026-01-20 17:32 UTC, twangboy approved these changes

2026-02-27 08:19 UTC, msciciel commented
@dwoz any chances for a review?

2026-04-05 09:59 UTC, merged