macpackage module: expand user before mounting
saltstack/salt pull request #63894
Opened 2023-03-17 02:43 UTC by dschaller

### What does this PR do?
Changes the `macpackage` module to expand the user substitution in a dmg path before attempting to mount it.

### What issues does this PR fix or reference?
Fixes: currently, if you try to mount any dmg that has a shorthand for the users's home (e.g. `~`) `hdiutil attach` will fail.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-22 19:24 UTC, Ch3LL requested changes
This will require a changelog and test coverage

2023-03-28 00:50 UTC, dschaller commented
@Ch3LL thanks for the first pass. Updated and should be ready for another look when you have a minute

2023-04-05 20:10 UTC, Ch3LL requested changes

2023-04-05 20:10 UTC, Ch3LL commented on changelog/63905.fixed.md
> +added proper expanding of user directory when mounting a macpackage
63905 is your other PR, can you update this to 63894

2023-12-12 01:03 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

@dschaller Feel free to re-open this if you want to get it into a release.

2023-12-12 01:03 UTC, closed without merging