Add function `primary_group()` to `modules/pw_user.py` and `get_group_name()` to `utils/user.py`
saltstack/salt pull request #63899
Opened 2023-03-17 12:25 UTC by gluf-technik

### What does this PR do?
Adds the missing function `primary_group(name)` to `modules/pw_user.py` so one can use `salt['user.primary_group'](username)` on FreeBSD, too.
As functions from `salt.utils.user` are used anyway I've also added a function to get the name to a given group ID there, `salt.utils.user.get_group_name(gid)`.

### What issues does this PR fix or reference?
Fixes: No `user.primary_group()` on FreeBSD.

### Previous Behavior
```
kvm-master:~# salt -C "*" user.primary_group root
deb11-kvm-minion:
    root
alpine317-kvm-minion:
    root
[...]
obsd72-kvm-minion:
    wheel
fbsd13-kvm-minion:
    'user.primary_group' is not available.
```
### New Behavior
```
kvm-master:~# salt -C "G@os:FreeBSD" user.primary_group root
fbsd13-kvm-minion:
    wheel
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-12-12 01:10 UTC, dwoz commented
@gluf-technik Can you please add a simple test case for this?

2025-04-02 19:14 UTC, twangboy requested changes
This needs some tests for both the util and the module

2025-04-02 19:14 UTC, twangboy commented on salt/utils/user.py
> +def get_group_name(gid):
This function doesn't appear to be called by anything

2026-06-29 22:22 UTC, twangboy approved these changes

2026-07-03 11:57 UTC, merged