macpackage state: cleanup temporary mountpoint dir
saltstack/salt pull request #63905
Opened 2023-03-17 21:08 UTC by dschaller

### What does this PR do?
modifies the mackpackage state to remove the directory used as a temporary mountpoint for dmg installers

### What issues does this PR fix or reference?
Fixes: these directories are orphaned and bloat upon each run

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-22 19:18 UTC, Ch3LL requested changes
This will also require a changelog and test coverage.

2023-03-22 19:18 UTC, Ch3LL commented on salt/states/macpackage.py
> +            __salt__["cmd.run"]("rm -rf {}".format(mount_point))
Is there a specific reason why you are shelling out?
I would prefer to use something native to python such as  `pathlib` 's `rmdir` call if the directory is expected to be empty or `shutil.rmtree`.

2023-03-28 00:50 UTC, dschaller commented
@Ch3LL thanks for the first pass. Updated and should be ready for another look when you have a minute

2023-04-05 20:05 UTC, Ch3LL approved these changes

2023-04-05 20:05 UTC, merged