[3006.x] Clarifying the documentation for extension_modules configuration option
saltstack/salt pull request #63936
Opened 2023-03-23 17:48 UTC by garethgreenaway

### What does this PR do?
Clarifying the documentation for extension_modules configuration option

### What issues does this PR fix or reference?
Fixes: #63929 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-23 18:03 UTC, whytewolf commented on doc/ref/configuration/master.rst
> +Directory wehre custom modules are synced to. This directory can contain
typo in where

2023-03-23 19:18 UTC, whytewolf submitted a review, later dismissed

2023-03-24 07:57 UTC, s0undt3ch requested changes

2023-03-24 07:57 UTC, s0undt3ch commented on conf/master
> +# Directory where custom modules synced to This directory can contain
```suggestion
# Directory where custom modules sync to. This directory can contain
```
?

2023-03-24 08:46 UTC, onmeac commented on conf/master
> -# Like 'extension_modules' but can take an array of paths
May change this to `must be array of pahts` as I got this message during salt-master startup: `Config option 'module_dirs' with value /srv/salt/extmods has an invalid type of str, a list is required for this option`

2023-03-24 08:50 UTC, onmeac commented
I am not sure this fixes #63929 

Even when using `module_dirs` a salt-syndic process reports it cannot find the `get_load` function.

2023-03-25 09:35 UTC, s0undt3ch approved these changes

2023-03-25 09:36 UTC, merged