[3006.x] Fixes to state check_cmd
saltstack/salt pull request #63970
Opened 2023-03-27 21:39 UTC by garethgreenaway

### What does this PR do?
Need to handle the scenario when the check_cmd requisite is used with a state function when the state has a local check_cmd function but that function isn't used by that function.

### What issues does this PR fix or reference?
Fixes: #63948 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-27 21:44 UTC, whytewolf approved these changes, later dismissed

2023-03-27 22:54 UTC, whytewolf approved these changes, later dismissed

2023-03-28 13:10 UTC, Ch3LL requested changes

2023-03-28 13:10 UTC, Ch3LL commented on changelog/63948.fixed.md
> +Hhandle the scenario when the check_cmd requisite is used with a state function when the state has a local check_cmd function but that function isn't used by that function.
```suggestion
Handle the scenario when the check_cmd requisite is used with a state function when the state has a local check_cmd function but that function isn't used by that function.
```

2023-03-28 18:11 UTC, twangboy approved these changes

2023-03-28 18:29 UTC, whytewolf approved these changes

2023-03-28 22:57 UTC, merged