[WIP] Allow exclusion of cmd opts for requisites that run commands, eg. onlyif and unless
saltstack/salt pull request #63977
Opened 2023-03-28 01:22 UTC by garethgreenaway

### What does this PR do?
Initial pass at adding the ability to exclude arguments from a state that end up passed to cmd.retcode when onlyif or other requisites that call cmd.remote are used.

### What issues does this PR fix or reference?
Fixes: #63956 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-03-28 22:25 UTC, whytewolf submitted a review, later dismissed

2023-03-28 23:49 UTC, twangboy submitted a review, later dismissed

2023-04-05 17:23 UTC, Ch3LL requested changes

2023-04-05 17:23 UTC, Ch3LL commented on doc/ref/states/requisites.rst
> +.. versionchanged:: 3006
```suggestion
.. versionchanged:: 3006.0
```

2023-04-05 17:23 UTC, Ch3LL commented on doc/ref/states/requisites.rst
> +    By include ``shell`` in ``cmd_opts_exclude``, that parameter would not be
```suggestion
    By including ``shell`` in ``cmd_opts_exclude``, that parameter would not be
```

2023-04-05 17:23 UTC, Ch3LL commented on doc/ref/states/requisites.rst
> +.. versionchanged:: 3006
```suggestion
.. versionchanged:: 3006.0
```

2023-04-05 17:23 UTC, Ch3LL commented on doc/ref/states/requisites.rst
> +    By include ``shell`` in ``cmd_opts_exclude``, that parameter would not be
```suggestion
    By including ``shell`` in ``cmd_opts_exclude``, that parameter would not be
```

2023-04-05 17:23 UTC, Ch3LL commented on changelog/63956.fixed.md
> +Adding the ability to exclude arguments from a state that end up passed to cmd.retcode when requisites such as onlyif or unless are used.
is this a feature? should the extension be added instad of fixed?

2023-04-06 19:34 UTC, Ch3LL approved these changes

2023-04-11 15:55 UTC, twangboy approved these changes

2023-04-11 18:24 UTC, merged