migrate unit_modules_test_boto_dynamodb to pytest
saltstack/salt pull request #64005
Opened 2023-03-30 20:21 UTC by frogunder

### What does this PR do?

migrate unit_modules_test_boto_dynamodb to pytest

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-04 07:34 UTC, s0undt3ch requested changes
Function names should not be upper cased.

2023-04-04 07:34 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_boto_dynamodb.py
> +    return [{"Key": "foo", "Value": "bar"}, {"Key": "hello", "Value": "world"}]
```suggestion
@pytest.fixture
def arn():
    return "arn:aws:dynamodb:us-east-1:012345678901:table/my-table"


@pytest.fixture
def tags():
    return {"foo": "bar", "hello": "world"}


@pytest.fixture
def tags_as_list():
    return [{"Key": "foo", "Value": "bar"}, {"Key": "hello", "Value": "world"}]
```

2023-04-10 15:59 UTC, frogunder commented on tests/pytests/unit/modules/test_boto_dynamodb.py
> +    return [{"Key": "foo", "Value": "bar"}, {"Key": "hello", "Value": "world"}]
Thanks

2023-04-11 02:51 UTC, garethgreenaway approved these changes

2023-04-11 02:51 UTC, merged