[3006.x] Return Not Found when service is missing
saltstack/salt pull request #64001
Opened 2023-03-29 23:10 UTC by twangboy

### What does this PR do?
Fixes issue with the win_system module that returned a CommandExecutionError if the service was not found on the system. It now returns "Not Found".

Additionally, ports test_win_service to pytests.

### What issues does this PR fix or reference?
Fixes: #63577 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-03-30 06:56 UTC, s0undt3ch requested changes

2023-03-30 06:56 UTC, s0undt3ch commented on salt/modules/win_service.py
> +    .. versionchanged:: 3006
```suggestion
    .. versionchanged:: 3006.0
```

2023-03-30 14:16 UTC, twangboy commented on salt/modules/win_service.py
> +    .. versionchanged:: 3006
Fixed

2023-03-30 14:18 UTC, s0undt3ch requested changes
Sorry, should have also see this on the first review.
The issue will get linked, no need to prefix the changelog entry with it.

2023-03-30 14:18 UTC, s0undt3ch commented on changelog/63577.fixed.md
> +Issue #63577: ``service.status`` on Windows does no longer throws a
```suggestion
``service.status`` on Windows does no longer throws a
```

2023-04-01 00:18 UTC, twangboy commented on changelog/63577.fixed.md
> +Issue #63577: ``service.status`` on Windows does no longer throws a
Done

2023-04-01 08:29 UTC, s0undt3ch approved these changes

2023-04-01 08:30 UTC, merged