Fixed issue where dictionary key not exists relied on exception
saltstack/salt pull request #64018
Opened 2023-04-03 22:38 UTC by tgriffitts-ns

### What does this PR do?
It changes the old logic which uses an exception to check if a dictionary key does not exist.  This logic is no longer valid.  The new YAML loaded creates dicts with default implementations for keys if they do not exist.  An exception is no longer thrown if the key does not exist.  This patch simply checks if the key exists rather than depending on an exception being thrown if it does not.
### What issues does this PR fix or reference?
Fixes:
#64017
### Previous Behavior
Lots of bugs are causes by this old code.  It manifests when setting multiple salt grains under the same hierarchy in a single highstate
### New Behavior
All works as expected

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-03 22:49 UTC, tgriffitts-ns reviewed
An ignore whitespace changes diff on this patch shows much clearing what is changed:

```
@@ -850,8 +850,9 @@
                         return default
         else:
             try:
+                if each in ptr:
                 ptr = ptr[each]
-            except KeyError:
+                else:
                 # Late import to avoid circular import
                 import salt.utils.args

```

2023-04-07 00:01 UTC, tgriffitts-ns commented on salt/utils/data.py
An ignore-whitespace-changes diff on this delta shows much more clearly what is being changed:

```
@@ -850,8 +850,9 @@
                         return default
         else:
             try:
+                if each in ptr:
                 ptr = ptr[each]
-            except KeyError:
+                else:
                 # Late import to avoid circular import
                 import salt.utils.args

```

The whitespaces changes are to indent the existing block of lines, unchanged, which are now under the new `if each in ptr` statement.

2023-04-28 16:51 UTC, twangboy requested changes
Could you please write some tests and add a changelog.

2023-12-17 02:56 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

@tgriffitts-ns We can re-open this if you want to get it into a release.

2023-12-17 02:56 UTC, closed without merging