[WIP] User packages
saltstack/salt pull request #64025
Opened 2023-04-04 18:51 UTC by dwoz

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-08 19:59 UTC, s0undt3ch requested changes

2023-04-08 19:59 UTC, s0undt3ch commented on salt/__init__.py
> +    ] + sys.path
```suggestion
    sys.path.insert(0, str(sys.RELENV / "extras-{}.{}".format(*sys.version_info[:2])))
```
No extra lists created.

2023-04-08 19:59 UTC, s0undt3ch commented on salt/scripts.py
> +        new_env["PYTHONPATH"] = f"{extras}{sep}{env['PYTHONPATH']}"
```suggestion
        new_env["PYTHONPATH"] = f"{extras}{os.pathsep}{env['PYTHONPATH']}"
```

2023-04-08 19:59 UTC, s0undt3ch commented on salt/scripts.py
> +    extras = str(sys.RELENV / "extras-{}.{}".format(*sys.version_info[:2]))
```suggestion
    extras = str(sys.RELENV / "extras-{}.{}".format(*sys.version_info))
```
No slicing is actually required

2023-04-13 21:06 UTC, garethgreenaway approved these changes

2023-04-13 22:49 UTC, twangboy approved these changes

2023-04-13 23:11 UTC, Ch3LL approved these changes

2023-04-14 01:47 UTC, merged