change transport to channel
saltstack/salt pull request #64024
Opened 2023-04-04 16:22 UTC by Zpell82

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: transport  depreciation error 
also added som comments about parallel start limits 

### Merge requirements satisfied?
don't need changes to test or docs for this 
- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2023-04-08 20:08 UTC, dwoz approved these changes, later dismissed

2023-04-10 16:19 UTC, cmcmarrow requested changes
Thank you for the PR, looks like Pre-commit is failing. To install pre-commit ->https://pre-commit.com/ . Pre-commit should then auto run when you run `commit -a`.

2023-04-24 21:29 UTC, Zpell82 commented
> Thank you for the PR, looks like Pre-commit is failing. To install pre-commit ->https://pre-commit.com/ . Pre-commit should then auto run when `commit -a`.



honestly, no clue what that is, I'm going to need to read up on it

2023-05-15 07:29 UTC, Zpell82 commented
il close this one, its fixed in a another pr

2023-05-15 07:29 UTC, closed without merging