changelog
saltstack/salt pull request #64053
Opened 2023-04-12 01:03 UTC by cmcmarrow

### What does this PR do?
Improves salt testing

### What issues does this PR fix or reference?
Fixes: Allows contributors to get test results fast https://github.com/saltstack/salt/issues/63081

### Previous Behavior
* A PR would run fast test 2 times per run.

### New Behavior
* A PR does not run fast tests 2 times per run.
* People can add labels to change what tests run.

##
new test decorators `--no-fast-tests`, `--slow-tests`,  `--core-tests`, `--flaky-jail`
* `--fast-test`, default = true
Salt contributors never need to write this pytest decorator. A test will default to this decorator if the test does not have `speed_test`, `slow_test` and `core_test`. Most fast-test should take less then 5 secs to run.
* `--slow-tests` or `--run_slow`, default = false
A test that takes more than 5 secs to run.
 *  `--core-tests`, default = false
A test of a low level salt function that is rarely if ever is touched by contributors.
 * `--flaky-jail`, default = false
```
#EX
#@pytest.mark.core_test
#@pytest.mark.flaky_jail
@pytest.mark.slow_test
def test():
   ...
```
##
### Merge requirements satisfied?
- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-04-12 16:45 UTC, twangboy submitted a review, later dismissed

2023-04-12 17:22 UTC, garethgreenaway submitted a review, later dismissed

2023-04-13 00:23 UTC, twangboy submitted a review, later dismissed

2023-04-13 19:28 UTC, s0undt3ch requested changes

2023-04-13 19:32 UTC, s0undt3ch requested changes

2023-04-13 19:32 UTC, s0undt3ch commented on tests/pytests/functional/modules/state/requisites/test_listen.py
> +pytestmark = [pytest.mark.windows_whitelisted, pytest.mark.core_test]
```suggestion
pytestmark = [pytest.mark.windows_whitelisted, pytest.mark.core_test,]
```
Add the `,` comma above and let black format it when you try to commit.
The same for all `pytestmark` which are list and are on a single line.

2023-04-14 01:55 UTC, cmcmarrow commented on .github/workflows/test-action-macos.yml
> +          } >> "$GITHUB_OUTPUT"
no it does not

2023-04-14 07:46 UTC, s0undt3ch approved these changes, later dismissed

2023-04-14 17:34 UTC, s0undt3ch approved these changes

2023-04-15 02:07 UTC, garethgreenaway approved these changes

2023-04-16 01:19 UTC, merged