[master] Fix for issue 29835
saltstack/salt pull request #64131
Opened 2023-04-21 15:58 UTC by amalaguti

Quick fix for https://github.com/saltstack/salt/issues/29835,  added 'or not hasattr(minion_instance, "functions")' to allow a masterless minion to run highsate on startup when master_type set to disabled

### What does this PR do?
quick fix to generate a minion_instance object with proper data (functions, returners and executors).

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/29835

### Previous Behavior
Minion in masterless setup does not run highstate on startup, described in 
https://github.com/saltstack/salt/issues/29835

### New Behavior
Minion in masterless setup executes highstate on startup

2023-05-10 20:22 UTC, Ch3LL requested changes
This will require a changelog and test coverage. Would also like to get reviews from @s0undt3ch and @dwoz

2023-05-10 20:44 UTC, s0undt3ch reviewed
What would be the proper fix?
Since this is commented as a quick fix.

2023-05-11 20:14 UTC, amalaguti commented
Hi @s0undt3ch , I used the term quick fix due it was what worked for me but I don't know if it's the right place or way to fix it. I haven't tested it extensively to be 100% sure that it's not affecting anything else. Maybe there's some other alternative in the code to apply the fix.

2023-12-18 20:52 UTC, dmurphy18 commented
@amalaguti This PR has been sitting around since May 11, and needs a testcase for the PR.  No PR is accepted without tests exercising the code changes. It also needs updating to the current master branch and conflicts resolved.

Please resolve the conflicts and add a testcase, or have you lost interest in this PR, if so, please consider closing it.

2024-05-13 22:29 UTC, dmurphy18 commented
@amalaguti This has been wanting a testcase for some time. If you are not interested in this PR, please consider closing it, or if you will be providing a testcase, do you have a timeframe ?, otherwise this PR will be closed soon due to inactivity.

2024-05-14 11:18 UTC, amalaguti commented
@dmurphy18 Hey David, never contributed with a test case before, and not sure if is this the proper fix. The minion.py module is in particular complex. I'll guess I'll try first if this is still an issue in latest 3006.x

2024-05-14 12:21 UTC, amalaguti commented
@dmurphy18 I just tried this in 3006.8, the issue is still present and what I suggested as fix seems to deal with it. As I mentioned, I'm not sure if this is the proper fix, or just a patch/workaround that just hides the real issue, maybe some of you in core can verify it. And not sure how to create a proper test case for this either.

2024-12-18 20:47 UTC, closed without merging