Feature: salt.states.virt support on_crash, on_poweroff and on_lockfailure
saltstack/salt pull request #64166
Opened 2023-04-26 14:49 UTC by darshanip

Fixes #60699 

### What does this PR do?

### What issues does this PR fix or reference?
#60699 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-26 15:23 UTC, twangboy requested changes

2023-04-26 15:23 UTC, twangboy commented on salt/modules/virt.py
> +        .. versionadded:: ?
3007

2023-04-26 15:23 UTC, twangboy commented on salt/modules/virt.py
> +        This is specially useful when creating a virtual machine with an installation cdrom or
especially... you get the idea

2023-05-10 20:30 UTC, Ch3LL requested changes
Can you also add a changelog

2023-05-10 20:30 UTC, Ch3LL commented on salt/modules/virt.py
> +        .. versionadded:: 3007
Can you change all of the 3007 versions to `3007.0`

2024-08-02 18:55 UTC, closed without merging