set the osfullname grain on *BSD
saltstack/salt pull request #64189
Opened 2023-04-28 17:31 UTC by rnagy

### What does this PR do?
Fixes a runtime error because osfullname was not set on *BSD

### Previous Behavior
Traceback (most recent call last):
  File "/usr/local/bin/salt-master", line 33, in <module>
    sys.exit(load_entry_point('salt==3006.0', 'console_scripts', 'salt-master')())
  File "/usr/local/lib/python3.10/site-packages/salt/scripts.py", line 89, in salt_master
    master.start()
  File "/usr/local/lib/python3.10/site-packages/salt/cli/daemons.py", line 204, in start
    self.master.start()
  File "/usr/local/lib/python3.10/site-packages/salt/master.py", line 723, in start
    chan = salt.channel.server.PubServerChannel.factory(opts)
  File "/usr/local/lib/python3.10/site-packages/salt/channel/server.py", line 721, in factory
    return cls(opts, transport, presence_events=presence_events)
  File "/usr/local/lib/python3.10/site-packages/salt/channel/server.py", line 727, in __init__
    self.aes_funcs = salt.master.AESFuncs(self.opts)
  File "/usr/local/lib/python3.10/site-packages/salt/master.py", line 1233, in __init__
    self.mminion = salt.minion.MasterMinion(
  File "/usr/local/lib/python3.10/site-packages/salt/minion.py", line 974, in __init__
    self.opts = salt.config.mminion_config(
  File "/usr/local/lib/python3.10/site-packages/salt/config/__init__.py", line 2328, in mminion_config
    opts["grains"] = salt.loader.grains(opts)
  File "/usr/local/lib/python3.10/site-packages/salt/loader/__init__.py", line 1116, in grains
    ret = funcs[key]()
  File "/usr/local/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/salt/grains/core.py", line 2682, in os_data
    _osrelease_data(grains["os"], grains["osfullame"], grains["osrelease"])
KeyError: 'osfullame'

### New Behavior
working as expected

2023-04-30 08:19 UTC, s0undt3ch requested changes, later dismissed
Can you please add test coverage around the newly added keys to the grains dictionary?

2023-05-05 13:07 UTC, rnagy commented
> Can you please add test coverage around the newly added keys to the grains dictionary?

There is already test coverage for the osfullname grain.

2023-12-11 21:26 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

@rnagy Feel free to re-open this and add a changelog.

2025-12-10 10:27 UTC, rnagy commented
Can we reopen this please? I have prepped the missing changelog for this to move forward.

2025-12-10 14:27 UTC, twangboy commented
It will also need a test, please.
It also might be a good idea to get this into the 3006.x branch as it is an issue there as well. We try to fix bugs on the oldest supported branch where the bug exists.

2025-12-12 12:50 UTC, rnagy commented
The grains test is now ammended, but I cannot change the source of the PR to my own 3006.x branch.

2025-12-12 16:21 UTC, rnagy commented
rebased to 3006.x

2025-12-12 17:01 UTC, twangboy approved these changes

2025-12-13 22:58 UTC, merged