[WIP][3006.x] deltaproxy, scheduler and event bus fixes
saltstack/salt pull request #64182
Opened 2023-04-27 18:24 UTC by garethgreenaway

### What does this PR do?
Update all the scheduler functions to include a fire_event argument which will determine whether to fire the completion event onto the event bus.  This event is only used when these functions are called via the schedule execution modules.  Inside deltaproxy, then update all scheudle related functions to include fire_event=False, as the event bus is not available when these functions are called.

### What issues does this PR fix or reference?
Fixes:

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-04-28 13:45 UTC, s0undt3ch requested changes

2023-04-28 13:45 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +                )
```suggestion
                log.info(
                    "An exception occurred during initialization for %s, skipping: %s",
                    _id,
                    exc,
                )
```
The `str()` of an exception is sometimes verbose. It's probably more readable this way.

2023-04-28 13:45 UTC, s0undt3ch commented on salt/metaproxy/deltaproxy.py
> +                )
```suggestion
                log.info(
                    "An exception occurred during initialization for %s, skipping: %s",
                    _id,
                    exc,
                )
```

2023-04-30 08:24 UTC, s0undt3ch commented on tests/pytests/integration/proxy/conftest.py
> +    tempfiles = []
Why do we need this `tempfiles` variable?

2023-04-30 08:24 UTC, s0undt3ch commented on tests/pytests/integration/proxy/conftest.py
> +    tempfiles = [top_tempfile, controlproxy_tempfile]
And this one?

2023-05-02 16:14 UTC, garethgreenaway commented on changelog/64102.fixed.md
> +Inside deltaproxy, then update all scheudle related functions to include fire_event=False,
No.  That does look incomplete.  Thanks for catching that.

2023-05-02 16:28 UTC, s0undt3ch approved these changes

2023-05-02 19:57 UTC, merged