Remove requirement for Proxmox image property
saltstack/salt pull request #64197
Opened 2023-05-01 17:39 UTC by mthibaut

### What does this PR do?

The image parameter is currently required for creating Proxmox VMs, but it doesn't exist in the Proxmox API. Removing it.

### Commits signed with GPG?
No

2023-05-09 19:48 UTC, Ch3LL requested changes
This will require a changelog file.

2023-05-17 20:13 UTC, Ch3LL approved these changes

2023-05-17 20:47 UTC, twangboy approved these changes

2023-09-19 00:33 UTC, nicholasmhughes commented
No opinions about the PR itself since I'm not a Proxmox user.

However, I did support @mthibaut in moving the Proxmox code out to an extension around the time this PR went in. Going forward, all Proxmox code should live in that extension.

@I3urny , if the code in the extension requires modification per your suggestions, please open an issue at https://github.com/salt-extensions/saltext-proxmox/issues

Closing this PR as all future updates should occur in the extension.

2023-09-19 00:33 UTC, closed without merging