Refactor the `tools pkg repo` commands into a subdirectory
saltstack/salt pull request #64217
Opened 2023-05-03 01:00 UTC by MKLeb

### What does this PR do?
See title

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-05-03 15:43 UTC, MKLeb commented
Passing staging run: https://github.com/saltstack/salt/actions/runs/4867253303

2023-05-06 07:02 UTC, s0undt3ch approved these changes, later dismissed

2023-05-08 16:42 UTC, twangboy requested changes

2023-05-08 16:42 UTC, twangboy commented on tools/pkg/repo/__init__.py
> +These commands are used to build the pacakge repository files.
package

2023-05-08 16:42 UTC, twangboy commented on tools/pkg/repo/create.py
> +These commands are used to build the pacakge repository files.
package

2023-05-08 16:42 UTC, twangboy commented on tools/pkg/repo/publish.py
> +These commands are used to build the pacakge repository files.
package

2023-05-08 16:42 UTC, twangboy commented on tools/pkg/repo/publish.py
> +            "help": "The salt version for which to build the repository",
Is it building the repository here? Or publishing? This looks like a copy/paste from the `create.py`

2023-05-08 16:42 UTC, twangboy commented on tools/pkg/repo/publish.py
> +            "help": "The salt version for which to build the repository",
same here

2023-05-09 19:05 UTC, merged