Fix the password hashing function of mac_user.enable_auto_login
saltstack/salt pull request #64229
Opened 2023-05-03 19:09 UTC by pjcreath

### What does this PR do?
To start, this PR corrects the password hashing function and integration test.  Furthermore, it improves the hashing function to more closely match the behavior of macOS and adds unit tests for various boundary conditions.

### What issues does this PR fix or reference?
Fixes: 64226

### Merge requirements satisfied?
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2023-05-04 00:11 UTC, dwoz requested changes
Everything looks good here, but the new tests should be going into the pytests directory `/tests/pytest/unit/modules/test_mac_user.py`. You can use a parameterized pytest for `test_kcpass`

2023-05-04 01:11 UTC, pjcreath commented
Ah, I didn't know about that directory (or notice the test_mac_user.py there).  I'll revise and push soon.

2023-05-04 15:57 UTC, dmurphy18 approved these changes

2023-05-04 18:21 UTC, pjcreath commented
@dwoz The PR has been updated with the changes you requested.

2023-05-12 20:18 UTC, dwoz approved these changes

2023-05-15 20:46 UTC, merged