[master] Fix 64260: Add pki_check_files option to increase speed of listing large numbers of keys
saltstack/salt pull request #64262
Opened 2023-05-09 14:08 UTC by bluesliverx

### What does this PR do?
It adds a configuration option for skipping the `isfile` check when enumerating keys in various situations. This speeds up minion key listing significantly in certain situations.

### What issues does this PR fix or reference?
Fixes: #64260

### Previous Behavior
Minion key listing and salt master startup took minutes with 10k+ minions and key storage on a slow filesystem (e.g. NAS).

### New Behavior
Minion key listing is performant.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

2023-05-09 19:14 UTC, Ch3LL submitted a review, later dismissed

2023-05-09 19:14 UTC, Ch3LL commented
Looks good, but I would also like to get @dwoz 's review here

2023-05-12 20:27 UTC, dwoz commented
I'm not sure I agree with adding an option for this. I think it would make sense to have this (not checking `isfile`) as the default. In general, I think we should default to the more performant case and only add an option for the less performant case when absolutely necessary. In this particular case, I can't see a reason for the less performant state. Let's assume salt is the only thing managing the keys and in the rare situation we run into a bad one, warn, clean it up, and move on.

2023-05-12 20:28 UTC, dwoz requested changes
Requesting changes this comment: https://github.com/saltstack/salt/pull/64262#issuecomment-1546254431

2023-05-15 17:45 UTC, bluesliverx commented
@dwoz I have updated the commit to pull out the pki_check_files config option completely per your request. Can you take a look again?

2023-05-17 21:07 UTC, dwoz submitted a review, later dismissed

2023-05-24 18:41 UTC, bluesliverx commented
@Ch3LL @dwoz any ideas on why the tests are failing here? I can't see how my changes would break tests in that way honestly...

2023-05-30 19:05 UTC, Ch3LL commented
Some of these tests have been recently fixed. I'll go ahead and update the branch.

2023-06-07 20:19 UTC, Ch3LL approved these changes

2023-06-09 20:32 UTC, Ch3LL approved these changes

2023-06-09 20:33 UTC, merged