Allow opt-out of discard on disk format
saltstack/salt pull request #64310
Opened 2023-05-19 18:42 UTC by jseba

### What does this PR do?
This allows disk images to be formatted explicitly non-sparsely by enabling callers to disable the automatic discard of blocks during filesystem creation.

This is only supported for ext and xfs filesystems.

### What issues does this PR fix or reference?
Fixes:

Current behavior of formatting disk images results in e.g. a 20GB disk image being reduced to 44MB on the parent filesystem, which shows up as potential free space when other things are looking at the parent's disk usage. If the parent filesystem no longer has blocks to service the disk image's usage, it gets ENOSPC errors when it is not at 100% usage.

### New Behavior
Callers to `disk.format` and `blockdev.formatted` can specify `discard=False` for ext and xfs filesystems to disable their respective mkfs tools from doing a block discard during filesystem creation. This ensures the disk image is still reserving blocks on the parent filesystem for itself if it was created non-sparsely.

### Merge requirements satisfied?
- [X] Docs
- [ ] Changelog
- [X] Tests written/updated

### Commits signed with GPG?
No

2023-05-22 20:09 UTC, Ch3LL requested changes
This looks good, but just needs a changelog entry (https://docs.saltproject.io/en/latest/topics/development/changelog.html)

2023-06-30 17:19 UTC, jseba commented
I added the changelog entry, also went ahead and rebased on master

2023-08-01 20:04 UTC, Ch3LL submitted a review, later dismissed

2023-08-24 18:08 UTC, Ch3LL commented
Looks like there are related test failures that need to be resolved. Also can you ensure to rebase as there was recent test fixes merged in.

2023-08-30 19:30 UTC, Ch3LL approved these changes, later dismissed

2025-04-02 19:23 UTC, twangboy requested changes
This also needs to be rebased and conflicts resolved

2025-04-02 19:23 UTC, twangboy commented on salt/modules/disk.py
> +    discard
This needs a `.. version-added::` marker

2026-06-26 11:19 UTC, merged