Fix salt user login shell path in Debian packages
saltstack/salt pull request #64378
Opened 2023-05-28 23:50 UTC by clayoster

There are cases where /sbin/nologin doesn't exist on Debian servers. This will set /usr/sbin/nologin on new installs and update it on existing installs during the next upgrade as well.

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #64377

### Previous Behavior
In cases where /sbin/nologin doesn't exist on Debian servers, running ```salt-master -l debug``` will fail because the login shell is not available.

### New Behavior
The "salt" user login shell will be set to /usr/sbin/nologin which is the Debian default.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-05-29 05:42 UTC, s0undt3ch approved these changes, later dismissed

2023-05-29 16:29 UTC, clayoster commented
I noticed one of the CI checks was failing because there was no newline in the changelog file. Added commit 58dd833301e5bf93ecb7827879a3720ddef81f27 to fix that.

2023-05-30 18:53 UTC, Ch3LL approved these changes, later dismissed

2023-05-30 19:25 UTC, dwoz requested changes
We should have some kind of regression test for this.

2023-05-30 19:25 UTC, dwoz requested changes
We should have some kind of regression test for this.

2023-06-07 16:43 UTC, whytewolf submitted a review, later dismissed

2023-06-13 03:42 UTC, clayoster commented
> We should have some kind of regression test for this.

@dwoz - What would you like to see tested? I'm thinking of two options:
- Test that the user login shell path exists
- Test that running salt-master in debug mode is successful

2023-06-28 12:35 UTC, s0undt3ch submitted a review, later dismissed

2023-06-29 18:29 UTC, dwoz commented
> > We should have some kind of regression test for this.
> 
> @dwoz - What would you like to see tested? I'm thinking of two options:
> 
> * Test that the user login shell path exists
> * Test that running salt-master in debug mode is successful

Both would be great :D

2023-07-24 02:52 UTC, clayoster commented
> > > We should have some kind of regression test for this.
> > 
> > 
> > @dwoz - What would you like to see tested? I'm thinking of two options:
> > 
> > * Test that the user login shell path exists
> > * Test that running salt-master in debug mode is successful
> 
> Both would be great :D

Would this file be an appropriate place to test that the user shell path exists?
https://github.com/saltstack/salt/blob/master/pkg/tests/integration/test_salt_user.py

I'm considering adding this test to the file:
```python
def test_salt_user_shell(install_salt):
    """
    Test the salt user's login shell
    """
    proc = subprocess.run(
        ["getent", "passwd", "salt"], check=False, capture_output=True
    )
    assert proc.returncode == 0
    shell = ""
    try:
        shell = proc.stdout.decode().split(":")[6]
        shell_exists = shell.exists()
    except:
        pass
    assert shell_exists is True
```

However, after following the documentation for setting up a development environment I'm not able to successfully run the tests in that file (or any under pkg/tests/). Tests under the top-level tests/ directory run just fine. Are the tests under the pkg/ directory run differently? 

![Screenshot 2023-07-23 at 9 36 52 PM](https://github.com/saltstack/salt/assets/17052503/d44e8074-f480-4b58-b3ca-aed240b3b054)

2023-08-01 20:29 UTC, Ch3LL commented
Yes, they are ran differently. There is an open issue here: https://github.com/saltstack/salt/issues/64400 to document this process.

The nox session is: `test-pkgs-onedir`. So the pkg tests are run with `nox -e 'test-pkgs-onedir'`. You also need to ensure the Salt onedir package is in `artifacts` and the Salt system package (debian in this case) is in `pkgs/artifacts`. You can download these artifacts from teh github actions summary page.

You can just try adding the check to that file, because the package tests run on the PR.

2023-08-02 02:27 UTC, clayoster commented
@Ch3LL Thanks for the information! I have added the test to the PR.

2023-08-02 18:52 UTC, Ch3LL submitted a review, later dismissed

2023-08-15 17:35 UTC, Ch3LL commented
@clayoster we are trying to get everything merged in for the next 3006 bug fix release by this Wednesday. I did add the backport label to backport this but I don't think we will get this merged in time. Can you point this to 3006.x branch instead. The fixes for the package test failures that you are seeing are merged into that branch already.

2023-08-15 17:47 UTC, clayoster commented
@Ch3LL To accomplish that, do I just need to switch from the "master" branch to "3006.x" in the pull request?

<img width="679" alt="Screenshot 2023-08-15 at 12 43 54 PM" src="https://github.com/saltstack/salt/assets/17052503/752bb4d3-870d-4e51-863a-5195438d92fa">

2023-08-15 18:17 UTC, Ch3LL commented
If its possible. If there are merge conflicts it might require manual intervention

2023-08-15 19:32 UTC, Ch3LL commented
looks like something went wrong as the file count is very high on the PR now. You might have to rebase manually

2023-08-15 19:33 UTC, clayoster commented
@Ch3LL There were a few merge conflicts, but none of them were files that I had edited so I accepted the versions from the 3006.x branch.

2023-08-15 19:35 UTC, Ch3LL commented
Yeah unfortunately I think it needs to be done manually. I think what happened is its trying to bring in all of the commits from master on your branch into 3006.x.

2023-08-15 21:13 UTC, clayoster commented
@Ch3LL I think I have the issues sorted out. Changed files are back to what they should be now!

2023-08-16 06:57 UTC, garethgreenaway approved these changes

2023-08-16 08:08 UTC, s0undt3ch approved these changes

2023-08-16 12:49 UTC, merged

2023-09-24 20:00 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/65275">](https://github.com/saltstack/salt/pull/65275)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->