[freeze][3005] Fix branch tests
saltstack/salt pull request #64384
Opened 2023-05-30 15:38 UTC by Ch3LL

2023-05-30 17:25 UTC, Ch3LL commented
re-run full all

2023-05-31 18:31 UTC, Ch3LL commented
re-run full all

2023-06-01 18:58 UTC, Ch3LL commented
re-run full all

2023-06-02 18:46 UTC, Ch3LL commented
re-run full all

2023-06-02 20:44 UTC, Ch3LL commented
re-run full all

2023-06-05 16:45 UTC, Ch3LL commented
re-run full all

2023-06-05 16:48 UTC, s0undt3ch requested changes

2023-06-05 16:48 UTC, s0undt3ch commented on tests/pytests/scenarios/setup/test_install.py
> +        pytest.skip("Windows installs with statis requirements only")
```suggestion
        pytest.skip("Windows installs with static requirements only")
```

2023-06-07 15:42 UTC, Ch3LL commented
re-run full all

2023-06-08 14:49 UTC, garethgreenaway approved these changes

2023-06-08 15:44 UTC, dmurphy18 approved these changes

2023-06-08 16:06 UTC, s0undt3ch approved these changes

2023-06-08 16:07 UTC, merged