Replace libnacl with PyNaCl
saltstack/salt pull request #64389
Opened 2023-05-31 05:31 UTC by dwoz

### What does this PR do?

Replacing libnacl with PyNaCl

### What issues does this PR fix or reference?
Fixes: #64372 #64342

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-05-31 06:59 UTC, s0undt3ch requested changes

2023-05-31 06:59 UTC, s0undt3ch commented on salt/cloud/deploy/bootstrap-salt.sh
This needs to be done in the salt-bootstrap repo, not on Salt's.
Please remove the change.

2023-05-31 06:59 UTC, s0undt3ch commented on tests/unit/utils/test_nacl.py
Let's take the opportunity to migrate these tests to PyTest too.

2023-05-31 07:20 UTC, dwoz commented on salt/cloud/deploy/bootstrap-salt.sh
Why is this file here and what is it doing then?

2023-05-31 07:22 UTC, s0undt3ch commented on salt/cloud/deploy/bootstrap-salt.sh
Because that's what's used by salt-cloud to bootstrap VMs. We update this script whenever there are new releases of salt-bootstrap.

2023-07-20 17:09 UTC, dmurphy18 commented
Closing this in favor of https://github.com/saltstack/salt/pull/64415 which is the active PR for this issue

2023-07-20 17:09 UTC, closed without merging