Fix lgpo.get functions not returning all boolean values
saltstack/salt pull request #64414
Opened 2023-06-02 21:08 UTC by twangboy

### What does this PR do?
Fixes an issue with the LGPO execution module where not all boolean values were being returned. This was affecting the ``lgpo.set`` state that was expecting to see the boolean settings present, but were instead missing.

The problem had to do with the eTree Element object. Sometimes it is an Element with a length of 0 that would not be reported. Other times it is an Element with a length greater than 0, which would be reported.

### What issues does this PR fix or reference?
Fixes:
- https://github.com/saltstack/salt/issues/63296
- https://github.com/saltstack/salt/issues/63473

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-06-05 19:44 UTC, Ch3LL submitted a review, later dismissed

2023-06-06 17:05 UTC, s0undt3ch commented on tests/pytests/unit/modules/win_lgpo/test_get_policy.py
> +    win_lgpo.set_computer_policy(name=policy_name, setting="Not Configured")
```suggestion
    win_lgpo.set_computer_policy(name=policy_name, setting=copy.copy(policy_settings))
    try:
        yield policy_name, policy_settings
    finally:
        win_lgpo.set_computer_policy(name=policy_name, setting="Not Configured")
```
That last function should run even on errors, right?

2023-06-07 17:31 UTC, s0undt3ch requested changes

2023-06-07 17:31 UTC, s0undt3ch commented on tests/pytests/unit/modules/win_lgpo/test_get_policy.py
> +    }
```suggestion
@pytest.fixture
def configure_loader_modules(minion_opts):
    return {
        win_lgpo: {
            "__opts__": minion_opts,
            "__salt__": {
                "file.file_exists": win_file.file_exists,
                "file.makedirs": win_file.makedirs_,
            },
        },
        win_file: {
            "__utils__": {
                "dacl.set_perms": win_dacl.set_perms,
            },
        },
    }
```

2023-06-08 21:56 UTC, s0undt3ch commented on tests/pytests/unit/modules/win_lgpo/test_get_policy.py
> +    }
Yes, it does. There's also a `master_opts` fixture, in case you ever need one.

2023-06-10 07:02 UTC, s0undt3ch approved these changes

2023-06-10 07:02 UTC, merged

2024-10-22 21:28 UTC, bcowman commented
This PR has fixed some GPO Policies, but then I tried these 2 GPO polices using 3007.1.  They work the first time but fail subsequently.

"Interactive logon: Number of previous logons to cache (in case domain controller is not available)"
"Network access: Named Pipes that can be accessed anonymously"