Update chocolatey.py / Search for choco.exe
saltstack/salt pull request #64428
Opened 2023-06-06 16:24 UTC by TimHiCe

## chocolatey.exe was renamed to choco.exe by Chocolatey in Version 2.0.0

### What does this PR do?
Add the search for choco.exe to confirm that Chocolatey is installed.

### What issues does this PR fix or reference?
Fixes: #64427 

### Previous Behavior
The module only searched for chocolatey.exe

### New Behavior
The module now search for choco.exe, too.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-06-06 19:17 UTC, Ch3LL requested changes
This will require a changelog  and test coverage. This would probably be the best place for test coverage: tests/pytests/unit/modules/test_chocolatey.py

2023-06-08 19:14 UTC, whytewolf submitted a review, later dismissed

2023-06-08 19:30 UTC, Ch3LL approved these changes, later dismissed

2023-06-14 19:27 UTC, TimHiCe commented
@Ch3LL thanks for your info. I saw it, too. I'm very new to GitHub and specially Python. I hoped to solve the problem with a little change. Changing chocolatey.py was easy, but I struggled with the unit-test. So, sorry for some extra circles.

I downloaded a local copy of the repo. Now I'm setting up the test env to run the test locally and commit a better unit-test shortly. 

You can safely wait with approval until next commit.

2023-06-26 22:14 UTC, twangboy approved these changes, later dismissed

2023-06-27 19:52 UTC, Ch3LL commented
@TimHiCe just following up here. Any direction I can help with?

2023-06-29 06:57 UTC, TimHiCe commented
@Ch3LL thanks for your question. I'm working on to get the test suit locally running. That was a lot trial and error but meanwhile I'm getting closer to the goal.  I think I can come back the next days with a correct unit test or specific questions.

2023-06-30 07:25 UTC, s0undt3ch approved these changes

2023-06-30 23:30 UTC, twangboy approved these changes

2023-07-17 15:22 UTC, s0undt3ch approved these changes

2023-07-17 15:43 UTC, dmurphy18 approved these changes

2023-07-18 12:13 UTC, TimHiCe commented
Sorry for my late reply – I was some days on vacation.

@twangboy and @s0undt3ch Thank you for fixing the tests.
I spend a lot of hours to get the tests locally running but until now it doesn’t. But that’s a topic for another issue.

@Ch3LL Since I’m very new here, do I have to do more things on this pull request? Or it is OK how it is now?

2023-07-18 15:05 UTC, s0undt3ch approved these changes

2023-07-19 11:47 UTC, merged

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:59 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 12:02 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64672">](https://github.com/saltstack/salt/pull/64672)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->