Fix missing arg in acme state/module "dns_plugin_propagate_seconds"
saltstack/salt pull request #64441
Opened 2023-06-09 07:34 UTC by rittycat

### What does this PR do?
Adds the function arguments, and the cmd append required to make the documented argument 'dns_plugin_propagate_seconds` work
### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/63700

### Previous Behavior
The argument was documented but did not exist in code

### New Behavior
The relevant code was added for both state and module, and documented in state

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-06-09 19:29 UTC, Ch3LL requested changes
Thanks for this, would you mind also adding some test coverage to ensure this does not regress in the future.

2025-03-31 19:39 UTC, twangboy requested changes
This will also need some tests

2025-03-31 19:39 UTC, twangboy commented on salt/modules/acme.py
> +            cmd.append("--dns-cloudflare-propagation-seconds {}".format(dns_plugin_propagate_seconds))
Please add docs for this new parameter as well as a ``.. version-added::``. If you can, document the other parameters as well.

2025-03-31 19:39 UTC, twangboy commented on salt/states/acme.py
> +    :param dns_plugin_propagate_seconds: Number of seconds to wait for DNS propogations before asking ACME servers to verify the DNS record. (default 10)
Add a ``.. version-added::`` comment here as well.

2026-06-09 07:23 UTC, dwoz commented
Closing — the author's fork was deleted so a maintainer-side rebase isn't mechanically possible on this PR. Reopened as #69404 against `3006.x` (the oldest branch where `acme` still ships — the module was removed from master/3008.x in dc526dc2b17 community-extensions purge) with @rittycat preserved as commit author.

2026-06-09 07:23 UTC, closed without merging