fix salt-run exception issue to set exitcode to 1 instead of 0
saltstack/salt pull request #64479
Opened 2023-06-13 20:16 UTC by whytewolf

### What does this PR do?

This fix changes the flow of using salt-run to return the full return to the cli command, so that the cli can pick up the retcode of the command run. it also adjusts the exception so that an exception cause during the run will set the retcode to 1. 

### What issues does this PR fix or reference?
Fixes: #61173 

### Previous Behavior
exitcode is 0 if an exception happens in a runner module. 

### New Behavior
exitcode is the retcode. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

2023-06-20 19:24 UTC, Ch3LL requested changes
One small request

2023-06-20 19:24 UTC, Ch3LL commented on changelog/61173.fixed.md
> +fix fixed runner not having a proper exit code when runner modules throw an exception.
```suggestion
fixed runner not having a proper exit code when runner modules throw an exception.  
```

2023-06-20 19:36 UTC, Ch3LL approved these changes

2023-06-20 23:33 UTC, twangboy approved these changes

2023-06-21 21:07 UTC, dwoz approved these changes

2023-06-22 12:42 UTC, merged