[3006.x] Fix for assume role when used salt-cloud to create aws ec2
saltstack/salt pull request #64481
Opened 2023-06-14 14:57 UTC by tryfunc

### What does this PR do?
Fixes assuming role when used salt-cloud to create aws ec2.

### What issues does this PR fix or reference?
Fixes: #52501

### Previous Behavior
The repeated function call did not call the function assumed_creds, because in the case of a valid `__Expiration__` - active creds were returned (`return __AccessKeyId__, __SecretAccessKey__, __Token__`) and the function execution was interrupted.

### New Behavior
The expression has been changed.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-06-14 15:36 UTC, whytewolf submitted a review, later dismissed

2023-06-14 15:44 UTC, whytewolf commented
looks like pre-commit failed. just needs black ran on it for a commit. Please update and that should take care of the issue.

2023-06-14 18:13 UTC, Ch3LL requested changes

2023-06-14 18:13 UTC, Ch3LL commented on tests/pytests/unit/utils/test_aws.py
> +        )
Would be good to also assert that `get_metadata("meta-data/iam/security-credentials/")` was called the first time and not the second.

2023-06-14 18:57 UTC, whytewolf approved these changes, later dismissed

2023-06-14 18:58 UTC, Ch3LL approved these changes, later dismissed

2023-06-15 17:26 UTC, Ch3LL approved these changes

2023-06-15 17:27 UTC, Ch3LL commented
Thanks for this. This is ready to go, the package tests failing will be fixed with this https://github.com/saltstack/salt/pull/64484 . Once that's merged we can rebase this PR and they should start passing.

2023-06-20 14:08 UTC, Ch3LL approved these changes

2023-06-21 19:54 UTC, Ch3LL approved these changes

2023-06-22 19:19 UTC, Ch3LL approved these changes

2023-06-26 19:52 UTC, Ch3LL approved these changes

2023-06-26 20:29 UTC, whytewolf approved these changes

2023-07-06 19:12 UTC, Ch3LL approved these changes

2023-08-02 18:53 UTC, Ch3LL approved these changes

2023-08-14 19:38 UTC, Ch3LL approved these changes

2023-08-16 01:08 UTC, merged