WIP: fix: file.directory children only kwarg did not work
saltstack/salt pull request #64497
Opened 2023-06-17 05:06 UTC by raddessi

### What does this PR do?
This fixes the behavior of the `children_only` kwarg on the file.directory state to perform as documented.

### What issues does this PR fix or reference?
Fixes: n/a

### Previous Behavior
The root directory would still be modified even when `children_only` is set to True

### New Behavior
Now it is not modified when requested.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
  - Not needed since we are bringing functionality inline with current docs.
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
  - Not yet, I will get it added
- [ ] Tests written/updated
  - Not yet, I will get to this and then unmark this as WIP

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-06-17 18:05 UTC, MKLeb commented
@raddessi Looks great! I see you're planning on adding a changelog and tests, so once those are in we can review this :)

2023-06-20 00:14 UTC, raddessi commented
I hope not having an issue is OK. I used the PR number as stated in the changelog docs.

2023-06-20 16:03 UTC, raddessi commented
Hmm  I clearly do not understand how file mode syntax works with the new pytest suite utils.. any insight would be helpful.

2023-06-22 17:21 UTC, whytewolf approved these changes, later dismissed

2023-06-22 18:04 UTC, dmurphy18 submitted a review, later dismissed

2023-09-23 04:44 UTC, raddessi commented
@MKLeb when you have time this has been sitting a while, can you let me  know if it needs changes?

2023-09-23 14:22 UTC, MKLeb approved these changes, later dismissed

2023-09-24 11:43 UTC, s0undt3ch approved these changes, later dismissed

2023-09-27 01:54 UTC, twangboy approved these changes, later dismissed

2023-09-27 20:08 UTC, Ch3LL submitted a review, later dismissed

2023-11-21 17:13 UTC, s0undt3ch requested changes

2023-11-21 17:13 UTC, s0undt3ch commented on tests/pytests/functional/states/file/test_directory.py
> +        pytest.skip("Skipped on windows")
```suggestion
@pytest.mark.skip_on_windows
def test_directory_children_only(file, tmp_path):
    """
    file.directory with children_only=True
    """
```

2023-11-22 05:21 UTC, raddessi commented
Test failures seem to be unrelated

2023-11-22 12:45 UTC, s0undt3ch approved these changes

2023-11-22 12:46 UTC, merged