Add syncing of custom ssh wrappers
saltstack/salt pull request #64518
Opened 2023-06-21 19:23 UTC by lkubb

### What does this PR do?
Adds `sync_wrapper` to the `saltutil` runner and execution modules.
From what I can tell, the loader is already configured to load them.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/45450

### Previous Behavior
`<cache_dir>/extmods/wrapper` is respected by the loader, but cannot be synced from the fileserver

### New Behavior
`<cache_dir>/extmods/wrapper` can be synced

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-06-22 19:30 UTC, Ch3LL requested changes
Could you add a test that syncs a custom salt-ssh wraper and then salt-ssh actually uses that wrapper?

Also, this is great, thanks once again.

2023-06-22 19:30 UTC, Ch3LL commented on salt/runners/saltutil.py
> +    .. versionadded:: 3000
```suggestion
    .. versionadded:: 3007.0
```

2023-06-22 19:30 UTC, Ch3LL commented on salt/states/saltutil.py
> +    Performs the same task as saltutil.sync_wrapper module
```suggestion
    .. versionadded:: 3007.0
    
    Performs the same task as saltutil.sync_wrapper module
```

2023-06-22 22:05 UTC, lkubb commented
Whoops, I was a bit too hasty in creating this PR, sorry. It was probably the surprise to find that 95% of the functionality was there already...

`versionadded` is now corrected and I added a test for syncing + usage. It works as expected on my machine, yay.

2023-06-26 19:40 UTC, Ch3LL approved these changes

2023-06-26 19:52 UTC, whytewolf approved these changes

2023-06-26 19:53 UTC, merged