[WIP] 3006 debian12 support
saltstack/salt pull request #64544
Opened 2023-06-26 08:41 UTC by lastmikoi

### What does this PR do?

This work in progress PR tries to add package building for Debian 12, as, while official support for Debian 12 won't happen until 3007, some of us would still like to use onedir Salt packages for that target.

### What issues does this PR fix or reference?
References: https://github.com/saltstack/salt/issues/64223 (doesn't fix)

### Previous Behavior
No Salt packages delivered for Debian 12

### New Behavior
Salt packages delivered for Debian 12

### Merge requirements satisfied?
Work in progress PR that I need to submit in order to make the CI run (I don't have access to the selfhosted github action CI nodes)
- [:no_entry_sign:] Docs
- [:no_entry_sign:] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [:no_entry_sign:] Tests written/updated

### Commits signed with GPG?
Yes

2023-06-26 10:01 UTC, lastmikoi commented
Pinging @s0undt3ch as they seem to be codeowner of `cicd/golden-images.json`: Hi ! It seems that the CI Image for Debian 12 is missing from what appears to be a selfhosted set of CI runners running on AWS (I'm completely unfamiliar with Salt's CI setup, so I may be wildly mistaken). Is there anything I can do on my end to help out with getting that image added and my pipeline unblocked ?

2023-06-27 12:55 UTC, lastmikoi commented
Looks like it's been taken care of yesterday already :sparkles: https://github.com/saltstack/salt-jenkins/pull/1811#event-9644838919 I've updated my PR accordingly.

2023-06-28 11:06 UTC, s0undt3ch commented
> Pinging @s0undt3ch as they seem to be codeowner of `cicd/golden-images.json`: Hi ! It seems that the CI Image for Debian 12 is missing from what appears to be a selfhosted set of CI runners running on AWS (I'm completely unfamiliar with Salt's CI setup, so I may be wildly mistaken). Is there anything I can do on my end to help out with getting that image added and my pipeline unblocked ?

https://github.com/saltstack/salt-jenkins/pull/1811

2023-06-28 11:11 UTC, s0undt3ch requested changes

2023-06-28 11:11 UTC, s0undt3ch commented on salt/cloud/deploy/bootstrap-salt.sh
> +        elif [ "$INPUT_VERSION" = "bookworm/sid" ]; then
These changes must be done against the salt-bootstrap repository, not salt.

2023-07-03 08:54 UTC, lastmikoi commented on .github/workflows/templates/test-pkg-repo-downloads.yml.jinja
> +                               ("debian-12", "Debian 12", "x86_64", "package"),
Aye, that's what I saw from the documentation that new OS support for LTS releases won't happen, but we're in a special predicament here, there's no Salt package for Debian12 provided by the OS, and there's no Salt package for Debian12 provided by saltproject. I can see that progress is being made for 3007.x, but I'm in the middle of an Ansible VS Saltstack evaluation pass at my dayjob and I'd love to be able to just use 3006.x "as-is" on a Debian12 environment, without any specific OS support.

So, how do I get Debian12 packages ? The whole process being automated and, frankly, quite difficult to reproduce locally, I figured that using the existing CI was the lowest hanging fruit, but if adding CI for debian12 is too much of a burden on 3006.x maintainers, I'll gladly take an alternative. I just want a few `.deb` files.

2023-07-03 16:41 UTC, s0undt3ch commented on .github/workflows/templates/test-pkg-repo-downloads.yml.jinja
> +                               ("debian-12", "Debian 12", "x86_64", "package"),
Have you tried the Debian 11 Debs?

2023-10-09 19:49 UTC, ScriptAutomate commented
This PR is being superseded by:
- https://github.com/saltstack/salt/pull/65116

Closing.

2023-10-09 19:49 UTC, closed without merging