Fix detection of Salt codename by "salt_version" execution module.
saltstack/salt pull request #64554
Opened 2023-06-27 12:08 UTC by meaksh

### What does this PR do?

This PR fixes an issue and some kind of mess we have around Salt version detection and codename resolution.

Currently, the codename resolution (`salt_version.get_release_number` and `salt_version.equal`) seems broken in Salt:

```console
# pip3 install salt
Collecting salt
  Downloading salt-3006.1.tar.gz (20.4 MB)
[...]
Successfully installed Jinja2-3.0.3 MarkupSafe-2.0.1 PyYAML-6.0 certifi-2023.5.7 charset-normalizer-2.0.12 contextvars-2.4 distro-1.8.0 idna-3.4 immutables-0.19 jmespath-0.10.0 looseversion-1.2.0 msgpack-1.0.5 psutil-5.9.5 pycryptodomex-3.18.0 pyzmq-25.0.2 requests-2.27.1 salt-3006.1 typing-extensions-4.1.1 urllib3-1.26.16

# salt-call --version
salt-call 3006.1

# salt-call --local grains.get saltversion
local:
    3006.1

# salt-call --local salt_version.equal Sulfur
local:
    False

# salt-call --local salt_version.get_release_number Sulfur
local:
    No version assigned.
```

### Previous Behavior
As mentioned above, the `salt_version.get_release_number` and `salt_version.equal` execution module functions (and probably others) are not working fine.

Other codenames seems working fine:

```console
# salt-call --local salt_version.get_release_number Neon
local:
    3000
```

After some debugging, I've noticed the following situations:
- Codename definitions for Salt >= 3006 seems wrong at `salt/version.py`, as they map the version codename to the `300X.0` release but not to the entire `300X`. This causes problems on codename detection.
- There seems to be a mess with the usage of `can_have_dot_zero` function that causes wrong a detection of Salt versions.

### New Behavior
Salt version resolution works fine now and versions are detected as expected:

```console
# salt-call --local salt_version.get_release_number Sulfur
local:
    3006

# salt-call --local salt_version.equal Sulfur
local:
    True
```

### Merge requirements satisfied?
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-06-28 12:17 UTC, s0undt3ch approved these changes

2023-06-28 12:17 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_salt_version.py
> +        if sv.new_version(major=v[0]):
So, from 3006 onward, the `.0` must always be present, the existing logic was correct, but SaltStackVersion is now reporting it differently?

2023-06-28 12:17 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_salt_version.py
> +    assert salt_version.get_release_number("Sulfur") == "3006"
```suggestion
    assert salt_version.get_release_number("Sulfur") == "3006.0"
```
In theory, this should be the expected outcome... Although, all 3006 minor versions are Sulfur versions...

2023-06-28 12:17 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_salt_version.py
> +        if sv.new_version(major=v[0]):
Ok, I see why this had to change.
And it looks like it hasn't broken other functionality.
```
❯ python
Python 3.10.2 (main, Nov 15 2022, 11:41:37) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.version
>>> v = salt.version.SaltStackVersion.parse("3006")
>>> str(v)
'3006.0'
>>> v.info
v.info
>>> v.info
(3006, 0)
>>> v = salt.version.SaltStackVersion.parse("3005")
>>> str(v)
'3005'
>>> v.info
(3005,)
>>>
```

2023-06-28 12:18 UTC, s0undt3ch requested changes

2023-06-28 12:18 UTC, s0undt3ch commented on changelog/64554.fixed.md
This file should be named `64306.fixed.md`

2023-06-28 12:24 UTC, meaksh commented on changelog/64554.fixed.md
Done. Thanks for the review!

2023-06-28 12:25 UTC, s0undt3ch commented
@meaksh since you've fixed most of the issues, could you also add a test case for the error shown in https://github.com/saltstack/salt/issues/64306 ?
Let me know if you don't have the bandwidth and I can push it to your PR.

2023-06-28 12:26 UTC, meaksh commented
@s0undt3ch ok, I'll give it a try to implement a test that covers the error shown at https://github.com/saltstack/salt/issues/64306

2023-06-28 13:15 UTC, meaksh commented
@s0undt3ch I've added the mentioned test.

I realized `salt_version.less_than` and others are expecting to get a "codename" string as input, and not really a version number (as it was done in https://github.com/saltstack/salt/issues/64306).

I've just adjusted to the code to raise a `CommandExecutionError` instead.

2023-06-28 13:19 UTC, s0undt3ch commented
> @s0undt3ch I've added the mentioned test.
> 
> I realized `salt_version.less_than` and others are expecting to get a "codename" string as input, and not really a version number (as it was done in #64306).
> 
> I've just adjusted to the code to raise a `CommandExecutionError` instead.

Thanks!

2023-06-28 13:19 UTC, s0undt3ch submitted a review, later dismissed

2023-06-28 18:20 UTC, Ch3LL requested changes
The documentation for `get_release_number` states it should return `MAJOR.PATCH` but your PR is only returning `MAJOR` for 3006 which now does include a patch in the version. The expected behavior seems to be to return `3006.0` instead of `3006`.

2023-06-28 19:17 UTC, MKLeb submitted a review, later dismissed

2023-06-28 20:31 UTC, ggiesen commented
If the intention is to not 

> > @s0undt3ch I've added the mentioned test.
> > I realized `salt_version.less_than` and others are expecting to get a "codename" string as input, and not really a version number (as it was done in #64306).
> > I've just adjusted to the code to raise a `CommandExecutionError` instead.
> 
> Thanks!

If the intention is not to fix this, then please update the example in the docs:

https://github.com/saltstack/salt/blob/9aeed74e96542558fc473a24d6b38add4a62b65b/salt/modules/salt_version.py#L18-L29

2023-06-29 09:15 UTC, meaksh commented
@Ch3LL as mentioned, the documentation for `salt_version` is now upgraded to reflect the expected behavior.

2023-06-30 16:27 UTC, s0undt3ch approved these changes

2023-07-01 07:46 UTC, merged

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-07-19 11:58 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/64671">](https://github.com/saltstack/salt/pull/64671)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->