Deprecated in favor of Salt Extension Decorator
saltstack/salt pull request #64569
Opened 2023-06-28 18:14 UTC by garethgreenaway

### What does this PR do?
Adding a new decorator to indicate when a module is deprecated in favor of a Salt extension

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-06-28 18:32 UTC, Ch3LL submitted a review, later dismissed
We need to document this so users know how to properly deprecate modules in favor of Salt extensions. I'm approving this as I'm okay if we do this in a separate PR as it might require more work since we don't have any documentation related to writing  a Salt extension currently that I'm aware of.

2023-06-28 18:44 UTC, dmurphy18 approved these changes, later dismissed
What about modules already with deprecation since moved to extensions in 3006, for example the ESXi module and it's cohorts, should they stay unchanged or be updated once this is merged ?

2023-06-28 19:34 UTC, s0undt3ch submitted a review, later dismissed

2023-06-28 19:52 UTC, s0undt3ch requested changes

2023-06-28 19:52 UTC, s0undt3ch commented on doc/topics/development/salt_extensions.rst
> +the new extension can be found.
```suggestion
should include the version of Salt that the module will be removed(should be 2 major versions from the current release. For example, the current Salt release is 3100, the deprecation version should be set to 3102), the name of the
collection of modules that are being deprecated, and the URL where the source for
the new extension can be found.
```

2023-06-28 19:54 UTC, Ch3LL submitted a review, later dismissed

2023-06-28 20:43 UTC, twangboy requested changes

2023-06-28 20:43 UTC, twangboy commented on doc/topics/development/salt_extensions.rst
> +The criteria to determine which category to place modules in will follow these rules.
Add a colon
```
...will follow these rules:
```

2023-06-28 20:43 UTC, twangboy commented on doc/topics/development/salt_extensions.rst
> +next major release. For example, the next major release of Salt is 3100, the
For example, `if` the next major release...

2023-06-28 21:53 UTC, dmurphy18 submitted a review, later dismissed

2023-06-28 22:09 UTC, s0undt3ch approved these changes, later dismissed

2023-06-29 15:12 UTC, dmurphy18 submitted a review, later dismissed

2023-06-29 17:25 UTC, s0undt3ch submitted a review, later dismissed

2023-06-29 17:25 UTC, s0undt3ch commented on tests/pytests/functional/utils/test_extension_deprecation.py
> +    """
yeah, we need to update this docstring

2023-06-29 18:04 UTC, I3urny requested changes
Just needs a minor fix in the documentation. Looks good otherwise.

2023-06-29 18:17 UTC, I3urny approved these changes

2023-06-29 18:39 UTC, dmurphy18 approved these changes

2023-06-30 16:00 UTC, s0undt3ch approved these changes

2023-06-30 18:23 UTC, twangboy approved these changes

2023-06-30 19:52 UTC, Ch3LL approved these changes

2023-06-30 19:53 UTC, merged