[master] Fix Flaky LazyLoaderRefreshFileMappingTest
saltstack/salt pull request #64568
Opened 2023-06-28 15:10 UTC by cianyleow

### What does this PR do?
Move creation of the lock to a private method to isolate mocking behaviour from main threading library.

### What issues does this PR fix or reference?
Fixes: [64567](https://github.com/saltstack/salt/issues/64567)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
- [N/A] Docs
- [YES] Changelog - `64567.fixed.md`
- [YES] Tests written/updated

### Commits signed with GPG?
**Yes**/No

2023-06-28 18:43 UTC, Ch3LL submitted a review, later dismissed
This looks good but I certainly want to get @dwoz and @s0undt3ch 's review here

2023-06-28 19:37 UTC, s0undt3ch requested changes

2023-06-28 19:37 UTC, s0undt3ch commented on tests/unit/test_loader.py
> +        loader = self.__init_loader()
```suggestion
        with patch.object(self.LOADER_CLASS, "_get_lock", MagicMock(return_value=lock_mock)):
            loader = self.__init_loader()
```

2023-06-28 19:37 UTC, s0undt3ch commented on tests/unit/test_loader.py
> +        loader = self.__init_loader()
This is untested code, but we need to use `patch` to revert the changes after the test completes

2023-06-29 17:37 UTC, s0undt3ch approved these changes

2023-07-03 13:15 UTC, cianyleow commented
@s0undt3ch thanks for the speedy reviews! I think I fixed the CI issues I noticed the other day, but will need a re-run to confirm

2023-07-03 16:37 UTC, s0undt3ch approved these changes

2023-07-05 11:45 UTC, cianyleow commented
@s0undt3ch I think the failing CI checks are unrelated (I see the same Windows tests are failing on [`master`](https://github.com/saltstack/salt/actions/runs/5447608111/jobs/9911153644) for the same reason). Is there anything I can do to help fix them to get this merged?

2023-07-12 09:03 UTC, cianyleow commented
Sorry to keep bugging @s0undt3ch, could I get a re-run of my CI? I think the previous Windows issue is resolved (and I've rebased), so it pass this time!

2023-07-12 14:02 UTC, s0undt3ch approved these changes

2023-07-25 11:01 UTC, cianyleow commented
Hi again @s0undt3ch, I realised this never got merged and now its out of date again, so I've rebased on the latest `master` and force-pushed to clear up the history. Would you be able to run CI again on it please?

2023-08-02 19:09 UTC, Ch3LL approved these changes

2023-08-11 08:58 UTC, cianyleow commented
Hey @Ch3LL not sure on the best way to get this merged as I've been in this cycle of either having failing tests or an out of date branch - would you like me to rebase on the latest `master` so that it can be re-run? The failing tests are related to `Windows 2016` which look similar to other ones I've had flake on me in the past.

2023-08-18 20:16 UTC, Ch3LL commented
Apologies, I have the 3007.0 label on this so it's on my radar. We are currently waiting on a merge forward for fixing all the tests. I'll make sure to follow up here to update the branch once that is merged into master.

2023-08-25 13:12 UTC, merged