Fixed: Configuration value '__utils__' needs to be set when creating …
saltstack/salt pull request #64578
Opened 2023-06-29 16:08 UTC by KarlAustin

…OpenNebula VM

### What does this PR do?
It fixes an issue when creating VMs for OpenNebula Cloud driver.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64577

### Previous Behavior
VM creation fails with error

### New Behavior
VM creation proceeds

### Merge requirements satisfied?
- [n/a] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [see below] Tests written/updated

Currently there is no test existing for create() for the OpenNebula driver.  This situation has not changed.

### Commits signed with GPG?
No

2023-06-30 18:18 UTC, twangboy approved these changes, later dismissed

2023-06-30 18:52 UTC, dmurphy18 submitted a review, later dismissed

2023-06-30 18:57 UTC, twangboy commented
@KarlAustin Would you mind fixing the pre-commit failures?

2023-06-30 19:04 UTC, garethgreenaway approved these changes, later dismissed

2023-06-30 22:09 UTC, KarlAustin commented
> @KarlAustin Would you mind fixing the pre-commit failures?

Assuming I'm reading it right, these all look to be related to string formatting in code I've not touched? 

More than willing to bring them up to date in a separate PR though, which would seem to make sense as they aren't really related to this issue.

2023-07-05 17:11 UTC, nicholasmhughes commented
@KarlAustin the string formatting is due to recent changes in the pyupgrade pre-commit check. If you merge the latest master branch and `pre-commit run --files [files you've changed]`, the pre-commit checks will take care of the changes for you. Then, just push the changed files up and everything will be happy.

2023-07-14 15:44 UTC, twangboy approved these changes

2023-08-18 20:10 UTC, Ch3LL requested changes

2023-08-18 20:10 UTC, Ch3LL commented on salt/cloud/clouds/opennebula.py
> +        data = salt.utils.cloud.wait_for_ip(
I'm not seeing `salt.utils.cloud` imported into this module

2023-10-17 20:03 UTC, Ch3LL commented
@KarlAustin did you see my review comment?

2023-12-16 21:54 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

@KarlAustin If you'd like to get this change into a release please re-open it after re-basing.

2023-12-16 21:54 UTC, closed without merging