unflip --no-fast
saltstack/salt pull request #64581
Opened 2023-06-29 23:41 UTC by cmcmarrow

### What does this PR do?
`--no-fast` was flip in https://github.com/saltstack/salt/pull/64386. Because https://github.com/saltstack/salt/pull/64386/files/79cd8696df48782ce4103e6b70895207a99d729f

Test need to be written to avoid another flip.

### What issues does this PR fix or reference?
Fixes: `--no-fast`

- [ ] Tests:

### Commits signed with GPG?
Yes

2023-06-29 23:49 UTC, s0undt3ch requested changes

2023-06-29 23:49 UTC, s0undt3ch commented on tests/conftest.py
> +        if test_group_count == 0 and not item.config.getoption("--no-fast-tests"):
This is not the fix.
The fix is:

```diff
   test_selection_group.addoption(
        "--no-fast",
        "--no-fast-tests",
        dest="fast",
        action="store_true",
        default=False,
        help="Don't run salt-fast tests. Default: %(default)s",
    )

2023-06-29 23:59 UTC, cmcmarrow commented on tests/conftest.py
> +        if test_group_count == 0 and not item.config.getoption("--no-fast-tests"):
all ready did

2023-06-30 03:45 UTC, twangboy approved these changes

2023-06-30 07:21 UTC, s0undt3ch approved these changes

2023-06-30 07:21 UTC, merged