Migrate service integration tests
saltstack/salt pull request #64589
Opened 2023-06-30 20:31 UTC by MKLeb

### What does this PR do?
See title.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-07-01 07:35 UTC, s0undt3ch reviewed
Do these tests really need a master and minion running?

Could they potentially be turned into functional tests?

2023-07-13 19:15 UTC, MKLeb commented
> Do these tests really need a master and minion running?
> 
> Could they potentially be turned into functional tests?

I have migrated them to functional tests.  I was thinking the same thing when doing the original migration.

2023-07-14 15:42 UTC, twangboy approved these changes, later dismissed

2023-07-16 09:20 UTC, s0undt3ch requested changes

2023-07-16 09:20 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_service.py
> +            modules.service.disable(service_name)
```suggestion
def setup_service(service_name, modules):
    pre_srv_status = modules.service.status(service_name)
    pre_srv_enabled = service_name in modules.service.get_enabled()

    try:
        yield pre_srv_status
    finally:
        post_srv_status = modules.service.status(service_name)
        post_srv_enabled = service_name in modules.service.get_enabled()

        if post_srv_status != pre_srv_status:
            if pre_srv_status:
                modules.service.enable(service_name)
            else:
                modules.service.disable(service_name)

        if post_srv_enabled != pre_srv_enabled:
            if pre_srv_enabled:
                modules.service.enable(service_name)
            else:
                modules.service.disable(service_name)
```
We always want the `finally` block to run, even if tests fail.

2023-07-16 09:20 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_service.py
> +@pytest.mark.flaky(max_runs=4)
```suggestion
@pytest.mark.flaky(max_runs=4)
```
Are these tests still flaky?

2023-07-16 09:20 UTC, s0undt3ch commented on tests/pytests/functional/states/test_service.py
> +        modules.service.disable(service_name)
```suggestion
@pytest.fixture(autouse=True)
def setup_service(service_name, modules):
    pre_srv_enabled = True if service_name in modules.service.get_enabled() else False
    post_srv_disable = False
    if not pre_srv_enabled:
        modules.service.enable(service_name)
        post_srv_disable = True
    try:
        yield post_srv_disable
    finally:
        if post_srv_disable:
            modules.service.disable(service_name)
```

2023-07-20 14:15 UTC, s0undt3ch approved these changes

2023-07-20 14:16 UTC, merged