[master] Allow salt-call arguments --file-root, --pillar-root and --states-dir to be specified multiple times
saltstack/salt pull request #64621
Opened 2023-07-10 17:04 UTC by martijnkruiten

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #64486

### Previous Behavior
The `salt-call` arguments `--file-root`, `--pillar-root` and `--states-dir` can each be specified only once.

### New Behavior
The `salt-call` arguments `--file-root`, `--pillar-root` and `--states-dir` can each be specified multiple times.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-10-03 16:01 UTC, MKLeb commented
Hi @martijnkruiten , I see you have a test for multiple file roots (I commented on that one).  We would really like to see full test coverage for this PR, so are you able to add a similar style of test for multiple pillar roots and state directories?

2023-10-10 13:19 UTC, martijnkruiten commented on tests/pytests/integration/cli/test_salt_call.py
> +            str(salt_master.state_tree.prod.paths[0]),
The `prod` and `base` file trees point to two separate locations:

```
/tmp/stsuite/master-4fB2Zt/state-tree/base
/tmp/stsuite/master-4fB2Zt/state-tree/prod
```

I've also verified that with

```
assert salt_master.state_tree.base.paths[0] != salt_master.state_tree.prod.paths[0]
```

2023-10-10 13:21 UTC, martijnkruiten commented
Hi @MKLeb, I'll have a look. I seem to recall that I didn't add them because these options weren't included in the test suite to begin with.

2023-10-10 16:07 UTC, martijnkruiten commented
I've added a test for the pillar roots that merges a dict that's defined in two different directories and then asserts that all the keys are present. What I'm stuck at, however, is writing a test for the states dirs. It seems to be sensitive to the environment that the file exists in (`base` vs `prod`), so I have to think of a different way to test this functionality.

2023-10-10 19:11 UTC, martijnkruiten commented
I think I'm going to need some help writing a test for `--states-dir`, as I'm not sure how it should be used exactly and there's not a lot of documentation available (it's not even mentioned in `salt-call.rst`). I thought that I could just point it to a random directory with sls files in it and that it would be able to run the states defined in those files, but it seems to be a bit more complicated than that.

Alternatively, I'm also fine with reverting the chances to that argument and going forward with the `--file-root` and `--pillar-root` options only. I'm still convinced that the change should work for `--states-dir` the same as it does for the other options, but I lack the knowledge to prove it in a test.

2025-03-28 15:40 UTC, twangboy requested changes
Could we get one more test for multiple `--states-dir`

2025-07-03 15:41 UTC, twangboy requested changes
Please add a test for multiple `--states-dir`

2025-07-03 15:41 UTC, twangboy commented on doc/ref/cli/salt-call.rst
> +    once to include multiple base pillar roots.
Looks like we're missing an option for `--states-dir`. Would you mind adding one for that as well?

2025-08-13 17:01 UTC, martijnkruiten commented
@twangboy I've made all the requested changes. Please review and let me know if further adjustments are needed.

2025-08-14 15:45 UTC, twangboy submitted a review, later dismissed

2025-08-29 12:52 UTC, martijnkruiten commented
@twangboy I've made sure that the pre-commit checks all pass.

2025-08-29 15:23 UTC, twangboy approved these changes

2025-10-29 10:54 UTC, martijnkruiten commented
@twangboy is there anything else I can do to make this go through?

2025-10-31 15:54 UTC, twangboy commented
Just need to get the tests to pass

2025-11-24 19:50 UTC, peterupton commented
> Just need to get the tests to pass

Is there anything that someone could do to help? I am interested in this PR.

2025-11-24 19:53 UTC, twangboy commented
Once the nightlies for master branch are passing, then we can rebase and see where we're at on the tests.

2026-03-17 21:03 UTC, merged