Manage SSH keys and certificates
saltstack/salt pull request #64708
Opened 2023-07-25 22:45 UTC by lkubb

### What does this PR do?
Adds `ssh_pki` execution and state modules that apply the principle (and rough code outline) of the `x509` modules to SSH keys and certificates.

This needs a bit more polishing and waiting until the current `x509_v2` issue regarding `test` mode propagation is fixed properly, but wanted to get this out for visibility/early feedback anyways.

### What issues does this PR fix or reference?
Fixes: TODO

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### Notes
I'm not sure if adding a new module fits the current zeitgeist of moving modules out into extensions, but tend to think being able to manage SSH keys (and certificates) should be part of Salt core.

In a lucky coincidence, the development of these modules resulted in the discovery of https://github.com/advisories/GHSA-cf7p-gm2m-833m, which means Salt now ships with the required `cryptography` version for them by default. :)

2023-09-15 08:37 UTC, OrangeDog commented
This feels like it should be sharing code with `x509_v2` and `tls` modules, as they all do essentially the same thing but with different default attributes. It would also avoid unexpected behaviour divergence.

2023-09-15 12:03 UTC, lkubb commented
@OrangeDog Although my initial expectation was the same, X509 v3 certificates are much more complicated than OpenSSH ones (and even for analogues, the `cryptography` APIs differ in some details). There might be some sections that can be abstracted somewhat reasonably regarding remote issuance and file handling, will investigate that further.

For the initial PR, I shied away from refactoring the `x509_v2` module to first gauge sentiment with a MVP. Also notice the modules in here are a bit more flexible than their `x509_v2` counterparts  - they allow signing policies to define overridable defaults + allowed values and the state module can optionally use a different execution module as the backend (there is an implementation for Vault e.g.). Implementing the latter for X509 is a lot of work.

I cannot speak for `tls`, but from what I groked it could be rewritten on top of `x509_v2` (or deprecated) since it's just a local CA implementation with defaults (what you would do with states otherwise).

2023-09-15 12:12 UTC, OrangeDog commented
> Implementing the latter for X509 is a lot of work

But you don't have to do that. If you've already implemented the flexibility, just call it from x509 without using those bits.

2023-09-15 14:39 UTC, lkubb commented
Sure, was trying to point out a few of the many subtle differences that carry the potential for the abstraction to end up as essentially two separate code paths in one ugly bowl of spaghetti.

I will investigate possible abstractions + do some low-hanging fruits as soon as I have the capacity, more complicated ones in case there is actual interest for this to be merged.

2024-03-07 11:57 UTC, lkubb commented
@dwoz Is managing SSH keys and certificates a functionality the team would accept into core in 3008? (Asking because of the new policy regarding module additions).

Note: This branch is currently outdated, but my current working branch is based on https://github.com/saltstack/salt/pull/65654, so I will wait for now.

2025-03-27 13:37 UTC, twangboy requested changes
A few docs changes

2025-03-27 14:10 UTC, lkubb commented on salt/states/x509_v2.py
> +    perform a ``file.managed`` sub-state run.
https://github.com/saltstack/salt/pull/64708#discussion_r2016760134 is valid here as well.

2025-03-27 14:56 UTC, lkubb commented on salt/utils/x509.py
> +    Extracted from the state module to be able to use this in the SSH wrapper.
This is part of https://github.com/saltstack/salt/pull/65654, which this PR is based on. Should I modify it there? Note that these functions should be considered module-internal ones since they are highly implementation-specific.

In this case, the (many) parameters are already documented on the modules that call this function.

2025-03-27 14:56 UTC, lkubb commented on salt/utils/x509.py
> +    on a builder instance to check for changes.
Same as https://github.com/saltstack/salt/pull/64708#discussion_r2016869414

2025-03-27 14:57 UTC, lkubb commented on salt/utils/x509.py
> +    Compare two lists of certificates for equality.
Same as https://github.com/saltstack/salt/pull/64708#discussion_r2016869414

2025-03-27 15:07 UTC, twangboy submitted a review, later dismissed

2025-05-09 19:41 UTC, twangboy submitted a review, later dismissed

2025-05-16 15:53 UTC, twangboy approved these changes, later dismissed

2025-10-21 20:01 UTC, lkubb commented
Sorry for dismissing the review, needed to adjust the system Python check after rebasing. Is there any estimate as to when PRs to the master branch will be merged again? No worries if you can't give specifics, just asking since I don't want to miss the 3008.0 RC. 👍

2025-10-31 17:48 UTC, twangboy approved these changes

2025-10-31 17:49 UTC, twangboy commented
We're still shooting for before the end of the year

2026-01-26 20:41 UTC, twangboy approved these changes

2026-01-29 23:59 UTC, merged