Make changes requested by Chunga and Rob H
saltstack/salt pull request #64721
Opened 2023-07-26 16:08 UTC by barbaricyawps

### What does this PR do?

This PR updates the Salt in 10 minutes tutorial to remove "SaltStack" and adjust Tom's title per a request from Chunga.

It also resolves a customer request from Rob H to remove inaccurate version information from the Salt Cloud on Windows documentation.

### What issues does this PR fix or reference?
Fixes: https://jira.eng.vmware.com/browse/VRAE-50911

2023-07-26 19:37 UTC, twangboy submitted a review, later dismissed

2023-07-27 15:33 UTC, s0undt3ch requested changes

2023-07-27 15:33 UTC, s0undt3ch commented on doc/topics/releases/3007.0.md
Don't commit this file.

Any additions should be done in the template file, https://github.com/saltstack/salt/blob/master/doc/topics/releases/templates/3007.0.md.template

2023-07-27 18:34 UTC, barbaricyawps commented on doc/topics/releases/3007.0.md
Thanks, Pedro. I'll remove the file from the PR.

Would I still get a docs build failure without the md file, though? That's the problem we're trying to solve. The build fails because it wants this missing md file.

2023-07-27 18:50 UTC, s0undt3ch commented on doc/topics/releases/3007.0.md
> Thanks, Pedro. I'll remove the file from the PR.
> 
> Would I still get a docs build failure without the md file, though? That's the problem we're trying to solve. The build fails because it wants this missing md file.

The CI/CD pipeline takes care of creating the file

2023-07-27 18:51 UTC, barbaricyawps commented on doc/topics/releases/3007.0.md
Awesome. That takes care of my concerns, then. I'll remove the file soon and push up the changes.

2023-07-27 20:08 UTC, barbaricyawps commented
I've added changes requested by @whytewolf to clarify which versions need the impacket dependencies.

I've also removed the 3007.0.md requested by @s0undt3ch .

Would you mind taking a second look? Thanks!

2023-07-27 20:25 UTC, s0undt3ch approved these changes

2023-07-27 20:25 UTC, whytewolf approved these changes

2023-07-28 17:25 UTC, merged