Fix _find_libcrypto for MacOS and Onedir
saltstack/salt pull request #64878
Opened 2023-07-28 21:43 UTC by garethgreenaway

### What does this PR do?
Look in location salt is running from, this accounts for running from an unpacked onedir file that has not been installed.

### What issues does this PR fix or reference?
Fixes: #64877 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-07-28 23:18 UTC, whytewolf submitted a review, later dismissed

2023-07-29 07:04 UTC, s0undt3ch requested changes
This should be going into 3006.x too correct?

2023-07-29 07:04 UTC, s0undt3ch commented on salt/utils/rsax931.py
> +        lib = lib or glob.glob(os.path.join("lib/libcrypto.dylib"))
```suggestion
        lib = lib or glob.glob("lib/libcrypto.dylib")
```
No need for `os.path.join` right?

2023-07-29 07:04 UTC, s0undt3ch commented on tests/unit/utils/test_rsax931.py
> +    @patch.object(salt.utils.platform, "is_darwin", lambda: True)
Let's move all these patch decorators to the test function both using `with` contexts please.

2023-07-31 16:34 UTC, twangboy submitted a review, later dismissed

2023-07-31 18:28 UTC, s0undt3ch submitted a review, later dismissed
Lets just remove these unnecessary comments.

2023-07-31 18:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_rsax931.py
> +# salt libs
```suggestion
```

2023-07-31 19:16 UTC, s0undt3ch approved these changes

2023-08-01 06:36 UTC, dwoz commented on salt/utils/rsax931.py
> +        lib = lib or glob.glob("lib/libcrypto.dylib")
Can't this just be a `find_library('libcrypto')` call?

2023-08-02 18:48 UTC, Ch3LL approved these changes

2023-08-04 06:53 UTC, dwoz approved these changes

2023-08-04 11:52 UTC, merged