Adding deprecation decorator to the vault modules for 3009.
saltstack/salt pull request #64889
Opened 2023-08-01 16:19 UTC by garethgreenaway

### What does this PR do?
Adding deprecation decorator to the vault modules for 3009.

### What issues does this PR fix or reference?
Fixes: TBD

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-08-02 16:57 UTC, dmurphy18 approved these changes, later dismissed

2023-08-03 19:56 UTC, Ch3LL requested changes

2023-08-03 19:56 UTC, Ch3LL commented on 64893.dprecated.md
> +Deprecate all Vault modules
```suggestion
Deprecate all the Vault modules in favor of the Vault Salt Extension https://github.com/saltstack/saltext-vault. The Vault modules will be removed in Salt core in 3009.0.
```

2023-08-10 16:19 UTC, dmurphy18 approved these changes

2023-08-17 20:02 UTC, Ch3LL approved these changes

2023-08-28 20:19 UTC, MKLeb approved these changes

2023-08-28 20:21 UTC, whytewolf approved these changes
looks like standard Deprecation.

2023-08-28 20:30 UTC, merged