[master] Adding deprecation decorator to docker modules for 3009.
saltstack/salt pull request #64890
Opened 2023-08-01 16:48 UTC by garethgreenaway

### What does this PR do?
Adding deprecation decorator to docker modules for 3009.

### What issues does this PR fix or reference?
Fixes: #64894

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-08-03 09:38 UTC, ITJamie commented
https://github.com/saltstack/salt/issues/64894 mentions compose but the PR hasnt added the flag to compose modules / states

2023-08-03 19:56 UTC, Ch3LL requested changes

2023-08-03 19:56 UTC, Ch3LL commented on changelog/64894.deprecated.md
> +Deprecated all Docker modules
```suggestion
Deprecate all the Docker modules in favor of the Docker Salt Extension https://github.com/saltstack/saltext-docker. The Docker modules will be removed in Salt core in 3009.0.
```

2023-08-10 16:03 UTC, garethgreenaway commented
@ITJamie Good catch. Thanks!  PR has been updated.

2023-08-10 16:20 UTC, cmcmarrow approved these changes

2023-08-17 19:59 UTC, Ch3LL approved these changes

2023-08-28 20:18 UTC, MKLeb approved these changes

2023-08-28 20:20 UTC, whytewolf approved these changes
looks like standard Deprecation.

2023-08-28 20:30 UTC, merged