[master] Adding deprecation decorator to zabbix modules for 3009.
saltstack/salt pull request #64892
Opened 2023-08-01 17:16 UTC by garethgreenaway

### What does this PR do?
Adding deprecation decorator to zabbix modules for 3009.

### What issues does this PR fix or reference?
Fixes: #64896

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-08-03 19:49 UTC, Ch3LL requested changes

2023-08-03 19:49 UTC, Ch3LL commented on changelog/64896.deprecated.md
> +Deprecate all Zabbix modules
```suggestion
Deprecate all the Zabbix modules in favor of the Zabbix Salt Extension https://github.com/salt-extensions/saltext-zabbix. The Zabbix modules will be removed in Salt core in 3009.0.
```

2023-08-17 20:04 UTC, Ch3LL approved these changes

2023-08-28 20:17 UTC, whytewolf approved these changes
looks like standard Deprecation.

2023-08-28 20:18 UTC, MKLeb approved these changes

2023-08-28 20:20 UTC, s0undt3ch approved these changes

2023-08-28 20:30 UTC, merged