fix(mac_brew_pkg): Guess homebrew prefix
saltstack/salt pull request #64924
Opened 2023-08-04 19:33 UTC by cdalvaro

### What does this PR do?

This PR improves the way salt tries to figure out the `brew` macOS command.

### What issues does this PR fix or reference?

After latest changes in brew command: https://github.com/Homebrew/brew/pull/15787 and https://github.com/Homebrew/brew/pull/15818, `salt` fails executing `brew` commands with the following error:

```
[salt.state       :325 ][ERROR   ][9799] An error was encountered while removing package(s): Path not found: Error: $HOME or $USER or $LOGNAME must be set to run brew./bin/brew
[salt.loaded.int.module.cmdmod:920 ][ERROR   ][13361] Command 'brew' failed with return code: 1
```

This is due because `salt-minion` is launched as a Launch Daemon in macOS with a very reduced environment:

```sh
LC_PAPER=C
LC_ADDRESS=C
LC_MONETARY=C
LC_NUMERIC=C
LC_TELEPHONE=C
PATH=/opt/homebrew/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LC_MESSAGES=C
LC_IDENTIFICATION=C
LC_COLLATE=C
PWD=/private/var/root
LC_MEASUREMENT=C
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
LANGUAGE=C
HOMEBREW_PREFIX=/opt/homebrew
LC_CTYPE=C
LC_TIME=C
LC_NAME=C
_=/usr/bin/env
```

(I have added PATH and HOMEBREW_PREFIX manually to my daemon's plist file)

When `salt` tries to recover the `brew --prefix` with the following code:

https://github.com/saltstack/salt/blob/4e8b77df671fd756970fe4fb08122fba9b47c50b/salt/modules/mac_brew_pkg.py#L96-L102

There is no `$HOME`, neither `$USER`, neither `$LOGNAME` in the environment.

This PR tries to figure out the Homebrew's prefix, by using the `HOMEBREW_PREFIX`. As it is already used in other salt modules, like in `rsax931.py`:

https://github.com/saltstack/salt/blob/4e8b77df671fd756970fe4fb08122fba9b47c50b/salt/utils/rsax931.py#L41

If the environment variable is not set, then it tries the most common paths for `brew` regarding the system architecture. `/opt/homebrew` for Apple Silicon, `/usr/local` for x86_64.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?

Yes

2023-08-05 14:53 UTC, cdalvaro commented on salt/modules/mac_brew_pkg.py
> +    # Try brew --prefix
Homebrew is not intended to be run as root, so I prefer to check for the environment variable before running `brew` as root.

2023-08-05 16:53 UTC, cdalvaro commented on salt/modules/mac_brew_pkg.py
> +        ret = salt.modules.cmdmod.run(
I use `salt.modules.cmdmod.run` instead of `__salt__["cmd.run"]` because it is not available to use from `salt/utils/rsax931.py`

2023-08-05 17:25 UTC, cdalvaro commented on salt/modules/mac_brew_pkg.py
> +        ret = salt.modules.cmdmod.run(
With this change, now you can run `salt-*` commands with `sudo` and without the `-E` argument:

```sh
sudo salt-call test.version
[WARNING ] HOMEBREW_PREFIX is not set. Please, consider adding it.
local:
    3006.1
```

Before this change, you get:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/salt-call", line 8, in <module>
    sys.exit(salt_call())
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/scripts.py", line 438, in salt_call
    import salt.cli.call
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/cli/call.py", line 3, in <module>
    import salt.cli.caller
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/cli/caller.py", line 12, in <module>
    import salt.channel.client
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/crypt.py", line 31, in <module>
    import salt.utils.rsax931
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/utils/rsax931.py", line 158, in <module>
    libcrypto = _init_libcrypto()
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/utils/rsax931.py", line 111, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/utils/rsax931.py", line 104, in _load_libcrypto
    return cdll.LoadLibrary(_find_libcrypto())
  File "/opt/homebrew/Cellar/salt/3006.1_1/libexec/lib/python3.10/site-packages/salt/utils/rsax931.py", line 96, in _find_libcrypto
    raise OSError("Cannot locate OpenSSL libcrypto")
OSError: Cannot locate OpenSSL libcrypto
```

2023-08-05 19:18 UTC, cdalvaro commented on salt/modules/mac_brew_pkg.py
> +        log.warning(f"{env_homebrew_prefix} is not set. Please, consider adding it.")
Maybe this log level is too high

2023-08-09 20:18 UTC, Ch3LL commented
@cdalvaro there is a merge conflict after the merge of this PR: https://github.com/saltstack/salt/pull/57946

Can you resolve conflicts and I'll give this a review.

2023-08-10 14:32 UTC, cdalvaro commented
> @cdalvaro there is a merge conflict after the merge of this PR: #57946
> 
> Can you resolve conflicts and I'll give this a review.

Done!

2023-08-20 08:18 UTC, cdalvaro commented
Branch rebased to latest changes

2023-08-30 10:31 UTC, cdalvaro commented
Hi @Ch3LL, could you review this PR, please??

2023-10-05 07:52 UTC, cdalvaro commented
Kind reminder to @Ch3LL for reviewing this PR

2023-11-30 12:24 UTC, cdalvaro commented
Hi @weswhet, could you move this PR, please?

2023-12-18 21:03 UTC, twangboy requested changes

2023-12-18 21:03 UTC, twangboy commented on changelog/64924.fixed.md
> +`brew` command can failed. So a last attempt is made to get the
\`brew\` command can fail.

2023-12-18 22:03 UTC, cdalvaro commented on changelog/64924.fixed.md
> +`brew` command can failed. So a last attempt is made to get the
Done!

2023-12-18 22:14 UTC, twangboy approved these changes

2023-12-22 04:35 UTC, merged