Add MySQL privilege SERVICE_CONNECTION_ADMIN
saltstack/salt pull request #64934
Opened 2023-08-08 07:50 UTC by bcremer

Add MySQL dynamic privilege `SERVICE_CONNECTION_ADMIN` that was introduced in MySQL 8.0.14.

See:
- https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-14.html
- https://dev.mysql.com/doc/refman/8.0/en/administrative-connection-interface.html

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-08-09 20:14 UTC, Ch3LL requested changes
This will need a changelog

@garethgreenaway any opinions here on whether we should require test coverage here or not?

2023-08-10 08:28 UTC, bcremer commented
Added a changelog file with the PR Number as index. Is that OK or do I need to create a Issue first and assigns that number?

2023-08-17 19:49 UTC, Ch3LL requested changes

2023-08-17 19:49 UTC, Ch3LL commented on changelog/64934.changed.md
> +Add missing MySQL Grant SERVICE_CONNECTION_ADMIN to mysql module.
I think the file extension `fixed.md` would apply better here. This would not change behavior for users, but fix an issue with mysql.

2023-08-17 19:50 UTC, Ch3LL commented
Just added one request and just want to get @garethgreenaway 's review here to see if we would require testing here.

2023-08-17 22:24 UTC, garethgreenaway commented
I'm good not including tests for this since it's not a potential breaking change and it's simply adding an additional permission type.

2023-08-18 19:52 UTC, Ch3LL commented
looks like pre-commit and lint are failing @bcremer 
Can you also make sure to rebase. The package tests should be passing now.

2023-08-22 05:31 UTC, bcremer commented
Renamed changlog entry, fixed CS issue, rebased to master.

2023-08-23 20:00 UTC, Ch3LL submitted a review, later dismissed

2023-08-24 17:59 UTC, Ch3LL commented
Looks like pre-commit is failing. Also can you ensure you rebase because some of the test failures in packages tests should now be resolved.

2023-09-12 05:29 UTC, bcremer commented
All failing cs-checks are unrelated to my change. I don't have a working python setup in place to run the automated tools. 
Please take over the cs-fixing.

2023-10-23 21:06 UTC, whytewolf approved these changes

2023-10-24 22:06 UTC, garethgreenaway approved these changes

2023-10-24 22:13 UTC, twangboy approved these changes

2023-10-24 22:35 UTC, merged