Fix pkg.install when using a port in the url.
saltstack/salt pull request #64945
Opened 2023-08-09 14:37 UTC by Ch3LL

### What does this PR do?
Removes `:` from url. `apt` does not handle `:` and windows does not allow it.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64516

### Previous Behavior
Could not install a package with a source url with an port in it.

### New Behavior
Can now install a package with a source with a url and a port in it.

2023-08-15 20:46 UTC, s0undt3ch requested changes

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient.py
> +    with patch("os.path.isfile", lambda prm: False):
```suggestion
    with patch("os.path.isfile", return_value=False):
```
?

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient.py
> +    del client
```suggestion
def file_client(mocked_opts):
    client = fileclient.Client(mocked_opts)
    try:
        yield client
    finally:
        del client
```

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient.py
> +        # Crypticla must return bytes to pass to transport.RequestClient.send
```suggestion
        # Crypticle must return bytes to pass to transport.RequestClient.send
```

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient.py
> +    with patch("os.path.isfile", lambda prm: False):
```suggestion
    with patch("os.path.isfile", return_value=False):
```
?

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient_cache.py
> +    patched_opts.update(mocked_opts)
```suggestion
    patched_opts = minion_opts.copy()
    patched_opts.update(mocked_opts)
```
In fact, the `minion_opts` fixture is generated(or copied) for every test function, so, you might not even need to copy it...

2023-08-15 20:46 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient_cache.py
> +    patched_opts.update(mocked_opts)
```suggestion
    patched_opts = {x: y for x, y in minion_opts.items()}
    patched_opts.update(mocked_opts)
```
Same as above

2023-08-16 06:52 UTC, garethgreenaway submitted a review, later dismissed

2023-08-16 08:07 UTC, s0undt3ch requested changes

2023-08-16 08:07 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient_cache.py
> +    patched_opts = {x: y for x, y in minion_opts.items()}
```suggestion
    patched_opts = minion_opts.copy()
```
Sorry didn't want to sound repetitive on my previous review.

2023-08-16 08:07 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient_cache.py
> +    patched_opts = {x: y for x, y in minion_opts.items()}
Same as above

2023-08-16 08:07 UTC, s0undt3ch commented on tests/pytests/unit/fileclient/test_fileclient_cache.py
> +    patched_opts = {x: y for x, y in minion_opts.items()}
```suggestion
    patched_opts = {x: y for x, y in minion_opts.items()}
```
Same as above

2023-08-16 08:44 UTC, s0undt3ch approved these changes

2023-08-16 12:49 UTC, merged