[3006.x] Preserve master credentials on spawning platforms
saltstack/salt pull request #64944
Opened 2023-08-09 05:00 UTC by dwoz

### What does this PR do?

Prevent spawning platform minions from having to re-authenticate on every job when using `multiprocessing=True`

### What issues does this PR fix or reference?

Fixes: #64914

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

2023-08-09 20:12 UTC, Ch3LL submitted a review, later dismissed

2023-08-13 17:56 UTC, s0undt3ch requested changes

2023-08-13 17:56 UTC, s0undt3ch commented on tests/pytests/integration/minion/test_reauth.py
> +        - comment: "Nothing has acutally been changed"
```suggestion
        - comment: "Nothing has actually been changed"
```

2023-08-14 21:49 UTC, dwoz commented on tests/pytests/integration/minion/test_reauth.py
> +        - comment: "Nothing has acutally been changed"
Fixed

2023-08-15 08:18 UTC, s0undt3ch approved these changes

2023-08-15 08:19 UTC, merged