Don't remove extras dir on uninstall
saltstack/salt pull request #65038
Opened 2023-08-23 20:17 UTC by twangboy

### What does this PR do?
- Don't remove the entire `salt` directory by default.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64957

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-08-23 20:37 UTC, MKLeb approved these changes, later dismissed

2023-08-24 20:26 UTC, Ch3LL requested changes
Can we add test coverage?

2023-08-25 07:54 UTC, s0undt3ch submitted a review, later dismissed

2023-08-28 20:16 UTC, MKLeb commented
This may be a matter of semantics, but the title says to not remove the directory on `uninstall`.  Is this what happens during upgrades and downgrades (i.e. installing the desired package while the undesired one is still on the system), or is that process different than explicitly uninstalling the package?

2023-08-30 15:21 UTC, s0undt3ch approved these changes

2023-08-30 15:30 UTC, MKLeb approved these changes

2023-08-31 21:30 UTC, garethgreenaway approved these changes

2023-08-31 21:30 UTC, merged