adding usermod, groupadd, useradd to requires for rpm
saltstack/salt pull request #65051
Opened 2023-08-24 21:03 UTC by felippeb

### What does this PR do?
add binaries required for package installation to package requires.

### What issues does this PR fix or reference?
Fixes: installation issue on photon4

https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html

2023-09-05 20:19 UTC, dwoz requested changes
Should this go to 3006.x instead of master?

2023-09-05 20:21 UTC, dwoz commented
> Should this go to 3006.x instead of master?

Nevermind, I see the other PR.

2023-09-05 20:21 UTC, dwoz submitted a review, later dismissed

2025-04-01 20:47 UTC, twangboy commented
@felippeb Is this still necessary on master?

2025-04-01 21:13 UTC, closed without merging