[3006.x] Increase code coverage for salt/state.py
saltstack/salt pull request #65176
Opened 2023-09-12 19:35 UTC by Ch3LL

### What does this PR do?
Increase code coverage for salt/state.py 

### What issues does this PR fix or reference?
Reference:  https://github.com/saltstack/salt/issues/64734
Fixes: https://github.com/saltstack/salt/issues/65210

2023-09-15 21:08 UTC, twangboy approved these changes, later dismissed

2023-09-17 12:17 UTC, s0undt3ch requested changes

2023-09-17 12:17 UTC, s0undt3ch commented on tests/pytests/functional/modules/state/requisites/test_mixed.py
> +        assert ["Illegal requisite \"['A']\", please check your syntax.\n"] == ret
```suggestion
        assert ret == ["Illegal requisite \"['A']\", please check your syntax.\n"]
```

2023-09-17 12:17 UTC, s0undt3ch commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
```suggestion
            "tag": f"salt/minion/{minion}/start",
```
?
And if this is how it should look like, why are the tests passing?

2023-09-17 12:17 UTC, s0undt3ch commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
```suggestion
            "tag": f"salt/minion/{minion}/start",
```
Same here...

2023-09-18 14:25 UTC, Ch3LL commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
The code does not use this part of the kwargs dictionary. I still want to keep this kwarg as it is, since this is what the kwarg data looks like when running the reactor.

2023-09-18 14:50 UTC, s0undt3ch commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
> since this is what the kwarg data looks like when running the reactor.

`{minion}` ? the format string? not the actual minion ID?

2023-09-18 18:05 UTC, s0undt3ch approved these changes

2023-09-18 18:05 UTC, merged

2023-09-18 19:45 UTC, Ch3LL commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
The actual data includes the minion ID. I updated the test to reflect that. Was just trying to answer your question as to why the tests where passing when the minion id was not in `data['tag']`

2023-09-18 19:57 UTC, s0undt3ch commented on tests/pytests/unit/state/test_reactor_compiler.py
> +            "tag": "salt/minion/{minion}/start",
Ah, makes sense now.