Fix heading level of "creates"
saltstack/salt pull request #65202
Opened 2023-09-15 08:54 UTC by OrangeDog

### What does this PR do?
Changes the "creates" heading to match all the other headings under "Altering States".

2023-09-17 12:08 UTC, s0undt3ch approved these changes

2023-09-18 18:37 UTC, s0undt3ch requested changes

2023-09-18 18:37 UTC, s0undt3ch commented on doc/ref/states/requisites.rst
> +~~~~~
```suggestion
creates
~~~~~~~
```

2023-09-18 18:38 UTC, s0undt3ch commented on doc/ref/states/requisites.rst
> +~~~~~
```
/home/runner/work/salt/salt/doc/ref/states/requisites.rst:1057: WARNING: Title underline too short.
```

2023-09-19 13:06 UTC, Ch3LL approved these changes

2023-09-19 13:06 UTC, merged

2023-09-24 20:15 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/65277">](https://github.com/saltstack/salt/pull/65277)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->

2023-09-24 20:15 UTC, s0undt3ch commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[<img src="https://img.shields.io/github/pulls/detail/state/saltstack/salt/65277">](https://github.com/saltstack/salt/pull/65277)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->