Increase code coverage for ps module
saltstack/salt pull request #65237
Opened 2023-09-20 00:07 UTC by garethgreenaway

### What does this PR do?
Increase code coverage for ps module

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-09-21 13:03 UTC, s0undt3ch requested changes

2023-09-21 13:03 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_ps.py
> +@pytest.mark.skipif(not ps.PSUTIL2, reason="Only run for psutil 2.x")
We now require psutil >= 5.0

https://github.com/saltstack/salt/blob/v3006.3/requirements/base.txt#L8

Let's just nuke all of the old code.

2023-10-03 15:18 UTC, dmurphy18 approved these changes, later dismissed

2023-10-03 15:21 UTC, twangboy approved these changes, later dismissed

2023-10-03 15:36 UTC, whytewolf approved these changes, later dismissed

2023-12-11 18:12 UTC, s0undt3ch approved these changes

2023-12-12 22:28 UTC, merged