IMDSv2 support for metadata grains
saltstack/salt pull request #65269
Opened 2023-09-22 21:27 UTC by edlitmus

### What does this PR do?

This is to make the built in metadata grains work with IMDSv2 as well as IMDSv1.

### What issues does this PR fix or reference?

Fixes: https://github.com/saltstack/salt/issues/65233

### Previous Behavior

The metadata grains would fail in environments requiring IMDSv2.

### New Behavior

The metadata grains work as expected regardless of IMDS version.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

I could not find any tests unit tests specific to the metadata grains, however I was able to test that the grains returned data as expected in a test EC2 instance:

```shell
ubuntu@ip-172-30-117-209:/usr/test/saltstack$ salt-call -c local/etc/salt grains.get meta-data:system
local:
    nitro
ubuntu@ip-172-30-117-209:/usr/test/saltstack$ salt-call -c local/etc/salt grains.get saltversion
local:
    3007.0+0na.c77b9dff87
```

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-12-17 21:49 UTC, dwoz commented
@edlitmus Can you please add some test coverage for this change?

2023-12-18 14:38 UTC, edlitmus commented
@dwoz I couldn't see a way to add additional testing, as I am re-using code that already has test coverage within the salt code base.

2024-03-14 13:09 UTC, s0undt3ch requested changes

2024-03-14 13:09 UTC, s0undt3ch commented on salt/grains/metadata.py
> +def main():
`main()`?

```suggestion
def metadata():
```

I guess your issue is that you import `import salt.utils.aws as metadata`, don't.
Instead do:

```python
import salt.utils.aws

...  

salt.utils.aws.get_metadata()
```

Or, 
```
import salt.utils.aws as aws
...  
aws.get_metadata()
```

2024-04-02 17:44 UTC, s0undt3ch requested changes

2024-04-02 17:44 UTC, s0undt3ch commented on salt/grains/metadata.py
> +    return ret
```suggestion
    return {
        "dynamic": _search("dynamic"),
        "meta-data": _search("meta-data"),
    }
```

2025-04-04 15:21 UTC, twangboy commented
This module and its associated states and tests have been transitioned to community support and are no longer maintained by the Salt Core team. The code has been removed from the Salt code-base and can be found in this repository: https://github.com/salt-extensions/community-extensions-holding/

There is currently discussion and work being done on the salt-extensions Discord channel (https://discordapp.com/channels/1200072194781368340/1208165123240370197) to document and build the infrastructure for community-supported salt extensions. There is also a Salt-Extensions Working Group that takes place on the 1st and 3rd Thursday of every month to coordinate salt-extension efforts.

2025-04-04 15:21 UTC, closed without merging