bump pygit in ci
saltstack/salt pull request #65308
Opened 2023-09-27 22:05 UTC by cmcmarrow

### What does this PR do?

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-09-28 21:52 UTC, s0undt3ch requested changes

2023-09-28 21:52 UTC, s0undt3ch commented on requirements/static/ci/darwin.in
> +pygit2>=1.13.1; python_version >= '3.8'
```suggestion
pygit2>=1.10.1
```
Then, once this change lands on the `master` branch we update to:
```
pygit2>=1.13.1
```

2023-09-28 21:52 UTC, s0undt3ch commented on requirements/static/ci/freebsd.in
> +pygit2>=1.13.1; python_version >= '3.8'
```suggestion
pygit2>=1.10.1
```
Then, once this change lands on the `master` branch we update to:
```
pygit2>=1.13.1
```

2023-09-28 21:52 UTC, s0undt3ch commented on requirements/static/ci/linux.in
> +pygit2>=1.13.1; python_version >= '3.8'
```suggestion
pygit2>=1.10.1
```
Then, once this change lands on the `master` branch we update to:
```
pygit2>=1.13.1
```

2023-09-28 21:52 UTC, s0undt3ch commented on requirements/static/ci/windows.in
> +pygit2>=1.13.1; python_version >= '3.8'
```suggestion
pygit2>=1.10.1
```
Then, once this change lands on the `master` branch we update to:
```
pygit2>=1.13.1
```

2023-10-19 17:45 UTC, cmcmarrow commented
closing for https://github.com/saltstack/salt/pull/65430

2023-10-19 17:45 UTC, closed without merging