is_link_test
saltstack/salt pull request #65313
Opened 2023-09-28 16:04 UTC by cmcmarrow

### What does this PR do?
https://github.com/saltstack/salt/issues/64741

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-09-29 17:57 UTC, MKLeb commented on tests/pytests/functional/modules/test_win_file.py
> +]
```suggestion
```

This seems to be a windows specific test, we don't want to skip that on windows.

2023-10-02 20:43 UTC, Ch3LL commented on tests/pytests/functional/modules/test_win_file.py
> +    assert win_file.is_link(tmp_path) is True
I'm surprised this is returning `True`. Does `tmp_path` create a symlink?

2023-11-03 07:08 UTC, s0undt3ch requested changes, later dismissed

2023-11-03 07:08 UTC, s0undt3ch commented on salt/modules/win_file.py
> +    )
What's the reason behind no longer having the `if` check?

2023-11-03 07:08 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_win_file.py
> +    assert win_file.is_link(link) is True
```suggestion
    file = tmp_path.joinpath("t.txt").touch()
    assert file.is_file() is True
    link = tmp_path / "l"
    assert win_file.is_link(link) is False
    assert win_file.symlink(file, link) is True
    assert file.is_file() is True
    assert win_file.is_link(link) is True
```
Same for remaining tests.

2023-11-03 07:08 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_win_file.py
> +    assert len(win_file.version("C:\\Windows\\System32\\wow64.dll").split(".")) == 4
```suggestion
def test_version():
    assert len(win_file.version("C:\\Windows\\System32\\wow64.dll").split(".")) == 4
```
Testing the returned version number of parts?
If the versioning scheme breaks the test breaks?
What are we really testing here?

2023-11-03 07:08 UTC, s0undt3ch commented on tests/pytests/functional/modules/test_win_file.py
> +        win_file.version(path)
```suggestion
def test_version_dir(tmp_path):
    path = tmp_path.joinpath("dir").mkdir()
    with pytest.raises(CommandExecutionError):
        win_file.version(str(path))
```
So much simpler...

2025-05-28 20:26 UTC, merged