update pre-commit-config
saltstack/salt pull request #65314
Opened 2023-09-28 16:37 UTC by cmcmarrow

### What does this PR do?
update pre-commit-config

### Commits signed with GPG?
Yes

2023-09-28 17:43 UTC, s0undt3ch requested changes

2023-09-28 17:43 UTC, s0undt3ch commented on .pre-commit-config.yaml
> +    rev: 23.9.1
https://github.com/saltstack/salt/pull/65314/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R1272 make it match

2023-09-28 17:49 UTC, s0undt3ch commented
Let's also make these changes please:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index f9af175715..6d123775a8 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -128,6 +128,9 @@ jobs:
                 - *salt_added_modified
                 - *tests_added_modified
                 - *pkg_tests_added_modified
+            pre-commit:
+              - added|modified:
+                - .pre-commit-config.yaml

       - name: Set up Python 3.10
         uses: actions/setup-python@v4
diff --git a/.github/workflows/pre-commit-action.yml b/.github/workflows/pre-commit-action.yml
index fbafa2c4b4..cf0e332b0d 100644
--- a/.github/workflows/pre-commit-action.yml
+++ b/.github/workflows/pre-commit-action.yml
@@ -50,14 +50,14 @@ jobs:
           cache-seed: ${{ inputs.cache-seed }}

       - name: Check ALL Files On Branch
-        if: github.event_name != 'pull_request'
+        if: github.event_name != 'pull_request' || fromJSON(inputs.changed-files)['pre-commit']
         env:
           SKIP: lint-salt,lint-tests,remove-import-headers,rstcheck
         run: |
           pre-commit run --show-diff-on-failure --color=always --all-files

       - name: Check Changed Files On PR
-        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['repo']
+        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['repo'] && fromJSON(inputs.changed-files)['pre-commit'] == false
         env:
           SKIP: lint-salt,lint-tests
           GH_ACTIONS_ANNOTATE: "1"
```
We want to run pre-commit on everything when `.pre-commit-config.yaml` changes

2023-09-28 17:51 UTC, s0undt3ch commented
Sorry

```diff
diff --git a/.github/workflows/pre-commit-action.yml b/.github/workflows/pre-commit-action.yml
index fbafa2c4b4..cf0e332b0d 100644
--- a/.github/workflows/pre-commit-action.yml
+++ b/.github/workflows/pre-commit-action.yml
@@ -50,14 +50,14 @@ jobs:
           cache-seed: ${{ inputs.cache-seed }}

       - name: Check ALL Files On Branch
-        if: github.event_name != 'pull_request'
+        if: github.event_name != 'pull_request' || fromJSON(inputs.changed-files)['pre-commit']
         env:
           SKIP: lint-salt,lint-tests,remove-import-headers,rstcheck
         run: |
           pre-commit run --show-diff-on-failure --color=always --all-files

       - name: Check Changed Files On PR
-        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['repo']
+        if: github.event_name == 'pull_request' && fromJSON(inputs.changed-files)['repo'] && fromJSON(inputs.changed-files)['pre-commit'] == false
         env:
           SKIP: lint-salt,lint-tests
           GH_ACTIONS_ANNOTATE: "1"
diff --git a/.github/workflows/templates/layout.yml.jinja b/.github/workflows/templates/layout.yml.jinja
index 773ebeb622..421b2f7ec1 100644
--- a/.github/workflows/templates/layout.yml.jinja
+++ b/.github/workflows/templates/layout.yml.jinja
@@ -176,6 +176,9 @@ jobs:
                 - *salt_added_modified
                 - *tests_added_modified
                 - *pkg_tests_added_modified
+            pre-commit:
+              - added|modified:
+                - .pre-commit-config.yaml
```

2023-09-29 18:48 UTC, cmcmarrow commented
Thansk @s0undt3ch

2023-10-02 10:29 UTC, s0undt3ch commented
As you can see, if we upgrade `black` there's a lot of code that needs to change in Salt, and, if the team decides to do that, we should also consider running `pyupgrade` (`pre-commit run -av pyupgrade`) against all of the Salt code base.

2023-10-03 15:16 UTC, twangboy approved these changes

2023-12-16 21:50 UTC, dwoz commented
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

2023-12-16 21:50 UTC, closed without merging