Fix install of logrotate config for debian pkg
saltstack/salt pull request #65318
Opened 2023-09-29 16:57 UTC by barneysowood

### What does this PR do?

Fixes the install of logrotate config for the debian pkg by moving file to pkg/common/logrotate/salt-common. File is installed via salt-common.install file, which can't rename files, only copy them to a directory, so we need to rename the file and put it in a subdir of pkg/common.

If the incorrect /etc/logrotate.d/salt directory created by original 3006.3 packages.

Adds /etc/logrotate.d/salt-common to salt.common.conffiles to ensure that dpkg will not overwrite configs modified by users.

Also updates RPM spec file for new location of logrotate config.

Config needs to be /etc/logrotate.d/salt-common as that is what is used by 3005.x packages.

### What issues does this PR fix or reference?
Fixes: #65231

### Previous Behavior
Logrotate config was incorrectly copied to /etc/logrotated.d/salt/salt-common.logrotate

### New Behavior
Config is copied to /etc/logrotate.d/salt-common and marked as a config file so dpkg will not overwrite modified configs.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-10-27 11:59 UTC, barneysowood commented
@s0undt3ch and @dmurphy18 - could I get a review of this? Thanks!

2023-10-31 00:09 UTC, dmurphy18 approved these changes, later dismissed
So long as you fix the issue @terminalmage raised about salt-common

2023-10-31 01:14 UTC, terminalmage commented
> So long as you fix the issue @terminalmage raised about salt-common

See here: https://github.com/saltstack/salt/issues/65231#issuecomment-1785708839

2023-10-31 20:28 UTC, s0undt3ch requested changes

2023-10-31 20:28 UTC, s0undt3ch commented on pkg/tests/integration/test_logrotate_config.py
> +pytestmark = [pytest.mark.skip_on_windows, pytest.mark.skip_on_darwin]
```suggestion
pytestmark = [
    pytest.mark.skip_unless_on_linux,
]
```

2023-10-31 20:28 UTC, s0undt3ch commented on pkg/tests/integration/test_logrotate_config.py
> +        return logrotate_dir / "salt-common"
```suggestion
@pytest.fixture
def logrotate_config_file(grains):
    """
    Fixture for logrotate config file path
    """
    logrotate_dir = pathlib.Path("/etc/logrotate.d")

    if grains["os_family"] == "RedHat":
        return logrotate_dir / "salt"
    elif grains["os_family"] == "Debian":
        return logrotate_dir / "salt-common"
```

2023-10-31 20:28 UTC, s0undt3ch commented on pkg/tests/integration/test_logrotate_config.py
> +from pathlib import Path
```suggestion
import pathlib
```

2023-10-31 20:28 UTC, s0undt3ch commented on pkg/tests/integration/test_logrotate_config.py
> +    path = Path("/etc/logrotate.d/salt")
```suggestion
    path = pathlib.Path("/etc/logrotate.d/salt")
```

2023-11-02 12:55 UTC, s0undt3ch submitted a review, later dismissed

2023-11-03 06:45 UTC, s0undt3ch approved these changes

2023-11-03 06:46 UTC, merged