[code-coverage] [3006.x] Increase code coverage for salt/client/mixins.py
saltstack/salt pull request #65339
Opened 2023-10-03 23:49 UTC by dmurphy18

### What does this PR do?
Increase code coverage for salt/client/mixins.py

### What issues does this PR fix or reference?
Fixes:  https://github.com/saltstack/salt/issues/64736

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-10-05 18:56 UTC, twangboy submitted a review, later dismissed

2023-10-05 20:14 UTC, Ch3LL approved these changes

2023-10-05 20:15 UTC, Ch3LL requested changes

2023-10-05 20:15 UTC, Ch3LL commented on tests/pytests/integration/client/test_runner.py
> +def test_get_docs(client, auth_creds):
```suggestion
def test_get_docs(client):
```

2023-10-18 19:19 UTC, Ch3LL approved these changes

2023-10-18 19:21 UTC, twangboy approved these changes

2023-10-23 15:26 UTC, s0undt3ch approved these changes

2023-10-23 15:26 UTC, merged