Add tops, alternatives tests for thin.py
saltstack/salt pull request #65373
Opened 2023-10-10 16:15 UTC by techhat

2023-11-02 16:35 UTC, s0undt3ch requested changes

2023-11-02 16:35 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_thin.py
> +            ]
```suggestion
def test_pack_alternatives(tmp_path):
    """
    test thin._pack_alternatives
    """
    jinja_fp = os.path.dirname(jinja2.__file__)
    ext_conf = {
        "test": {
            "py-version": [2, 7],
            "path": str(CODE_DIR),
            "dependencies": [jinja_fp],
        }
    }
    tops = copy.deepcopy(ext_conf)
    digest = salt.utils.hashutils.DigestCollector()
    tar = _tarfile(None).open()
    exp_files = [
        os.path.join("salt", "payload.py"),
        os.path.join("jinja2", "__init__.py"),
    ]
    lib_root = str(tmp_path / "fake-libs")

    with patch("salt.utils.thin.get_ext_tops", MagicMock(return_value=tops)):
        salt.utils.thin._pack_alternative(ext_conf, digest, tar)
        calls = tar.mock_calls
        for _file in exp_files:
            assert [x for x in calls if f"{_file}" in x[-2]]
            assert [
                x
                for x in calls
                if os.path.join("test", "pyall", _file) in x[-1]["arcname"]
            ]
```

2023-11-02 16:35 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_thin.py
> +from tests.support.runtests import RUNTIME_VARS
```suggestion
from tests.conftest import CODE_DIR
```

2023-11-02 16:36 UTC, s0undt3ch commented
Why are adding these tests in `master`? Why not 3006.x?

2026-07-03 22:40 UTC, dwoz commented
Replaced by #69668. Addressed s0undt3ch's review feedback: dropped RUNTIME_VARS in favor of tests.conftest.CODE_DIR and pytest tmp_path fixture.

2026-07-03 22:40 UTC, closed without merging