Add more tests for salt/state and salt/modules/aptpkg
saltstack/salt pull request #65391
Opened 2023-10-12 17:26 UTC by Ch3LL

2023-10-13 13:19 UTC, cmcmarrow submitted a review, later dismissed

2023-10-13 14:56 UTC, dmurphy18 approved these changes, later dismissed

2023-10-15 20:00 UTC, s0undt3ch requested changes

2023-10-15 20:00 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_aptpkg.py
> +        print(ret)
```suggestion
```

2023-10-19 20:47 UTC, twangboy approved these changes

2023-10-19 23:51 UTC, dmurphy18 approved these changes

2023-10-20 13:41 UTC, merged