[WIP] Add log level insecure warning to more places
saltstack/salt pull request #65393
Opened 2023-10-12 18:26 UTC by Ch3LL

We already log this if the user is using an insecure log level: `[WARNING ] Insecure logging configuration detected! Sensitive data may be logged`

And we have it documented in every config file:

```
 # The following log levels are considered INSECURE and may log sensitive data:
 # ['garbage', 'trace', 'debug']
```

And the documentation here: https://docs.saltproject.io/en/latest/ref/configuration/examples.html

This PR makes this warning more noticeable across multiple places in the docs and when the user runs `--help`

2023-10-12 19:27 UTC, whytewolf approved these changes, later dismissed

2023-10-15 18:28 UTC, s0undt3ch requested changes

2023-10-15 18:28 UTC, s0undt3ch commented on salt/utils/parsers.py
> +                ", ".join(insecure_log()),
```suggestion
            help=(
                "Console logging log level. One of {}. Default: '{}'.\n"
                "The following log levels are INSECURE and may log sensitive data: {}"
            ).format(
                ", ".join(["'{}'".format(n) for n in salt._logging.SORTED_LEVEL_NAMES]),
                self._default_logging_level_,
                ", ".join(insecure_log()),
```
Minor formatting change for smaller line length, but, is the added line break actually respected?

2023-10-15 18:28 UTC, s0undt3ch commented on salt/utils/parsers.py
> +                ", ".join(insecure_log()),
Same as above

2023-10-15 18:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/verify/test_clean_path_link.py
> +@pytest.fixture()
```suggestion
@pytest.fixture
```

2023-10-15 18:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/verify/test_clean_path_link.py
> +        raise ctypes.WinError()
```suggestion

class Symlink:
    """
    symlink(source, link_name) Creates a symbolic link pointing to source named
    link_name
    """
    def __init__(self):
        self._csl = None
        
    def __call__(self, source, link_name):
        if self._csl is None:
            self._csl = ctypes.windll.kernel32.CreateSymbolicLinkW
            self._csl.argtypes = (ctypes.c_wchar_p, ctypes.c_wchar_p, ctypes.c_uint32)
            self._csl.restype = ctypes.c_ubyte

        flags = 0
        if source is not None and source.is_dir():
            flags = 1
            
        if self._csl(link_name, source, flags) == 0:
            raise ctypes.WinError()

@pytest.fixture(scope="module")
def symlink():
    return Symlink()
```

There, no more globals usage.

2023-10-15 18:28 UTC, s0undt3ch commented on tests/pytests/unit/utils/verify/test_clean_path_link.py
> +    return to_path, from_path
```suggestion
def setup_links(tmp_path, symlink):
    to_path = tmp_path / "linkto"
    from_path = tmp_path / "linkfrom"
    if salt.utils.platform.is_windows():
        kwargs = {}
    else:
        kwargs = {"target_is_directory": True}
    if salt.utils.platform.is_windows():
        symlink(to_path, from_path, **kwargs)
    else:
        from_path.symlink_to(to_path, **kwargs)
    return to_path, from_path
```

2023-10-16 14:10 UTC, s0undt3ch commented on salt/utils/parsers.py
> +                ", ".join(insecure_log()),
> So yes, its respected. It looks cleaner to me to have that line break, but its not required if you want to remove it.

If it's respected, leave it.

2023-10-16 18:42 UTC, s0undt3ch approved these changes, later dismissed

2023-10-17 19:53 UTC, whytewolf approved these changes

2023-10-17 19:54 UTC, merged