fire event at job start
saltstack/salt pull request #65405
Opened 2023-10-16 10:28 UTC by Legrems

### What does this PR do?
We ran into some issues with a large amount of minions in our salt cluster. We wanted an ack from minions that they were starting job. The `salt/job/<jid>/new` wasn't enough, since it doesn't imply that the job will/have ever be started.

This PR make salt-minion fire an even when a minion start a job.

*This code was meant to be deployed in our production, so the patch were made to be as faulty resistent as possible (hence the decorators for `*args` and `**kwargs`, in a non-existent file)*

### What issues does this PR fix or reference?
Unsure if any similar issue was created for this particular wanted behaviour

### New Behavior
The salt-minion now fire an event under `custom/job/<jid>/started/<minion_id>`  when starting a job.

### Merge requirements satisfied?
- [x] Docs
- [X] Changelog => No issue for this?
- [ ] Tests written/updated
  - No tests written, but i'm open to writting them if this is a wanted feature for salt

### Commits signed with GPG?
Yes

2023-10-16 17:07 UTC, s0undt3ch commented
Personally, I'd prefer calling it explicitly instead of using a decorator...
I know its a lot of duplicate code.

Alternatively, create a utility function and call that out in the function bodies(instead of using the decorator).

2023-11-07 07:23 UTC, dwoz requested changes
This is a new feature and the PR should be against master, not 3006.x

2024-06-21 03:24 UTC, dwoz commented
> This is a new feature and the PR should be against master, not 3006.x

@Legrems Are you able to port this to the master branch please?

2025-03-25 19:48 UTC, twangboy requested changes
Needs to be created against the master branch. Also needs a changelog and some tests.

2026-06-17 07:50 UTC, dwoz commented
This was implimented: https://github.com/saltstack/salt/pull/69013

2026-06-17 07:50 UTC, closed without merging