[master] Add autosign_grains to auth events with action 'pend'
saltstack/salt pull request #65426
Opened 2023-10-18 12:10 UTC by thus

### What does this PR do?

It adds the "autosign_grains" that the minion sends during auth to the auth event that the master sends. This enables us to create a runner to do more cool autosign stuff (more than just shared secrets, which is already supported by autosign_grains).

To enable it, the option `auth_events_pend_autosign_grains` is added. By default it is false. When enabled, it only passes on the "autosign_grains" when the action is pending. This means that it not added any more when a key is accepted, rejected or denied.

Example auth event (with autosign grains):
```
salt/auth       {
    "_stamp": "2023-10-18T11:57:23.212718",
    "act": "pend",
    "id": "test.example.com",
    "pub": "<REDACTED>",
    "autosign_grains": {
        "autosign_key": "abcdefgh"
    }
}
```
As far as I can see, people has wanted something similar in the past: #37712, #43394, #56189 (all closed issues)

In addition to this, I also fixed so all auth events have the "act" field set (#56200) and moved variables that was only used when auth events were enabled.

### What issues does this PR fix or reference?
Fixes: #56200
(not the main goal of the PR, but I had to touch that part of the code anyway)

### New Behavior
Add "autosign_grains" to auth events when "act" is "pend".

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-11-12 19:24 UTC, thus commented
What is the timeline for reviewing this PR?

Please let me know if there is anything I can do to help or if there is anything missing that I should fix.

2023-11-27 13:10 UTC, thus commented
@felippeb: bump! :)

2023-12-08 19:57 UTC, twangboy approved these changes

2023-12-08 21:22 UTC, twangboy requested changes

2023-12-08 21:22 UTC, twangboy commented on doc/ref/configuration/master.rst
> +---------------
This underline needs to be the full length of the title, to include the backticks

2023-12-08 21:34 UTC, thus commented
Thanks, @twangboy!

Do you want the changes in this PR or should I create a new branch, open a new PR and close this one? My experience is that different project teams have different preferences regarding this :)

2023-12-08 21:35 UTC, twangboy commented
Just make the changes in this branch. You'll need to pull since I rebased this PR.

2024-02-23 09:03 UTC, thus commented
Sorry for the delay, I had some other projects I needed to finish first. I have now rebased with master, and I'm working on implementing the changes you wanted.

2024-02-26 15:11 UTC, twangboy submitted a review, later dismissed

2024-04-17 11:08 UTC, thus commented
Any plans for when this PR will be merged? 😊

2024-04-17 15:31 UTC, twangboy commented
Probably need to change the `.. versionadded` to 3008 now.

2024-04-18 20:10 UTC, tazaki commented
Would also love to see this added to a release! +1

2024-04-28 20:13 UTC, thus commented
Bumped the version added to 3008, and fixed a typo I made in the documentation :)

2024-05-06 20:34 UTC, thus commented
Any chance of getting a new review? :smile:

2024-05-13 18:00 UTC, twangboy approved these changes

2024-05-13 18:54 UTC, thus commented
@twangboy: I hit the wrong button, sorry!

2024-05-13 19:53 UTC, twangboy approved these changes

2024-07-25 19:38 UTC, thus commented
Any chance of getting this merged soon? 😊

2024-09-03 11:47 UTC, thus commented
@twangboy: bump! :)

2024-09-18 19:05 UTC, twangboy requested changes
Would you mind looking at the conflict?

2024-10-18 01:51 UTC, tazaki commented
@thus if you have time to fix that would be great!

2024-10-18 07:57 UTC, thus commented
@twangboy, @tazaki: The conflict was due to a trivial and non-related change. It is resolved now :)

2024-10-25 22:23 UTC, twangboy approved these changes, later dismissed

2025-08-06 21:24 UTC, twangboy commented
Need to resolve conflicts

2025-08-28 23:55 UTC, tazaki commented
@thus home stretch! Can you fix please?

2025-09-03 18:08 UTC, thus commented
Sorry for the late reply. I'll take a look at fixing it as soon as possible.

2025-09-05 13:21 UTC, thus commented
Took longer than expected to rebase because there was lots of merge conflicts, but it should now be fixed. It would be awesome to finally get this functionality in Salt :)

2025-09-15 20:55 UTC, twangboy submitted a review, later dismissed

2026-03-12 20:18 UTC, thus commented
Any chance of merging this, trivial but highly useful, change soon? 😅

2026-03-17 21:35 UTC, twangboy commented
Yes, we're trying to get these in over the next few weeks. Could you address the pre-commit failures?

2026-03-17 23:24 UTC, thus commented
@twangboy, I have fixed the pre-commit failures now. Black was complaining that it made changes to one of the files in the commit.

2026-03-18 22:13 UTC, dwoz approved these changes

2026-03-18 22:14 UTC, merged