Increase coverage for textfsm module
saltstack/salt pull request #65454
Opened 2023-10-24 19:27 UTC by garethgreenaway

### What does this PR do?
Increase coverage for textfsm module

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-10-24 20:05 UTC, twangboy submitted a review, later dismissed

2023-11-06 18:23 UTC, s0undt3ch requested changes

2023-11-06 18:23 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +]
```suggestion
textfsm = pytest.importorskip("textfsm", reason="Install textfsm to be able to run this test.")
```

2023-11-06 18:23 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                        clitable, "open", mock_open(read_data=mock_read_data)
```suggestion
                        textfsm.clitable, "open", mock_open(read_data=mock_read_data)
```

2023-11-06 18:23 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                        clitable, "open", mock_open(read_data=mock_read_data)
```suggestion
                        textfsm.clitable, "open", mock_open(read_data=mock_read_data)
```

2023-11-06 18:23 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                        clitable, "open", mock_open(read_data=mock_open_index)
```suggestion
                        textfsm.clitable, "open", mock_open(read_data=mock_open_index)
```

2023-11-16 11:21 UTC, s0undt3ch requested changes
Basically, only deep nest if we really need to.

2023-11-16 11:21 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +@pytest.fixture()
```suggestion
@pytest.fixture
```

2023-11-16 11:21 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +def test_virttual_virtual():
```suggestion
def test_dunder_virtual():
```

2023-11-16 11:21 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                            }
```suggestion
    with patch.object(textfsm_mod, "HAS_CLITABLE", True), patch.dict(
        textfsm_mod.__opts__, {"textfsm_platform_grain": "textfsm_platform_grain"}
    ), patch.dict(
        textfsm_mod.__grains__,
        {"textfsm_platform_grain": "textfsm_platform_grain"},
    ), patch.dict(
        textfsm_mod.__salt__,
        {"cp.cache_dir": MagicMock(return_value="/path/to/cache/")},
    ), patch.object(
        textfsm_mod.clitable,
        "open",
        mock_open(read_data=mock_open_index),
    ), patch.dict(
        textfsm_mod.__salt__,
        {"cp.get_file_str": MagicMock(return_value=False)},
    ):
        ret = textfsm_mod.index(
            command="sh ver",
            platform="",
            output_file="salt://textfsm/juniper_version_example",
            textfsm_path="salt://textfsm/",
        )
        assert ret == {
            "out": None,
            "result": False,
            "comment": "Unable to read from salt://textfsm/juniper_version_example. Please specify a valid file or text.",
        }
```

2023-11-16 11:21 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                            }
We really don't need to deep nest this...

2023-11-16 11:21 UTC, s0undt3ch commented on tests/pytests/unit/modules/test_textfsm_mod.py
> +                            }
Same as above, too much nesting.

2023-11-16 21:59 UTC, s0undt3ch approved these changes, later dismissed

2023-12-20 20:23 UTC, twangboy approved these changes, later dismissed

2024-02-14 21:32 UTC, twangboy submitted a review, later dismissed

2024-03-06 15:11 UTC, twangboy approved these changes

2024-03-06 15:19 UTC, s0undt3ch approved these changes

2024-03-06 15:19 UTC, merged