[WIP] Duplicate `arm64` repo paths for rpm-based distros to `aarch64` paths
saltstack/salt pull request #65455
Opened 2023-10-24 20:56 UTC by MKLeb

### What does this PR do?
See title

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65198
See also: https://github.com/saltstack/salt/pull/65205

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-10-25 07:50 UTC, s0undt3ch submitted a review, later dismissed

2023-11-08 18:12 UTC, s0undt3ch commented on tools/ci.py
> +            Bucket="salt-project-prod-salt-artifacts-release", Prefix=prefix
```suggestion
            Bucket=f"salt-project-{tools.utils.SPB_ENVIRONMENT}-salt-artifacts-release", Prefix=prefix
```

2023-11-14 22:52 UTC, MKLeb commented
New passing staging run: https://github.com/MKLeb/salt/actions/runs/6867077920

2023-11-16 16:54 UTC, MKLeb commented
Final passing staging run: https://github.com/MKLeb/salt/actions/runs/6880738359

2023-11-16 17:46 UTC, s0undt3ch requested changes

2023-11-16 17:46 UTC, s0undt3ch commented on tools/ci.py
> +                )
```suggestion
                if backend == "classic":
                    session += "-classic"
                _matrix.append(
                    {
                        "test-chunk": session,
                        "version": str(version),
                    }
                )
                if backend == "relenv" and fips is True and distro_slug.startswith(("photonos-4", "photonos-5")):
                    # Repeat the last one, but with fips
                    _matrix.append({"fips": "fips", **_matrix[-1]})
```

2023-11-17 07:08 UTC, MKLeb commented
https://github.com/MKLeb/salt/actions/runs/6895006120

2023-11-17 18:06 UTC, s0undt3ch approved these changes

2023-11-19 19:42 UTC, merged