Update SSH wrappers, wrap more funcs
saltstack/salt pull request #65517
Opened 2023-11-06 14:59 UTC by lkubb

### What does this PR do?
* Updates existing wrapper modules to be mostly in sync with the respective execution modules.
* Wraps most `cp.*` functions.
* Adds `slsutil` wrapper
* Adds `cmdmod` wrapper for `cmd.script`
* Makes `cp.cache_file` add the respective files to the filerefs tar that is sent to the minion during state runs

Based on https://github.com/saltstack/salt/pull/64576, which would have to be merged beforehand.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/61100
Fixes: https://github.com/saltstack/salt/issues/56441
Fixes: https://github.com/saltstack/salt/issues/65067
Fixes: https://github.com/saltstack/salt/issues/61143
Fixes: https://github.com/saltstack/salt/issues/50196
Fixes: https://github.com/saltstack/salt/issues/48067

Partially: https://github.com/saltstack/salt/issues/61426
Helps with: https://github.com/saltstack/salt/issues/31531
Helps with: https://github.com/saltstack/salt/issues/19564

### Previous Behavior
* Confusing behavior when module calls behave differently via `salt-ssh` than usual
* (see linked issues, many more would have been possible)
* Jinja imports in managed file templates would fail. The workaround was to specify `extra_filerefs` before applying states, either via CLI param or in the Saltfile. This PR allows to declare those dependencies in the state files themselves.

### New Behavior
Works mostly the same as regular Salt.

### Merge requirements satisfied?
- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-11-16 22:33 UTC, twangboy submitted a review, later dismissed

2023-11-17 11:33 UTC, s0undt3ch requested changes
This is adding functionality, so, it shouldn't be targeted to 3006.x

2023-12-18 20:55 UTC, twangboy submitted a review, later dismissed

2023-12-20 15:44 UTC, s0undt3ch reviewed
Test failure looks related

2024-01-02 10:07 UTC, s0undt3ch approved these changes, later dismissed

2024-01-02 21:17 UTC, merged