feat: allow configurable destination for netbox ext_pillar data
saltstack/salt pull request #65531
Opened 2023-11-09 19:18 UTC by raddessi

### What does this PR do?
This adds support to allow the user to configure in what pillar key the netbox ext_pillar data gets populated in. For example I already use the `netbox` pillar for server and client configuration and there are a few overlapping keys there. Personally I would prefer to leave the existing config as-is and then move the minion data in to the pillar location `netbox:minion`.

### What issues does this PR fix or reference?
I didn't open an issue for this since it seemed like a trivial addition for me to just add and ask for opinions on afterwards.

### Previous Behavior
The netbox minion data would always be populated in the `netbox` pillar.

### New Behavior
The netbox minion data will be populated in the `netbox` pillar by default but the user can now specify the pillar location they would like it placed in to, optionally.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-11-09 19:20 UTC, raddessi commented on tests/pytests/unit/pillar/test_netbox.py
> +
I just copied the full test so this could be cleaned up for sure. I can add a minimal response fixture that is dedicated for this test if wanted.

2023-11-09 19:22 UTC, raddessi commented on salt/pillar/netbox.py
> +    data should be populated. This lets put the data in the pillar at
What's a cleaner way to say this?

2023-11-09 19:23 UTC, raddessi commented
@ggiesen you may want to comment here? Thanks!

2023-11-09 21:21 UTC, raddessi commented
the logic doesn't work, I will update

2023-11-09 21:44 UTC, raddessi commented on tests/pytests/unit/pillar/test_netbox.py
> +
Scratch that, I have now copied the fixture data also. In theory we could deduplicate this a little now if you would like.

2023-11-12 00:15 UTC, raddessi commented
Looks like the current test failure may be unrelated?

2025-04-01 16:01 UTC, twangboy requested changes

2025-04-01 16:01 UTC, twangboy commented on salt/pillar/netbox.py
> +    data should be populated. This lets put the data in the pillar at
How about this from ChatGPT:
A colon-delimited string representing a nested path within the pillar where the data should be placed. This allows flexibility in organizing pillar data. For example, you can store the data under netbox:minion or an-arbitrary-location, which is useful if you already use the netbox pillar and need to avoid key conflicts within it.

2025-04-01 16:22 UTC, raddessi commented on salt/pillar/netbox.py
> +    data should be populated. This lets put the data in the pillar at
I'll update this PR tonight, thanks!

2026-03-18 15:59 UTC, twangboy commented
Please rebase and address merge conflicts.

2026-06-17 05:07 UTC, dwoz approved these changes

2026-06-17 05:07 UTC, merged