Added deprecation warning for Salt's backport of OrderedDict class removal in 3009
saltstack/salt pull request #65542
Opened 2023-11-13 17:12 UTC by dmurphy18

### What does this PR do?
Added deprecation warning for Salt's backport of OrderedDict class removal in 3009

### What issues does this PR fix or reference?
Fixes: 

### New Behavior
Deprecation warning issued about removal of Salt's backport of OrderedDict added in Python 2 days, recommending use of Python 3 OrderedDict.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2023-11-14 16:40 UTC, twangboy approved these changes, later dismissed

2023-11-14 16:52 UTC, s0undt3ch requested changes

2023-11-14 16:52 UTC, s0undt3ch commented on changelog/65542.deprecated.md
> +Deprecation warning for Salt's backport of OrderedDict class which wil be removed in 3009
```suggestion
Deprecation warning for Salt's backport of ``OrderedDict`` class which will be removed in 3009
```

2023-11-14 16:52 UTC, s0undt3ch commented on salt/utils/odict.py
> +                    "Please use Python 3 `OrderedDict`.",
```suggestion
                    "Please import `OrderedDict` from `collections`.",
```

2023-11-15 20:13 UTC, s0undt3ch requested changes

2023-11-15 20:13 UTC, s0undt3ch commented on salt/utils/odict.py
> +                    category=FutureWarning,
```suggestion
                    category=DeprecationWarning
```

2023-11-15 20:28 UTC, dmurphy18 commented on salt/utils/odict.py
> +                    category=FutureWarning,
done

2023-11-15 21:13 UTC, s0undt3ch submitted a review, later dismissed

2023-11-16 12:39 UTC, s0undt3ch approved these changes

2023-11-16 12:39 UTC, merged