Salt Cloud: Put cleanup in a try/except block
saltstack/salt pull request #65586
Opened 2023-11-17 21:08 UTC by twangboy

### What does this PR do?
In a previous attempt to have PSExec clean up after itself, we started calling the cleanup command. This doesn't always work and will raise an exception. This shouldn't be a blocker to a successful installation of Salt, so this PR puts that command in a Try/Except block. If it fails to cleanup the PAexec binaries, it should still continue.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65584

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-11-18 09:47 UTC, s0undt3ch requested changes

2023-11-18 09:47 UTC, s0undt3ch commented on salt/utils/cloud.py
> +            log.debug("Exception cleaning up PAexec: %s", repr(exc))
```suggestion
            log.debug("Exception cleaning up PAexec: %r", exc)
```
Info you really want a `repr()` of an exception....

2023-11-18 09:47 UTC, s0undt3ch commented on tests/pytests/unit/utils/test_cloud.py
> +        mock_client.return_value.cleanup = MagicMock(side_effect=CannotDelete)
```suggestion
        mock_client.return_value.cleanup = MagicMock(side_effect=CannotDelete())
```
The side effect should most likely be the class instance, not the class itself.

2023-11-20 18:10 UTC, s0undt3ch approved these changes

2023-11-22 00:42 UTC, garethgreenaway approved these changes

2023-11-22 00:42 UTC, merged