Add pruning option to file.keyvalue
saltstack/salt pull request #65640
Opened 2023-11-29 00:35 UTC by tacerus

### What does this PR do?

This implements a new optional argument "prune" in the file.keyvalue state function, which, if set to True, deletes lines not configured using the "key_values" or "key"/"value" arguments as part of the execution. Useful for ensuring a file only contains the desired key/value pairs and no additional data.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65631

### Previous Behavior

`prune` was not a valid argument.

### New Behavior

`prune` is a a valid argument! :-)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2025-04-04 17:41 UTC, twangboy requested changes
If we get this in it will be part of 3008

2025-04-04 17:41 UTC, twangboy commented on salt/states/file.py
> +        .. versionadded:: pls.help
3008.0

2025-04-04 20:11 UTC, tacerus commented on salt/states/file.py
> +        .. versionadded:: pls.help
Thanks!

2025-04-09 20:56 UTC, twangboy approved these changes, later dismissed
Once the nightly builds are green we'll need to rebase this.

2026-01-30 22:31 UTC, merged