Artifactory module basic auth fix
saltstack/salt pull request #65642
Opened 2023-11-29 08:57 UTC by ubrix

### What does this PR do?
This fixes issue with basic auth causing invalid header error and 401 Bad Request. Using HTTPBasicAuthHandler instead of header.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/58936

### Previous Behavior
When setting username and password you received an error.

### New Behavior
When setting username and password it works.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2023-12-18 05:06 UTC, dwoz requested changes
Needs changelog

2023-12-18 15:11 UTC, ubrix commented
> Needs changelog

Added changelog

2023-12-18 15:39 UTC, twangboy submitted a review, later dismissed

2023-12-20 20:15 UTC, twangboy approved these changes

2023-12-28 09:14 UTC, merged