Merge forward
saltstack/salt pull request #65690
Opened 2023-12-13 02:02 UTC by dwoz

Merge forward

2023-12-13 05:43 UTC, s0undt3ch requested changes
```
pre-commit run -v pyupgrade --files (git diff --name-only HEAD~250 HEAD); and git commit -a -m 'Run `pyupgrade` against the files modified in the merge-forward'
```
Run that until it finally commits(should be twice)

2023-12-13 09:07 UTC, s0undt3ch approved these changes

2023-12-14 11:36 UTC, s0undt3ch commented
Now that the `3007.x` branch exists, the merge forward from `3006.x` should be `3006.x` -> `3007.x` -> `master`

https://github.com/saltstack/salt/pull/65699

2023-12-14 22:03 UTC, dwoz commented
> Now that the `3007.x` branch exists, the merge forward from `3006.x` should be `3006.x` -> `3007.x` -> `master`
> 
> #65699

Not until we freeze 3007.x. Right now I'm keeping 3007.x up to date with the head of master.

2023-12-14 22:09 UTC, closed without merging