Fix __salt__ when used via __utils__
saltstack/salt pull request #65696
Opened 2023-12-14 00:24 UTC by dwoz

### What does this PR do?

Making NameLoaderContext return a proper value for __bool__ (instead of almost always returning True) broke the usage of `__salt__` via `__utils__`. https://github.com/saltstack/salt/commit/989790cb90687d0bb8ec7a51135d693453ba62bc

This PR fixes `__salt__` for salt.utils.bootmod and other utils modules.

### What issues does this PR fix or reference?

Fixes: #65691

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

2023-12-14 10:39 UTC, s0undt3ch requested changes

2023-12-14 10:39 UTC, s0undt3ch commented on tests/pytests/unit/loader/test_loader.py
> +        loader["mymod.foobar"]()
```suggestion
def test_named_loader_context_name_not_packed(tmp_path):
    opts = {
        "optimization_order": [0],
    }
    py_mod_contents = """
    from salt.loader.dunder import loader_context
    __not_packed__ = loader_context.named_context("__not_packed__")
    def foobar():
        return __not_packed__["not.packed"]()
    """
    with pytest.helpers.temp_file("mymod.py", py_mod_contents, directory=tmp_path):
        loader = salt.loader.LazyLoader([tmp_path], opts)
        with pytest.raises(
            salt.exceptions.LoaderError,
            match="LazyLoader does not have a packed value for: __not_packed__",
        ):
            loader["mymod.foobar"]()
```

2023-12-15 10:01 UTC, s0undt3ch approved these changes, later dismissed

2023-12-18 08:36 UTC, dwoz commented
@s0undt3ch tests should pass now.

2023-12-18 11:21 UTC, s0undt3ch submitted a review, later dismissed

2023-12-19 13:12 UTC, s0undt3ch approved these changes, later dismissed

2023-12-22 16:47 UTC, merged