Handle regular expressions which do not not use grouping
saltstack/salt pull request #65708
Opened 2023-12-15 11:32 UTC by vin01

### What does this PR do?

Handle regular expressions which do not not use grouping in `regex_search` and `regex_match`

### Previous Behavior

```
FAILED tests/pytests/functional/modules/state/test_jinja_filters.py::test_filter[regex_match_ungrouped0] - assert {'ret': '()'} == {'ret': "('1.abc',)"}
FAILED tests/pytests/functional/modules/state/test_jinja_filters.py::test_filter[regex_match_ungrouped1] - assert {'ret': '()'} == {'ret': "('1.abc',)"}
```

### New Behavior

Entire match is returned as a tuple.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2023-12-17 01:32 UTC, dwoz requested changes
Looks okay to me but we'll need a test case and changelog. Ideally there would also be an open issue with an explanation of what we're fixing.

2023-12-17 21:00 UTC, vin01 commented
> Looks okay to me but we'll need a test case and changelog. Ideally there would also be an open issue with an explanation of what we're fixing.

I had added [a couple](https://github.com/saltstack/salt/pull/65708/commits/fd4f6d2a704f733185f1661ccd848c8405667c5f) of functional state tests already, wouldn't that fly? :)

Added an issue and corresponding changelog entry, I skipped it initially as I presumed this behavior might be intentional and up for a bit of discussion.

2023-12-18 11:43 UTC, dwoz approved these changes
@vin01 

Approved, but also asking for @whytewolf and @s0undt3ch to have a look.

2023-12-18 12:35 UTC, s0undt3ch approved these changes

2024-01-15 10:55 UTC, vin01 commented
this branch is getting out of date, please feel free to update and merge if you think this is ready now.

2024-01-15 16:41 UTC, whytewolf approved these changes

2024-02-21 20:59 UTC, vin01 commented
can this be merged please?

2025-04-04 17:05 UTC, twangboy approved these changes

2025-06-25 23:51 UTC, merged