Add timeout parameter to lxc.stop
saltstack/salt pull request #65700
Opened 2023-12-14 12:55 UTC by gregorg

### What does this PR do?

Add parameter `timeout` to lxc.stop module.

2023-12-14 23:50 UTC, dwoz requested changes
This needs a changelog entry and preferably a test too.

2023-12-18 07:33 UTC, dwoz commented
@gregorg pre-commit is now failing.

2023-12-20 20:04 UTC, twangboy approved these changes

2024-01-03 07:23 UTC, gregorg commented
> This needs a changelog entry and preferably a test too.

Done.

2024-01-03 18:30 UTC, twangboy approved these changes

2025-04-02 19:04 UTC, closed without merging