Introduce fc_host grain
saltstack/salt pull request #65751
Opened 2023-12-27 15:01 UTC by tacerus

New grain to assess whether the minion is a fiber channel host.

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65750

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

Hi,

- Is this fine in core or should I move it to extra?
- What tests could I add for this? I checked tests for other grains in `tests/pytests/unit/grains/test_core.py` but I couldn't find how mocked files under /proc, /sys are created.

Would appreciate any pointers.

2025-03-31 19:19 UTC, twangboy requested changes
I think the name of this grain should be more descriptive, especially since the value is just ``True`` or ``False``. Something like ``fiber_channel_host`` instead to be clear what the grain is describing. Also, please provide a simple test.

2025-03-31 20:25 UTC, tacerus commented
>  Something like fiber_channel_host instead to be clear what the grain is describing

Sure, can adapt.

> Also, please provide a simple test.

Seems back then I asked for advice in the PR description but there wasn't any feedback :-) .. I figured out how to work the test suite in the meanwhile, so, added now.

2025-03-31 20:30 UTC, tacerus commented
Actually after changing it, I'm not so sure about "fiber_channel_host", because both "fiber" and "fibre" are valid spellings, and it can be unintuitive for a user having to figure out and remember the right spelling.

2025-03-31 21:31 UTC, twangboy approved these changes, later dismissed

2025-03-31 21:36 UTC, tacerus commented
I changed it to `fibre` now as it seems to be the more widely accepted form in the context of computing.

The "CI / Test Salt / Ubuntu 24.04 integration zeromq (pull_request) CI / Test Salt / Ubuntu 24.04 integration zeromq" failure seems unrelated to my patch.

2025-08-06 21:34 UTC, whytewolf commented
so, I never seemed to get pinged on this. but i think i should put in my two cents here. true and false are not exactly useful. more useful would be the fibre info if it is a fibre host such as WWN etc. and just not list fibre if it isn't. this would still trigger truthiness in tests. AND give needed information if it is. I know i have had to search for WWN's in a lot of places before so just having the info already available would be a step in the right direction. 

```
fibre:
  hba0:
    wwn: '5A:CD:E4:82:34:56:78:98'
    ...
```

2025-08-06 21:39 UTC, tacerus commented
Hi @whytewolf. In my case it is useful as we set kernel parameters based on whether the host is FC enabled (true or false). I understand there might be other use cases where evaluating the WWNs makes sense, but we already have ` salt.grains.fibre_channel.fibre_channel_wwns()` for this purpose - the grain introduced here is intended to be a "light" version where one does not want to enable comparatively expensive evaluation of WWNs but still wants to find out whether a minion is hosting FC.

2026-03-17 21:02 UTC, merged