Allow keyword arguments for the fileserver roots backend update function.
saltstack/salt pull request #65819
Opened 2024-01-09 10:30 UTC by ycedres

### What does this PR do?

When an orchestration state is applied the user responsible for the runner is passed to the `update` function as the `__pub_user` keyword argument. Therefore, the `update` function must be aware of this or the orchestration state application will fail.

### Previous Behavior
The application of this example orchestration state fails
```
my_orch:
  salt.runner:
    - name: fileserver.update
```
whit the following error:
` Passed invalid arguments: update() got an unexpected keyword argument '__pub_user'`

### New Behavior
Now the orchestratin state is applied correctly.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-01-16 16:57 UTC, meaksh requested changes
The same issue happens for other fileserver backends, like `gitfs`. I would rather go by excluding the `__pub_user` from the kwargs we propagate when calling update to the `Fileserver`, here:

https://github.com/saltstack/salt/blob/master/salt/runners/fileserver.py#L353

2025-04-02 15:17 UTC, twangboy requested changes

2025-04-02 15:17 UTC, twangboy commented on tests/integration/runners/test_fileserver.py
>          """
This test needs to be migrated to pytests. We are no longer accepting non-pytest tests.

2026-03-17 22:16 UTC, twangboy commented
Please rebase and resolve conflicts

2026-03-23 13:59 UTC, twangboy approved these changes

2026-03-24 16:58 UTC, merged