deprecate the use of egrep in favor of grep -E
saltstack/salt pull request #65864
Opened 2024-01-15 11:01 UTC by leifliddy

### What does this PR do?
It changes all uses of `egrep` --> `grep -E`
`egrep` has been deprecated since 2007, so it's about time we adopted the new `grep -E` format. 

No need to write a unit test as `egrep` is functionally equivalent to `grep -E`  

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/65608

### Previous Behavior
The use of `egrep` with Fedora 39 spits out an error message that causes errors with salt states that use it.

### New Behavior
Salt states that use `grep -E` are now functional (on Fedora 39)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2025-04-04 16:48 UTC, twangboy requested changes
This needs to be rebased and the conflicts fixed.

2026-03-17 21:34 UTC, dwoz commented
@leifliddy Please rebase this. :pray:

2026-03-20 21:47 UTC, twangboy commented
`salt/modules/csf.py` was removed as part of the great module migration

2026-03-25 22:12 UTC, leifliddy commented
@dwoz These last couple years have been pretty brutal for me. I suffered a TBI (traumatic brain injury) from a motorcycle accident. 
I'm mostly recovered now, but there  are gaps in what I can recall. I was never a git savant to begin with. Could you please list the commands needed to rebase this? I'll add them to my notes for future use. 

Thanks.

2026-03-30 21:57 UTC, dwoz commented
@leifliddy I am very sorry to hear this but am glad to hear you've been recovering. We'll get this rebased for you.

2026-04-05 10:00 UTC, merged