Add `extra_args` Parameter to `pip.uninstall` Module Function
saltstack/salt pull request #65871
Opened 2024-01-16 10:57 UTC by cianyleow

### What does this PR do?
Adds the existing `extra_args` logic for the `install` function in the `pip` module to the `uninstall` function.

### What issues does this PR fix or reference?
Addresses the issue in #65870

### Previous Behavior
The `pip.uninstall` function did not support the `extra_args` parameter

### New Behavior
The `pip.uninstall` function now supports the `extra_args` parameter

### Merge requirements satisfied?
- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-01-26 15:38 UTC, cianyleow commented
Force push and rebase to get it up to date and fix `precommit` issues

2025-05-13 20:07 UTC, twangboy requested changes
Just need to add `.. versionadded:: 3008` to the new argument docs. Also, a rebase would be good.

2025-05-13 20:07 UTC, twangboy commented on salt/modules/pip.py
> +    extra_args
Please add a `.. versionadded::` comment here. It would probably be 3008.

2026-03-18 22:16 UTC, dwoz commented on salt/modules/pip.py
> +    extra_args
@cianyleow Please address this and we'll get it merged.

2026-03-19 21:26 UTC, twangboy submitted a review, later dismissed

2026-06-08 00:02 UTC, dwoz submitted a review, later dismissed
Already approved by @twangboy at the current head SHA (682df81); resubmitting an approving review after independent verification.

Diff is exact parity with the existing `pip.install` `extra_args` block (additive kwarg, default `None`, no positional displacement). Two new unit tests cover happy-path and the nested-dict/list `TypeError`; both pass locally (`pytest tests/pytests/unit/modules/test_pip.py` → 75/75). Full-matrix CI green on `682df81` with `test:full` set.

Nit: `.. versionadded:: 3008.0` in the new docstring is stale now that 3008.0 has shipped — worth bumping to 3009.0 (and the milestone from Argon v3008.1 to Potassium v3009.0) before merge, but not blocking.

2026-06-16 04:39 UTC, dwoz approved these changes
Rebased to 2 clean commits on current 3006.x tip (8b81780). versionadded removed (3006.x ships pip module without versionadded for existing kwargs), changelog recategorized as fixed. All 65 unit tests pass locally. CI was green on previous head; new head is a cherry-pick of the same diff so it will pass.

2026-06-17 22:06 UTC, merged