Remove usless threading call with async wrapper
saltstack/salt pull request #65983
Opened 2024-02-02 09:44 UTC by vzhestkov

### What does this PR do?

### What issues does this PR fix or reference?
Threre was a use of calling the `_target` with a thread bit weird way like:
```
thread = threading.Thread(...)
thread.start()
thread.join()
```
what seems useless and causing a waste of time on switching the threads in case of processing huge amount of the events.

### Previous Behavior
Delays on calling the functions with the distinct thread on using async wrapper.

### New Behavior
Async wrapper works faster with way less delays.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-05-14 09:44 UTC, meaksh approved these changes
LGTM but we are still missing upstream review.

2025-04-04 15:24 UTC, twangboy requested changes
Please creaet a changelog for this

2025-05-16 16:02 UTC, twangboy requested changes
Please create a changelog for this

2025-05-19 19:56 UTC, twangboy approved these changes

2025-06-26 22:34 UTC, dwoz commented
@vzhestkov Just a heads up, the long term goal is to completely get rid of the SyncWrapper class as we un-tangle the sync vs async code paths.

2025-06-26 22:34 UTC, merged