Fix exceptions being set on completed futures
saltstack/salt pull request #66011
Opened 2024-02-06 17:50 UTC by cianyleow

### What does this PR do?
Fixes an issue in the ZeroMQ transport where caught exceptions were being set on futures that had already completed (i.e. done) and were logging lots of error messages.

### What issues does this PR fix or reference?
Fixes: #66006

### Previous Behavior
Attempts to set an exception on a future, regardless if it is `done` or not, resulting in error messages.

### New Behavior
Attempts to set an exception on a future, _iff_ it is not `done`.

### Merge requirements satisfied?
- [✓] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated (couldn't figure out a nice way to test this)

### Commits signed with GPG?
Yes

2024-02-06 18:09 UTC, whytewolf commented
fixes should be against 3006.x also this is going t need tests.

2024-02-06 20:18 UTC, dwoz requested changes
@cianyleow Are you able to write a regression test for this please?

2024-02-11 21:45 UTC, cianyleow commented
@whytewolf I've updated to `3006.x` as the base branch / @dwoz I've written some tests, let me know what you think.

2024-02-14 21:33 UTC, dwoz approved these changes, later dismissed

2024-02-16 12:07 UTC, s0undt3ch approved these changes

2024-02-16 21:08 UTC, merged