Make rpms more universal by replacing systemd_* scriptlets with RHEL7/8 styled forward-compatible definitions
saltstack/salt pull request #66030
Opened 2024-02-08 16:54 UTC by ScriptAutomate

### What does this PR do?

Uses systemd_* scriptlet definitions from RHEL 7/8 that are forward-compatible with RHEL 9, allowing for the RPMs to be built on newer systems while the built artifacts are still compatible with RHEL 7/8/9.

### What issues does this PR fix or reference?
Fixes: #65987

### Previous Behavior

`systemd_*` scriptlet definitions were not compatible with RHEL 7/8 systems (including Photon OS 3, Photon OS 4, AlmaLinux 8, etc.).

### New Behavior

`systemd_*` scriptlet definitions were used from RHEL 7/8 build macros, allowing for more universal compatibility on RHEL 7/8/9 systems, regardless of OS that package is built on. Definitions have been tested on RHEL 9 systemd and work as expected.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-02-08 17:18 UTC, ScriptAutomate commented
Requires a test review and updates to:

- [`tests/pytests/pkg/upgrade/test_salt_upgrade.py`](https://github.com/saltstack/salt/blob/3006.x/tests/pytests/pkg/upgrade/test_salt_upgrade.py)
- [`tests/pytests/pkg/upgrade/test_salt_downgrade.py`](https://github.com/saltstack/salt/blob/3006.x/tests/pytests/pkg/downgrade/test_salt_downgrade.py)

The upgrades and downgrades need to:

- Prior to downgrade/upgrade: Grab pid of currently running service(s)
- After downgrade/upgrade: Grab pid of currently running service(s)
- Verify that the pids differ, which would show that the services have restarted

[`tests/pytests/pkg/integration/test_systemd_config.py`](https://github.com/saltstack/salt/blob/3006.x/tests/pytests/pkg/integration/test_systemd_config.py) might be a good reference point for how to retrieve the information via systemd, since that is what is being managed here.

2024-02-13 21:36 UTC, s0undt3ch submitted a review, later dismissed
Don't know enough to validate the spec file changes.
@dwoz or @dmurphy18 ?

2024-02-14 16:46 UTC, twangboy approved these changes, later dismissed

2024-02-14 16:54 UTC, dmurphy18 requested changes
need to check comments for post

2024-02-14 16:54 UTC, dmurphy18 commented on pkg/rpm/salt.spec
> +if [ $1 -eq 1 ] ; then
-eq 1 is an install, but you are neglecting upgrade that is '$1` == 2' where you would want to restart the salt-xxx if it was already running.

Do you need an 
if [ $1 -gt 1 ] ; then
  systemctl retry-restart salt-xxxx.service > /dev/null 2>&1 || :+1: 
else
 systemctl preset salt-xxxx.service > /dev/null 2>&1 || :
fi

2024-02-14 16:54 UTC, dmurphy18 commented on pkg/rpm/salt.spec
> +if [ $1 -eq 1 ] ; then
see above

2024-02-14 16:54 UTC, dmurphy18 commented on pkg/rpm/salt.spec
> +if [ $1 -eq 1 ] ; then
see above

2024-02-14 16:54 UTC, dmurphy18 commented on pkg/rpm/salt.spec
> +if [ $1 -eq 1 ] ; then
see above

2024-02-14 18:21 UTC, dmurphy18 approved these changes

2024-02-14 18:26 UTC, twangboy approved these changes

2024-02-14 18:32 UTC, s0undt3ch approved these changes

2024-02-14 21:24 UTC, merged