[3006.x][BACKPORT] Fix utf8 handling in 'pass' renderer and make it more robust #64300
saltstack/salt pull request #66033
Opened 2024-02-09 08:35 UTC by mbebjak

### What does this PR do?

Backports fixes from https://github.com/saltstack/salt/pull/64300

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65349

2024-02-14 21:31 UTC, dwoz commented
@mbebjak Please rebase this.

2024-02-14 21:31 UTC, dwoz requested changes
Please rebase.

2024-02-15 08:21 UTC, mbebjak commented
@dwoz rebased

2024-02-27 13:12 UTC, jbartak commented
Any update please?
@dwoz

2024-06-21 03:22 UTC, dwoz approved these changes

2024-06-21 03:22 UTC, merged