Fix datetime.datetime.utcnow() deprecated in Python 3.12
saltstack/salt pull request #66042
Opened 2024-02-11 22:43 UTC by chloekaii

### What does this PR do?
This changes all instances of datetime.utcnow() to datetime.now(tz=timezone.utc).
### What issues does this PR fix or reference?
Fixes: #65604

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-02-12 06:00 UTC, max-arnold commented
I think this might be not backward compatible, because `utcnow()` returns a naive datetime, and `now(tz=datetime.UTC) returns a timezone-aware one.

2024-02-12 16:46 UTC, twangboy commented
To create a naive datetime
```
from datetime import datetime, UTC
datetime.now(UTC).replace(tzinfo=None)
```

2024-08-15 12:33 UTC, marmarek commented
> I think this might be not backward compatible, because `utcnow()` returns a naive datetime, and `now(tz=datetime.UTC)` returns a timezone-aware one.

That's the point of this deprecation warning, no? To stop using non-timezone-aware objects.

2024-08-15 13:01 UTC, marmarek requested changes

2024-09-20 19:17 UTC, twangboy commented
This needs to be rebased and there are quite a number of test failures. This will also need a changelog.
Some of these changes are in @marmarek's PR https://github.com/saltstack/salt/pull/66902

2026-03-17 21:33 UTC, dwoz commented on salt/state.py
> +        timezone_delta = datetime.datetime.now(tz=datetime.timezone.utc) - datetime.datetime.now()
@chloekaii Can you address this please?

2026-03-17 22:09 UTC, twangboy commented
Please rebase and address conflicts

2026-03-18 22:12 UTC, dwoz commented
This is no longer needed with #66902. If I'm missing something feel free to re-open it.

2026-03-18 22:12 UTC, closed without merging