Draft: 65264 retain existing perms (RPM)
saltstack/salt pull request #66050
Opened 2024-02-13 00:18 UTC by barneysowood

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: #65264 

### Previous Behaviour

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-03-12 20:27 UTC, dmurphy18 requested changes
the previous owner may not be root, and more than 3006.0-2 at this point

2024-03-12 20:27 UTC, dmurphy18 commented on pkg/rpm/salt.spec
> +        \( -user salt -o -group salt \) -exec chown root:root \{\} \;
The machine might not be root ownership, what if they had installed as non-root. Can think of one customer which names it something completely different

2024-03-28 19:54 UTC, dmurphy18 reviewed
wondering about changes I made in https://github.com/saltstack/salt/pull/66218 and if applicable ?, That and not version specific, esp. since 3005.x is EOL

2024-04-23 15:53 UTC, dmurphy18 commented
@barneysowood Given this PR is not getting a lot of attention, wondering if you would be fine with my taking it over

2024-04-23 16:28 UTC, barneysowood commented
> @barneysowood Given this PR is not getting a lot of attention, wondering if you would be fine with my taking it over

@dmurphy18 - sorry, I just haven't been able to spend any time on this in the last few weeks. If you're able to take over that would be great, thanks.

2024-04-24 19:34 UTC, dmurphy18 commented
Closing this in favor of PR https://github.com/saltstack/salt/pull/66218

2024-04-24 19:34 UTC, closed without merging