Handle pkg version for apk
saltstack/salt pull request #66054
Opened 2024-02-13 10:54 UTC by the-nando

### What does this PR do?

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/66053

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-02-13 13:58 UTC, s0undt3ch requested changes
You're missing tests.

2024-02-14 07:47 UTC, the-nando commented
@s0undt3ch as far as can I see there are no tests at all for apk pkg and setting them up from scratch isn't a simple task I'm afraid. I can leave this open as is for someone to add tests or close it, whichever you prefer.

2025-05-14 20:14 UTC, twangboy requested changes
Please add a changelog and a test

2025-05-14 20:14 UTC, twangboy commented
Also needs to be rebased and conflicts resolved

2026-03-17 22:08 UTC, twangboy commented
Please rebase and resolve conflicts

2026-03-19 22:08 UTC, twangboy commented
The APK module has been removed as part of the great module migration. Please create a salt-extension for this and make your changes there.

2026-03-19 22:08 UTC, closed without merging