Add mako to pkg dependencies
saltstack/salt pull request #66093
Opened 2024-02-19 03:03 UTC by dwoz

### What does this PR do?

See title.

### What issues does this PR fix or reference?
Fixes: #66091

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

2024-02-19 15:42 UTC, s0undt3ch commented
`mako` can be `salt-pip` installed at any time.

If we add `mako` why would we deny someone requesting `cheetah3`, `genshi` and `wempy`?

2024-02-19 15:43 UTC, s0undt3ch commented
Even with the old packages, the user reporting the issue had to somehow install mako to use mako templates...

2024-02-20 16:52 UTC, twangboy requested changes

2024-02-20 16:52 UTC, twangboy commented on requirements/static/pkg/windows.in
> +mako
I love how you ignore the comment right above this...

2024-02-21 02:50 UTC, dwoz commented
The mako renderer has been moved to core extensions

2024-02-21 02:50 UTC, closed without merging