Streamline MongoDB connection and settings in (pillar|tops)mongo.py.
saltstack/salt pull request #66129
Opened 2024-02-23 07:52 UTC by dhs-rec

### What does this PR do?
Streamline MongoDB connection and settings in `(pillar|tops)/mongo.py`, esp. reg. `mongo.uri`. Also adds a new `mongo.authdb` setting, defaulting to `mongo.db`.

### What issues does this PR fix or reference?
#66122 

### Previous Behavior
Inconsistent settings and behavior, as well as the missing `mongo.authdb` setting could lead to connection failures.
 
### New Behavior
The way `ext_pillar` and `ext_tops` are connecting to MongoDB is now unified. However, could be further enhanced by moving this into a separate module.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2025-05-09 21:23 UTC, twangboy requested changes
Please add a changelog and write a test for this

2025-05-09 21:23 UTC, twangboy commented on salt/pillar/mongo.py
>  ===============================
These need to be as long as the string above

2025-05-09 21:23 UTC, twangboy commented on salt/pillar/mongo.py
>  ================================
again here

2025-05-09 21:23 UTC, twangboy commented on salt/tops/mongo.py
>  ===============================
And here

2025-05-09 21:23 UTC, twangboy commented on salt/tops/mongo.py
>  ====================================
here

2025-05-20 06:51 UTC, dhs-rec commented
Seems like `salt/pillar/mongo.py` has been removed upstream in the meantime. If storing pillar data in MongoDB is no longer supported, this PR doesn't make sense anymore.

2025-05-20 14:53 UTC, twangboy commented
Please rebase and address conflicts

2025-05-23 12:46 UTC, dhs-rec commented
Well cannot push to my fork anymore after rebasing:

> To https://github.com/dhs-rec/saltstack-salt.git
 ! [remote rejected]       issue_66122 -> issue_66122 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/backport.yml` without `workflow` scope)

2025-05-23 20:55 UTC, closed without merging