[3006.x] [DOC] Add documentation about masking passwd in logs and stdout
saltstack/salt pull request #66154
Opened 2024-02-28 19:02 UTC by twangboy

### What does this PR do?
Adds documentation regarding how ``passwd`` is masked in log and stdout.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/65406

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-02-28 21:14 UTC, dwoz requested changes
I prefer we make sure we never log a password, masked or not.

2024-02-28 21:27 UTC, s0undt3ch approved these changes

2024-03-01 21:51 UTC, twangboy commented
We're not logging a password here. We're checking the return of a command and masking anything that matches the password that was passed.

2024-03-15 17:12 UTC, twangboy commented
From @vzhestkov 
I think it's not just a documentation issue, looks like the data is wiping too early and as I specified it could potentially wipe any part of the response from json if it's matching the password just by accident, in this case we can't really say the customers not to use the passwords which could potentially match any part of the output.
Check the example with grains I put in the original description. For me it sounds too weird to ask the users to take care of it themselves. And especially because it became a problem after the certain `fix`.

2025-03-20 21:32 UTC, dmurphy18 approved these changes

2025-05-19 21:42 UTC, closed without merging