[3007.x] Address minion log flood from zeromq
saltstack/salt pull request #66231
Opened 2024-03-14 00:40 UTC by dismari

### What does this PR do?
Checks if callback object in zeromq consume method is not None when handling logging as error.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Every minion will see many log errors for an:
`TypeError: object NoneType can't be used in 'await' expression`
from zeromq callback exception handling

### New Behavior
The consume method will now only log an error if there is an exception from with callback.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-03-14 13:03 UTC, s0undt3ch requested changes

2024-03-14 13:03 UTC, s0undt3ch commented on salt/transport/zeromq.py
> +                        except TypeError as exc:  # pylint: disable=broad-except
```suggestion
                        except TypeError as exc:
```
It's not a broad exception.

2024-03-14 13:03 UTC, s0undt3ch commented on salt/transport/zeromq.py
> +                                log.error("Exception while running callback %s", exc, exc_info=True)
```suggestion
                                log.exception("Exception while running callback: %s", callback)
```
Log the callback, and `log.exception` will make sure `exc_info` is also shown.

2024-03-14 20:21 UTC, twangboy approved these changes, later dismissed

2024-03-14 20:38 UTC, s0undt3ch approved these changes, later dismissed

2024-03-14 21:21 UTC, twangboy commented
Looks like you have some pre-commit errors

2024-03-15 07:17 UTC, SwimGeek commented
Hi

Is there an ETA for this fix to be available (on Debian)?

It's causing lots of our minions to disconnect from master.

2024-03-26 19:25 UTC, merlinz01 commented
As I understand it from doing some debugging, the problem is not that the callback is None, but that the callback is a non-async function that is used in an `await` statement. See [my comment, with example](https://github.com/saltstack/salt/issues/66177#issuecomment-2018638154). So this PR as it is does not fix the issue.

Here's my understanding of coroutines as it relates to this bug:

When you write `await some_function()`, that means "call some_function and then *await* the return value". If `some_function` is defined with `async def`, then `some_function()` immediately returns a coroutine object that can be awaited, which is how this is supposed to work. However, if `some_function` is defined with a simple `def`, then it returns None or whatever the function decides to return. When Python gets to the *await*-ing part, all it has is the return value, which in this case is None. The None object can't be awaited, so it throws the error described.

2024-03-26 19:33 UTC, dismari commented
My 'fix' (as I described in my PR) is not really fix and rather just removing the unnecessary log which floods the salt minion's logs. As far as I can tell, the code is operational/functional and thus the logging is excessive. I would like someone to resolve the root of the issue but do not have the time/bandwidth (just trying to reduce unnecessary logs in my salt minions).

2024-03-27 22:43 UTC, dwoz reviewed
Please hold off on merging this until I have a chance to look at it in more detail.

2024-05-01 21:27 UTC, dwoz commented
superseded by #66335

2024-05-01 21:27 UTC, closed without merging