Decode oscap byte stream to string
saltstack/salt pull request #66234
Opened 2024-03-14 16:43 UTC by ycedres

### What does this PR do?

In the openscap module, we send non-escaped byte error stream from the oscap output to salt-master. However, the error stream may contain non-ascii characters, which Uyuni cannot process further. This means that user doesn't see any errors in the UI, just decoding exceptions in the logs.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-03-14 20:18 UTC, twangboy approved these changes

2024-03-15 08:50 UTC, s0undt3ch commented on salt/modules/openscap.py
> +        error = error.decode("ascii", errors="ignore")
If Salt is supposed to treat all output as text, and non binary output, then why not fix the subprocess call?
```python
ret = subprocess.run(cmd_opts, capture_output=True, text=True)
error = ret.stderr
```
etc...

2024-03-22 21:32 UTC, dwoz requested changes
This module is being removed from master as a community maintained extension.

2025-07-01 20:36 UTC, twangboy commented
This module and its associated states and tests have been transitioned to community support and are no longer maintained by the Salt Core team. The code has been removed from the Salt code-base and can be found in this repository: https://github.com/salt-extensions/community-extensions-holding/

There is currently discussion and work being done on the salt-extensions Discord channel (https://discordapp.com/channels/1200072194781368340/1208165123240370197) to document and build the infrastructure for community-supported salt extensions. There is also a Salt-Extensions Working Group that takes place on the 1st and 3rd Thursday of every month to coordinate salt-extension efforts.

2025-07-01 20:36 UTC, closed without merging