[3006.x] Fix x509.certificate_managed - ca_server did not return a certificate
saltstack/salt pull request #66286
Opened 2024-03-28 16:43 UTC by nicholasmhughes

### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #66284

### Previous Behavior
Error when attempting to deploy certificates on 3006.7 or 3007.0 and a base64-encoded DER with `b64:` prefix is received.

### New Behavior
base64-encoded DER with `b64:` prefix is handled properly.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-03-29 19:31 UTC, twangboy approved these changes, later dismissed

2024-03-30 22:05 UTC, s0undt3ch requested changes

2024-03-30 22:05 UTC, s0undt3ch commented on tests/pytests/functional/utils/test_x509.py
> +]
```suggestion
cx509 = pytest.importorskip("cryptography.x509")
```

2024-04-01 09:29 UTC, s0undt3ch approved these changes

2024-04-01 09:30 UTC, merged