New pem managed state
saltstack/salt pull request #66322
Opened 2024-04-08 11:46 UTC by flajr

…l info in the comment

### What does this PR do?

Create new state that will handle certificates as files and provide easier management with few conditions and human readable info in the comment. Under the hood use standard `file.managed` state to provide any necessary and already implemented magic.

Reason for this state is easier management of files with PEM formats (certificates), which can hold just one certificate or combinations of privkey->certificate->chain

Requirement is cryptography package, which is checked. Maybe few more conditions and informations to the output comment can be add later. E.g if chain is detected, then right order of chain is required with another condition check.

This provides easy and quick status to any admin dealing with certificate files which he already have at hand.

Name of the module `pem` can be certainly changed if required but is relatively appropriate.

### Examples

#### No changes - certificates are same
```
----------
          ID: /etc/ssl/postfix/domain.com/domain.com.pem
    Function: pem.managed
      Result: True
     Comment: Existing cert info:
              - Subject: CN=*.domain.com
              - Not valid after: 2024-08-08 23:59:59
              New cert info:
              + Subject: CN=*.domain.com
              + Not valid after: 2024-08-08 23:59:59
              The file /etc/ssl/postfix/domain.com/domain.com.pem is in the correct state
     Started: 11:30:39.960125
    Duration: 167.712 ms
     Changes:
```

#### Certificates are not the same - test=true
```
----------
          ID: /etc/ssl/postfix/domain.com/domain.com.pem
    Function: pem.managed
      Result: None
     Comment: Existing cert info:
              - Subject: CN=*.domain.com
              - Not valid after: 2024-08-08 23:59:59
              New cert info:
              + Subject: CN=*.domain.com
              + Not valid after: 2024-09-09 23:59:59
              The file /etc/ssl/postfix/domain.com/domain.com.pem is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.
     Started: 11:30:39.728193
    Duration: 231.621 ms
     Changes:
              ----------
              diff:
              # normal diff output from file.managed
```

#### Certificates do not pass conditions
```
----------
          ID: /etc/ssl/postfix/domain.com/domain.com.pem
    Function: pem.managed
      Result: False
     Comment: Existing cert info:
              - Subject: CN=*.domain.com
              - Not valid after: 2024-08-08 23:59:59
              New cert info:
              + Subject: CN=*.someother.com
              + Not valid after: 2024-04-04 23:59:59
              New certificate expires sooner than existing one (skip with pillar='{skip_conditions: True}')
              Certificates CN does not match (skip with pillar='{skip_conditions: True}')
     Started: 13:22:26.868966
    Duration: 98.669 ms
     Changes:
```

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

2024-04-08 16:19 UTC, twangboy requested changes

2024-04-08 16:19 UTC, twangboy commented on salt/states/pem.py
> +    expiration and common name in comment.
Manage certificates as files and provide certificate expiration and common name in the comment.

2024-04-08 16:19 UTC, twangboy commented on salt/states/pem.py
> +    or make sure that only newer certificates will be salted.
Provides an easy way to match against the certificate's ``Common Name`` or to make sure that only newer certificates are copied down.

2024-04-08 16:19 UTC, twangboy commented on salt/states/pem.py
> +    `salt-call state.apply some_other_state pillar="{skip_conditions: True}"`
These should be under a list of Args including all args for the function.

```
Args:

    name (str): The full path to the certificate file on the target system

    source (str): The full path to the certificate source

    source_hash (str): The hash of the source file

    source_hash_name (str): ...
```

Or provide a link to the `file.managed` docs to state that it uses similar parameters, then document the additional parameters provided by this function.

2024-04-08 16:19 UTC, twangboy commented on salt/states/pem.py
> +    because it is used underneat to process changes to files.
``underneath``

2024-04-08 16:19 UTC, twangboy commented on salt/states/pem.py
> +    skip_conditions = __pillar__.get("skip_conditions", skip_conditions)
Is this intended behavior?
- Pillar data `skip_conditions` will override state defined `skip_conditions`

2024-04-09 17:23 UTC, twangboy approved these changes, later dismissed

2024-04-10 11:25 UTC, flajr commented
Can someone point me how to solve problems in pipeline please?

2024-04-10 15:36 UTC, twangboy commented
I think you also need to add it to `salt/doc/ref/states/all/index.rst`

2024-04-16 06:55 UTC, flajr commented
It was not working as expected when passing content and also some errors with cryptography package were not catched. Now it should be more stable. Thank you for your time spent on this.

2024-04-16 14:46 UTC, twangboy commented
We'll be discussing this in our Standup Today. We have moved many modules out of Salt to be supported by the community as Salt Extensions. This may be a candidate for a Salt Extension.

2024-04-17 22:19 UTC, dwoz requested changes
I think this contribution would be better made as a salt extension rather than landing in the core Salt codebase.

2024-04-23 15:15 UTC, twangboy commented
I think this would be a new repository in the salt-extensions org. @nicholasmhughes can create it and make you the maintainer

2025-05-13 20:12 UTC, twangboy requested changes

2025-05-13 20:12 UTC, twangboy commented on salt/states/pem.py
> +"""
Please add a `.. versionadded:: 3008` to the docs for this new state module.

2025-05-13 20:12 UTC, twangboy commented on salt/states/pem.py
> +"""
Also, this needs to be rebased

2025-07-02 19:55 UTC, closed without merging