Fix #66194: Exchange HTTPClient by AsyncHTTPClient in salt.utils.http
saltstack/salt pull request #66330
Opened 2024-04-09 07:46 UTC by krombel

### What does this PR do?
It replaces HTTPClient by AsyncHTTPClient 

### What issues does this PR fix or reference?
Fixes #66194 

### Background
https://github.com/tornadoweb/tornado/issues/2325#issuecomment-375972739
==> might be caused by #64305 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-04-18 16:50 UTC, twangboy commented
Hey @krombel , since this effects 3007, would you mind rebasing this against the 3007.x branch?

2024-04-19 06:24 UTC, krombel commented
@twangboy done

2024-04-22 14:57 UTC, twangboy commented
@krombel Would you know how to write a test for this?

2024-04-29 07:33 UTC, ITJamie commented on salt/utils/http.py
https://github.com/saltstack/salt/blob/bfa1cbedc8b63ac7ee1e3c9695c26e4e486fdd13/salt/utils/http.py#L661 needs to be changed from .code to .status_code 

`Failed to load ext_pillar netbox: 'Future' object has no attribute 'code'`

2024-04-29 19:08 UTC, krombel commented
@twangboy Sadly no. There are no related tests (I could find and adapt) and I am not familiar with python testing...

@ITJamie After you mentioned it I somehow could reproduce it. I don't know why it worked in the first place but now I introduced the SyncWrapper which allows calling fetch() in a sync manner.

A "proper" fix would possibly be to make query an async function (so we can simply `await download_client.fetch()`) but I think this would be too much of work for this (intended small/simple ) bug fix without touching too much of code...

2024-05-27 14:32 UTC, krombel commented
@dwoz Anything I can do to help bring this PR forward?

As mentioned my knowledge of testing that specific part is limited (as it is caused by concurrency which I do not know how to "create" it for a test case...)

A previous version of this PR did not using the SyncWrapper caused [this problem](https://github.com/saltstack/salt/issues/66194#issuecomment-2082033724) which got fixed in the meantime.
I am using this code now in my instances successfully and in #66591 it is mentioned that this patch seems to fix it.

(I am just curious how long I need to keep my workaround and don't want this to get overseen as the last "action" on this is almost a month ago...)

2024-05-27 19:35 UTC, ITJamie commented
@krombel ive made a [pr](https://github.com/krombel/salt/pull/1) against your branch which adds a basic test. I confirmed that the test fails without your HTTP fix

2024-05-28 20:48 UTC, krombel commented
Thanks @ITJamie 🎉 
merged it now 🙂

2024-05-29 16:27 UTC, twangboy requested changes

2024-06-04 11:56 UTC, ITJamie commented
@krombel ive made a [pr](https://github.com/krombel/salt/pull/2) for your branch to fix the pre-commit issue

2024-06-12 20:36 UTC, twangboy approved these changes

2024-06-22 07:40 UTC, merged