Enable executor properties in salt-ssh
saltstack/salt pull request #66340
Opened 2024-04-10 11:05 UTC by m-czernek

### What does this PR do?

The `salt-ssh` binary does not accept the `module_executors` and `executor_opts` properties, yet the `salt` binary does. This PR unifies the differences so that we can use the executors property for `salt-ssh` as well.

### What issues does this PR fix or reference?
Part of https://github.com/SUSE/spacewalk/issues/23874

### Previous Behavior
`salt-ssh` could only read the `module_executors` property from the roster file (`minion_opts`) or from the `ssh_minion_opts` config.

### New Behavior
`salt-ssh` can read the `module_executors` property from the command-line arguments as well.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-07-01 21:59 UTC, Akm0d approved these changes, later dismissed
LGTM but needs a test

2025-04-16 21:00 UTC, twangboy requested changes
Please add a changelog and a test for this.

2026-03-17 22:15 UTC, twangboy commented
Changelog and test please?

2026-06-30 22:05 UTC, twangboy requested changes

2026-06-30 22:05 UTC, twangboy commented on salt/client/ssh/__init__.py
> +            self.minion_opts.update({"executor_opts": opts.get("executor_opts")})
Switch from .update() to .setdefault() so that the global master/CLI options are only applied as a fallback when they aren't already explicitly declared on the minion:

```python
        # Fall back to global master config/CLI options if not explicitly 
        # defined for this target minion in the roster.
        if opts.get("module_executors") is not None:
            self.minion_opts.setdefault("module_executors", opts.get("module_executors"))
        if opts.get("executor_opts") is not None:
            self.minion_opts.setdefault("executor_opts", opts.get("executor_opts"))
```

Additionally, the new unit test test_executor_opts_propagate_to_minion_opts passes because the test fixture cleanly strips these keys out of the base options beforehand, which masks this clobbering edge case.

Please write an additional test case that ensures an existing module_executors key inside ssh_minion_opts isn't overridden by the master config.

2026-07-01 07:07 UTC, m-czernek commented
This feature work got priority removed since the PR creation, closing this PR for now.

2026-07-01 07:07 UTC, closed without merging