[3006.x] Fix #66133: roots fileserver path verification for symlinks
saltstack/salt pull request #66419
Opened 2024-04-22 18:30 UTC by hurzhurz

### What does this PR do?
Changes of the path verification so that symlinks to destinations outside of the roots directory work again.
This is broken since the CVE fix commit e0cdb80b55123f4a024759ffcf2b3f0e0788e7ab.

### What issues does this PR fix or reference?
Fixes #66133, #66052, #65977

2024-04-22 21:32 UTC, dwoz requested changes
I'd prefer that salt.utils.verify.clean_path be modified to optionally allow for symlinks.

2024-04-23 09:19 UTC, hurzhurz commented
I thought about that but wasn't sure if I should touch the function.
Hope it is ok how I have done it now...

2024-04-23 15:20 UTC, twangboy approved these changes

2024-05-01 21:49 UTC, dwoz commented
Yes, I like this approach better. Please hold off on merging this. I have a few things I would like to validate before we proceed.

2024-05-16 22:20 UTC, merged