Fix minion config option startup_states
saltstack/salt pull request #66605
Opened 2024-05-30 20:56 UTC by transistortim

### What does this PR do?

The changes in this PR fix #66592 by making additional functions use async/await.

### What issues does this PR fix or reference?
Fixes #66592

### Previous Behavior
https://github.com/saltstack/salt/commit/11a06ce0dafd3d13c5b54961f9e0019539eac3f7 made some internal functions async. This broke functions calling these internal functions without await. This leads to the minion configuration option `startup_states` not working any more.

### New Behavior
Starting the minion with startup_states now works as expected.

### Merge requirements satisfied?

**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No. Is this required?

### Note
Making more functions async might have introduced some more bugs I didn't catch yet. Specifically I've never used ProxyMinions and Syndic, maybe somebody with more experience could look into that.

2024-06-12 20:41 UTC, twangboy approved these changes

2024-06-12 20:43 UTC, twangboy requested changes
This should probably be made against 3007.x branch. Would you mind rebasing this PR?

2024-06-14 08:10 UTC, transistortim commented
Thanks for the review! I'm currently on vacation, I'll take care of it when I get back (around June 24).

2024-08-08 07:32 UTC, 73VW commented
Hey @transistortim any update on this?

Thanks

2024-08-11 19:21 UTC, transistortim commented
Sorry for the delay, I was busy with some other things. Finally, here's the update :)

2024-10-25 22:17 UTC, twangboy submitted a review, later dismissed

2024-10-29 21:25 UTC, amalaguti commented
Will this fix be made available for 3007.2 ?

2024-10-30 16:08 UTC, amalaguti commented
> Looks like there is a lint failure. Would you mind taking a look? Also, there are some test failures.

Shane, 
found this in the CI pipeline
```
************* Module salt.minion
salt/minion.py:3879: [W0236(invalid-overridden-method), ProxyMinion.tune_in] Method 'tune_in' was expected to be 'async', found it instead as 'non-async'
```
Today I worked on another two issues related to async/await and also the tune_in() (the main tune_in in minion class). 
Looks like it's all related. 
#66932 
#67016

2025-05-03 03:35 UTC, dwoz approved these changes

2025-05-03 20:47 UTC, dwoz commented
@transistortim The tests you added pass against the recent merge forwards from 3006.x. Merging this.

2025-05-03 20:47 UTC, merged