Second salt con
saltstack/salt pull request #66635
Opened 2024-06-13 03:40 UTC by madavarajK

## Summary

This pull request enhances error handling and logging in the `tools/utils/repo.py` module. It also adds corresponding tests and updates the changelog.

## Changes

- Replaced print statements with logging using `log` for consistency.
- Added specific exception handling for `ClientError`, `NoCredentialsError`, and `PartialCredentialsError`.
- Updated `CHANGELOG.md` to document these changes.
- Created `tests/test_repo.py` to add tests for the logging functionality using `caplog`.

## Testing

- Verified that the `get_repo_json_file_contents` function handles different exceptions correctly and logs appropriate messages.
- Ensured that the changes do not affect the existing functionality.
- Added tests that use `caplog` to check that logging occurs as expected during different scenarios.

## Additional Notes

These changes aim to improve the robustness and maintainability of the code, making it easier to debug and understand. The logging ensures that detailed information is available when issues arise, facilitating quicker resolution.

2024-07-01 21:40 UTC, Akm0d approved these changes

2025-04-11 18:12 UTC, twangboy requested changes

2025-04-11 18:12 UTC, twangboy commented on CHANGELOG.md
> +
Changelog entries are not done here. They are created in the changelog directory and we use towncrier to generate the changelog on release. Please see https://docs.saltproject.io/en/latest/topics/development/changelog.html

2025-07-01 20:34 UTC, twangboy commented
We are no longer using S3

2025-07-01 20:34 UTC, closed without merging