Suppress error output for missing sysrc variables on FreeBSD
saltstack/salt pull request #66652
Opened 2024-06-21 13:28 UTC by amendlik

### What does this PR do?
Suppress error output for missing sysrc variables on FreeBSD
This condition is expected and handled by the code, so there is no need to write error logs when it happens.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
If the `sysrc.get` module was called for a sysrc variable that did not exist, several lines of error message would be written to the log/console.
```
$ sudo salt-call sysrc.get name=example
[ERROR   ] Command 'sysrc' failed with return code: 1
[ERROR   ] stdout: sysrc: unknown variable 'example'
[ERROR   ] retcode: 1
[ERROR   ] Command 'sysrc' failed with return code: 1
[ERROR   ] output: sysrc: unknown variable 'example'
local:
    None
```
This is condition is accounted for by the code, which return the correct value of `None`, so there is no value in displaying the errors.

### New Behavior
The error messages are suppressed.
```
$ sudo salt-call sysrc.get name=example
local:
    None
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-06-21 15:29 UTC, Akm0d approved these changes

2024-06-22 06:59 UTC, dwoz requested changes
Merge conflicts need to be addressed.

2024-06-23 21:07 UTC, amendlik commented
The `sysrc` module has been removed from the repository, along with scores of others, in dc526dc2b17660059ca19f2d486cabeba54d021a.

Was this decision published or explained somewhere? Since I rely on this module and others that have now been deleted, what are my options?

2024-06-27 15:24 UTC, amendlik commented
@dwoz - Can you offer some insight on the "purge of community extensions"? It seems like a good way to alienate contributors and customers at the same time, but I'd like to understand the rationale before drawing any conclusions.

2024-12-03 21:09 UTC, closed without merging