Draft: Remove deprecated pyvenv and add venv support
saltstack/salt pull request #66673
Opened 2024-06-27 00:27 UTC by Akm0d

### What does this PR do?

### What issues does this PR fix or reference?
Fixes #66132
Fixes #51742

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-06-27 16:06 UTC, dmurphy18 approved these changes, later dismissed

2024-06-27 20:44 UTC, twangboy requested changes

2024-06-27 20:44 UTC, twangboy commented on salt/modules/virtualenv_mod.py
> -    upgrade=None,
I think these need to go through a deprecation process. You can't just remove parameters.

2024-06-28 20:20 UTC, twangboy requested changes

2024-06-28 20:20 UTC, twangboy commented on tests/unit/modules/test_virtualenv_mod.py
> +VENV_BIN = f"{sys.executable} -m venv"
The module is modified to use virtualenv, yet we're using venv for the tests. Is that right?

2024-07-01 20:28 UTC, dmurphy18 reviewed
Looks good, wonder if we have sufficient test coverage with existing tests

2024-07-02 15:23 UTC, twangboy approved these changes

2024-07-02 20:25 UTC, dmurphy18 approved these changes

2024-07-05 04:51 UTC, merged

2024-09-30 16:34 UTC, OrangeDog commented
The documentation is no longer correct. It says the default is to use `virtualenv`, but it now is not if not installed.

It also appears that there's no way to use the `venv` module of a different Python (e.g. the system Python)?

People will have to workaround by creating custom `pyvenv` wrappers.