Add proxy option to gitfs and git_pillar
saltstack/salt pull request #66744
Opened 2024-07-25 15:28 UTC by eisenmann-b1

### What does this PR do?
This PR add the options `gitfs_proxy` and `git_pillar_proxy`, with which a proxy server can be specified to be used for connecting to git repositories.  These options can also be set per remote as `proxy`, overriding the global options.

For Pygit2, a warning will be given if `proxy` is set and the URL to the git repository does not have an `https` scheme.
This is due to an (issue)[https://github.com/libgit2/libgit2/issues/5650] in libgit2, the library pygit2 is using.

### What issues does this PR fix or reference?
Fixes #30990 

### Previous Behavior
There is no option to specify the proxy server.  The workaround described in #30990 requires changes to code akin to the ones here, or setting environment variables in service files.

### New Behavior
A proxy server can now be specified like this:
```
gitfs_remotes:
  - https://foo.com/bar.git:
    - proxy: http://proxy.com:8080/
```
In this example, the repository at `https://foo.com/bar.git` is fetched through the proxy `http://proxy.com:8080/`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-07-25 15:55 UTC, dmurphy18 commented
@eisenmann-b1 Need to tick the ``` Tests written/updated``` box too

2024-07-25 16:10 UTC, eisenmann-b1 commented
> @eisenmann-b1 Need to tick the ` Tests written/updated` box too

I did not tick it since there are no new tests, which I felt would be necessary for this.

2024-07-25 16:49 UTC, dmurphy18 commented
@eisenmann-b1 you ``updated``` tests, hence you need to tick the box, for example: tests/pytests/unit/fileserver/gitfs/test_gitfs.py

2024-07-25 17:03 UTC, eisenmann-b1 commented
@dmurphy18 ok, I ticked the box.

2024-07-26 09:24 UTC, eisenmann-b1 commented
Added the option to `winrepo`.

2025-04-11 17:32 UTC, twangboy requested changes

2025-04-11 17:32 UTC, twangboy commented on conf/master
>  # Specifies whether or not to ignore SSL certificate errors when contacting
Need to add `winrepo_proxy` here as well

2025-04-11 17:32 UTC, twangboy commented on pkg/common/conf/master
> +
Need to add `winrepo_proxy` here

2025-04-11 23:27 UTC, eisenmann-b1 commented on conf/suse/master
>  # Specifies whether or not to ignore SSL certificate errors when contacting
Added `winrepo_proxy`.

2025-04-11 23:27 UTC, eisenmann-b1 commented on conf/master
>  # Specifies whether or not to ignore SSL certificate errors when contacting
Added it here too.

2025-04-11 23:27 UTC, eisenmann-b1 commented on pkg/common/conf/master
> +
And here too.

2025-04-15 20:36 UTC, twangboy approved these changes, later dismissed
I'd like to see a review from @dwoz

2025-11-13 16:52 UTC, eisenmann-b1 commented
What do you think about this?
@dwoz

2025-11-18 10:29 UTC, eisenmann-b1 commented
I guess the failure here was unrelated to the changes in the PR.

2026-01-12 19:13 UTC, twangboy approved these changes, later dismissed

2026-01-20 17:40 UTC, twangboy approved these changes

2026-01-30 23:09 UTC, merged