Do not use deprecated ssl.PROTOCOL_TLS
saltstack/salt pull request #66767
Opened 2024-07-31 01:36 UTC by CyrilRoelandteNovance

This has been deprecated in Python 3.10[1] and will be removed in the
future.

[1] https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS

2024-09-30 15:22 UTC, OrangeDog commented
I guess this would fix #66602?

2025-05-09 20:25 UTC, twangboy requested changes
Please add a changelog and write a test for this.

2026-02-09 14:11 UTC, hegyre commented
The issue is still there with SaltStack v3006.20

2026-02-11 19:26 UTC, twangboy commented
We can get this in once we have a test and a changelog

2026-03-19 21:15 UTC, twangboy approved these changes

2026-03-19 21:27 UTC, merged