Replace Slack with Discord
saltstack/salt pull request #66769
Opened 2024-07-31 16:38 UTC by max-arnold

### What does this PR do?

Replace Slack community links with Discord

https://www.reddit.com/r/saltstack/comments/1ecppqn/thoughts_on_the_purge_of_community_extensions/lf1smr8/

### Merge requirements satisfied?

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

2024-07-31 16:39 UTC, max-arnold commented
Cc: @ScriptAutomate

2024-07-31 16:54 UTC, ScriptAutomate reviewed
We are in the midst of replacing the Discord invite link to be from Chunga, even though this invite link will continue to work as a non-expiring link. Using this one to be part of the official documentation and the blog.

- Old non-expiring link (will continue to be available), but is by Derek: https://discord.gg/YVQamSwV3g
- New non-expiring link, but is by the community manager (Chunga): https://discord.gg/bPah23K7mG

The website is also being updated today. I'll apply a batch commit to make the changes.

2024-07-31 16:54 UTC, ScriptAutomate commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://discord.gg/YVQamSwV3g
```suggestion
    url: https://discord.gg/bPah23K7mG
```

2024-07-31 16:54 UTC, ScriptAutomate commented on .github/config.yml
> +    - [Join our Community Discord](https://discord.gg/YVQamSwV3g)
```suggestion
    - [Join our Community Discord](https://discord.gg/bPah23K7mG)
```

2024-07-31 16:54 UTC, ScriptAutomate commented on .github/config.yml
> +    - [Join our Community Discord](https://discord.gg/YVQamSwV3g)
```suggestion
    - [Join our Community Discord](https://discord.gg/bPah23K7mG)
```

2024-07-31 16:54 UTC, ScriptAutomate commented on CONTRIBUTING.rst
> +   the `community Discord <https://discord.gg/YVQamSwV3g>`__,
```suggestion
   the `community Discord <https://discord.gg/bPah23K7mG>`__,
```

2024-07-31 16:54 UTC, ScriptAutomate commented on README.rst
> +   :target: https://discord.gg/YVQamSwV3g
```suggestion
   :target: https://discord.gg/bPah23K7mG
```

2024-07-31 16:54 UTC, ScriptAutomate commented on README.rst
> +.. _Salt Project Community Discord: https://discord.gg/YVQamSwV3g
```suggestion
.. _Salt Project Community Discord: https://discord.gg/bPah23K7mG
```

2024-07-31 16:54 UTC, ScriptAutomate commented on SUPPORT.rst
> +`<https://discord.gg/YVQamSwV3g>`_
```suggestion
`<https://discord.gg/bPah23K7mG>`_
```

2024-07-31 16:54 UTC, ScriptAutomate commented on doc/_incl/requisite_incl.rst
> +    `Salt Project Discord Community <https://discord.gg/YVQamSwV3g>`_.
```suggestion
    `Salt Project Discord Community <https://discord.gg/bPah23K7mG>`_.
```

2024-07-31 16:54 UTC, ScriptAutomate commented on doc/conf.py
> +.. _`salt-discord`: https://discord.gg/YVQamSwV3g
```suggestion
.. _`salt-discord`: https://discord.gg/bPah23K7mG
```

2024-07-31 16:54 UTC, ScriptAutomate commented on doc/security/index.rst
> +* `Salt Project Discord Community <https://discord.gg/YVQamSwV3g>`__
```suggestion
* `Salt Project Discord Community <https://discord.gg/bPah23K7mG>`__
```

2024-07-31 16:54 UTC, ScriptAutomate commented on doc/topics/tutorials/states_pt4.rst
> +`Salt Project Discord Community <https://discord.gg/YVQamSwV3g>`_.
```suggestion
`Salt Project Discord Community <https://discord.gg/bPah23K7mG>`_.
```

2024-07-31 16:55 UTC, ScriptAutomate approved these changes

2024-07-31 17:10 UTC, dmurphy18 submitted a review, later dismissed

2024-07-31 17:18 UTC, ScriptAutomate requested changes
Going to wait on this at the moment. Need to see if we have a better solution this week for a permanent link that could be generated by something like a bot instead of specific user.

2024-08-28 17:16 UTC, dmurphy18 commented
@max-arnold Sorry forgot about this when I did PR https://github.com/saltstack/salt/pull/66850. Recommend doing this against the 3006.x branch, as it will be merged-forward to the other branches

2024-08-28 19:57 UTC, dmurphy18 commented
@max-arnold Suggest using lionk  https://discord.com/invite/J7b7EscrAs for the Discord invite, was used in last week's Open Hour and is not based on Chunga but Salt Project Admin

2024-08-29 06:47 UTC, max-arnold commented
@dmurphy18 Rebased against 3006.x and used the proper Discord link

2024-08-29 15:07 UTC, twangboy approved these changes

2024-08-29 15:39 UTC, dmurphy18 approved these changes

2024-08-29 15:41 UTC, dmurphy18 commented
@ScriptAutomate Can you review this and help get it over the line, looks good to me

2024-08-29 19:22 UTC, ScriptAutomate approved these changes

2024-08-29 19:34 UTC, merged