Ensure Manjaro ARM reports the correct os_family of Arch.
saltstack/salt pull request #66796
Opened 2024-08-08 23:02 UTC by garethgreenaway

### What does this PR do?
Ensure Manjaro ARM reports the correct os_family of Arch.

### What issues does this PR fix or reference?
Fixes n/a

### Previous Behavior
Manjaro ARM does not report as Arch in os_family grain

### New Behavior
Manjaro ARM will now report as Arch in os_family grain

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-08-08 23:57 UTC, dwoz approved these changes, later dismissed

2024-08-09 19:05 UTC, dmurphy18 requested changes
Can not believe it, no changelog file :rofl:

2024-08-09 19:29 UTC, garethgreenaway commented
@dmurphy18 Sorry about that.  Forgot to push after adding the changelog file.  I can redo the change against 3006.x if you all prefer.

2024-08-09 19:50 UTC, dmurphy18 approved these changes

2024-08-09 19:51 UTC, dmurphy18 commented
@garethgreenaway Hope things going well for you.  Just thinking it will be a while before master branch -> 3008, and hence if want this sooner, adding to 3006.x and merge-forwards will get it out there sooner.  Which branch you want to submit against is fine.

2024-08-09 22:22 UTC, garethgreenaway commented
@dmurphy18 fyi, https://github.com/saltstack/salt/pull/66802

2024-08-12 17:57 UTC, dmurphy18 commented
@garethgreenaway Note, the 3006.x https://github.com/saltstack/salt/pull/66796 will eventually get merged forward.
It is out for review and merge anyway as is the other

2024-08-12 18:25 UTC, twangboy approved these changes

2024-08-12 19:42 UTC, dwoz commented
Trumped by #66802

2024-08-12 19:42 UTC, closed without merging