[66799] Update master-cluster.rst Example Config
saltstack/salt pull request #66822
Opened 2024-08-21 16:06 UTC by kevin-andrew-wipro

The Master Config example's `file_roots` and `pillar_roots` properties need the `base` property followed by a list of the directory. Otherwise, the Salt master shows an error in the logs.

### What does this PR do?
Updates the documentation of the Master Cluster config.

### What issues does this PR fix or reference?
Incorrect example of the Master Cluster config.
Fixes 66799 [DOCS] Documentation Inconsistency

### Previous Behavior
![saltExample](https://github.com/user-attachments/assets/e43694cd-c558-499b-a116-de3f7599f1bb)

### New Behavior
Based on the example of `file_roots` here:
https://docs.saltproject.io/en/latest/ref/configuration/master.html#file-roots

we add `base:` to the config.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-09-18 20:09 UTC, twangboy approved these changes

2024-09-18 20:10 UTC, twangboy requested changes
Please rebase this against the 3006.x branch

2024-09-19 23:36 UTC, kevin-andrew-wipro commented
Hi, @twangboy . I'm a little confused by your comment asking to rebase against the 3006.x branch.

The page on which I'm suggesting to make the change doesn't exist in 3006.x. `Master Cluster` is a new feature, first available in version 3007.
https://docs.saltproject.io/en/latest/topics/tutorials/master-cluster.html

However, I saw that there was a button to "Update branch" (or something), so I went ahead and clicked it and a new commit was automatically done. But I'm pretty sure it's still just from the master branch.

If you really want me to rebase onto the `3006.x` branch, I can try. But the file I'm changing doesn't exist there. So I'm confused as to what the reason and expectation of the question is. And what the outcome of the rebase will do.

2024-09-20 18:33 UTC, twangboy commented
You are correct, that was added in 3007, I believe. Please rebase against 3007.x

2024-09-23 18:50 UTC, closed without merging