[3006.x] Remove salt.utils.data from fileserver
saltstack/salt pull request #66836
Opened 2024-08-26 17:19 UTC by twangboy

### What does this PR do?
The salt.utils.data util was used to support python 2. Since we no longer support python 2, we can start removing this. This gives us some great speed increases as we're removing a lot of overhead and unnecessary function calls

### What issues does this PR fix or reference?
Fixes #66835 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-08-27 16:53 UTC, dmurphy18 approved these changes, later dismissed

2024-08-28 00:15 UTC, dwoz requested changes
I think this deserves a changelog.

2024-08-28 19:42 UTC, twangboy commented
Changelog has been added

2024-08-28 22:03 UTC, dwoz submitted a review, later dismissed

2024-08-29 15:17 UTC, dmurphy18 submitted a review, later dismissed

2024-09-03 16:41 UTC, dmurphy18 approved these changes

2024-09-12 15:55 UTC, merged