Stop using egrep
saltstack/salt pull request #66832
Opened 2024-08-26 09:35 UTC by Rudd-O

### What does this PR do?

When egrep is used, a nasty warning from grep saying egrep should be replaced by grep -E appears on the executed command.  This leads to failure matching returned values from `semanage fcontext`.

This fix fixes it.

### What issues does this PR fix or reference?
Have not noticed any bugs reported on this.

### Previous Behavior
Failure running `selinux.fcontext_policy_present`.

### New Behavior
It works.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-08-26 15:47 UTC, dmurphy18 commented
@Rudd-O This PR requires a changelog entry and tests new or updated if current tests are insufficient to test the code changes, no PR is accepted without the above.

2024-09-18 19:55 UTC, twangboy requested changes
Please provide a changelog and a test

2024-10-08 12:11 UTC, Rudd-O commented
I am not familiar enough with the testing system to provide a test, and I am regrettably too busy with other matters to make further changes.

I suppose I'll have to live with my local mod of SaltStack that doesn't continually spew "egrep is deprecated" to standard error.

Feel free to either close the PR, or turn it into another open ticket.

2024-10-08 16:43 UTC, dmurphy18 commented
@Rudd-O You missed a few files too
```david@david-XPS-15-9570:~/devcode/dgm_salt_3006/salt$ grep -R -w egrep *
pkg/old/shar/salt.sh:        osmajor=`egrep -o '[0-9]+\.[0-9]+' /etc/redhat-release | cut -f1 -d.`
pkg/old/shar/build_shar.sh:pip help install 2>/dev/null | egrep --quiet '(--)no-use-wheel' && PIP_OPTS='--no-use-wheel' || PIP_OPTS=''
pkg/old/shar/build_shar.sh:        zeromq_version=`egrep '^Version' "$zeromq_spec" | awk '{print $2}'`
salt/modules/selinux.py:        "semanage fcontext -l | egrep "
salt/modules/selinux.py:        cmd = f"semanage fcontext -l | egrep '{filespec}'"
salt/modules/selinux.py:        "semanage port -l | egrep "
salt/modules/csf.py:    exists = __salt__["cmd.run_all"](f"egrep ^'{ip} +' /etc/csf/csf.{method}")
tests/pytests/unit/modules/test_selinux.py:        expected_cmd_shell = f"semanage fcontext -l | egrep '{filespec}'"
```

This change would be better against the 3006.x branch, come out sooner  and the failing tests would need to be addressed.
That current test file tests/pytests/unit/modules/test_selinux.py modified for replacement of ```egrep``` should be enough.
Changelog entry is simple, similar to a git commit statement, <pr number>.fixed.md in directory changelog

2024-10-08 16:44 UTC, dmurphy18 requested changes
See comment https://github.com/saltstack/salt/pull/66832#issuecomment-2400356511

2024-10-22 17:31 UTC, dmurphy18 requested changes
Missing changelog entry for this PR, and testings ? are current tests sufficient ?

Also this may be quicker released by rebasing to the 3006.x branch, given it will be some time before 3008 is generated from the master branch.

2024-10-25 22:12 UTC, twangboy commented
Isn't this fix in 3006.x and part of the merge-forward?
https://github.com/saltstack/salt/pull/67002

2024-10-25 22:44 UTC, dmurphy18 commented
@twangboy It is now, wasn't when this was created, thanks for the work @Rudd-O , copied from the best :)

2025-01-12 02:30 UTC, bdrx312 commented
I am assuming the changes for egrep to grep -E from 3006.x/3007.x will get merged forward to master at some point so can this PR be closed?

2025-07-01 19:54 UTC, closed without merging