docs(modules/system): fix `system.get_computer_name` CLI example
saltstack/salt pull request #66838
Opened 2024-08-26 17:59 UTC by myii

### What does this PR do?

Documentation fix for `system.get_computer_name` CLI example.

### Merge requirements satisfied?
- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-09-18 19:54 UTC, twangboy requested changes
Would you mind rebasing this against the 3006.x branch?

2024-09-19 12:46 UTC, myii commented
> Would you mind rebasing this against the 3006.x branch?

@twangboy No problem, I've made the adjustments.

2024-09-19 15:48 UTC, twangboy approved these changes

2024-09-19 16:31 UTC, dwoz approved these changes

2024-09-19 16:31 UTC, merged