Better handling output of `systemctl --version`
saltstack/salt pull request #66856
Opened 2024-08-28 13:21 UTC by vzhestkov

### What does this PR do?

In some cases calling `systemctl --version` with `salt.grains.core._systemd` could return unexpected output what could cause `IndexError` exception preventing minion service from running.

### What issues does this PR fix or reference?
Tracks https://github.com/SUSE/spacewalk/issues/25122

### Previous Behavior
`IndexError` exception on starting minions service caused by unexpected response of  `systemctl --version`

### New Behavior
Normal minion start with just error message in the log about unexpected output.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-08-28 22:47 UTC, bdrx312 commented on salt/grains/core.py
> +        systemd_output = __salt__["cmd.run_all"]("systemctl --version")
This is running one command. It does not need to use `run_all`.

2024-08-29 15:35 UTC, dmurphy18 requested changes
Need to tick the ``` Tests written/updated``` box and add a changelog entry for the fix.
Otherwise it looks good

2024-09-05 19:49 UTC, dmurphy18 approved these changes

2024-09-18 18:53 UTC, twangboy approved these changes

2024-09-25 09:28 UTC, merged