Include the VM name with the IP address for Libvirt cloud logging
saltstack/salt pull request #66860
Opened 2024-08-29 15:44 UTC by m0duspwnens

### What does this PR do?
This PR adds the VM name to the log output for Libvirt when the IP address is reported. This is helpful when running salt-cloud in parallel with -P to know which IP address belongs to which host.
 
### What issues does this PR fix or reference?
There is not an issue for this PR.

### Previous Behavior
```
[INFO    ] Address = 10.66.166.111
```

### New Behavior
```
[INFO    ] Address = 10.66.166.111 | Name = my_test_vm
```

### Merge requirements satisfied?

If this is required for this change, then please let me know.

**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-09-05 19:51 UTC, dmurphy18 requested changes
Need to have a changelog entry for the PR. Also are current tests sufficient for this or at least there should be a test which verifies that the correct VM name is reported.

2024-12-17 20:26 UTC, Akm0d approved these changes

2025-02-17 08:10 UTC, dwoz requested changes
We don't generally use pipes in our logs. I'd prefer that it (`|`) is removed here. We'd also need a changelog entry to get this in.

2025-03-06 20:53 UTC, dmurphy18 commented
@m0duspwnens This needs a testcase and a changelog entry. If uninterested in completing this PR, please consider closing it, otherwise if no response within a few weeks, it will be closed due to unresponsive

2025-04-27 04:50 UTC, dwoz commented
Closing due to lack of follow up.

2025-04-27 04:50 UTC, closed without merging