Remove perms from linux_acl.list_absent docstring
saltstack/salt pull request #66892
Opened 2024-09-15 21:55 UTC by tacerus

Not a valid argument for this function, remove misleading documentation reference.

### What does this PR do?

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/66891.

### Previous Behavior

Misleading documentation block.

### New Behavior

Less misleading documentation. ;-)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

2024-09-17 19:20 UTC, twangboy approved these changes

2024-09-17 19:31 UTC, twangboy requested changes
Please rebase this on 3006.x branch

2024-09-17 22:50 UTC, tacerus commented
Done, but I can't change the PR target branch.

2024-09-18 17:36 UTC, twangboy approved these changes

2024-09-23 16:49 UTC, Akm0d approved these changes

2024-10-17 01:23 UTC, merged