Add state.sls_exists to ssh client
saltstack/salt pull request #66894
Opened 2024-09-16 11:14 UTC by shtrom

### What does this PR do?

Add state.sls_exists to the SSH wrapper

### What issues does this PR fix or reference?
Fixes #66893

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-09-17 11:06 UTC, shtrom commented on salt/client/ssh/wrapper/state.py
> +    Tests for the existence the of a specific SLS or list of SLS files on the
Fixed (including in original code from which the fix came).

2024-09-17 19:03 UTC, twangboy commented
This should go on the master branch since this is a new feature. The ``.. versionadded::` needs to be `3008.0`

2024-09-17 19:04 UTC, twangboy requested changes
This should go on the master branch since this is a new feature. The `.. versionadded::` needs to be `3008.0`

2024-09-18 08:51 UTC, shtrom commented
Looks like the CI release job is failing as it started before I changed the target branch back to `master`.

2024-09-18 18:37 UTC, twangboy commented
Maybe it needs to be `.. versionadded:: Argon`

2024-09-19 08:08 UTC, shtrom commented
There's no other instance of `Argon` as a version, but there are 3008.0. I just rewrote the top commit and force-pushed. If my previous hunch is correct, the tests should pass this time.

2024-09-20 01:35 UTC, shtrom commented
Yep, it's happy now!

2024-09-20 18:31 UTC, twangboy requested changes
This looks good. Could we get a changelog please?

2024-09-21 08:13 UTC, shtrom commented
Added Changelog, rebased on master, and squashed.

2024-09-23 22:02 UTC, twangboy approved these changes

2024-09-24 17:04 UTC, Akm0d approved these changes

2024-09-26 17:18 UTC, dmurphy18 approved these changes

2024-09-26 22:11 UTC, merged