salt.channel.server.handle_message: be more defensive
saltstack/salt pull request #66909
Opened 2024-09-20 13:05 UTC by mattp-

### What does this PR do?
it's possible _encrypt_private can throw depending on what key backend is used; so we should guard against any possible unhandled exceptions in this critical codepath. We already do this when wrapping the payload_handler, so we just move the other code in the same try.

I've also added some tests to cover different scenarios in handle_message as its untested atm.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

2024-09-20 18:18 UTC, twangboy requested changes
Please add a changelog
There are also some failing tests

2024-09-20 18:19 UTC, mattp- commented
@twangboy will do, still looking at that. thanks

2024-09-23 14:49 UTC, mattp- commented
@twangboy I didn't change anything but pushed the changelog.md, it seems to be passing minus one test. would you mind a sanity check/merge? Thanks 👍

2024-09-23 21:48 UTC, twangboy approved these changes, later dismissed

2024-09-24 17:07 UTC, Akm0d approved these changes, later dismissed

2025-06-26 22:22 UTC, dwoz commented
@mattp- Can you please rebase this one?

2025-06-27 13:44 UTC, mattp- commented
@dwoz sure, done

2025-06-27 15:52 UTC, twangboy approved these changes, later dismissed

2025-06-27 15:53 UTC, twangboy commented
Looks like there are some pre-commit failures.

2025-06-27 15:55 UTC, mattp- commented
@twangboy woops, sorry about that. fixed

2025-06-30 18:33 UTC, twangboy submitted a review, later dismissed

2025-07-01 15:34 UTC, twangboy commented
We're working on a merge-forward that should fix the failing tests on master branch (https://github.com/saltstack/salt/pull/68130). Once that is merged, we can rebase and get the tests working here.

2025-07-01 16:38 UTC, mattp- commented
sure just let me know in the #develop discord and i'll rebase all the PR's

2025-09-15 18:13 UTC, twangboy submitted a review, later dismissed

2025-10-21 20:49 UTC, dwoz commented
@mattp- This one has conflicts now. Sorry it was my changes that caused the conflicts. :/

2025-10-31 17:46 UTC, twangboy commented
Please resolve the merge conflict

2025-10-31 18:14 UTC, mattp- commented
@dwoz @twangboy all good, rebased now. ill keep an eye on CI

2025-10-31 18:15 UTC, twangboy approved these changes, later dismissed

2026-02-11 19:11 UTC, twangboy approved these changes

2026-03-17 20:57 UTC, merged