[master] fix(nacl): Update `generate pk using the sk` procedure
saltstack/salt pull request #66901
Opened 2024-09-18 09:12 UTC by hatamiarash7

### What does this PR do?

Fix the `generate pk using the sk` procedure in `genkey` function of the `salt.utils.nacl` file.

### What issues does this PR fix or reference?
Fixes #66900

### Previous Behavior

Generate the wrong `pk` value because it's the same as `sk`.

### New Behavior

Generate the correct `pk` value.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2024-09-18 15:43 UTC, twangboy requested changes
Hey, could we get a test for this?

2024-09-18 20:06 UTC, hatamiarash7 commented
> Hey, could we get a test for this?

Definitely

A test was already written for this case, which did not have the necessary coverage and only checked the console output. I completed this function and file content check was added to it.

2024-09-18 20:08 UTC, twangboy approved these changes

2024-09-19 07:27 UTC, hurzhurz commented
This overlaps with my PR #66773 which fixes the same issue (and a related second one).

2024-09-19 21:55 UTC, dwoz commented
I thought the nacl stuff was slated to be moved to a community driven extension. Looks we missed `salt/utils/nacl.py` and `salt/renderers/nacl.py`.

2024-09-19 21:57 UTC, dwoz commented
Merged #66773, closing this as duplicate.

2024-09-19 21:57 UTC, closed without merging