Datetime utcnow
saltstack/salt pull request #66902
Opened 2024-09-18 15:10 UTC by marmarek

### What does this PR do?

This removes some usage of deprecated datetime.datetime.utcnow() and replaces them with timezone-aware objects, while not changing the actual behavior.

### What issues does this PR fix or reference?
Partial fix for https://github.com/saltstack/salt/issues/65604

This is complementary to https://github.com/saltstack/salt/pull/66042

### Previous Behavior

Salt logs warnings like:
```
/usr/lib/python3.12/site-packages/salt/utils/jid.py:19: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```

### New Behavior

No warning.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-09-18 15:36 UTC, twangboy approved these changes

2024-09-18 15:36 UTC, twangboy requested changes
Looks like you have some pre-commit failures

2024-09-18 15:55 UTC, marmarek commented
> Looks like you have some pre-commit failures

Fixed

2024-09-18 18:51 UTC, dmurphy18 submitted a review, later dismissed

2024-09-18 20:22 UTC, marmarek commented
> Looks like the test failures are related to your changes in `utils/pkg/rpm.py`

What test failures? For the current version I don't see any (there are either green, or pending)

2024-09-18 20:28 UTC, twangboy commented
The test suite tries 3 times... here is the 2nd run:
https://github.com/saltstack/salt/actions/runs/10925697063/attempts/2?pr=66902

2024-09-18 20:50 UTC, marmarek commented
Ah, I see, `datetime.UTC` alias is available only since Python 3.11. Fixed.

2024-09-20 19:06 UTC, twangboy submitted a review, later dismissed

2024-09-20 19:10 UTC, dmurphy18 submitted a review, later dismissed

2024-12-17 20:26 UTC, Akm0d approved these changes, later dismissed

2025-04-08 09:08 UTC, marmarek commented
Is there anything I can do to help get this merged? CI failures look unrelated to my changes.

2025-04-08 20:09 UTC, twangboy commented
I think you'll need to accept those changes for py3.10.

2025-04-08 21:52 UTC, marmarek commented
Now a bunch of errors like this:
```
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'bdist_wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yamlordereddictloader
```
...

2025-04-09 20:55 UTC, twangboy commented
Maybe we'll need to wait until we get the branch builds green again, and then rebase this one.

2025-04-09 21:53 UTC, marmarek commented
This looks to be related to https://github.com/pypa/wheel/issues/662, and I see there is a workaround committed to 3006.x already: https://github.com/saltstack/salt/commit/ec3178f2007d513012fcb908b652f08cb658f94c. When merge to master is done usually?

2025-04-11 15:44 UTC, twangboy commented
First we'll get things merged to 3007.x... then merge forward from there to master

2026-03-17 22:08 UTC, twangboy commented
Please rebase and resolve conflicts

2026-03-18 22:10 UTC, merged