WIP - Generate a rebuild to test gitfs pillar
saltstack/salt pull request #66954
Opened 2024-10-09 19:33 UTC by dmurphy18

### What does this PR do?
Resolve cache refresh issue with git pillar

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/65467

### Previous Behavior
Pillar not updated with git pillar if '/' is part of the name when changes are made

### New Behavior
Pillar is updated with git pillar if '/' is part of the name when changes are made

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes
Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2025-02-05 22:08 UTC, twangboy approved these changes

2025-02-05 22:08 UTC, twangboy commented on salt/runners/git_pillar.py
> +    print(f"DGM runners git_pillar update, exit ret '{ret}'", flush=True)
Probably don't want that

2025-02-05 22:08 UTC, twangboy commented on salt/utils/gitfs.py
> +                )  # replace '/' with '-' to not cause trouble with file-system
We're using `_` above, why switch to `-` here?

2025-02-05 22:10 UTC, twangboy requested changes
A few changes / questions

2025-02-05 22:44 UTC, dmurphy18 commented on salt/runners/git_pillar.py
> +    print(f"DGM runners git_pillar update, exit ret '{ret}'", flush=True)
dang habit, thought I got them all, did a grep -R DGM, rats, it is gone

2025-02-05 22:47 UTC, dmurphy18 commented on salt/utils/gitfs.py
> +                )  # replace '/' with '-' to not cause trouble with file-system
This line used https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L3387 with gitfs, hence thought I'd do same, but could be underscore like https://github.com/saltstack/salt/blob/2b44a6ce9a9c387b08ff3abb2bb025c5acece112/salt/utils/gitfs.py#L483-L488 if you prefer

2025-02-10 20:59 UTC, twangboy approved these changes

2025-02-10 22:26 UTC, merged