Support limiting the number of states running in parallel
saltstack/salt pull request #66957
Opened 2024-10-10 19:37 UTC by lkubb

### What does this PR do?
Adds support for limiting the number of states executing in `parallel` via a new configuration called `state_max_parallel`.

This solution is a bit ugly, but alternative implementations proved hard to be implemented in a backwards-compatible way or came with performance concerns.

Based on https://github.com/saltstack/salt/pull/66956

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/49301

### Previous Behavior
No limit on the number of states running in parallel.

### New Behavior
States running in parallel can be limited via configuration.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2025-08-15 19:35 UTC, twangboy requested changes
Just a question about running these tests on Windows.

2025-08-15 19:35 UTC, twangboy commented on tests/pytests/functional/modules/state/test_parallel.py
> +@pytest.mark.skip_on_windows
Why is this skipped on Windows? Will Windows not honor the new `state_max_parallel` setting?

2025-08-15 20:17 UTC, lkubb commented on tests/pytests/functional/modules/state/test_parallel.py
> +@pytest.mark.skip_on_windows
Yes, it should honor it. The issue is that I'm using the `sleep`/`true` executables in the test, which (afair) are not available on Windows - please correct me if that's wrong. iirc the other `parallel` tests have the same limitation.

Unsure if there's a straightforward, cross-platform way of testing this.

2025-10-31 17:50 UTC, twangboy submitted a review, later dismissed

2025-10-31 17:50 UTC, twangboy commented on tests/pytests/functional/modules/state/test_parallel.py
> +@pytest.mark.skip_on_windows
On Windows you can use `timeout 5`

2025-11-03 10:48 UTC, lkubb commented on tests/pytests/functional/modules/state/test_parallel.py
> +@pytest.mark.skip_on_windows
Thanks for the pointer! (Somehow it just got published with your recent review)

Applied, let's hope it works on the Windows runners. :)

2025-11-13 21:38 UTC, twangboy approved these changes

2026-03-17 21:04 UTC, merged