Make file.symlink/_symlink_check() respect follow_symlinks
saltstack/salt pull request #66981
Opened 2024-10-18 10:31 UTC by tomdoherty

### What does this PR do?
See issue for details

### What issues does this PR fix or reference?
Fixes: #66980

### Previous Behavior
`_symlink_check()` always uses `os.path.exists` regardless of `follow_symlinks`

### New Behavior
`follow_symlinks=False` causes `os.path.lexists()` to be used.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-10-21 15:32 UTC, twangboy requested changes
Would you mind writing a test for this?

2024-10-22 12:45 UTC, tomdoherty commented
> Would you mind writing a test for this?

Done!

2024-10-25 22:14 UTC, twangboy approved these changes

2024-11-01 16:11 UTC, tomdoherty commented
@dwoz @twangboy any hints on getting this merged?

2024-11-01 17:09 UTC, twangboy commented
Our infra is broken right now... once we get it fixed, we'll have you rebase and let the tests run.

2025-03-06 10:07 UTC, tomdoherty commented
> Our infra is broken right now... once we get it fixed, we'll have you rebase and let the tests run.

I rebased this - are we in a position to merge now?

2025-03-14 16:05 UTC, dmurphy18 approved these changes

2025-03-16 21:06 UTC, dwoz commented
Should this be back ported to 3006.x?

2025-03-17 21:43 UTC, merged