Change repo.saltproject.io to new url
saltstack/salt pull request #67024
Opened 2024-10-31 15:54 UTC by twangboy

### What does this PR do?
This is a first attempt to change URLs from repo.saltproject.io to packages.broadcom.com. I'm not addressing any workflow stuff here.

2024-11-12 21:47 UTC, dmurphy18 requested changes
And fix lint

2024-11-12 21:47 UTC, dmurphy18 commented on tests/pytests/functional/modules/test_aptpkg.py
> +            "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ jammy main",
we are using salt.sources now , see https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html

2024-11-12 21:47 UTC, dmurphy18 commented on tests/pytests/functional/states/pkgrepo/test_debian.py
> +    repo_content = "deb [arch=amd64 signed-by={}] https://packages.broadcom.com/artifactory/saltproject-deb/ buster main".format(
se above https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html

2024-11-12 21:47 UTC, dmurphy18 commented on tests/pytests/pkg/download/test_pkg_download.py
> +            f"salt-master-{salt_release}",
for rpm it is :+1: 
salt-minion=3006.8

2024-11-12 21:47 UTC, dmurphy18 commented on tests/support/pkg.py
> +                    f"deb [signed-by={gpg_full_path} arch={arch}] "
salt.sources https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html

2024-11-12 21:47 UTC, dmurphy18 commented on tests/support/pkg.py
> +            mac_pkg_url = f"{root_url}/saltproject-generic/macos/{major_ver}/{mac_pkg}"
it is {major_ver}.{minor_ver}

2024-12-02 18:39 UTC, Akm0d submitted a review, later dismissed

2025-02-10 21:43 UTC, dmurphy18 approved these changes

2025-02-11 22:07 UTC, merged