Use relenv.fetch to download tarball
saltstack/salt pull request #67022
Opened 2024-10-30 17:03 UTC by Akm0d

### What does this PR do?

### What issues does this PR fix or reference?
Fixes #67010

### Previous Behavior
Used salt.utils.http to download salt onedir package from repo.saltproject.com

### New Behavior
Use `relenv.fetch` to download salt onedir package.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-11-06 14:27 UTC, twangboy approved these changes

2024-11-12 18:45 UTC, twangboy submitted a review, later dismissed

2025-06-26 22:18 UTC, dwoz commented
@Akm0d Can we get a changelog for this?

2025-06-27 19:30 UTC, twangboy requested changes
Could we get a changelog and a test for this, please?

2026-03-17 22:00 UTC, dwoz commented
My change will account for this: https://github.com/saltstack/salt/pull/68520

2026-03-17 22:00 UTC, closed without merging