Constrain the localfs cache to the cachedir
saltstack/salt pull request #67033
Opened 2024-11-04 11:30 UTC by lkubb

### What does this PR do?
Constrain the localfs cache module to its cachedir.

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/67031

### Previous Behavior
Operates on the whole filesystem when `bank` (or `key`) is prefixed with `os.sep`

### New Behavior
Only operates on subpaths of `cachedir`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

2024-11-06 16:40 UTC, twangboy requested changes
Looks like the pre-commit tests are failing. Once we get the CICD fixed, the others should pass.

2024-11-11 20:30 UTC, twangboy approved these changes

2025-02-11 21:08 UTC, twangboy approved these changes, later dismissed

2025-03-13 20:36 UTC, dmurphy18 approved these changes

2025-03-16 21:03 UTC, merged