Repair fstab_present test mode
saltstack/salt pull request #67066
Opened 2024-11-25 12:47 UTC by tacerus

Return no pending changes if the configuration already matches.

### What does this PR do?

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/67065

### Previous Behavior

Pending changes.

### New Behavior

No pending changes.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2025-02-12 16:48 UTC, twangboy requested changes
Please write a test for this

2025-02-12 18:07 UTC, twangboy submitted a review, later dismissed

2025-02-19 20:43 UTC, tacerus commented
Amended to update the two related non-Linux tests as well (as noted in https://github.com/openSUSE/salt/pull/702#pullrequestreview-2620500055).

2025-05-16 18:17 UTC, twangboy approved these changes

2025-06-26 00:17 UTC, merged