Fix nftables module check function doesn't understand that braces are optional
saltstack/salt pull request #67079
Opened 2024-11-29 20:52 UTC by nicholasmhughes

### What does this PR do?
See issue for details

### What issues does this PR fix or reference?
Fixes #67078

### Previous Behavior
See issue for details

### New Behavior
The braces are effectively ignored for comparison purposes

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-12-02 18:15 UTC, dmurphy18 reviewed
Should use f-strings at this point.
Can you email david-dm.murphy@broadcom.com to discuss salt extensions too, since this PR has your attention and reaching out to you has failed so far

2024-12-02 18:15 UTC, dmurphy18 commented on salt/modules/nftables.py
> +    cmd = "{} --handle list chain {} {} {}".format(
Could update this to use f-strings

2025-01-11 23:05 UTC, bdrx312 commented on salt/modules/nftables.py
> +    search_rule = f"{rule} #".replace("{ ", "{? ?").replace(" }", " ?}?")
I don't think we want to be in the business of trying to parse and maintain the syntax of nftables rules. I suggest trying to find a way to have the tools canonicalize both rules. `nft` also has a `--json` flag to give json output which may also be cleaner/safer to handle.

2025-01-11 23:17 UTC, bdrx312 commented on salt/modules/nftables.py
> +    found = re.search(search_rule, out)
We did not escape the search_rule before using it as a regex so regex special characters like `.` and `[` will not be treated as literal.

2025-01-11 23:27 UTC, bdrx312 commented on salt/modules/nftables.py
> +    search_rule = f"{rule} #".replace("{ ", "{? ?").replace(" }", " ?}?")
There are other things that would make the rules not normalized and therefore not match like extra whitespaces. Here is a list according to copilot:

> 
> Whitespace: Variations in spaces or tabs can impact rule formatting, although it generally doesn’t affect functionality.
> 
> Comments: Inline or separate comments within rules might not be present in the canonical form.
> 
> Ordering: The sequence of rules and attributes can differ.
> 
> Default actions: When default actions aren’t explicitly stated, different interpretations may arise.
> 
> Aliases: Using aliases for set names or interfaces may introduce variations.
> 
> Optional attributes: Omitting certain attributes might create differences.
> 
> Nesting: The manner and extent of nesting in expressions might vary.
>

2025-02-11 21:03 UTC, twangboy commented
@nicholasmhughes Could you address the comments from @bdrx312?

2025-07-01 19:16 UTC, twangboy requested changes
Please make this PR against the 3006.x branch as it is a bugfix there.

2025-08-28 14:40 UTC, twangboy commented
@nicholasmhughes I just rebased this on 3006.x. Just need you to address the comments from @bdrx312

2025-10-02 01:09 UTC, bdrx312 commented on salt/modules/nftables.py
> +    found = re.search(search_rule, out)
in other words should call `re.escape` on `search_rule`

2025-10-02 21:35 UTC, twangboy commented
@nicholasmhughes It looks like tests are passing. Could you address the comments from @bdrx312 ?

2025-10-03 20:06 UTC, bdrx312 commented on salt/modules/nftables.py
> +    search_rule = f"{rule} #".replace("{ ", "{? ?").replace(" }", " ?}?")
Instead of trying to normalize and and check the rule yourself, you could use the `--check` flag with `nft`.

2025-10-06 19:09 UTC, twangboy commented
@nicholasmhughes Thanks for rebasing. Could you address @bdrx312 questions?

2025-10-13 09:28 UTC, dwoz commented
@nicholasmhughes ping. Looking to see if this can land in the next release.

2025-12-09 20:21 UTC, twangboy commented on salt/modules/nftables.py
> +    cmd = f"{_nftables_cmd()} --handle list chain {nft_family} {table} {chain}"
The `--numeric` changes the output:
`--numeric` skips the lookup of IP addresses to symbolic hostnames
`--numeric --numeric` also shows port numbers
`--numeric --numeric --numeric` also shows protocols and UIDs/GUIDs
These can be substituted with `-n, -nn, -nnn`. So, I guess this would only affect the parsing of the results.

2025-12-09 20:22 UTC, twangboy commented
@nicholasmhughes Do you have some time to look at this?

2026-02-17 22:10 UTC, twangboy approved these changes

2026-02-17 22:56 UTC, merged