Fix issue preventing non-root salt master on Ubuntu
saltstack/salt pull request #67085
Opened 2024-12-03 17:22 UTC by Akm0d

### What does this PR do?
Fixes an issue preventing salt-master from running without root on Ubuntu.

### What issues does this PR fix or reference?
Fixes  #67083

### Previous Behavior
Running salt-master without root on Ubuntu resulted in an error during grains collection.

### New Behavior
salt-master is able to run without root.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2025-01-20 16:57 UTC, dnessett commented
I was wondering if there is an estimate when this fix might be merged into 3007.x?

2025-01-29 19:49 UTC, twangboy approved these changes

2025-02-06 22:30 UTC, dnessett commented
I'm a little confused. The bug report that motivated this PR, #67083, has been closed. And yet the PR has not passed the requirements necessary for integration into 3007.x. It may be (probably is) that I don't understand PR workflow. Is this PR still moving forward? I should also mention that this problem also arises in 3006.x, so I would hope that any fixes appearing in 3007.2 will be back ported to 3006.9. Is that the case?

2025-02-11 20:45 UTC, twangboy requested changes
Could you create a test for this?
Also, would you mind rebasing this on 3006.x?

2025-03-13 20:30 UTC, dmurphy18 commented
@Akm0d rebae to 2006.x and add tests or close this if not interested in it anymore

2025-05-03 03:49 UTC, dwoz commented
@Akm0d re-open this if you want to get it across the finish line.

2025-05-03 03:49 UTC, closed without merging

2025-05-03 16:28 UTC, dnessett commented
I am spending all of my Salt development time another bug [#65265](https://github.com/saltstack/salt/issues/65265). I didn't submit a bug report issue for this problem, because I thought it was going to be fixed by this PR. Now that it is closed, should I submit a new bug report issue for the same problem? It doesn't appear @Akm0d is paying any attention to this.