throw a TypeError when trying to merge a list with a mapping when `me…
saltstack/salt pull request #67093
Opened 2024-12-11 11:03 UTC by tomdoherty

…rge_lists=True`

### What does this PR do?

### What issues does this PR fix or reference?
Fixes #67092 

### Previous Behavior
Silently drops values

### New Behavior
Throws TypeError

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-12-12 11:35 UTC, lkubb commented
I don't think this is the correct (default) behavior since this function intends to emulate `dict.update`. This also happens for nested dicts, where a non-dict value overwrites the whole nested dict as well. If you want to enforce the same structure for both dicts, I would consider adding a `strict` switch or a separate function that enforces this.

Note that this should go into 3008 since it's either breaking compatibility or, if going with `strict`, introducing new functionality.

2025-02-11 22:14 UTC, twangboy requested changes
Please rebase this on the master branch.

2025-03-06 09:40 UTC, tomdoherty commented
> Please rebase this on the master branch.

done. thanks for looking!

2025-03-06 10:11 UTC, tomdoherty commented
> I don't think this is the correct (default) behavior since this function intends to emulate `dict.update`. This also happens for nested dicts, where a non-dict value overwrites the whole nested dict. If you want to enforce the same structure for both dicts, I would consider adding a `strict` switch or a separate function that enforces this.
> 
> Note that this should target 3008 since it's either breaking compatibility (a lot) or, if going with `strict`, introducing new functionality.

thanks for the review. I took your advice and added `strict`

2025-05-16 16:11 UTC, twangboy approved these changes, later dismissed

2025-05-20 13:32 UTC, twangboy commented
Looks like we got some pre-commit failures a long with other test failures

2026-01-28 22:15 UTC, merged