[3006.x] systemd_service: remove caching of 'systemctl status' to fix automatic daemon-reload for repeated invocations
saltstack/salt pull request #67116
Opened 2024-12-20 15:34 UTC by hurzhurz

### What does this PR do?
Removes the caching of the `systemctl status` and unit-change-check result in `__context__`.

While the caching could help to avoid a few multiple unnecessary invocations of `systemctl status`, it also can cause problems when there are multiple subsequent operations an a service when running a state.apply.

See issue for details.

### What issues does this PR fix or reference?
Fixes #66864

2025-01-30 16:22 UTC, twangboy requested changes
Hey, this looks great. Could we get some tests for this?

2025-01-31 17:13 UTC, hurzhurz commented
> Hey, this looks great. Could we get some tests for this?

Well, I was not sure how to do this for this issue, but ok, I gave it a try.
Could you have a look and let me know if it is ok? Or maybe give me some hints?

2025-02-11 21:13 UTC, twangboy approved these changes

2025-03-06 20:50 UTC, dmurphy18 approved these changes

2025-03-08 03:09 UTC, merged