[3006.x] module.run: fix result detection from returned dict
saltstack/salt pull request #67115
Opened 2024-12-20 11:24 UTC by hurzhurz

### What does this PR do?
Fixes #65842 Module.run state returns invalid result when method returns a dict

module.run should also check for a key `result` in the return of the executed module to determin if it was successful.
But this only works for the legacy- and not the new-style.

This is because in the new-style, the `_get_result` function is always executed with a actually empty dict as the `changes` parameter, where it searches for the `result` key.

Also this `changes` parameter is not necessary as even, in the case of the legacy-style, it is effectively just a copy of the `func_ret` parameter.

2025-01-11 22:48 UTC, bdrx312 requested changes

2025-01-11 22:48 UTC, bdrx312 commented on salt/states/module.py
> +        elif func_ret.get("retcode", 0) != 0:
This case is already handled on line 699 https://github.com/saltstack/salt/blob/1c23b3dca1c03f374e9024d2aae303cafdb69fba/salt/states/module.py#L669

2025-01-11 22:48 UTC, bdrx312 commented on salt/states/module.py
> +    elif isinstance(func_ret, dict):
There is no longer an else case for when `func_ret` is not a `bool` nor a `dict`, the return will be `True`. The `func_ret` not being a `bool` nor `dict` is unexpected so should throw an exception or at least return `False`. Also we are checking `isinstance(func_ret, dict)` multiple times (also on line 669). We should just check once and have the `func_ret.get("retcode", 0) != 0` check be inside it.

2025-01-14 19:48 UTC, hurzhurz commented on salt/states/module.py
> +    elif isinstance(func_ret, dict):
There was not really a plain else case before, as the `else` had the `if isinstance(changes_ret, dict)` inside which itself had no else case.
And I think it is ok or even wanted to have it return `True` in such cases: Not every execution module function does give a clear successful/unsuccessful indication.

2025-01-14 19:49 UTC, hurzhurz commented on salt/states/module.py
> +        elif func_ret.get("retcode", 0) != 0:
You are right, I missed that while changing it from `changes_ret` to `func_ret`. I will edit that!

2025-01-14 23:27 UTC, bdrx312 commented on salt/states/module.py
> +    elif isinstance(func_ret, dict):
> Not every execution module function does give a clear successful/unsuccessful indication.
In that case I would expect `func_ret` to be `None` which I recommend we handle in the way you deem correct, but an unexpected data type should either return the truth/`bool` value of it self (i.e. `bool(func_ret)` so empty list `[]` is False and list with value is True) or should throw an exception because we are getting an unexpected value. We should not do the worst case though of returning `True` that function was successful it wasn't and returned a bad value.

2025-01-14 23:43 UTC, bdrx312 commented on salt/states/module.py
> +        # if return key exists and is is boolean, return that as the result
typo `is is`

2025-01-14 23:43 UTC, bdrx312 commented on salt/states/module.py
> +            res = func_ret.get("result", {})
Since we determined the result is already in the dict, I recommend using `[]` instead of `get`. Also we don't use the default `{}` value on line 674 so I recommend using None instead:

```python
if isinstance(func_ret.get("result"), bool):
    res = func_ret["result"]
```

alternatively we can use the newer python `:=` assignment operator:

```python
if isinstance(bool_res := func_ret.get("result"), bool):
    res = bool_res
```

2025-01-15 14:47 UTC, hurzhurz commented on salt/states/module.py
> +    elif isinstance(func_ret, dict):
Well, there seems to be no hard standard for the return of execution modules. Unlike state modules.
Returning `None` or `[]` could simply mean that it had nothing to do.
For example `saltutil.sync_modules` does return a list of synced modules. But if there was nothing to sync, the list is empty, which is totally fine and actually a success.

However, there are some typical ways how some module functions indicate the succession: By a returning a bool or by dict keys `result` or `retcode`. Everything else would be a guess.
Using module.run is just some kind of a workaround anyway. If a proper determination of the result is needed, one should look for a state module or make one.

Also this PR is just meant to fix the limited (and often sufficient) way the function already had to determine the succession. Not to redesign it.

2025-01-15 14:47 UTC, hurzhurz commented on salt/states/module.py
> +            res = func_ret.get("result", {})
> Since we determined the result is already in the dict, I recommend using `[]` instead of `get`. Also we don't use the default `{}` value on line 674 so I recommend using None instead:
> 
> ```python
> if isinstance(func_ret.get("result"), bool):
>     res = func_ret["result"]
> ```

I actually thought about that, but I didn't want to start refactoring the whole module.
And I just moved those lines and did not create or edit them.

> alternatively we can use the newer python `:=` assignment operator:
> 
> ```python
> if isinstance(bool_res := func_ret.get("result"), bool):
>     res = bool_res
> ```

While I think the assignment operator is pretty neat, I think it is better to not use it here.
Salt is sometimes still used with somewhat old python versions that don't support it yet. For example if you use salt-ssh, you need to rely on the python installation that already exists on the system.

2025-01-15 23:56 UTC, bdrx312 approved these changes

2025-01-29 20:04 UTC, twangboy submitted a review, later dismissed

2025-02-20 10:02 UTC, dwoz approved these changes, later dismissed

2025-02-20 10:02 UTC, dwoz commented on tests/unit/states/test_module.py
> +    def test_module_run_ret_result(self):
Ideally this file would be migrated to `tests/pytests/`.

2025-03-26 18:14 UTC, twangboy commented
Could you migrate that test to pytest?

2025-03-28 08:37 UTC, SndR85 commented
@hurzhurz To move the pytest change to your PR, can I have write access to your repository? I also have included the change I mentioned earlier.

2025-03-28 10:06 UTC, hurzhurz commented
@SndR85 ok, I have added/invited you as a collaborator

I probably won't have time to work on it myself until sometime next week.

@twangboy Just the new test or necessarily the whole file, like @dwoz suggested?

2025-03-28 14:35 UTC, twangboy commented
Yeah, you need to move the whole file and convert it to pytest.

2025-03-28 14:43 UTC, SndR85 commented
> Yeah, you need to move the whole file and convert it to pytest.

Alright, it's going to take some time, but I will look into it.

2025-03-28 18:46 UTC, hurzhurz commented
> Yeah, you need to move the whole file and convert it to pytest.

I didn't expect this as a requirement for a simple fix-PR, but ok.

@SndR85 I can look into it next week as well

2025-03-30 18:22 UTC, SndR85 commented
I have literally migrated the whole file over to pytest, with some modifications. I have keep the same author because it's still created by Nicole Thomas.

2025-03-31 13:13 UTC, twangboy approved these changes

2025-04-23 04:17 UTC, merged